### ISSUE TITLE
mingw-w64-gimp 2.9.2 doesn't contain a gimp.exe

### ISSUE THREAD

**Issue by mingwandroid** [Alexpux/MINGW-packages#1005]
As per title.

**Comment by DavidEGrayson** [comment]
I suspect that gimp.exe missing is related to the fact that GIMP 2.9.2 is an unstable release (because the middle number is odd).  I talked about this in issue #1022 and I proposed that we downgrade to 2.8.16.  Would a pull request like that be acceptable?

**Comment by Alexpux** [comment]
Downgrade is not good. I will create "gimp.exe" in current package.

**Comment by Alexpux** [comment]
I'm upload new package with "gimp.exe"
