### ISSUE TITLE
autoreconf command not found

### ISSUE THREAD

**Issue by TwentyOneSolutions** [Alexpux/MINGW-packages#1010]
I'm trying to run the package that builds postgresql.  I installed the dependencies 

    $ pacman -S mingw-w64-x86_64-python2
    $ pacman -S mingw-w64-x86_64-libxml2
    $ pacman -S mingw-w64-x86_64-libxslt
    $ pacman -S winpty-git
    $ pacman -S patch

but now I'm getting an error:

    Admin@Works12 MINGW64 ~/MINGW-packages/mingw-w64-postgresql
      $ makepkg-mingw
      ==> Making package: mingw-w64-x86_64-postgresql 9.4.4-2 (Mon, Jan 18, 2016  6:08:31 PM)
      ==> Checking runtime dependencies...
      ==> Checking buildtime dependencies...
      ==> Retrieving sources...
        -> Found postgresql-9.4.4.tar.bz2
        -> Found postgresql-9.4.1-mingw-link.patch
        -> Found postgresql-9.4.1-pl-perl.patch
        -> Found postgresql-9.4.1-pl-python.patch
        -> Found postgresql-9.4.1-pl-tcl.patch
        -> Found postgresql-9.4.1-mingw-enable-readline.patch
      ==> Validating source files with md5sums...
          postgresql-9.4.4.tar.bz2 ... Passed
          postgresql-9.4.1-mingw-link.patch ... Passed
          postgresql-9.4.1-pl-perl.patch ... Passed
          postgresql-9.4.1-pl-python.patch ... Passed
          postgresql-9.4.1-pl-tcl.patch ... Passed
          postgresql-9.4.1-mingw-enable-readline.patch ... Passed
      ==> Extracting sources...
        -> Extracting postgresql-9.4.4.tar.bz2 with bsdtar
      ==> Starting prepare()...
      patching file src/Makefile.shlib
      patching file src/backend/Makefile
      patching file src/pl/plperl/GNUmakefile
      patching file src/pl/plpython/Makefile
      patching file src/pl/tcl/Makefile
      /home/Admin/MINGW-packages/mingw-w64-postgresql/PKGBUILD: line 47: autoreconf: command not found
      ==> ERROR: A failure occurred in prepare().
          Aborting...

And I can't figure out where to get `autoreconf` from?  Thank you.

**Comment by mingwandroid** [comment]
`pacman -S base-devel`

**Comment by TwentyOneSolutions** [comment]
Thank you!

Where is this documented?  Where can I find the full names and descriptions of the available packages?

**Comment by DavidEGrayson** [comment]
It's documented here, but I certainly didn't see it:


You can run `pacman -Ss` to see named and descriptions of available packages.  You can also look in this repository and AlexPux/MSYS2-packages to see all the build scripts.

**Comment by TwentyOneSolutions** [comment]
Great, thanks!

**Comment by xiaoyifang** [comment]
pacman -S autoconf-wrapper

**Comment by MuhammadTaseen** [comment]
Thank you it resolve my issue :)
