### ISSUE TITLE
Duplicate short option in help text of astyle

### ISSUE THREAD

**Issue by FrankHB** [Alexpux/MINGW-packages#1011]
```
pacman -S --needed mingw-w64-x86_64-astyle
astyle --help | grep xd
```

shows

```
    --pad-first-paren-out  OR  -xd
    --delete-empty-lines  OR  -xd
```

The official document [here](http://astyle.sourceforge.net/astyle.html) is correct.
I suspect it is an upstream issue, though not sure. Perhaps easy to work around here, so reported.

**Comment by FrankHB** [comment]
Is this fixed?

**Comment by Alexpux** [comment]
@FrankHB  if it is not fixed - report upstream. This is not our issue
