### ISSUE TITLE
Rust package broken

### ISSUE THREAD

**Issue by jhasse** [Alexpux/MINGW-packages#1016]
I've installed the Rust package in a fresh MinGW install. Cargo, Rust's package manager, is missing and I can't run `rustc`:

```
jhasse MINGW64 ~
$ rustc --version
C:/msys64/mingw64/bin/rustc.exe: error while loading shared libraries: rustc_driver-e9599659.dll: cannot open shared object file: No such file or directory
```

I restarted the shell, which resulted in no output:

```
jhasse MINGW64 ~
$ rustc --version

jhasse MINGW64 ~
$
```

**Comment by henryborchers** [comment]
rustc works for me.

**Comment by univerio** [comment]
For me, rustc was missing zlib and libffi. I also had a `?` in place of the dll name, but I discovered that if you run rustc in `cmd.exe` a GUI dialog pops up with the name.

**Comment by Gheoan** [comment]
This is fixed by https://github.com/Alexpux/MINGW-packages/issues/1825.
