### ISSUE TITLE
No cc.exe in mingw-w64-i686-gcc and mingw-w64-x86_64-gcc 5.3.0-1

### ISSUE THREAD

**Issue by ian-abbott** [Alexpux/MINGW-packages#1030]
Several `Makefiles` in the wild assume the C compiler is called `cc` and use that explicitly instead of `$(CC)`. The current mingw-w64-i686-gcc and mingw-w64-x86_64-gcc packages do not include a `/mingw{32|64}/bin/cc.exe`. This means `make` might not find `cc`, or might find the one from the msys2 gcc package (leading to a runtime dependency on `msys-2.0.dll`).

Would it be possible to install the gcc frontend as both gcc and cc?

**Comment by BrisingrAerowing** [comment]
AFAIK those makefiles are considered incorrect as the user should be able to specify the compiler. They probably should be patched to use $(CC) instead of directly calling the cc executable.

Assumptions in programming pretty much always end in utter failure.

**Comment by elieux** [comment]
See #1034.

**Comment by ian-abbott** [comment]
The suggestion of patching makefiles to use `$(CC)`, while a good one (if slightly bothersome), is not sufficient by itself, because the default value of the `CC` variable in the `make` package is `cc`.

**Comment by elieux** [comment]
New packages including `cc.exe` are uploaded.
