### ISSUE TITLE
Segfault in boost::context on x86_64 platform

### ISSUE THREAD

**Issue by twlostow** [Alexpux/MINGW-packages#1032]
Boost::context 1.60 crashes due to a bug in assembly code for the x86_64 architecture. 

Full bug report & a patch filed on Boost bug tracker. Would it be possible to add the patched version to MSYS2 packages?

https://svn.boost.org/trac/boost/ticket/11946

Best Regards,
Tom

**Comment by mingwandroid** [comment]
Great work Tom! Can I ask that you make a pull request for it yourself? If not no problem, I expect someone in MSYS2 will, but I personally don't have time at present.

Thanks very much for your contribution.

**Comment by Alexpux** [comment]
New package uploaded.

**Comment by twlostow** [comment]
Thanks a lot Aleksey!

Cheers,
Tom

2016-02-03 13:42 GMT+01:00 Алексей <notifications@github.com>:
