### ISSUE TITLE
Not exactly an issue...

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#1036]
More of a question.

I have ported the Gnome's dconf configuration system to MinGW (with the help of a patch from Cygwin to enable libtool usage) and I was wondering if you guys would like the patches I used for it.

The SHM tests don't run as they dynamically load a reference to the pwrite function, but I could easily just have that function just provided in line on MinGW using some sources from GnuLib (what is the correct capitalization for that project, anyways?).

The porting didn't take too long, actually. The hardest part was replacing the flock-based locking system, but I got it working after some Googling.

I still have the patched sources, but I am going to redo the patches and clean them up some before actually creating patch files.

**Comment by BrisingrAerowing** [comment]
I forgot to mention that I added support for setting the paths used by dconf with environment variables, and I am going to add relocation support using pathtools in the new patched sources.

It may be a while before I get to this, as I am currently doing a full rebuild starting with the base toolchain as part 1. DConf will be in part 4, so I still have a ways to go (part 2 has Python, Ruby, Perl, Lua and their dependencies, and part 3 does gobject-introspection and PyGobject and their dependencies)

**Comment by elieux** [comment]
I think that would be nice, ideally in the form of a pull request.
