### ISSUE TITLE
Package requests

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#1037]
[Net-SNMP](http://www.net-snmp.org/)

[BIND DNS Server](https://www.isc.org/)  (Site is rather weird, if you don't go through the main page nothing else will load. Just go to Software > BIND to get to the information page. A download button is on the left side.)

**Comment by Alexpux** [comment]
Well, the better way if you create PKGBUILD yourself instead asking us to do it. We have lot of other work.

**Comment by BrisingrAerowing** [comment]
I'll look into it and see what I can come up with. I will have to actually get to building them first (it may be a while, though. I am having fun with the Ruby build goofing up thanks to it trying to use MSYS2 paths as Win32 paths. I got this fixed before with all sorts of symlinks and stuff, and it is a mess.

**Comment by lazka** [comment]
@BrisingrAerowing what's the status here? Do you still plan on working on this, or can this be closed?

**Comment by BrisingrAerowing** [comment]
I am no longer using this project.

**Comment by lazka** [comment]
@BrisingrAerowing thanks for the update
