### ISSUE TITLE
latest fossil package does not include exe binary

### ISSUE THREAD

**Issue by fracting** [Alexpux/MINGW-packages#1055]
Detected by our CI server, it was weird that the fossil command is not found even after install the fossil package.

Take a look at the msys repo, I found the size of latest fossil package is unnatural small:

mingw-w64-i686-fossil-1.33-2-any.pkg.tar.xz        30-Jun-2015 10:21              537840
mingw-w64-i686-fossil-1.33-2-any.pkg.tar.xz.sig    30-Jun-2015 10:21                  96
mingw-w64-i686-fossil-1.35-1-any.pkg.tar.xz        27-Jan-2016 10:20                9216
mingw-w64-i686-fossil-1.35-1-any.pkg.tar.xz.sig    27-Jan-2016 10:20                  96

I download the package and manually unpack, confirm the 1.35 version does not contain any exe files.

**Comment by elieux** [comment]
See #1054 and #1027.

**Comment by elieux** [comment]
Fixed packages uploaded. Beware that the new packages are version `1.34-1`.

**Comment by fracting** [comment]
Thanks, I can confirm that latest fossil package works on Windows.

Unfortunately it doesn't work on Wine, I've reported a bug to Wine, here is a cross-reference, please ignore if you are not interesting in Wine, sorry for the noise:

https://bugs.wine-staging.com/show_bug.cgi?id=646

**Comment by fracting** [comment]
@elieux Do you know where is the macro access defined?

#ifndef _WIN32
  if( access(zHome, W_OK) ){
    fossil_fatal("home directory %s must be writeable", zHome);
  }
#endif

I know fossil calls AccessCheck in some way but I couldn't find where.

Thanks!

**Comment by fracting** [comment]
Update:

I've fixed the Wine bug uncovered by fossil, patch sent to WineHQ, should be merged before next release.

http://source.winehq.org/patches/data/119240
http://source.winehq.org/patches/data/119241

**Comment by fracting** [comment]
Update:

I've upgrade docker image used in wine-ci.org, with Wine Staging 1.9.4 installed, which has the fix for fossil.

fossil starts to work now: http://wine-ci.org/Alexpux/MINGW-packages/127

**Comment by elieux** [comment]
Do you still need the answer to https://github.com/Alexpux/MINGW-packages/issues/1055#issuecomment-183162778 ("11 days ago", oops)?

**Comment by fracting** [comment]
No, thanks, I figured out by myself later, see my comment in Wine Staging bugzilla:

```
fossil-src-1.34/src/winfile.c
218   AccessCheck(pSd, hToken, desiredAccess, &genMap, 0,
219                    &privSetSize, &grantedAccess, &accessYesNo);
220   /*
221    * Should have failed with ERROR_INSUFFICIENT_BUFFER
222    */
```
