### ISSUE TITLE
OpenImageIO UTF-8 support

### ISSUE THREAD

**Issue by MrKepzie** [Alexpux/MINGW-packages#1061]
Currently patches for OpenImageIO breaks UTF-8 support on MingW, read the following issue for more info:

https://github.com/OpenImageIO/oiio/issues/1349

A patch has been proposed at https://github.com/MrKepzie/Natron/blob/workshop/tools/Windows/include/patches/OpenImageIO/oiio-1.5.23-mingw-UTF8iostream.patch

**Comment by lazka** [comment]
Looks like this was fixed upstream in 1.7.2 and the msys2 version is currently at 1.7.12. Is this still an issue?

**Comment by MrKepzie** [comment]
My pull request to OpenImageIO was merged so it's no longer an issue.
