### ISSUE TITLE
openssl v1.0.2e does not exist on openssl server anymore, makepkg-mingw fails

### ISSUE THREAD

**Issue by withmorten** [Alexpux/MINGW-packages#1071]
openssl's newest version is 1.0.2f and it seems with that release they removed their old 1.0.2e release from the server.

morten@larch MINGW32 ~/software/mingw-packages/mingw-w64-openssl
$ makepkg-mingw
==> Making package: mingw-w64-openssl 1.0.2.e-1 (Sun Feb 14 01:31:02 CET 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading openssl-1.0.2e.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading http://www.openssl.org/source/openssl-1.0.2e.tar.gz
    Aborting...

Changing the PKGBUILD file to 1.0.2f and starting makepkg-mingw with --skippgpcheck --skipchecksums seems to work so far.

**Comment by elieux** [comment]
Thanks for your report. The package has been updated to v1.0.2g since this ticket was filed, so I'm closing it now.
