### ISSUE TITLE
Add `git` to makedepends for multiple `-git` packages

### ISSUE THREAD

**Issue by fracting** [Alexpux/MINGW-packages#1090]
For example gcc-git, detected by https://ci.appveyor.com/project/Alexpux/mingw-packages/build/1.0.38

```
[MSYS2 CI] mingw-w64-gcc-git: Installing dependencies

==> Making package: mingw-w64-x86_64-gcc-git r144783.9a0f46c-1 (Mon, Feb 22, 2016  9:56:50 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning gcc git repo...
==> ERROR: Cannot find the /usr/bin/git binary required for makepkg.

[MSYS2 CI] FAILURE: mingw-w64-gcc-git: Installing dependencies failed.
```

Our Drone CI has msys2 git pre-installed in docker image fracting/msys32, so it didn't detect this error.

Not a hard job, if anyone is going to work on it that would be nice, other wise I might be back few weeks later.

**Comment by elieux** [comment]
I had a script for detecting that somewhere. If you ping me in the evening, I'll look for it.

**Comment by mingwandroid** [comment]
Are you taking a break?
