### ISSUE TITLE
Build of package mingw-w64-sqlite3 broken

### ISSUE THREAD

**Issue by diracsbracket** [Alexpux/MINGW-packages#1093]
I get the following error when building package mingw-w64-sqlite3 in MSYS2:

```
x86_64-w64-mingw32-gcc.exe: fatal error: no input files
compilation terminated.
Makefile:532: recipe for target 'sqlite3.lo' failed
make: *** [sqlite3.lo] Error 1
make: *** Waiting for unfinished jobs....
mv -f .deps/sqlite3-shell.Tpo .deps/sqlite3-shell.Po
mv -f .deps/sqlite3.Tpo .deps/sqlite3.Po
mv -f .deps/sqlite3-sqlite3.Tpo .deps/sqlite3-sqlite3.Po
==> ERROR: A failure occurred in build().
    Aborting...
```
Any ideas why this fails?

The build using Visual Studio 2015 succeeds using:
```
MINGW-packages\mingw-w64-sqlite3\src\sqlite-autoconf-3110000>nmake /f Makefile.msc
```
Thanks!

**Comment by fracting** [comment]
Hi @diracsbracket 

Two days ago I just built sqlite3 on Drone CI and it worked: http://wine-ci.org/fracting/MINGW-packages/30

Sorry I don't know what's wrong as well. Note that the CI has a 32bit msys2 installed while you are using 64bit, but this might not be related.

I hope someone else has idea.

(I also have another example where package builds fine on CI server but fails on local machine, see https://github.com/Alexpux/MINGW-packages/issues/1100, but it could be totally not related)

**Comment by fracting** [comment]
@diracsbracket btw, could you show your full command line for building your package? Also it would be great if you can upload full build log.

**Comment by ian-abbott** [comment]
FWIW, it built fine on my machine, using a 64-bit MSYS2, and from any of the three shell environments: MSYS2 Shell, MinGW-w64 Win32 Shell, and MinGW-w64 Win64 Shell.

**Comment by elieux** [comment]
Since there's no response from OP and the package builds fine for other people, I'm closing this ticket. If the issue persists, add a comment.
