### ISSUE TITLE
Are issues filed against the official repo being followed?

### ISSUE THREAD

**Issue by mkae** [Alexpux/MINGW-packages#1106]
Alexey, there's also an issue tracker on
https://github.com/msys2/MINGW-packages and I am not sure on which I should file new issues, since you're obviously more active here. :-)

**Comment by Alexpux** [comment]
msys2 is just our rsync. Went still start using it. Right now you need post issues in my repos.

**Comment by mkae** [comment]
There are quite a few issues on the other issue tracker...
For me as a new user it wasn't obvious, that I should file my issues rather here on your one.
Perhaps it would be advisable to disable the other repo's issue tracker and rather forward potential issues filers to here?
There existing issues would need relocation to here.
