### ISSUE TITLE
ffmpeg is broken

### ISSUE THREAD

**Issue by henryborchers** [Alexpux/MINGW-packages#1111]
When installing with pacman I get:

    c:/tools/msys64/mingw64/bin/ffmpeg.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

When I try makepkg-mingw, I get:

    ffmpeg-3.0.tar.bz2 ... FAILED (unknown public key B4322F04D67658D8)
    ==> ERROR: One or more PGP signatures could not be verified!"

Even with a fresh install of msys2, I still have this problem. This used to work perfectly. What did I do wrong?

**Comment by henryborchers** [comment]
I don't know if this affects anything but I did another fresh install of msys2 and the pacman package just gave me a different message now after installing ffmpeg:

    C:/msys64/mingw64/bin/ffmpeg.exe: error while loading shared libraries: swscale-3.dll: cannot open shared object file: No such file or directory

**Comment by kokutoukiritsugu** [comment]
use depends x64 check x264.exe.
x264.exe it depends libx264-**146**.dll
but in msys64\mingw64\bin floder only has libx264-**148**.dll
mayby its a packing error.

**Comment by Alexpux** [comment]
seems this is x264 build issue and during build x264 linked with already installed libx264 instead newly builded.

**Comment by henryborchers** [comment]
yeah, I'm getting that. it looks like it's looking for libx264-146.dll when I have libx264-148.dll.

I'm also noticing that even a hello world program in g++ is segfaulting. Is this related?

**Comment by Alexpux** [comment]
g++ segfaulting fixed. Update packages.

**Comment by henryborchers** [comment]
Yay!!!! g++ is working again! Now all I need if ffmpeg up an running again.

**Comment by henryborchers** [comment]
Is this a problem that I can get working on my end or should I just wait for the next push?

**Comment by Alexpux** [comment]
i can't see it until monday

**Comment by henryborchers** [comment]
Thank you a million!

**Comment by henryborchers** [comment]
I'm happy with the amazing work you've done on this project. Before discovering this, my research used to take so much more time. However, having a broken version of ffmpeg is preventing me from moving forward. If it is going to take some time to fix, is it possible for me to roll back to a working version?

**Comment by chhe** [comment]
What's breaking `ffmpeg` right now are the new versions of `x264` and `x265`. The current build of `ffmpeg` needs `libx264-146.dll` which is not provided anymore. Instead a newer version (`libx264-148.dll`) is provided. Same for `x265`. So by rolling back to an older version of `x264` and `x265` you can use the current `ffmpeg` again.

You can use `pacman -U` and old versions of `x264` and `x265` which may be still present in your `pacman`cache directory (`/var/cache/pacman/pkg/`) to downgrade.

**Comment by henryborchers** [comment]
Thanks for this explanation. I'll give it a try when I get home. 

Out of curiosity, does this mean that ffmpeg needs to update their code to link to the new version of x264 and x265?

**Comment by chhe** [comment]
@henryborchers Right now this has nothing to do with `ffmpeg`.  It should work fine with newer versions of `x264` and `x265`. @Alexpux will need to make a new build of `ffmpeg` which links against these.

**Comment by henryborchers** [comment]
Thanks again for the explanation @chhe! I had a similar issue when I tried to build it myself.

**Comment by Alexpux** [comment]
Have problem with building 32-bit ffmpeg 3.0. Need fix detecting openjpeg (maybe remove OPJ_STATIC)

**Comment by Alexpux** [comment]
New packages uploaded
