### ISSUE TITLE
KF5 on MSYS2 needs update

### ISSUE THREAD

**Issue by mkae** [Alexpux/MINGW-packages#1112]

**Comment by Alexpux** [comment]
Guys, don't post such issue. If you think that something need to be updated - create pull requests with changes and we will review.

**Comment by mkae** [comment]
Great to see KF5 on MSYS2 already!
Cool stuff!!

The version 5.12 is rather old. Are there showstoppers for updating this to KF5's current version?

By the way I noticed that many framework packages (still) contained invalid package descriptions! This rather fresh merge of mingwandroid seems to have done copy-pasted a lot and is not yet fully polished.

Looking forward to give this a test ride. :-)

**Comment by mkae** [comment]
Sorry, Alexey, as you see above, I didn't mean to commit an empty issue.
But okay, I see where you're coming from. Will address this directly to mingwandroid.
Sorry again for the noise.
