### ISSUE TITLE
mingw-w64-gcc 5.3.0 fails to build

### ISSUE THREAD

**Issue by ulin0208** [Alexpux/MINGW-packages#1121]
make[3]: Entering directory '/d/cpp/MINGW-packages/mingw-w64-gcc/src/build-x86_64-w64-mingw32/x86_64-w64-mingw32/libstdc++-v3/include'
Makefile:1423: recipe for target 'stamp-bits-sup' failed
make[3]: [stamp-bits-sup] Error 1 (ignored)
echo timestamp > stamp-pb
echo timestamp > stamp-host
echo 0 > stamp-namespace-version
echo 0 > stamp-visibility
echo 1 > stamp-extern-template
echo 1 > stamp-dual-abi
echo 1 > stamp-cxx11-abi
sed -e '/^#pragma/b' \
    -e '/^#/s/\([ABCDEFGHIJKLMNOPQRSTUVWXYZ_][ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*\)/_GLIBCXX_\1/g' \
    -e 's/_GLIBCXX_SUPPORTS_WEAK/__GXX_WEAK__/g' \
    -e 's/_GLIBCXX___MINGW32_GLIBCXX___/__MINGW32__/g' \
    -e 's,^#include "\(.*\)",#include <bits/\1>,g' \
    < /d/cpp/MINGW-packages/mingw-w64-gcc/src/gcc-5.3.0/libstdc++-v3/../libgcc/gthr.h > x86_64-w64-mingw32/bits/gthr.h
sed -e 's/\(UNUSED\)/_GLIBCXX_\1/g' \
    -e 's/\(GCC[ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*_H\)/_GLIBCXX_\1/g' \
    < /d/cpp/MINGW-packages/mingw-w64-gcc/src/gcc-5.3.0/libstdc++-v3/../libgcc/gthr-single.h > x86_64-w64-mingw32/bits/gthr-single.h
sed -e 's/\(UNUSED\)/_GLIBCXX_\1/g' \
    -e 's/\(GCC[ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*_H\)/_GLIBCXX_\1/g' \
    -e 's/SUPPORTS_WEAK/__GXX_WEAK__/g' \
    -e 's/\([ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*USE_WEAK\)/_GLIBCXX_\1/g' \
    < /d/cpp/MINGW-packages/mingw-w64-gcc/src/gcc-5.3.0/libstdc++-v3/../libgcc/gthr-posix.h > x86_64-w64-mingw32/bits/gthr-posix.h
sed -e 's/\(UNUSED\)/_GLIBCXX_\1/g' \
    -e 's/\(GCC[ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*_H\)/_GLIBCXX_\1/g' \
    -e 's/SUPPORTS_WEAK/__GXX_WEAK__/g' \
    -e 's/\([ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*USE_WEAK\)/_GLIBCXX_\1/g' \
    -e 's,^#include "\(.*\)",#include <bits/\1>,g' \
    < /d/cpp/MINGW-packages/mingw-w64-gcc/src/gcc-5.3.0/libstdc++-v3/../libgcc/gthr-posix.h > x86_64-w64-mingw32/bits/gthr-default.h
make[3]: Leaving directory '/d/cpp/MINGW-packages/mingw-w64-gcc/src/build-x86_64-w64-mingw32/x86_64-w64-mingw32/libstdc++-v3/include'
make[2]: Leaving directory '/d/cpp/MINGW-packages/mingw-w64-gcc/src/build-x86_64-w64-mingw32'
Makefile:20162: recipe for target 'stage2-bubble' failed
make[1]: *** [stage2-bubble] Error 2
make[1]: Leaving directory '/d/cpp/MINGW-packages/mingw-w64-gcc/src/build-x86_64-w64-mingw32'
Makefile:906: recipe for target 'all' failed
make: *** [all] Error 2
make: INTERNAL: Exiting with 5 jobserver tokens available; should be 9!

I used the latest msys2 to build mingw-w64-gcc and got this error. 
Could anyone tell me why? Thanks

**Comment by Alexpux** [comment]
Error itself is not present here. You can find real error earlier in the logs

**Comment by ulin0208** [comment]
f951.exe: Fatal Error: Reading module 'openacc_kinds' at line 55 column 72: Unexpected EOF
compilation terminated.
Makefile:640: recipe for target 'openacc.lo' failed
make[5]: *** [openacc.lo] Error 1

Maybe it's the real error. What does it mean? @Alexpux

**Comment by Alexpux** [comment]
Seems this is I/O error. Try rebuild again and switch OFF all antiviruses

**Comment by ulin0208** [comment]
libtool: compile:  /d/cpp/MINGW-packages/mingw-w64-gcc/src/build-x86_64-w64-mingw32/./gcc/gfortran -B/d/cpp/MINGW-packages/mingw-w64-gcc/src/build-x86_64-w64-mingw32/./gcc/ -L/mingw64/x86_64-w64-mingw32/lib -L/mingw64/lib -isystem /mingw64/x86_64-w64-mingw32/include -isystem /mingw64/include -B/mingw64/x86_64-w64-mingw32/bin/ -B/mingw64/x86_64-w64-mingw32/lib/ -isystem /mingw64/x86_64-w64-mingw32/include -isystem /mingw64/x86_64-w64-mingw32/sys-include -L. -Wall -L../libgfortran -c ../../../gcc-5.3.0/libgomp/openacc.f90  -DDLL_EXPORT -o .libs/openacc.o
f951.exe: Fatal Error: Reading module 'openacc_kinds' at line 55 column 72: Unexpected EOF
compilation terminated.

I found that the error is returened by gfortran.
I don't want to build fortran complier, so I changed "--enable-languages=c,lto,c++,objc,obj-c++,ada,fortran \" to "--enable-languages=c,c++ \" and everything is OK.
