### ISSUE TITLE
mingw-w64-gmime: missing include file gmime/gmime-gpg-context.h

### ISSUE THREAD

**Issue by ghelmer** [Alexpux/MINGW-packages#1124]
Attempting to build software that uses gmime fails with this error:
In file included from foo.cc:85:0:
C:/mingw32/include/gmime-2.6/gmime/gmime.h:74:37: fatal error: gmime/gmime-gpg-context.h: No such file or directory
compilation terminated.

I have successfully compiled after commenting-out the include of gmime/gmime-gpg-context.h in gmime/gmime.h.

**Comment by Alexpux** [comment]
Maybe because gmime-gpg-context.h is not for windows targets?

**Comment by ghelmer** [comment]
Right, so it seems it would be useful for the include/gmime-2.6/gmime/gmime.h file in the package to not try to include a file that doesn't exist.
