### ISSUE TITLE
New version of tcl/tk is out

### ISSUE THREAD

**Issue by oscarfv** [Alexpux/MINGW-packages#1125]
Tried to update the package but I'm stuck on `007-install.mingw.patch`. Why do we need all the replacements like this:

```
-		$(COPY) $$i "$(BIN_INSTALL_DIR)"; \
+		$(INSTALL_PROGRAM) $$i "$(BIN_INSTALL_DIR)"; \
```

where

```
+INSTALL			= $(SHELL) $(UNIX_DIR)/install-sh -c
+INSTALL_PROGRAM		= ${INSTALL}
+INSTALL_LIBRARY		= ${INSTALL}
+INSTALL_DATA		= ${INSTALL} -m 644
+INSTALL_DATA_DIR	= ${INSTALL} -d -m 755
+
```

What's the problem with `$(COPY)` ?

**Comment by Alexpux** [comment]
Because it use Windows copy program and it not work under msys2

**Comment by oscarfv** [comment]
`win/Makefile.in` has

```
COPY = cp
```

**Comment by Alexpux** [comment]
well ok. But what problem with the patch at all?

**Comment by oscarfv** [comment]
Sorry for the late answer, I'm not receiving some e-mail notifications.

The largest chunk on the patchset is related to replacing `$(COPY)` with `$(INSTALL...)` and it fails to apply on the new tcl version. Other chunks failed too but they were easy to fix. Not so with that chunk, where one must decide which `INSTALL_*` must use instead of the `COPY`.

I tried removing that chunk and the packaging failed with something related to the man pages, IIRC. I don't know if it is caused by the missing chunk or not.

Just in case someone wants to continue the job, my changes are here:

https://github.com/oscarfv/MINGW-packages/tree/tcl-8.6.5

Another issue is that the extensions included on this package are building with `-static-libgcc`.

**Comment by Alexpux** [comment]
New packages uploaded

**Comment by oscarfv** [comment]
Thank you Alexey.
