### ISSUE TITLE
ffmpeg still broken

### ISSUE THREAD

**Issue by henryborchers** [Alexpux/MINGW-packages#1126]
Thank you for your efforts but ffmpeg is still broken. I can execute command line "ffmpeg", "ffprobe", and "ffplay" and nothing crashes but not actually runs either.

Using the libraries in my project isn't working either.

**Comment by henryborchers** [comment]
32-bit seems to work though.

**Comment by chhe** [comment]
@henryborchers Are you using Windows 10 64-Bit by any chance (or maybe even Windows 8)? The 64-Bit `ffmpeg` works fine on my Windows 7 64-Bit machine but on none of my Windows 10 64-Bit machines. I can confirm that the 32-Bit version works fine on a Windows 10 32-Bit though.

And as a side note: @Alexpux Anything that is dependant on `ffmpeg` needs to be rebuilt as well. For example `mpv`.

**Comment by chhe** [comment]
As for description of the "still broken": 

Running `ffmpeg.exe` in a MSYS2-shell yields no output. No error message or anything. It seems to do nothing.

Running `ffmpeg.exe` in a Windows command prompt yields a Windows error popup stating the following:

```
The application was unable to start correctly (0xc0000142). Click OK to close the application.
```

Building the `ffmpeg`- package by myself yields the same results.

**Comment by henryborchers** [comment]
@chhe Correct, I'm on Windows 10. 

Running ffmpeg in the Mingw32_shell works.
Running ffmpeg in the Mingw64_shell yields no output and gives me the same error message in Windows command prompt like you said.

**Comment by henryborchers** [comment]
I can confirm that my work builds with no problems with the 32-bit version of ffmpeg on Windows 10.

**Comment by van-nguyen** [comment]
+1 same thing happening with nodejs also, maybe they are related? and not ffmpeg specific.

**Comment by henryborchers** [comment]
I have tested this in Windows 7 & Windows 10 and I got the same result as @chhe. 

OS | Result
---- | --------
Windows 7  | Works in 32-bit and 64-bit
Windows 10 | Works only in 32-bit.

I'm relatively new to compiled languages so I'm very curious why this would happen. Any idea why ffmpeg would compile fine in 64-bit for Windows 7 but not Windows 10?

**Comment by omichel** [comment]
I confirm that ffmpeg is currently broken for me as well (ffmpeg 64 bit, Windows 10). Any idea on what might be the cause of this problem?

**Comment by Alexpux** [comment]
Seems Win 10 is the problem here. Works ok on Win 7 32/64

**Comment by Alexpux** [comment]
To solve it someone ned build debug version on Win 10 and try find the problem

**Comment by omichel** [comment]
It seems many dependencies of ffmpeg.exe changed with the new version of ffmpeg:
```
swscale-4.dll
swresample-2.dll
postproc-54.dll
avutil-55.dll
avresample-3.dll
avformat-57.dll
avfilter-6.dll
avdevice-57.dll
avcodec-57.dll
libx264-148.dll
```
We could narrow down the problem by checking if the wrong behavior is caused by one of these new dependencies.

**Comment by chhe** [comment]
Only libx264-148.dll is a third-party dependency. All the other dlls are
FFMPEG's.

**Comment by mati865** [comment]
GDB output:
`Starting program: D:\msys64\mingw64\bin\ffmpeg.exe
[New Thread 3664.0x804]
[New Thread 3664.0x1224]
[New Thread 3664.0x16ac]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000061cc6ab2 in ?? () from D:\msys64\mingw64\bin\libintl-8.dll
`

Strace:
`$ strace ffmpeg
create_child: ffmpeg
--- Process 4008 created
--- Process 4008 loaded C:\Windows\System32\ntdll.dll at 00007FF938280000
--- Process 4008 loaded C:\Windows\System32\kernel32.dll at 00007FF937960000
--- Process 4008 loaded C:\Windows\System32\KernelBase.dll at 00007FF934950000
--- Process 4008 loaded C:\Windows\System32\msvcrt.dll at 00007FF937750000
--- Process 4008 thread 5528 created
--- Process 4008 loaded C:\Windows\System32\ole32.dll at 00007FF9371C0000
--- Process 4008 loaded C:\Windows\System32\combase.dll at 00007FF9358C0000
--- Process 4008 loaded C:\Windows\System32\rpcrt4.dll at 00007FF9370A0000
--- Process 4008 loaded C:\Windows\System32\bcryptprimitives.dll at 00007FF935360000
--- Process 4008 loaded C:\Windows\System32\sechost.dll at 00007FF9377F0000
--- Process 4008 thread 1268 created
--- Process 4008 loaded C:\Windows\System32\gdi32.dll at 00007FF9375C0000
--- Process 4008 loaded C:\Windows\System32\user32.dll at 00007FF935760000
--- Process 4008 loaded C:\Windows\System32\psapi.dll at 00007FF937C90000
--- Process 4008 loaded C:\Windows\System32\shell32.dll at 00007FF935B40000
--- Process 4008 loaded C:\Windows\System32\cfgmgr32.dll at 00007FF935630000
--- Process 4008 loaded C:\Windows\System32\windows.storage.dll at 00007FF934B40000
--- Process 4008 loaded C:\Windows\System32\advapi32.dll at 00007FF937310000
--- Process 4008 loaded C:\Windows\System32\shlwapi.dll at 00007FF937C30000
--- Process 4008 loaded C:\Windows\System32\kernel.appcore.dll at 00007FF9348A0000
--- Process 4008 loaded C:\Windows\System32\SHCore.dll at 00007FF9353D0000
--- Process 4008 loaded C:\Windows\System32\powrprof.dll at 00007FF9348E0000
--- Process 4008 loaded C:\Windows\System32\profapi.dll at 00007FF9348C0000
--- Process 4008 loaded D:\msys64\mingw64\bin\avdevice-57.dll at 00007FF92EB10000
--- Process 4008 loaded C:\Windows\System32\oleaut32.dll at 00007FF935680000
--- Process 4008 loaded D:\msys64\mingw64\bin\avfilter-6.dll at 00007FF918800000
--- Process 4008 loaded D:\msys64\mingw64\bin\avcodec-57.dll at 00007FF90F890000
--- Process 4008 loaded D:\msys64\mingw64\bin\avformat-57.dll at 00007FF9156C0000
--- Process 4008 loaded D:\msys64\mingw64\bin\avresample-3.dll at 00007FF92E310000
--- Process 4008 loaded C:\Windows\System32\ws2_32.dll at 00007FF937520000
--- Process 4008 loaded D:\msys64\mingw64\bin\avutil-55.dll at 00007FF919D80000
--- Process 4008 loaded D:\msys64\mingw64\bin\postproc-54.dll at 00007FF92E2E0000
--- Process 4008 loaded D:\msys64\mingw64\bin\swresample-2.dll at 00007FF923360000
--- Process 4008 loaded D:\msys64\mingw64\bin\swscale-4.dll at 00007FF916D60000
--- Process 4008 loaded D:\msys64\mingw64\bin\libcaca-0.dll at 0000000069F40000
--- Process 4008 loaded C:\Windows\System32\avicap32.dll at 00007FF930B10000
--- Process 4008 loaded D:\msys64\mingw64\bin\libass-5.dll at 0000000069340000
--- Process 4008 loaded D:\msys64\mingw64\bin\SDL.dll at 0000000068100000
--- Process 4008 loaded D:\msys64\mingw64\bin\libfreetype-6.dll at 00000000693C0000
--- Process 4008 loaded D:\msys64\mingw64\bin\libfontconfig-1.dll at 0000000064F80000
--- Process 4008 loaded D:\msys64\mingw64\bin\libopenal-1.dll at 0000000066040000
--- Process 4008 loaded D:\msys64\mingw64\bin\libcelt0-2.dll at 0000000064AC0000
--- Process 4008 loaded D:\msys64\mingw64\bin\libdcadec-0.dll at 000000005E710000
--- Process 4008 loaded D:\msys64\mingw64\bin\libgsm.dll at 0000000070800000
--- Process 4008 loaded D:\msys64\mingw64\bin\libiconv-2.dll at 0000000000D00000
--- Process 4008 loaded D:\msys64\mingw64\bin\liblzma-5.dll at 0000000063CC0000
--- Process 4008 loaded D:\msys64\mingw64\bin\libmp3lame-0.dll at 000000006EB80000
--- Process 4008 loaded D:\msys64\mingw64\bin\libopencore-amrnb-0.dll at 000000006F540000
--- Process 4008 loaded D:\msys64\mingw64\bin\libopencore-amrwb-0.dll at 0000000066BC0000
--- Process 4008 loaded D:\msys64\mingw64\bin\libopenjp2-7.dll at 0000000066100000
--- Process 4008 loaded D:\msys64\mingw64\bin\libopus-0.dll at 0000000062500000
--- Process 4008 loaded D:\msys64\mingw64\bin\libschroedinger-1.0-0.dll at 000000006BBC0000
--- Process 4008 loaded D:\msys64\mingw64\bin\libspeex-1.dll at 0000000069580000
--- Process 4008 loaded D:\msys64\mingw64\bin\libtheoradec-1.dll at 0000000065B40000
--- Process 4008 loaded D:\msys64\mingw64\bin\libtheoraenc-1.dll at 0000000063100000
--- Process 4008 loaded D:\msys64\mingw64\bin\libvorbis-0.dll at 000000006D540000
--- Process 4008 loaded D:\msys64\mingw64\bin\libvpx-1.dll at 0000000066280000
--- Process 4008 loaded D:\msys64\mingw64\bin\libvorbisenc-2.dll at 000000006B680000
--- Process 4008 loaded D:\msys64\mingw64\bin\libwavpack-1.dll at 0000000069180000
--- Process 4008 loaded D:\msys64\mingw64\bin\libx264-148.dll at 000000005E570000
--- Process 4008 loaded D:\msys64\mingw64\bin\libx265.dll at 0000000000E10000
--- Process 4008 loaded D:\msys64\mingw64\bin\zlib1.dll at 0000000062E80000
--- Process 4008 loaded D:\msys64\mingw64\bin\xvidcore.dll at 0000000062600000
--- Process 4008 loaded C:\Windows\System32\secur32.dll at 00007FF92F9D0000
--- Process 4008 loaded D:\msys64\mingw64\bin\libbluray-1.dll at 0000000069840000
--- Process 4008 loaded D:\msys64\mingw64\bin\libbz2-1.dll at 0000000001290000
--- Process 4008 loaded D:\msys64\mingw64\bin\libmodplug-1.dll at 000000006CB80000
--- Process 4008 loaded D:\msys64\mingw64\bin\librtmp-1.dll at 000000006DA40000
--- Process 4008 loaded D:\msys64\mingw64\bin\libwinpthread-1.dll at 0000000064940000
--- Process 4008 loaded C:\Windows\System32\msvfw32.dll at 00007FF919D50000
--- Process 4008 loaded C:\Windows\System32\winmm.dll at 00007FF932FE0000
--- Process 4008 loaded D:\msys64\mingw64\bin\libharfbuzz-0.dll at 0000000061600000
--- Process 4008 loaded D:\msys64\mingw64\bin\libfribidi-0.dll at 0000000063980000
--- Process 4008 loaded D:\msys64\mingw64\bin\libpng16-16.dll at 0000000068B40000
--- Process 4008 loaded D:\msys64\mingw64\bin\libexpat-1.dll at 0000000068F40000
--- Process 4008 loaded D:\msys64\mingw64\bin\libgcc_s_seh-1.dll at 0000000061440000
--- Process 4008 loaded D:\msys64\mingw64\bin\liborc-0.4-0.dll at 0000000065680000
--- Process 4008 loaded D:\msys64\mingw64\bin\libogg-0.dll at 0000000070680000
--- Process 4008 loaded D:\msys64\mingw64\bin\libxml2-2.dll at 0000000070F40000
--- Process 4008 loaded D:\msys64\mingw64\bin\libgmp-10.dll at 000000006ACC0000
--- Process 4008 loaded D:\msys64\mingw64\bin\libhogweed-4-1.dll at 0000000069000000
--- Process 4008 loaded D:\msys64\mingw64\bin\libgnutls-30.dll at 00000000012B0000
--- Process 4008 loaded C:\Windows\System32\crypt32.dll at 00007FF935190000
--- Process 4008 loaded D:\msys64\mingw64\bin\libnettle-6-1.dll at 0000000067780000
--- Process 4008 loaded C:\Windows\System32\msasn1.dll at 00007FF9348B0000
--- Process 4008 loaded C:\Windows\System32\winmmbase.dll at 00007FF932820000
--- Process 4008 loaded C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.10586.0_none_396e892957c7fb25\comctl32.dll at 00007FF932AB0000
--- Process 4008 loaded D:\msys64\mingw64\bin\libglib-2.0-0.dll at 00000000685C0000
--- Process 4008 loaded D:\msys64\mingw64\bin\libstdc++-6.dll at 000000006FC40000
--- Process 4008 loaded C:\Windows\System32\sspicli.dll at 00007FF9345B0000
--- Process 4008 loaded D:\msys64\mingw64\bin\libintl-8.dll at 0000000061CC0000
--- Process 4008 loaded D:\msys64\mingw64\bin\libidn-11.dll at 0000000069540000
--- Process 4008 loaded D:\msys64\mingw64\bin\libtasn1-6.dll at 0000000065F00000
--- Process 4008 loaded D:\msys64\mingw64\bin\libp11-kit-0.dll at 0000000068EC0000
--- Process 4008 loaded D:\msys64\mingw64\bin\libffi-6.dll at 000000006B740000
--- Process 4008 loaded C:\Windows\System32\imm32.dll at 00007FF937CA0000
--- Process 4008, exception c0000005 at 0000000061CC6AB2
--- Process 4008 thread 1268 exited with status 0xc0000005
--- Process 4008 thread 5528 exited with status 0xc0000005
--- Process 4008 exited with status 0xc0000005
Segmentation fault
`
I'll try tocompile debug version when I get more time.

**Comment by mati865** [comment]
GDB output:
```
Starting program: D:\msys64\mingw64\bin\ffmpeg.exe
[New Thread 3664.0x804]
[New Thread 3664.0x1224]
[New Thread 3664.0x16ac]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000061cc6ab2 in ?? () from D:\msys64\mingw64\bin\libintl-8.dll
```

Since strace is long I posted it on pastebin:
http://pastebin.com/j2geUsNy

I'll try to compile debug version when I get more time.

**Comment by chhe** [comment]
mati865's research gave me an idea. The DLL which causes the segfault is a part of the `gettext` package. I updated it to version `0.19.7` by compiling it myself. `FFMPEG` seems to be working now. I have no idea though what an update to `gettext` might break elsewhere.

**Comment by mati865** [comment]
I'm trying to compile debug version. When looking at the pkgbuild I've found `--disable-static \` in line 68 and `--enable-static \` in line 103. Not sure which one we want but I'll use non-static for debugging and post results tomorrow.

**Comment by dthpham** [comment]
@chhe's suggestion to update gettext to 0.19.7 works.

The PKGBUILD for that package is already up to date in the master branch, so all you have to do is check it out and build it yourself. As for ffmpeg, you may need to comment out the `check()` block in the PKGBUILD to get it to install successfully (it fails there for some reason). Another note, I built gettext and ffmpeg under the 64-bit shell, building with the msys2 shell didn't work for me.

Hope this helps.

**Comment by omichel** [comment]
Apparently @Alexpu updated gettext to 0.19.7 on March 26th. Doing a `pacman -Syuu` brought me this new version (tagged 0.19.7-3). However, ffpmeg is still broken as before. Therefore, I suspect that recompiling manually gettext on a Windows 10 machine is the trick that makes ffmpeg work. Maybe we should ask @Alexpu to recompile a new version of that package, e.g., 0.19.7-4 on a Windows 10 machine if possible?

**Comment by mati865** [comment]
Gettext 0.19.7 is msys2 repo and crash is caused by gettext from MINGW repo which is in 0.19.6 version `Process 2624 loaded D:\msys64\mingw64\bin\libintl-8.dll at 0000000061CC0000`.
I'll try to update mingw-w64-x86_64-gettext on my 10 tomorrow.

**Comment by omichel** [comment]
Oh, you are right mingw-w64-x86_64-gettext is still at version 0.19.6, that's probably the problem... Thanks for taking care of updating this package!

**Comment by dthpham** [comment]
I'm using all the default mirrors and pacman is reporting that mingw64/mingw-w64-x86_64-gettext in the repo is still versioned 0.19.2-2, while my local build is at 0.19.7-1. For reference, my ffmpeg is at version 3.0-1 and I am also using 64-bit Windows 10.

**Comment by mati865** [comment]
Ok build went faster than I expected and ffmpeg is fine with mingw-w64-x86_64-gettext-0.19.7-1
If you want to test yourself here are packages build on Win10
i686: https://mega.nz/#!o4RHna6K!oTOZpNgFwBU90py2XZUtN8aX8Uc6JtM0ZvawXL_3cl4
x86_64: https://mega.nz/#!B8YEGJQS!00Ve-yyUBjh-aFaNRAK9lABCXz_R4lhtJw39kQ_DNXc

**Comment by omichel** [comment]
I installed the x86_64 package and can confirm that it fixed the ffmpeg problem. Thanks! Hopefully it will arrive soon through `pacman -Syuu`.

**Comment by Alexpux** [comment]
Well It will not be available soon as I can't build 32-bit version. It always crash on linking during build.

**Comment by omichel** [comment]
And can't you use the version contributed by @mati865? It seems he was able to compile the 32-bit version.

**Comment by Alexpux** [comment]
I'm not able

**Comment by mati865** [comment]
Adding binary build by some random people to msys64 repo would be serious security flaw.
CI seems to have problem compiling it.

**Comment by mati865** [comment]
Ffmpeg is fine with mingw-w64-x86_64-gettext 0.19.7-1 from repo.

**Comment by omichel** [comment]
I confirm it works now nicely out of the box. Thanks!

**Comment by henryborchers** [comment]
It'w working now! Thanks a million!
