### ISSUE TITLE
Ruby installation broken (gem install gives error in openssl.so)?

### ISSUE THREAD

**Issue by casper** [Alexpux/MINGW-packages#1129]
> pacman -S ruby
    > gem install win32-sapi
    ERROR:  Loading command: install (LoadError)
        No such process - /usr/lib/ruby/2.1.0/i386-msys/openssl.so
    ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

:( Am I missing some library? OpenSSL is installed already.

    msys/libopenssl 1.0.2.g-1 (libraries) [installed]

**Comment by Alexpux** [comment]
Ruby need to be rebuilded because of openssl API changes

**Comment by Alexpux** [comment]
Rebuilded/uploaded.

**Comment by HankAviator** [comment]
Спасибо больше!
