### ISSUE TITLE
nodejs doesn't work

### ISSUE THREAD

**Issue by nyz93** [Alexpux/MINGW-packages#1130]
When run under strace I get an error about a missing symbol, `SSLv2_client_method` in `SSLEAY32.dll`.

**Comment by elieux** [comment]
This package needs to be re-built. I can't tell you when it happens, but you can build it yourself in the meantime. Instructions are on our wiki.

**Comment by mati865** [comment]
Since both i686 and x86_64 build fine why not bump pkgrel and rebuild it?

**Comment by Alexpux** [comment]
because we want to upgrade this package rather than rebuild

**Comment by mati865** [comment]
I've made initial work on getting nodejs 4.4.1 to work https://github.com/mati865/MINGW-packages/tree/nodejs
But there is much to be fixed still

**Comment by Alexpux** [comment]
Right now 0.10.43 builded. Need to work on upgrade to latest 5.9.0
