### ISSUE TITLE
 liblept-4.dll: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by barik** [Alexpux/MINGW-packages#1166]
After installing the tesseract package via `pacman -S mingw-w64-x86_64-tesseract-ocr` and then running with `tesseract.exe`, I obtain the following error message:

> C:/msys64/mingw64/bin/tesseract.exe: error while loading shared libraries: liblept-4.dll: cannot open shared object file: No such file or directory

This is on a Windows 10, 64-bit machine.

**Comment by barik** [comment]
Interesting, running:

```
$ pacman -Ss leptonica
mingw32/mingw-w64-i686-leptonica 1.73-1
    Leptonica library (mingw-w64)
mingw64/mingw-w64-x86_64-leptonica 1.73-1 [installed]
    Leptonica library (mingw-w64)
```

does show that Leptonica is installed, but that it also installs `liblept-5.dll`.

**Comment by Alexpux** [comment]
This is because tesseract was builded against leptonic-1.72. Today will upload new tesseract package
