### ISSUE TITLE
Add Vulkan header files and library to packages

### ISSUE THREAD

**Issue by FslNopper** [Alexpux/MINGW-packages#1168]
Please add the Vulkan header files and library as a package:
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers

**Comment by Alexpux** [comment]
Please provide PKGBUILD for it :)

**Comment by FslNopper** [comment]
Never done a PKGBUILD script - so this may take a while.

**Comment by DoctorWho11** [comment]
It's simple and I already have some tarballs provided from the official vulkan sdk (import libs generated from the defs of the vulkan dll though)

**Comment by FslNopper** [comment]
It's easy when you have done it before :-) The honor will go to you, as soon it goes live. Thank you very much. Please close, as soon as the libs are available.
