### ISSUE TITLE
mingw-w64-qt5-git update please ?

### ISSUE THREAD

**Issue by mcallegari** [Alexpux/MINGW-packages#1180]
Hey guys, I am trying to build Qt5 on my own with MSYS2.
In particular I'd like to build Qt 5.7.0 alpha cause my interest is in the bleeding edge development of Qt3D. I can't use the ready-made PKGBUILD which at the moment builds Qt 5.5.1.

Now, there is a mingw-w64-qt5-git package but apparently it is not updated. It refers to Qt 5.3.0.
Also I found that https://github.com/Alexpux/Qt-builds is not maintained as well.

I'd like to kindly know:
1- is it of any interest to keep the -git package updated ?
2- if (1 == no), then can you please suggest which patches I should cherry pick from mingw-w64-qt5 and apply to a recent version of Qt (5.6.x / 5.7.x) ?
3- is there a step-by-step tutorial to build Qt5 from a source package the "manual" way ? Basically where I run configure with the options that I need

Thanks and keep up the great job on this project !

**Comment by DavidEGrayson** [comment]
I have compiled Qt 5.5.1 before using the mingw-w64-qt5 PKGBUILD in this repo (at commit https://github.com/Alexpux/MINGW-packages/commit/f7cb02ebfb164ee42d0044c2e9074ad80129e50d).  I'm not an expert on building Qt; @mingwandroid and @Alexpux would know more.

Question 2: I would suggest that you use that script as your starting point.  I would leave all the patches in that script; the MSYS2 developers presumably added them for a reason, and if they apply cleanly to the source of the Qt version you are building then it's probably a good idea to keep them.

Question 3: The PKGBUILD script in this repository can be used as a step-by-step tutorial, right?

**Comment by mcallegari** [comment]
Since 4 hours I am trying to make the PKGBUILD script to build Qt 5.7.0 alpha.
It's a mess.
QtWebKit is no more bundled in the sources, so most of the upstream patches are no more valid.
The process is freaking long cause every time the script extracts the sources, and until all patches are applied, I cannot skip that phase.
At this point I need to test each patch manually, cause I can't tell which ones were for webkit and which weren't :disappointed:

**Comment by DavidEGrayson** [comment]
Each hunk specifies a filename.

**Comment by mcallegari** [comment]
> Each hunk specifies a filename.
Is that supposed to be a lesson on how patches work ?
I am a developer too. I know how patches work and I already modified a couple to the new sources.

What I don't know is the whole history of the upstream patches, where, for example patch 0029 is not clear to me if it was done for webkit or something else.
The only hint is a comment saying
> # Ossi says we should fix this in qwebkit with a $$(shell_path), but the ' quotes get in the way
> # due to qtPrepareTool adding them with $$shell_quote

Anyway, after tweaking and disabling many patches, the build started.

**Comment by Alexpux** [comment]
You must download QtWebkit from qt repo and place it to source tree before building. QWebEngine is not buildable with mingw

**Comment by mcallegari** [comment]
@Alexpux luckily I'm not interested in qtwebkit or qtwebengine (I'm the one of #851, remember ?)
I'd just like to have the minimum necessary to test a Qt3D application.

Anyway, my question about mingw-w64-qt5-git is still there.
Basically I'd expect it to git clone the current dev repo and build it.
However, at the moment when you clone, qtwebkit is still there but not officially supported anymore, so the preferred module is now qtwebengine, and MSYS2 should adapt to it (and remove all the patches related to qtwebkit)
Although the -git package might sound difficult to maintain, it can be a good chance to have MSYS2 ready for a new Qt release on day 1 when it's released.
See it like a "staging" area, mainly for developers and never released in binary form (so PKGBUILD must be always used)

**Comment by mingwandroid** [comment]
I'd love to get the patches upstreamed and I did get a good few of them upstreamed in the early days, but the Qt Project have (rightly so) a high quality threshold on the quality of the patches they accept so it takes considerable time to get each one merged. It can be done, but to the detriment of working on other things, as usual.

If you want to maintain qt5-git and add all of our patches to that, please go ahead. That would be really good. We can try to remember what each patch is about if you can't figure any of them out.

As @Alexpux said qtwebengine can't be built with mingw-w64, and I think it was wrong of them to remove qtwebkit until either clang works properly and can build qt5 or qtwebengine can be built with mingw-w64.

**Comment by mcallegari** [comment]
@mingwandroid yes, upstreaming patches into the Qt project is painful (I experienced it on my skin) and I believe it's out of this discussion even though it'd remain a nice thing since MSYS2 is quite popular and should be officially supported by the Qt company.
Anyway, when I'm done building Qt I can polish what I have done today and try to come up with a pull request for mingw-w64-qt5-git to at least build 80% of the source tree.

You might be happy to know that Qt 5.7.0 alpha seems to build fine, with examples and tools. My PC is still not done with it, and until it's not finished I'm not going to speak too soon to tell if it is a good buid or not. I have to build an application on top of it first.

One question though: when I will move the installation folder, should I run qtbinpatcher ? If so, just on qmake.exe or on the entire tree (dlls included) ?

Thanks

**Comment by mcallegari** [comment]
Update: thanks to the latest patches submitted for Qt 5.6.0, I've been able to produce a working build for Qt 5.7.0 alpha.
The goal is to automate the download from GIT and build the latest sources.
Also, I opted for installing the "dev" binaries into /opt/qt5-dev, not to conflict with the mingw-w64-*-qt5 packages.

If you guys are interested, I can polish what I have done and come up with a PR that might be handy for other developers like me.

**Comment by Alexpux** [comment]
You can fix our qt5-git package and create pull request

**Comment by mcallegari** [comment]
> You can fix our qt5-git package and create pull request

Yep, that's the goal. Gimme a few days and I'll send a PR.
Note: of course there will be no QtWebKit (deprecated) and no QtWebEngine since it doesn't build with MinGW yet

**Comment by mcallegari** [comment]
Hey guys, I'm on the qt5-git PKGBUILD script.
The prepare section is complete, but I have an issue right after qmake is created.
Have you ever seen this error ?
```Can't open perl script "\D\MINGW-packages\mingw-w64-qt5-git\src\qt5\qtbase\bin\syncqt.pl": No such file or directory```

The paths passed to configure are correct (with / slashes) but for some reason they get reversed in that perl call, creating an invalid path.

The configure call looks like this:
```D:\MINGW-packages\mingw-w64-qt5-git\src\qt5\qtbase\configure.bat -top-level -prefix D:/MINGW-packages/mingw-w64-qt5-git/pkg/mingw-w64-i686-qt5-git/opt/qt5-5.7 -datadir D:/MINGW-packages/mingw-w64-qt5-git/pkg/mingw-w64-i686-qt5-git/opt/qt5-5.7/share/qt5 -archdatadir D:/MINGW-packages/mingw-w64-qt5-git/pkg/mingw-w64-i686-qt5-git/opt/qt5-5.7/share/qt5 -examplesdir D:/MINGW-packages/mingw-w64-qt5-git/pkg/mingw-w64-i686-qt5-git/opt/qt5-5.7/share/qt5/examples -testsdir D:/MINGW-packages/mingw-w64-qt5-git/pkg/mingw-w64-i686-qt5-git/opt/qt5-5.7/share/qt5/tests -opengl desktop -opensource -confirm-license -platform win32-g++ -release -I C:/msys64/mingw32/include/dbus-1.0 -I C:/msys64/mingw32/lib/dbus-1.0/include -I C:/msys64/mingw32/include/libxml2 -I C:/msys64/mingw32/include/mariadb -no-iconv -system-freetype -system-harfbuzz -icu```

**Comment by mcallegari** [comment]
Alright, so here's an update after a few PRs
- I had to add an extra patch to avoid including qopengles2ext.h and I actually had to remove the file from the tree to allow building. This makes no sense to me and any help to figure it out would be appreciated
- I had to disable the qtscxml module. I don't even know what that is
- right now the build produces an non working lrelease binary and in fact it fails on qttranslations with this error:
```/D/MINGW-packages/mingw-w64-qt5-git/src/qt5/qttranslations/translations/lrelease_wrapper.sh assistant_cs.ts -qm assistant_cs.qm

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_ios::clear```

Now I have no idea (yet) if this depends on GCC 5.3.0 or Qt but it prevents the build to complete :disappointed:
