### ISSUE TITLE
mingw-w64-x86_64-readline devel package

### ISSUE THREAD

**Issue by gokhansolak** [Alexpux/MINGW-packages#1200]
Hi, I was trying to build an open source project which requires readline. And I installed readline package. But it gave error: 

`configure: error: --with-readline was given, but test for readline failed`

After asking at stackoverflow ([here](http://stackoverflow.com/questions/36010121/msys2-bash-readline-command-not-found)) I found a solution. By installing the _libreadline-devel_ package at MSYS2 main, I was able to achieve build.

But I wasn't able to do the same with _mingw-w64_, since readline's `-devel` package is not available.

So I wanted to inform you about this absence. I was able to build, but it may be needed future by other users. 

Thanks for the great job and good luck.

**Comment by fracting** [comment]
Msys2 use different packaging policy for MSYS2-packages and MINGW-packages.
We have -devel package in MSYS2-packages, but no this kind of package in MINGW-packages, the devel files (like headers) are packaging in the same MinGW-w64 packages like mingw-w64-i686-libreadline or so. 

If it already works for you, then nothing need to be worry in the MINGW-packages case.

**Comment by gokhansolak** [comment]
I was able to build using MSYS2 packages. But with MinGW-w64 shell I still keep getting error
`configure: error: --with-readline was given, but test for readline failed`

**Comment by Alexpux** [comment]
Are you use right mingw-w64 shell and mingw deadline package installed? Maybe also you need mingw pig-config package

**Comment by fracting** [comment]
Hi,

I just double check and found the package name should be mingw-w64-i686-readline or mingw-w64-x86_64-readline, depends on your arch. Did you install that package?

There are some example PKGBUILDs in https://github.com/Alexpux/MINGW-packages, for example the mingw-w64-fossil-fossil, which depends on MINGW readline and builds fine here. Is the example helpful for your?

**Comment by gokhansolak** [comment]
I use the mingw64_shell.bat under msys64 folder. [Here](http://pastebin.com/1mVneHs1) is the batch script. 

I have mingw-w64-x86_64-readline installed. I didn't have pig-config. And I couldn't find it with `pacman -Ss pig-config` now.

I didn't understand what I found in mingw-w64-fossil-fossil folder, sorry :(

Configure file of the project I'm trying to build is [here](https://sourceforge.net/p/yap/yap-6.3/ci/6.3.0/tree/configure).

**Comment by fracting** [comment]
Typo, I think it is pkg-config ;)

**Comment by gokhansolak** [comment]
Sorry :). I installed mingw-w64-x86_64-pkg-config but still have the same error.

**Comment by Alexpux** [comment]
Do you have installed ming-w64-x86_64-toolchain?

**Comment by gokhansolak** [comment]
Oh, it seems I missed some packages from ming-w64-x86_64-toolchain. After installing them I was able to configure. 
Thank you for your attention.

**Comment by maoueh** [comment]
@gokhansolak Please close the issue since ti seems to be resolved :)
