### ISSUE TITLE
mingw-w64-i686-osgearth is crashing when osgearth_viewer is invoked

### ISSUE THREAD

**Issue by rhornig** [Alexpux/MINGW-packages#1203]
Invoking 'osgearth_viewer' or other non-trivial executables causes a segmentation fault (osgearth:version is working though)

**Comment by filnet** [comment]
Do you have bt of the crash. 
I recently pushed a fix for an osgearth crash in src/osgEarth/Units.
The new package version is not yet published.

**Comment by elieux** [comment]
Closing due to no response.
