### ISSUE TITLE
libXpm-noX4 i686 and x86_64 have different dependencies

### ISSUE THREAD

**Issue by phillord** [Alexpux/MINGW-packages#1211]
The x86_64 DLL has no dependencies, while the i686 DLL depends on both libgcc and winthreads, which seems wrong to me.

**Comment by mati865** [comment]
There are only mingw-w64-i686-xpm-nox and mingw-w64-x86_64-xpm-nox. They both require "${MINGW_PACKAGE_PREFIX}-gcc-libs".

**Comment by phillord** [comment]
I checked the DLLs using dependency walker (and also in actual use) and the two have different dependencies. The x64_86 works standalone while the i686 version does not. If this is not the intended behaviour then something is wrong somewhere.

**Comment by Alexpux** [comment]
Nothing wrong. This is due to GCC patch https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gcc/955-4.9.2-apply-hack-so-gcc_s-isnt-stripped.patch

**Comment by phillord** [comment]
Okay, if that is the expected behaviour. 

Unfortunately, it makes that DLL less useful for my purposes, and I'll have to use one from elsewhere.
