### ISSUE TITLE
pacman not finding git

### ISSUE THREAD

**Issue by Shreeshrii** [Alexpux/MINGW-packages#1212]
```
ra@Shree MINGW64 ~
$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date      0.0   B  0.00B/s 00:00 [---------------------]   0%
 mingw64 is up to date      0.0   B  0.00B/s 00:00 [---------------------]   0%
 msys is up to date         0.0   B  0.00B/s 00:00 [---------------------]   0%
:: Starting full system upgrade...
 there is nothing to do

ra@Shree MINGW64 ~
$ pacman -Ss mingw-w64-git

ra@Shree MINGW64 ~
$ pacman -Ss mingw-w64-x86_64-git
mingw64/mingw-w64-x86_64-git-repo 0.3.17-1 (mingw-w64-x86_64) [installed]
    The multiple Git repository tool (mingw-w64)
mingw64/mingw-w64-x86_64-gitg 3.19.4-1 [installed]
    git repository viewer for GTK+/GNOME (mingw-w64)

```

**Comment by Alexpux** [comment]
There are no mingw version of "git" in repo

**Comment by Alexpux** [comment]
Need developer for it.

**Comment by Shreeshrii** [comment]
Thanks. 

So, how do I use git under Msys2. I can't seem to find the package. I had it installed earlier on a different pc.

**Comment by Alexpux** [comment]
MSYS2 have msys version of git.
````pacman -S git````

**Comment by Shreeshrii** [comment]
Thanks!!

**Comment by Swoorup** [comment]
Why doesn't msys2 have a native package instead?

**Comment by mati865** [comment]
@Swoorup 

> Alexpux commented on 21 Mar 2016
There are no mingw version of "git" in repo

>Alexpux commented on 21 Mar 2016
Need developer for it.

**Comment by Swoorup** [comment]
@mati865 Developer: https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper

Has already done it. Except I realized we are waiting for few changes to be merge in. 
I can vouch that this is heaps faster than current msys/git on our repository with gazillions of files.

**Comment by mati865** [comment]
@Swoorup from the link you posted:
> Git for Windows created some patches for msys2-runtime that have not yet been sent upstream

https://dl.bintray.com/git-for-windows/pacman replaces some MSYS2 packages with patched version and git will not work properly without them.
So there will be no native git until they are until the patches are merged.
