### ISSUE TITLE
Package: grib-api

### ISSUE THREAD

**Issue by jeroenooms** [Alexpux/MINGW-packages#1213]
Placeholder for myself: 

Source: https://software.ecmwf.int/wiki/display/GRIB/Releases
Homebrew: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/grib-api.rb
RPM: https://apps.fedoraproject.org/packages/grib_api
DEB: https://packages.debian.org/source/sid/grib-api

**Comment by elieux** [comment]
Placeholder expired. :) Further discussion possible.
