### ISSUE TITLE
Emscripten

### ISSUE THREAD

**Issue by wsmoses** [Alexpux/MINGW-packages#122]
Emscripten is an LLVM-to-javascript compiler that many have used to port C/other languages to a browser environment.

Given the installation's dependence on other packages (and fairly simple installation once those have been resolved), I think it's a good candidate to add.

http://kripken.github.io/emscripten-site/docs/contributing/building_from_source/Using-Emscripten-on-Windows.html

**Comment by elieux** [comment]
Closing, as this feature request didn't get any attention.

**Comment by martell** [comment]
webasm is now mostly in the llvm and clang tree.
Will do a clang package update once 4.0 has been tagged to get that in a package

**Comment by elieux** [comment]
Cool.

**Comment by mati865** [comment]
@martell I'm rebasing clang and llvm patches on the master branch and trying to push some of them, it might be useful for you https://github.com/mati865/MINGW-packages/tree/clang-svn/mingw-w64-clang-svn
It's still WIP.

**Comment by martell** [comment]
Hey @mati865 yeah that would be useful. :)
I'm currently upstreaming a few patches and we can kill them locally after this happens.
