### ISSUE TITLE
QtCreator click menu "Technical Support" Segmentation fault

### ISSUE THREAD

**Issue by bstaint** [Alexpux/MINGW-packages#1220]
package: `mingw-w64-i686-qt-creator-3.6.1-1`

click menu "Technical Support" will Segmentation fault.

**Comment by mati865** [comment]
32-bit version crashes, 64-bit is fine.

**Comment by Alexpux** [comment]
It is related to https://github.com/Alexpux/MINGW-packages/issues/940
