### ISSUE TITLE
mingw-w64-x86_64-luajit-git: cannot resolve winpty-git dependency

### ISSUE THREAD

**Issue by patrikhuber** [Alexpux/MINGW-packages#1242]
```
$ pacman -S mingw-w64-x86_64-luajit-git
resolving dependencies...
warning: cannot resolve "winpty-git", a dependency of "mingw-w64-x86_64-luajit-git"
:: The following package cannot be upgraded due to unresolvable dependencies:
      mingw-w64-x86_64-luajit-git
```

I think the `winpty-git` package might have recently been renamed to `winpty`. #1239 is a different package and seems to have the same problem.

**Comment by merlinusambrosius** [comment]
I am experiencing the same error.

**Comment by mati865** [comment]
Not sure why it is not in MINGW repo yet. However you can build it yourself since fixed pkgbuild is already merged to this repo (https://github.com/Alexpux/MINGW-packages).

**Comment by mati865** [comment]
Updated package landed in repo.

**Comment by patrikhuber** [comment]
Cool, it's working for me now as well. Thanks.
