### ISSUE TITLE
compile with clang error.what's wrong

### ISSUE THREAD

**Issue by zhangxnghai** [Alexpux/MINGW-packages#1251]
HI,I test  clang with hello world.But I get error
clang++ --stdlib=libc++ -c hello.cpp -v

clang version 3.8.0 (tags/RELEASE_380/final)
Target: i686-w64-windows-gnu
Thread model: posix
InstalledDir: D:\msys32\mingw32\bin
 "D:\\msys32\\mingw32\\bin\\clang++.exe" -cc1 -triple i686-w64-windows-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name hello.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -target-cpu pentium4 -v -dwarf-column-info -debugger-tuning=gdb -coverage-file "D:\\msys32\\home\\h\\hello.cpp" -resource-dir "D:\\msys32\\mingw32\\bin\\..\\lib\\clang\\3.8.0" -internal-isystem "D:\\msys32\\mingw32\\include\\c++\\v1" -internal-isystem "D:\\msys32\\mingw32\\bin\\..\\lib\\clang\\3.8.0\\include" -internal-isystem "D:\\msys32\\mingw32\\lib\\gcc\\i686-w64-mingw32\\5.3.0\\include" -internal-isystem "D:\\msys32\\mingw32\\i686-w64-mingw32/sys-root/mingw/include" -internal-isystem "D:\\msys32\\mingw32\\lib\\gcc\\i686-w64-mingw32\\5.3.0\\include-fixed" -internal-isystem "D:\\msys32\\mingw32\\i686-w64-mingw32\\include" -internal-isystem "D:\\msys32\\mingw32\\include" -fdeprecated-macro -fdebug-compilation-dir "D:\\msys32\\home\\h" -ferror-limit 19 -fmessage-length 0 -fno-use-cxa-atexit -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o hello.o -x c++ hello.cpp
clang -cc1 version 3.8.0 based upon LLVM 3.8.0 default target i686-w64-windows-gnu
ignoring nonexistent directory "D:\msys32\mingw32\i686-w64-mingw32/sys-root/mingw/include"
#include "..." search starts here:
#include <...> search starts here:
 D:\msys32\mingw32\include\c++\v1
 D:\msys32\mingw32\bin\..\lib\clang\3.8.0\include
 D:\msys32\mingw32\lib\gcc\i686-w64-mingw32\5.3.0\include
 D:\msys32\mingw32\lib\gcc\i686-w64-mingw32\5.3.0\include-fixed
 D:\msys32\mingw32\i686-w64-mingw32\include
 D:\msys32\mingw32\include
End of search list.
In file included from hello.cpp:1:
In file included from D:\msys32\mingw32\include\c++\v1\iostream:38:
In file included from D:\msys32\mingw32\include\c++\v1\ios:216:
In file included from D:\msys32\mingw32\include\c++\v1\__locale:15:
In file included from D:\msys32\mingw32\include\c++\v1\string:439:
In file included from D:\msys32\mingw32\include\c++\v1\algorithm:625:
D:\msys32\mingw32\include\c++\v1\type_traits:1634:1: error: requested alignment must be 8192 bytes or smaller
_CREATE_ALIGNED_STORAGE_SPECIALIZATION(0x4000);
^                                      ~~~~~~
D:\msys32\mingw32\include\c++\v1\type_traits:1612:12: note: expanded from macro '_CREATE_ALIGNED_STORAGE_SPECIALIZATION'
    struct _ALIGNAS(n) type\
           ^        ~
D:\msys32\mingw32\include\c++\v1\__config:274:38: note: expanded from macro '_ALIGNAS'
#  define _ALIGNAS(x) __attribute__((__aligned__(x)))
                                     ^           ~
1 error generated.

My OS is windows home basic sp1.

Thanks.

**Comment by mati865** [comment]
If you compile without --stdlib=libc++ there will be no error. To get working exe you can use this as workaround
```
$ clang++ main.cpp
$ ./a
test
```

**Comment by zhangxnghai** [comment]
hi,mati865
Without --stdlib=libc++,the clang++ use libstdc++ and g++ headers,But I want to test clang++ and libc++ and clang++ headers.
Thanks

**Comment by mati865** [comment]
https://github.com/Alexpux/MINGW-packages/issues/940#issuecomment-201438024
Clang isn't ready to use yet

**Comment by zhangxnghai** [comment]
So clang hasn't been a set of ready-to-use toolchains for mingw under windows,even for hello world?
I have another question,I know clang and llvm can be used with libstdc+,libgcc_s and g++ headers.why the authors try their efforts and do their bests to build the libc++,libc++abi,compiler-rt and publish them.These are only built and can't be used?Or they would work under specified enviroment.(platform,patch)?

**Comment by Alexpux** [comment]
@martell  works on clang toolchain. We build as more as can from clang side but libc++ not yet ready to use. It is builded for those peoples who interested in testing it and fixing issues in upstream.

**Comment by mingwandroid** [comment]
clang and llvm are a set of technologies as well as compilers, so even if you can't build hello-world.cpp, those libraries are still useful for very many things in MSYS2.

Anyway, it's all about the PKGBUILDs and people contributing bits and pieces as and when they can, knowing that they can use MSYS2 to easily build the software to investigate the problem(s) in a supportive environment.

So if you are interested, lend a hand. Compile our clang/llvm/libc++ PKGBUILDs in debug mode, figure out why there are segfaults when using libc++ and propose patches fixing them.
