### ISSUE TITLE
Segfault when upgrading to mingw-w64-x86_64-gcc 5.3.0-4 from 5.3.0-2

### ISSUE THREAD

**Issue by timsong-cpp** [Alexpux/MINGW-packages#1262]
The following C++ code

```
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/ini_parser.hpp>
#include <sstream>
#include <cassert>
int main(){
    std::stringstream meow("miv = 5\n");
    boost::property_tree::ptree tree;
    boost::property_tree::read_ini(meow, tree);
    assert(tree.get<int>("miv") == 5);
}
```
runs OK with mingw-w64-x86_64-gcc 5.3.0-2 at `-O2` (the boost package is mingw-w64-x86_64-boost 1.60.0-2).

When upgraded to gcc 5.3.0-4, it segfaults (with or without recompilation).

**Comment by Alexpux** [comment]
It's due to buggy binutils 2.26. Will fix tomorrow

**Comment by Alexpux** [comment]
The same as https://github.com/Alexpux/MINGW-packages/issues/1262
