### ISSUE TITLE
pango: segfault in libpangoft2-1.0-0.dll

### ISSUE THREAD

**Issue by Shreeshrii** [Alexpux/MINGW-packages#1265]
Is a debug version of pango available? Tesseract training tools (text2image) segfault when used under MSYS2. They work fine under linux, the problem seems to be with libpangoft2-1.0-0.dll

```

(gdb) run --fonts_dir=C:/WINDOWS/fonts/ --text ../langdata/eng/eng.training_text --font Arial --outputbase eng.Arial.exp0
Starting program: C:\msys64\home\ra\text2tif\text2tif.exe --fonts_dir=C:/WINDOWS/fonts/ --text ../langdata/eng/eng.training_text --font Arial --outputbase eng.Arial.exp0
[New Thread 8608.0x1134]
[New Thread 8608.0x1ed0]
[New Thread 8608.0x1b18]
[New Thread 8608.0xfe8]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000006d702227 in ?? () from C:\msys64\mingw64\bin\libpangoft2-1.0-0.dll
(gdb) backtrace
#0  0x000000006d702227 in ?? ()
   from C:\msys64\mingw64\bin\libpangoft2-1.0-0.dll
#1  0x0000000000407992 in tesseract::PangoFontInfo::CanRenderString (
    this=0x8ef780,
    utf8_word=0x9d4d70 "different New Articles page 23 a To Service ~~ a details DC that don't as 7 «« Date: #1 : AZ\n___ Music am search this Please time each How at Online (7) get quality Advanced can | may such\na August "...,
    len=9, graphemes=0x8ef0c0) at ./training/pango_font_info.cpp:442
#2  0x00000000004076f9 in tesseract::PangoFontInfo::CanRenderString (
    this=0x8ef780,
    utf8_word=0x9d4d70 "different New Articles page 23 a To Service ~~ a details DC that don't as 7 «« Date: #1 : AZ\n___ Music am search this Please time each How at Online (7) get quality Advanced can | may such\na August "...,
    len=9) at ./training/pango_font_info.cpp:384
#3  0x000000000040b901 in tesseract::StringRenderer::StripUnrenderableWords (
    this=0x8ef780, utf8_text=0x8ef1a0) at ./training/stringrenderer.cpp:621
#4  0x000000000040c1d0 in tesseract::StringRenderer::RenderToImage (
    this=0x8ef780,
    text=0x987c50 "different New Articles page 23 a To Service ~~ a details DC that don't as 7 «« Date: #1 : AZ\n___ Music am search this Please time each How at Online (7) get quality Advanced can | may such\na August "...,
    text_length=6801, pix=0x8ef6e0) at ./training/stringrenderer.cpp:763
#5  0x000000000040eece in main (argc=1, argv=0x9199a8)
    at ./training/text2image.cpp:591

```

**Comment by Shreeshrii** [comment]
I tried to build it with enable-debug, but that process is getting errors too.

```
ra@Shree MINGW64 ~/MINGW-packages/mingw-w64-pango
$ makepkg-mingw -sLf
==> Making package: mingw-w64-pango 1.40.0-1 (Thu, Mar 31, 2016 12:58:38 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading pango-1.40.0.tar.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   348    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 1033k  100 1033k    0     0   337k      0  0:00:03  0:00:03 --:--:--  990k
  -> Found 0001-no-unconditional-xft-please.all.patch
  -> Found 0002-msvc-is-impotent-but-not.mingw.patch
==> Validating source files with sha256sums...
    pango-1.40.0.tar.xz ... Passed
    0001-no-unconditional-xft-please.all.patch ... Passed
    0002-msvc-is-impotent-but-not.mingw.patch ... Passed
==> Extracting sources...
  -> Extracting pango-1.40.0.tar.xz with bsdtar
==> Starting prepare()...
patching file docs/pango.types.in
patching file configure.ac
Hunk #1 succeeded at 243 (offset -14 lines).
Hunk #2 succeeded at 253 with fuzz 1 (offset -14 lines).
Hunk #3 succeeded at 626 (offset -318 lines).
patching file pango/pangocairo.def
acinclude.m4:68: warning: the serial number must appear before any macro definition
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
acinclude.m4:68: warning: the serial number must appear before any macro definition
configure.ac:115: installing './compile'
configure.ac:52: installing './missing'
gtk-doc.make:7: error: GTK_DOC_USE_LIBTOOL does not appear in AM_CONDITIONAL
docs/Makefile.am:101:   'gtk-doc.make' included from here
gtk-doc.make:60: error: GTK_DOC_BUILD_HTML does not appear in AM_CONDITIONAL
docs/Makefile.am:101:   'gtk-doc.make' included from here
gtk-doc.make:65: error: GTK_DOC_BUILD_PDF does not appear in AM_CONDITIONAL
docs/Makefile.am:101:   'gtk-doc.make' included from here
gtk-doc.make:74: error: ENABLE_GTK_DOC does not appear in AM_CONDITIONAL
docs/Makefile.am:101:   'gtk-doc.make' included from here
gtk-doc.make:274: error: HAVE_GTK_DOC does not appear in AM_CONDITIONAL
docs/Makefile.am:101:   'gtk-doc.make' included from here
docs/Makefile.am:142: error: ENABLE_GTK_DOC does not appear in AM_CONDITIONAL
docs/Makefile.am:54: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
examples/Makefile.am:6: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
examples/Makefile.am: installing './depcomp'
pango-view/Makefile.am:30: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
pango/Makefile.am:16: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
pango/mini-fribidi/Makefile.am:3: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
tools/Makefile.am:3: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
autoreconf: automake failed with exit status: 1
==> ERROR: A failure occurred in prepare().
    Aborting...


```

**Comment by Alexpux** [comment]
Update packages with ````pacman -Syuu```` to get rebuilded GCC and downgraded BINUTILS and try again.

**Comment by Shreeshrii** [comment]
Alex,
I am still getting the segfault
```

(gdb) run --fonts_dir= --text ../langdata/eng/eng.training_text --font "Arial" --outputbase eng.Arial.exp0 --tlog_level=2 2>&1 | grep run
Starting program: C:\msys64\home\shree\text2tif\text2tif.exe --fonts_dir= --text ../langdata/eng/eng.training_text --font "Arial" --outputbase eng.Arial.exp0 --tlog_level=2 2>&1 | grep run
[New Thread 5524.0x11e8]
[New Thread 5524.0x13b4]
[New Thread 5524.0x17b8]
[New Thread 5524.0x16b4]

Thread 1 hit Breakpoint 2, tesseract::PangoFontInfo::CanRenderString (
    this=0x8ef780,
    utf8_word=0x4404970 "different New Articles page 23 a To Service ~~ a details DC that don't as 7 «« Date: #1 : AZ\n___ Music am search this Please time each How at Online (7) get quality Advanced can | may such\na August "...,
    len=9, graphemes=0x8ef0c0) at ./training/pango_font_info.cpp:442
442            fc_font, kDottedCircleGlyph);
(gdb)
(gdb) continue
Continuing.

Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000006d702227 in ?? () from C:\msys64\mingw64\bin\libpangoft2-1.0-0.dll

```

**Comment by Shreeshrii** [comment]
the program works fine under cygwin64 also.

**Comment by Alexpux** [comment]
Try rebuild pango

**Comment by Shreeshrii** [comment]
​​
shree@lenovo MINGW64 ~/MINGW-packages/mingw-w64-pango
$ pacman -Syuu
:: Synchronizing package databases...
 mingw32 is up to date
                       0.0   B  0.00B/s 00:00
[-----------------------------------------------------------------------]
0%
 mingw64 is up to date
                       0.0   B  0.00B/s 00:00
[-----------------------------------------------------------------------]
0%
 msys is up to date
                      0.0   B  0.00B/s 00:00
[-----------------------------------------------------------------------]
0%
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do

shree@lenovo MINGW64 ~/MINGW-packages/mingw-w64-pango
$ makepkg-mingw -sLf
==> Making package: mingw-w64-pango 1.40.0-1 (Thu, Mar 31, 2016 11:01:13 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found pango-1.40.0.tar.xz
  -> Found 0001-no-unconditional-xft-please.all.patch
  -> Found 0002-msvc-is-impotent-but-not.mingw.patch
==> Validating source files with sha256sums...
    pango-1.40.0.tar.xz ... Passed
    0001-no-unconditional-xft-please.all.patch ... Passed
    0002-msvc-is-impotent-but-not.mingw.patch ... Passed
==> Extracting sources...
  -> Extracting pango-1.40.0.tar.xz with bsdtar
==> Starting prepare()...
patching file docs/pango.types.in
patching file configure.ac
Hunk #1 succeeded at 243 (offset -14 lines).
Hunk #2 succeeded at 253 with fuzz 1 (offset -14 lines).
Hunk #3 succeeded at 626 (offset -318 lines).
patching file pango/pangocairo.def
acinclude.m4:68: warning: the serial number must appear before any macro
definition
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
acinclude.m4:68: warning: the serial number must appear before any macro
definition
configure.ac:115: installing './compile'
configure.ac:52: installing './missing'
gtk-doc.make:7: error: GTK_DOC_USE_LIBTOOL does not appear in AM_CONDITIONAL
docs/Makefile.am:101:   'gtk-doc.make' included from here
gtk-doc.make:60: error: GTK_DOC_BUILD_HTML does not appear in AM_CONDITIONAL
docs/Makefile.am:101:   'gtk-doc.make' included from here
gtk-doc.make:65: error: GTK_DOC_BUILD_PDF does not appear in AM_CONDITIONAL
docs/Makefile.am:101:   'gtk-doc.make' included from here
gtk-doc.make:74: error: ENABLE_GTK_DOC does not appear in AM_CONDITIONAL
docs/Makefile.am:101:   'gtk-doc.make' included from here
gtk-doc.make:274: error: HAVE_GTK_DOC does not appear in AM_CONDITIONAL
docs/Makefile.am:101:   'gtk-doc.make' included from here
docs/Makefile.am:142: error: ENABLE_GTK_DOC does not appear in
AM_CONDITIONAL
docs/Makefile.am:54: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS'
(or '*_CPPFLAGS')
examples/Makefile.am:6: warning: 'INCLUDES' is the old name for
'AM_CPPFLAGS' (or '*_CPPFLAGS')
examples/Makefile.am: installing './depcomp'
pango-view/Makefile.am:30: warning: 'INCLUDES' is the old name for
'AM_CPPFLAGS' (or '*_CPPFLAGS')
pango/Makefile.am:16: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS'
(or '*_CPPFLAGS')
pango/mini-fribidi/Makefile.am:3: warning: 'INCLUDES' is the old name for
'AM_CPPFLAGS' (or '*_CPPFLAGS')
tools/Makefile.am:3: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS'
(or '*_CPPFLAGS')
autoreconf: automake failed with exit status: 1
==> ERROR: A failure occurred in prepare().
    Aborting...


ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Alexpux** [comment]
Seems you have some missing packages for build

**Comment by Shreeshrii** [comment]
I have all of the packages listed in PKGBUILD. Are any others needed?

​makedepends=("${MINGW_PACKAGE_PREFIX}-gcc"
            "${MINGW_PACKAGE_PREFIX}-pkg-config"
            "${MINGW_PACKAGE_PREFIX}-gobject-introspection")
depends=("${MINGW_PACKAGE_PREFIX}-gcc-libs"
         "${MINGW_PACKAGE_PREFIX}-cairo"
         "${MINGW_PACKAGE_PREFIX}-freetype"
         "${MINGW_PACKAGE_PREFIX}-fontconfig"
         "${MINGW_PACKAGE_PREFIX}-glib2"
         "${MINGW_PACKAGE_PREFIX}-harfbuzz")​

**Comment by Alexpux** [comment]
try install ````gtk-doc```` as I told you.

**Comment by mati865** [comment]
After installing  gtk-doc prepare() pass. I'll edit comment when build() finish to let you know if everything is fine.

**Comment by Shreeshrii** [comment]
Alex,
I was able to build pango with debug.
Thank you!

**Comment by Alexpux** [comment]
Is it solved?

**Comment by mati865** [comment]
Probably not related to msys2 https://github.com/amitdo/text2tif/issues/1

**Comment by Alexpux** [comment]
we not have text2tif comment in our packages.

**Comment by Shreeshrii** [comment]
Thanks.  Appreciate the help.

You can close this.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Alexpux** [comment]
@Shreeshrii, you solve this?

**Comment by Shreeshrii** [comment]
I think it was application problem. Debug version of pango helped find it.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
the original code of text2image from tesseract-ocr also has the same
problem.

Please see
https://github.com/amitdo/text2tif/commit/b055d4347abc523e4dadbd69c4bcfea22142a4a4

Amit @amitdo has just added a workaround to avoid the crash under
msys2/mingw64 -

It works under linux and cygwin, if you have any suggestions please let us
know.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by amitdo** [comment]
I will pull request the changes done in text2tif to tesseract sometime this month.
