### ISSUE TITLE
mingw-w64-i686-gdb duplicated entry

### ISSUE THREAD

**Issue by mati865** [Alexpux/MINGW-packages#1267]
There are 2 versions of the same package, 7.11-1 from msys32 repo and 7.9-1 from msys2.
To verify it I've created new msys2 directory using msys2-base package and installed only mingw-w64-i686-gdb with dependencies with the same result.
```
mingw32/mingw-w64-i686-gdb 7.11-1 (mingw-w64-i686-toolchain) [installed]
mingw64/mingw-w64-x86_64-gdb 7.11-1 (mingw-w64-x86_64-toolchain)
msys/gdb 7.9-1 (base-devel)
msys/mingw-w64-i686-gdb 7.9-1 (mingw-w64-i686-toolchain) [installed: 7.11-1]
```

EDIT: In clean msys2 pacman -Ss also returns 2 entries. Probably database bug.

**Comment by Alexpux** [comment]
What problem with it? One for mingw32/64 the second is for msys2 itself, third is from cross toolchain.

**Comment by DavidEGrayson** [comment]
The part of the name after the slash should be unique, right?  I don't think pacman can install the first and fourth entry at the same time because they have same name, and the fourth entry does not have "cross" in its name.

**Comment by Alexpux** [comment]
well latest seems not good. will check

**Comment by Alexpux** [comment]
Fixed in database. Will upload today later.
