### ISSUE TITLE
readline/gdb issue

### ISSUE THREAD

**Issue by jtanx** [Alexpux/MINGW-packages#1280]
Normally, I run `winpty gdb ...`, but after upgrading recently (with `pacman -Syuu`), it now sporadically crashes with

```
readline: readline_callback_read_char() called with no handler!

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by jtanx** [comment]
Just to add - if I run it without `winpty` then it doesn't crash.

**Comment by fracting** [comment]
Does it crash if you run `winpty cmd` from Mintty console?

**Comment by jtanx** [comment]
Brief testing suggests that it does not.

It seems to crash more often when you try to provide input when it's not accepting any e.g.:

1. Run program under winpty gdb
2. In the console, press enter or spam other keyboard input
3. Press Ctrl+C to interrupt/get into gdb

 ---> This is where it normally crashes

If not there, then when you continue execution then reach another breakpoint or interrupt it, then it may crash too. But it doesn't happen always.

I also just got this when exiting gdb under winpty

    error return ../../gdb-7.7.50.20140303/gdb/windows-nat.c:1216 was 5

**Comment by Alexpux** [comment]
Hmm seems you use very old GDB as I see.

**Comment by jtanx** [comment]
I ran `pacman -Syuu` and there were no updates available. Running `gdb --version` gives

~~~~~
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
~~~~~

pacman reports:

~~~~
$ pacman -Q mingw-w64-i686-gdb
mingw-w64-i686-gdb 7.11-1
~~~~

**Comment by jtanx** [comment]
Ahhh I see. Sorry. Ignore that line about `7.7.50` - in the past few hours I had copied in the gdb binary from [equation](http://www.equation.com/servlet/equation.cmd?fa=gdb). So I was actually using that - I was wondering why it wasn't crashing anymore.

-----

Okay, so if I run with the msys2 gdb, it does crash pretty predictably:

1. Run (non-terminal) program under `winpty gdb`
2. Press enter a few times into the terminal
3. Press Ctrl+C

It will terminate with 

~~~~~
readline: readline_callback_read_char() called with no handler!

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

~~~~~

**Comment by jtanx** [comment]
One example is:

    winpty gdb glade

I can make it happen just by pressing 'Enter' once into the terminal while Glade is running and then trying to interrupt with Ctrl+C

**Comment by jtanx** [comment]
Slightly unrelated but another issue with gdb under winpty is that the arrow keys don't work - when you press up, it prints 'H', down prints 'P', left prints 'K' and right prints 'M'.

**Comment by jtanx** [comment]
It doesn't seem to print anything anymore, but if you Ctrl+C while under winpty sometimes it will just quit unexpectedly instead of breaking into the debugger.
