### ISSUE TITLE
Lua and Readline

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#1296]
Even though Lua does not enable Readline on Windows, I did so anyways and got it to work right off the bat. I also applied a patch that enables additional readline support. The patch can be found on the [LuaPowerPatches](http://lua-users.org/wiki/LuaPowerPatches) part of the lua-users wiki.

The patch is called 'Advanced readline support (5.3, 5.2, 5.1, 5.0)'

I encountered no issues using the readline features.

**Comment by elieux** [comment]
Why is this not in upstream Lua? I don't think we want many third-party patches that aren't related to supporting Windows as a first-class platform.
