### ISSUE TITLE
add LLVM.dll to mingw-w64-x86_64-llvm

### ISSUE THREAD

**Issue by amigalemming** [Alexpux/MINGW-packages#1300]
Could you please add LLVM.dll (e.g. LLVM-3.8.0.dll) to MSYS2's llvm package? I need it for calling LLVM from Haskell/GHC.

I am not able to build this package with makepkg-mingw myself. It fails with:

```
tar: cfe-3.8.0.src/test/Driver/Inputs/multilib_64bit_linux_tree/usr/bin/as: cannot add symbolic link to x86_64-unknown-linux-gnu-as: No such file or directory
```

and similar errors but that is certainly a different issue.

**Comment by Alexpux** [comment]
LLVM is fully static for mingw builds so I can't do something here myself. Feel free to investigate how to build it or ask on LLVM mailing list.

**Comment by amigalemming** [comment]
I have applied the patches from
https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-clang
manually to the llvm-3.8 source tree and then run the cmake build using the LLVM_BUILD_LLVM_DYLIB=ON switch as described at: http://llvm.org/docs/CMake.html .
This way I got a LLVM.dll. However, the LLVM tools become pretty large (bin directory contains 600MB). LLVM_LINK_LLVM_DYLIB=ON should link them with LLVM.dll but this results in a lot of linker errors concerning missing symbols.

**Comment by thielema** [comment]
Here is the result, installed in /usr/local/llvm-3.8:
http://code.haskell.org/~thielema/llvm-mingw/

**Comment by mati865** [comment]
Currently it fails linking LTO: https://gist.github.com/mati865/2be58881336db472f2dc819e6f1c83ac

**Comment by mati865** [comment]
Additional info: When using `LLVM_BUILD_LLVM_DYLIB=ON` and `LLVM_LINK_LLVM_DYLIB=ON` it doesn't fail but created LLVM.dll have 321 KiB and LLVM.dll.a 1KiB.
Clearly symbols aren't put into shared lib.

**Comment by mati865** [comment]
Found it, LLVM.dll is 37 MiB big, patches incoming in next days.

**Comment by mati865** [comment]
New version with LLVM.dll is almost ready https://github.com/Alexpux/MINGW-packages/pull/2070
You can try it if you wish

**Comment by elieux** [comment]
I think it's done now. :)
