### ISSUE TITLE
cannot build mingw-w64-x86_64-llvm with makepkg-mingw

### ISSUE THREAD

**Issue by amigalemming** [Alexpux/MINGW-packages#1303]
Building mingw-w64-x86_64-llvm on Windows 7 64bit with MSYS2 fails.
First it downloads and unpacks LLVM-3.8.0 archives from llvm.org.
Then it emits a message like this:

```
tar: cfe-3.8.0.src/test/Driver/Inputs/multilib_64bit_linux_tree/usr/bin/as: cannot add symbolic link to x86_64-unknown-linux-gnu-as: No such file or directory
```

(error message translated from German).
Finally it performs some patches and quits:

```
...
cfe-3.8.0.src/tools/diagtool/DiagnosticNames.cpp
cfe-3.8.0.src/tools/diagtool/DiagTool.h
cfe-3.8.0.src/tools/diagtool/DiagnosticNames.h
cfe-3.8.0.src/Makefile
tar: Beende mit Fehlerstatus aufgrund vorheriger Fehler
patching file cmake/modules/GetHostTriple.cmake
patching file cmake/modules/LLVMInstallSymlink.cmake
patching file cmake/modules/AddLLVM.cmake
Hunk #1 succeeded at 417 with fuzz 1 (offset 18 lines).
patching file lib/Driver/Driver.cpp
Hunk #1 succeeded at 363 (offset -1628 lines).
patching file tools/libclang/CMakeLists.txt
patching file tools/driver/CMakeLists.txt
patching file tools/libclang/CMakeLists.txt
patching file lib/profile/WindowsMMap.h
Hunk #1 succeeded at 12 (offset 1 line).
patching file lib/CMakeLists.txt
patching file src/random.cpp
==> Beginne build()...
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
```

**Comment by mati865** [comment]
Tip:
If you want to run program in English mode run it like that `LANG="en_GB.utf8" makepkg...` you can replace GB with any English locale. Also you can temporary change shell language by using `export LANG="en_GB.utf8"`.

I have similar error however it keeps building:
```
cfe-3.8.0.src/tools/diagtool/DiagnosticNames.cpp
cfe-3.8.0.src/tools/diagtool/DiagTool.h
cfe-3.8.0.src/tools/diagtool/DiagnosticNames.h
cfe-3.8.0.src/Makefile
tar: Exiting with failure status due to previous errors
patching file cmake/modules/GetHostTriple.cmake
patching file cmake/modules/LLVMInstallSymlink.cmake
patching file cmake/modules/AddLLVM.cmake
Hunk #1 succeeded at 417 with fuzz 1 (offset 18 lines).
patching file lib/Driver/Driver.cpp
Hunk #1 succeeded at 363 (offset -1628 lines).
patching file tools/libclang/CMakeLists.txt
patching file tools/driver/CMakeLists.txt
patching file tools/libclang/CMakeLists.txt
patching file lib/profile/WindowsMMap.h
Hunk #1 succeeded at 12 (offset 1 line).
patching file lib/CMakeLists.txt
patching file src/random.cpp
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- The ASM compiler identification is GNU
-- Found assembler: D:/msys64/mingw64/bin/gcc.exe
```

**Comment by amigalemming** [comment]
I'll try the local switch to english next time.
If the creation of symbolic links was not fatal, how can I find out why makepkg actually fails?

**Comment by mati865** [comment]
If you use `makepkg-mingw -sLf` you will have logs named like that: mingw-w64-clang-3.8.0-2-x86_64-build.log, mingw-w64-clang-3.8.0-2-x86_64-prepare.log. They may contain some useful info, you can put them on pastebin, rename them to end with .txt or zip them and attach to GitHub comment.

**Comment by amigalemming** [comment]
I'll try the local switch to english next time.
If the creation of symbolic links was not fatal, how can I find out why makepkg actually fails?

**Comment by amigalemming** [comment]
I did
~~~~
$ export LANG="en_GB.utf8"
$ makepkg-mingw -sLCf
~~~~
As far as I can see, the generated log file does not contain any more interesting detail.
It is too big for pastebin, thus I put it there:
http://code.haskell.org/~thielema/mingw-llvm/makepkg-mingw-log.tar.xz

**Comment by mati865** [comment]
Maybe missing dependencies?
Exectue following commands:
```
pacman --needed -S base-devel
pacman --needed -S mingw-w64-x86_64-toolchain
pacman --needed -S mingw-w64-i686-toolchain      #if you want 32bit builds
```
And try again.

**Comment by amigalemming** [comment]
Ah, after installing these package groups `makepkg-mingw` run about 2h and reported that it has successfully built the package. Maybe installation of those packages should be mentioned in the README file?

**Comment by mati865** [comment]
README comes from llvm tarball.
Here you can find instructions on wiki:
https://sourceforge.net/p/msys2/wiki/Contributing%20to%20MSYS2/

**Comment by amigalemming** [comment]
On Sun, 17 Apr 2016, Mateusz Mikuła wrote:

> README comes from llvm tarball.

I meant this one:
    https://github.com/Alexpux/MINGW-packages/blob/master/README.md

> Here you can find instructions on wiki:
> https://sourceforge.net/p/msys2/wiki/Contributing%20to%20MSYS2/

Good to know!

**Comment by mati865** [comment]
I think it is good idea. Lets wait for @Alexpux.
