### ISSUE TITLE
boost: Symlinks not supported when compiled on MSYS2 MinGW64 Windows 7

### ISSUE THREAD

**Issue by emmenlau** [Alexpux/MINGW-packages#1305]
I will try to follow up this issue a bit further myself, but wanted to report it ASAP to help others and track the progress. Please see the issue report here: https://svn.boost.org/trac/boost/ticket/12119

An (ugly) patch that enforces symlink support is attached. It requires additionally the Windows version to be defined to something higher than XP, like i.e. Vista. I have tested with adding define=_WIN32_WINNT=0x0601 to b2 for compiling.

[boost-1.60.0-enforce-symlinks.patch.txt](https://github.com/Alexpux/MINGW-packages/files/211997/boost-1.60.0-enforce-symlinks.patch.txt)

**Comment by mati865** [comment]
https://sourceforge.net/p/msys2/tickets/41/

**Comment by DavidEGrayson** [comment]
Since this repository has more than one package in it, it would be good to put the package name (boost) in the subject.

**Comment by mingwandroid** [comment]
AFAIK, reparse points can be interpreted with some custom code on XP just fine. Qt does it for example. It's just a matter of casting to be appropriate structure.

Boost should take a look at this and rework their approach, bit with XP being at the end of its life, I think this is something that the MSYS2 project would have to maintain patches for.

**Comment by emmenlau** [comment]
I went a bit deeper into the problem and found two problems:
  - boost::filesystem can only create symlinks when run with elevated permissions. It also needs to be compiled with elevated permissions in order to detect that the platform supports symlinks in the first place
  - boost::filesystem requires _WIN32_WINNT=0x0601 (or higher) define to enable symlinks

I understand now MSYS2 perspective on _WIN32_WINNT=0x0601, so I can add this define myself. But why is admin permission required? From the 'ln' command it works as normal user?! Is this a boost-issue or MSYS2-issue?

**Comment by mingwandroid** [comment]
Adding that flag yourself isn't good for the community. If you can find a solution that enables it boost to work for everyone who has the symlink permission set that would be better.

The compile time elevated permissions test in boost is just wrong. There's no other way to describe it. Build != host.

As I said before, there are other ways of handling symlinks for earlier systems, they involve manually parsing reparse records. Boost should do that instead.

**Comment by emmenlau** [comment]
I fully agree that this should be fixed in boost! And other packages proove that its possible. But I have been unable to fix this myself, as I seem to be completely unable to understand the logic of the link.jam configuration script. I've also reported the issue to boost::filesystem, but no response so far.

The best I can provide is the workaround: compile with elevated permissions, and define winver as appropriate for your target system.
