### ISSUE TITLE
keep packages for earlier LLVM versions like mingw-w64-x86_64-llvm35

### ISSUE THREAD

**Issue by amigalemming** [Alexpux/MINGW-packages#1306]
LLVM changes its API in nearly every release, thus I cannot simply update to a recent version.
Thus I ask to keep packages of older versions. As I understand you already do that for LLVM-3.5 with the mingw-w64-x86_64-llvm35 package. However it is not possible to install both LLVM-3.5 and latest LLVM at the same time. I guess you need put each LLVM version into a dedicated directory.

**Comment by Alexpux** [comment]
Sorry, I will not do it.

**Comment by elieux** [comment]
I don't think there's any hard technical reason against packaging older LLVM versions, but due to time constraints, we don't want to package old stuff. (I don't even know why `mingw-w64-x86_64-llvm35` exists. :)

Note that you can have multiple MSYS2 installations side by side.

**Comment by Alexpux** [comment]
@elieux ````mingw-w64-llvm35```` exists because it need to build ````OpenShadingLanguage```` that needed for ````Blender````.
See https://github.com/imageworks/OpenShadingLanguage/issues/480

**Comment by Alexpux** [comment]
Seems recent builds are now support LLVM 3.9. I will check and if all ok will remove LLVM 3.5
