### ISSUE TITLE
Qt5 application bsdfprocessor can't find the windows plugin anymore

### ISSUE THREAD

**Issue by mkae** [Alexpux/MINGW-packages#1308]
After my recent upgrade on a 64 bit system I get the error message
```
This application failed to start because it could not find or load the Qt platform plugin "Windows" in "".

Reinstalling the application may fix this Problem.
```
when starting package `mingw-w64-x86_64-bsdfprocessor`'s executable `bsdfprocessor`.
What is this about?

I had correctly upgraded with ```pacman -Suuy``` in this case, due to the downgrade of 2 packages.

---
Another issue is that when opening an msys2 shell at first a Windows CMD gets started which stays behind the actual msys2 shell window then and needs manual closing. Why gets the CMD window opened anyway?

**Comment by Alexpux** [comment]
Seems qtbinpatcher not run successfully.
Run it manually inside /mingw64/bin as
qtbinpatcher --force --nobackup

**Comment by mati865** [comment]
> Another issue is that when opening an msys2 shell at first a Windows CMD gets started which stays behind the actual msys2 shell window then and needs manual closing. Why gets the CMD window opened anyway?

https://github.com/Alexpux/MSYS2-packages/issues/537

**Comment by mkae** [comment]
mati865, thanks, that solved it!

**Comment by mkae** [comment]
Alexpux, yes, that was it, the qtbinpatcher didn't run on said machine.
