### ISSUE TITLE
mpv dependencies broken in live package repository

### ISSUE THREAD

**Issue by abjugard** [Alexpux/MINGW-packages#1313]
Updating today breaks mpv dependencies (depends on winpty-git rather than winpty).

> :: Synchronising package databases...
>  mingw32 is up to date
>  mingw64 is up to date
>  msys is up to date
> :: Starting core system upgrade...
>  there is nothing to do
> :: Starting full system upgrade...
> :: Replace winpty-git with msys/winpty? [Y/n]
> resolving dependencies...
> looking for conflicting packages...
> error: failed to prepare transaction (could not satisfy dependencies)
> :: mingw-w64-x86_64-mpv: removing winpty-git breaks dependency 'winpty-git'

**Comment by Alexpux** [comment]
I can't rebuild mpv. Not yet figure my problem

**Comment by mati865** [comment]
Maybe @fracting could take a loot at build bots?

**Comment by abjugard** [comment]
Oh? It built fine on my machine.

**Comment by mati865** [comment]
Yep, everyone can build locally but both bots fail.

**Comment by mati865** [comment]
Should be fixed now https://github.com/Alexpux/MINGW-packages/pull/1318
