### ISSUE TITLE
A better way of fixing ZeroMQ WinXP Incompatibility

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#1319]
[This patch should work](https://gist.github.com/BrisingrAerowing/193d3d057de285fc19bad836bb82f50e)

I just took the implementation from GLib and modified it so that it would build.

**Comment by mingwandroid** [comment]
Could you require it in spirit of how glib did it, bit without referring to their code? They are incompatible licence-wise, only slightly, but enough to be problematic.

Thanks for the effort.
