### ISSUE TITLE
qt-creator needs a rebuild now that qt5 has been updated

### ISSUE THREAD

**Issue by mkae** [Alexpux/MINGW-packages#1321]
qt-creator currently hangs, which is probably due to the qt5 update.

I think the interdependencies between packages need to be verified whenever a package is updated. Every update could potentially make a rebuild of dependent packages necessary. Surely not in all cases, but definitely in some.

**Comment by Alexpux** [comment]
QtCreator is builded agains qt 5.6.0 already

**Comment by mingwandroid** [comment]
The Qt Project takes binary compatibility *very* seriously. Most projects don't. Some others version their DLLs sometimes a little haphazardly.

I'm not seeing any hangs.

I recommend backing up your settings in %AppData%/QtProject and then deleting them and seeing if a clean reinstall of qt creator fixes it.

**Comment by mati865** [comment]
Crashing:
32bit Qt-creator with msys2 cmake version 3.2.3: http://pastebin.com/tHWwPdmN
32bit Qt-creator with msys2 cmake https://github.com/Alexpux/MSYS2-packages/pull/584: http://pastebin.com/3KQw8MLQ
Non crashing reference:
64bit Qt-creator with msys2 cmake version 3.2.3: [qtcreator.txt](https://github.com/Alexpux/MINGW-packages/files/259765/qtcreator.txt)
64bit Qt-creator with msys2 cmake https://github.com/Alexpux/MSYS2-packages/pull/584: [qtcreator_new_cmake.txt](https://github.com/Alexpux/MINGW-packages/files/259769/qtcreator_new_cmake.txt)

Shouldn't MinGW cmake be used instead of MSYS2 cmake?

**Comment by mkae** [comment]
@mati865, is this resolved for you by now?

**Comment by mati865** [comment]
@mkae, 32 bit is still crashing with several exceptions. But I'm using 64 bit apps mostly so it's no big deal for me.
I'll try to debug it but cannot promise anything.

**Comment by mkae** [comment]
Thanks for caring, @mati865!

**Comment by mati865** [comment]
I was not able to compile it in debug mode:
```
D:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lqbscored1
D:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lqbsqtprofilesetupd1
collect2.exe: error: ld returned 1 exit status
```

**Comment by mingwandroid** [comment]
You need first to compile and install mingw-w64-qbs in debug mode.

**Comment by mkae** [comment]
There should be a *-debug package instead, don't you think?

**Comment by mati865** [comment]
I've just compiled it and it doesn't crash in debug mode.

**Comment by mkae** [comment]
But it does so in release mode?

**Comment by mingwandroid** [comment]
We don't provide -debug packages generally. What would you expect to be in such a package?

Debug symbols for the normal release build or a full debug build? Either way, if you want to debug something then you're going to want to build it yourself so you can test your fixes out.

**Comment by mkae** [comment]
@mingwandroid, yes, I understand. Packages of kind -debug only make sense for libraries to be used by other applications, like it is e.g. the case for OpenSceneGraph.

Rebuilding Qt creator locally now. Will see whether that makes it work for me.

**Comment by mkae** [comment]
@mati865, can you tell me in detail what I need to do to get qt-creator to build in debug mode? Could you perhaps share your PKGBUILD for the debug configuration here?

**Comment by mati865** [comment]
@mkae 
Change `options=('docs' 'staticlibs') # 'debug' '!strip')` to `options=('docs' 'staticlibs' 'debug' '!strip')`
So it looks like this:
```
makedepends=("${MINGW_PACKAGE_PREFIX}-clang")
options=('docs' 'staticlibs' 'debug' '!strip')
optdepends=("${MINGW_PACKAGE_PREFIX}-gdb: for the debugger"
```

**Comment by mkae** [comment]
Cool, @mati865, thanks very much! (I am still too much of a newbee here on MSYS2...)

**Comment by mati865** [comment]
Np.

**Comment by mkae** [comment]
So, building debug versions of `qbs` as well as `qtcreator` worked. 
However, `qtcreator` still fails to run, but this time Iam at least able to get some sort of backtrace:
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named libstdcxx.v6.printers
c:\msys32\mingw32\bin\../etc/gdbinit:5: Error in sourced command file:
Error while executing Python code.
Reading symbols from qtcreator...done.
(gdb) run
Starting program: C:\msys32\mingw32\bin\qtcreator.exe
[New Thread 2196.0x714]
Can't read data for section '.debug_info' in file 'C:\msys32\mingw32\bin\Qt5Quickd.dll'

Program received signal SIGSEGV, Segmentation fault.
0x15fcc50c in WTF::OSAllocator::reserveAndCommit (bytes=8388608,
    writable=true, executable=false, includesGuardPages=true)
    at ../3rdparty/masm/wtf/OSAllocatorWin.cpp:57
57      ../3rdparty/masm/wtf/OSAllocatorWin.cpp: No such file or directory.
(gdb) bt f
#0  0x15fcc50c in WTF::OSAllocator::reserveAndCommit (bytes=8388608,
    writable=true, executable=false, includesGuardPages=true)
    at ../3rdparty/masm/wtf/OSAllocatorWin.cpp:57
        result = 0x0
#1  0x16199a39 in WTF::PageAllocation::allocate (
../../gdb-7.11.1/gdb/utils.c:1066: internal-error: virtual memory exhausted: can't allocate 1048663 bytes.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) [answered Y; input not from terminal]

This is a bug, please report it.  For instructions, see:
<http://www.gnu.org/software/gdb/bugs/>.

../../gdb-7.11.1/gdb/utils.c:1066: internal-error: virtual memory exhausted: can't allocate 1048663 bytes.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Create a core file of GDB? (y or n) [answered Y; input not from terminal]

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```
There is some 3rd party code seemingly responsible for the crash.

And on top of that this crash reveals a bug in `gdb`!

**Comment by mati865** [comment]
@mkae, `WTF::OSAllocator` is a WebKit stuff. Are you sure you have enough memory to debug it?

P.S.
Looks like binutils, gdb and libtool weren't rebuild. I fixed it for myself some time ago but forgot to send PR.

**Comment by mkae** [comment]
Jesus, why all those three also need to be build as debug? I have 3 GB RAM only... Perhaps that's not enough?!

**Comment by mati865** [comment]
They don't have to be build in debug mode but they should be rebuild each time GCC is updated. Their last rebuild was for GCC 5.4.0 and now we use GCC 6.1.0.

I think 3GB should be enough for 32-bit since process can use only 2GB, could you monitor your memory usage during debugging? It could be anothe WebKit bug.

**Comment by mkae** [comment]
Oh, I see. That would have been the same for `qbs` then?!!?

If so, such dependency chains should all be automagically updated once a dedepence requires that!

It looks like MSYS2 is suffering a little from the fact that only Alexey himself is managing the whole updating on his machine(s) after all...

**Comment by mkae** [comment]
This is what I got when I tried to build `binutils`:
```
    9ac47a4.diff ... Passed
==> Verifying source file signatures with gpg...
    binutils-2.25.1.tar.bz2 ... FAILED (unknown public key C3126D3B4AE55E93)
==> ERROR: One or more PGP signatures could not be verified!
```
What's going on there?

**Comment by mkae** [comment]
Same for `libtool`:
```
    0008-tests.patch ... Passed
==> Verifying source file signatures with gpg...
    libtool-2.4.6.tar.xz ... FAILED (unknown public key 151308092983D606)
==> ERROR: One or more PGP signatures could not be verified!
```

**Comment by mkae** [comment]
`gdb`:
```
    gdb-fix-using-gnu-print.patch ... Passed
==> Verifying source file signatures with gpg...
    gdb-7.11.1.tar.xz ... FAILED (unknown public key 92EDB04BFF325CF3)
==> ERROR: One or more PGP signatures could not be verified!
```

**Comment by mingwandroid** [comment]
This is a trust feature of `pacman` where you are mean to verify through your own investigations whether you trust a given developer or not. Read more here: 

https://bbs.archlinux.org/viewtopic.php?id=152337

.. or skip to the last comment, or else, if you don't care for this, add `--skippgpcheck` to each call of `makepkg/makepkg-mingw`.

**Comment by mkae** [comment]
I never had to skip the check up to now...

**Comment by mkae** [comment]
Strange that I couldn't successfully get this key accepted for building:
```
    9ac47a4.diff ... Passed
==> Verifying source file signatures with gpg...
    binutils-2.25.1.tar.bz2 ... FAILED (the public key EAF1C276A747E9ED86210CBAC3126D3B4AE55E93 is not trusted)
==> ERROR: One or more PGP signatures could not be verified!
```
although I have the key in my keyring:
```
$ LANG=C gpg --list-key EAF1C276A747E9ED86210CBAC3126D3B4AE55E93
gpg: WARNING: using insecure memory!
gpg: please see http://www.gnupg.org/documentation/faqs.html for more information
pub   1024D/4AE55E93 2008-10-16
uid                  Tristan Gingold <gingold@adacore.com>
sub   2048g/66D026B2 2008-10-16
```

**Comment by mkae** [comment]
Do I need to personally locally sign the relevant GPG keys in my key ring, so that pacman accepts them?

**Comment by mati865** [comment]
You can sign it or simply change it's trust level.
