### ISSUE TITLE
Python3 static lib is missing

### ISSUE THREAD

**Issue by zelid** [Alexpux/MINGW-packages#1324]
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python3/PKGBUILD
has "staticlibs" in it's options

After installation there are only dynamic libraries:
/mingw32/bin/libpython3.5m.dll
/mingw32/lib/libpython3.5m.dll.a
/mingw32/lib/python3.5/config-3.5m/libpython3.5m.dll.a

And no static library "libpython3.5m.a" how to get a static Python 3.5 library and CXX flags to link with it?

**Comment by Alexpux** [comment]
We not have Python static library

**Comment by zelid** [comment]
Any easy way to build one by myself that will be compatible with other MSYS2 static libraries?

**Comment by Alexpux** [comment]
No there are no easy way to build Python static library

**Comment by mati865** [comment]
You can try this https://stackoverflow.com/questions/1150373/compile-the-python-interpreter-statically
But don't expect it to work in MSYS2 without some patching.

**Comment by lazka** [comment]
@zelid do you still need this?

**Comment by lazka** [comment]
If you still do feel free to post here or open another issue. Closing for now.
