### ISSUE TITLE
No longer needed patch.

### ISSUE THREAD

**Issue by lhmouse** [Alexpux/MINGW-packages#1325]
The commit 1f4cfb7ffe95dcf2e3568d98889ee6db914c0b40 to GCC's gcc-5-branch renders the patch [mingw-w64-gcc-git/0009-Work-around-un-too-late-resolved-__EH_FRAME_BEGIN__.patch](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gcc-git/0009-Work-around-un-too-late-resolved-__EH_FRAME_BEGIN__.patch) no longer needed. Please remove it.

[remove-0009.patch.txt](https://github.com/Alexpux/MINGW-packages/files/222168/remove-0009.patch.txt)

**Comment by mingwandroid** [comment]
Please make a pull request.

**Comment by mingwandroid** [comment]
@lhmouse asked me to close this since a proper PR will be made.

**Comment by lhmouse** [comment]
See #1326.
