### ISSUE TITLE
Every shell opens 2 windows

### ISSUE THREAD

**Issue by mcallegari** [Alexpux/MINGW-packages#1327]
Hi, today I've updated my msys2 installation (pacman -Syu) and now every shell I open, results in 2 windows.

I even reinstalled everything from scratch, updated (update-core and pacman -Su) and it's still happening.
See screenshot

![image](https://cloud.githubusercontent.com/assets/2951337/14588416/a4882296-04c9-11e6-9b7d-596a988ed77e.png)

**Comment by Alexpux** [comment]
I'm not yet release new installers with fixes

**Comment by mati865** [comment]
https://github.com/Alexpux/MSYS2-packages/issues/537
