### ISSUE TITLE
Libxml++ 3.0

### ISSUE THREAD

**Issue by Dalan94** [Alexpux/MINGW-packages#1343]
libxml++-3.0 and libxml++-2.6 are incompatible (see [here](https://git.gnome.org/browse/libxml++/tree/NEWS)). Is it possible to create a package for each version ?

**Comment by mati865** [comment]
Yes since they have different names for files. You can create pkgbuild yourself if there is need for older version.

**Comment by rakhimov** [comment]
It's very rough jump from 2.6 to 3.0 building on AppVeyor CI.
Could the 2.6 version be provided under libxml++-2.6 (like libxml2)?
