### ISSUE TITLE
Package: pyzmq

### ISSUE THREAD

**Issue by embray** [Alexpux/MINGW-packages#1357]
I've been having a heck of a time installing pyzmq for mingw.  The issues are probably on its end, but it would be nice to have a package for this considering the difficulties.  I'd be happy to work on the packaging myself if it would be accepted.

**Comment by mati865** [comment]
Create PR and wait for someone to review it.

**Comment by galeksandrp** [comment]
It is now there.

**Comment by embray** [comment]
Indeed, it seems this came along with #1566.  I don't even remember what I needed this for :)
