### ISSUE TITLE
qt5: cmake fails to find package Qt5Quick

### ISSUE THREAD

**Issue by filnet** [Alexpux/MINGW-packages#1364]
See https://github.com/Alexpux/MINGW-packages/pull/1362

A cmake script will fail to do a `find_package(Qt5Quick REQUIRED)` with this error:

```
CMake Error at C:/msys64/mingw64/lib/cmake/Qt5Qml/Qt5Qml_QLocalClientConnectionFactory.cmake:2 (add_library):
  add_library cannot create imported target
  "Qt5::QLocalClientConnectionFactory" because another target with the same
  name already exists.
Call Stack (most recent call first):
  C:/msys64/mingw64/lib/cmake/Qt5Qml/Qt5QmlConfigExtras.cmake:4 (include)
  C:/msys64/mingw64/lib/cmake/Qt5Qml/Qt5QmlConfig.cmake:176 (include)
  C:/msys64/mingw64/lib/cmake/Qt5Quick/Qt5QuickConfig.cmake:96 (find_package)
  CMakeLists.txt:84 (find_package)

CMake Error at C:/msys64/mingw64/lib/cmake/Qt5Qml/Qt5Qml_QQmlDebuggerServiceFactory.cmake:2 (add_library):
  add_library cannot create imported target "Qt5::QQmlDebuggerServiceFactory"
  because another target with the same name already exists.
Call Stack (most recent call first):
  C:/msys64/mingw64/lib/cmake/Qt5Qml/Qt5QmlConfigExtras.cmake:4 (include)
  C:/msys64/mingw64/lib/cmake/Qt5Qml/Qt5QmlConfig.cmake:176 (include)
  C:/msys64/mingw64/lib/cmake/Qt5Quick/Qt5QuickConfig.cmake:96 (find_package)
  CMakeLists.txt:84 (find_package)

...
```

**Comment by filnet** [comment]
A change in qt 5.6 combined with PKGBUILD patch triggers the issue.

The patch 0037 changes the logic of finding Qt plugins from:
- find all *Plugin.cmake files
to
- final all *.cmake files that contain the string _PLUGINS
The idea is to force all plugins (even those that do not match the *Plugin.cmake regexp) to be included. This in turn to fix the qt5 static package.

This worked until qt 5.6 started to load some of those files itself causing the "already exist" issue.

This is the list of all plugins force loaded by the patch :
```
Qt5Location/Qt5Location_QGeoServiceProviderFactoryMapbox.cmake
Qt5Location/Qt5Location_QGeoServiceProviderFactoryNokia.cmake
Qt5Location/Qt5Location_QGeoServiceProviderFactoryOsm.cmake

Qt5Positioning/Qt5Positioning_QGeoPositionInfoSourceFactoryGeoclue.cmake
Qt5Positioning/Qt5Positioning_QGeoPositionInfoSourceFactoryPoll.cmake
Qt5Positioning/Qt5Positioning_QGeoPositionInfoSourceFactorySerialNmea.cmake

Qt5Qml/Qt5Qml_QLocalClientConnectionFactory.cmake
Qt5Qml/Qt5Qml_QQmlDebuggerServiceFactory.cmake
Qt5Qml/Qt5Qml_QQmlDebugServerFactory.cmake
Qt5Qml/Qt5Qml_QQmlInspectorServiceFactory.cmake
Qt5Qml/Qt5Qml_QQmlNativeDebugConnectorFactory.cmake
Qt5Qml/Qt5Qml_QQmlProfilerServiceFactory.cmake
Qt5Qml/Qt5Qml_QTcpServerConnectionFactory.cmake
```

That's without 3rd party plugins...

The problem is caused by .\lib\cmake\Qt5Qml\Qt5QmlConfigExtras.cmake which apparently now also loads the Qml factory plugins.

**Comment by mingwandroid** [comment]
Thanks for the analysis. Sounds like you are most of the way to a fix?

**Comment by bagong** [comment]
I am glad this is being looked into! Thanks a lot!

**Comment by filnet** [comment]
A simple fix is to exclude the problematic Qt5Qml plugins from the patch.

```
    file(GLOB pluginTargetsMaybe "${CMAKE_CURRENT_LIST_DIR}/Qt5Qml_*.cmake")
    unset(pluginTargets)
    if (pluginTargetsMaybe)
        foreach(pluginTarget ${pluginTargetsMaybe})
+          # exclude Qt5Qml factory plugins as they will be loaded later by Qt5QmlConfigExtras
+          string(REGEX MATCH Qt5Qml_.*Factory.cmake excluded ${pluginTarget})
+          if (excluded)
+              continue()
+          endif()
            file(STRINGS ${pluginTarget} matched REGEX Qt5Qml_PLUGINS)
            if (matched)
                list(APPEND pluginTargets ${pluginTarget})
            endif()
        endforeach()
    endif()
```

**Comment by mingwandroid** [comment]
Yeah you could do that or you could uniquify the list in a common bit of code so if the same thing happens again elsewhere it's already taken care off.

**Comment by filnet** [comment]
@mingwandroid I am not sure I get your last comment.

The proposed fix will be applied to Qt5BasicConfig.cmake.in so will impact all Qt5*Config.cmake files.

I could make the REGEX pattern less targeted (i.e. Qt5.*_.*Factory.cmake).

**Comment by mingwandroid** [comment]
My suggestion was to uniquify the pluginTargets list, either as a post process or by not adding things already on it.

I admit I've not looked at the cmake scripts for a while though!

If you don't think this is possible then your fix LGTM.

**Comment by filnet** [comment]
I was trying to find a more elegant and generic solution.

Problem is that the duplicate include() happens later and elsewhere.

It happens in Qt5QmlConfigExtras.cmake : 

```
file(GLOB _qt5qml_other_plugins ${CMAKE_CURRENT_LIST_DIR}/Qt5Qml_*Factory.cmake)

foreach(_other_plugin ${_qt5qml_other_plugins})
    include(${_other_plugin} OPTIONAL)
endforeach()
```

So you don't end up with a single pluginTargets list that contains duplicates and that you can simply uniquify.

**Comment by bagong** [comment]
I commented out that include in my local workaround ;)

**Comment by filnet** [comment]
what's the recommend approach for a fix like I proposed:
- modify existing patches, or
- create a new patch on top of the others ?

**Comment by mingwandroid** [comment]
It's appropriate to roll this change in with 0042-qt-5.4.0-static-cmake-also-link-plugins-and-plugin-deps.patch. Patching patches is not something I would wish on anyone (or myself when I look at it in the future).

**Comment by Optiligence** [comment]
`CMAKE_AUTOSTATICPLUGINS` now adds `Q_IMPORT_PLUGIN` for the above mentioned `Qt5Qml` plugins but does not link them
