### ISSUE TITLE
Prepare for upcoming OpenSSL fixes

### ISSUE THREAD

**Issue by dscho** [Alexpux/MINGW-packages#1373]
As per https://mta.openssl.org/pipermail/openssl-announce/2016-April/000069.html, we should expect an important bug fix release this coming Tuesday, between 12:00 and 15:00 UTC.

As I would like to release a new Git for Windows version as soon as possible after that, I would like to coordinate with you gentle people. Do you have any upgrade plans yet? Can I help?

**Comment by Alexpux** [comment]
I'm off from MSYS2 work for a 10 days. Will be available after 10th May.

**Comment by dscho** [comment]
@Alexpux anybody filling in for you?

If not, no biggie. I will make local MSYS2 and MINGW packages for OpenSSL, then, release Git for Windows, and open two Pull Requests (and MSYS2 will receive the updates at your convenience).

**Comment by mati865** [comment]
I think @mingwandroid will manage this project in the meantime.

**Comment by mingwandroid** [comment]
I don't do binary package builds and uploads.

**Comment by mingwandroid** [comment]
Hi @dscho, do you want me to help out with any of the patch refreshing effort? It's out now ..

**Comment by dscho** [comment]
Yes! I just ran out of time yesterday...

**Comment by dscho** [comment]
Here you go: https://github.com/Alexpux/MINGW-packages/pull/1381 and https://github.com/Alexpux/MSYS2-packages/pull/586

**Comment by mingwandroid** [comment]
Thanks a lot. It was a busy day for me also.

**Comment by dscho** [comment]
Okay, those two PRs are merged, and I'll leave the rest in your capable hands ;-)
