### ISSUE TITLE
GCC 6.1.0

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#1374]
GCC 6.1.0 has been released, and I was wondering if work is being done to update to it.

Just curious. Some of the new features look nice.

**Comment by mati865** [comment]
@Alexpux is off for 10 days.
There is some work done for gcc 6 in `gcc-git` package https://github.com/Alexpux/MINGW-packages/commits/master/mingw-w64-gcc-git

**Comment by mingwandroid** [comment]
And also some problems reported regarding relocation by @lhmouse and some bugs reported by @tkelman, it might be a little while yet, but your experiences with a self-built mingw-w64-gcc-git package would be appreciated.

**Comment by tkelman** [comment]
The new error and warning printing is nicer, but it did get more picky about some constructs so some code accepted by gcc 5 won't be by gcc 6.

**Comment by lhmouse** [comment]
Known issue: ncurses 5.9 doesn't compile with GCC 6.

**Comment by Alexpux** [comment]
Right now curses is 6.0. Do you try it?

**Comment by lhmouse** [comment]
> Right now curses is 6.0. Do you try it?
Yes I have tried yesterday. 6.0 is fine

**Comment by mati865** [comment]
@tkelman It's because of `The default mode for C++ is now -std=gnu++14 instead of -std=gnu++98`. There was analogical situation when GCC switched from ` -std=gnu89` to  `-std=gnu11`. Code which cannot be easily ported to new standard should be compiled with old flags.

**Comment by tkelman** [comment]
@mati865 not entirely. I'm on a phone atm so don't have a link handy, but we found examples of code that gcc 5 compiled fine but gcc 6 could not be made to build with any set of flags, std or otherwise.

**Comment by lhmouse** [comment]
@mati865 I used to always build ncurses-5.9 with -std=c99. Yes it fails on GCC 6.

**Comment by BrisingrAerowing** [comment]
I'll get it building and see what happens. Might be a while, though.

**Comment by BrisingrAerowing** [comment]
I get various errors trying to build, mostly file not found issues, with a few compiler errors thrown in for good measure. I'm not sure if it is my environment or the package itself, but I am giving up on trying to build this package. I am going to just build GCC 5.3.0 instead.

Leaving this open for now.

**Comment by lhmouse** [comment]
@BrisingrAerowing
It sounds strange. Which files were not found?

**Comment by mati865** [comment]
I cannot build GCC 6 git version. For 3 days it fails with:
```
==> Starting package_mingw-w64-x86_64-gcc-git()...
cp: cannot stat 'lib/gcc/x86_64-w64-mingw32/6.1.1/libvtv*': No such file or directory
==> ERROR: A failure occurred in package_mingw-w64-x86_64-gcc-git().
    Aborting...
```
Inside `src\build-x86_64-w64-mingw32\x86_64-w64-mingw32` there is libvtv directory but in `src\mingw64` there is nothing like libvtv.

I also noticed there is error about missing patch for gcc 6:
```
fatal: could not open '/d/projekty/msys2/build/testing/mingw-w64-gcc-git/src/0001-gcc-6-branch-gfortran-incorrect-reading-of-values-fr.patch' for reading: No such file or directory
```
And there is only `0001-gcc-5-branch-gfortran-incorrect-reading-of-values-fr.patch` in [mingw-w64-gcc-git](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-gcc-git) package.
I have installed base-devel, msys2-devel, and toolchains for both architectures.
I also have ccache enables but it's used only at beginning of compilation. I'll try without it when I find more time.

Here are logs:
makepkg-mingw: [mingw-w64-gcc-git.zip](https://github.com/Alexpux/MINGW-packages/files/253143/mingw-w64-gcc-git.zip)

build-x86_64-w64-mingw32: [archive.tar.gz](https://github.com/Alexpux/MINGW-packages/files/253144/archive.tar.gz)
Sorry for double compression, it wasn't planned.

**Comment by lhmouse** [comment]
@mati865 
Lack of gfortran patch is a known problem. I didn't touch the fortran part, but there have been a magical '|| true' in PKGBUILD on this line:
`git am "${srcdir}"/0001-${_branch}-gfortran-incorrect-reading-of-values-fr.patch || true`

Apparently the guy who made this patch didn't make one for the gcc-6-branch, and it was to be ignored for gcc-6-branch for some unknown reason.

**Comment by mati865** [comment]
@lhmouse
Probably better way to do it would be like in Qt packge https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-qt5/PKGBUILD#L294

Missing libvtv case is still open. Also there are 3 failures in build log:
```
Makefile:1461: recipe for target 'stamp-bits-sup' failed
make[3]: [stamp-bits-sup] Error 1 (ignored)
```

**Comment by lhmouse** [comment]
@mati865

When I built GCC I also got those stamp-bits-sup errors and there seemed no harm to ignore them, just as 'make' does.

**Comment by lhmouse** [comment]
@mati865 

Confirmed with @mingwandroid yesterday. The gfortran patch is unneeded for gcc-6-branch and master.

> [21:25:57] <lh_mouse> mingwandroid, meow.
> [21:26:22] <lh_mouse> did you make a gfortran patch for gcc-6-branch?
> [21:26:24] <mingwandroid> lh_mouse: woof. naah, actually, squeek.
> [21:26:55] <mingwandroid> lh_mouse: there shouldn't be any need AFAIK, the guy who fixed the bug committed to the 6 branch and master branch.

**Comment by mati865** [comment]
I still cannot get it to compile. Fresh MSYS2 with base-devel and mingw-w64 toolchain also fails in `package()` with error `libvtv*: No such file or directory`.

**Comment by Alexpux** [comment]
Well need to see why this libraries not builded. Maybe need change configure parameters

**Comment by mati865** [comment]
@Alexpux logs are attached in this comment https://github.com/Alexpux/MINGW-packages/issues/1374#issuecomment-217582069

**Comment by Alexpux** [comment]
I will check when have time.

**Comment by mati865** [comment]
I have to test configure option `--enable-vtable-verify` but I don't have enough time to compile it for now.

**Comment by lhmouse** [comment]
> I have to test configure option --enable-vtable-verify but I don't have enough time to compile it for now.

I haven't been enabling it explicitly and the library is always built after all.

**Comment by mati865** [comment]
> I haven't been enabling it explicitly and the library is always built after all.

According to GCC [wiki](https://gcc.gnu.org/wiki/vtv):

> Builds must be configured to explicitly enable vtable verification.

I've enabled vtv and compilation failed with undefined references http://gcc.1065356.n5.nabble.com/Port-of-VTV-for-Cygwin-and-MinGW-td1064332.html

Log: [mingw-w64-gcc-git-r145779.fbcdb72-1-x86_64-build.log.zip](https://github.com/Alexpux/MINGW-packages/files/275215/mingw-w64-gcc-git-r145779.fbcdb72-1-x86_64-build.log.zip)

**Comment by tkelman** [comment]
Weak symbols did have some cyg/ming changes between gcc 5 and 6, that were related to fixing the bug with 5 that would miscompile LLVM IIRC.

**Comment by mingwandroid** [comment]
There's also been changes to binutils recently around weak symbol support for PECOFF targets.

**Comment by mati865** [comment]
Arch doesn't use `--enable-vtable-verify` and have `libvtv` in `gcc-libs`. I'll try with GCC 5 soon.
Windows 10 x86_64

**Comment by lhmouse** [comment]
@mati865 

Yes I know GCC wiki says vtv should be enabled explicitly. But I suggest you disable it and see whether vtv works. I don't know why the library is built despite the disability of vtv.

**Comment by mati865** [comment]
@lhmouse 
On Arch with GCC 6.1 compiled without it have `libvtv.so`, libvtv.so.0` and `libvtv.so.0.0.0`. However it cannot compile code with `fvtable-verify=std`.
On Windows compiling MinGW GCC 6.1 doesn't produce any `libvtv*` files. It fails at `package()` due to `libvtv*: No such file or directory`.

**Comment by Alexpux** [comment]
Currently you can comment this linehttps://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gcc-git/PKGBUILD#L275
to skip this issue

**Comment by mati865** [comment]
@Alexpux 
Yes I know but there must be reason why this file is generated on Linux and other Msys environments.

**Comment by lhmouse** [comment]
@mati865

I do have libvtv-0.dll built. I don't know what happened though. XD

**Comment by mati865** [comment]
@lhmouse 

Did you do 32-bit or 64-bit build.

**Comment by lhmouse** [comment]
@mati865 

Both.

**Comment by lhmouse** [comment]
libvtv wasn't built. `configure` didn't return an error, but the `Makefile` does nothing.

**Comment by lhmouse** [comment]
FWIW, libvtv is now excluded from the package. I am now going to make a full bootstrap of toolchains of all languages for i686 and x86_64 and push a patch later. This is going to take hours.

**Comment by mati865** [comment]
@lhmouse 

About libvtv https://gcc.gnu.org/ml/gcc-patches/2016-05/msg00094.html
Makefile:
```
...
if ENABLE_VTABLE_VERIFY
  toolexeclib_LTLIBRARIES = libvtv.la
if VTV_CYGMIN
  toolexeclib_LTLIBRARIES += libvtv_stubs.la
endif
endif
...
```

**Comment by lhmouse** [comment]
@mati865 

Currently we don't have VTV enabled so removing VTV DLL should be fine. Nonetheless, patches are welcome.

**Comment by lhmouse** [comment]
@mati865 

The `libvtv` library is still not built, nor is `libvtv_stubs`. The libvtv-0.dll` that comes with gcc-5 seems not exporting anything, which might explain why it is no longer built.

**Comment by mati865** [comment]
I was able to build binutils (had to install dlfcn) and libtool with GCC 6 and then recompile GCC 6. I think it would be ok to create repo testing or something like that and provide at least core packages build with GCC 6 to test if it's stable enough.
