### ISSUE TITLE
__STDC_CONSTANT_MACROS not sufficient to compile fixed-width integer constant macros under C++98

### ISSUE THREAD

**Issue by geimer** [Alexpux/MINGW-packages#1399]
The following minimal test code

```
#define __STDC_CONSTANT_MACROS
#include <stdint.h>

int main(int argc, char** argv)
{
    int8_t var = INT8_C(42);
    return 0;
}
```

does not compile with `g++` under Msys2/MinGW-w64:

```
$ g++ -c main.cpp
In file included from C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/5.3.0/include/stdint.h:9:0,
                 from main.cpp:2:
main.cpp: In function 'int main(int, char**)':
main.cpp:6:18: error: 'INT_LEAST8_MAX' was not declared in this scope
     int8_t var = INT8_C(42);
                  ^
```

The culprit is that the definition of `INT8_C` relies on `INT_LEAST8_MAX`, which is only available if `__STDC_LIMIT_MACROS` is defined as well.  However, according to the C99 standard (§7.18.4), defining `__STDC_CONSTANT_MACROS` should be sufficient to make the constant macros work under C++ (more precisely C++98).

I know that the problem vanishes when compiling in C++11 mode.  On the other hand, the footnotes about defining `__STDC_(CONSTANT|FORMAT|LIMIT)_MACROS` were removed with C11, and thus, newer versions of glibc don't require their use anymore and define the corresponding macros unconditionally so that they work out-of-the-box even in C++98 mode.  Maybe this is the way to go?

**Comment by geimer** [comment]
> On the other hand, the footnotes about defining __STDC_(CONSTANT|FORMAT|LIMIT)_MACROS were removed with C11, and thus, newer versions of glibc don't require their use anymore and define the corresponding macros unconditionally so that they work out-of-the-box even in C++98 mode. Maybe this is the way to go?

Well, "newer versions" is relative... For reference, here is the glibc ticket (with reference to the discussion on the mailing list):
https://sourceware.org/bugzilla/show_bug.cgi?id=15366
and the corresponding commit:
https://sourceware.org/git/?p=glibc.git;a=commit;h=1ef74943ce2f114c78b215af57c2ccc72ccdb0b7

**Comment by mati865** [comment]
No problem compiling it in Arch Linux with GCC 6.1 and `-std=gnu++98`.

**Comment by nak5124** [comment]
> No problem compiling it in Arch Linux with GCC 6.1 with -std=gnu++98 and glibc 2.23-2.
> Isn't is rather problem of MinGW w64 than Msys2?

MinGW-w64 GCC 6.1.0 which I built by myself can compile it without any error.

**Comment by geimer** [comment]
Installed msys2-x86_64 from https://msys2.github.io and then ran `pacman -S mingw-w64-x86_64-gcc`. This installed GCC 5.3 which gives me the above error.
