### ISSUE TITLE
/mingw32/bin/gtk-update-icon-cache-3.0.exe permission denied

### ISSUE THREAD

**Issue by KrullKorg** [Alexpux/MINGW-packages#141]
i don't know if it is a bug of mingw or in upstream, but executing /mingw32/bin/gtk-update-icon-cache-3.0.exe i get "permission denied"

**Comment by elieux** [comment]
Does this still happen?

**Comment by KrullKorg** [comment]
it works!!!

**Comment by maoueh** [comment]
@KrullKorg Great news :) can we close this issue then.
