### ISSUE TITLE
libzip failure due to rename failure

### ISSUE THREAD

**Issue by omichel** [Alexpux/MINGW-packages#1418]
I debugged a problem encoutered while using libzip to create ZIP files programmatically. My program create a ZIP file, then adds new files one-by-one to this existing archive. It is not working on MSYS2 whereas it is working nicely on Linux and Mac OS X.

It turned out that at some point libzip tries to rename a temporary file using the system `rename` function (http://man7.org/linux/man-pages/man2/rename.2.html) and this function behaves wrongly in MSYS2. If the `newpath` already exists, the function should siliently atomically overwrite it (according to the man page). However, on MSYS2, the function simply fails in that case, thus breaking libzip in `zip_source_filep.c` line 245 (libzip version 1.0.1).

Since `rename()` is a widely used system function, I would not be surprized that this could be the source of many bugs in MSYS2.

**Comment by mingwandroid** [comment]
Are you using POSIX or native here? If native you can't expect POSIX semantics (instead check msdn documentation). If POSIX, report the issue to Cygwin.

**Comment by omichel** [comment]
I don't understand what do mean.

I am simply trying to use the libzip package from https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-libzip and it turns out to be broken.

I found the cause of the problem: it seems this package is compiled to make use of the POSIX `rename()` function which doesn't behave properly on MSYS2.

We can easily fix libzip by adding a call to `unlink()` just before the call to `rename()` in the libzip package (I can send you a patch) or we can fix the behavior of the `rename()` POSIX function (that seems more complicated as I am not sure how to report the issue to Cygwin and I don't have a patch for that).

**Comment by mingwandroid** [comment]
You aren't using the POSIX layer (`gcc -dumpmachine` doesn't give `x86_64-pc-msys` or `i686-pc-msys`). You are using native compilers which means you are linking to the WIN32 API which means largely not POSIX at all, so the `rename` function you are calling is not a POSIX function which is why I recommended you to look at the documenation on MSDN: 
https://msdn.microsoft.com/en-us/library/zw5t957f.aspx

.. where you would read:

`The new name must not be the name of an existing file or directory`

None of this has anything to do with MSYS2 since we didn't write WIN32 APIs `rename`.

Is there still any misunderstanding?

**Comment by mingwandroid** [comment]
If you want to make a patch to do this go ahead, but ideally you should report it to the people who wrote the software: http://www.nih.at/libzip/index.html

**Comment by omichel** [comment]
Yes, you are perfectly right. Thank you for the clarification! I stupidly assumed that the Win32 `rename` function was POSIX which is obviously wrong. I will send my patch to the authors of libzip as you suggest.

**Comment by mingwandroid** [comment]
Great. We would appreciate the patch in the meantime with a link to the upstream bug report of possible, so please make a PR.

**Comment by omichel** [comment]
All right. I am currently checking my patch with the authors (by e-mail since I didn't find an online bug reporting tool). I will get back here once I am sure the patch is correct and accepted by the authors.

**Comment by omichel** [comment]
Ok, the issue is sorted out. It actually came from a bug in the configure script which made it unable to recognize the win32 platform and made that the rename() function was called whereas it should not be called on the Windows platform. The current mercurial version of libzip fixes this bug. However, the latest public release of libzip source code (version 1.1.2) has the configure bug. The version currently used by MINGW is version 1.0.1 (where the bug was already there). I believe that applying this patch: http://hg.nih.at/libzip/rev/536d63060341 on version 1.1.2 might fix the bug we have on MSYS2.

I will open a new PR to try to make such a patch.

**Comment by omichel** [comment]
Ok, I did the PR #1428, but it seems it doesn't pass the CI test, I am not sure why. Can you check it?
