### ISSUE TITLE
Can't build firefox on AppVeyor

### ISSUE THREAD

**Issue by Endle** [Alexpux/MINGW-packages#1419]
I added a [stub patch](https://github.com/Endle/MINGW-packages-firefox-ci/commit/9f3e5270bc8860cc8c2640a6a3b5373c75421f0e) to trigger AppVeyor, and the CI failed:

https://ci.appveyor.com/project/Endle/mingw-packages-firefox-ci/build/1.0.6

**Comment by Endle** [comment]
Seems @mingwandroid is the maintainer?
Is there any known issues for msys2 on AppVeyor?

**Comment by Alexpux** [comment]
Firefox WIP package. It not buildable right now

**Comment by mati865** [comment]
I don't think you will be able to build Firefox in AppVeyor even after fixing all of the issues since there is 1 hour quota. After reaching it build fails.

**Comment by lazka** [comment]
No one has worked on the firefox PKGBUILD since this was opened, so not much we can do here.
