### ISSUE TITLE
glib2-git patch problem?

### ISSUE THREAD

**Issue by bluecd** [Alexpux/MINGW-packages#1431]
Win10-64 on MSYS2: Can't build gtk3-git because of glib2-git patch problem: /Trim-remove if doubled issue,pls/

==> Starting prepare()...
patching file glib/gstdio.c
patching file glib/gbacktrace.c
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file glib/gbacktrace.c.rej
patching file glib/giowin32.c
Reversed (or previously applied) patch detected!  Skipping patch.
7 out of 7 hunks ignored -- saving rejects to file glib/giowin32.c.rej
patching file glib/gmessages.c
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file glib/gmessages.c.rej
patching file glib/gslice.c
Hunk #1 succeeded at 1106 (offset 24 lines).
Hunk #2 succeeded at 1191 (offset 26 lines).
Hunk #3 succeeded at 1212 (offset 26 lines).
Hunk #4 succeeded at 1226 (offset 26 lines).
Hunk #5 succeeded at 1462 (offset 26 lines).
patching file glib/gtester.c
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file glib/gtester.c.rej
patching file glib/gtestutils.c
Reversed (or previously applied) patch detected!  Skipping patch.
3 out of 3 hunks ignored -- saving rejects to file glib/gtestutils.c.rej
patching file glib/gthread-posix.c
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file glib/gthread-posix.c.rej
patching file glib/gthread-win32.c
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file glib/gthread-win32.c.rej
patching file glib/gutils.c
Hunk #1 FAILED at 2375.
1 out of 1 hunk FAILED -- saving rejects to file glib/gutils.c.rej
patching file glib/gutils.h
Hunk #1 succeeded at 193 (offset -35 lines).
==> ERROR: Error occured in prepare().
    Stopping...

**Comment by mati865** [comment]
`glib2-git` isn't actively maintained, you should use release version or fix patches.

**Comment by bluecd** [comment]
OK, how could I build glib2 2.49-1 version?

**Comment by mati865** [comment]
Since 2.49 is not released yet you will have to fix patches for git version.

**Comment by bluecd** [comment]
Since we got so far...would you be kind to advice which patches, where and how should I apply to achieve gtk-git (which needs glib2 >=2.49-1, its about Mypaint debugging w/Gtk and Wintab fatal errors.

**Comment by lazka** [comment]
@bluecd is this still an issue?

glib2 is now at 2.54.3 and glitb2-git has been updated/fixed in the meantime in #2689 (it might have gotten out of sync again, not sure)

**Comment by lazka** [comment]
Assuming this is fixed. I have some meson stuff queued for glib, so glib2-git is on my list to update sometime..
