### ISSUE TITLE
64 bit openblas-git builds failed

### ISSUE THREAD

**Issue by fracting** [Alexpux/MINGW-packages#1432]
Unfortunately the build log on Tea CI ( https://tea-ci.org/Alexpux/MINGW-packages/771 ) is longer than the database storage size, so there's no full log for openblas-git on CI server. I manually build on my machine, and found:

```
make[1]: Entering directory '/z/home/fracting/src/MINGW-packages-fracting/mingw-w64-OpenBLAS-git/src/build-x86_64/test'
gfortran -Wall -m64  -o sblat1 sblat1.obj ../libopenblas_sandybridgep-r0.2.19.dev.a -defaultlib:advapi32 -lgfortran -defaultlib:advapi32 -lgfortran
../libopenblas_sandybridgep-r0.2.19.dev.a(memory.obj):memory.c:(.text+0x358): undefined reference to `gotoblas_dynamic_init'
../libopenblas_sandybridgep-r0.2.19.dev.a(memory.obj):memory.c:(.text+0x42d): undefined reference to `gotoblas_dynamic_init'
../libopenblas_sandybridgep-r0.2.19.dev.a(memory.obj):memory.c:(.text.startup+0x19): undefined reference to `gotoblas_dynamic_init'
Makefile:129: recipe for target 'sblat1' failed
```

32 bit builds fine.

@mingwandroid are you able to confirm, or is there any problem with my environment? Just make sure this issue won't be ignored, I'm not a user of openblas by myself ;)

**Comment by mingwandroid** [comment]
I believe there is a race condition on the openblas build system, however building it single threaded takes hours. I will try to find time to investigate further in a week or two.
