### ISSUE TITLE
gdal: Missing dependencies

### ISSUE THREAD

**Issue by Krakonos** [Alexpux/MINGW-packages#1439]
Running cygcheck on libgdal-20.dll, I get (among others) this result:

cygcheck: track_down: could not find libnetcdf.dll
cygcheck: track_down: could not find libnspr4.dll
cygcheck: track_down: could not find nss3.dll
cygcheck: track_down: could not find smime3.dll
cygcheck: track_down: could not find LIBPQ.dll

It would seem that gdal depends on -postgres and -netcdf, libpoppler depends on -nspr and -nss, none of them are listed as dependencies.

Tested a while ago on Tea-Ci.org.

**Comment by lazka** [comment]
Please open a PR adding the missing dependencies (assuming this is still a problem)
