### ISSUE TITLE
mingw-w64-x86_64-emacs: Launching emacs fails with error message due to missing libMagickCore-6.Q16HDRI-2.dll

### ISSUE THREAD

**Issue by maehne** [Alexpux/MINGW-packages#1453]
Launching the Emacs version from the mingw-w64-x86_64-emacs fails in the MinGW-w64 shell as well as from Windows explorer with similar error messages:

In the shell, the following error is displayed:

```
$ emacs
C:/msys64/mingw64/bin/emacs.exe: error while loading shared libraries: libMagickWand-6.Q16HDRI-2.dll: cannot open shared object file: No such file or directory
```

Launching from Windows explorer causes a system error window to pop up stating:

"The program can't start because libMagickCore-6.Q16HDRI-2.dll is missing from your computer. Try reinstalling the program to fix this problem."

The DLL seems to belong to ImageMagick of wich the following version is installed by pacman:

```
$ pacman -Ss magick
mingw32/mingw-w64-i686-graphicsmagick 1.3.24-1
    An image viewing/manipulation program (mingw-w64)
mingw32/mingw-w64-i686-imagemagick 7.0.1.8-1
    An image viewing/manipulation program (mingw-w64)
mingw64/mingw-w64-x86_64-graphicsmagick 1.3.24-1
    An image viewing/manipulation program (mingw-w64)
mingw64/mingw-w64-x86_64-imagemagick 7.0.1.8-1 [installed]
    An image viewing/manipulation program (mingw-w64)
```

Maybe the Emacs package just needs to be rebuilt to link to this new ImageMagick version?

**Comment by mati865** [comment]
Update to imagemagic changed `libMagickCore-6.Q16HDRI-2.dll` to `libMagickCore-7.Q16HDRI-0.dll`.
Rebuild fixes issue.
Pinging @Alexpux for pkgver bump.

**Comment by dlrourke** [comment]
When will the new emacs (referring to ImageMagick 7 rather than 6) be available via pacman?

**Comment by Alexpux** [comment]
@dlrourke be patient, this is free time project.
If you need fixed emacs right now you can build it locally yourself

**Comment by dlrourke** [comment]
Didn't mean to be a nudge; sorry.  After I found Alexpux/MINGW-packages, I did build my own.  Very elegant and nearly painless; thank you.  Even though the version of Emacs is X64, I686 versions of ctags and ImageMagick appear to be runtime dependencies.  Is this intentional?

**Comment by elieux** [comment]
@dlrourke, I think that was just `makepkg-mingw` wanting to build for both architectures.

Anyway, currently emacs doesn't support ImageMagick v7, so although it doesn't crash with missing DLLs, it doesn't process images either. Tracking that over at https://sourceforge.net/p/msys2/tickets/270/.
