### ISSUE TITLE
mingw-w64-x86_64-perl: patch for batch file removal should not be applied

### ISSUE THREAD

**Issue by zmughal** [Alexpux/MINGW-packages#1463]
When build scripts for Perl modules are run, many of them use ExtUtils::MakeMaker. The code for that [expects that pl2bat.bat is available](https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/blob/v7.19_01/lib/ExtUtils/MM_Win32.pm#L145-L147).

This is why applying the patch [003-replace-batch-scripts-with-bare-perl.patch](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-perl/003-replace-batch-scripts-with-bare-perl.patch) can break the installation of many Perl modules (change introduced in https://github.com/Alexpux/MINGW-packages/pull/412).

For example, if I install `App::cpanminus` using the CPAN client:

``` shell
yes | cpan App::cpanminus
```

I get the error

```
   Configuring M/MI/MIYAGAWA/App-cpanminus-1.7040.tar.gz with Makefile.PL
   Checking if your kit is complete...
   Looks good
   Generating a dmake-style Makefile
   Writing Makefile for App::cpanminus
   Writing MYMETA.yml and MYMETA.json
     MIYAGAWA/App-cpanminus-1.7040.tar.gz
     C:\msys64\mingw64\bin\perl.exe Makefile.PL -- OK
   Running make for M/MI/MIYAGAWA/App-cpanminus-1.7040.tar.gz
   cp lib/App/cpanminus/fatscript.pm blib\lib\App\cpanminus\fatscript.pm
   cp lib/App/cpanminus.pm blib\lib\App\cpanminus.pm
   "C:\msys64\mingw64\bin\perl.exe" -MExtUtils::Command -e cp -- bin/cpanm blib\script\cpanm
   pl2bat.bat blib\script\cpanm
   'pl2bat.bat' is not recognized as an internal or external command,
   operable program or batch file.
   dmake:  Error code 129, while making 'blib\script\cpanm'
   dmake:  'blib\script\cpanm' removed.
     MIYAGAWA/App-cpanminus-1.7040.tar.gz
     dmake -- NOT OK
```

A workaround is to run

``` shell
pl2bat $(which pl2bat)
```

to create `pl2bat.bat`, but the file should be installed in the first place.

CC: https://github.com/project-renard/curie/issues/119.

**Comment by renatosilva** [comment]
Simply removing the patch is a poor suggestion, since batch wrappers are pointless. MakeMaker does not need to use or generate them. This is an example of the general fact that projects are not used to good environments like MSYS2. Note also that Perl modules are supposed to be packaged instead of being managed by cpan. You can contribute a MINGW package for MakeMaker and send patches upstream, they have demonstrated interest in improvements.

**Comment by zmughal** [comment]
Thanks for the insight. Patching EU::MM sounds like a much better approach. I'll keep tabs on this issue and see if I can whip up a fix for EU::MM.

**Comment by BrisingrAerowing** [comment]
Another way is to create simple batch file wrappers for the Perl utilities, e.g.

```text
perl pl2bat %*
```

in pl2bat.bat

That shouldn't be to difficult to add as a post-build step in the PKGBUILD.

Granted, patching MakeMaker is best in the long run, but having batch files may be useful for other things as well (e.g. using directly from the Win32 command prompt).
