### ISSUE TITLE
Update GLFW to 3.2

### ISSUE THREAD

**Issue by matanui159** [Alexpux/MINGW-packages#1465]
This is just a quick request. Recently GLFW updated to 3.2 and it adds some interesting features I would like to use. Would you be able to update it if you get a chance?

I myself am not really good at package building (thats why I ended up using MSYS2 in the first place :stuck_out_tongue_winking_eye: )

**Comment by DavidEGrayson** [comment]
glfw 3.2 is available via pacman now.

**Comment by lazka** [comment]
glfw 3.2.1 is in the repo atm
