### ISSUE TITLE
gpg BAD signature docbook-xsl-1.78.1-3.src.tar.gz

### ISSUE THREAD

**Issue by yellowboxtext** [Alexpux/MINGW-packages#1487]
Files:

> https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/Sources/docbook-xsl-1.78.1-3.src.tar.gz
> https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/Sources/docbook-xsl-1.78.1-3.src.tar.gz.sig

Imported key https://raw.githubusercontent.com/Alexpux/MSYS2-keyring/master/msys2.gpg

> gpg: Signature made 12/08/14 18:18:15 Ekaterinburg Standard Time using DSA key ID A47D45A1
> gpg: BAD signature from "Alexey Pavlov (Alexpux) alexpux@gmail.com" [unknown]

gpg version:

> gpg (GnuPG) 2.1.12

sha1sum:

> fcaa071c13a5ce41c92336c719671b70b045b6f8  docbook-xsl-1.78.1-3.src.tar.gz
> 52cdf2eaa587b6b2120ad02dff89198580789fc1  docbook-xsl-1.78.1-3.src.tar.gz.sig

**Comment by Alexpux** [comment]
GnuPG 2 not work ok with MSYS2 so we have previous version of it.

**Comment by yellowboxtext** [comment]
Version:
gpg (GnuPG) 1.4.20

Verify:
gpg: Signature made 12/08/14 18:18:15 using DSA key ID A47D45A1
gpg: BAD signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>"

**Comment by yellowboxtext** [comment]
Full log using "gpg (GnuPG) 1.4.20":


**gpg --homedir . --import msys2.gpg**

gpg: keyring `.\secring.gpg' created
gpg: keyring `.\pubring.gpg' created
gpg: .\trustdb.gpg: trustdb created
gpg: key CA25678A: public key "Alexey Pavlov (Alexpux) <alexey.pawlow@gmail.com>" imported
gpg: key AEEA755C: public key "Martell Malone (martell) <martellmalone@gmail.com>" imported
gpg: key 3E0D0813: public key "Ray Donnelly (MSYS2 Developer - master key) <mingw.android@gmail.com>"
imported
gpg: key 3E652008: public key "Ignacio Casal Quinteiro <icquinteiro@gmail.com>" imported
gpg: key A47D45A1: public key "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" imported
gpg: key 2C51581E: public key "Martell Malone (MSYS2 Developer) <martellmalone@gmail.com>" imported
gpg: key 4CA56930: public key "Ray Donnelly (MSYS2 Developer) <mingw.android@gmail.com>" imported
gpg: Total number processed: 7
gpg:               imported: 7  (RSA: 6)
gpg: no ultimately trusted keys found



**gpg --homedir . --verify docbook-xsl-1.78.1-3.src.tar.gz.sig docbook-xsl-1.78.1-3.src.tar.gz**

gpg: Signature made 12/08/14 18:18:15 using DSA key ID A47D45A1
gpg: BAD signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>"
