### ISSUE TITLE
Make include doesn't work with variables.

### ISSUE THREAD

**Issue by nyz93** [Alexpux/MINGW-packages#1495]
The following Makefile complains about b.mk not existing, even if it does.
```
BASE:=$(shell pwd)
include ${BASE}/b.mk
```
It doesn't matter how I try to create the path, if there is a variable in the include expression it's going to fail.

**Comment by DavidEGrayson** [comment]
It works for me using `make` (/usr/bin/make).  Could you post a concise shell session that shows how you reproduced this issue?  Which version of make are you using?

**Comment by nyz93** [comment]
I see, I was trying with mingw32-make. I guess this is one of the reasons why it has that prefix.
It does work with msys make.
