### ISSUE TITLE
jq is missing a dependency on oniguruma

### ISSUE THREAD

**Issue by dgbustos** [Alexpux/MINGW-packages#1503]
I installed jq, but running it failed with

     C:/msys64/mingw64/bin/jq.exe: error while loading shared libraries: libwinpthread-1.dll: cannot open shared object file: No such file or directory

Double-clicking from Windows Explorer indicated it was looking for `libonig-2.dll`.  So I installed `oniguruma` and now it works.

**Comment by vszakats** [comment]
I'd add that installing `oniguruma` now (at version 6.0.0-1) installed `libonig-3.dll`, so running `jq` (1.5-1) fails to run with this error:
```
jq.exe: error while loading shared libraries: libonig-2.dll: cannot open shared object file: No such file or directory
```

**Comment by Den-dp** [comment]
@vszakats Maybe this is not a best solution but the following works for me
```
pacman -S mingw-w64-x86_64-jq
pacman -S mingw-w64-x86_64-oniguruma
pacman -D --asdep mingw-w64-x86_64-oniguruma
cp /mingw64/bin/libonig-3.dll /mingw64/bin/libonig-2.dll
```

**Comment by vszakats** [comment]
Thanks @Den-dp, the `cp` was enough to make it work in my installation.

**Comment by gertcuykens** [comment]
Can this be reopend I think its broken again?
![image](https://user-images.githubusercontent.com/863731/49486731-eeedf380-f83f-11e8-96d1-c4ab498f77e9.png)

**Comment by gertcuykens** [comment]
pacman -S mingw-w64-x86_64-libwinpthread is needed for jq aparently
