### ISSUE TITLE
mingw-w64-x86_64-make is missing a dependency on make.

### ISSUE THREAD

**Issue by jrmoore** [Alexpux/MINGW-packages#1517]
I'm just starting out with MSYS2 and it seems that package is missing a dependency on make.

Unless... base-devel members are implied dependencies and don't need to be added? If that's the case, I think adding make as a dependency for that package wouldn't hurt though.

$ mingw32-make.exe
make  all-recursive
process_begin: CreateProcess(NULL, make all-recursive, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:370: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by DavidEGrayson** [comment]
I don't think mingw32-make depends on `make` at runtime. It looks like you are using a Makefile that is invoking `make` recursively; you should modify it to run `mingw32-make`.  It's hard to give advice on how to modify the Makefile without seeing it.

**Comment by jrmoore** [comment]
Thank you for the reply David!

It seems you're right, the Makefile was indeed using `make` instead which is why it failed since I didn't have that package installed:

`MAKE=make`

I thought I needed to use the mingw-w64-x86_64 package though, that for some reason using the regular `make` package would fail. I am new to MSYS2 and installing the 64-bit mingw-w64 toolchain the one for `make` came along.

Since this is a non issue it can be closed already.

**Comment by DavidEGrayson** [comment]
I can't close this issue, but you can.
