### ISSUE TITLE
imagemagick 7.0.2-2

### ISSUE THREAD

**Issue by jeroen** [Alexpux/MINGW-packages#1534]
Notes for updating to imagemagick 7.0.2.2 (didn't have time to write a patch yet):
- `locale.c` line 133 needs `&& !defined(__MINGW32__)` just like the current patch does for line 260
- `PKGBUILD` configure option `--without-ltdl` seems deprecated/unrecognized
- `PKGBUILD` configure option `--without-lcms2` should be `--without-lcms`
-  Removed `#include <intsafe.h>` from `thread_.h` to build on gcc 4.9.3
- Added`LIBS="-lOleAut32"`

**Comment by jeroenooms** [comment]
Upstream patches applied: https://github.com/ImageMagick/ImageMagick/commit/360889c1650bd82cff29db568cee55949314d543

**Comment by peterbud** [comment]
@jeroenooms can you check the latest update to the package #1905 and close the issue if it works well?

**Comment by lazka** [comment]
Since there hasn't been a response and there were quite a few imagemagick updates/releases in the meantime I'm closing this for now.
