### ISSUE TITLE
qt5-git package

### ISSUE THREAD

**Issue by aquiles2k** [Alexpux/MINGW-packages#1538]
Hi i tried to build the qt5-git package. For that i copied the mingw-w64-qt5-git dir into my home dir and cd'ed into it then starting it with makepkg-mingw -sLf

It failes quite early after configuring the build with:

```
g++ -x c++-header -c -std=c++11 -fno-rtti -fno-exceptions -mthreads -Wall -Wextra -DUNICODE -DQT_NO_DATASTREAM -DQT_NO_CODECS -DQT_NO_TEXTCODEC -DQT_NO_UNICODETABLES -DQT_LITE_COMPONENT -DQT_NO_COMPRESS -DQT_NO_THREAD -DQT_NO_QOBJECT -DQT_NO_GEOM_VARIANT -D_CRT_SECURE_NO_DEPRECATE -DQT_BOOTSTRAPPED -DQT_BUILD_CONFIGURE -DQT_USE_QSTRINGBUILDER -DQT_VERSION_STR=\"5.7.0\" -DQT_VERSION_MAJOR=5  -DQT_VERSION_MINOR=7  -DQT_VERSION_PATCH=0  -I"../../include" -I"../../include/QtCore" -I"../../include/QtCore/5.7.0" -I"../../include/QtCore/5.7.0/QtCore" -I"D:/Dev/msys64/home/adrian/mingw-w64-qt5-git/src/qt5/qtbase/tools/shared" -I"D:/Dev/msys64/home/adrian/mingw-w64-qt5-git/src/qt5/qtbase/mkspecs/win32-g++" -o configure_pch.h.gch/c++ D:/Dev/msys64/home/adrian/mingw-w64-qt5-git/src/qt5/qtbase/tools/configure/configure_pch.h
In file included from D:/Dev/msys64/home/adrian/mingw-w64-qt5-git/src/qt5/qtbase/mkspecs/win32-g++/qplatformdefs.h:51:0,
                 from D:/Dev/msys64/home/adrian/mingw-w64-qt5-git/src/qt5/qtbase/tools/configure/configure_pch.h:34:
../../include/QtCore/qglobal.h:1:118: fatal error: ../../../../../../../../../../../home/adrian/mingw-w64-qt5-git/src/qt5/qtbase/src/corelib/global/qglobal.h: No such file or directory
compilation terminated.
Makefile:123: recipe for target 'configure_pch.h.gch/c++' failed
mingw32-make: *** [configure_pch.h.gch/c++] Error 1
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...

```

See http://pastebin.com/CescYTbe

What can i do to resolve this?

**Comment by mati865** [comment]
`WARNING: To install it run: 'pacman -S mingw-w64-x86_64-toolchain'`
Use
```
pacman --needed -S mingw-w64-x86_64-toolchain mingw-w64-i686-toolchain
```

**Comment by aquiles2k** [comment]
Its a warning not an error and i have already installed the i686 toolchain. Is it really necessary to install the x86_64 toolchain?

**Comment by mati865** [comment]
If you use 64 bit MSYS2 `makepkg-mingw` will build 64 bit package first and after that 32 bit.
In case you want to build 32 bit package only use `MINGWINSTALLS=mingw32 makepkg-mingw`, if you want 64 bit only then replace mingw32 with mingw64.

**Comment by aquiles2k** [comment]
Hm just for the sake of it i installed the x86_64 toolchain and also tried MINGWINSTALLS. Both didnt work either.

See http://pastebin.com/HFHQ9VRf

For clarity, i start msys through "msys2_shell.cmd" in the root folder if that makes a difference.

Any stuff i should check?

Thanks for your time so far - much appreciated :)

**Comment by mati865** [comment]
You can try asking on IRC, probably a upstream commit broken some patches. Currently I'm out of time to investigate it but I'll take a look into it later today.
Lets ping @mcallegari

**Comment by mati865** [comment]
@aquiles2k remove .bat from `configure.bat` in the PKGBUILD.

**Comment by mati865** [comment]
@Alexpux, @mcallegari  shouldn't we use `configure` instead of `configure.bat`?
At least for qt5-git ./configure.bat calls qtbase/configure.bat which then sets make to MSVC namke:
```
set make=nmake
if not "%jom.exe%" == "" set make=jom
```
This causes fail (at least for me): https://gist.github.com/mati865/42885a5fcdb1e2b06973ddacf8884748

**Comment by aquiles2k** [comment]
So removing the .bat helped me getting past configuration but then it stops at compiling qtbase:

```
g++ -c -pipe -fno-keep-inline-dllexport -march=nocona -mtune=core2 -Wa,-mbig-obj -ffunction-sections -O2 -std=gnu++1z -fno-exceptions -frtti -Wall -Wextra -DUNICODE -DQT_NO_MTDEV -DQT_NO_DYNAMIC_LIBRARY -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_TSLIB -DQT_NO_LIBINPUT -DQT_BOOTSTRAPPED -DQT_LITE_UNICODE -DQT_NO_CAST_TO_ASCII -DQT_NO_CODECS -DQT_NO_DATASTREAM -DQT_NO_LIBRARY -DQT_NO_QOBJECT -DQT_NO_SYSTEMLOCALE -DQT_NO_THREAD -DQT_NO_UNICODETABLES -DQT_NO_USING_NAMESPACE -DQT_NO_DEPRECATED -DQT_NO_TRANSLATION -DQT_CRYPTOGRAPHICHASH_ONLY_SHA1 -DQT_NO_FOREACH -DQT_NO_CAST_FROM_ASCII -DQT_BUILD_BOOTSTRAP_LIB -DQT_BUILDING_QT -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -I. -I../../../include -I../../../include/QtCore -I../../../include/QtCore/5.7.0 -I../../../include/QtCore/5.7.0/QtCore -I../../../include/QtXml -I../../../include/QtXml/5.7.0 -I../../../include/QtXml/5.7.0/QtXml -Itmp -I../../../mkspecs/win32-g++  -o .obj/release/qxml.o ../../xml/sax/qxml.cpp
In file included from ../../xml/dom/qdom.cpp:41:0:
../../../include/QtXml/qdom.h:1:133: fatal error: ../../../../../../../../../../../../../home/adrian/dev/MINGW-packages/mingw-w64-qt5-git/src/qt5/qtbase/src/xml/dom/qdom.h: No such file or directory
compilation terminated.
In file included from ../../xml/sax/qxml.h:43:0,
                 from ../../xml/sax/qxml.cpp:40:
../../../include/QtXml/qtxmlglobal.h:1:136: fatal error: ../../../../../../../../../../../../../home/adrian/dev/MINGW-packages/mingw-w64-qt5-git/src/qt5/qtbase/src/xml/qtxmlglobal.h: No such file or directory
compilation terminated.
make[4]: *** [Makefile.Release:8841: .obj/release/qdom.o] Fehler 1
make[4]: *** Es wird auf noch nicht beendete Prozesse gewartet....
make[4]: *** [Makefile.Release:8972: .obj/release/qxml.o] Fehler 1
make[4]: Verzeichnis „/home/adrian/dev/MINGW-packages/mingw-w64-qt5-git/src/qt5/qtbase/src/tools/bootstrap“ wird verlassen
make[3]: *** [Makefile:34: release] Fehler 2
make[3]: Verzeichnis „/home/adrian/dev/MINGW-packages/mingw-w64-qt5-git/src/qt5/qtbase/src/tools/bootstrap“ wird verlassen
make[2]: *** [Makefile:61: sub-bootstrap-make_first] Fehler 2
make[2]: Verzeichnis „/home/adrian/dev/MINGW-packages/mingw-w64-qt5-git/src/qt5/qtbase/src“ wird verlassen
make[1]: *** [Makefile:42: sub-src-make_first] Fehler 2
make[1]: Verzeichnis „/home/adrian/dev/MINGW-packages/mingw-w64-qt5-git/src/qt5/qtbase“ wird verlassen
make: *** [Makefile:73: module-qtbase-make_first] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...

```

See https://gist.github.com/aquiles2k/378cdfc1e34d89f8ac8c0a0060eaaa67

Furthermore, even though i used your proposed MINGWINSTALLS=mingw32 configure states:

`Build type:    win32-g++ (x86_64, CPU features: cx16 mmx sse sse2 sse3)`

What do you mean by "Non git qt5 configure.bat is fine"? Should i take a configure.bat from their precompiled binaries?

**Comment by mati865** [comment]
> So removing the .bat helped me getting past configuration but then it stops at compiling qtbase:

I cannot really help here because I don't follow qt development, maybe @Alexpux, @mingwandroid or @mcallegari could help.

> Furthermore, even though i used your proposed MINGWINSTALLS=mingw32 configure states:
> 
> Build type: win32-g++ (x86_64, CPU features: cx16 mmx sse sse2 sse3)

I've been using it like that for long time but you can try `MINGW_INSTALLS=mingw32`

> What do you mean by "Non git qt5 configure.bat is fine"? Should i take a configure.bat from their precompiled binaries?

I mean can use configure.bat with [mingw-w64-qt5](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-qt5) package but [mingw-w64-qt5-git](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-qt5-git) configure.bat fails

**Comment by aquiles2k** [comment]
Ok, thx for your help anyway. I'll then wait if the other people you mentioned make a comment or the mingw-w64-qt5 package updates to qt5.7 at some point.

**Comment by stahta01** [comment]
I am working on updating the mingw-w64-qt5-git package to 5.8.x. Not really a Qt5 user, doing it to learn how to use git submodules with MSys2 mingw packages. Only trying to get package to build no plans to fix or even test for run-time issues. Tim S.

**Comment by stahta01** [comment]
@aquiles2k The error you got is like the error I was getting till I shortened the path used by the git repo.
The seems to be a max path length exceeded problem during building.

Tim S.

**Comment by revelator** [comment]
Should the flag not  be MINGW_INSTALLS= ?
