### ISSUE TITLE
Cargo for rust package

### ISSUE THREAD

**Issue by marcthe12** [Alexpux/MINGW-packages#1540]
Cargo is used in rust, it manage rust dependencies and provides a build system. To some extent it is similar to pip. It is no present a all either in rust package or another package. It makes life easy for rust. It is a part of rust lang itself. Add it as a separate package or add it to rust.

It was last mentioned in the issue #1016

**Comment by marcthe12** [comment]
#1016

**Comment by Gheoan** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/issues/1825.
