### ISSUE TITLE
Problem with mingw-w64-openocd-git/PKGBUILD

### ISSUE THREAD

**Issue by RoccoMarco** [Alexpux/MINGW-packages#1552]
Hi I am currently unable to build this package:
-bash-4.3$ cd ~/mingw-packages/mingw-w64-openocd-git
-bash-4.3$ makepkg --config ${MAKEPKG_CONFIG}
==> Making package: mingw-w64-openocd-git 0.9.0.r2.g79fdeb3-1 (Thu, Jul 14, 2016 11:09:02 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating openocd git repo...
Fetching origin
==> Validating source files with sha256sums...
    openocd ... Skipped
==> Extracting sources...
  -> Creating working copy of code git repo...
Reset branch 'makepkg'
==> Starting prepare()...
+ aclocal
+ libtoolize --automake --copy
+ autoconf
+ autoheader
+ automake --gnu --add-missing --copy
Makefile.am:23: warning: wildcard $(srcdir: non-POSIX variable name
Makefile.am:23: (probably a GNU make extension)
Setting up submodules
Cloning into '/home/RoccoMarco/mingw-packages/mingw-w64-openocd-git/src/openocd/src/jtag/drivers/libjaylink'...
      1 [main] git-remote-http 6676 child_info_fork::abort: C:\msys32\usr\bin\msys-iconv-2.dll: Loaded to different address: parent(0x520000) != child(0x640000)
error: cannot fork() for fetch-pack: Resource temporarily unavailable
fatal: clone of 'http://repo.or.cz/r/libjaylink.git' into submodule path '/home/RoccoMarco/mingw-packages/mingw-w64-openocd-git/src/openocd/src/jtag/drivers/libjaylink' failed
==> ERROR: A failure occurred in prepare().
    Aborting...

Is some one able to help me. A good starting point would be to understand if the problem is more related to PKGBUILD, MSYS2 or openocd. Thanks

**Comment by Alexpux** [comment]
This is common issue for 32-bit Cygwin/MSYS2. You must close all MSYS2 consoles and run autorebase.bat from MSYS2 directory. Then you can continue.

**Comment by mingwandroid** [comment]
Also, don't use 32-bit if you don't have to.
