### ISSUE TITLE
Gimp 2.9.4-1 doesn't find exchndl.dll

### ISSUE THREAD

**Issue by KrullKorg** [Alexpux/MINGW-packages#1554]
as object

**Comment by Alexpux** [comment]
That is strange. It also want libmypaint package.

**Comment by Alexpux** [comment]
I verify build log. Seems gimp need two new dependencies - drmingw and libmypaint. Will fix today.

**Comment by KrullKorg** [comment]
ok thanks, i didn't find where exchndl.dll was; i had found pidgin, but it seemed to me very strange that gimp depended on pidgin

i think gimp depends also on json-c
