### ISSUE TITLE
mingw-w64-x86_64-gimp 2.9.4-2 depends mingw-w64-x86_64-json-c 

### ISSUE THREAD

**Issue by ustsv** [Alexpux/MINGW-packages#1556]
mingw-w64-x86_64-gimp 2.9.4-2 has a dependency libjson-c-2.dll, bat PKGBUILD not.
[-] Add mingw64/mingw-w64-x86_64-json-c  depends
upd:
[+] mingw64/mingw-w64-x86_64-libmypaint adds a dependency

**Comment by Alexpux** [comment]
Will fix today

**Comment by ustsv** [comment]
New mingw-w64-x86_64-libmypaint  1.3.0beta.1-2 build w/o

mingw-w64-x86_64-libmypaint /mingw64/bin/**libmypaint-1-3-0.dll**

**Comment by Alexpux** [comment]
Ok. Fix it.
