### ISSUE TITLE
Tesseract 3.04 does not include language data

### ISSUE THREAD

**Issue by Shreeshrii** [Alexpux/MINGW-packages#157]
Hi Alex,

thanks for the tesseract package. I was able to install and use it easily.

However,
make install for tesseract does not install the language data for any language, requiring the user to download the 'traineddata' files separately. This is intentional by tesseract developers, I think.

But
https://packages.debian.org/sid/tesseract-ocr
includes three additional packages for this 

https://packages.debian.org/sid/tesseract-ocr-eng
https://packages.debian.org/sid/tesseract-ocr-equ
https://packages.debian.org/sid/tesseract-ocr-osd

So, I think it will be good to include these same languages in the mingw32/64 packages for tesseract and allow the user the ability to download other languages.

The latest files are at https://code.google.com/p/tesseract-ocr/source/checkout?repo=tessdata

However, we do not want all users to have to download the language data for ALL languages.

So there also need to be separate language traineddata and related files packaged together.
e.g.
hin - https://packages.debian.org/sid/tesseract-ocr-hin
ara - https://packages.debian.org/sid/tesseract-ocr-ara

These should be unpacked in the tessdata directory and TESSDATA_PREFIX should be  given correctly.

I think there was 'install-langs' option for make at one  time, but I do not see it now.

**Comment by elieux** [comment]
Packages with tessdata are now available. Closing this ticket.
