### ISSUE TITLE
Autoconf Archive Bug

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#1570]
The current release of Autoconf Archive has a bug that was fixed in (this commit)[http://git.savannah.gnu.org/cgit/autoconf-archive.git/commit/?id=d343892fbd0605a9375ff1ae0467aa320a404b12].

It might be a good idea to apply that fix to the released version, as it breaks aclocal for numerous packages (like JasPer).

**Comment by lazka** [comment]
autoconf-archive is now at 2017.03.21. Is this still a problem?

**Comment by BrisingrAerowing** [comment]
I haven't been doing much with this lately, and from the version I would guess not.
