### ISSUE TITLE
cmake 3.6.0 is broken

### ISSUE THREAD

**Issue by mati865** [Alexpux/MINGW-packages#1577]
I'm back for a few days and I was curious how updated cmake will affect KDE Frameworks building.
Unfortunately attica-qt5 (both 5.23.0 and 5.24.0 versions) cannot but build with cmake 3.6.0.
Cmake 3.5.2 from this commit https://github.com/Alexpux/MINGW-packages/commit/465215ea6074f2805a492093834c5afa7fb9dfdd is fine however.

To be sure it's not an upstream bug I've tested cmake 3.6.0 with attica-qt5 5.24.0 and had no problem building it.

Error:
```
[ 95%]  Building CXX object src/CMakeFiles/KF5Attica.dir/topicparser.cpp.obj
make[2]: *** No rule to make target 'src/KF5Attica_autogen.cpp', needed by 'src/CMakeFiles/KF5Attica.dir/KF5Attica_autogen.cpp.obj'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 97%] Building CXX object src/CMakeFiles/KF5Attica.dir/attica_debug.cpp.obj
make[1]: *** [CMakeFiles/Makefile2:119: src/CMakeFiles/KF5Attica.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

Logs:
cmake 3.6.0: [mingw-w64-attica-qt5-5.24.0-1-x86_64-build.log.txt](https://github.com/Alexpux/MINGW-packages/files/373928/mingw-w64-attica-qt5-5.24.0-1-x86_64-build.log.txt)
cmake 3.5.2: [mingw-w64-attica-qt5-5.24.0-1-x86_64-build.log.txt](https://github.com/Alexpux/MINGW-packages/files/373933/mingw-w64-attica-qt5-5.24.0-1-x86_64-build.log.txt)

**Comment by zhangshaowei** [comment]
I have the same problem after updating cmake 3.6.0

**Comment by mati865** [comment]
@zhangshaowei could you test https://github.com/Alexpux/MINGW-packages/issues/1596?
