### ISSUE TITLE
Rebuild wxWidgets with gcc 6.1

### ISSUE THREAD

**Issue by jessehager** [Alexpux/MINGW-packages#1578]
I just installed gcc 6.1 and programs built with wxWidgets stopped working:

![wxwidgetsfatalerrorabi1010](https://cloud.githubusercontent.com/assets/1455423/16992504/9c2dbf82-4e6d-11e6-8577-b3e39642b097.png)

The ABI version has been bumped to 1010 and wxWidgets needs to be recompiled with the new gcc version.

This is similar to issue #712 from a year ago.

**Comment by mati865** [comment]
Just create PR with bumped `pkgrel`.

**Comment by lazka** [comment]
wxWidgets has been rebuild multiple times in the meantime.
