### ISSUE TITLE
Relocation errors with -lstdc++ starting with GCC6

### ISSUE THREAD

**Issue by wiiaboo** [Alexpux/MINGW-packages#1580]
Both FFmpeg and mpv when linking with -lstdc++ fail with these exact errors when compiling with x86_64-w64-mingw32 GCC 6.1:
```
C:/builds/ab/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0\libstdc++.a(cow-stdexcept.o):(.text$_Z35_txnal_cow_string_C1_for_exceptionsPvPKcS_+0x2c): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_RU1'
C:/builds/ab/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0\libstdc++.a(cow-stdexcept.o):(.text$_Z35_txnal_cow_string_C1_for_exceptionsPvPKcS_+0x39): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `transaction clone for operator new[](unsigned long long)'
C:/builds/ab/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0\libstdc++.a(cow-stdexcept.o):(.text$_Z35_txnal_cow_string_C1_for_exceptionsPvPKcS_+0x5d): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_memcpyRtWn'
C:/builds/ab/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0\libstdc++.a(cow-stdexcept.o):(.text$_Z23_txnal_cow_string_c_strPKv+0x1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_RU8'
C:/builds/ab/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0\libstdc++.a(cow-stdexcept.o):(.text$_Z23_txnal_sso_string_c_strPKv+0x1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_RU8'
C:/builds/ab/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0\libstdc++.a(cow-stdexcept.o):(.text$_Z20_txnal_cow_string_D1Pv+0x5): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_RU8'
C:/builds/ab/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0\libstdc++.a(cow-stdexcept.o):(.text$_Z20_txnal_cow_string_D1Pv+0x1e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_addUserCommitAction'
C:/builds/ab/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0\libstdc++.a(cow-stdexcept.o):(.text$_ZGTtNSt11logic_errorC1EPKc+0x2e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_memcpyRnWt'
C:/builds/ab/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0\libstdc++.a(cow-stdexcept.o):(.text$_ZGTtNSt11logic_errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x2e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_memcpyRnWt'
C:/builds/ab/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0\libstdc++.a(cow-stdexcept.o):(.text$_ZGTtNSt11logic_errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x36): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_ITM_RU8'
C:/builds/ab/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0\libstdc++.a(cow-stdexcept.o):(.text$_ZGTtNSt11logic_errorD0Ev+0x1a): additional relocation overflows omitted from the output
collect2.exe: error: ld returned 1 exit status
```
There errors are only missing if libs that depend on stdc++ are avoided.

**Comment by wiiaboo** [comment]
Something like this probably needs to be done in mingw64 as well: https://github.com/gcc-mirror/gcc/commit/40c727c8722ab47a821e2fe371f1b6b96be0200d

**Comment by mati865** [comment]
@wiiaboo could you tell how to reproduce it?
I asked @lhmouse on msys2 IRC and he pointed me that [0012-MinGW-w64-Enable-libitm.patch](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gcc-git/0012-MinGW-w64-Enable-libitm.patch) allowed libitm to build but the library didn't work.
I would like to test if weak refs could be used again after disabling libitm.

**Comment by wiiaboo** [comment]
- Use 64-bit MinGW GCC installed from Msys2
- Compile a static lib that depends on -lstdc++ and uses exceptions (example: https://github.com/lachs0r/rubberband) (x265 is one of the few that depends on libstdc++ but doesn't have issues because it doesn't use exceptions)
- Compile FFmpeg with `configure --disable-shared --enable-librubberband --extra-libs=-lstdc++`
  - this will fail linking with the errors on the first post unless either libitm is disabled or weak refs are disabled.

**Comment by mati865** [comment]
Thank you, I'll be able test it over Saturday or Sunday because Windows Update interrupted GCC recompilation 😞.

**Comment by wiiaboo** [comment]
Unfortunately it seems the issue still persists with 6.2.0. Looks like the problem really is about weak references.

**Comment by lhmouse** [comment]
@wiiaboo 

Would you please try disabling `libitm` ?

**Comment by wiiaboo** [comment]
How do I do that?

**Comment by lhmouse** [comment]
@wiiaboo

You probably have to compile GCC yourself... Or we could wait for someone to update MSYS2 sources.

**Comment by wiiaboo** [comment]
Isn't MinGW 6.2.0 already supposed to not be using libitm?

**Comment by lhmouse** [comment]
I don't know how it is going.

    C:\Users\LH_Mouse>grep -R ITM_ /mingw64
    Binary file /mingw64/bin/libstdc++-6.dll matches
    Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.1/cc1.exe matches
    Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.1/cc1plus.exe matches
    Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.1/lto1.exe matches
    Binary file /mingw64/lib/libstdc++.a matches

@mati865 Would you please have a look?

**Comment by mati865** [comment]
Hmm, I compiled ffmpeg using @wiiaboo instructions without errors.
My GCC:
https://sourceforge.net/projects/mati865-packages/files/gcc/
```
$ LANG=C grep -R ITM_ /mingw64
Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.1/cc1.exe matches
Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.1/cc1obj.exe matches
Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.1/cc1objplus.exe matches
Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.1/cc1plus.exe matches
Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.1/f951.exe matches
Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.1/gnat1.exe matches
Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.1/libstdc++.a matches
Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.1/lto1.exe matches
```

@wiiaboo notice this line in your output: `Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.1.0/libitm.dll.a matches`.
I cannot find it inside gcc-6.2.0 packages from repo. Could you remove it and retry?

**Comment by wiiaboo** [comment]
Same errors. It just wasn't removed with the upgrade. No reason for it to be used, I'm not using -litm in LDFLAGS.

**Comment by mati865** [comment]
That's really strange, before opening https://github.com/Alexpux/MINGW-packages/issues/1722 I compiled rubberband and ffmpeg using your instructions.
From CI log:
```
checking for libitm support... no
```
So it shouldn't really be there. 
So either I made mistkae trying to reproduce issue or there was a problem during updating files.

**Comment by wiiaboo** [comment]
I'd guess libitm patch was still applied. I'm compiling myself now with clean git clone. If ITM_ is still there it's very weird.

**Comment by mati865** [comment]
You can use my PKGBUILD https://gitlab.com/mati865/MATI865-packages/blob/master/mingw-w64-gcc/PKGBUILD

**Comment by mati865** [comment]
It's worth to note `ITM` symbols are placed in static lib only:
```
$ nm /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.1/libstdc++.dll.a | grep ITM

$ nm /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.1/libstdc++.a | grep ITM
0000000000000000 A .weak._ITM_addUserCommitAction._Z27_txnal_cow_string_D1_commitPv
0000000000000000 A .weak._ITM_memcpyRnWt._Z27_txnal_cow_string_D1_commitPv
0000000000000000 A .weak._ITM_memcpyRtWn._Z27_txnal_cow_string_D1_commitPv
0000000000000000 A .weak._ITM_RU1._Z27_txnal_cow_string_D1_commitPv
0000000000000000 A .weak._ITM_RU8._Z27_txnal_cow_string_D1_commitPv
                 w _ITM_addUserCommitAction
                 w _ITM_memcpyRnWt
                 w _ITM_memcpyRtWn
                 w _ITM_RU1
                 w _ITM_RU8
```

**Comment by wiiaboo** [comment]
That's kind of the issue, no? I'm not distributing libstdc++.dll with otherwise perfectly working static binaries.

**Comment by mati865** [comment]
Yes, we need to find out why there are ITM symbols in static lib only.
@lhmouse what do you think? You know much more about GCC after all.

**Comment by wiiaboo** [comment]
Compiling by myself without the weak refs patch there's still the same ITM relocation errors.

**Comment by mati865** [comment]
I worry disabling weak refs could cause side effects.
I cannot test right now if disabling weak refs removes all ITM occurences.
Weak symbols from static libstdc++:
```
$ nm /mingw32/lib/gcc/i686-w64-mingw32/6.2.1/libstdc++.a | grep " w\|v "
         w __ITM_addUserCommitAction
         w __ITM_memcpyRnWt
         w __ITM_memcpyRtWn
         w __ITM_RU1
         w __ITM_RU4
         w __ZGTtdlPv
         w __ZGTtnaj
```
Not sure what `__ZGT` is but it will be nuked by disabling weak refs.
Also I'm wondering why symbol type is `w` and not `v`.

**Comment by wiiaboo** [comment]
My build of gcc 6.1.0 without weak refs had no ITM symbols in libstdc++.a but it had a separate libitm.a. Maybe I do need to compile my own gcc from now on.

**Comment by wiiaboo** [comment]
6.2.0 with weak refs patch applied:
```
grep -R ITM_ /mingw64
Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.0/cc1.exe matches
Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.0/cc1plus.exe matches
Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.0/gnat1.exe matches
Binary file /mingw64/lib/gcc/x86_64-w64-mingw32/6.2.0/lto1.exe matches
```

**Comment by mati865** [comment]
`__ZGT` are also libitm symbols.
@martell told me on IRC that weak symbols are supported by Windows and this issue is rather related to bintuls or libstdc++.

> Maybe I do need to compile my own gcc from now on.

I'm sorry but it sounds as the best solution for now.

**Comment by mati865** [comment]
Those symbols seems to come from https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/src/c%2B%2B11/cow-stdexcept.cc#L205

**Comment by mati865** [comment]
After discussion with @Alexpux I'll try new binutils. If it doesn't help we will probably use your patch @wiiaboo.

**Comment by wiiaboo** [comment]
New versions don't come out that often. If I have to build my own once in a while, it's not too bad. There's probably not too many people compiling statically with Msys2.

**Comment by mati865** [comment]
Still it's a defect and should be taken care of.

**Comment by lhmouse** [comment]
@mati865 

I know nothing about itm. GCC is so huge that hardly can a person know everything about it.

Windows does support weak references, but they don't go into DLLs. That is to say, they could exist in a static library or an import library. (a .dll.a file).

**Comment by mati865** [comment]
@wiiaboo I've created PKGBUILDs for rubberband and ffmpeg [github](https://github.com/mati865/MATI865-packages/tree/master/binutils-testing) or [gitlab](https://gitlab.com/mati865/MATI865-packages/tree/master/binutils-testing). I still cannot reproduce it, so could you take a look at them?

Also I've compiled binutils 2.27 and recompiled important packages with it. Links are available here: [download-list.txt](https://github.com/Alexpux/MINGW-packages/files/487909/download-list.txt) or [here](https://sourceforge.net/projects/mati865-packages/files/binutils-testing/)
If you want to test it, separate MSYS2 is recommend since it's not tested well enough.
Theoretically static libs should be compatible, but in the end they might need rebuild.
You can use download managers or aria2 to download it:
```
/mignw64/bin/aria2c -i download-list.txt
```
And install it with `pacman -U`

**Comment by wiiaboo** [comment]
It looks like you're compiling rubberband dynamically, so that's why you can't reproduce.

**Comment by mati865** [comment]
I made sure there is static lib, fixing shared lib compilation was to lean something about Makefiles:
```
mingw-w64-x86_64-rubberband /mingw64/
mingw-w64-x86_64-rubberband /mingw64/bin/
mingw-w64-x86_64-rubberband /mingw64/bin/librubberband-2.dll
mingw-w64-x86_64-rubberband /mingw64/bin/librubberband-2.dll.2
mingw-w64-x86_64-rubberband /mingw64/bin/librubberband-2.dll.2.1.0
mingw-w64-x86_64-rubberband /mingw64/include/
mingw-w64-x86_64-rubberband /mingw64/include/rubberband/
mingw-w64-x86_64-rubberband /mingw64/include/rubberband/RubberBandStretcher.h
mingw-w64-x86_64-rubberband /mingw64/include/rubberband/rubberband-c.h
mingw-w64-x86_64-rubberband /mingw64/lib/
mingw-w64-x86_64-rubberband /mingw64/lib/librubberband.a       # here
mingw-w64-x86_64-rubberband /mingw64/lib/librubberband.dll.a
mingw-w64-x86_64-rubberband /mingw64/lib/pkgconfig/
mingw-w64-x86_64-rubberband /mingw64/lib/pkgconfig/rubberband.pc
```

**Comment by wiiaboo** [comment]
Yeah, but if there's a .dll.a available it'll be used instead of the static lib.

**Comment by mati865** [comment]
Sound like some kind of weird issue but will try and report.

**Comment by wiiaboo** [comment]
It's not an issue, it's normal behavior of ld with cygwin/mingw. It looks for libxxx.dll.a, xxx.dll.a and then libxxx.a. Ways to force it include passing the full path to libxxx.a, passing `-Wl,-Bstatic` or just `-static`, and renaming the import library to something else.
I use the last one:
```bash
do_hide_all_sharedlibs() {
    local files
    files="$(find /mingw{32,64}/lib /mingw{32/i686,64/x86_64}-w64-mingw32/lib -name "*.dll.a" 2>/dev/null)"
    local tomove=()
    for file in $files; do
        [[ -f "${file%*.dll.a}.a" ]] && tomove+=("$file")
    done
    printf "%s\n" "${tomove[@]}" | xargs -i mv -f '{}' '{}.dyn'
}```

**Comment by mati865** [comment]
I made small corrections (published on git) and made sure there is no dynamic rubberband libs left.
Again it didn't fail.

**Comment by wiiaboo** [comment]
Until you hide the import libs with do_hide_all_sharedlibs() compilation does work. Without hidden implibs, the final ffmpeg.exe stills needs a bunch of msys2 dlls.

**Comment by mati865** [comment]
New binutils didn't solve issue. I'll re-add your patch since it's best fix we have for now.

**Comment by lhmouse** [comment]
Does this problem happen on i686 targets?

**Comment by mati865** [comment]
@lhmouse I don't think so.

**Comment by lhmouse** [comment]
@mati865 
Then fixing it on x64 without doing the same on x86 could be questionable, unless we get some advices from gcc people.

**Comment by wiiaboo** [comment]
It affects cygwin, so I'd assume it would affect mingw as well, no?

**Comment by lhmouse** [comment]
> It affects cygwin, so I'd assume it would affect mingw as well, no?

Generally yes. But the reason why it affects x64 but not x86 still requires investigation.

**Comment by mati865** [comment]
Ping @lhmouse 
As noticed on mingw-w64 mailing list, original issue is here https://trac.ffmpeg.org/ticket/5895

[This commit](https://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=a58c22d61260941fc651add73836882d5b112fdb) added `--image-base` for x86_64 build so mistery is solved.

What should we do about it?

**Comment by lhmouse** [comment]
no idea. `--image-base` is an LD flag so it might have something to do with binutils.

**Comment by mati865** [comment]
It was issue with 2.25 binutils and 2.27 update haven't solved it.

@wiiaboo do you know if it was reported to binutils upstream?

**Comment by wiiaboo** [comment]
No idea. Never investigated further than the workaround.

**Comment by DeadSix27** [comment]
Whats the conclusion? I'm trying to build ffmpeg with rubberband using gcc 6.3.0 from source as well, is the only fix the weak-refs patch for it?

**Comment by wiiaboo** [comment]
Afaik, yes, that's the only workaround so far.

**Comment by DeadSix27** [comment]
@wiiaboo bummer know if there's a official issue post for this on gcc?

**Comment by wiiaboo** [comment]
I just found the [same issue but regarding cygwin](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69506) and made the workaround so it worked for mingw too. I couldn't create an account back then either, so no issue created. The workaround is literally the same as https://github.com/gcc-mirror/gcc/commit/40c727c8722ab47a821e2fe371f1b6b96be0200d so I don't have any authorship on the code.

**Comment by DeadSix27** [comment]
@wiiaboo Ah, thanks, I actually missed that link in https://github.com/Alexpux/MINGW-packages/issues/1580#issuecomment-234019251
Odd, guess ill compile from git tag then, seems to be patched there?: https://github.com/gcc-mirror/gcc/blob/gcc-6_3_0-release/libstdc%2B%2B-v3/config/os/newlib/os_defines.h#L57
Unlike in the tarball.

**Comment by wiiaboo** [comment]
It's not fixed in [https://github.com/gcc-mirror/gcc/blob/gcc-6_3_0-release/libstdc%2B%2B-v3/config/os/**_mingw32-w64_**/os_defines.h](https://github.com/gcc-mirror/gcc/blob/gcc-6_3_0-release/libstdc%2B%2B-v3/config/os/mingw32-w64/os_defines.h)
That's what the workaround is for.

**Comment by DeadSix27** [comment]
@wiiaboo Oh, right! Saw that wrong, also my statement its not in the tarball, well that specific line is in the tarball too, but both do not contain the proper patch of course, so nvm that (I'm tired..)

**Comment by chouquette** [comment]
Should be fixed in next GCC release: https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=247502
No idea if they will backport it to 6.x though

**Comment by lhmouse** [comment]
Wasn't it jon_y that committed the patch?
I am still wondering why i686 works fine without that `#define` ...

**Comment by chouquette** [comment]
To my knowledge, he pushed a patch but not for mingw-w64

**Comment by lhmouse** [comment]
Of course this patch ain't meant to be applied to mingw-w64...
jon_y is the maintainer for mingw targets now.

**Comment by rkitover** [comment]
I reported this bug to the gcc bugzilla here:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85298

**Comment by rkitover** [comment]
The mingw gcc in the cygwin distribution also does not have this patch.
