### ISSUE TITLE
inkscape fails to start

### ISSUE THREAD

**Issue by wanglongqi** [Alexpux/MINGW-packages#1583]
Fresh install of MSYS2, inkscape in the repository seems still using imagemagic 6 and the current imagemagic in the respository is 7. `inkscape` command returns following error message:

> C:/msys64/mingw64/bin/inkscape.exe: error while loading shared libraries: libMagick++-6.Q16HDRI-6.dll: cannot open shared object file: No such file or directory

**Comment by Alexpux** [comment]
It not buildable with 7 now.

**Comment by wanglongqi** [comment]
@Alexpux so any solution to install `inkscape` in msys2?

**Comment by Alexpux** [comment]
I'm at holidays from today. I can't fix anything during this month

**Comment by mati865** [comment]
I'll look into it in 2 days when I'll be back.
