### ISSUE TITLE
python3 has trouble with correctly calling pkg-config

### ISSUE THREAD

**Issue by fspeech** [Alexpux/MINGW-packages#1595]
In my python3 installed from a month ago I have problem with

```
$ python3
Python 3.5.0 (default, Mar  4 2016, 09:42:51)  [GCC 5.3.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from subprocess import getstatusoutput
>>> getstatusoutput('sh -c "pkg-config freetype2 --libs --cflags"')
(1, "Package freetype2 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `freetype2.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'freetype2' found")
```

As you can see this will cause some python build scripts that use pkg-config to fail. Calling directly from shell gives the correct result:

```
$ pkg-config freetype2 --libs
-L/mingw32/lib -LC:/building/msys64/mingw32/lib -L/mingw32/lib -lfreetype -lz -lbz2 -lpng16 -lz -lharfbuzz -lglib-2.0 -lintl -pthread -lws2_32 -lole32 -lwinmm -lshlwapi -lpcre -lintl -lpcre -lgraphite2
```

My older build of python3 (on a different machine) also works fine:

```
$ python3
Python 3.5.0 (default, Oct  8 2015, 12:38:47)
[GCC 5.2.0] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from subprocess import getstatusoutput
>>> getstatusoutput('sh -c "pkg-config freetype2 --libs --cflags"')
(0, '-mms-bitfields -IC:/alt/msys32/mingw32/include/freetype2 -IC:/alt/msys32/mingw32/include -IC:/alt/msys32/mingw32/include/libpng16 -IC:/alt/msys32/mingw32/include/harfbuzz -IC:/alt/msys32/mingw32/include/glib-2.0 -IC:/alt/msys32/mingw32/lib/glib-2.0/include -LC:/alt/msys32/mingw32/lib -lfreetype')
```

Any ideas?

**Comment by mati865** [comment]
Like Arch Linux MSYS2 does **not** support [partial updates ](https://wiki.archlinux.org/index.php?title=System_maintenance&redirect=no#Partial_upgrades_are_unsupported).
Updated packages are fine
```
MINGW64 ~
$ python3
Python 3.5.2 (default, Jul 12 2016, 14:44:57)  [GCC 5.4.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from subprocess import getstatusoutput
>>> getstatusoutput('sh -c "pkg-config freetype2 --libs --cflags"')
(0, '-mms-bitfields -ID:/msys64/mingw64/include/freetype2 -ID:/msys64/mingw64/include -ID:/msys64/mingw64/include/libpng16 -ID:/msys64/mingw64/include/harfbuzz -ID:/msys64/mingw64/include/glib-2.0 -ID:/msys64/mingw64/lib/glib-2.0/include -ID:/msys64/mingw64/include -LD:/msys64/mingw64/lib -lfreetype')
>>>
```
If you want to use older packages you have to rebuild them.

**Comment by Alexpux** [comment]
Also verify that you have installed mingw-w64 version of pkg-config

**Comment by fspeech** [comment]
Everything was installed either with ```pacman -Su``` or ```pip3```. I will do a ```pacman -Syu``` and see if problem goes away. @mati865 without the ```y``` to update the package list does pacman pull in older versions of packages or does it pull in mixed versions? I assume if version letters are always bumped I would always pull in consistent versions of packages but maybe some builds don't bump the version numbers in package names and it could get inconsistent?

**Comment by fspeech** [comment]
@Alexpux You are right I didn't have the mingw-w64 version of pkg-config and it is picking up the msys version instead. Once I installed the mingw version the problem went away. Thanks.

I would recommend that at least add the mingw-w64 pkg-config dependency to pip3 package if not python3 itself, since without it some pip3 installs would fail.

**Comment by mati865** [comment]
> Everything was installed either with pacman -Su or pip3.

If you install modules with `pip` you may get version for MS Visual Studio. It is strongly recommended to install modules with `pacman`.

> @mati865 without the y to update the package list does pacman pull in older versions of packages or does it pull in mixed versions?
`-y` means refresh, it downloads list of most recent versions. `pacman -Su` checks this list (aka database) for available updates. Therefore if you don't use `pacman -Syu` you cannot upgrade your packages.

**Comment by fspeech** [comment]
@mati865 With the amount of pip packages available it is fairly impossible to have all python modules through pacman. Also I may want different build options for python modules. For example if I do ```pacman -Su``` matplotlib it offers me a 4GB installation as it pulls in all the gui options and dependencies. On the other hand I can first do a ```pip3 matplotlib --build``` and then patch the ```setup.py``` and ```setupext.py``` using the patch files from the mingw packages and build a much more limited version for my own purpose.

**Comment by mati865** [comment]
@fspeech of course but keep in mind you can easily break things.

**Comment by fspeech** [comment]
@mati865 Sure. Thanks for the help!
