### ISSUE TITLE
Failing dependecy on avcodec-*.dll

### ISSUE THREAD

**Issue by marcin-sielski** [Alexpux/MINGW-packages#1608]
(gst-inspect-1.0:6072): GStreamer-WARNING **: Failed to load plugin 'C:\msys64\mingw32\lib\gstreamer-1.0\libgstchromaprint.dll'

**Comment by lazka** [comment]
chromaprint in the repo no longer uses ffmpeg, so I guess this is "fixed". If not please say so.
