### ISSUE TITLE
Native git package

### ISSUE THREAD

**Issue by fspeech** [Alexpux/MINGW-packages#1619]
It appears that we have a msys/git package that can be installed using pacman, but there are no native versions available.

**Comment by fspeech** [comment]
I see this question was already partly answered as #1212 so feel free to close this or leave it open as a feature to be developed.

**Comment by fspeech** [comment]
This fork may be relevant? https://github.com/git-for-windows/MINGW-packages/tree/master/mingw-w64-git

**Comment by elieux** [comment]
You can already install native git (with some caveats) into a regular MSYS2 by following the steps here: https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper

The progress on providing a native git package directly is tracked here: https://github.com/git-for-windows/git/issues/284
