### ISSUE TITLE
validating source files always failed

### ISSUE THREAD

**Issue by w2moon** [Alexpux/MINGW-packages#1620]
I use MSYS2 shell on windows 10,and all packages have the same problem.
--------------------------------------------------------------------------------------------------------
/e/projects/MINGW-packages/mingw-w64-libogg
$ makepkg-mingw
==> Making package: mingw-w64-libogg 1.3.2-2 (Fri Aug  5 12:45:35 CST 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found libogg-1.3.2.tar.gz
==> Validating source files with sha256sums...
    libogg-1.3.2.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!

--------------------------------------------------------------------------------------------------------------
Administrator@bielaiwan MINGW32 /e/projects/MINGW-packages/mingw-w64-libogg
$ updpkgsums
==> ERROR: pkgname is not allowed to start with a hyphen.

PKGBUILD file--------------------------------------------------------------------------------------------------
# Maintainer: Alexey Pavlov <alexpux@gmail.com>

_realname=libogg
pkgbase=mingw-w64-${_realname}
pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
pkgver=1.3.2
pkgrel=2
pkgdesc="Ogg bitstream and framing library (mingw-w64)"
arch=('any')
url="https://xiph.org"
license=('BSD')
makedepends=("${MINGW_PACKAGE_PREFIX}-gcc")
options=('staticlibs' 'strip')
source=(http://downloads.xiph.org/releases/ogg/${_realname}-${pkgver}.tar.gz)
sha256sums=('e19ee34711d7af328cb26287f4137e70630e7261b17cbe3cd41011d73a654692')

prepare() {
  cd ${srcdir}/libogg-${pkgver}
}

build() {
  [[ -d "${srcdir}/build-${MINGW_CHOST}" ]] && rm -rf "${srcdir}/build-${MINGW_CHOST}"
  mkdir -p ${srcdir}/build-${MINGW_CHOST}
  cd ${srcdir}/build-${MINGW_CHOST}
  ../libogg-${pkgver}/configure \
    --enable-shared \
    --enable-static \
    --prefix=${MINGW_PREFIX} \
    --build=${MINGW_CHOST} \
    --host=${MINGW_CHOST} \
    --target=${MINGW_CHOST}
  make
}

package() {
  cd ${srcdir}/build-${MINGW_CHOST}
  make DESTDIR="${pkgdir}" install
}

**Comment by Alexpux** [comment]
First you need update msys2-core packages because you have old pacman. In your case you need run updpkgsums like:
````MINGW_PACKAGE_PREFIX=mingw-w64-i686 updpkgsums````

**Comment by w2moon** [comment]
thanks!It's worked.
