### ISSUE TITLE
Any program in mingw-w64-x86_64-gdal generates an error

### ISSUE THREAD

**Issue by rhornig** [Alexpux/MINGW-packages#1638]
Starting any program from the package, like: gdalinfo results in an error:

osgearth_version.exe: error while loading shared libraries: libgdal-20.dll: cannot open shared object file: No such file or directory

**Comment by rhornig** [comment]
Previously I have reported this issue for osgEarth, but is seems that gdal is more at the root at the problem. osgEarth failures are just a consequence.

**Comment by rhornig** [comment]
Recompiling the gdal package from the sources fixed the issues, however postrgres was also installed for the rebuild so it's possible that postgres package is required however it is treated as an optional dependency. (uninstalling postgres leads to the same error so I suspect that is the case)

**Comment by lazka** [comment]
Likely the same as #1439

Please continue there.
