### ISSUE TITLE
SDL2_mixer issue #865 regression

### ISSUE THREAD

**Issue by danpla** [Alexpux/MINGW-packages#1641]
The issue #865 was fixed by @fabiangreffrath in #867 for both SDL_mixer and SDL2_mixer.

While all is OK with SDL_mixer, the fix was completely removed from SDL2_mixer in 276d9bd71b474a8d82fe10e06dcff17a5ff57614.

**Comment by fabiangreffrath** [comment]
> While all is OK with SDL_mixer, the fix was completely removed from
> SDL2_mixer in 276d9bd71b474a8d82fe10e06dcff17a5ff57614.

My patch was applied to the configure script itself and now probably does
not apply anymore to the one shipped with the updated release. I should
have commited it as a patch to apply to configure.ac, but that would have
required an additional autoconf step in the build process. It should be
possible, however, to recover the patch and apply it against configure.ac
instead with little effort.

Thanks!

 - Fabian
