### ISSUE TITLE
lcov package contains no files.

### ISSUE THREAD

**Issue by effh** [Alexpux/MINGW-packages#1643]
after installing the lcov package(the gcov wrapper), no lcov command was found. pacman queries yielded the following:

-----@---------- MINGW32 ~
$ pacman -Qk mingw-w64-i686-lcov
mingw-w64-i686-lcov: 0 total files, 0 missing files

-----@---------- MINGW32 ~
$ pacman -Qk mingw-w64-x86_64-lcov
mingw-w64-x86_64-lcov: 0 total files, 0 missing files

(I Installed both versions to see if one actually had files.)

**Comment by DavidEGrayson** [comment]
There is no package named `mingw-w64-x86_64-icov`.  Did you make a typo?

**Comment by galeksandrp** [comment]
#1643
