### ISSUE TITLE
Missing dependency for gnupg-2.1 - libreadline

### ISSUE THREAD

**Issue by mrinx** [Alexpux/MINGW-packages#1645]
There seems to be a missing dependency somewhere; after installing `mingw64/mingw-w64-x86_64-gnupg` I get an error:

```
$ gpg2 --version
C:/msys64/mingw64/bin/gpg2.exe: error while loading shared libraries: libsystre-0.dll: cannot open shared object file: No such file or directory
```

After I install `mingw64/mingw-w64-x86_64-readline`, gpg2 works just fine.

**Comment by peterbud** [comment]
This dependency has been added already, issue should be closed.
