### ISSUE TITLE
No mingw-w64-gperf package?

### ISSUE THREAD

**Issue by equalsraf** [Alexpux/MINGW-packages#1653]
I tried to install mingw-w64_x86_64-gperf earlier but pacman failed to even find the package. Trying to build it with makepkg-mingw fails due to
1. a failed PGP check
2. missing `diff`
3. missing ./cout

that last one was as far as I got.

Is this package expected to work, or am I missing something?

**Comment by lazka** [comment]
gperf seems to build fine here now

@Alexpux can you build it?
