### ISSUE TITLE
No package updates since 2016-07-21

### ISSUE THREAD

**Issue by vszakats** [Alexpux/MINGW-packages#1658]
The filelists haven't been updated since 2016-07-21, even though there was commit activity that would imply updates:

Visible on these URLs:
http://repo.msys2.org/mingw/i686/
https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/
http://www.futureware.at/~nickoe/msys2-mirror/mingw/x86_64/?C=M;O=D

Is this intended, or is there something stuck in the infrastructure?

**Comment by Alexpux** [comment]
I was on vacation. Return only two days ago.

**Comment by vszakats** [comment]
Thank you, and closing as resolved.
