### ISSUE TITLE
Bug in Cyrus-Sasl patch

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#1661]
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-cyrus-sasl/19-paths-relocation.patch#L113

Shouldn't the variable be 'default_conf_path'?

**Comment by Alexpux** [comment]
Fixed in https://github.com/Alexpux/MINGW-packages/commit/c833670b01c622ac5014d2e5a9645e2ff4ed6673
