### ISSUE TITLE
libpixbufloader-svg.dll': The specified procedure could not be found

### ISSUE THREAD

**Issue by juml** [Alexpux/MINGW-packages#1664]
On today's update mingw-w64-x86_64-gdk-pixbuf2-2.35.3-1 installation I'm getting error:

> (6/8) upgrading mingw-w64-x86_64-gdk-pixbuf2       [#####################] 100%
> g_module_open() failed for D:\msys64\mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders\l                                                                     ibpixbufloader-svg.dll: 'D:\msys64\mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders\lib                                                                     pixbufloader-svg.dll': The specified procedure could not be found.

Error also occasionally shown running gtk3 application, like:

> (articoka.exe:22724): Gtk-WARNING **: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.

**Comment by mati865** [comment]
Cannot reproduce. Maybe another bug caused by https://github.com/Alexpux/MINGW-packages/issues/1663?

**Comment by juml** [comment]
Output of gdk-pixbuf-query-loaders says

```
$ gdk-pixbuf-query-loaders.exe
# GdkPixbuf Image Loader Modules file
# Automatically generated file, do not edit
# Created by gdk-pixbuf-query-loaders.exe from gdk-pixbuf-2.35.3
#
# LoaderDir = D:\msys64\mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders
#
g_module_open() failed for D:\msys64\mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders\libpixbufloader-svg.dll: 'D:\msys64\mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders\libpixbufloader-svg.dll': The specified procedure could not be found.
```

**Comment by mati865** [comment]
You are right I used outdated mirror.

**Comment by mati865** [comment]
32 bit package is fine, only 64 bit is bugged

**Comment by mkae** [comment]
Yeah, still saw this during a recent update:
```
(65/77) Aktualisiere mingw-w64-x86_64-gdk-pixbuf2                  [###################################] 100%
g_module_open() failed for C:\msys64\mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders\libpixbufloader-svg.dll: 'C:\msys64\mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders\libpixbufloader-svg.dll': Die angegebene Prozedur wurde nicht gefunden.
```

**Comment by juml** [comment]
Hm issue doesn't happen to me anymore for some time, also during last updates.
Are libpixbufloader-svg.dll dependencies installed ?

(librsvg and its dependencies like  LIBXML2-2.DLL ?)

**Comment by lazka** [comment]
Is this still any issue?

**Comment by juml** [comment]
No problem her for some time.
