### ISSUE TITLE
mingw-w64-i686-clang is built improperly

### ISSUE THREAD

**Issue by vit9696** [Alexpux/MINGW-packages#1669]
Hello,
Some while ago I posted an issue regarding [unordered_map and clang](https://github.com/Alexpux/MINGW-packages/issues/886). This is still unfixed, and I well understand you because with a large number of headers included it is very hard to analyse. However, there are more similar cases.

[Here](https://github.com/Alexpux/MINGW-packages/issues/1195) some person supposedly had the same crash with -O3. Despite its validity the issue is unfixed and I was able to reproduce it with -O2 and -O3. Having it unfixed is understandable because it requires a lot of headers to track things down, having it closed is strange.

Since the second issue is closed, and since the first issue may not be related I created a new one. Here is a dead simple sample of code I extracted from iostream and friends to reproduce a crash:

```
struct A {
  char ok;
  void init();
  void method() {
    if (ok) init();
  }
};

static A a;
int main() {
  a.method();
}
```

Compile it with mingw-w64-i686-clang and use the following parameters:

```
clang++ -c -O2 t.cpp
```

These 12 lines of code are enough to isolate clang from any crazy library headers and are perfectly valid C++. 

I verified the [official clang 3.8.0 binary](http://llvm.org/releases/3.8.0/LLVM-3.8.0-win32.exe) and had no issue with it. I did also check the same code on macOS where nothing similar exists either. All in all the issue is specific to your 32-bit builds of clang and according to the comments the issue is not present in cygwin as well. 

Please fix it or remove clang from the package list. The compiler provided is not production ready and wastes the time of the people attempting to make the use of it.

Thanks :)

**Comment by mingwandroid** [comment]
That we don't use clang to build any of MSYS2 might give some indication of how production-ready we think it is.

MSYS2 is open source and apologetically cutting edge. Having packages available lowers the barrier for entry for people who want to investigate any said issues (by looking at intermediate compiler output in this case).

Besides that, all software has bugs.

Sorry you feel we've wasted you time, but perhaps you could spend a little more of it to do something useful for the rest of the community rather than complain?

**Comment by vit9696** [comment]
Hi Ray,
Thanks for a quick reply. Not to misunderstand each other, I would not have created an issue if I thought I wasted my own time, I am eager to get clang work fine spending as much resources on this as I actually can spare. That's why I added the details in my post.

creduce is a nice tool but I do not think it can work better than hand-crafted samples. And I do not think one can minimise 12 lines of code not requiring any includes any further.

Due to your hint to try print-after-all I was able to confirm that the cause is related to missing init function body, but that much is the only info one can get from it I am afraid.
[clang official](https://ghostbin.com/paste/f6ke7) vs [clang mingw](https://ghostbin.com/paste/m3hd5).

Even if we get the symbol names in the trace here, I am afraid it will not be possible to say what went wrong for someone not familiar with llvm internals.

**Comment by mingwandroid** [comment]
That's a good for figuring out the exact problem, thanks.

The creduce suggestion was in regard to your unordered_map crash.

**Comment by vit9696** [comment]
I decided to give creduce a try with unordered_map in the background. Although it gave me something terrible I was able to identify the pattern I spotted and explained above fairly quickly after it finished. After some manual rewrite I ended up having pretty much the same example:
```
struct _Hashtable {
  void *_M_buckets;
  void _M_deallocate_buckets();
  ~_Hashtable() {
    if (_M_buckets)
      _M_deallocate_buckets();
  }
} a;
```
This makes some kind of a checklist:
* A global variable (could be pointer or instance) of some class;
* A member function prototype;
* A class member that is not explicitly defined (static will not affect bug reproduction);
* A member function call after that unevaluatable if condition;
* Explicitly or implicitly called code function with an if condition.

At this step #886 can be closed I guess, since it is a duplicate.

**Comment by woobs** [comment]
Not sure how much it matters for this issue, but clang/LLVM 3.9 is due to be release-tagged today.

**Comment by revelator** [comment]
unfortunatly the 3.9.0 version does not build, it complains about missing thread functionality (cant find winpthread it seems), and two missing crt library functions strtod_l and strtold_l in libcxx.

**Comment by mati865** [comment]
> unfortunatly the 3.9.0 version does not build

That's why it have WIP tap.

**Comment by revelator** [comment]
Ah ok, well will be nice to see if it works any better when we get it 
building then :)


Den 09-09-2016 kl. 17:36 skrev Mateusz Mikuła:

**Comment by yumetodo** [comment]
@vit9696 
You said this issue is related with 
https://llvm.org/bugs/show_bug.cgi?id=28493
https://github.com/yumetodo/string_split/issues/1
however, It looks slightly different. It's seem malloc function work fine.

**Comment by vit9696** [comment]
@yumetodo while reducing the bug I was constantly receiving a slightly different stack trace including the one similar to what you have. In many cases the output got simply corrupted (like those 0xffffffffffffffff), which looked to me in a way that a crash was simply delayed by some other condition. You could play with things to see this.

Even though you are somewhat right that it can only be speculated whether the issue is the same or not until it gets fixed, the crash itself is not the cause but a singal that the issue exists. Even if these crashes are caused by not the same functions (although I have strong doubts about it) it is very likely that the breach in them is caused by the same thing.

I'd rather not speculate but given that clang is qite multithreaded and the issue only happens on 32-bit binaries stack alignment might be related. Perhaps recompiling it with -mstackrealign could affect something.

**Comment by revelator** [comment]
Gave it a go with -mstackrealign but the 32 bit version still crashes.

If the same code works when compiled with msvc, it suggests that 
something is wrong with either the build chain or the api or some of the 
dependencies i would think.


Den 17-09-2016 kl. 11:30 skrev vit9696:

**Comment by mati865** [comment]
Fixed in upcoming Clang 3.9 package.

**Comment by vit9696** [comment]
@mati865 Wow, that sounds brilliant. May I know what was the cause?

**Comment by mati865** [comment]
Wait, that's weird. i686 toolchain is in fact 64 bit toolchain:
```
$ clang -v
clang version 3.9.0 (tags/RELEASE_390/final)
Target: x86_64-pc-windows-gnu
Thread model: posix
InstalledDir: D:\projekty\msys2\clang\msys64\mingw32\bin
```
Something terrible must have happened in build system, looks like a lot of digging.

**Comment by mati865** [comment]
Also resolved.
