### ISSUE TITLE
Issues when building with clang (mixed cstdio linkage)

### ISSUE THREAD

**Issue by vit9696** [Alexpux/MINGW-packages#1678]
Hello,

I am currently testing clang compilation and ran into several issues. Due to #1669 being unfixed at this moment I mostly relied on [3.8.0 win32](http://llvm.org/releases/3.8.0/LLVM-3.8.0-win32.exe) and [3.9.0 rc3 win32](http://llvm.org/pre-releases/3.9.0/rc3/LLVM-3.9.0-rc3-win32.exe), however I tested mingw-w64-i686-clang (3.8) as well. Due to reports getting large I decided to split them.

**3. Mixing gcc-compiled libraries with clang objects creates cstdio symbol duplication**

Imagine two files:
_example3.cpp_:

```
#include <cstdio>

void printStr(const char *str);

int main(int argc, char *argv[]) {
    char buf[1024];
    snprintf(buf, 1024, "<<%s>>", argv[0]);
    printStr(buf);
}
```

_example3_gcc.app_:

```
#include <cstdio>

void printStr(const char *str) {
    char buf[256];
    snprintf(buf, 256, "Some temp string %s", str);
    puts(buf);
}
```

Run the following commands on them:

```
clang++ -target i686-w64-mingw32 -std=c++11 -O1 -c example3.cpp
g++ -std=c++11 -O1 -c example3_gcc.cpp
ar rvs example3.a example3_gcc.o
clang++ -target i686-w64-mingw32 -static -std=c++11 -pthread -static example3.o example3.a -o example3
```

The last call (any clang) will produce a linkage error:

```
$ clang++ -target i686-w64-mingw32 -static -std=c++11 -pthread -static example3.o example3.a -o example3
example3.a(example3_gcc.o):example3_gcc.cpp:(.text$_Z8snprintfPcjPKcz[__Z8snprintfPcjPKcz]+0x0): multiple definition of `snprintf(char*, unsigned int, char const*, ...)'
example3.o:(.text[__Z8snprintfPcjPKcz]+0x0): first defined here
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
```

From what I can tell the issue happens due to a strange workaround for gcc present in _msys64\mingw32\i686-w64-mingw32\include\stdio.h_:

```
/* There seems to be a bug about builtins and static overrides of them
   in g++.  So we need to do here some trickery.  */
#ifdef __cplusplus
extern "C++" {
#endif
```

If anything this hack looks strange, and I do not see why it should applicable to clang. Furthermore I have no clue why one would define a C function wrapper as C++ :x Therefore a suggested solution that worked for me is disabling the mad extern for clang:

```
/* There seems to be a bug about builtins and static overrides of them
   in g++.  So we need to do here some trickery.  */
#if defined(__cplusplus) && !defined(__clang__)
extern "C++" {
#endif
```

and

```
/* #endif */ /* __NO_ISOCEXT */

#if defined(__cplusplus) && !defined(__clang__)
}
#endif
```

**Comment by mati865** [comment]
Indeed it's very strange, you should ask about it on mingw-w64 mailing list or IRC.
