### ISSUE TITLE
Issues when building with clang (POSIX limits)

### ISSUE THREAD

**Issue by vit9696** [Alexpux/MINGW-packages#1679]
Hello,

I am currently testing clang compilation and ran into several issues. Due to #1669 being unfixed at this moment I mostly relied on [3.8.0 win32](http://llvm.org/releases/3.8.0/LLVM-3.8.0-win32.exe) and [3.9.0 rc3 win32](http://llvm.org/pre-releases/3.9.0/rc3/LLVM-3.9.0-rc3-win32.exe), however I tested mingw-w64-i686-clang (3.8) as well. Due to reports getting large I decided to split them.

**4. Attempting to use POSIX limits in clang does not work by default**

According to the documentation <limits.h> defines PATH_MAX preprocessor macro, which provides maximum number of bytes in a pathname, including the terminating null character.

Imagine a file:
_example4.c_:

```
#include <limits.h>
int main() { char buf[PATH_MAX]; }
```

Running _clang example4.c_ will fail with the following error:

```
example4.c:2:23: error: use of undeclared identifier 'PATH_MAX'
int main() { char buf[PATH_MAX]; }
```

The issue can be reproduced with any clang and is caused by inclusion order:

```
#1 "C:\\msys64\\mingw32\\bin\\..\\lib\\clang\\3.8.0\\include\\limits.h" 1 3
#37 "C:\\msys64\\mingw32\\bin\\..\\lib\\clang\\3.8.0\\include\\limits.h" 3
#1 "C:\\msys64\\mingw32\\lib\\gcc\\i686-w64-mingw32\\6.1.0\\include-fixed\\limits.h" 1 3
#38 "C:\\msys64\\mingw32\\bin\\..\\lib\\clang\\3.8.0\\include\\limits.h" 2 3
```

On gcc the order is different, and therefore works:

```
#1 "C:/msys64/mingw32/lib/gcc/i686-w64-mingw32/6.1.0/include-fixed/limits.h" 1 3 4
#168 "C:/msys64/mingw32/lib/gcc/i686-w64-mingw32/6.1.0/include-fixed/limits.h" 3 4
#1 "C:/msys64/mingw32/i686-w64-mingw32/include/limits.h" 1 3 4
```

If we look deeper, it will be noticed that clang's limits.h protects itself from including gcc's limits.h:

```
/* The system's limits.h may, in turn, try to #include_next GCC's limits.h.
   Avert this #include_next madness. */
#if defined __GNUC__ && !defined _GCC_LIMITS_H_
#define _GCC_LIMITS_H_
#endif
```

However, it does nothing to ensure the right file is included (with clang's limits.h there are 3 files in path, and without it there are only 2). By examining gcc's limits.h it can be noticed that it does have an ability to recurse:

```
#ifdef _GCC_NEXT_LIMITS_H
#include_next <limits.h>        /* recurse down to the real one */
#endif
```

However, clang does not and should not define _GCC_NEXT_LIMITS_H. This is not its duty. Therefore the suggested change to _msys64\mingw32\lib\gcc\i686-w64-mingw32\6.1.0\include-fixed\limits.h_ should be as follows:

```
#if defined(_GCC_NEXT_LIMITS_H) || defined(__clang__)
#include_next <limits.h>        /* recurse down to the real one */
#endif
```

P. S. This hopefully is the last issue for the time being.

**Comment by mati865** [comment]
Clang `limits.h` defines `_GCC_LIMITS_H_` and GCC `limits.h` check for it at beginning `#ifndef _GCC_LIMITS_H_`. Therefore everything inside GCC limits.h is skipped and `#if defined(_GCC_NEXT_LIMITS_H) || defined(__clang__)` will not help.

In fact it's Clang related bug and should be fixed in Clang. I'll compare behavior of our Clang with Clang on Arch Linux tomorrow and hopefully see where are the differences.

P.S.
Clang 3.9 should be ready in 2 weeks, 64 bit it usable already but still suffers from the same bugs as Clang 3.8.

**Comment by mati865** [comment]
Improved workaround:
[0001-clang-limits-fix.patch.txt](https://github.com/Alexpux/MINGW-packages/files/494055/0001-clang-limits-fix.patch.txt)

**Comment by mati865** [comment]
This one is also resolved.

**Comment by vit9696** [comment]
@mati865 is it? From the text it looks like the only change made did only affect mingw clang distribution, and nothing got merged to clang upstream?

**Comment by mati865** [comment]
I think only our platform is affected but I can try to upstream it.
Patch: https://github.com/Alexpux/MINGW-packages/pull/1768/files#diff-bd77b6f7469ad8a2c5607eb454fb36f3

**Comment by vit9696** [comment]
I see. That would be very kind of you. I guess the issue is closed in mingw packages area though.

**Comment by mati865** [comment]
On Linux there is no issue because Clang isn't searching headers inside `/lib/gcc/*`.
But on Windows:
```
#include <...> search starts here:
 D:\msys64\mingw64\bin\..\lib\clang\3.9.0\include
 D:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\6.2.0\include
 D:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\6.2.0\include-fixed
 D:\msys64\mingw64\x86_64-w64-mingw32\include
 D:\msys64\mingw64\include
```
I'll try reverting  `mingw-w64-clang/0018-experimental-workaround-for-limits-bug.patch` and removing `include-fixed`.

@martell do you know why Windows Clang uses `mingw{32,64}/lib/gcc/x86_64-w64-mingw32/6.2.0/include`?
It provides it's own headers in `mingw{32,64}/lib/clang/3.9.0/include`.

**Comment by mati865** [comment]
UPDATE: I disabled searching for headers in `/mingw{32,64}/lib/gcc/*` and everything seems to be working without this limits.h hack.
