### ISSUE TITLE
LLDB

### ISSUE THREAD

**Issue by tylorr** [Alexpux/MINGW-packages#168]
Would it be possible to add LLDB? It is a debugger designed for LLVM and it should be possible to include in the clang package.

I've tried building the package myself along with llvm and clang but I keep running into errors related to building llvm

http://lldb.llvm.org/build.html

**Comment by joca-bt** [comment]
LLDB is coming to Windows very soon, http://blog.llvm.org/2015/01/lldb-is-coming-to-windows.html
