### ISSUE TITLE
GTK 2.0 Issue

### ISSUE THREAD

**Issue by Joffrey** [Alexpux/MINGW-packages#1685]
I use an application that worked a few days ago. I updated the msys2 environment, I didn't change anything in the application and it's now encountering a bug when launching :

> "The procedure entry point IID_IUnknown could not be located in the dynamic link library C:\msys64\mingw64\bin\libgtk-win32-2.0-0.dll."
> "The procedure entry point IID_IDataObject could not be located in the dynamic link library C:\msys64\mingw64\bin\libgdk-win32-2.0-0.dll."

I tested several things until now:
- Reinstall GTK and some dev tools.
- Rebuild my application (that worked a few days ago).

EDIT:
Both 32 and 64bits version don't start.

2nd EDIT:
I found a temporary workaround by downgrading gdk
```
pacman -U mingw-w64-i686-gdk-pixbuf2-2.35.1-1-any.pkg.tar.xz
```

You can download previous packages from:
https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/x86_64/
https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/i686/

**Comment by jtanx** [comment]
I'm also getting:

~~~~~
$pacman -S mingw-w64-i686-gtk2
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-i686-gtk2-2.24.28-1

Total Download Size:    5.10 MiB
Total Installed Size:  36.98 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 mingw-w64-i686-gtk2...     5.1 MiB   813K/s 00:06 [#####################] 100%
(1/1) checking keys in keyring                     [#####################] 100%
(1/1) checking package integrity                   [#####################] 100%
(1/1) loading package files                        [#####################] 100%
(1/1) checking for file conflicts                  [#####################] 100%
(1/1) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/1) installing mingw-w64-i686-gtk2               [#####################] 100%
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_CAsakD/.INSTALL; post_install 2.24.28-1 ) failed to execute correctly
~~~~~

**Comment by mati865** [comment]
Try with https://github.com/Alexpux/MINGW-packages/commit/f6e29866cfe2a9222c71c55dad7a4971b4ac0ae5

**Comment by jtanx** [comment]
Yeah it works now
