### ISSUE TITLE
Pidgin++: `IID_IDataObject` missing in `libgdk-win32-2.0-0.dll`

### ISSUE THREAD

**Issue by elieux** [Alexpux/MINGW-packages#1691]
Pidgin++ can't start after recent updates.

![image](https://cloud.githubusercontent.com/assets/1399406/18158858/2dc3aa5e-7026-11e6-94b2-330285a5d206.png)

**Comment by mati865** [comment]
I wanted to reproduce and got during install:
```
( 6/36) installing mingw-w64-x86_64-gtk2         [#####################] 100%
błąd:  command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_yqKghv/.INSTALL; post_install 2.24.28-1 ) failed to execute correctly
( 7/36) installing mingw-w64-x86_64-hunspell     [#####################] 100%
```
Happens for both 32 and 64 bit gtk2. Probably related to this error

**Comment by Joffrey** [comment]
Possible workaround here:
[https://github.com/Alexpux/MINGW-packages/issues/1685](url)

**Comment by mati865** [comment]
Fixed in https://github.com/Alexpux/MINGW-packages/commit/f6e29866cfe2a9222c71c55dad7a4971b4ac0ae5

**Comment by elieux** [comment]
Yes, I can confirm. Thanks.
