### ISSUE TITLE
wxWidgets/wxPython abi mismatch.

### ISSUE THREAD

**Issue by stambaughw** [Alexpux/MINGW-packages#1695]
As of the most recent wxWidgets packages, KiCad crashes when launching Pcbnew with a wxWidgets/wxPython abi mismatch.  I didn't see anything in the https://github.com/Alexpux/MINGW-packages commit log to indicate that the wxPython package was going to get rebuilt.  Please rebuild wxPython to fix the abi mismatch.

Thanks,

Wayne

**Comment by Alexpux** [comment]
Currently I have problems rebuilding it. Headers not install correctly. When I have time I will fix it

**Comment by Alexpux** [comment]
New packages uploaded
