### ISSUE TITLE
glade doesn't start anymore (libgdk_pixbuf-2.0-0.dll)

### ISSUE THREAD

**Issue by juml** [Alexpux/MINGW-packages#1700]
glade doesn't start anymore (mingw-w64-x86_64-glade)
due fails to load libgdk_pixbuf-2.0-0.dll (DLLMain entry point missing)

![nodllmain](https://cloud.githubusercontent.com/assets/4678780/18270132/b595ae92-742b-11e6-818d-f6af1d5b8403.png)

**Comment by Alexpux** [comment]
Nearly all GTK packages need to be rebuild with GCC 6 and C++ packages too

**Comment by juml** [comment]
might this be due change
https://github.com/Alexpux/MINGW-packages/commit/3fa9b918d44f46bb1b14953a86f99dad4aa79449 
?

**Comment by DavidEGrayson** [comment]
Does GCC 6 break the C++ ABI again, just like GCC 5 did?

**Comment by mati865** [comment]
Everything that depends on `gdk-pixbuf2` have to be rebuild:
```
pacman -Qi mingw-w64-x86_64-gdk-pixbuf2
Name            : mingw-w64-x86_64-gdk-pixbuf2
...
Required By     : mingw-w64-x86_64-cogl  mingw-w64-x86_64-gst-plugins-good
                  mingw-w64-x86_64-gtk2  mingw-w64-x86_64-gtk3
                  mingw-w64-x86_64-librsvg
...
```
Now when `gtk2` is rebuild for `gdk-pixbuf2` `0003-fix-dllmain.patch` every framework (and some apps) depending on `gtk2` should also be rebuild.

Now back to the glade:
```
pacman -Qi mingw-w64-x86_64-glade
Name            : mingw-w64-x86_64-glade
...
Depends On      : mingw-w64-x86_64-gtk3  mingw-w64-x86_64-libxml2
                  mingw-w64-x86_64-adwaita-icon-theme
...
```
Gtk3 haven't been rebuild with https://github.com/Alexpux/MINGW-packages/commit/f6e29866cfe2a9222c71c55dad7a4971b4ac0ae5
I don't have time to test but rebuilding `gtk3` should fix it. If it doesn't then `glade` also have to be rebuild.

As you can it's very time consuming process and @Alexpux is busy.

**Comment by mati865** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/63ddf36504e7ed4a504064388b9f1c071c39a2a8

**Comment by Alexpux** [comment]
Fixed.

**Comment by juml** [comment]
thanks a lot, helped

**Comment by Garux** [comment]
Hi!
Got the same error after building against recent mingw-w64-x86_64-gtk2 (mingw-w64-x86_64-gtk2-2.24.28-3-any.pkg.tar.xz) and few more libs.
![pixbuf](https://cloud.githubusercontent.com/assets/1734117/19196138/074bbc8c-8cbd-11e6-8bcc-d01171ad2d45.png)
Is it something to do with compiling process?

**Comment by dussek** [comment]
try re-building `mingw-w64-gtkspell` package

**Comment by Garux** [comment]
Thanks, but i doubt, that it can help, since mentioned pack isn't used
I'v been told, that app, built against 32bit, has no this problem
Also gtk-demo from 64 package runs fine
