### ISSUE TITLE
MinGW-w64 version of curl fails to download file, while MSYS2 version succeeds

### ISSUE THREAD

**Issue by RyanGlScott** [Alexpux/MINGW-packages#1707]
I was recently tripped up by an apparent discrepancy in the behavior between the two versions of `curl` that MSYS2 offers. This should illustrate the difference:

```
$ /mingw64/bin/curl -L https://downloads.haskell.org/~ghc/mingw/x86_64/mingw-w64-x86_64-crt-git-5.0.0.4531.49c7046-1-any.pkg.tar.xz -o ghc-tarballs/mingw-w64/x86_64/mingw-w64-x86_64-crt-git-5.0.0.4531.49c7046-1-any.pkg.tar.xz --create-dirs -#
Warning: Failed to create the file
Warning: ghc-tarballs/mingw-w64/x86_64/mingw-w64-x86_64-crt-git-5.0.0.4531.49c7
Warning: 046-1-any.pkg.tar.xz: No such file or directory

curl: (23) Failed writing body (0 != 2759)

$ /usr/bin/curl -L https://downloads.haskell.org/~ghc/mingw/x86_64/mingw-w64-x86_64-crt-git-5.0.0.4531.49c7046-1-any.pkg.tar.xz -o ghc-tarballs/mingw-w64/x86_64/mingw-w64-x86_64-crt-git-5.0.0.4531.49c7046-1-any.pkg.tar.xz --create-dirs -#
######################################################################## 100.0%

```

Is this expected, and if so, do I need to do something to make `/mingw64/bin/curl` behave the same way as `/usr/bin/curl`?

**Comment by mati865** [comment]
Maybe upstream bug. Could you build curl 7.50.2 and test it?

**Comment by RyanGlScott** [comment]
Ah, I didn't realize I wasn't using the latest version of `curl`.

For posterity, here are the version numbers I was using in the above example:

```
$ /mingw64/bin/curl --version
curl 7.50.1 (x86_64-w64-mingw32) libcurl/7.50.1 OpenSSL/1.0.2h zlib/1.2.8 libidn/1.33 libssh2/1.7.0 nghttp2/1.13.0 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 Metalink

$ /usr/bin/curl --version
curl 7.50.1 (x86_64-pc-msys) libcurl/7.50.1 OpenSSL/1.0.2h zlib/1.2.8 libidn/1.33 libssh2/1.7.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: Debug IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets Metalink
```

I'll try building 7.50.2 now.

**Comment by RyanGlScott** [comment]
I experienced the same error with the latest version:

```
$ /mingw64/bin/curl -L https://downloads.haskell.org/~ghc/mingw/x86_64/mingw-w64-x86_64-crt-git-5.0.0.4531.49c7046-1-any.pkg.tar.xz -o ghc-tarballs/mingw-w64/x86_64/mingw-w64-x86_64-crt-git-5.0.0.4531.49c7046-1-any.pkg.tar.xz --create-dirs -#
Warning: Failed to create the file
Warning: ghc-tarballs/mingw-w64/x86_64/mingw-w64-x86_64-crt-git-5.0.0.4531.49c7
Warning: 046-1-any.pkg.tar.xz: No such file or directory

curl: (23) Failed writing body (0 != 2759)

$ /mingw64/bin/curl --version
curl 7.50.2 (x86_64-w64-mingw32) libcurl/7.50.2 OpenSSL/1.0.2h zlib/1.2.8 libidn/1.33 libssh2/1.7.0 nghttp2/1.13.0 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 Metalink
```

**Comment by mati865** [comment]
I have tested Windows release from cURL website made by @vszakats. It have the same issue. So it must be upstream bug.
Msys2 version works because it's emulated POSIX.

**Comment by RyanGlScott** [comment]
OK. If it's an upstream bug, is the right course of action to close this bug and re-open it at https://github.com/curl/curl/issues? Or does something need to be done in `MINGW-packages`?

**Comment by vszakats** [comment]
Strictly speaking on Windows, filenames are expected to use backslashes as dirseps. In this case forward slashes are used, which seems to be causing the problem. Having said that, most tools understand forward slashes, too, so it'd be nice if curl would handle this.

**Comment by mati865** [comment]
> OK. If it's an upstream bug, is the right course of action to close this bug and re-open it at https://github.com/curl/curl/issues? Or does something need to be done in MINGW-packages?

You can close it here and open at curl repo.

**Comment by RyanGlScott** [comment]
Thanks @vszakats, that's some helpful insight. Indeed, the issue is precisely the use of forward slashes. A workaround is to convert all the forward slashes to backslashes:

```
$ /mingw64/bin/curl -L https://downloads.haskell.org/~ghc/mingw/x86_64/mingw-w64-x86_64-crt-git-5.0.0.4531.49c7046-1-any.pkg.tar.xz -o ghc-tarballs\\mingw-w64\\x86_64\\mingw-w64-x86_64-crt-git-5.0.0.4531.49c7046-1-any.pkg.tar.xz --create-dirs -#
######################################################################## 100.0%
```

I'll close this issue in favor of https://github.com/curl/curl/issues/1007.

**Comment by DavidEGrayson** [comment]
Could this issue actually be caused by MSYS2 automatic argument conversion, and that's why it only affects the native Windows curl?
