### ISSUE TITLE
qtcreator get Segmentation fault

### ISSUE THREAD

**Issue by winland0704** [Alexpux/MINGW-packages#1713]
https://forum.qt.io/topic/71150/qt-creator-msys2-segmentaion-fault/3

mateczek found :  

mateczek 4 days ago 
I tried to install qt-creator in the MSYS2 environment. Operating system windows7-32 bits
//qt-creator 4.1.0 based on  Qt 5.6.1

$ qtcreator -noload Welcome
Segmentation fault
This command also generates fault, but I tried

 MINGW32 ~
$ qtcreator -noload all -load Core //Start OK 
And qt-creator start without error. At the moment i must only find bad plugin

//edit
I find bad plugin. it is QmlProfiler!!!! Thanks You very much

**Comment by mati865** [comment]
https://github.com/Alexpux/MINGW-packages/issues/1321

Could be related to https://github.com/Alexpux/MINGW-packages/issues/924
