### ISSUE TITLE
Failed to load 'libwebkitgtk-3.0-0.dll

### ISSUE THREAD

**Issue by MaxPerl** [Alexpux/MINGW-packages#1715]
Hello,

When I try to use "mingw-w64-x86_64-webkitgtk3 2.4.11-1" through the perl module Gtk3::WebKit, I get the following error:

> WARNING **: Failed to load shared library 'libwebkitgtk-3.0-0.dll' referenced by the typelib: 'libwebkitgtk-3.0-0.dll': Die angegebene Prozedur wurde nicht gefunden. at C:/msys64/mingw64/lib/perl5/site_perl/Glib/Object/Introspection.pm line 110.

and two lines later
> Could not locate symbol webkit_web_view_new at ./test_webkit.pl line 12.
(sorry for the german output, I tried LC_ALL=C and LC_ALL=en_US.utf8 without success)

A little example code that doesn't work could look like this:

`#!/usr/bin/perl`

`use strict;`
`use warnings;`

`use Gtk3 -init;`
`use Gtk3::WebKit;`

`my $window=Gtk3::Window->new();`
`$window->signal_connect('delete-event' => sub {Gtk3->main_quit()});`
`my $scroll_win = Gtk3::ScrolledWindow->new();`
`my $view = Gtk3::WebKit::WebView->new();`
`my $html_content = "<h1>Hello World</h1><br><p>This should be shown in the webview</p>";`
`$view->load_html_string($html_content, '');`
`$scroll_win->add($view);`
`$window->add($scroll_win);`
`$window->show_all();`
`Gtk3->main();`

the perl module Gtk3 and Gtk3::WebKit are installed (of course the tests of Gtk3::WebKit failed, too)

Has someone an idea or can help? It would be great if this error could be fixed and Gtk3::WebKit could be used! Because the perl module uses the Glib::Object::Introspection interface I think other language bindings (python, Vala) are also affected?
Thanks in advance,
Max

**Comment by mati865** [comment]
It need recompilation after https://github.com/Alexpux/MINGW-packages/pull/1611.
You can do it locally for yourself or wait for @Alexpux.

**Comment by MaxPerl** [comment]
Dear mati865,
thank you for your answer. I am very glad to hear that the problems will be fixed the next time! I don't want to steal your time. But if you could tell me how I can recompile it locally, this would be great! But probably this is beyond my capabilities?

**Comment by mingwandroid** [comment]
It is very easy to build msys2 packages.

Clone this repo, install mingw-w64-x86_64-toolchain and base-devel. cd to mingw-w64-gedit and type `MINGW_INSTALLS=mingw64 makepkg-mingw -sLf`

**Comment by mati865** [comment]
@mingwandroid you can add `-i --noconfirm` to make it even eaiser and more automated.
Final form: `MINGW_INSTALLS=mingw64 makepkg-mingw -sLfi --noconfirm`.

**Comment by MaxPerl** [comment]
Hello everybody,
thank you very much for your help. Unfortunately Building WebKitGtk3 doesn't work. Enclosed you find the install log and error messages.. Perhaps I have to wait for @Alexpux ,
Nevertheless thank you again very very much. You Msys2 people are really great!

Install log:
[webkit-install-log.txt](https://github.com/Alexpux/MINGW-packages/files/478589/webkit-install-log.txt)

**Comment by mati865** [comment]
Here is the problem: `checking for perl... /mingw64/bin/perl`.
Both MSYS2-packages and MINGW-packages are meant to be build from MSYS2 shell.
I'll provide prebuild packages when compilation finish.

**Comment by mati865** [comment]
So it failed after 9 hours of compilation, probably due math changes in GCC 6.x:
```
../webkitgtk-2.4.11/Source/WebCore/platform/gtk/GtkClickCounter.cpp: In member function 'int WebCore::GtkClickCounter::clickCountForGdkButtonEvent(GtkWidget*, GdkEventButton*)':
../webkitgtk-2.4.11/Source/WebCore/platform/gtk/GtkClickCounter.cpp:88:59: error: call of overloaded 'abs(gdouble)' is ambiguous
         || ((abs(buttonEvent->x - m_previousClickPoint.x()) < doubleClickDistance)
                                                           ^
In file included from D:/msys64/mingw64/include/c++/6.2.1/cstdlib:75:0,
                 from D:/msys64/mingw64/include/c++/6.2.1/stdlib.h:36,
                 from ../webkitgtk-2.4.11/Source/WTF/wtf/FastMalloc.h:25,
                 from ../webkitgtk-2.4.11/Source/JavaScriptCore/config.h:60,
                 from ../webkitgtk-2.4.11/Source/WebCore/platform/gtk/GtkClickCounter.cpp:19:
D:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:338:34: note: candidate: int abs(int)
   int __cdecl abs(int _X);
                                  ^
In file included from D:/msys64/mingw64/include/c++/6.2.1/stdlib.h:36:0,
                 from ../webkitgtk-2.4.11/Source/WTF/wtf/FastMalloc.h:25,
                 from ../webkitgtk-2.4.11/Source/JavaScriptCore/config.h:60,
                 from ../webkitgtk-2.4.11/Source/WebCore/platform/gtk/GtkClickCounter.cpp:19:
D:/msys64/mingw64/include/c++/6.2.1/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
D:/msys64/mingw64/include/c++/6.2.1/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
../webkitgtk-2.4.11/Source/WebCore/platform/gtk/GtkClickCounter.cpp:89:62: error: call of overloaded 'abs(gdouble)' is ambiguous
             && (abs(buttonEvent->y - m_previousClickPoint.y()) < doubleClickDistance)
                                                              ^
In file included from D:/msys64/mingw64/include/c++/6.2.1/cstdlib:75:0,
                 from D:/msys64/mingw64/include/c++/6.2.1/stdlib.h:36,
                 from ../webkitgtk-2.4.11/Source/WTF/wtf/FastMalloc.h:25,
                 from ../webkitgtk-2.4.11/Source/JavaScriptCore/config.h:60,
                 from ../webkitgtk-2.4.11/Source/WebCore/platform/gtk/GtkClickCounter.cpp:19:
D:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:338:34: note: candidate: int abs(int)
   int __cdecl abs(int _X);
                                  ^
In file included from D:/msys64/mingw64/include/c++/6.2.1/stdlib.h:36:0,
                 from ../webkitgtk-2.4.11/Source/WTF/wtf/FastMalloc.h:25,
                 from ../webkitgtk-2.4.11/Source/JavaScriptCore/config.h:60,
                 from ../webkitgtk-2.4.11/Source/WebCore/platform/gtk/GtkClickCounter.cpp:19:
D:/msys64/mingw64/include/c++/6.2.1/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
D:/msys64/mingw64/include/c++/6.2.1/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
```
It will need this patch: https://git.archlinux.org/svntogit/packages.git/tree/trunk/webkitgtk-2.4.9-abs.patch?h=packages/webkitgtk
I'll try to provide 64bit build anyway.

**Comment by MaxPerl** [comment]
Thank you very much for all your efforts! It would be great if the 64bit build will work!

Please let me ask a little question off-topic: Shall everything be built on the MSys terminal? Or can I build my perl scripts (if they need C /XS parts) also in the MinGW64 terminal (that is the way I go at the moment). If not, how can I then set that the build shall be for the mingw-x86_64 environment?

**Comment by mati865** [comment]
MSYS2 shell is used for building MINGW-packages and for software when compatibility with POSIX is more important than performance.
So you should use MINGW shells because they provide native software (like libwebkitgtk).

**Comment by mati865** [comment]
After very, very long time it compiled however I cannot test it due to missing perl module.
[mingw-w64-x86_64-webkitgtk3-2.4.11-1-any.pkg.tar.xz.zip](https://github.com/Alexpux/MINGW-packages/files/480208/mingw-w64-x86_64-webkitgtk3-2.4.11-1-any.pkg.tar.xz.zip) (note: you must unzip it first due to stupid github limits)

**Comment by MaxPerl** [comment]
Dear mati865,
Thank you very very much. Everything works now perfect! You are great!!!
Best regards,
Max

**Comment by mati865** [comment]
Glad to hear that it's working now.

**Comment by litch0** [comment]
@mati865, You saved my project, I am realy glad that people like you exist. If it is not inconvenient to ask, can you compile libwebkitgtk 4 plz. If not it's ok

**Comment by litch0** [comment]
Actually, I got to an error from wine, about missing libraries.
HERE: 
![image](https://user-images.githubusercontent.com/57605930/93278935-60403180-f79c-11ea-90a6-9e414c4041bf.png)
Do you guys know where can i find these libraries?

**Comment by Biswa96** [comment]
MSYS2 (or cygwin) can not be run in wine. If you want to run mingw packages you've to download the dependencies manually.

**Comment by mati865** [comment]
@litch0 sorry but I don't have enough time to investigate it.

**Comment by litch0** [comment]
I run it on windows, and the window doesn't open @Biswa96

**Comment by litch0** [comment]
Also, when I tried compiling the pkg from @mati865 , It give me these errors:
saying that the pkgs mingw-w64-x68_64-angleproject and mingw-w64-x68_64-geoclue are not resolvable

**Comment by mati865** [comment]
@litch0 webkitgtk package is no longer supported https://github.com/msys2/MINGW-packages/pull/5375

**Comment by litch0** [comment]
@mati865, But is it any way to compile it or just find the dlls?

**Comment by mati865** [comment]
@litch0 you have to build all the dependencies yourself.

**Comment by litch0** [comment]
ok, Is it like: 
Download Source and compile?

**Comment by mati865** [comment]
Yeah.

**Comment by litch0** [comment]
ok, I give up, I discovered another browser engine called Netsurf, I will try to embed they, webkit is not even supporting widows anyway

**Comment by litch0** [comment]
Thanks for your time I really appreciate
