### ISSUE TITLE
Failed to load 'C:\msys64\mingw64\lib\gedit\libgedit.dll'

### ISSUE THREAD

**Issue by MaxPerl** [Alexpux/MINGW-packages#1716]
Hello,

When I try to start gedit (mingw-w64-x86_64-gedit 3.20.2-1) I get the following error:

> Failed to load 'C:\msys64\mingw64\lib\gedit\libgedit.dll': 'C:\msys64\mingw64\lib\gedit\libgedit.dll': Die angegebene Prozedur wurde nicht gefunden. 
Failed to load 'libgedit.dll': 'libgedit.dll': Das angegebene Modul wurde nicht gefunden.

I still found this old bug: [https://github.com/Alexpux/MINGW-packages/issues/291](url)
But this was fixed long ago, so I don't think that my problem is connected with this issue.

Perhaps my MSys2 environment is wrongly set up, because with libwebkitgtk I got a similar error, see here: [https://github.com/Alexpux/MINGW-packages/issues/1715](url) ?

I have installed before the gedit package from [https://wiki.gnome.org/Apps/Gedit](url) but uninstalled it before I tried installing gedit in MinGW64. I don't know if this is important.

Thanks for your help and your great work!
Max

**Comment by mati865** [comment]
The same as #1715.
