### ISSUE TITLE
still problems with openocd makepkg

### ISSUE THREAD

**Issue by RoccoMarco** [Alexpux/MINGW-packages#1717]
Hi starting pkgbuild of openocd-git I receive this error

$ makepkg --config ${MAKEPKG_CONFIG}
==> ERROR: conflicts should be an array
==> ERROR: provides should be an array

the error disappears deleting conflicts and provides lines. But I don't know if this workaround can cause other issues.

**Comment by DavidEGrayson** [comment]
You can define an array in Bash with syntax like this:

    conflicts=(pkg1 pkg2)

You can look in other PKGBUILDs to see examples of how to define those arrays too.

**Comment by DavidEGrayson** [comment]
Also, the correct way to build MINGW packages is with the `makepkg-mingw` script provided by MSYS2.

**Comment by lazka** [comment]
Looks like this was fixed in #2050, so I'm closing this. Thanks @RoccoMarco !

**Comment by RoccoMarco** [comment]
Yes! I confirm
