### ISSUE TITLE
The mingw-w64-x86_64-gdb package errors out on startup if GCC is not installed

### ISSUE THREAD

**Issue by Eli-Zaretskii** [Alexpux/MINGW-packages#1729]
I installed GDB using pacman, and when I started it, it displayed this error message:

Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named libstdcxx.v6.printers
d:\usr\mingw64\mingw64\bin../etc/gdbinit:5: Error in sourced command file:
Error while executing Python code.

Guessing that the problem was with with some GCC-related file, I installed mingw-w64-x86_64-gcc, although I didn't need it, and the problem went away.  It looks like the problem is with the share/gcc-6.1.0/python/libstdcxx directory, which comes with GCC, but GDB references v6/printers.py from that directory.

So how does one install a MinGW64 GDB without GCC?  On that machine, I need to be able to debug MinGW64 executables, but I don't need to build them.

Thanks.

**Comment by Alexpux** [comment]
You can just skip this error. This is just information for you that pretty-printers are disabled

**Comment by Alexpux** [comment]
Or you just remove file gdbinit

**Comment by Eli-Zaretskii** [comment]
Yes, I know.  But your suggestions mean that Python extensions in GDB might not work.  At the minimum, this error is an annoyance that is better avoided.

Why not provide an empty etc/gdbinit with GDB, and the one you provide currently with GCC?  That sounds like a much cleaner solution.

**Comment by Alexpux** [comment]
well then need only provide gdbinit with GCC because I can't have two the same files in different packages without conflict

**Comment by Eli-Zaretskii** [comment]
OK, that's still cleaner than the current situation, IMO.

**Comment by Alexpux** [comment]
will think in next GCC rebuild. Will not do it immediately
