### ISSUE TITLE
Apply relocation fix patch from master to binutils port

### ISSUE THREAD

**Issue by Mistuke** [Alexpux/MINGW-packages#1765]
Hi,

Would it be possible to get this patch https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=384f7503344b1d07561f801ced7493858cde6164 applied to the binutils distributed here?

The bug it fixes is described here https://sourceware.org/bugzilla/show_bug.cgi?id=17955#c1 it's a rather small patch but fixes a very long standing problem for the GHC (Haskell compiler) on Windows when using the LLVM backend https://ghc.haskell.org/trac/ghc/ticket/8974.

Thanks

**Comment by mati865** [comment]
Damn, it could even fix issue with those `__ITM` symbols relocation we nuked from libstdc++.
@Alexpux is away for two weeks so you will have to wait.

**Comment by Mistuke** [comment]
@mati865 That's fine, hopefully it fixes those as well then :)

**Comment by mati865** [comment]
@Mistuke would you open PR with this patch or should I do it?

**Comment by Mistuke** [comment]
@mati865 I can open one, that's no problem.

**Comment by Mistuke** [comment]
binutils 2.27-2 with the patch has been released. Thanks!
