### ISSUE TITLE
DMake Source Archive is 404

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#1775]
The URL to the source archive for DMake is 404.

A bunch of other places it can be found is located on [FileFinder](http://www.filewatcher.com/m/dmake-4.12.2.tar.bz2.461738-0.html).

**Comment by mati865** [comment]
https://github.com/mohawk2/dmake/releases seems to be better than using mirror.

**Comment by galeksandrp** [comment]
#2314
