### ISSUE TITLE
GnuPG patches disable user profile based home directories

### ISSUE THREAD

**Issue by lmmarsano** [Alexpux/MINGW-packages#1778]
I'm trying to use MINGW packages for GnuPG deployments to multi-user machines.
I'd like GnuPG to keep its per user home directory files (keyrings, trust databases, etc) somewhere under users' profiles like GnuPG's default home directory (`%APPDATA%\Roaming\GnuPG` as explained in [FAQ](https://gnupg.org/faq/gnupg-faq.html#location_gpg_conf_file)).
Unfortunately, the MINGW GnuPG sets the home directory to `/home/` which all users would have to share.

```
$ gpg.exe -k -vv
gpg: NOTE: THIS IS A DEVELOPMENT VERSION!
gpg: It is only intended for test purposes and should NOT be
gpg: used in a production environment or with production keys!
gpg: keybox 'C:/Open/git/mingw64/home/pubring.kbx' created
gpg: C:/Open/git/mingw64/home/trustdb.gpg: trustdb created
gpg: using pgp trust model
```

The comments for the `--homedir` section of [the manual](https://gnupg.org/documentation/manuals/gnupg/GPG-Configuration-Options.html) explain this is the _portable_ home directory location, which can be enabled by creating 

> an empty file name gpgconf.ctl in the same directory as the tool gpgconf.exe

However, no such file exists, so portable mode enabled this way.
Instead, the comments for the [MINGW GnuPG patches](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-gnupg)

> Mingw always generate portable apps.

suggest patches were applied to _lock_ portable mode, leaving the user no way to undo it without recompilation.
Rather than lock the application into portability mode with patches, could you consider creating a blank gpgconf.ctl as the `--homedir` section of [the manual](https://gnupg.org/documentation/manuals/gnupg/GPG-Configuration-Options.html) recommends?

**Comment by mati865** [comment]
Mingw version is supposed to store it in /home/<username>

**Comment by mati865** [comment]
Cannot edit while on mobile, it should store it in `/home/<username>`

**Comment by lmmarsano** [comment]
Hi @mati865, I see: there must be something wrong with my installation.
I tried a fresh install, and it stores it there as you say.
Thanks!

**Comment by mati865** [comment]
Definitely MinGW version is wrong:
- gpg 2.1.15 (from MIGNW shell):
```
Home: D:/msys64/mingw64/home
```
- gpg 1.4.20 (from MSYS shell):
```
Home: ~/.gnupg
```
As workaround you can use old version from MSYS shell until it's fixed.

**Comment by abelcheung** [comment]
The path relocation path strikes me to be a bit odd -- is it an expected behavior to relocate homedir like how other folders (sysconfdir, datadir etc) are handled?

**Comment by peterbud** [comment]
I have started working on this, and now I have managed to update and compile `gnupg `to 2.1.22, and now the HOME folder points to `~/.gnupg`. However it seems that pathtools `single_path_relocation ()` does not convert such path to a normal fully qualified windows directory.

Before boiling the ocean: is this a known issue with pathtool, or am I doing something wrong?

**Comment by mingwandroid** [comment]
~ replacement happens at the shell level only, even on POSIX. I would fix this as high up the stack as possible. It's definitely not something that pathtool should ever see.

**Comment by peterbud** [comment]
Can you point to a good example in other library/package how this home name resolution is being done?

**Comment by peterbud** [comment]
See #2999

**Comment by Alexpux** [comment]
Won't fix
