### ISSUE TITLE
Setting environment variables from PKGBUILD

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#1789]
Apologies for the basic question: what is the standard way to add an enviroment variable during a package installation in PKGBUILD file? One of the packages I'd like to port is using two env variables in the code, and if they are not set it does not work. If I set them in my .bash_profile it works nicely.

**Comment by mingwandroid** [comment]
Do you mean during build or during installation?

If the former then you'd typically set them on the pertainent call, e.g.

`VAR1=FOO VAR2=BAR make`

If the latter then you need to write an install file and identify that in the PKGBUILD. There's lots of examples of these in this repository.

**Comment by DavidEGrayson** [comment]
There are many ways to set an environment variable depending on what scope
you want them to have.

If want to just temporarily set an environment variable for one Bash
session, run:

    export MYVAR=foo

If you want that variable to be set automatically whenever you use MSYS2,
put that line in your personal .profile or .bash_profile or .bashrc file in
your home directory, depending on how you have things set up.  The
documentation of Bash explains very clearly what files it runs when it
starts up, and if you put the command in any of those files, then the
environment variable will get set.  Depending on how your $HOME is set,
this may or may not apply to all instances of MSYS2 on your computer.

If you want to automatically set environment variables for every Bash
session of every user in a particular instance of MSYS2, add a command like
the one above to a shell script in /etc/profile.d/.  Its name should
probably have the extension ".sh".  You could do this manually, or you
could use pacman to install such a file, just like pacman would install any
other file in a package.  This is probably the answer you are looking for.

If you want to set an environment variable for yourself that works on all
instances of MSYS2, use the standard Windows interface for setting User
environment variables.

If you want to set an environment variable for all users and all instances
of MSYS2, use the standard Windows interface for setting System environment
variables.

I don't see how an install file (which lets you run arbitrary shell
commands when a package is installed) would help.

Also, I question why your package needs environment variables; if the
variables are missing, can't it just use some reasonable default values?

--David

**Comment by DavidEGrayson** [comment]
There are many ways to set an environment variable depending on what scope you want them to have.

If want to just temporarily set an environment variable for one Bash session, run:

```
export MYVAR=foo
```

If you want that variable to be set automatically whenever you use MSYS2, put that line in your personal .profile or .bash_profile or .bashrc file in your home directory, depending on how you have things set up.  The documentation of Bash explains very clearly what files it runs when it starts up, and if you put the command in any of those files, then the environment variable will get set.  Depending on how your $HOME is set, this may or may not apply to all instances of MSYS2 on your computer.

If you want to automatically set environment variables for every Bash session of every user in a particular instance of MSYS2, add a command like the one above to a shell script in /etc/profile.d/.  Its name should probably have the extension ".sh".  You could do this manually, or you could use pacman to install such a file, just like pacman would install any other file in a package.  This is probably the answer you are looking for.

If you want to set an environment variable for yourself that works on all instances of MSYS2, use the standard Windows interface for setting User environment variables.

If you want to set an environment variable for all users and all instances of MSYS2, use the standard Windows interface for setting System environment variables.

Also, I question why your package needs environment variables; if the variables are missing, can't it just use some reasonable default values?

**Comment by peterbud** [comment]
Hi David and Ray - thanks for the answer, I was looking for the /etc/profile.d solution.

And to answer for your question, I'm trying to port the [libgphoto2 library](https://github.com/gphoto/libgphoto2), and it usese two env variables: CAMLIBS and IOLIBS to locate the place where the libraries are.

I'm thinking to add something like this then:
`# install profile script `
`mkdir -p "${pkgdir}${MINGW_PREFIX}"/etc/profile.d`
`echo "export CAMLIBS=${MINGW_PREFIX}/lib//libgphoto2/2.5.10" > "${pkgdir}${MINGW_PREFIX}"/etc/profile.d/libgphoto2.sh`

**Comment by DavidEGrayson** [comment]
You should be careful to make sure that the 32-bit and 64-bit versions of your package do not interfere with eachother, for example by setting those environment variables to point to /mingw32 while you are running MinGW-w64 64-bit shell.  One way to do that would be to expand the $MINGW_PREFIX variable at run time instead of at package build time.  Also, be sure to put a bitness indicator in the shell script's filename so that there is not a name collision.
