### ISSUE TITLE
GCC 6.2.0 compile failure

### ISSUE THREAD

**Issue by EmilyBjoerk** [Alexpux/MINGW-packages#1792]
```
git clone https://github.com/Alexpux/MINGW-packages.git
cd MINGW-packages/mingw-w64-gcc
makepkg-mingw -sLf
```

Fails with missing file: `MINGW-packages/mingw-w64-gcc/src/0001-gcc-6-branch-gfortran-incorrect-reading-of-values-fr.patch`.

However the file: `MINGW-packages/mingw-w64-gcc/src/0001-gcc-5-branch-gfortran-incorrect-reading-of-values-fr.patch` does exist. Note gcc-5, instead of gcc-6. 

```
==> Extracting sources...
  -> Extracting gcc-6.2.0.tar.bz2 with bsdtar
==> Starting prepare()...
patch: **** Can't open patch file /src/MINGW-packages/mingw-w64-gcc/src/0001-gcc-6-branch-gfortran-incorrect-reading-of-values-fr.patch : No such file or directory
patching file intl/Makefile.in
patching file intl/bindtextdom.c
The next patch would create the file intl/canonicalize.c,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file intl/canonicalize.h,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file intl/relocatex.c,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file intl/relocatex.h,
which already exists!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored
==> ERROR: A failure occurred in prepare().
    Aborting...
```

Seems this was introduced in commit 54101537025a9a3a381a1e292fb9bc967e374bd2.

**Comment by mati865** [comment]
```
The next patch would create the file intl/canonicalize.c,
which already exists!  Assume -R? [n]
Apply anyway? [n]
```
Try removing `src/` or adding `-C` to makepkg.

**Comment by EmilyBjoerk** [comment]
Adding -c worked. I was following the instructions here:
https://sourceforge.net/p/msys2/wiki/Contributing%20to%20MSYS2/ where -c
wasn't mentioned.

2016-10-06 17:33 GMT+02:00 Mateusz Mikuła <notifications@github.com>:

**Comment by mati865** [comment]
It happens when patches create new files, during archive extraction modified files are overwritten so patches can be applied.
However files created by patches aren't removed and when patch tries to create file it will fail.

**Comment by mati865** [comment]
Can it be closed now?
