### ISSUE TITLE
Error while updating

### ISSUE THREAD

**Issue by filnet** [Alexpux/MINGW-packages#1795]
$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
 librepilot-mingw is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
warning: mingw-w64-i686-qt5: local (5.6.1-4) is newer than mingw32 (5.6.1-3)
resolving dependencies...
looking for conflicting packages...

Packages (28) mingw-w64-i686-binutils-2.27-2  mingw-w64-i686-cogl-1.22.2-1  mingw-w64-i686-gdb-7.12-1
              mingw-w64-i686-gst-plugins-base-1.8.3-1  mingw-w64-i686-gst-plugins-good-1.8.3-1  mingw-w64-i686-gtk3-3.22.1-1
              mingw-w64-i686-lcms2-2.8-1  mingw-w64-i686-libtool-2.4.6-7  mingw-w64-i686-libwebp-0.5.1-1  mingw-w64-i686-mpg123-1.23.8-1
              mingw-w64-i686-ncurses-6.0.20161001-1  mingw-w64-i686-openssl-1.0.2.j-1  mingw-w64-i686-ruby-2.3.1-1
              mingw-w64-i686-tcl-8.6.6-1  mingw-w64-i686-tk-8.6.6-1  mingw-w64-x86_64-binutils-2.27-2  mingw-w64-x86_64-cogl-1.22.2-1
              mingw-w64-x86_64-gdb-7.12-1  mingw-w64-x86_64-gtk3-3.22.1-1  mingw-w64-x86_64-lcms2-2.8-1  mingw-w64-x86_64-libtool-2.4.6-7
              mingw-w64-x86_64-libwebp-0.5.1-1  mingw-w64-x86_64-lua-5.3.3-1  mingw-w64-x86_64-mpg123-1.23.8-1
              mingw-w64-x86_64-ncurses-6.0.20161001-1  mingw-w64-x86_64-openssl-1.0.2.j-1  mingw-w64-x86_64-tcl-8.6.6-1
              mingw-w64-x86_64-tk-8.6.6-1

Total Installed Size:  511.01 MiB
Net Upgrade Size:        2.70 MiB

:: Proceed with installation? [Y/n](28/28) checking keys in keyring                                                     [###############################################] 100%
(28/28) checking package integrity                                                   [###############################################] 100%
(28/28) loading package files                                                        [###############################################] 100%
(28/28) checking for file conflicts                                                  [###############################################] 100%
error: failed to commit transaction (conflicting files)
mingw-w64-x86_64-lua: /mingw64/bin/luac exists in filesystem
Errors occurred, no packages were upgraded.

**Comment by filnet** [comment]
removing lua fixed it.

**Comment by mkae** [comment]
Well, I guess this is not really fixed, but!

It looks like the lua package needs some changes to not let this happen again in the future, right!?

**Comment by lazka** [comment]
As far as I can see this is due to #1793 replacing the .exe with a script.

pacman got a workaround to handle that case in the meantime in https://github.com/Alexpux/MSYS2-packages/pull/1013

So I think this is fixed (if not, say so)
