### ISSUE TITLE
g_message triggering crash if program started out of mingw shell

### ISSUE THREAD

**Issue by juml** [Alexpux/MINGW-packages#1796]
Hi.

My program started to crash after gtk update to 3.22 (3.22.1) if executed out of msys2 shell.
Via gdb turned it crashed on g_message() on call, if line disabled crash disappeared.
Running same program using msys2 shell works fine.
Used to work correctly using gtk 3.20.

Issue looks to be cause of crashes of glade (on start) and gedit too (on exit) if running out of mintty.

**Comment by juml** [comment]
Might this be just fixed upstream ?

ref:
https://git.gnome.org/browse/glib/commit/?id=615b847d981323477b507d39a736df9652d9b905
https://bugzilla.gnome.org/show_bug.cgi?id=772511

**Comment by mati865** [comment]
You can create PR and add this patch.

**Comment by juml** [comment]
fix verified
