### ISSUE TITLE
gstreamer doesn't export .a files for .dll.a files

### ISSUE THREAD

**Issue by rolftheunissen** [Alexpux/MINGW-packages#1807]

**Comment by DavidEGrayson** [comment]
I don't know anything about gstreamer in particular, but the .dll file (in the bin directory) is the dynamic shared object, and the .dll.a file is the import library.  You don't need both a .a and a .dll.a.

**Comment by lazka** [comment]
@rolftheunissen if the above answer didn't help feel free to post here or open a new issue. Please try to include more information regarding what you are trying to do and what fails.
