### ISSUE TITLE
opencv fails to build

### ISSUE THREAD

**Issue by filnet** [Alexpux/MINGW-packages#1808]
Error is:

Scanning dependencies of target opencv_viz
make[2]: **\* No rule to make target 'C:/building/msys64/mingw32/lib/libfreetype.dll.a', needed by 'bin/libopencv_viz310.dll'.  Stop.
make[1]: **\* [CMakeFiles/Makefile2:1513: modules/viz/CMakeFiles/opencv_viz.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....

I tracked the cause to ./lib/cmake/vtk-7.0 files having C:/building hardwired in them.

**Comment by Alexpux** [comment]
Well it  need to be fixed then

**Comment by Alexpux** [comment]
Well it  need to be fixed then. Better to fix cmake files to use relative paths.

**Comment by filnet** [comment]
Seems like the cmake files used to be fixed but that part was commented out by https://github.com/Alexpux/MINGW-packages/commit/6bc5380cb82d23f5263a2f9fc28859f8690cc718#diff-f0af008e4ef358aff651913acc1672f4

Will see if I can put it back.

**Comment by filnet** [comment]
opencv is fine
