### ISSUE TITLE
unable to build package

### ISSUE THREAD

**Issue by BazelFaron** [Alexpux/MINGW-packages#1812]
Hello, i'm trying to build ANY package I've downloaded from the Alexpux/MINGW-packages repo.
1)after the makepkg-mingw command I always getting error like this:
==>required dependencies:
  -> mingw-w64-x86_64-gcc
  -> mingw-w64-x86_64-gcc-ada
-----etc.
2)However if I run the windows shell(cmd) and type gcc -v it states I have 6.2.0.(x86_64-win32-seh-rev1, Built by MinGW-64 project). Also I've installed the base-devel , mingw-w64-x86_64-toolchain packages.
3)My mingw64 compiler is in C;/msys2/mingw64 folder 
4)also In the PATH system variable : 
C:\msys64\usr\bin; C:\msys64\mingw64\bin

Can you help me, please? Thanks in advance!

**Comment by Alexpux** [comment]
MSYS2 build system works only with its own GCC packages, not third party

**Comment by BazelFaron** [comment]
i'm a little bit confused, can you clarify a bit please. following the wiki:

> The core packages groups you need to install if you wish to build from PKGBUILDs are:
> - base-devel for any building
> - msys2-devel for building msys2 packages
> - mingw-w64-i686-toolchain for building mingw32 packages
> - mingw-w64-x86_64-toolchain for building mingw64 packages

these steps done. Also I've found a lot of packages in the directory : 
C:\msys64\var\cache\pacman\pkg and installed them using the pacman -U ${package-name}*.pkg.tar.xz 
command. If i got you right, this last step was wrong?

**Comment by Alexpux** [comment]
You write that "gcc -v it states I have 6.2.0.(x86_64-win32-seh-rev1, Built by MinGW-64 project)".
But our GCC output is "Built by MSYS2 project". So you seems use wrong compiler.

**Comment by BazelFaron** [comment]
okay, i got you, thanks for help and the fast feeback!
