### ISSUE TITLE
building mingw-w64-binutils package fails

### ISSUE THREAD

**Issue by BazelFaron** [Alexpux/MINGW-packages#1814]
Hello! building the mingw-w64-gnutls from the  package fails with error:
==> Проверка подписей исходных файлов с помощью 'gpg'**...//means checking files with gpg**
    binutils-2.27.tar.bz2 ... СБОЙ (неизвестный открытый ключ C3126D3B4AE55E93**)//unknown open key**
==> ОШИБКА: Одна или больше PGP-подписей не могут быть проверены**!//one or more PGP-signs could not be checked**
 
base-devel, msys2-devel, mingw-w64-x86_64-toolchain packages are installed.

**Comment by Alexpux** [comment]
pass --skippgpcheck

**Comment by BazelFaron** [comment]
thanks a lot!
