### ISSUE TITLE
building mingw-w64-binutils package fails. (Unable to create a packjage file)

### ISSUE THREAD

**Issue by BazelFaron** [Alexpux/MINGW-packages#1820]
Hello again, sorry to bother you, but can you help me please. It seems like after building the package something fails to archive the package:
==> Очистка...
  -> Удаление файлов libtool...  **//deleting  libtool's files**
  -> Удаление ненужных файлов...  **//deleting unnecessary files**
  -> Удаление отладочной информации из бинарников и библиотек..**.//deleting debug info**
  -> Сжатие документации (man и info)...**//compressing  docs**
==> Checking for packaging issue...
==> Создание пакета "mingw-w64-x86_64-binutils"... **//creating package**
  -> Создание файла '.PKGINFO'... **//creating file**
  -> Создание файла '.BUILDINFO'...**//creating file**
  -> Создание файла '.MTREE'...**//creating file**
  -> Сжатие пакета..**.//compressing**
: archive_write_pax_header: 'x' header failed?!  This can't happen.
==> ОШИБКА: Не удалось создать файл пакета.**//unable to create package file**

Sorry if that's a stupid question, but searching in internet gave no resutls. Thanks in advance!

**Comment by Alexpux** [comment]
well I think this is due to incompatibility with locales.
I'm always run makepkg as:
"LC_ALL=C LANGUAGE=en_US.UTF-8 makepkg-mingw ..."
I'm also Russian))

**Comment by BazelFaron** [comment]
Okay i'll try, and come back with result. thanks a lot again for the quick reply! Крутой !)

**Comment by BazelFaron** [comment]
same error :(. May it be something with user/admin rights?

**Comment by Alexpux** [comment]
Maybe, check also that directory do not contain spaces. Also I remember that I see such errors when log into windows with domain user

**Comment by mati865** [comment]
I don't understand what is said there but error is the same https://github.com/Alexpux/MSYS2-packages/issues/90

**Comment by BazelFaron** [comment]
> I don't understand what is said there but error is the same Alexpux/MSYS2-packages#90
thanks a lot, i'll try and come back with result.

**Comment by BazelFaron** [comment]
on my home pc the package build without this error. Thanks for help guys!
