### ISSUE TITLE
application using poco NetSSL crash on startup

### ISSUE THREAD

**Issue by oxillo** [Alexpux/MINGW-packages#1823]
The following code works with older version (GCC5) but crashes as soon as the application starts with latest version.
```C
#include <iostream>
#include "Poco/Net/NetSSL.h"

int main( ){
		std::cerr << "initializeSSL...";
        Poco::Net::initializeSSL();
		std::cerr << "Done\n";
		
		std::cerr << "uninitializeSSL...";
		Poco::Net::uninitializeSSL();
		std::cerr << "Done\n";
        
}

**Comment by Alexpux** [comment]
Try rebuild POCO yourself with GCC6

**Comment by oxillo** [comment]
did not rebuilt correctly with - 
```
MINGW_INSTALLS=mingw32 makepkg-mingw -sLf
```

error when building pocoXML.dll

**Comment by Alexpux** [comment]
What error? Try to fix it if you can

**Comment by rulez85** [comment]
I have a similar issue when I try to run a simple application using Poco::Net::initializeSSL() under WindowsCE x86 (compiling with vs2008 and STANDARDSDK_500).

```
#include <Poco/Net/NetSSL.h>
void foo()
{
   Poco::Net::initializeSSL();  // if you comment this line, the program runs successfully
}

int _tmain(int argc, _TCHAR* argv[])
{
    printf("pippo\n");
    return 0;
}
```
The application crashes when loading before reaching the first line of the main method.
Could this issue be related to this post?
Thanks in advance
