### ISSUE TITLE
Libmicrohttpd

### ISSUE THREAD

**Issue by marcin-sielski** [Alexpux/MINGW-packages#1826]
Hi,

I just would like to point out that  Libmicrohttpd does not work on Windows 10 at
all if it is not compiled with  CFLAGS="-DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -D_POSIX_C_SOURCE" thus it is useless library. It probably may be compiled for 0x0602
as well to work on Windows 10.

I am not sure how to solve this issue. My commit that fixes it was removed.

Best Regards

Marcin Sielski

**Comment by Alexpux** [comment]
I'm remove your commit because it break support of older platforms.

**Comment by marcin-sielski** [comment]
I am curious what Windows platforms are supported by this project.
I believe that microhttpd do not work on Windows 10, 8, 7, Vista in the form that it is currently compiled
I believe that adding compilation option >= 0x0600 would sufficient.

**Comment by mati865** [comment]
@marcin-sielski how can we test this lib? Any minimal example?

**Comment by marcin-sielski** [comment]
Hi,

Sure here you go:
https://github.com/marcin-sielski/simplehttpd
CFLAGS="-DWINVER=0x0502 -D_WIN32_WINNT=0x0502 -D_POSIX_C_SOURCE" does not work
CFLAGS="-DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -D_POSIX_C_SOURCE" works fine
on Windows 10. Presumably it works for Windows 8, 7 and Vista. Here is reference a
https://msdn.microsoft.com/pl-pl/library/windows/desktop/aa383745(v=vs.85).aspx

Hope that helps.

Best Regards

Marcin Sielski

**Comment by mati865** [comment]
Your previous fix was removed because it set minimal version to Win 10 which is not acceptable. However setting minimal version to Vista is much more reasonable and I would vote for merging it.

**Comment by Alexpux** [comment]
Well create new pull request then. Do no forget update pkgrel
