### ISSUE TITLE
gcc -print-prog-name=ld returns Windows-style path

### ISSUE THREAD

**Issue by ncihnegn** [Alexpux/MINGW-packages#1827]
Part of libffi _configure_ script:
> case $host in
  *-*-mingw*)
    # gcc leaves a trailing carriage return which upsets mingw
    ac_prog=`($CC -print-prog-name=ld) 2>&5 | tr -d '\015'` ;;
  *)
    ac_prog=`($CC -print-prog-name=ld) 2>&5` ;;
  esac
  echo $ac_prog
  case $ac_prog in
    # Accept absolute paths.
    [\\/]* | ?:[\\/]*)
      re_direlt='/[^/][^/]*/\.\./'
      # Canonicalize the pathname of ld
      ac_prog=`$ECHO "$ac_prog"| $SED 's%\\\\%/%g'`
      while $ECHO "$ac_prog" | $GREP "$re_direlt" > /dev/null 2>&1; do
  	ac_prog=`$ECHO $ac_prog| $SED "s%$re_direlt%/%"`
      done

It will be trapped in the loop like:
> checking for ld used by gcc... 

Because _gcc -print-prog-name=ld_ returns
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe

instead of /mingw64/bin/ld.exe

**Comment by Alexpux** [comment]
Because GCC is native Windows program. It can't print path in UNIX format. Something with configure script itself

**Comment by ncihnegn** [comment]
You are right. Perhaps my grep is messed up.
