### ISSUE TITLE
gdk-pixbuf2 package is not adding loaders to the package

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#1838]
As I see the mingw-w64-gdk-pixbuf2 package is not adding the loaders to the package.
**$ pacman -Ql mingw-w64-x86_64-gdk-pixbuf2**

shows this filelist (stripped the doc files):
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/bin/
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/bin/gdk-pixbuf-csource.exe
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/bin/gdk-pixbuf-pixdata.exe
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/bin/gdk-pixbuf-query-loaders.exe
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/bin/libgdk_pixbuf-2.0-0.dll
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-animation.h
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-autocleanups.h
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-core.h
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-enum-types.h
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-features.h
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-io.h
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-loader.h
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-macros.h
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-marshal.h
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-simple-anim.h
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-transform.h
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/lib/
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/lib/gdk-pixbuf-2.0/
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/lib/gdk-pixbuf-2.0/2.10.0/
**mingw-w64-x86_64-gdk-pixbuf2 /mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/**
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/lib/girepository-1.0/
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/lib/girepository-1.0/GdkPixbuf-2.0.typelib
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/lib/libgdk_pixbuf-2.0.a
mingw-w64-x86_64-gdk-pixbuf2 /mingw64/lib/libgdk_pixbuf-2.0.dll.a

I expect that at lest the following files should be there:
/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ani.dll
/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-bmp.dll
/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-gif.dll
/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-icns.dll
/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ico.dll
/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jasper.dll
/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.dll
/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pnm.dll
/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-qtif.dll
/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/ibpixbufloader-tga.dll
/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tiff.dll
/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xbm.dll
/mingw64/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.dll

Is ther a specific reason not having them in the package?

**Comment by mati865** [comment]
Maybe they are not build or not packaged. Fixes are welcome.

**Comment by peterbud** [comment]
Fair enough :) Just I was not very familiar with this library, and I thought maybe somebody knows it rigth away. Anyhow, I have made a research and seems to have a simple fix and PR #1841
