### ISSUE TITLE
Procedure entry points cannot be found in libs sigc, cairomm, glibmm, giomm

### ISSUE THREAD

**Issue by db0451** [Alexpux/MINGW-packages#1855]
Hello,

When trying to compile against the above with latest g++ 6.2, I get 'procedure entry point failed' errors for all. I guess they need to be updated.

Thanks for all the great work!

**Comment by db0451** [comment]
Hmm, I just rebuilt these from git, and the same errors still occur:

- _ZdllPvj in libsigc-2.0-0.dll
- _ZNSt11logic_errorC2EPKc in libcairomm-1.0-1.dll
- _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESalcEE4copyEPcjj in libglibmm-2.4-1.dll
- _ZNST7__cxx1112basic_stringIcSt11char_traitsIcESalcEE10_M_replaceEjjPKcj in libgiomm-2.4-1.dll

Maybe I'm just doing something else wrong?

**Comment by db0451** [comment]
Hi,

Do these need to be rebuilt? If so, could that be done before too long?

Thanks a lot!

**Comment by mingwandroid** [comment]
You need to provide a working testcase showing the problem.

http://sscce.org

**Comment by db0451** [comment]
I got this working OK on a different installation of MSYS2 so will assume there was something wrong with the original one and close unless I can ever reproduce it again (with more detail)
