### ISSUE TITLE
GnuPG requires Sqlite3

### ISSUE THREAD

**Issue by mattico** [Alexpux/MINGW-packages#1858]
`mingw-w64-gnupg` should depend on `mingw-w64-sqlite3`

Attempting to launch gpg without sqlite gives the error:

```
C:/msys64/mingw64/bin/gpg.exe: error while loading shared libraries: libsqlite3-0.dll: cannot open shared object file: No such file or directory
```

**Comment by peterbud** [comment]
As I see @Alexpux has fixed this: [af86b90](https://github.com/Alexpux/MINGW-packages/commit/085121414b643a4cb2c4a9859f6a699583e5badd).
@mattico: Can you check this, and if this works, close the issue?
