### ISSUE TITLE
Question: xml2-config contains hard-coded library path

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#1864]
I have noticed that the xml2-config file contains hard-coded library path, like "C;/building"

```
    --libs)
        if [ "`uname`" = "Linux" ]
    then
        if [ "-L${libdir}" = "-L/usr/lib" -o "-L${libdir}" = "-L/usr/lib64" ]
        then
        echo -lxml2 -LC:/building/msys64/mingw64/lib -lz -LC:/building/msys64/mingw64/lib -llzma   -liconv    
        else
        echo -L${libdir} -lxml2 -LC:/building/msys64/mingw64/lib -lz -LC:/building/msys64/mingw64/lib -llzma   -liconv    
        fi
    else
        echo -L${libdir} -lxml2 -LC:/building/msys64/mingw64/lib -lz -LC:/building/msys64/mingw64/lib -llzma   -liconv     -lws2_32
    fi
        ;;
```

Is this something which we should worry about, or it is OK?

**Comment by peterbud** [comment]
@Alexpux : who is the best contact for mingw-w64-x86_64-libxml2 package?

**Comment by mati865** [comment]
There are plenty packages with `C:/building/msys64` hard-coded (https://github.com/Alexpux/MINGW-packages/issues/1670) and it would be great if even some of them got fixed.

**Comment by peterbud** [comment]
So I understand it right, that they should not be there... Will take a look at this.
