### ISSUE TITLE
OCE: CMake script references C:/building/msys64/mingw64/lib/libfreetype.dll.a

### ISSUE THREAD

**Issue by GyrosGeier** [Alexpux/MINGW-packages#1870]
With the latest OCE packages, we get build failures for KiCad while linking against OCE, as OCE-libraries-release.cmake contains the above path as the location for the freetype library:

make[2]: **\* No rule to make target 'C:/building/msys64/mingw64/lib/libfreetype.dll.a', needed by 'utils/kicad2step/kicad2step.exe'.  Stop.

Full KiCad build log at http://ci.kicad-pcb.org/job/windows-kicad-msys2-debug-nightlies/365/console

**Comment by peterbud** [comment]
Hi, I believe it is similar to this issue: #1864
