### ISSUE TITLE
mingw-w64-gnome-doc-utils not in the repository?

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#1884]
I see that there should be a [mingw-w64-gnome-doc-utils  ](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-gdk-pixbuf2)in the MINGW repository, though you cannot find it by `pacman -Ss doc-utils` and you cannot install by `pacman -S mingw-w64-gnome-doc-utils`

Anybody knows why?

**Comment by lazka** [comment]
`pacman -S gnome-doc-utils` works here

https://github.com/Alexpux/MSYS2-packages/tree/master/gnome-doc-utils

**Comment by peterbud** [comment]
MSYS2 package is not the same as MINGW package.
This is the source of [MSYS2 package](https://github.com/Alexpux/MSYS2-packages/tree/master/gnome-doc-utils) and this is the source of [MINGW package](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-gnome-doc-utils)
I can access the MYS2 version, but I'd need the MINGW version.

**Comment by Alexpux** [comment]
I'm not create mingw package for gnome-doc-utils because it need docbook-xml working.

**Comment by peterbud** [comment]
I got it. Let me see whether I can help. Do you know what is **not** working today with the docbook-xml?

**Comment by Alexpux** [comment]
Well it hard to tell. Mostly it not work because of wrong paths or wrong conversion

**Comment by peterbud** [comment]
@Alexpux : I have spent some time with the mingw-w64-docbook-xml. What I have found is the following: the created XML catalog files and the docbook-xml file is OK, and all the DTD files seem to be in place. Nevertheless I was unsuccessful to validate a docbook file (`sample.xml`) with the following command:
`xmllint  --valid --nonet sample.xml`

Turning on the catalog debug reveals the following:
`XML_DEBUG_CATALOG=1 xmllint  --valid --nonet sample.xml`
```
Resolve: pubID -//OASIS//DTD DocBook XML V4.5//EN sysID http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
Failed to parse catalog file:///etc/xml/catalog
```

So it seems that the default catalog location is **wrong**. With further research I have found that actually you can validate the docbook file with the installed DTDs if you use the following command:
`XML_DEBUG_CATALOG=1 XML_CATALOG_FILES="/mingw64/etc/xml/catalog" xmllint  --valid --nonet sample.xml`

So IMHO the only issue is that the default XML catalog file location in the **libxml** package is wrong. In catalog.c the default location is defined at line 72:

```
#ifndef XML_XML_DEFAULT_CATALOG
#define XML_XML_DEFAULT_CATALOG "file:///etc/xml/catalog"
#endif
```

Do you agree that we need to have a conditional define here for a MINGW compile?

**Comment by peterbud** [comment]
@Alexpux : I have tested gnome-doc-utils, and with the new docbook-xml it works for me pretty OK. Would you mind adding back the binary package to the repo? For automated builds it would be great.
