### ISSUE TITLE
mingw-w64-imagemagick: missing ENV variables

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#1885]
After you install mingw-w64-imagemagick with pacman, apparently it cannot locate its coder modules and configure path. Symptoms are the following errors::
```
$ convert -resize "800x800" test.jpg test.png
convert.exe: no decode delegate for this image format `JPG' @ error/constitute.c/ReadImage/508.
convert.exe: no images defined `test.png' @ error/convert.c/ConvertImageCommand/3253.
```
Adding the following to your bash_profile solves the problem:
```
export MAGICK_HOME="/mingw64/bin"
export MAGICK_CONFIGURE_PATH="/mingw64/etc/ImageMagick-7"
export MAGICK_CODER_MODULE_PATH="/mingw64/lib/ImageMagick-7.0.3/modules-Q16HDRI/coders"
```
` convert -resize 800X800 test.jpg test.png` runs without error

Should have been these variables defined at compile time? Or should they be defined with a profile.d script?

**Comment by schmittl** [comment]
Just came across the same problem.

I am just guessing here, but the `001-7.0.1.3-relocate.patch` for the imagemagick package seems suspicious to me:

```
+CODER.XML      IMAGEMAGICK DISCARDABLE "..\\etc\\ImageMagick-6\\coder.xml"
+COLORS.XML     IMAGEMAGICK DISCARDABLE "..\\etc\\ImageMagick-6\\colors.xml"
+CONFIGURE.XML     IMAGEMAGICK DISCARDABLE "..\\etc\\ImageMagick-6\\configure.xml"
+DELEGATES.XML  IMAGEMAGICK DISCARDABLE "..\\etc\\ImageMagick-6\\delegates.xml"
+ENGLISH.XML    IMAGEMAGICK DISCARDABLE "..\\share\\ImageMagick-6\\english.xml"
+LOCALE.XML     IMAGEMAGICK DISCARDABLE "..\\share\\ImageMagick-6\\locale.xml"
+LOG.XML        IMAGEMAGICK DISCARDABLE "..\\etc\\ImageMagick-6\\log.xml"
+MAGIC.XML      IMAGEMAGICK DISCARDABLE "..\\etc\\ImageMagick-6\\magic.xml"
+THRESHOLDS.XML  IMAGEMAGICK DISCARDABLE "..\\etc\\ImageMagick-6\\thresholds.xml"
+TYPE.XML       IMAGEMAGICK DISCARDABLE "..\\etc\\ImageMagick-6\\type.xml"
+TYPE-GHOSTSCRIPT.XML  IMAGEMAGICK DISCARDABLE "..\\etc\\ImageMagick-6\\type-ghostscript.xml"
```

The directories should probably point to`ImageMagick-7` instead of `ImageMagick-6`

**Comment by mati865** [comment]
@schmittl you are right, @JPeterMugaas probably missed it when updating patch.

**Comment by peterbud** [comment]
Unfortunately its not so easy. I have just tried to fix that patch with "ImageMagick-7", then recompiled and installed, but still does not work. I believe what we need is to set at compile time properly the MAGICK_CODER_MODULE_PATH. I'll do some more research.

**Comment by Ede123** [comment]
Quick related question:
It seems the relocation is hardwired to `..\\etc` and `..\bin`? It deems this breaks proper relocation for package structures where a programs main executable and the libraries are located directly in the root for the installation.

Do you have any elegant workarounds for that or do I have to set environment variables / rewrite the relocations patches?

**Comment by paulalanthompson** [comment]
I am continuing to get the error of locating the configure.xml file

convert.exe: unable to locate configure file 'configure.xml' 

I found it in a different place, and when I copied it to

..\etc\ImageMagick-7

the error went away. I am still out the 3 days that it took to figure this out.
