### ISSUE TITLE
How to target 32bit architecture from the 64bit shell? (using -m32)

### ISSUE THREAD

**Issue by ukhf-jm** [Alexpux/MINGW-packages#1888]
Firstly, I am aware that there is the 32bit shell where I can build 32bit binaries but I wanted to be able to compile 32bit binaries using the -m32 switch.

I first tried `$ g++ -static test.cpp -o test32 -m32` which gave a lot of errors about not being able to find all the default libraries.  
```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0\libstdc++.a when searching for -lstdc++  
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lstdc++  
...
```

I then tried giving the directories to the i686 lib folders but got a lot of undefined references for the crt library, `$ g++ -static -m32 -LC:/msys64/mingw32/i686-w64-mingw32/lib -LC:/msys64/mingw32/lib/gcc/i686-w64-mingw32/6.2.0 test.cpp -o test32`

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/lib/crt2.o: In function `pre_c_init':
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:130: undefined reference to `_set_app_type'
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:133: undefined reference to `encode_pointer'  
...
```

So perhaps I'm being an idiot but can someone point out what I'm doing wrong?
I'm guessing that the linker is still picking up the x64 version of the CRT.

As for why I wanted to do this, I wanted to be able to setup a CMake project that used compiler flags to target 32bit builds as well as the default 64bit (hence the -m32 flag).  
Is it possible or will I have to change the toolchain directory when I want to build a 32bit version of the program?

**Comment by mingwandroid** [comment]
We do not build multilib compilers on MSYS2 because that forces 32-bit and 64-bit to use the same exception model, and the only one that is compatible with both is sjlj which is there worst option for both (think of it like a lowest common denominator).

You can probably get away with prefixing your path with `/mingw32/bin` before running cmake, but you should really check all the other differences between the shells (using `env` and `diff` for example) to ensure you don't run into issues.

**Comment by ukhf-jm** [comment]
Thanks for the explanation @mingwandroid . Isn't SEH available for both 32bit and 64bit? I know it's used in the 64bit compiler but I thought I remembered some news near the start of the year that it was now usable on 32bit with GCC. I might be remembering incorrectly though (that wouldn't be a surprise).

**Comment by mati865** [comment]
It's not that easy. You can read whole discussion at https://sourceforge.net/p/mingw-w64/mailman/message/35433261/

**Comment by ukhf-jm** [comment]
Thanks @mati865 . I found that I was misremembering what I had read regarding SEH on 32bit (here's the link http://blog.davidegrayson.com/2016/02/windows-32-bit-structured-exception.html ) but yeah, read up on the discussion you linked as well. Appreciate the time you both took to respond to this. Like I thought, I was being an idiot and not considering the exception handling. Thanks
