### ISSUE TITLE
adwaita-icon-theme: no windows cursors

### ISSUE THREAD

**Issue by bpisoj** [Alexpux/MINGW-packages#1906]
Try running gtk3-demo->Cursors and click on any buttons.
As a result cursor either disappear or is not anything like one pictured on button.
Adding line "gtk-cursor-theme-name=Adwaita" to etc/gtk-3.0/settings.ini does not changing anything except printing "Gdk-WARNING **: Failed to load cursor theme Adwaita"

Looks like adwaita-icon-theme ships XCursor and Gtk can not work with them.

If i manually convert first one called "alias" to windows cursor format "alias.cur" there is no more warnings and if you click on first button in "Drag and Drop" in before mention program you see that pointer start look as one pictured on button.

Don't know why PKGBUILD don't produce windows version of cursors but i see on https://github.com/GNOME/adwaita-icon-theme/tree/master/src/cursors two python files whose function is like to be that.

[alias.zip](https://github.com/Alexpux/MINGW-packages/files/574216/alias.zip)

**Comment by juml** [comment]
In official tarball (https://download.gnome.org/sources/adwaita-icon-theme/3.22/adwaita-icon-theme-3.22.0.tar.xz) there are no python scripts (and src/cursors/pngs/make-w32.sh too).

**Comment by lazka** [comment]
I've created an upstream patch for this: https://bugzilla.gnome.org/show_bug.cgi?id=774671

**Comment by lazka** [comment]
It's now in upstream master: https://git.gnome.org/browse/adwaita-icon-theme/commit/?id=fa1a4b9181111c3e4d0111ee87f8b4288a1f1ecb
