### ISSUE TITLE
Compile failure ImageMagick

### ISSUE THREAD

**Issue by EmilyBjoerk** [Alexpux/MINGW-packages#1907]
The tarball referred in the `MINGW-packages/mingw-w64-imagemagick/PKGBUILD` no longer exists.

Also build problems described here: http://www.wizards-toolkit.org/discourse-server/viewtopic.php?f=1&t=30804&p=139539&sid=2274a8869b702910bdcef329a176976c#p139539 

ImageMagick developer claims no patchset is necessary to compile, waiting for more feedback from them atm.

**Comment by peterbud** [comment]
Yesterday evening the package has been updated to use version 7.0.3.5. You can find it merged intot the master branch now.

**Comment by EmilyBjoerk** [comment]
/src/MINGW-packages/mingw-w64-imagemagick
$ makepkg -sLfC
==> Making package: mingw-w64-imagemagick 7.0.3.5-2 (Tue, Nov 08, 2016  9:29:22 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading ImageMagick-7.0.3-5.tar.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8089k  100 8089k    0     0   867k      0  0:00:09  0:00:09 --:--:-- 1194k
  -> Downloading ImageMagick-7.0.3-5.tar.xz.asc...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   801  100   801    0     0   1064      0 --:--:-- --:--:-- --:--:--  1068
  -> Found ImageMagick-7.0.1.3-mingw.patch
  -> Found 001-7.0.1.3-relocate.patch
  -> Found 002-7.0.3.1-build-fixes.patch
  -> Found 003-7.0.1.8-cplusplus-fixes.patch
  -> Found 004-7.0.3.5-build-fixes.patch
==> Validating source files with sha256sums...
    ImageMagick-7.0.3-5.tar.xz ... Passed
    ImageMagick-7.0.3-5.tar.xz.asc ... Skipped
    ImageMagick-7.0.1.3-mingw.patch ... Passed
    001-7.0.1.3-relocate.patch ... Passed
    002-7.0.3.1-build-fixes.patch ... Passed
    003-7.0.1.8-cplusplus-fixes.patch ... Passed
    004-7.0.3.5-build-fixes.patch ... Passed
==> Verifying source file signatures with gpg...
    ImageMagick-7.0.3-5.tar.xz ... FAILED (unknown public key 89AB63D48277377A)
==> ERROR: One or more PGP signatures could not be verified!

**Comment by mati865** [comment]
You don't have this key imported, add `--skippgpcheck` to makepkg or import key with `gpg --recv-key 89AB63D48277377A` and then use makepkg-mingw without `--skippgpcheck`.
