### ISSUE TITLE
SDL2_mixer: Wrong name of the shared library

### ISSUE THREAD

**Issue by danpla** [Alexpux/MINGW-packages#1910]
The shared library of SDL2_mixer is named as `libSDL2_mixer-2-0-0.dll`, but the right name is `SDL2_mixer.dll`, as in previous releases. All other SDL2 DLLs names are  `SDL2.dll`, `SDL2_image.dll`, `SDL2_net.dll`, and `SDL2_ttf.dll`.

**Comment by mati865** [comment]
Upstream decides their naming convention so you should ask there.
Arch Linux have similar names https://www.archlinux.org/packages/extra/x86_64/sdl2_mixer/files
