### ISSUE TITLE
Question: Update of http://repo.msys2.org/mingw/x86_64/

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#1914]
Recent updates since 25th October (ie: #1875) are not available in the official repo, although they have been merged. When the repo is normally refreshed?

**Comment by mati865** [comment]
When @Alexpux have enough free time to do it.

**Comment by peterbud** [comment]
I see - thanks!

**Comment by peterbud** [comment]
@mati865 as a second tought; would it be possible to extend the Appveyor script to build and deploy to the repo (and mirrors) those packages which were merged into master?
