### ISSUE TITLE
lldb: process launch failed unable to locate lldb-server

### ISSUE THREAD

**Issue by dthpham** [Alexpux/MINGW-packages#1941]
Hello, lldb is returning this error every time I try to use it.
```
$ lldb a.o
(lldb) target create "a.o"
Current executable set to 'a.o' (x86_64).
(lldb) run
error: process launch failed: unable to locate lldb-server
```

`pacman -Ql mingw-w64-x86_64-lldb` shows that lldb-server doesn't exist.

**Comment by mati865** [comment]
Yes, it's an upstream decision https://github.com/llvm-mirror/lldb/blob/ceb5f6cd339a4bcd49666158578f883c1ec96663/cmake/modules/LLDBConfig.cmake#L362
I'll try to get it working when I get more time.

**Comment by mati865** [comment]
There is a lot of POSIX code so there will be no lldb-server available.
Need to see if there is another way to use lldb on Windows.

**Comment by mati865** [comment]
@dthpham you could try to use LLDB with https://github.com/facebook/ds2

Additionally python support depends on https://github.com/Alexpux/MINGW-packages/issues/1944
