### ISSUE TITLE
Lua - Minor install path niggle

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#1943]
[Line 83](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-lua/PKGBUILD#L83)

Shouldn't that be `install -Dm644 ../LICENSE "$pkgdir"${MINGW_PREFIX}/share/licenses/$pkgname/LICENSE`?

**Comment by mati865** [comment]
Yes, you can create PR with fix.

**Comment by galeksandrp** [comment]
No, why do you want to install license to `/mingw64/share/licenses/mingw-w64-x86_64-lua/LICENSE` instead of `/mingw64/share/licenses/lua/LICENSE`?
