### ISSUE TITLE
The 'mingw-w64-hunspell-en' package not accessible through Pacman

### ISSUE THREAD

**Issue by Alexander-Shukaev** [Alexpux/MINGW-packages#1958]
For some reason, one cannot `pacman -S mingw-w64-x86_64-hunspell-en` as the package is not found.  `pacman -Sqs` of course does not list the package as well.  What is the reason for the package not being officially installable?

**Comment by peterbud** [comment]
Not all the packages are in the [repo](http://repo.msys2.org/mingw/), it really depends on @Alexpux and his free time. But in theory you build it for yourself using the PKGBUILD file.

**Comment by Alexander-Shukaev** [comment]
That's what I did actually.  Anyway, I was just curious whether there is any technical limitation here.  My point is that `mingw-w64-x86_64-hunspell` is available but is unusable unless dictionaries coming from `mingw-w64-x86_64-hunspell-en` are installed.

**Comment by peterbud** [comment]
@Alexander-Shukaev as I see `mingw-w64-x86_64-hunspell-en` is available. Could you check, and then close this issue?
