### ISSUE TITLE
mingw-w64-x86_64-gnupg needs libreadline6.dll

### ISSUE THREAD

**Issue by canfoderiskii** [Alexpux/MINGW-packages#1965]
- OS: win 10
- installed mingw-w64-x86_64-gnupg
- the folder 'msys64\mingw64\bin' added to PATH

open `cmd`, type `gpg`, system informs that 'libreadline6.dll is missing'.  I searched database and there is no package like `libreadline` for mingw64, but only for msys. So, how am i suppose to do to install libreadline for mingw64?

**Comment by peterbud** [comment]
Have you tried:
`pacman -S mingw-w64-x86_64-readline`

The pacman -Ql reveals that the dll should be there:

```
$ pacman -Ql mingw-w64-x86_64-readline
mingw-w64-x86_64-readline /mingw64/
mingw-w64-x86_64-readline /mingw64/bin/
mingw-w64-x86_64-readline /mingw64/bin/libhistory6.dll
mingw-w64-x86_64-readline /mingw64/bin/libreadline6.dll
....
```

Keep in mind that cmd prompt is not the same as MSYS2 bash prompt. So what is working under MSYS2 environment/subsystem, it might not work under a simple cmd prompt.

**Comment by canfoderiskii** [comment]
@peterbud Hi, I already installed `mingw-w64-x86_64-readline`, I tried pacman -Ql then, and found out that  I have `libreadline7.dll`, no file named libreadline6.dll.

**Comment by peterbud** [comment]
The latest package is indeed updated to readline 7. If you need a specific (older version) you can download it from the [repo](http://repo.msys2.org/mingw/x86_64/), and install it with 
`pacman -U mingw-w64-x86_64-readline-6.3.008-1-any.pkg.tar.xz`

What is interesting, that gnupg, does not seem to be dependent on readline, at least pactree is not showing it, so itmight be a problem with the PKGBUILD file.
`pactree -u  mingw-w64-x86_64-gnupg`

**Comment by canfoderiskii** [comment]
@peterbud I exec the command `pactree -u mingw-w64-x86_64-gnupg` on my machine too, and `mingw-w64-x86_64-readline` did exist inside the listed result.

**Comment by mati865** [comment]
Gnupg need rebuild.

**Comment by JPeterMugaas** [comment]
I did rebuild it and it was checked in.  The package should be rebuild and made available, IMAO.

**Comment by peterbud** [comment]
@canfoderiskii : can we close this issue?

**Comment by JPeterMugaas** [comment]
Probably, considering that gnupg was rebuilt.

**Comment by wutiejun** [comment]
I find the low version file and change the filename into the high version, and the awk works.
