### ISSUE TITLE
Please keep old package db files in the repo

### ISSUE THREAD

**Issue by eighttails** [Alexpux/MINGW-packages#1966]
Hi.
I develop a Qt application with mingw 32bit.

But due to issue #940 I cound't create release build until Jul.19(gcc6.1 comes).
And due to issue #1862 I can't run gdb since Oct.8(gdb7.12 comes).

In other words, from Jun.19 to Oct.8 is a "usable period" for me.
What I want to do is to rollback environment to as of June.

It seems old packages since last year is archived in Sourceforge repo, but resolving dependency and specifying packages to be downgraded is almost impossible without package db files in the past.
However, there is only one generation backup of package db files(mingw32.db) .
If I could retrieve old version of db files from repo, I supporse I could rollback enviromnent.

I understand that it is difficult to create db files in the past from now, but please consider it in case similar situations happen in the future.

**Comment by mingwandroid** [comment]
You do not have to update your env if it is working well for you. If it is mission critical you can test on a new installation (you can have as many as you want, space allowing, on the same computer) to make sure everything is OK.

Of course the best thing to do is to roll your sleeves up and fix problems if you have the time and motivation.

**Comment by eighttails** [comment]
OK I found previous snapshot of MSYS2 environment.
https://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-base-x86_64-20160921.tar.xz

I extracted /var/lib/pacman/sync from the snapshot and copied to my environment.
And "pacman -Suu" did the trick. I could downgrade whole packages.

**Comment by mati865** [comment]
Why not simply use `pacman -U <path/to/pkgname.pkg.tar.xz>`?

**Comment by eighttails** [comment]
> Why not simply use pacman -U <path/to/pkgname.pkg.tar.xz>?

Don't we have to resolve dependency, download and install all dependent package?
Doing it manually is really painful.
Or pacman keeps consistency by specifying single package?

**Comment by mati865** [comment]
Pacman "knows" only most update packages so you have to either rebuild package against updated dependencies or downgrade more packages.

**Comment by eighttails** [comment]
That's why I need previous db files.
Old db files know which package and version to downgrade and pacman downgrades all package automatically with them.

Anyway I have solved my problem and closing the issue. thanks.
