### ISSUE TITLE
DllMain missing in libgtkhex-3-0.dll of mingw-w64-x86_64-ghex?

### ISSUE THREAD

**Issue by canfoderiskii** [Alexpux/MINGW-packages#1967]
- OS: win 10
- installed `mingw-w64-x86_64-ghex`
- inside neither `cmd` nor `bash` the ghex can get running.
- If ghex is started inside `cmd`, system informs that it cannot find `DllMain` in the `libgtkhex-3-0.dll`.

**Comment by mati865** [comment]
It needs rebuild.

**Comment by juml** [comment]
ghex now works for after rebuild (https://github.com/Alexpux/MINGW-packages/commit/d313ba75a5a600fe6523c670f60a33a5d7442500).

Might have been closed

**Comment by canfoderiskii** [comment]
@juml yes, thanks, it works. I'll close this issue.
