### ISSUE TITLE
QTCreator 'mingw-w64-qtcreator' not responding after launch

### ISSUE THREAD

**Issue by askondro** [Alexpux/MINGW-packages#1974]
After launch QTCreator just freezes. It only show the projects overview and nothing can be clicked on.

Observed on: 

- Windows 10

- Windows 7

**Comment by askondro** [comment]
After compiling the package 'mingw-w64-qtcreator' by myself and installing it resolves the issue.
Reinstalling the package from the repo results with the issue as described in the title.

**Comment by mingwandroid** [comment]
This is an upstream bug. Clicking on any of "Welcome", "Edit", "Debug" or "Help" should work and allows the other controls and menus to be clicked on.

**Comment by jhasse** [comment]
I can't reproduce this on Windows 10 with Qt Creator 4.1.0.

**Comment by mingwandroid** [comment]
Did you try my suggestion?

**Comment by jhasse** [comment]
With "reproduce" I meant the original bug report: Qt Creator is working fine after launch, I don't need to do anything.

**Comment by mingwandroid** [comment]
Ah OK. I've seen this issue on macOS too and the same workaround works there so it's not something we should be too concerned about.
