### ISSUE TITLE
QtCreator clang code model does not work

### ISSUE THREAD

**Issue by nazar554** [Alexpux/MINGW-packages#1976]
`clangbackend.exe` can't find `libclang.dll`. Interesting though, that I have the import library under `/mingw64/lib/libclang.dll.a` and the static one. Somehow the clang package is missing its dll.

**Comment by nazar554** [comment]
Rebuilding Qt Creator helped.

**Comment by mati865** [comment]
There is issue with Clang. There were `libclang.dll` and `liblibclang.dll.a` generated.
Now there are `clang.dll` and `libclang.dll.a` which isn't good either.

**Comment by mingwandroid** [comment]
That can be ok so long as libclang.dll.a refers to clang.dll and not libclang.dll?

**Comment by mati865** [comment]
Ugly but working solution is renaming `clang.dll` to `libclang.dll`. Without https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-clang/0106-generate-libclang-instead-of-liblibclang.patch I've had many undefined references but it could get solved by another patches.

I couldn't find solution for it.

**Comment by revelator** [comment]
cmake add's lib prefix by default so yeah.
