### ISSUE TITLE
xargs behaves weirdly.

### ISSUE THREAD

**Issue by joeparkerz** [Alexpux/MINGW-packages#1985]
When you compile curl using MSVC and then do this command it launches a lot of xargs processes. It should launch 1-2 MAX.

seq 1 1000000000000 | xargs -n1 -P16 c:\\bin\\curl

**Comment by mingwandroid** [comment]
We have no interest in MSVC as it is closed source and we cannot do anything about it.

**Comment by joeparkerz** [comment]
Ugh this doesn't work with mingw-x64 either...
