### ISSUE TITLE
Cmake fails because of missing libxml

### ISSUE THREAD

**Issue by Rondom** [Alexpux/MINGW-packages#1991]
After the latest cmake update to 3.7.0 (b4b191b2c05403ae2e1ba8f2dd6eacdfb7879fdd, #1931) by @JPeterMugaas, cmake does not run. CMake (or one of its dependencies) seems to require libxml2.

Installing `mingw-w64-{x86_64,i686}-libxml2` fixes the issue.

**Comment by JPeterMugaas** [comment]
Alright, it seems that libarchive is now linking to libxml-2.  I have updated the build to reflect this.  https://github.com/Alexpux/MINGW-packages/pull/1992 .

**Comment by Alexpux** [comment]
See my comment on pull request

**Comment by JPeterMugaas** [comment]
I also think expat in the MSYS repository needs to be updated with the patch.  I have made a PR request:
https://github.com/Alexpux/MSYS2-packages/pull/764

**Comment by Rondom** [comment]
Thanks for the quick fix! How long does it take for this fix to reach the mirrors? Is that a manual process?

Btw MSYS Cmake is still at 3.6.0

**Comment by Rondom** [comment]
This has been fixed long time ago.
