### ISSUE TITLE
Package build solution

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#2006]
I have been thinking how we could solve the problem to have a **stable package building environment**, and I decided to open an issue to have a forum to discuss the different options and opinions.

My starting point was this really [old thread](https://sourceforge.net/p/msys2/wiki/Devtopics/): "Off-load package building and uploading"

Design considerations:
* It should be automated and should free up time for @Alexpux who is building the packages himself
* Should be free or low cost solution
* Should be a low maintenence solution
* Should solve the issue of long running builds (python, gcc etc)

After doing some research I have some rudimentary ideas, which I'd like to discuss more broadly.

What could work is the following:
1. Use a hosted Azure Windows Server which supports containers
2. Create a dockerfile which provides a basic Windows container with a full MSYS2 installed, including `base-devel`, `git`, `mingw-w64-x86_64-toolchain` and `mingw-w64-i686-toolchain`
3. Using a **daily** scheduled job in Azure (let say starting at midnight), run a daily job which checks the git master repository, pulls the folders which has been touched/merged in the previous day, and builds them.
4. Deply the artifacts to bintray, or directly to the repo.

Actually, I have a working MSYS2 `dockerfile`, and a working virtual machine under my Azure account and it seems to work nicely. Each time a build is initiated for a given PKGBUILD file a prisitine new container is being launched with exactly the same environment.

Once per a month we can rebuild the container using the `dockerfile `to keep the base container up-to-date with the latest binaries, shortening the build cycles.

I have not really polished the build script and the deplyment script to bintray so this is TBD.

I have also calculated the cost of running such solutions using the [Azure pricing calculator](https://azure.microsoft.com/en-us/pricing/calculator/). Assuming a simple A1 machine with an average usage of 3 hours/day, or 90 hours/month usage, it costs like 3 EUR/month. Depending on the bandwidth usage, some small additional fees (1EUR/ 20 GB) are added. Considering that I still have from my free initial balance like 120 EUR, that would cover the costs easily for more than a year.

So feel free to add your thought/ideas.

**Comment by nazar554** [comment]
Have you checked out [Tea CI](https://tea-ci.org)? It is based on drone & docker, does builds for pull requests with `wine` on Ubuntu. Don't know if it currently saves the resulting packages, but it works well.

**Comment by peterbud** [comment]
I have seen that, and it is currently working, but has own limitations: based on wine, not the latest gcc and MSYS environment. As far as I understood also cannot build long running packages.

**Comment by mati865** [comment]
None of currently used CI is able to build all packages.

**Comment by achadwick** [comment]
Neither Tea-CI nor Appveyor can build monsters like gtk3: they take too long, and the virtuals get killed off after an hour. At least, that's what seems to happen.
