### ISSUE TITLE
mingw-w64-cmake: execute_command () you need to specify the executable?

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#2008]
Environment:
simple shell script `test.sh`:
```
#!/bin/sh
echo "VERSION: 1.2"
```

Simple CMakeLitst.txt:
```
cmake_minimum_required(VERSION 3.2)
    execute_process(
      COMMAND  ${CMAKE_SOURCE_DIR}/test.sh 
      OUTPUT_VARIABLE PROJECT_VERSION
      RESULT_VARIABLE COMMAND_RESULT
      WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})

message("PROJECT_VERSION: ${PROJECT_VERSION}")
message("COMMAND_RESULT: ${COMMAND_RESULT}")
```

running `cmake --build .`  shows that the PROJECT_VERSION variable is empty
```
PROJECT_VERSION:
COMMAND_RESULT: %1 is not a valid Win32 application
```

If you change the CMakeLists.txt to include **bash**
```
cmake_minimum_required(VERSION 3.2)

    execute_process(
      COMMAND  bash ${CMAKE_SOURCE_DIR}/test.sh 
      OUTPUT_VARIABLE PROJECT_VERSION
      RESULT_VARIABLE COMMAND_RESULT
      WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})

message("PROJECT_VERSION: ${PROJECT_VERSION}")
message("COMMAND_RESULT: ${COMMAND_RESULT}")
```
then PROJECT_VERSION variable is populated.

```
PROJECT_VERSION: VERSION 1.2
COMMAND_RESULT: 0
```
Is this normal behaviour?

**Comment by oscarfv** [comment]
mingw-w64-cmake is a native Windows application, it knows nothing about *nix shell scripts, shebang, etc. What you see is expected.

Also, please note that the `execute_process` documentation says `No intermediate shell is used`.

**Comment by peterbud** [comment]
Thanks @oscarfv 

The interesting thing is that the `COMMAND  ${CMAKE_SOURCE_DIR}/test.sh ` style works on *nix, and I'm now wondering what is the best solution for a cmake script which works on both platform.
