### ISSUE TITLE
Error in gdk-pixbuf2-xxx .install scripts

### ISSUE THREAD

**Issue by sparksh** [Alexpux/MINGW-packages#2009]
In the current version of package gdk-pixbuf2, the .install files
for both i686 and x86_64 have a remove script that uses the wrong path
for the loaders.cache file. They contain:

    pre_remove() {
          rm -f mingwXX/lib/gdk-pixbuf-2.0/2.10.0/loaders/loaders.cache
    }

But the path to the default location for loaders.cache is one level up, so
the scripts should read:

    pre_remove() {
          rm -f mingwXX/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
    }

**Comment by peterbud** [comment]
Thx!
