### ISSUE TITLE
libboost-python3-mt.dll links to python2.7

### ISSUE THREAD

**Issue by sbabbi** [Alexpux/MINGW-packages#2028]
> $ pacman -Q | grep boost
> mingw-w64-x86_64-boost 1.62.0-1

> $ ldd /mingw64/bin/libboost_python3-mt.dll
>         ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ff8f6d70000)
>         KERNEL32.DLL => /c/Windows/system32/KERNEL32.DLL (0x7ff8f49c0000)
>         KERNELBASE.dll => /c/Windows/system32/KERNELBASE.dll (0x7ff8f4250000)
>         msvcrt.dll => /c/Windows/system32/msvcrt.dll (0x7ff8f6cd0000)
>         libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x61440000)
>         libstdc++-6.dll => /mingw64/bin/libstdc++-6.dll (0x6fc40000)
>         USER32.dll => /c/Windows/system32/USER32.dll (0x7ff8f6b80000)
>         GDI32.dll => /c/Windows/system32/GDI32.dll (0x7ff8f4b40000)
>         libpython2.7.dll => /mingw64/bin/libpython2.7.dll (0x6d600000)
>         ADVAPI32.dll => /c/Windows/system32/ADVAPI32.dll (0x7ff8f4cd0000)
>         sechost.dll => /c/Windows/system32/sechost.dll (0x7ff8f5230000)
>         RPCRT4.dll => /c/Windows/system32/RPCRT4.dll (0x7ff8f6a50000)
>         WS2_32.dll => /c/Windows/system32/WS2_32.dll (0x7ff8f4f40000)
>         NSI.dll => /c/Windows/system32/NSI.dll (0x7ff8f4430000)
>         libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x64940000)

This causes all sort of issues on a simple test application. Apparently renaming `libpython3.5m.dll -> libpython2.7.dll` can be used as a workaround.

**Comment by mkeeter** [comment]
I ran into the same problem when trying to use Boost::Python with Python 3: everything seemed to be going fine, but my application failed to link because function signatures have changed (details [here](http://stackoverflow.com/questions/5810101/undefined-boost-python-symbol-boostpythondetailinit-module)).

The renaming workaround won't help for me, because I actually *want* Python 3 (crazy, I know) – any ideas besides building Boost myself?

**Comment by jwakely** [comment]
Probably due to https://github.com/boostorg/build/issues/163

**Comment by jhasse** [comment]
@jwakely In the issue you said that you manually restore the previous behaviour by commenting out https://github.com/boostorg/build/commit/78ffbe094400d277627b2c19ceb182d637b8baca. Can the same be done for MSYS2?

**Comment by jwakely** [comment]
I have no idea, I know nothing about MSYS2 and I don't understand Boost.Build's black magic.

**Comment by laevilgenius** [comment]
I've worked it around by building boost twice: first with python 2 only and then with python 3 only. Not ideal, but it works.

**Comment by mati865** [comment]
Arch also builds boost twice so it might be preferred solution.

**Comment by ste-ve** [comment]
@laevilgenius Would you mind sharing steps on how you built boost with python 3? I haven't had success with the `--with-python` or `--with-python-version` flags.

**Comment by laevilgenius** [comment]
Try this hacky [PKGBUILD](https://github.com/Alexpux/MINGW-packages/files/1186956/PKGBUILD.txt) to build both python 2 and 3. If you need only one python version, its pretty straightforward to modify (you can use original PKGBUILD as well): just put in your _user-config.jam_ an appropriate python version string (for example: `using python : 3.6 : C:/msys64/mingw64/bin/python3.exe : C:/msys64/mingw64/include/python3.6m : C:/msys64/mingw64/lib/python3.6/config-3.6m ;`).

**Comment by ste-ve** [comment]
@laevilgenius Works great, thank you!
