### ISSUE TITLE
diff can't load libintl-8.dll

### ISSUE THREAD

**Issue by hmijail** [Alexpux/MINGW-packages#2048]
I just installed mingw-w64-x86_64-diffutils with pacman, but `diff` fails like this:
```
C:/msys64/mingw64/bin/diff.exe: error while loading shared libraries: libintl-8.dll: cannot open shared object file: No such file or directory
```
Indeed, I don't see any such dll installed by MSYS2. 

Is this a packaging bug or am I doing something wrong?

FWIW, pacman reports that there is a msys/libintl library that is already installed, but if I understand correctly this doesn't help for a mingw64 package.
The diff.exe in the msys/diffutils package does run.

**Comment by mati865** [comment]
Seems it depends on `mingw-w64-x86_64-gettext`.

**Comment by hmijail** [comment]
Installing `mingw-w64-x86_64-gettext` does fix the problem. Thank you!

**Comment by juml** [comment]
Might be there an problem with latest gettext update ?
gtk3-demo doesn't start anymore, complaining on "point_lock_file could not be located in the dynamic link library libintl-8.dll"

**Comment by achadwick** [comment]
@juml 
That's a separate issue. I've reported it at Alexpux/MINGW-packages#2099, please can you comment there?

**Comment by karen-arutyunov** [comment]
Despite the gettext package dependency was added with 47c0acd commit nine months ago, the issue still present:

```
$ diff --version
C:/msys32/mingw32/bin/diff.exe: error while loading shared libraries: libintl-8.dll: cannot open shared object file: No such file or directory
```

Should be due to the fact that the gettext dependency still missing in the package database:

```
$ pacman -Qi mingw-w64-i686-diffutils
Name            : mingw-w64-i686-diffutils
Version         : 3.3-2
Description     : GNU Diffutils is a package of several programs related to finding differences between
                  files (mingw-w64)
Architecture    : any
URL             : http://www.gnu.org/software/diffutils/
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : mingw-w64-i686-libwinpthread
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 671.00 KiB
Packager        : Alexey Pavlov <alexpux@gmail.com>
Build Date      : Thu, Oct 22, 2015 11:51:35 AM
Install Date    : Wed, Oct 25, 2017 1:44:32 PM
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

Could somebody of repo collaborators to reopen the issue?

**Comment by achadwick** [comment]
@Alexpux 
Please can you rebuild `mingw-w64-i686-diffutils`? Latest `pkgrel` in the repositories is 2, which is 9 months out of data.

**Comment by karen-arutyunov** [comment]
@Alexpux

Probably also need to do the same for mingw-w64-x86_64-diffutils, as there is no dependency from gettext as well:

```
$ pacman -Qi mingw-w64-x86_64-diffutils
Name            : mingw-w64-x86_64-diffutils
Version         : 3.3-2
Description     : GNU Diffutils is a package of several programs related to finding differences between files (mingw-w64)
Architecture    : any
URL             : http://www.gnu.org/software/diffutils/
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : mingw-w64-x86_64-libwinpthread
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 650.00 KiB
Packager        : Alexey Pavlov <alexpux@gmail.com>
Build Date      : Thu, Oct 22, 2015 11:36:05 AM
Install Date    : Wed, Oct 25, 2017 1:34:24 PM
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```
