### ISSUE TITLE
ImageMagick pkgconfig

### ISSUE THREAD

**Issue by Phil1216** [Alexpux/MINGW-packages#2054]
I noticed something strange with the ImageMagick pgkconfig files.

prefix=/mingw64
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/ImageMagick-7
includearchdir=/mingw64/include/ImageMagick-7
libname=MagickCore-7.Q16HDRI
moduledir=${exec_prefix}/lib/ImageMagick-7.0.3/modules-Q16HDRI
 
Name: MagickCore
Description: MagickCore - C API for ImageMagick (ABI Q16HDRI)
URL: https://www.imagemagick.org
Version: 7.0.3
Cflags: -I${includearchdir} -I${includedir} -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -D_DLL -D_MT
Libs: -L${libdir} -l${libname}
Libs.private: -L${libdir} -l${libname}  -LC:/building/msys64/mingw64/lib -llcms2 -LC:/building/msys64/mingw64/lib -lfreetype -LC:/building/msys64/mingw64/lib -lraqm -lfreetype -LC:/building/msys64/mingw64/lib -llqr-1 -lglib-2.0 -lintl -LC:/building/msys64/mingw64/lib -lfftw3  -LC:/building/msys64/mingw64/lib -lfontconfig -lfreetype     -LC:/building/msys64/mingw64/lib -llzma -lbz2 -LC:/building/msys64/mingw64/lib -lz -lltdl -lgdi32 -lm -lgomp     -lm

What is the C:/building directory? I have msys64 installed at C:/msys64. As far as I know, C:/building/msys64 doesn't exist.

**Comment by JPeterMugaas** [comment]
Alright, what happened was that some pathes were hard-coded by the build process.  I have made a workaround in a pull request: https://github.com/Alexpux/MINGW-packages/pull/2058 .
