### ISSUE TITLE
calling windres freezes msys2 console

### ISSUE THREAD

**Issue by askondro** [Alexpux/MINGW-packages#2062]
All I can do is force-kill the console...

**Comment by peterbud** [comment]
I can confirm, even with the latest binutils build (mingw-w64-x86_64-binutils 2.27-3)

**Comment by mati865** [comment]
Seems to hang only when no arguments are given.
Also killing `cc1.exe` unblocks terminal.

**Comment by peterbud** [comment]
That's a good news, though it should work also without arguments :)

**Comment by mati865** [comment]
Indeed but it greatly lowers this bug priority unless someone provides example that freezes windres.
