### ISSUE TITLE
Binutils Cannot Be Built Using the MSYS Environment

### ISSUE THREAD

**Issue by cr1901** [Alexpux/MINGW-packages#2068]
I needed to build a binutils with profiling information to diagnose a potential performance bug. I don't actually know if this is a bug or not, but attempting to build binutils with the MSYS shell eventually bombs with the error described in this gist: https://gist.github.com/cr1901/584c426453a00f943460be2d9b3ccffb

Using the MINGW64 environment works fine. However, I'm under the impression that all software is _meant_ to be built in the MSYS shell, and `./configure` will find the correct compiler (it doesn't in the case of binutils). Is my understanding correct, or am I missing something?

**Comment by mati865** [comment]
> However, I'm under the impression that all software is meant to be built in the MSYS shell, and ./configure will find the correct compiler

There is no magic used.
In MINGW64 shell compiler from /mingw64/bin is used, in MSYS2 shell compiler from /usr/bin is used.

You want to use MSYS2 shell if building packages with makepkg or makepkg-mingw or building software with emulated POSIX (like Cygwin).

**Comment by cr1901** [comment]
>You want to use MSYS2 shell if building packages with makepkg or makepkg-mingw or building software with emulated POSIX (like Cygwin).

Well, binutils does not compile under the MSYS2 shell/environment. One reason is the compiler in `/usr/bin` is missing some defines, and even using makepkg-mingw, binutils decides to use the compiler under `/usr/bin` instead of `/mingw64`.

Opening a MINGW64 environment alleviates the problem, but I thought software using makepkg must be build under MSYS2?

**Comment by mati865** [comment]
`makepkg-mingw` will pick compiler from `/mingw64/bin` if it is installed.

**Comment by emmenlau** [comment]
Do you still experience this problem? I can build current binutils with `makepkg-mingw` from an MSYS2 shell. As @mati865 said, it seems to correctly use the compiler from `/mingw64/bin`.
