### ISSUE TITLE
mingw-w64-clang fix support of SjLj/SEH EH for Objective-C

### ISSUE THREAD

**Issue by GunGraveKoga** [Alexpux/MINGW-packages#2078]
[objc-eh-personality.patch.txt](https://github.com/Alexpux/MINGW-packages/files/703864/objc-eh-personality.patch.txt)
Current release version of clang (3.9.0) does not support SjLj and SEH exception handling for Objective-C.

Attached patch enable it.

Original commit https://github.com/llvm-mirror/clang/commit/3a07c87d4dc20c8d6b02a1d6cf38a5d1eb245a7f

This fix is useful for building ObjFW on mingw-w64

**Comment by mingwandroid** [comment]
Please make this into a pull request.

**Comment by GunGraveKoga** [comment]
>Please make this into a pull request.
Done
