### ISSUE TITLE
No more updates?

### ISSUE THREAD

**Issue by tschoonj** [Alexpux/MINGW-packages#2079]
Hi,

Is there a reason why I am no longer getting any updates? It seems that there haven't been uploads to sourceforge for several weeks now, though package updates keep getting merged in here...

**Comment by Alexpux** [comment]
Because I have no time to build packages very often. All packages in repository are building and uploading by me manually.

**Comment by tschoonj** [comment]
I did not know that: I assumed you used artefacts produced by AppVeyor which would then be automatically pushed to sourceforge...

Thanks for the good work though: I really like MSYS2!
