### ISSUE TITLE
mingw-w64-x86_64-csfml-2.3-2 not compatible with mingw-w64-x86_64-sfml-2.4.1-1

### ISSUE THREAD

**Issue by RyanGlScott** [Alexpux/MINGW-packages#2084]
Using the most recent versions of `csfml` and `sfml` together leads to issues. First, I'll install them afresh:

```
$ pacman -S mingw-w64-x86_64-csfml mingw-w64-x86_64-sfml
resolving dependencies...
looking for conflicting packages...

Packages (2) mingw-w64-x86_64-csfml-2.3-2  mingw-w64-x86_64-sfml-2.4.1-1

Total Installed Size:  15.38 MiB

:: Proceed with installation? [Y/n] y
(2/2) checking keys in keyring                             [###############################] 100%
(2/2) checking package integrity                           [###############################] 100%
(2/2) loading package files                                [###############################] 100%
(2/2) checking for file conflicts                          [###############################] 100%
(2/2) checking available disk space                        [###############################] 100%
:: Processing package changes...
(1/2) installing mingw-w64-x86_64-sfml                     [###############################] 100%
(2/2) installing mingw-w64-x86_64-csfml                    [###############################] 100%
```

Now I'll compile a simple program that uses CSFML:

```c
$ more wat.c
#include <SFML/Graphics.h>

#include <stdio.h>

int main()
{
    printf("Foo\n");

    sfCircleShape* circle1 = sfCircleShape_create();
    sfCircleShape* circle2 = sfCircleShape_copy(circle1);
    return 0;
}
```

```
$ gcc wat.c -o wat -lcsfml-graphics
```

So far, so good. But if I actually try to run this program, it mysteriously fails:

```
$ ./wat.exe
$ echo $?
127
```

And `strace` tells me this:

> The procedure entry point `_ZNK2sf4Font8getGlyphEjjb` could not be located in the dynamic link library `C:\msys64\mingw64\bin\csfml-graphics-2.dll`.

At this point, I decided to check what symbols `sfml-graphics-2.dll` was exporting, as `sfFont_getGlyph` should be exported from it. But that wasn't the case!

```
$ /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio\ 14.0/VC/bin/amd64/dumpbin.exe -EXPORTS /mingw64/bin/sfml-graphics-2.dll | grep getGlyph
        358  165 000042A0 _ZNK2sf4Font8getGlyphEjjbf
```

It's not the same symbol! That is, there's an `f` suffix, so there must be an additional `float` argument added to `sfFont_getGlyph`. And sure enough, [such a change was introduced](https://github.com/SFML/SFML/commit/957cabb816f69a3d7a3909d24b9e773ffc9a65b5#diff-3c241b2b2608c22871b4a77a8f04373bL292) in SFML 2.4.0. This must mean that CSFML 2.3 (which `pacman` installed) still expects the version of `sfFont_getGlyph` without the `float` argument.

In order to work around this issue, I had to manually downgrade to `mingw-w64-x86_64-sfml-2.3.2-2`. Is there a way to tell `pacman` not to install `mingw-w64-x86_64-sfml-2.4.1-1` with `mingw-w64-x86_64-csfml-2.3-2`?

**Comment by mati865** [comment]
To ignore specific package: https://wiki.archlinux.org/index.php/pacman#Skip_package_from_being_upgraded
Either add package to `IgnorePkg` in `pacman.conf` or use pacman with `--ignore` argument.

But it's not proper solution to this problem.
I think rebuilding csfml with smfl 2.4 should fix it symbols.

**Comment by Alexpux** [comment]
Rebuilded packages uploaded.
