### ISSUE TITLE
Latest gtk2 binary update broke Windows XP support

### ISSUE THREAD

**Issue by Forkest** [Alexpux/MINGW-packages#2086]
entry point wcscpy_s could not be located in msvcrt.dll

Dependency Walker says it comes from libgdk-win32-2.0-0.dll

This appears only with the latest mingw-w64-i686-gtk2-2.24.31-1, whereas mingw-w64-i686-gtk2-2.24.28-3 doesn't have the issue. Something has changed in the build process? Could it be changed back for the next GTK release please?

**Comment by mati865** [comment]
Upstream broke XP support with https://github.com/GNOME/gtk/commit/0b06d401034bcbee3e1e50085769361d96a81aaf

This patch has been applied with https://github.com/Alexpux/MINGW-packages/pull/1979

**Comment by Forkest** [comment]
A patch [is presented](https://bugzilla.gnome.org/show_bug.cgi?id=768722#c33) in the original bug, could you please recompile with it?

I was trying to build the gtk2 package myself with the latest available for XP MSYS2 version, but without success.

**Comment by Alexpux** [comment]
It is ok that patch is present in original bug report. Get it there and create pull request here.

**Comment by Ede123** [comment]
@Forkest: I guess the patch from #2087 is also applicable for gtk3?
Would you mind having a look at that, too?

**Comment by Forkest** [comment]
@Ede123, I'd like to see GTK3 on XP too, but the support for it has been dropped after 3.16, so this bug is far from the only thing that prevents it from working.

**Comment by Ede123** [comment]
I see. I was just scraping the issues for XP-related issues due to #2155 but I'm starting to get the impression it might just not be possible...

**Comment by Forkest** [comment]
@Ede123, you can download the package for the supported GTK 3.16 from here: http://repo.msys2.org/mingw/i686/mingw-w64-i686-gtk3-3.16.6-1-any.pkg.tar.xz and install it with `pacman -U`. Hope this helps.

**Comment by Alexpux** [comment]
@Forkest, it will not work. I case of downgrading package you also must downgrade dependencies too.

**Comment by Alexpux** [comment]
In @Ede123 case better to build its own gtk3-3.16 with current dependencies

**Comment by Forkest** [comment]
@Ede123: are you sure you need gtk3 at all? I see that the latest version of Inkscape in Debian and the latest available Windows version are built against gtk2.

**Comment by Ede123** [comment]
Yes, Inkscape 0.92 will be the last version to use gtk2. In current trunk (i.e. future Inkscape 0.93) gtk2 support was dropped and gtk3 will be mandatory.

> In @Ede123 case better to build its own gtk3-3.16 with current dependencies
I'll ocnsider that but the main reason I'm looking into switching to MSYS2 is to remove the need of maintaining our own custom-built libraries. (Currently we use a complete set of libraries built with vanilla mingw-w64).
I guess this will at some point become a community decision over dropping XP...
