### ISSUE TITLE
mingw-w64-gettext 0.19.8.1-1 build breaks GTK3

### ISSUE THREAD

**Issue by achadwick** [Alexpux/MINGW-packages#2099]
The latest build of gettext breaks gtk 3.22.6 badly. Still investigating why.

* When `mingw-w64-{i686,x86_64}-gettext-0.19.8.1-1-any.pkg.tar.xz` is installed, gtk3-demo.exe and other demo apps all exit immediately when launched from MINGW64 or MINGW32 shells. No UI is shown.
* Problem is solved for me by downgrading to 0.19.7-1 from my local pacman cache, without changing  anything else (gtk3 version kept the same).
* Python GI code fails with the exception and traceback shown below in affected versions.
* Attempts to load *any* GTK code (either GI Python stuff or gtk3-demo.exe) from Windows itself (CreateProcessW()) fails with an error dialog implicating libintl-8.dll.

#### Error implicating libintl-8

Both Styrene wrappers for MyPaint installed to `C:\Program Files` (with a stripped down and canned MSYS2 install), and `gtk3-demo.exe` (double-clicked from Windows in `C:\msys64\mingw64\bin`) fail in the same way when their GTK links to an affected libintl:

![image](https://cloud.githubusercontent.com/assets/61299/22045815/835b1bfe-dd14-11e6-9082-70f4bcc55db9.png) ![image](https://cloud.githubusercontent.com/assets/61299/22045983/ab6d5480-dd15-11e6-8d20-967140adb8a0.png)

MyPaint is an interesting case, as it tries to load `libintl[something].dll` itself with `ctypes` before pulling in GTK so that its UI can be translated (don't ask...!)

It successfully does so:

```
INFO: lib.i18n: Windows: LANG='en_US.UTF-8'
INFO: lib.i18n: Windows: LANGUAGE='en_GB:en_US'
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
INFO: mypaint: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (ctypes)
```

... and then exits with the exception shown below when it does an import from `gi`.

### Python backtraces

An inability to pull in the `Gtk` namespace over GI is indicative of this bug.

#### gettext 0.19.7-1 (unaffected)

Namespaces should just load, perhaps with a gripe about having to declare versions which we don't care about:

```python
$ python2 -i
Python 2.7.13 (default, Jan 17 2017, 13:56:44)  [GCC 6.3.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import GLib
>>> from gi.repository import GdkPixbuf
__main__:1: PyGIWarning: GdkPixbuf was imported without specifying a version first. Use gi.require_version('GdkPixbuf', '2.0') before import to ensure that the right version gets loaded.
>>> from gi.repository import Gdk
__main__:1: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
>>> from gi.repository import Gtk
__main__:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>>> exit()
```

#### gettext 0.19.8.1-1 (affected)

Affected versions bomb out like this at the point of importing Gtk in the presence of an affected gettext package. Other GI namespaces import cleanly.

```python
$ python2 -i
Python 2.7.13 (default, Jan 17 2017, 13:56:44)  [GCC 6.3.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import GLib
>>> from gi.repository import GdkPixbuf
__main__:1: PyGIWarning: GdkPixbuf was imported without specifying a version first. Use gi.require_version('GdkPixbuf', '2.0') before import to ensure that the right version gets loaded.
>>> from gi.repository import Gdk
__main__:1: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
>>> from gi.repository import Gtk

** (python2.exe:3480): WARNING **: Failed to load shared library 'libgtk-3-0.dll' referenced by the typelib: 'libgtk-3-0.dll': The specified procedure could not be found.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python2.7/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "C:/msys64/mingw64/lib/python2.7/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "C:/msys64/mingw64/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "C:/msys64/mingw64/lib/python2.7/site-packages/gi/overrides/Gtk.py", line 118, in <module>
    class Widget(Gtk.Widget):
  File "C:/msys64/mingw64/lib/python2.7/site-packages/gi/module.py", line 183, in __getattr__
    interfaces = tuple(interface for interface in get_interfaces_for_object(info)
  File "C:/msys64/mingw64/lib/python2.7/site-packages/gi/module.py", line 107, in get_interfaces_for_object
    interfaces.append(getattr(module, name))
  File "C:/msys64/mingw64/lib/python2.7/site-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "C:/msys64/mingw64/lib/python2.7/site-packages/gi/module.py", line 222, in __getattr__
    wrapper = metaclass(name, bases, dict_)
  File "C:/msys64/mingw64/lib/python2.7/site-packages/gi/types.py", line 234, in __init__
    register_interface_info(cls.__info__.get_g_type())
TypeError: must be an interface
>>> exit()
```

**Comment by achadwick** [comment]
`mingw-w64-*-gtk3-3.22.4-1-any.pkg.tar.xz` from my cahe is affected too.

**Comment by Alexpux** [comment]
Well I'm try to find what dll is linked with missing symbols. This is not gtk3 irtself seems

**Comment by Alexpux** [comment]
Rebuilding GTK3 fix problem. Will upload new packages today.

**Comment by achadwick** [comment]
I can confirm that a rebuild with 3.22.7 fixes this for MINGW64.
