### ISSUE TITLE
llvm-config-3.9.1-2 doesn't report shared libs correctly

### ISSUE THREAD

**Issue by RyanGlScott** [Alexpux/MINGW-packages#2107]
I have `mingw-w64-x86_64-llvm-3.9.1-2` installed. If I run `llvm-config --libs --link-shared`:

```
llvm-config: error: LLVM-3.9.dll is missing
```

I noticed that the files that live `/mingw64/bin` in `/mingw64/lib` are named `LLVM.dll` and `libLLVM.dll.a`, respectively. Should these be given `-3.9` suffixes, perhaps?

**Comment by mati865** [comment]
Look similar to https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-clang/0106-generate-libclang-instead-of-liblibclang.patch
But somehow dynamically linked LLVM modules are working

On the Linux:
libLLVM-3.9.1.so symlink to libLLVM-3.9.so
libLLVM-3.9.so    the lib
libLLVM.so         another symlink
libLTO.so            LTO lib

MSYS2 have `LLVM.dll` and `LTO.dll`.

So yes, libs have to be fixed.

**Comment by Alexpux** [comment]
Lobs don't need to be prefixed on Windows. Need to fix llvm-config

**Comment by mati865** [comment]
@Alexpux,
But suffix `-3.9` shouldn't be there?

**Comment by Alexpux** [comment]
I don't think so. No one previous release has it

**Comment by mati865** [comment]
So we have AddLLVM.cmake adding version string to lib name on UNIX: https://github.com/llvm-mirror/llvm/blob/e3aa75949b5b83f1ce060ad84abeb1e1968b60eb/cmake/modules/AddLLVM.cmake#L489

And this C++ code looking for versioned lib https://github.com/llvm-mirror/llvm/blob/93e6e5414ded14bcbb233baaaa5567132fee9a0c/tools/llvm-config/llvm-config.cpp#L385

**Comment by mati865** [comment]
One must be fixed

**Comment by Alexpux** [comment]
Need fix cpp file. Do not versioning library for Windows

**Comment by mati865** [comment]
Ok it will be simple.

**Comment by TravisWhitaker** [comment]
I just ran into this myself using `llvm-config` built from source on Windows. Is the relevant MinGW patch just a workaround? Surely this is a bug in `llvm-config`, and it doesn't seem to be fixed upstream as of version 5.0.

**Comment by mati865** [comment]
@TravisWhitaker it is a workaround that most likely doesn't meet LLVM quality requirements and I was out of time to upstream it anyway.

I checked official LLVM binaries for Windows and LTO.dll is 37 MiB big so build system probably needs some more patches.

**Comment by TravisWhitaker** [comment]
Ah, I see.

The only reason I'm building LLVM from source is because I need NVPTX support, would you guys consider including that in the MinGW package? If so I can take a crack at a patch.

**Comment by mati865** [comment]
If @Alexpux will have no problem with small increase of LLVM build time and you are willing to build (just once for tests) and test it.
