### ISSUE TITLE
mingw-w64-opencl-headers: missing cl_d3d10.h and cl_d3d11.h

### ISSUE THREAD

**Issue by dthpham** [Alexpux/MINGW-packages#2116]
They are deleted in the PKGBUILD:
```
# remove useless headers
rm "${pkgdir}${MINGW_PREFIX}"/include/CL/{cl_d3d,cl_dx9}*.h
```
Khronos OpenCL-ICD-Loader depends on these headers, I actually need them myself, and another developer may need them down the line. I can't see a valid justification for not including these headers in the package and would appreciate it if they were added back in.

**Comment by JPeterMugaas** [comment]
There probably is no valid justification unless it's from Linux.  Unfortunately, I had based much of the work off of package scripts from Archlinux and I did not see it.  For those that don't know.  d3d and dx9 are part of the DirectX headers in Windows and are.  Thanks for that fix.  I hope we get it in soon.

**Comment by dthpham** [comment]
Thanks for clarifying. It makes more sense knowing it was based off an Arch PKGBUILD.  Anyways, closing this because the fix has been merged.
