### ISSUE TITLE
multiple definition when static linking with libcrypto and libxml2

### ISSUE THREAD

**Issue by bartland** [Alexpux/MINGW-packages#2125]
Using msys64.

MINGW-packages/mingw-w64-libxml2/0026-mingw-relocate.patch introduced pathtool.c. This file is used in a number of packages including MINGW-packages/mingw-w64-openssl.

When I statically link both I get:

> E:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.3.0/../../../../lib\libxml2.a(pathtools.o):(.text+0x100): multiple definition of `malloc_copy_string'
E:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.3.0/../../../../lib\libcrypto.a(pathtools.o):(.text+0x100): first defined here

... and other functions: sanitise_path, etc

If I remove 0026-mingw-relocate.patch from PKGBUILD and rebuild, everything works.

**Comment by peterbud** [comment]
Are you compiling the 32-bit or 64-bit version? Int he comment you are referring to the mingw-w64 (64-bit) version, but the error message seems to refere to mingw32 (32-bit) subsystem.

**Comment by bartland** [comment]
Hi @peterbud . Could you clarify? I may be misunderstanding.

I'm using 64 bit msys2 and building a 32 bit version of my code with MINGW32. 

As I understand it, the PKGBUILD modules mingw-w64-xxx (openssl, etc) build both the 32 bit and 64 bit versions of the repository package, depending on whether the 32 bit and/or 64 bit toolchain is installed.

Since pathtools has been added to a number of the packages, combining those packages results in the above conflict.

Now in this case, given that it's due to the same source (pathtools), I could use --allow-multiple-definition to force the first definition to be used. However that seems to be dangerous. It seems to me that pathtools should be its own lib?

**Comment by peterbud** [comment]
If you want to **build** packages you need to use the msys2 subsystem.

I'd suggest to read this wiki page as well: [Using MSYS2](https://github.com/Alexpux/MINGW-packages/wiki/Using-MSYS2)

As I see both the 32-bit and 64-bit compile was successful with the in the 0026-mingw-relocate.patch according to [CI log](https://ci.appveyor.com/project/Alexpux/mingw-packages/build/1.0.1828).
