### ISSUE TITLE
pcre pkgbuild

### ISSUE THREAD

**Issue by ScreamingInDigital** [Alexpux/MINGW-packages#2134]
The pkgbuild file for pcre should have the following options added to the configure script.

--enable-newline-is-any
This is because Unicode is enabled in the build, and the platform is Windows(CRLF for EOL is standard).  Also, some of the tests will fail, other than the test involving French locale.

--disable-stack-for-recursion
This is documented as primarily an issue on Windows, because of the standard stack size.  The recommended stack size is 8MB.  This can also be done by setting the link option "-Wl,--stack,8388608", however, when running the provided tests, the success was not consistent based on different versions of gcc.  I cannot explain this.  Although disabling recursion does come with a decrease in performance, it was consistently stable and passed all but the French locale tests.

**Comment by peterbud** [comment]
@ScreamingInDigital : even with those flags the 2 out of 5 tests are failing:
```
PASS: pcrecpp_unittest.exe
PASS: pcre_scanner_unittest.exe
PASS: pcre_stringpiece_unittest.exe
FAIL: RunTest
FAIL: RunGrepTest
```
So this looks like more complex problem.
