### ISSUE TITLE
bash: getent : command not found

### ISSUE THREAD

**Issue by filnet** [Alexpux/MINGW-packages#2137]
I fully updated msys2 recently and I am now seeing this message when starting any msys2 shell (msys or mingw32).
The message "command not found" is roughly translated from the Frenc.h "commande introuvable"...

**Comment by Alexpux** [comment]
First, you post issue to wrong place. This need to be in MSYS2-packages.
Second, this is know issue. See issues list in MSYS2-packages.

**Comment by filnet** [comment]
Ok. Sorry...
