### ISSUE TITLE
Error while loading zlib1.dll.

### ISSUE THREAD

**Issue by 0x414c** [Alexpux/MINGW-packages#2138]
After latest upgrade (31 Jan 17) I found that `CMake` can't start:
`# cmake`
`C:/msys64-2/mingw64/bin/cmake.exe: error while loading shared libraries: zlib1.dll: cannot open shared object file: No such file or directory`
I did a fresh installation of `MSYS2` to separate directory (see [pacman.log](https://gist.github.com/0x414c/13769ede4e54799c1fde333a813870d9)), upgraded it and installed `CMake`, error was still the same.

`curl` can't start too:
`# curl`
`C:/msys64-2/mingw64/bin/curl.exe: error while loading shared libraries: zlib1.dll: cannot open shared object file: No such file or directory`

**Comment by mati865** [comment]
`zlib` seems to depend on `mingw-w64-x86_64-libunistring` or `mingw-w64-i686-libunistring` depending on architecture.

**Comment by 0x414c** [comment]
Installing `mingw-w64-x86_64-libunistring` fixed the issue.

**Comment by elieux** [comment]
Fixed in 07f64002. Will be available after Alexey rebuilds the package
