### ISSUE TITLE
mingw-w64-x86_64-rust 1.14.0-2  cargo does not work

### ISSUE THREAD

**Issue by kasehiroyuki** [Alexpux/MINGW-packages#2143]
With mingw-w64-x86_64-rust package version 1.14.0-2 , cargo command does not work with error.

```
$ cargo
C:/msys64/mingw64/bin/cargo.exe: error while loading shared libraries: zlib1.dll: cannot open shared object file: No such file or directory
```

But /mingw64/bin/zlib1.dll is already installed.
```
$ pacman -Qo /mingw64/bin/zlib1.dll
/mingw64/bin/zlib1.dll is owned by mingw-w64-x86_64-zlib 1.2.11-1
```

OS is Windows 10 Home 64bit.

**Comment by Alexpux** [comment]
try under CMD. It will show you real missing library

**Comment by kasehiroyuki** [comment]
Thank you for quick reply.
In cmd.exe, error dialog said that libssh2-1.dll is required.

Then I installed  mingw-w64-x86_64-libssh2 and zlib1.dll error was not shown.

**Comment by ScreamingInDigital** [comment]
There is a bug with "ldd" on Windows 10.  It does not show missing dependencies.

Install "ntldd" and execute 'ntldd <library or executable name> | grep "not found" ' to see the list of missing dependencies.

**Comment by Alexpux** [comment]
@ScreamingInDigital , no one tell here about ldd

**Comment by ScreamingInDigital** [comment]
@Alexpux ,
Assume that "libssh2" was missing and "rust" was installed, the following could be executed to determine the missing library or libraries with "ntldd" from the msys2/mingw64 prompt.
ntldd cargo.exe | grep "not found"

**Comment by Alexpux** [comment]
I know about ntldd, it is not bug free too. I prefer to use Dependency Walker in such cases. It also show if some imports are missing in libraries

**Comment by ScreamingInDigital** [comment]
@Alexpux 
I also use dependency walker.  "ntldd" is currently not as "buggy" as "ldd", and he could have executed that immediately after trying to use "cargo".
In the case of the "cargo" command, it would have worked fine.

**Comment by hcorion** [comment]
@kasehiroyuki Does the issue still persist with the latest version of rust?

**Comment by kasehiroyuki** [comment]
@hcorion This issue is missing dependency to  mingw-w64-x86_64-libssh2 
and I checked 1.15.1-1 and seems to have the same problem.
