### ISSUE TITLE
mingw-w64-qt5

### ISSUE THREAD

**Issue by irakhlin** [Alexpux/MINGW-packages#2144]
Hello,

I am unable to currently build the mingw-w64-qt5 package. I have tried my existing build env along with starting a clean msys2 instance. I receive the same error in both cases:

se/qwindowskeymapper.o ../windows/qwindowskeymapper.cpp
In file included from ../windows/qwindowsintegration.h:46:0,
                 from ../windows/qwindowsintegration.cpp:41:
../../../../include/QtFontDatabaseSupport/5.8.0/QtFontDatabaseSupport/private  /qwindowsfontdatabase_p.h:1:93: fatal error: ../../../../../src/platformsuppo  rt/fontdatabases/windows/qwindowsfontdatabase_p.h: No such file or directory
 #include "../../../../../src/platformsupport/fontdatabases/windows/qwindowsf  ontdatabase_p.h"
                                                                                               ^
compilation terminated.
make[6]: *** [Makefile.Release:2358: .obj/release/qwindowsintegration.o] Erro  r 1
make[6]: *** Waiting for unfinished jobs....
In file included from ../windows/qwindowsintegration.h:46:0,
                 from ../windows/qwindowswindow.cpp:44:
../../../../include/QtFontDatabaseSupport/5.8.0/QtFontDatabaseSupport/private  /qwindowsfontdatabase_p.h:1:93: fatal error: ../../../../../src/platformsuppo  rt/fontdatabases/windows/qwindowsfontdatabase_p.h: No such file or directory
 #include "../../../../../src/platformsupport/fontdatabases/windows/qwindowsf  ontdatabase_p.h"
                                                                                               ^
compilation terminated.
make[6]: *** [Makefile.Release:1894: .obj/release/qwindowswindow.o] Error 1
In file included from ../windows/qwindowsintegration.h:46:0,
                 from ../windows/qwindowswindow.cpp:44:
../../../../include/QtFontDatabaseSupport/5.8.0/QtFontDatabaseSupport/private  /qwindowsfontdatabase_p.h:1:93: fatal error: ../../../../../src/platformsuppo  rt/fontdatabases/windows/qwindowsfontdatabase_p.h: No such file or directory
 #include "../../../../../src/platformsupport/fontdatabases/windows/qwindowsf  ontdatabase_p.h"
                                                                                               ^
compilation terminated.
In file included from ../windows/qwindowsintegration.h:46:0,
                 from ../windows/qwindowscontext.cpp:42:
../../../../include/QtFontDatabaseSupport/5.8.0/QtFontDatabaseSupport/private  /qwindowsfontdatabase_p.h:1:93: fatal error: ../../../../../src/platformsuppo  rt/fontdatabases/windows/qwindowsfontdatabase_p.h: No such file or directory
 #include "../../../../../src/platformsupport/fontdatabases/windows/qwindowsf  ontdatabase_p.h"
                                                                                               ^
compilation terminated.
In file included from ../windows/qwindowsintegration.h:46:0,
                 from ../windows/qwindowscontext.cpp:42:
../../../../include/QtFontDatabaseSupport/5.8.0/QtFontDatabaseSupport/private  /qwindowsfontdatabase_p.h:1:93: fatal error: ../../../../../src/platformsuppo  rt/fontdatabases/windows/qwindowsfontdatabase_p.h: No such file or directory
 #include "../../../../../src/platformsupport/fontdatabases/windows/qwindowsf  ontdatabase_p.h"
                                                                                               ^
compilation terminated.
make[6]: *** [Makefile.Debug:1894: .obj/debug/qwindowswindow.o] Error 1
make[6]: *** [Makefile.Debug:2791: .obj/debug/qwindowscontext.o] Error 1
make[6]: *** [Makefile.Release:2791: .obj/release/qwindowscontext.o] Error 1
In file included from ../windows/qwindowsintegration.h:46:0,
                 from ../windows/qwindowsscreen.cpp:43:
../../../../include/QtFontDatabaseSupport/5.8.0/QtFontDatabaseSupport/private  /qwindowsfontdatabase_p.h:1:93: fatal error: ../../../../../src/platformsuppo  rt/fontdatabases/windows/qwindowsfontdatabase_p.h: No such file or directory
 #include "../../../../../src/platformsupport/fontdatabases/windows/qwindowsf  ontdatabase_p.h"
                                                                                               ^
compilation terminated.
make[6]: *** [Makefile.Debug:3158: .obj/debug/qwindowsscreen.o] Error 1
In file included from ../windows/qwindowsintegration.h:46:0,
                 from ../windows/qwindowskeymapper.cpp:42:
../../../../include/QtFontDatabaseSupport/5.8.0/QtFontDatabaseSupport/private  /qwindowsfontdatabase_p.h:1:93: fatal error: ../../../../../src/platformsuppo  rt/fontdatabases/windows/qwindowsfontdatabase_p.h: No such file or directory
 #include "../../../../../src/platformsupport/fontdatabases/windows/qwindowsf  ontdatabase_p.h"
                                                                                               ^
compilation terminated.
make[6]: *** [Makefile.Debug:3560: .obj/debug/qwindowskeymapper.o] Error 1
make[6]: Leaving directory '/home/irakhlin/MINGW-packages/mingw-w64-qt5/src/x  86_64/qtbase/src/plugins/platforms/direct2d'
make[5]: *** [Makefile:38: debug-all] Error 2
make[5]: *** Waiting for unfinished jobs....
In file included from ../windows/qwindowsintegration.h:46:0,
                 from ../windows/qwindowskeymapper.cpp:42:
../../../../include/QtFontDatabaseSupport/5.8.0/QtFontDatabaseSupport/private  /qwindowsfontdatabase_p.h:1:93: fatal error: ../../../../../src/platformsuppo  rt/fontdatabases/windows/qwindowsfontdatabase_p.h: No such file or directory
 #include "../../../../../src/platformsupport/fontdatabases/windows/qwindowsf  ontdatabase_p.h"
                                                                                               ^
compilation terminated.
In file included from ../windows/qwindowsintegration.h:46:0,
                 from ../windows/qwindowsscreen.cpp:43:
../../../../include/QtFontDatabaseSupport/5.8.0/QtFontDatabaseSupport/private  /qwindowsfontdatabase_p.h:1:93: fatal error: ../../../../../src/platformsuppo  rt/fontdatabases/windows/qwindowsfontdatabase_p.h: No such file or directory
 #include "../../../../../src/platformsupport/fontdatabases/windows/qwindowsf  ontdatabase_p.h"

**Comment by Alexpux** [comment]
You need build Qt in directory with shorter PATH, like ````C:\repo\mingw-w64-qt````
Second is that you must remove previous Qt5 packages before building new one

**Comment by irakhlin** [comment]
Thank you very much. This indeed does fix it. I did not have old QT5 packages but it seem the path length was the issue. After fixing this everything builds fine.
