### ISSUE TITLE
nodejs is still 0.10.43

### ISSUE THREAD

**Issue by Uni-** [Alexpux/MINGW-packages#2146]
mingw-w64-nodejs 6.5.0 builds well (even current LTS 6.9.5 does), but the package seems suggesting an outdated version.

![still 0.10.43](https://cloud.githubusercontent.com/assets/1371115/22549479/e67c2bfc-e98e-11e6-8f1f-577c1eb6c518.png)

**Comment by Alexpux** [comment]
Well you can try update PKGBUILD for nodejs yourself for building current version. Then test both 32 and 64 builds yourself and if all is ok create pull request with changes to repository

**Comment by Uni-** [comment]
The point is, building `mingw-w64-nodejs` did not fail for 6.5.0 in our PKGBUILD; but pacman tells me to install 0.10.43. This is weird.

**Comment by mati865** [comment]
nodejs PKGBUILD from git repo will work if it is built in short path otherwise build will fail
