### ISSUE TITLE
mingw-w64-x86_64-hunspell uses invalid dictionary search paths

### ISSUE THREAD

**Issue by legends2k** [Alexpux/MINGW-packages#2147]
On a clean installation of MSYS2, I logged on to MINGW64 system and installed

* mingw-w64-x86_64-hunspell
* mingw-w64-x86_64-hunspell-en

The second package installed lot of English dictionary files at `/mingw64/share/hunspell`.

`hunspell -D` should show the search paths for dictionaries and the available dictionaries in those paths.  Here's the output I got

```
SEARCH PATH:
.;D:/msys64/mingw64/bin/;/mingw64/share/hunspell:/mingw64/share/myspell:/mingw64/share/myspell/dicts;%USERPROFILE%\/Application Data/OpenOffice.org 2/user/wordbookD:/msys64/mingw64/share/dict/ooo
AVAILABLE DICTIONARIES (path is not mandatory for -d option):
Can't open affix or dictionary files for dictionary named "en_US"
```

Notice that both Windows-based path delimiter `;` and MSYS2's path delimiter `:` are mixed and used; what's more, the last path has no delimiter!  Also the needed path is there but hunspell is unable to reach it perhaps due to this.

According to [hunspell's man page](https://linux.die.net/man/1/hunspell) if `$DICPATH` is set, it will search based on that.  In my `.bash_profile` I tried manually setting this to `/mingw64/share/hunspell` and still the same result: the old collage of paths we see above prevails.

How do we fix this?  It was working a month back.  I suspect it may be cause of #2091.

**Comment by peterbud** [comment]
As I see there is minimal or zero quality checks on those builds unfortunately.

What you can do is to revert back to the earlier version for the time being:
`cd /var/cache/pacman/pkg`
`pacman -U mingw-w64-x86_64-hunspell-1.4.1-2-any.pkg.tar.xz  `

**Comment by legends2k** [comment]
@peterbud Thanks, this works well for a a temporary workaround.
