### ISSUE TITLE
mingw-w64-x86_64-clang: can not build with coverage info.

### ISSUE THREAD

**Issue by LebedevRI** [Alexpux/MINGW-packages#2148]
I compile with `-fprofile-arcs -ftest-coverage` flags, and link with `-fprofile-arcs -ftest-coverage --coverage` flags, as stated everywhere.
On my local machine, with debian sid + clang 3.9 / 4.0 it does work, and the resulting binary does produce coverage data.
On appveyor ci, with msys2 + mingw-w64-x86_64-clang, linking step fails with messages like `undefined reference to `llvm_gcda_start_file'`" and so on.

Packages i install manually: `mingw-w64-x86_64-{toolchain,gcc,clang,cmake,ninja,libxml2,pugixml,libjpeg-turbo,zlib}`

What other information can i provide?

**Comment by mati865** [comment]
I worry one could say:

> It's not a bug, it's a feature

Feature reserved for UNIX like systems: in [ToolChains.cpp](https://github.com/llvm-mirror/clang/blob/0c60bc93ef346b9d7b8a58a8f85a8282508fd34b/lib/Driver/ToolChains.cpp) there are `void Darwin::addProfileRTLibs(...)` and `void Linux::addProfileRTLibs(...)` functions but nothing like Windows.
Those functions add aguments to the linker so it can link GCOV/GCDA symbols.

Also MSVC Clang either dumps core or cannot link symbols (depends on tested code):
```
clang_rt.profile-x86_64.lib(GCDAProfiling.c.obj) : error LNK2019: unresolved external symbol __iob_func referenced in function llvm_gcda_start_file
```

Unless Clang upstream resolves it I wouldn't expect this feature on Windows.

**Comment by LebedevRI** [comment]
Ah, ok then :)
