### ISSUE TITLE
osgearth does not compile with geos 3.6.1

### ISSUE THREAD

**Issue by filnet** [Alexpux/MINGW-packages#2153]
I'll take care of it (have already submitted a patch upstream)

**Comment by Alexpux** [comment]
osgearth in repo builded with geos-3.6.1. Patch was from upstream pull request

**Comment by Alexpux** [comment]
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-osgearth/0002-geos-3_6_1-support.patch

**Comment by filnet** [comment]
+1
