### ISSUE TITLE
NtCreateFile API failed when building Inkscape (Windows XP compatibility issue)

### ISSUE THREAD

**Issue by Ede123** [Alexpux/MINGW-packages#2155]
I'm a packager for the Inkscape project and I'm currently investigating if we can switch to MSYS2/mingw-w64 for building the official Inkscape Windows distributions in future.

I already successfully built Inkscape trunk with both, i686 and x86_64 architectures and they run on Windows 10 x64.

However I tried to run the i686 build on Windows XP x86 which immediately fails with the following system error:
> The NtCreateFile API failed. This error should never be returned to an application, it is a place holder for the Windows Lan Manager Redirector to use in its internal error mapping routines.

Seems to be `ERROR_NET_OPEN_FAILED` (see error number 570 [here](https://msdn.microsoft.com/library/windows/desktop/ms681388.aspx)), which I'm not sure makes sense at all and I have really no idea what could possibly trigger it, so I'm hoping somebody around here can help me find out what's going wrong!

The only thing I have so far: Could this be a problem with exception handling? I know x86_64-w64-mingw32 is built with dw2 exception handling and if I understand [the information in the GCC wiki](https://gcc.gnu.org/wiki/WindowsGCCImprovements) correctly it might be fundamentally incompatible for building an app like Inkscape?

*P.S. I know this is not a real bug report, yet, as I've still to determine if the problem is actually in one of the MINGW-packages. However I couldn't find a better location to discuss such issues, so please let me know if I overlooked anything*

**Comment by Alexpux** [comment]
Well it can be issue with one of the packages because XP support is dropping now by different projects.

**Comment by mati865** [comment]
> I know x86_64-w64-mingw32 is built with dw2 exception handling

I think you mean i686-w64-mingw32.
Dw2 was working on XP but could be broken recently by toolchain update.

CreateFile error could be caused by insufficient permissions or anti-virus software.
And as @Alexpux says dependencies might be using APIs incompatible with XP which is getting more common as time goes by.
