### ISSUE TITLE
error: C++ preprocessor "/lib/cpp" fails sanity check

### ISSUE THREAD

**Issue by memoryleakno1** [Alexpux/MINGW-packages#2157]
I am trying to build libjpeg-turbo and libtiff with mingw-64 and I am getting from both libraries same error from configure script. I was able to build some other packages without problems.

**Comment by Alexpux** [comment]
Look into config.log at first.

**Comment by mati865** [comment]
You are using msys/gcc instead of mingw32/mingw-w64-i686-gcc or mingw64/mingw-w64-x86_64-gcc

**Comment by memoryleakno1** [comment]
I am quite sure I am using mingw64 sheel, I always use that one.  I just tried again and get same result from libtiff. Libjpeg-turbo  builds fine after I sincked mingw-packages to repo. Log says configure fails to find dlfcn.h:

configure:8552: checking for dlfcn.h
configure:8552: x86_64-w64-mingw32-gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-strict-aliasing -Wall -W -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 conftest.c >&5
conftest.c:55:19: fatal error: dlfcn.h: No such file or directory
 #include <dlfcn.h>

**Comment by mati865** [comment]
I assumed you are using msys/gcc because `/lib/cpp` exists only as /usr/lib/cpp.

Failure to find dlfcn is expected as you shouldn't have it installed and it isn't reason preventing you from building it.
I just compiled 64 bit libtiff, here is [config.log.txt](https://github.com/Alexpux/MINGW-packages/files/759308/config.log.txt)

**Comment by memoryleakno1** [comment]
> Failure to find dlfcn is expected as you shouldn't have it installed and it isn't reason preventing you from building 
Well it is for me :-). But why does it fail for me? I don't even have a /lib/cpp installed - there is no /lib. I made a symlink to /mingw64/bin/cpp.exe just to get around these compilation errors, but it still fails as shown above. 

What cmd did you use to build it with? I used     
`MINGW_INSTALLS=mingw64` makepkg-mingw -sLf 

As stated in README in top dir.

**Comment by memoryleakno1** [comment]
Ok, it was my bad I have found the problem. I had in my shell defined CXX environement variable which was pointing to where I have my c++ headers, code, etc (I have different environements setupped for different compilers). That env spooked with configure script seems like. After renaming it I have build libtiff without problems. It was bit tuff to find since I had it for sol on without problems and was deep in some shell scripts I use to config my system.

**Comment by mati865** [comment]
@elieux, can you close it?

**Comment by ChrigiGee** [comment]
Hi @all,

Sorry, I open this case again, I have again this problem until now.
I try to compile xapian, i deinstall mingw and install again.
I delete source copy from zip in my folder, try again, with same error.

I use windows i7 pc with win 11.

Kind regards
Chris
