### ISSUE TITLE
Imagemagick compilation fails with pgp signature can not be verified

### ISSUE THREAD

**Issue by memoryleakno1** [Alexpux/MINGW-packages#2158]
I just sinced to git repo and am trying to build Imagemagic. It fails to verify pgp signature to main package:

 003-7.0.1.8-cplusplus-fixes.patch ... Godkänd
==> Verifierar källfil signaturer med gpg...
    ImageMagick-7.0.4-7.tar.xz ... MISSLYCKADES (okänd publik nyckel 89AB63D48277377A)
==> FEL:  En eller fler PGP signaturer kunde ej bli Verifierade!

(sorry it's in swedish - says: ... FAILED (unknown public key 89AB63D48277377A) ...

I was able to fix it by downloading lexie.p. key from MIT keyserver and importing it to my pacman database.

However, compilation fails in configure script:

conftest.c:14:28: fatal error: ac_nonexistent.h: No such file or directory
 #include <ac_nonexistent.h>
                            ^
compilation terminated.

**Comment by Alexpux** [comment]
Pass "--skippgpcheck" to makepkg

**Comment by memoryleakno1** [comment]
Ok, didn't know about that flag.

**Comment by mati865** [comment]
I don't thing missing `ac_nonexistent.h` is the cause. It is POSIX header which isn't even available under Cygwin.

Make sure you are using command like `makepkg-mingw -s`, `-s` will install package dependencies.
If it doesn't help paste whole terminal output.

**Comment by memoryleakno1** [comment]
It was my bad, as I wrote in another comment, I had badly named env variable (CXX) that really spooked all builds that involve c++ seems like. After renaming it I was able to build libtiff, imagemagic and openscenegraph without problems.
