### ISSUE TITLE
Qt WebKit crash after latest upgrade

### ISSUE THREAD

**Issue by omichel** [Alexpux/MINGW-packages#2163]
After I updated this morning `mingw-w64-x86_64-qt5` and `mingw-w64-x86_64-qtwebkit` (among others), my application crashes when calling `QWebView::load()`. Any idea on what could have been broken by this update?

**Comment by Alexpux** [comment]
This is new QtWebkit module based on new sources. So this is maybe bug. Try to get more info

**Comment by omichel** [comment]
It seems `mingw-w64-x86_64-qtwebkit` is a new package based on version `tp5` of https://github.com/annulen/webkit. I can't figure out what was the name of the old one it replaced. Was it based on version `tp4` or something else?

**Comment by bagong** [comment]
Maybe safer to stay rather conservative with Webkit?

**Comment by annulen** [comment]
* Could you get backtrace with gdb?
* Could you check 32-bit version of package?

**Comment by omichel** [comment]
See comments and follow-up here: https://github.com/supercollider/supercollider/issues/2204#issuecomment-279694679

**Comment by Alexpux** [comment]
Test new qtwebkit packages uploaded to repo.

**Comment by omichel** [comment]
Thank you. I just tested it (`pacman -Syuu`) but I get the exact same crash 😒. When reverting to the good old `Qt5WebKitWidgets.dll` and `Qt5WebKit.dll` (version just before tp5), then it works again without any crash.

**Comment by Alexpux** [comment]
Did you get tp5-2 package?

**Comment by omichel** [comment]
Yes:
```
$ pacman -Q | grep webkit
mingw-w64-x86_64-qtwebkit tp5-2
```

**Comment by bagong** [comment]
For what it's worth (little, really, but at least some reaction and token of appreciation): for our project these latest webkit packages work, 64- and 32-bit. But we don't use Webkit extensively, and I haven't had a chance to test it into corners. Oth, for the time being, we'd collapse without it ;). I am glad @annulen 's packages gets some exposure in MSYS2, they fill a real gap that that will likely be felt more and more in the years needed by people to decide if they can afford to switch to WebEngine (which in turn means they'd have to leave the MinGW ecosystem, right). While it's not the right place here (sorry, ;) ), I'll mention too that annulen also provides VS 2015 packages, which is another serious desideratum for people on the dark side :D For us, as small, very specialized project, it is effectively impossible to test and even just judge the usability and safeness of packages as complex as Webkit. We actually depend on *trust*. So we thank MSYS2 for creating an environment in which taking the step of moving away from the official distributions becomes a bit more responsible.

**Comment by omichel** [comment]
I confirm that the new package, e.g., `mingw-w64-x86_64-qtwebkit tp5-3`, seems to fix the problem. My app doesn't crash any more. Thanks ! 😄

**Comment by Alexpux** [comment]
64 bit QtWebkit builded without JIT

**Comment by Alexpux** [comment]
I think we need get this issue open while QtWebkit not fixed upstream bug with JIT

**Comment by bagong** [comment]
Thank you so much for your work, @Alexpux  and @annulen !
