### ISSUE TITLE
gtk3 native windows theme

### ISSUE THREAD

**Issue by Ede123** [Alexpux/MINGW-packages#2164]
Is gtk3 supposed to offer a native Windows theme?

This is what the "gtk3-demo-application.exe" about screen looks out-of-the-box for me on Windows 10 (i.e. it clearly uses the Adwaita theme):
![gtk3_windows10](https://cloud.githubusercontent.com/assets/904570/22955495/b595b048-f31c-11e6-98e0-b768b3422396.png)

Setting `gtk-theme-name=win32` in `etc\gtk-3.0\settings.ini` doesn't improve upon that all (remember I'm on Windows 10, so the theme is completely wrong):
![gtk3_windows10_win32-theme](https://cloud.githubusercontent.com/assets/904570/22955639/6ed2052a-f31d-11e6-8b62-be7a6a129a54.png)

Did the Gnome-people break native Windows theming or is there a packaging issue?

**Comment by lazka** [comment]
Two things:

1) gtk3 never had a proper windows theme, some work went into improving it for 3.20/22. I'm using Adwaita (the default) on Windows and no one ever complained about it.
2) gtk3 for some reason defaults to client side window decorations, which means it draws the window border manually. You can disable them by setting the GTK_CSD env var to 0. They still get used if the program forces them by putting widgets in them etc.. Someone should probably file a bug report upstream to change the default behavior.

**Comment by Ede123** [comment]
Wow, thank you so much! 2. is solid gold!
The non-matching window borders and title bar were the main reason for me to look into this. I can live if some controls looking different, but obviously the windows itself shouldn't deviate too much from the system default.

Also since everything else can be changed in CSS if necessary this basically would allow to make the rest at least look native, but transparent borders and stuff is probably nothing that can be recreated easily.

**Comment by Ede123** [comment]
With `GTK_CSD=0` it already looks OK
![zwischenablage01](https://cloud.githubusercontent.com/assets/904570/23035817/bb4f1514-f480-11e6-80e1-ee1307e5cbdb.png)

With `GTK_CSD=0` and `gtk-theme-name=win32` it could pass as native
![zwischenablage02](https://cloud.githubusercontent.com/assets/904570/23035839/d4e11540-f480-11e6-9847-6a42316b6891.png)

**Comment by Ede123** [comment]
Well, I filed [a bug](https://bugzilla.gnome.org/show_bug.cgi?id=778791) in the GNOME bugtracker, let's see if something comes from it.

At least I hope people will be able to find this bug report as the `GTK_CSD` seems widely unknow/undocumented while it offers an easy solution.

**Comment by lazka** [comment]
Thanks for filing the bug report.

btw, this is the CSS I use on Windows to make buttons/entries more compact with Adwaita, maybe it helps:

```
spinbutton, button {
    min-height: 1.8rem;
}
.view button {
    min-height: 2.0rem;
}
entry {
    min-height: 2.4rem;
}
entry.cell {
    min-height: 0;
}
```

**Comment by Ede123** [comment]
Enabling CSD by default on Windows was actually [implemented on purpose](https://bugzilla.gnome.org/show_bug.cgi?id=759899).
