### ISSUE TITLE
Unable to compile with OpenGL or FreeGLUT in 32 bits

### ISSUE THREAD

**Issue by jburguete** [Alexpux/MINGW-packages#2176]
I cannot compile my applications using OpenGL and FreeGLUT in 32 bits.

I have installed the last mingw32/mingw-w64-i686-freeglut package.

A typical test code as:

char glViewport ();
char glutInit ();
int main ()
{
glViewport ();
glutInit ();
return 0;
}

Then, trying to compile in 32 bits as:
gcc test.c -lopengl32 -lfreeglut

fails with the error message:
undefined reference to 'glViewport'
undefined reference to 'glutInit'
collect2.exe: error: ld returned 1 exit status

In 64 bits they are not problems.

**Comment by mati865** [comment]
@Alexpux?

32 bit lib:
```
$ nm /mingw32/lib/libfreeglut.dll.a | grep glutInit
...
00000000 I __imp__glutInit@8
00000000 T _glutInit@8
...
```

64 bit lib:
```
$ nm /mingw64/lib/libfreeglut.dll.a | grep glutInit
...
0000000000000000 I __imp_glutInit
0000000000000000 T glutInit
...
```

**Comment by jburguete** [comment]
Similar for OpenGL:
`$ nm /mingw32/i686-w64-mingw32/lib/libopengl32.a | grep glViewport`
`00000000 I __imp__glViewport@16`
`00000000 T _glViewport@16`
`$ nm /mingw64/x86_64-w64-mingw32/lib/libopengl32.a | grep glViewport`
`0000000000000000 I __imp_glViewport`
`0000000000000000 T glViewport`

**Comment by Alexpux** [comment]
For me example looks completely wrong. You must include freeglut headers to properly link with libraries. 
Output of nm is completely right

**Comment by Alexpux** [comment]
Read http://www.transmissionzero.co.uk/computing/using-glut-with-mingw/

**Comment by Alexpux** [comment]
Here is code:
````
#include <stdlib.h>
#include <GL/glut.h>

void keyboard(unsigned char key, int x, int y);
void display(void);


int main(int argc, char** argv)
{
  glutInit(&argc, argv);
  glutCreateWindow("GLUT Test");
  glutKeyboardFunc(&keyboard);
  glutDisplayFunc(&display);
  glutMainLoop();

  return EXIT_SUCCESS;
}


void keyboard(unsigned char key, int x, int y)
{
  switch (key)
  {
    case '\x1B':
      exit(EXIT_SUCCESS);
      break;
  }
}


void display()
{
  glClear(GL_COLOR_BUFFER_BIT);

  glColor3f(1.0f, 0.0f, 0.0f);

  glBegin(GL_POLYGON);
    glVertex2f(-0.5f, -0.5f);
    glVertex2f( 0.5f, -0.5f);
    glVertex2f( 0.5f,  0.5f);
    glVertex2f(-0.5f,  0.5f);
  glEnd();

  glFlush();
}
````

Building and running show expected result:
````
Alexey@HomeBuild MSYS ~
$ PATH=/mingw64/bin:$PATH gcc -o test_glut.exe test_glut.c -lfreeglut -lopengl32 -Wl,--subsystem,windows

Alexey@HomeBuild MSYS ~
$ PATH=/mingw64/bin:$PATH ./test_glut.exe

Alexey@HomeBuild MSYS ~
$ PATH=/mingw32/bin:$PATH gcc -o test_glut2.exe test_glut.c -lfreeglut -lopengl32 -Wl,--subsystem,windows

Alexey@HomeBuild MSYS ~
$ PATH=/mingw32/bin:$PATH ./test_glut2.exe  
````

**Comment by mati865** [comment]
Nm shows that symbols are fine. Why does it compile using 64 bit tools/libs?

**Comment by Alexpux** [comment]
@mati865, 64-bit libraries contain symbols without underscores. It depends on calling convention. But if you run topic starter example builded with 64 bit compiler it immediately crash with segmentation fault, so it not work too.

**Comment by Alexpux** [comment]
@mati865 , also look into free glut headers how prototype of ````glutInit```` looks. It completely different from example of topic starter

**Comment by Alexpux** [comment]
@jburguete @mati865 look more deeply into ````nm```` output. It tell:
````__imp__glutInit@8````
Where  ````@8```` is argument count passed to function.
The same for ````__imp__glViewport@16````

In the topic starter example prototypes are:
````
char glViewport ();
char glutInit ();
````

So linker not find in libraries functions with 0 arguments passed to it.

**Comment by mati865** [comment]
@Alexpux thanks for explaining. I thought 32 bit functions with decoration works the same as undecorated 64 bit functions.

**Comment by jburguete** [comment]
OK, thanks for explaining.

However, the test is a modified code extracted from autoconf tests searching libraries as:
`AC_SEARCH_LIBS([OPENGL], [GL opengl32])`
`AC_SEARCH_LIBS([GLUT], [freeglut glut])`

32 bit functions with decoration could complicate to do portable configure scripts.
