### ISSUE TITLE
mingw-w64-zeromq is missing c++ headers

### ISSUE THREAD

**Issue by carrotIndustries** [Alexpux/MINGW-packages#2179]
The c++ headers got moved to a new project, see the archlinux PKGBUILD on where to get them.

**Comment by mingwandroid** [comment]
Please submit a PR.

**Comment by carrotIndustries** [comment]
See https://github.com/Alexpux/MINGW-packages/pull/2193

**Comment by Alexpux** [comment]
Fixed.
