### ISSUE TITLE
Is texinfo considered mandatory, or why is it not listed as dependency?

### ISSUE THREAD

**Issue by emmenlau** [Alexpux/MINGW-packages#2184]
I found that several packages depend on `texinfo` (because they fail to build without `makeinfo`). Affected is at least `mingw-w64-gdb` and `mingw-w64-binutils`. I can add texinfo and make a pull request, but first I wanted to know: is this my fault, am I expected to have texinfo installed first? Or am I using the wrong make or wrong shell? I build all packages with `make-pkg` from the `MSYS` shell, not `MinGW64` shell, is that ok?

**Comment by dimztimz** [comment]
Texinfo is part of the package  group base-devel which is mandatory for any package. That is why it is not specified in the pkgbuid. It is assumed that you already have it installed.

**Comment by emmenlau** [comment]
Thanks for the quick reply. I understand now. But I wonder, would it maybe be helpful if every package lists all build dependencies explicitly? As an example, many packages list 'gcc' explicitly as a requirement, which lead me to believe that all prerequisites are explicitly listed.

In other words, if I add `texinfo` explicitly and make a PR, would it be appreciated or discouraged?

**Comment by Alexpux** [comment]
Well listing in all PKGBUILD many packages is hard to maintain really. I will not accept this changes. Read WIKI - it tell that for package developing you need install ````base-devel```` packages group

**Comment by emmenlau** [comment]
Ok if its discouraged then its fine for me! Closing issue.
