### ISSUE TITLE
latest mingw-w64-pkg-config fails to build with size_t error in configure

### ISSUE THREAD

**Issue by emmenlau** [Alexpux/MINGW-packages#2191]
I tried to compile the current toolchain (from today) for `x86_64`. After a few packages the build stops at `mingw-w64-pkg-config`. pkg-config fails to configure, due to an error:
```
checking for the appropriate definition for size_t... configure: error: No type matching size_t in size
configure: error: ../../pkg-config-0.29.1/glib/configure failed for glib
```
Here is the build log:
http://data.biodataanalysis.de/tmp/buildlogs/1487602125-mingw-w64-pkg-config-buildlog.txt

**Comment by mati865** [comment]
It is missing dependency on glib2.

**Comment by emmenlau** [comment]
Thanks @mati865 , fixed by https://github.com/Alexpux/MINGW-packages/pull/2197

**Comment by Alexpux** [comment]
I'm not accept changes

**Comment by emmenlau** [comment]
Should I set PKGBUILD to use `--with-internal-glib` and make a PR?

**Comment by Alexpux** [comment]
it already have this option
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-pkg-config/PKGBUILD#L74

**Comment by emmenlau** [comment]
Sorry wait, there *is* already `--with-internal-glib`, then why did the build fail?

**Comment by emmenlau** [comment]
Ok I see, we where on the wrong track! Its the same issue with size_t:
```
checking for the appropriate definition for size_t... configure: error: No type matching size_t in size
```
See the build log: http://data.biodataanalysis.de/tmp/buildlogs/1487602125-mingw-w64-pkg-config-buildlog.txt

**Comment by emmenlau** [comment]
I've modified the build order and pkg-config still fails, albeit with a slightly more helpful error message:
```
make[7]: Entering directory '/d/Temp/mingw-w64-pkg-config/src/build-x86_64-w64-mingw32/glib/glib/gnulib'
  CC       libgnulib_la-asnprintf.lo
  CC       libgnulib_la-printf-args.lo
  CC       libgnulib_la-printf-parse.lo
  CC       libgnulib_la-vasnprintf.lo
  CC       libgnulib_la-printf.lo
In file included from ../../../../pkg-config-0.29.1/glib/glib/gtypes.h:34:0,
                 from ../../../../pkg-config-0.29.1/glib/glib/galloca.h:34,
                 from ../../../../pkg-config-0.29.1/glib/glib/glib.h:32,
                 from ../../../../pkg-config-0.29.1/glib/glib/gnulib/g-gnulib.h:23,
                 from ../../../../pkg-config-0.29.1/glib/glib/gnulib/printf-args.c:23:
../../glib/glibconfig.h:77:2: error: #error SIZEOF_VOID_P unknown - This should never happen
 #error SIZEOF_VOID_P unknown - This should never happen
  ^~~~~
In file included from ../../../../pkg-config-0.29.1/glib/glib/gtypes.h:34:0,
                 from ../../../../pkg-config-0.29.1/glib/glib/galloca.h:34,
                 from ../../../../pkg-config-0.29.1/glib/glib/glib.h:32,
                 from ../../../../pkg-config-0.29.1/glib/glib/gnulib/g-gnulib.h:23,
                 from ../../../../pkg-config-0.29.1/glib/glib/gnulib/printf-parse.c:23:
../../glib/glibconfig.h:77:2: error: #error SIZEOF_VOID_P unknown - This should never happen
 #error SIZEOF_VOID_P unknown - This should never happen
  ^~~~~
In file included from ../../../../pkg-config-0.29.1/glib/glib/gtypes.h:34:0,
                 from ../../../../pkg-config-0.29.1/glib/glib/galloca.h:34,
                 from ../../../../pkg-config-0.29.1/glib/glib/gnulib/vasnprintf.c:31:
../../glib/glibconfig.h:77:2: error: #error SIZEOF_VOID_P unknown - This should never happen
 #error SIZEOF_VOID_P unknown - This should never happen
  ^~~~~
In file included from ../../../../pkg-config-0.29.1/glib/glib/gtypes.h:34:0,
                 from ../../../../pkg-config-0.29.1/glib/glib/galloca.h:34,
                 from ../../../../pkg-config-0.29.1/glib/glib/glib.h:32,
                 from ../../../../pkg-config-0.29.1/glib/glib/gnulib/g-gnulib.h:23,
                 from ../../../../pkg-config-0.29.1/glib/glib/gnulib/asnprintf.c:23:
../../glib/glibconfig.h:77:2: error: #error SIZEOF_VOID_P unknown - This should never happen
 #error SIZEOF_VOID_P unknown - This should never happen
  ^~~~~
In file included from ../../../../pkg-config-0.29.1/glib/glib/gtypes.h:34:0,
                 from ../../../../pkg-config-0.29.1/glib/glib/galloca.h:34,
                 from ../../../../pkg-config-0.29.1/glib/glib/glib.h:32,
                 from ../../../../pkg-config-0.29.1/glib/glib/gnulib/g-gnulib.h:23,
                 from ../../../../pkg-config-0.29.1/glib/glib/gnulib/printf.c:33:
../../glib/glibconfig.h:77:2: error: #error SIZEOF_VOID_P unknown - This should never happen
 #error SIZEOF_VOID_P unknown - This should never happen
  ^~~~~
make[7]: *** [Makefile:984: libgnulib_la-printf-args.lo] Error 1
make[7]: *** Waiting for unfinished jobs....
```
http://data.biodataanalysis.de/tmp/buildlogs/1487699827-mingw-w64-pkg-config-buildlog.txt

I wonder why the compile worked when I installed `mingw-w64-glib2` before pkg-config. And ideas whats going on?

**Comment by mati865** [comment]
Your toolchain is broken, but I have no idea what could cause it.
External glib2 worked because it's build with working toolchain.

**Comment by emmenlau** [comment]
Its more strange than that: I build the external glib2 myself and it worked.

When I added the dependency `mingw-w64-glib2` to `mingw-w64-pkg-config`, my build order became `mingw-w64-gdb mingw-w64-glib2 mingw-w64-libiconv mingw-w64-make mingw-w64-mpfr mingw-w64-tools-git mingw-w64-expat mingw-w64-ncurses mingw-w64-mpc mingw-w64-pkg-config ...` and everything worked until after pkg-config.

Now I removed the dependency on external glib2 again, and the build order is `mingw-w64-headers-git mingw-w64-make mingw-w64-crt-git mingw-w64-pkg-config` and pkg-config fails. So maybe the problem is caused by latest `mingw-w64-headers-git` or `mingw-w64-crt-git`?

**Comment by mati865** [comment]
You can downgrade crt, headers and try.

**Comment by Alexpux** [comment]
@emmenlau  @mati865  sems you guys have some issues with your environment. I'm rebuild pkg-config without any errors

**Comment by Alexpux** [comment]
Here is build log:
http://pastebin.com/0veTZjR8

**Comment by mati865** [comment]
@Alexpux I couldn't reproduce it (I have glib installed).
By error message I supposed internal glib is broken.

**Comment by Alexpux** [comment]
@mati865 Try to find what is wrong for you. Really I can't reproduce issue with building

**Comment by emmenlau** [comment]
Ok, it seems that since yesterdays package updates, the problem is solved. I could still reproduce the problem yesterday, but now not anymore. I'm closing this issue as fixed and will re-open in case it should appear again...
