### ISSUE TITLE
mingw-w64-python2 error: cannot compute sizeof (size_t)

### ISSUE THREAD

**Issue by emmenlau** [Alexpux/MINGW-packages#2196]
I continued building the current toolchain with latest snapshot packages from git for `x86_64`. The next failure is in `mingw-w64-python2`, it can not compute the sizeof size_t:
```
configure: error: cannot compute sizeof (size_t)
See `config.log' for more details
==> ERROR: A failure occurred in build().
    Aborting...
```
Could this error be related to https://github.com/Alexpux/MINGW-packages/issues/2183? I'm just wildly guessing here, but it seems a very "basic" functionality broken? Please find my build log here: http://data.biodataanalysis.de/tmp/buildlogs/1487634780-mingw-w64-python2-buildlog.txt

**Comment by Alexpux** [comment]
Show config.log from build folder.

**Comment by emmenlau** [comment]
http://data.biodataanalysis.de/tmp/buildlogs/1487634780-mingw-w64-python2-config.log

**Comment by mati865** [comment]
To make it clear: have you build headers before crt?
https://github.com/Alexpux/MINGW-packages/issues/2186#issuecomment-280949792

**Comment by emmenlau** [comment]
Maybe I have a bad build order? I use tsort on the dependencies to find a best ordering, but there are two loops so tsort can not resolve everything. What it finds is this order (I'm stuck at `mingw-w64-python2`, so `mingw-w64-headers-git` and `mingw-w64-crt-git` would come much later):
```
mingw-w64-gdb
mingw-w64-glib2
mingw-w64-libiconv
mingw-w64-make
mingw-w64-mpfr
mingw-w64-python2
mingw-w64-tools-git
mingw-w64-expat
mingw-w64-ncurses
mingw-w64-mpc
mingw-w64-pkg-config
mingw-w64-windows-default-manifest
mingw-w64-xz
mingw-w64-libmangle-git
mingw-w64-winpthreads-git
mingw-w64-winstorecompat-git
mingw-w64-zlib
mingw-w64-headers-git
mingw-w64-isl
mingw-w64-crt-git
mingw-w64-gmp
mingw-w64-gcc
```

**Comment by emmenlau** [comment]
PS: my build system installs the package immediately after the build, before building the next package. Is that good practice, or should I first build all updated toolchain packages with the current toolchain, and then install them together?

**Comment by mingwandroid** [comment]
You should probably try to install as a group all those that were built from the same `PKGBUILD`.

**Comment by emmenlau** [comment]
The problem persists, even though I tried various steps like installing as a group, building python2 dependencies before python2, or changing build order. The error remains always similar, it can not compute the sizeof some type:
http://data.biodataanalysis.de/tmp/buildlogs/1488412915-mingw-w64-python2-buildlog.txt

**Comment by emmenlau** [comment]
I have similar (or at least possibly related) problems with a number of packages. Not every build, I can build some ~30 packages successfully, but there are at least `mingw-w64-lzo2`, `mingw-w64-mpg123` and `mingw-w64-python3` that also fail with an error `cannot compute sizeof (xxx)` for different types `xxx`.

**Comment by emmenlau** [comment]
After a long debugging period, the most likely cause for my problems is actually a Windows permission problem. I am not certain about this yet, but there have been some spurious errors about "permission denied" i.e. when `qtbinpatcher` was run on qmake. Since I seem to get more errors than most other people I will test on a different computer setup and close all issues until further notice. 

If somebody has insight on Windows user accounts, it would be highly appreciated: I am running continuous integration as a service, using the logon credentials of my actual Windows (GUI) user account. I use the username and password in the system logon. It still seems the build behavior is different from running the CI versus a manual compile from the GUI. Is this possibly a known problem?
