### ISSUE TITLE
freeimage broken after libraw upgrade

### ISSUE THREAD

**Issue by omichel** [Alexpux/MINGW-packages#2210]
libfreeimage-3.dll still refer to old and missing libraw-15 after the upgrade to libraw-16.
Could you re-build mingw-w64-x86_64-freeimage to fix this problem?

**Comment by Alexpux** [comment]
Will look into it tomorrow

**Comment by omichel** [comment]
I confirm that 420298252d779163fd87c1198e4587a48fa6f5c0 fixed the problem.
