### ISSUE TITLE
qt5-static not building

### ISSUE THREAD

**Issue by loganmc10** [Alexpux/MINGW-packages#2227]
I am trying to get an application to build on AppVeyor, it works fine on my Windows 7 laptop, but on AppVeyor I get this:

```
make[1]: Entering directory '/c/projects/mupen64plus-gliden64/mupen64plus-gui/build'
/C/msys64/mingw64/qt5-static/bin/uic.exe ../mainwindow.ui -o ui_mainwindow.h
make[1]: *** No rule to make target '../../../../../msys64/mingw64/qt5-static/include/QtWidgets/QMainWindow', needed by 'release/main.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
```

**Comment by Alexpux** [comment]
Try use shorter folder for project. Seems generated path is wrong

**Comment by loganmc10** [comment]
I made it shorter, same result:
```
make[1]: Entering directory '/c/mg/mupen64plus-gui/build'
/C/msys64/mingw64/qt5-static/bin/uic.exe ../mainwindow.ui -o ui_mainwindow.h
make[1]: *** No rule to make target '../../../../msys64/mingw64/qt5-static/include/QtWidgets/QMainWindow', needed by 'release/main.o'.  Stop.
```

**Comment by loganmc10** [comment]
I found a document that documents the undocumented features of qmake (https://wiki.qt.io/Undocumented_QMake), and it suggested adding ```QMAKE_PROJECT_DEPTH  = 0``` to the .pro file, which forces absolute paths in the Makefile generation, which fixed this problem for me. For some reason my PC was using absolute paths and AppVeyor was using (wrong) relative paths
