### ISSUE TITLE
mingw-w64-x86_64-make 4.2.1-1 needs libintl-8.dll

### ISSUE THREAD

**Issue by per42** [Alexpux/MINGW-packages#2233]
Like reported in https://github.com/Alexpux/MINGW-packages/issues/2048, mingw make also can't load libintl-8.dll. It fails to run when executed in Windows.

Downgrading to 4.1 solves it:

```sh
pacman -U mingw-w64-x86_64-make-4.1.2351.a80a8b8-1-any.pkg.tar.xz
```

Installing mingw gettext like suggested in the issue mentioned also solves it.

**Comment by mmozeiko** [comment]
Can confirm. This is happening with latest packages even right now.

**Comment by vec715** [comment]
installing gettext did not fixing the problem for me...
