### ISSUE TITLE
mingw-w64-libtool build fails

### ISSUE THREAD

**Issue by emmenlau** [Alexpux/MINGW-packages#2234]
I'm trying to build `mingw-w64-libtool` but it fails and I can not fix it myself, help would be
appreciated. Here the error I get:
```
libtool:   error: not configured to extract global symbols from dlpreopened files
libltdl/.libs/libltdl_libltdl_la-ltdl.o:ltdl.c:(.rdata$.refptr.lt_libltdl_LTX_preloaded_symbols[.refptr.lt_libltdl_LTX_preloaded_symbols]+0x0): undefined reference to `lt_libltdl_LTX_preloaded_symbols'
collect2.exe: error: ld returned 1 exit status
```
What I found so far is this error may actually be related to a problem when using `nm`. Its possible that this is also the problem for me, because I could find suspicious lines with respect to `nm` in `config.log`. I'm using latest binutils from the official repo, in case that matters.

Here is the build log:
http://data.biodataanalysis.de/tmp/buildlogs/1488399488-mingw-w64-libtool-buildlog.txt
And the config.log:
http://data.biodataanalysis.de/tmp/buildlogs/1488399488-mingw-w64-libtool-config.log

**Comment by mati865** [comment]
I don't know if it is wrong but only static library contains `lt_libltdl_LTX_preloaded_symbols`.

**Comment by emmenlau** [comment]
After a long debugging period, the most likely cause for my problems is actually a Windows permission problem. I am not certain about this yet, but there have been some spurious errors about "permission denied" i.e. when `qtbinpatcher` was run on qmake. Since I seem to get more errors than most other people I will test on a different computer setup and close all issues until further notice. 

If somebody has insight on Windows user accounts, it would be highly appreciated: I am running continuous integration as a service, using the logon credentials of my actual Windows (GUI) user account. I use the username and password in the system logon. It still seems the build behavior is different from running the CI versus a manual compile from the GUI. Is this possibly a known problem?
