### ISSUE TITLE
many packages fail building because configure does not know how to parse nm output?

### ISSUE THREAD

**Issue by emmenlau** [Alexpux/MINGW-packages#2244]
I've problems building a list of packages that all fail for the same reason. The list is `mingw-w64-freetype`, `mingw-w64-fribidi`, `mingw-w64-jansson`, `mingw-w64-libass`, `mingw-w64-libgpg-error`, `mingw-w64-libpng`, `mingw-w64-libssh2`, `mingw-w64-libtheora`, `mingw-w64-mpg123`, `mingw-w64-opencore-amr`, `mingw-w64-orc`, `mingw-w64-p11-kit`, `mingw-w64-portaudio`, `mingw-w64-schroedinger`, `mingw-w64-wavpack`. They all fail with (mostly) the same error:
```
./libtool: eval: line 1736: syntax error near unexpected token `|'
```
The line number of libtool and the path to libtool may be slightly different, but other than that, the error is the same. All these packages have a problem using nm to parse binaries, i.e. they all complain earlier in configure:
```
checking command to parse /mingw64/bin/nm -B output from x86_64-w64-mingw32-gcc object... failed
```
According to a broad internet search, this might be related.

**Comment by askondro** [comment]
I built mingw-w64-mpg123 right now without issues. Can you post the output of your makepkg command?

**Comment by askondro** [comment]
Did you try to reinstall mingw-w64-x86_64-binutils?

**Comment by emmenlau** [comment]
After a long debugging period, the most likely cause for my problems is actually a Windows permission problem. I am not certain about this yet, but there have been some spurious errors about "permission denied" i.e. when `qtbinpatcher` was run on qmake. Since I seem to get more errors than most other people I will test on a different computer setup and close all issues until further notice. 

If somebody has insight on Windows user accounts, it would be highly appreciated: I am running continuous integration as a service, using the logon credentials of my actual Windows (GUI) user account. I use the username and password in the system logon. It still seems the build behavior is different from running the CI versus a manual compile from the GUI. Is this possibly a known problem?
