### ISSUE TITLE
mingw-w64-gettext never compiles from makepkg-mingw, but sometimes from the shell

### ISSUE THREAD

**Issue by emmenlau** [Alexpux/MINGW-packages#2245]
I continue having bad problems building mingw64 packages, this time with `mingw-w64-gettext`. The build always fails in directory `gettext-tools/src/` with an error about linking on the the tools `msgfmt.exe`, `msgunfmt.exe`, `msgmerge.exe` or `msgattrib.exe`:
```
libtool: link: x86_64-w64-mingw32-gcc -march=x86-64 -mtune=generic -O2 -pipe -pipe -Wl,--disable-auto-import -o .libs/msgfmt.exe msgfmt-msgfmt.o msgfmt-write-mo.o msgfmt-write-java.o msgfmt-write-csharp.o msgfmt-write-resources.o msgfmt-write-tcl.o msgfmt-write-qt.o msgfmt-write-desktop.o msgfmt-write-xml.o ../../gettext-runtime/intl/msgfmt-hash-string.o gettext.res  ./.libs/libgettextsrc.dll.a -L/mingw64/lib /d/Temp/mingw-w64-gettext/src/build-x86_64-w64-mingw32/gettext-tools/gnulib-lib/.libs/libgettextlib.dll.a -lncurses /d/Temp/mingw-w64-gettext/src/build-x86_64-w64-mingw32/gettext-tools/intl/.libs/libintl.dll.a -liconv -L/mingw64/lib
libtool: link: x86_64-w64-mingw32-gcc -march=x86-64 -mtune=generic -O2 -pipe -pipe -Wl,--disable-auto-import -o .libs/msgunfmt.exe msgunfmt-msgunfmt.o msgunfmt-read-mo.o msgunfmt-read-java.o msgunfmt-read-csharp.o msgunfmt-read-resources.o msgunfmt-read-tcl.o gettext.res  ./.libs/libgettextsrc.dll.a -L/mingw64/lib /d/Temp/mingw-w64-gettext/src/build-x86_64-w64-mingw32/gettext-tools/gnulib-lib/.libs/libgettextlib.dll.a -lncurses /d/Temp/mingw-w64-gettext/src/build-x86_64-w64-mingw32/gettext-tools/intl/.libs/libintl.dll.a -liconv -L/mingw64/lib
libtool: link: x86_64-w64-mingw32-g++ -D__STDC_LIMIT_MACROS -march=x86-64 -mtune=generic -O2 -pipe -pipe -Wl,--disable-auto-import -o .libs/msgmerge.exe ../woe32dll/msgmerge-c++msgmerge.o msgmerge-msgl-fsearch.o msgmerge-lang-table.o msgmerge-plural-count.o gettext.res  ./.libs/libgettextsrc.dll.a -L/mingw64/lib /d/Temp/mingw-w64-gettext/src/build-x86_64-w64-mingw32/gettext-tools/gnulib-lib/.libs/libgettextlib.dll.a -lncurses /d/Temp/mingw-w64-gettext/src/build-x86_64-w64-mingw32/gettext-tools/intl/.libs/libintl.dll.a -liconv -L/mingw64/lib
libtool: link: x86_64-w64-mingw32-g++ -D__STDC_LIMIT_MACROS -march=x86-64 -mtune=generic -O2 -pipe -pipe -Wl,--disable-auto-import -o .libs/msgattrib.exe ../woe32dll/msgattrib-c++msgattrib.o gettext.res  ./.libs/libgettextsrc.dll.a -L/mingw64/lib /d/Temp/mingw-w64-gettext/src/build-x86_64-w64-mingw32/gettext-tools/gnulib-lib/.libs/libgettextlib.dll.a -lncurses /d/Temp/mingw-w64-gettext/src/build-x86_64-w64-mingw32/gettext-tools/intl/.libs/libintl.dll.a -liconv -L/mingw64/lib
collect2.exe: error: ld returned 5 exit status
make[5]: *** [Makefile:2822: msgunfmt.exe] Error 1
```
What makes the issue so special is that when I navigate from an MinGW64 shell into the root build directory and invoke `make -j1` manually, then ~8 out of 10 times it fails with the same error, but at least once or twice in 10 times it does work and link correctly. I repeatedly tested this and the issue seems completely random. I also tried adding a 10x loop around make in `PKGBUILD`, however this never lead to successful compiles.

Furthermore, I could not find any useful information about `ld returned 5 exit status` with google... what does the exit status `5` indicate?

**Comment by mati865** [comment]
Your environment is definitely broken.
Do you have mingw dlfcn installed by any chance?

**Comment by emmenlau** [comment]
No, `pacman --query --quiet|grep dlfcn` returns nothing. Is that good or bad?

**Comment by mati865** [comment]
It's good but cause of the breakage remains undiscovered.
The thing is when your toolchain is faulty it will spread breakage to the other packages.

**Comment by emmenlau** [comment]
After a long debugging period, the most likely cause for my problems is actually a Windows permission problem. I am not certain about this yet, but there have been some spurious errors about "permission denied" i.e. when `qtbinpatcher` was run on qmake. Since I seem to get more errors than most other people I will test on a different computer setup and close all issues until further notice. 

If somebody has insight on Windows user accounts, it would be highly appreciated: I am running continuous integration as a service, using the logon credentials of my actual Windows (GUI) user account. I use the username and password in the system logon. It still seems the build behavior is different from running the CI versus a manual compile from the GUI. Is this possibly a known problem?
