### ISSUE TITLE
clang: boost/thread + boost/dll: Multiple definitions of GetModuleHandleA

### ISSUE THREAD

**Issue by askondro** [Alexpux/MINGW-packages#2247]
I have issues when using these headers in the same compilation unit and compile it with clang++.

```
#include <boost/thread.hpp>
#include <boost/dll.hpp>
```

g++ works OK.

with clang++ I get this error:

clang version 3.9.1 (tags/RELEASE_391/final)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:\msys64\mingw64\bin
 "C:\\msys64\\mingw64\\bin\\clang++.exe" -cc1 -triple x86_64-w64-windows-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name boost_test.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu corei7 -momit-leaf-frame-pointer -v -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -coverage-file "C:\\Users\\askondro\\Documents\\build-untitled-Desktop_Qt_MinGW_w64_64bit_MSYS2-Default\\CMakeFiles\\untitled.dir\\boost_test.cpp.obj" -resource-dir "C:\\msys64\\mingw64\\bin\\..\\lib\\clang\\3.9.1" -internal-isystem "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\include\\c++" -internal-isystem "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\include\\c++\\x86_64-w64-mingw32" -internal-isystem "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\include\\c++\\backward" -internal-isystem "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\include\\c++\\6.3.0" -internal-isystem "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\include\\c++\\6.3.0\\x86_64-w64-mingw32" -internal-isystem "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\include\\c++\\6.3.0\\backward" -internal-isystem "C:\\msys64\\mingw64\\include\\c++\\6.3.0" -internal-isystem "C:\\msys64\\mingw64\\include\\c++\\6.3.0\\x86_64-w64-mingw32" -internal-isystem "C:\\msys64\\mingw64\\include\\c++\\6.3.0\\backward" -internal-isystem "C:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\6.3.0\\include\\c++" -internal-isystem "C:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\6.3.0\\include\\c++\\x86_64-w64-mingw32" -internal-isystem "C:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\6.3.0\\include\\c++\\backward" -internal-isystem "C:\\msys64\\mingw64\\bin\\..\\lib\\clang\\3.9.1\\include" -internal-isystem "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\include" -internal-isystem "C:\\msys64\\mingw64\\include" -Wall -pedantic -std=c++1z -fdeprecated-macro -fdebug-compilation-dir "C:\\Users\\askondro\\Documents\\build-untitled-Desktop_Qt_MinGW_w64_64bit_MSYS2-Default" -ferror-limit 19 -fmessage-length 0 -femulated-tls -fno-use-cxa-atexit -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o "CMakeFiles\\untitled.dir\\boost_test.cpp.obj" -x c++ "C:\\Users\\askondro\\Documents\\untitled\\boost_test.cpp"
clang -cc1 version 3.9.1 based upon LLVM 3.9.1 default target x86_64-w64-windows-gnu
ignoring nonexistent directory "C:\msys64\mingw64\x86_64-w64-mingw32\include\c++"
ignoring nonexistent directory "C:\msys64\mingw64\x86_64-w64-mingw32\include\c++\x86_64-w64-mingw32"
ignoring nonexistent directory "C:\msys64\mingw64\x86_64-w64-mingw32\include\c++\backward"
ignoring nonexistent directory "C:\msys64\mingw64\x86_64-w64-mingw32\include\c++\6.3.0"
ignoring nonexistent directory "C:\msys64\mingw64\x86_64-w64-mingw32\include\c++\6.3.0\x86_64-w64-mingw32"
ignoring nonexistent directory "C:\msys64\mingw64\x86_64-w64-mingw32\include\c++\6.3.0\backward"
ignoring nonexistent directory "C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\6.3.0\include\c++"
ignoring nonexistent directory "C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\6.3.0\include\c++\x86_64-w64-mingw32"
ignoring nonexistent directory "C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\6.3.0\include\c++\backward"
#include "..." search starts here:
#include <...> search starts here:
 C:\msys64\mingw64\include\c++\6.3.0
 C:\msys64\mingw64\include\c++\6.3.0\x86_64-w64-mingw32
 C:\msys64\mingw64\include\c++\6.3.0\backward
 C:\msys64\mingw64\bin\..\lib\clang\3.9.1\include
 C:\msys64\mingw64\x86_64-w64-mingw32\include
 C:\msys64\mingw64\include
End of search list.
In file included from C:\Users\askondro\Documents\untitled\boost_test.cpp:5:
In file included from C:\msys64\mingw64\include\boost/dll.hpp:16:
In file included from C:\msys64\mingw64\include\boost/dll/shared_library.hpp:24:
In file included from C:\msys64\mingw64\include\boost/dll/detail/windows/shared_library_impl.hpp:12:
In file included from C:\msys64\mingw64\include\boost/dll/shared_library_load_mode.hpp:17:
C:\msys64\mingw64\include\boost/detail/winapi/dll.hpp:47:1: error: functions that differ only in their return type cannot be overloaded
GetModuleHandleA(boost::detail::winapi::LPCSTR_ lpFileName);
^
C:\msys64\mingw64\include\boost/thread/win32/thread_primitives.hpp:176:55: note: previous declaration is here
                __declspec(dllimport) void* __stdcall GetModuleHandleA(char const*);
                                      ~~~~~           ^
In file included from C:\Users\askondro\Documents\untitled\boost_test.cpp:5:
In file included from C:\msys64\mingw64\include\boost/dll.hpp:16:
In file included from C:\msys64\mingw64\include\boost/dll/shared_library.hpp:24:
In file included from C:\msys64\mingw64\include\boost/dll/detail/windows/shared_library_impl.hpp:12:
In file included from C:\msys64\mingw64\include\boost/dll/shared_library_load_mode.hpp:17:
C:\msys64\mingw64\include\boost/detail/winapi/dll.hpp:82:1: error: functions that differ only in their return type cannot be overloaded
GetProcAddress(boost::detail::winapi::HMODULE_ hModule, boost::detail::winapi::LPCSTR_ lpProcName);
^
C:\msys64\mingw64\include\boost/thread/win32/thread_primitives.hpp:196:59: note: previous declaration is here
                __declspec(dllimport) farproc_t __stdcall GetProcAddress(void *, const char *);
                                      ~~~~~~~~~           ^

**Comment by mati865** [comment]
Currently Clang is having issues even with much simpler headers. Sometimes changing dialect from c++ to gnu++ helps but I doubt it will in this case.

I'm waiting for upstream to accept patches and then I'll try to get their help with mingw issues.
