### ISSUE TITLE
ipython2 missing dependency backports.shutil_get_terminal_size

### ISSUE THREAD

**Issue by aconverse** [Alexpux/MINGW-packages#2251]
ipython2 version 5.3.0-1 seems to be missing the dependency backports.shutil_get_terminal_size

$ ipython2
Traceback (most recent call last):
  File "C:/msys64/mingw64/bin/ipython2", line 4, in <module>
    from IPython import start_ipython
  File "C:/msys64/mingw64/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "C:/msys64/mingw64/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "C:/msys64/mingw64/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "C:/msys64/mingw64/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "C:/msys64/mingw64/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named backports.shutil_get_terminal_size

I'm not sure what package (if any) provides backports.shutil_get_terminal_size

Here's what I have installed:
Alex@machine MSYS ~
$ pacman -Qs  python2
local/mingw-w64-x86_64-python2 2.7.13-1
    A high-level scripting language (mingw-w64)
local/mingw-w64-x86_64-python2-decorator 4.0.11-1
    Better living through Python with decorators (mingw-w64)
local/mingw-w64-x86_64-python2-enum34 1.0.4-1
    Python 3.4 Enum backported to 3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4
    (mingw-w64)
local/mingw-w64-x86_64-python2-ipython 5.3.0-1
    An enhanced Interactive Python shell (mingw-w64)
local/mingw-w64-x86_64-python2-ipython_genutils 0.1.0-1
    IPython vestigial utilities (mingw-w64)
local/mingw-w64-x86_64-python2-numpy 1.11.2-1
    Scientific tools for Python (mingw-w64)
local/mingw-w64-x86_64-python2-path 10.1-1
    File system based database that uses python pickles (mingw-w64)
local/mingw-w64-x86_64-python2-pickleshare 0.7.4-1
    File system based database that uses python pickles (mingw-w64)
local/mingw-w64-x86_64-python2-prompt_toolkit 1.0.9-1
    Library for building powerful interactive command lines in Python
local/mingw-w64-x86_64-python2-pygments 2.1.3-1
    Python syntax highlighter (mingw-w64)
local/mingw-w64-x86_64-python2-scipy 0.18.1-1
    SciPy is open-source software for mathematics, science, and engineering.
    (mingw-w64)
local/mingw-w64-x86_64-python2-setuptools 31.0.0-1
    Easily download, build, install, upgrade, and uninstall Python packages
    (mingw-w64)
local/mingw-w64-x86_64-python2-simplegeneric 0.8.1-1
    File system based database that uses python pickles (mingw-w64)
local/mingw-w64-x86_64-python2-six 1.10.0-1
    Python 2 and 3 compatibility utilities (mingw-w64)
local/mingw-w64-x86_64-python2-traitlets 4.3.2-1
    A lightweight Traits like module (mingw-w64)
local/mingw-w64-x86_64-python2-wcwidth 0.1.7-1
    Measures number of Terminal column cells of wide-character codes
local/mingw-w64-x86_64-python2-win_unicode_console 0.5-1
    Measures number of Terminal column cells of wide-character codes
local/python2 2.7.13-1
    A high-level scripting language

**Comment by lazka** [comment]
ipykernel depends on python2-backports.shutil_get_terminal_size now

Looks like this was fixed in cd52bfec2694fb2d59116
