### ISSUE TITLE
libzip is missing zipconf.h header

### ISSUE THREAD

**Issue by int19h** [Alexpux/MINGW-packages#2254]
After installing mingw-w64-libzip, I cannot compile any code that does `#include "zip.h"` (which comes from that library), because that header in turn does `#include <zipconf.h>` - which is not installed in /mingw64/include.

Looking at the PKGBUILD for the package, it appears that it had a line that should address this:
https://github.com/Alexpux/MINGW-packages/blob/7d616ce3e4a490088d4e7e3c1925c3d5b9bd960d/mingw-w64-libzip/PKGBUILD#L45

However, it is commented out. After doing the same exact operation manually, I can compile successfully.

So it would seem that the PKGBUILD just needs to have that line uncommented. I'm not sure why it was commented in the first place - looking at history, it appears that it was already commented out in the initial commit for the package.

**Comment by peterbud** [comment]
I guess because `ln `creates a symbolic link, and that is not really supported today on Windows. I believe a simply file copy would do the trick in the package, but I'm not the maintainer, so it should be done by somebody who can actually test that it will work later.

**Comment by int19h** [comment]
I actually used `ln` and it worked for me. I checked it again now, and it looks like in MSYS, `ln` just copies the file. So it appears that uncommenting the line would do the trick.

Does this need to be done by the maintainer? I can test and create a PR otherwise.

**Comment by peterbud** [comment]
It's a community effort, absolutely OK if you test the change and then create a PR (which closes this issue)

**Comment by int19h** [comment]
Here's the PR.

https://github.com/Alexpux/MINGW-packages/pull/2362
