### ISSUE TITLE
mingw-w64-ca-certificates 20170211-1 fails with failed sha256

### ISSUE THREAD

**Issue by emmenlau** [Alexpux/MINGW-packages#2261]
It fails in the sha for StartSSL.sub.class1.server.ca.pem. I tried to fix it but I'm not sure what the contents of this file should be. When I download (as of now) the file has only a single line with the
text `class1/sha2/pem/sub.class1.server.sha2.ca.pem`. This seems wrong?
The error in building I get is:
```
==> Validating source files with sha256sums...
    certdata.txt ... Passed
    nssckbi.h ... Passed
    StartSSL.sub.class1.server.ca.pem ... FAILED
    certdata2pem.py ... Passed
    trust-fixes ... Passed
    update-ca-trust ... Passed
    update-ca-trust.8 ... Passed
==> ERROR: One or more files did not pass the validity check!
```

**Comment by galeksandrp** [comment]
Fixed in 20170211-2 https://github.com/Alexpux/MINGW-packages/commit/20c98433e8b20ae16ce1a637c7b8637cbf95cfc2
