### ISSUE TITLE
Building libtxc_dxtn for Windows 32-bit

### ISSUE THREAD

**Issue by pal1000** [Alexpux/MINGW-packages#2271]
I attempted to build libtxc_dxtn as requested by some guy but unfortunately it doesn't work.
I tried both [release 1.0.1](https://people.freedesktop.org/~cbrill/libtxc_dxtn/libtxc_dxtn-1.0.1.tar.bz2) and master: git://people.freedesktop.org/~mareko/libtxc_dxtn , but both x86_64-w64-mingw32-gcc and x86_64-w64-mingw32-g++ produced invalid code.  There is also an autoconf build, but that seams to only produce linux code.
The tarball must be extracted in mesa-**version**/include. That's right, it depends on Mesa codebase.

**Comment by emmenlau** [comment]
I found some `libtxc_dxtn` websites online but they seem to be about 7 years old and not maintained anymore. Is this the `libtxc_dxtn` you are referring to? It seems a bit tricky to approach this problem.

**Comment by pal1000** [comment]
Well, the code was last updated in 2015, stable release came in 2011. There is also an alternative called [libtxc_dxtn_s2tc](https://github.com/divVerent/s2tc) which was built by cygwin, but that one is unstable and buggy, possibly it was compiled with old Mesa3D components, it also got updated since it was built by cygwin with many fixes /improvements.  @lowenz complained about poor performance with libtxc_dxtn_s2tc cygwin build [here](http://forums.thedarkmod.com/topic/17867-compiled-llvmpipesoftpipe-for-windows/page-2#entry403038).

**Comment by pal1000** [comment]
This is the command I use to build;
`x86_64-w64-mingw32-gcc -v txc_dxtn.h -o dxtn.dll`

**Comment by pal1000** [comment]
Succeeded build for x64. Had to create a shared library to solve undefined reference to WinMain
This command produced a working 64-bit DLL

`x86_64-w64-mingw32-gcc -shared -v txc_dxtn.h txc_compress_dxtn.c txc_fetch_dxtn.c -I /c/Software/Development/projects/mesa/mesa/include -Wl,--dll,--dynamicbase,--enable-auto-image-base -o dxtn.dll`

I'll try 32-bit soon.

**Comment by pal1000** [comment]
Unfortunately, the 32-bit build with i686-w64-mingw32-gcc does not work. GL_EXT_texture_compression_s3tc is not available.

**Comment by pal1000** [comment]
I was successful by building with standalone mingw-w64-i686. You definitely have a problem with mingw-w64-i686-toolchain. Also the DLL resulted was much smaller - 59 KB with standalone mingw vs 292 KB with your toolchain. The DLL builds apparently successful, but when I use it, S3 texture compression is not exposed. Tested with both PPSSPP 32-bit and Aida64 Engineer.

## How to reproduce
###Prerequisites
- [PPSSPP 32-bit](http://buildbot.orphis.net/ppsspp/) and / or Aida64 Engineer. GPU Caps Viewer is also an option, but take note of [this](http://www.geeks3d.com/forums/index.php/topic,4899.0.html)
 - Mesa 3D 32-bit driver. Your build does not work (#2089). Instead you can use [my build](https://github.com/pal1000/mesa-dist-win/releases) or [QT bild](http://download.qt.io/development_releases/prebuilt/llvmpipe/windows/opengl32sw-32-mesa_12_0_rc2.7z).
- Mesa3D source code: ftp://ftp.freedesktop.org/pub/mesa/
- libtxc_dxtn source code:  git://people.freedesktop.org/~mareko/libtxc_dxtn

###Steps to reproduce
- Build libtxc_dxtn with a command that looks like this:

`x86_64-w64-mingw32-gcc -shared -v txc_dxtn.h txc_compress_dxtn.c txc_fetch_dxtn.c -I /c/Software/Development/projects/mesa/mesa/include -Wl,--dll,--dynamicbase,--enable-auto-image-base -o dxtn.dll`

Make sure to update -I parameter path to point to the correct location of mesa source code include sub-folder
- drop dxtn,dll and opengl32.dll where the application exe to test with is located (qt devs renamed their build to opengl32sw.dll)
- With Aida64 browse to Display - OpenGL.  With PPSSPP go to Settings - Tools - System Information - OGL Extensions,
- With both pieces of software you'll have to scroll down until you find, or rather don't find GL_EXT_texture_compresion_s3tc. Fortunately most extensions are sorted alphabetically, there are just a few exceptions, but they appear near the end of the list, after GL_EXT_texture_compresion_s3tc.
-

**Comment by pal1000** [comment]
I am happy to report that this is no longer an issue. Got a perfectly working binary with mingw-w64-i686-toolchain. I think the fix landed with the upgrade to GCC 7.2.0.
