### ISSUE TITLE
qtbinpatcher sources away, github page down

### ISSUE THREAD

**Issue by emmenlau** [Alexpux/MINGW-packages#2277]
Does somebody have the sources for `qtbinpatcher` version `2.2.0`? I found the github page is down, and the official website is also down. Maybe somebody knows where to get them, and could put them on some public mirror (or send them to me)?

**Comment by Alexpux** [comment]
need get qtbunpatcher from source package from our repository

**Comment by mati865** [comment]
http://repo.msys2.org/mingw/sources/

**Comment by emmenlau** [comment]
Ah, thanks! Fixed by PR https://github.com/Alexpux/MINGW-packages/pull/2280
