### ISSUE TITLE
mingw-w64-libspectre does not build

### ISSUE THREAD

**Issue by emmenlau** [Alexpux/MINGW-packages#2287]
I get the following error when trying to build current `mingw-w64-libspectre`:
```
In file included from ../../libspectre-0.2.8/libspectre/spectre-status.c:21:0:
../../libspectre-0.2.8/libspectre/spectre-status.h:24:39: fatal error: libspectre/spectre-macros.h: No such file or directory
 #include <libspectre/spectre-macros.h>
```
Please find the full build log here: http://data.biodataanalysis.de/tmp/buildlogs/1489336043-mingw-w64-libspectre-buildlog.txt

**Comment by galeksandrp** [comment]
Seems that out-of-source build not working for 0.2.8 #2287
