### ISSUE TITLE
Portaudio: using --enable-static has no effect

### ISSUE THREAD

**Issue by bagong** [Alexpux/MINGW-packages#2317]
If I grep the configure part of the log for static, it says:

$ cat mingw-w64-portaudio-190600_20161030-1-i686-build.log | grep static
checking if i686-w64-mingw32-gcc static flag -static works... yes
checking whether to build static libraries... yes
checking if i686-w64-mingw32-g++ static flag -static works... yes

But in the end no libportaudio.a file, just libportaudio.dll.a and .dll

**Comment by bagong** [comment]
I tried building with autotools under msys2/mingw64 and got the same result:
Looking at:
 ````
/bin/sh ./libtool --mode=link gcc -o bin/paqa_latency -g -O2 -DPA_LITTLE_ENDIAN -I../../include -I../../src/common -I../../src/os/win -DPA_USE_WMME=0 -DPA_USE_ASIO=0 -DPA_USE_WDMKS=0 -DPA_USE_DS=0 -DPA_USE_WASAPI=0 -UPA_USE_WMME -DPA_USE_WMME=1 -mthreads -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DSIZEOF_SHORT=2 -DSIZEOF_INT=4 -DSIZEOF_LONG=4 -DHAVE_CLOCK_GETTIME=1 -DHAVE_NANOSLEEP=1 ../../qa/paqa_latency.c lib/libportaudio.la -lwinmm -lm -lole32 -luuid
`````
the enable-static/shared info seems not to be passed in, and it only builds with defaults? Does this make sense? Should this be reported upstream?

**Comment by bagong** [comment]
I remember though having build with mingw native and cmake some time ago actually worked. But I need the mingw/msys version ;)

**Comment by mati865** [comment]
Could be this: https://github.com/Alexpux/MINGW-packages/commit/2e5076aba39971f3fb9f35379b034fac2c7af34a#diff-1404cdeadd737f24c66de19c44c6d1f4L55

**Comment by bagong** [comment]
Yes, I actually did try cmake, and it worked, also within the msys-mingw environment. I think the  patch you refer to was removed because it doesn't apply to the newer version.

Using cmake, a static library (and dynamic) is built, called portaudio-static.a Interestingly, while the library is there, it is not "installed", and it uses this non-standard name.

The current state of build options seems to be:

- wmme and wdmks work out of the box
- asio works if the asio-sdk is supplied
- wasapi is broken (known bug, would require a mingw expert to fix, the author failed ;) )
- directx/dsound works if 
    a) one carefully directs all paths (lib, include etc) into the area where mingw dsound resides (uning the MS sdk will not work)
    b) one switches off PA_USE_DIRECTSOUNDFULLDUPLEXCREATE

cmake seems to be the better supported build now on Windows, even when using MinGW. But PKGBUILD can't provide a wrapper for cmake, right?

**Comment by mati865** [comment]
> But PKGBUILD can't provide a wrapper for cmake, right?

I don't know why you think so, look at amount of packages using cmake: https://github.com/Alexpux/MINGW-packages/search?utf8=%E2%9C%93&q=%24%7BMINGW_PACKAGE_PREFIX%7D-cmake&type=Code
Even big (huge?) projects like LLVM and friends are successfully build with CMake: https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-clang/PKGBUILD#L272

**Comment by bagong** [comment]
I didn't think so, I just wondered. So I think moving the portaudio PKGBUILD from autotools to cmake might be a good move...

**Comment by bagong** [comment]
This patch fixes the WASAPI-build using MinGW. Most of it still applies to the current PA release:

https://github.com/mxe/mxe/commit/eb65c9cdb60161e5e96e6f4d9fdf2b9adb9a2cb6

It also enhances the dsound backend a bit. PA_USE_DIRECTSOUNDFULLDUPLEXCREATE still needs to be set off, but all backends build!

**Comment by bagong** [comment]
A more recent patch applies to current PA:
https://github.com/mxe/mxe/blob/9a5b34cf036fcee967b94f30ceae120e23709e42/src/portaudio-1-fixes-crlf.patch

**Comment by mati865** [comment]
You can open PR with the patch.

**Comment by bagong** [comment]
Too busy with other stuff atm, sorry...
Just thought the info might be useful.

**Comment by elieux** [comment]
Reopening - this issue is not yet resolved.
