### ISSUE TITLE
Does mingw-w64-python3-cairo really makedepend on python3, not mingw-w64-python3?

### ISSUE THREAD

**Issue by emmenlau** [Alexpux/MINGW-packages#2318]
I stumbled accross the PKGBUILD from `mingw-w64-python3-cairo`, it would like to install
`python3` as a make-dependency. I am a bit surprised, since it already depends on
`mingw-w64-python3`, does it really use msys `python3` for building? I'm just checking if this
is a typing error, but its really all fine for me...

**Comment by mati865** [comment]
It already downloads mingw python3 because it is dependency so msys/python3 isn't used at all.

**Comment by emmenlau** [comment]
Ok great, I will remove `makedepend=('python3')` and make a PR
