### ISSUE TITLE
gtk3-demo.exe crash: cairo_win32_scaled_font_select_font:SelectObject: The handle is invalid.

### ISSUE THREAD

**Issue by komlevv** [Alexpux/MINGW-packages#2325]
c:\msys64\mingw64\bin\gtk3-demo.exe
win7 x64
mingw64/mingw-w64-x86_64-gtk3 3.22.9-1

gtk3-demo.exe crashes when i try to run `Pango` -> `Font Features` demo
with following error msg in cmd.exe:
`cairo_win32_scaled_font_select_font:SelectObject: The handle is invalid.`

appcrash output:
```
Problem Event Name:	APPCRASH
  Application Name:	gtk3-demo.exe
  Application Version:	0.0.0.0
  Application Timestamp:	00000000
  Fault Module Name:	libharfbuzz-0.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	000000000003b857
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	02ad
  Additional Information 2:	02ad0939abc1b38817a67f01cd7d3c6c
  Additional Information 3:	27d0
  Additional Information 4:	27d086b2354f82ed31f1830b70c524de
```

**Comment by Alexpux** [comment]
Does it still present with latest gtk3 package?

**Comment by johny-bravo** [comment]
i've updated to `http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gtk3-3.22.10-1-any.pkg.tar.xz`, same issue

**Comment by db0451** [comment]
fwiw, can confirm

this bt is next to useless, but just in case it can help somehow:

`cairo_win32_scaled_font_select_font:SelectObject: The handle is invalid.

Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000006163b857 in ?? () from /mingw64/bin/libharfbuzz-0.dll
(gdb) bt
#0  0x000000006163b857 in ?? () from /mingw64/bin/libharfbuzz-0.dll
#1  0x000000006163b974 in ?? () from /mingw64/bin/libharfbuzz-0.dll
#2  0x000000000041e003 in ?? ()
#3  0x000000000041e6f3 in ?? ()
#4  0x000000000041f52e in ?? ()
#5  0x000000000041f602 in ?? ()
#6  0x0000000063a4611c in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#7  0x0000000063a57025 in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#8  0x0000000063a5f01d in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#9  0x0000000063a5f288 in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#10 0x00000000666da669 in ?? () from /mingw64/bin/libgtk-3-0.dll
#11 0x00000000666e3ad8 in ?? () from /mingw64/bin/libgtk-3-0.dll
#12 0x000000006b744797 in ?? () from /mingw64/bin/libffi-6.dll
#13 0x000000006b7443a7 in ?? () from /mingw64/bin/libffi-6.dll
#14 0x0000000063a46cd8 in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#15 0x0000000063a46347 in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#16 0x0000000063a5ed86 in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#17 0x0000000063a5f288 in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#18 0x00000000665610fb in ?? () from /mingw64/bin/libgtk-3-0.dll
#19 0x0000000063a4888e in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#20 0x0000000063a46347 in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#21 0x0000000063a5ed86 in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#22 0x0000000063a5f288 in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#23 0x000000006655e029 in ?? () from /mingw64/bin/libgtk-3-0.dll
#24 0x000000006655f47e in ?? () from /mingw64/bin/libgtk-3-0.dll
#25 0x000000006656237f in ?? () from /mingw64/bin/libgtk-3-0.dll
#26 0x000000006652f345 in ?? () from /mingw64/bin/libgtk-3-0.dll
#27 0x00000000666f3beb in ?? () from /mingw64/bin/libgtk-3-0.dll
#28 0x00000000665ab695 in ?? () from /mingw64/bin/libgtk-3-0.dll
#29 0x0000000063a46347 in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#30 0x0000000063a5e972 in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#31 0x0000000063a5f288 in ?? () from /mingw64/bin/libgobject-2.0-0.dll
#32 0x00000000666f5d2e in ?? () from /mingw64/bin/libgtk-3-0.dll
#33 0x00000000665a83cd in ?? () from /mingw64/bin/libgtk-3-0.dll
#34 0x00000000665aa5a4 in ?? () from /mingw64/bin/libgtk-3-0.dll
#35 0x0000000070ecdb09 in ?? () from /mingw64/bin/libgdk-3-0.dll
#36 0x0000000070ef8e90 in ?? () from /mingw64/bin/libgdk-3-0.dll
#37 0x00000000685f2231 in ?? () from /mingw64/bin/libglib-2.0-0.dll
#38 0x00000000685f2418 in ?? () from /mingw64/bin/libglib-2.0-0.dll
#39 0x00000000685f264d in ?? () from /mingw64/bin/libglib-2.0-0.dll
#40 0x000000006d5e88e2 in ?? () from /mingw64/bin/libgio-2.0-0.dll
#41 0x0000000000429e3b in ?? ()
#42 0x00000000004013f8 in ?? ()
#43 0x000000000040151b in ?? ()
#44 0x00000000774559cd in KERNEL32!BaseThreadInitThunk () from /c/Windows/system32/kernel32.dll
#45 0x000000007768a561 in ntdll!RtlUserThreadStart () from /c/Windows/SYSTEM32/ntdll.dll
#46 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)`
