### ISSUE TITLE
MINGW-packages gtk-doc is not in the repos, and need update to 1.25.

### ISSUE THREAD

**Issue by ehoffman2** [Alexpux/MINGW-packages#2328]
Hello

The repos (http://repo.msys2.org) does not have the MINGW version of gtk-doc.  It's there in the MSYS, but not MINGW.

Moreover, the GIT-master version of the gtk-doc for MINGW is still at 1.21 (while the MSYS version is fetching 1.25).

Because of this, although the MSYS version is working fine in mingw64 environment, 3rd-party packages/applications compiled under mingw (mingw-w64 for example) relying on gtk-doc fail to find the dependency when using pkg-config, since the only version available is the MSYS version (and pkg-config, when run under mingw64, will not see the MSYS-installed version of gtk-doc).

Regards,
Eric

**Comment by Alexpux** [comment]
There are no mingw version of gtk-doc package because it need to run perl package. But mingw perl is not usable.

**Comment by ehoffman2** [comment]
Ok, that's the reason!  One thing however, when you say that it needs to run perl, I guess that it means that gtk-doc uses perl at runtime, rather than being a dependency to compile gtk-doc, right?

If so, would gtk-doc still be usable if you do install the MSYS version of perl?

gtk-doc probably will not be something that will be distributed with an application compiled under MinGW (and expected to run afterward standalone on a MinGW-less Windows environment), but rather a tool used during the compilation (probably 99% of the time).  So in most cases, the philosophy of distributing a native Windows application still hold.  gtk-doc in itself would still be a native Windows application (even if for all practical purpose, it does not bring any added value since gtk-doc will only be used during compilation of a 3rd party MinGW package/program, within a MSYS shell).  However, this will prevent breaking 3rd party packages/programs dependencies to gtk-doc.

It's kind of similar to the base-devel meta-package (libtools and others), which are available under MSYS only (which is definitely not distributed along with the MinGW-compiled program).

I may be wrong though :-)

Eric

**Comment by lazka** [comment]
gtk-doc is currently being ported to python: https://mail.gnome.org/archives/desktop-devel-list/2017-March/msg00113.html

**Comment by lazka** [comment]
See #2911

**Comment by lazka** [comment]
This can be closed.
