### ISSUE TITLE
New mingw-w64-libwebp broke mingw-w64-qtwebkit

### ISSUE THREAD

**Issue by omichel** [Alexpux/MINGW-packages#2330]
mingw-w64-qtwebkit package should be rebuilt against libwebp-0.6.0 as it has a dependency:

Qt5WebKit.dll depends on libwebp-6.dll, but libwebp-0.6.0 provide only libwebp-7.dll

**Comment by bagong** [comment]
+1

**Comment by Alexpux** [comment]
Will upload new packages today.

**Comment by omichel** [comment]
That works! Thank you @Alexpux!

**Comment by bagong** [comment]
Thanks!
