### ISSUE TITLE
ghc fails to build

### ISSUE THREAD

**Issue by ncihnegn** [Alexpux/MINGW-packages#2336]
/bin/sh: line 1:  8640 Segmentation fault      "/home/ncihnegn/MINGW-packages/mingw-w64-ghc/src/x86_64/host/bin/ghc.exe" -hisuf hi -osuf o -hcsuf hc -static -O -H64m -Wall -package-db libraries/bootstrapping.conf -this-unit-id ghc-8.0.2 -hide-all-packages -i -icompiler/basicTypes -icompiler/cmm -icompiler/codeGen -icompiler/coreSyn -icompiler/deSugar -icompiler/ghci -icompiler/hsSyn -icompiler/iface -icompiler/llvmGen -icompiler/main -icompiler/nativeGen -icompiler/parser -icompiler/prelude -icompiler/profiling -icompiler/rename -icompiler/simplCore -icompiler/simplStg -icompiler/specialise -icompiler/stgSyn -icompiler/stranal -icompiler/typecheck -icompiler/types -icompiler/utils -icompiler/vectorise -icompiler/stage1/build -icompiler/stage1/build/autogen -Icompiler/stage1/build -Icompiler/stage1/build/autogen -Icompiler/. -Icompiler/parser -Icompiler/utils -Icompiler/stage1 -optP-include -optPcompiler/stage1/build/autogen/cabal_macros.h -package-id Win32-2.3.1.1 -package-id array-0.5.1.1 -package-id base-4.9.1.0 -package-id binary-0.8.3.0 -package-id bytestring-0.10.8.1 -package-id containers-0.5.7.1 -package-id deepseq-1.4.2.0 -package-id directory-1.3.0.0 -package-id filepath-1.4.1.1 -package-id ghc-boot-8.0.2 -package-id ghc-boot-th-8.0.2 -package-id hoopl-3.10.2.1 -package-id hpc-0.6.0.3 -package-id process-1.4.3.0 -package-id template-haskell-2.11.1.0 -package-id time-1.6.0.1 -package-id transformers-0.5.2.0 -Wall -fno-warn-name-shadowing -this-unit-id ghc -XHaskell2010 -DSTAGE=1 -O -no-user-package-db -rtsopts -odir compiler/stage1/build -hidir compiler/stage1/build -stubdir compiler/stage1/build -c compiler/nativeGen/X86/Ppr.hs -o compiler/stage1/build/X86/Ppr.o
make[1]: *** [compiler/ghc.mk:584: compiler/stage1/build/X86/Ppr.o] Error 139

**Comment by revelator** [comment]
Theres a bug in the downloaded gcc wrappers if compiling on any OS newer than win7 (something about an api change), i had the same problem but after a rather exhaustive google search i came across a thread at the ghc forums mentioning this bug and a fix by downloading and replacing the fixed gcc wrappers. After that it built without any problems. Sadly i cant provide a link because its a while back so you will probably have to search it yourself :(
