### ISSUE TITLE
Integrate the patch for ld horrible #21274  bug

### ISSUE THREAD

**Issue by awson** [Alexpux/MINGW-packages#2350]
Some time ago I faced [an egregious bug in ld](https://sourceware.org/bugzilla/show_bug.cgi?id=21274).

Finally I proposed [the simplest patch possible](https://sourceware.org/bugzilla/attachment.cgi?id=9920&action=diff), which is coherent with the current name length limit handling approach in PECOFF-related binutils code.

Unfortunately, dear mr. Alan Modra have decided to take the opportunity and overhaul the whole approach, going from fixed 4096 bytes long buffers + overflow panic to unlimited name length support. Thus no solution at all has landed still.

I didn't tested his solution yet. For my personal taste, this solution is an overkill since it adds quite a bit of code and make things slower for only to resolve yet non-existing problem.

Could we, then, integrate my simplest patch into the MSys2 binutils build?

Or if someone wants to test mr. Modra's patch and report this to binutils bugzilla it would be perfectly OK too.

**Comment by mingwandroid** [comment]
Thanks for the pointers. Could you not try Alan's patch within MSYS2 using makepkg-mingw and purpose a PR if it fixes your issue (and doesn't seem to break building a few other C++ packages)?

**Comment by lazka** [comment]
From what I see in the upstream bug report this should be fixed in 2.29, and we are at 2.29.1 now.
