### ISSUE TITLE
The chipmunk package is far out of date!

### ISSUE THREAD

**Issue by ninepillars** [Alexpux/MINGW-packages#2352]
chipmunk package is needed for some game engines, such as cocos2d-x.

current version in msys2 is 6.2, but the newest version should be 7.0! with many new functions.

the newest cocos2d-x ( version 3.14.1 ) needs chipmunk version 7.0.

**Comment by hcorion** [comment]
Hah, funny. Apparently chipmunk was downgraded from 7 just because cocos2d-x didn't support the latest version of chipmunk7 at the time.
https://github.com/Alexpux/MINGW-packages/commit/5bd2f218dacd285812c7496be7f072fb6601cdb8

**Comment by lazka** [comment]
chipmunk is at 7.0.1 now (see #2370)
