### ISSUE TITLE
mingw-w64-glib2 doesn't install documentation

### ISSUE THREAD

**Issue by liberforce** [Alexpux/MINGW-packages#2355]
It seems the gtk-doc documentation is not installed, which makes it not show in the devhelp help browser. It should either pass the --enable-gtk-doc argument to the configure script or have a specific package of pre-compiled docs.

**Comment by mati865** [comment]
Duplicate of https://github.com/Alexpux/MINGW-packages/issues/2328

**Comment by lazka** [comment]
mingw-w64-glib2 in the repo includes documentation now
