### ISSUE TITLE
GCC doesn't come with stdlib, how can I get these libraries?

### ISSUE THREAD

**Issue by abcdefghi123456789** [Alexpux/MINGW-packages#2365]
I am trying to compile a simple c++ file and I am getting the error saying that it cannot find iostream,
I search msys64 installation directory and it isn't wrong, no header with that name in there. I followed the instructions on msys2.org. Any help?

**Comment by mati865** [comment]
Both `mingw-w64-i686-gcc` and `mingw-w64-x86_64-gcc` depends on `mingw-w64-i686-gcc-libs` or `mingw-w64-x86_64-gcc-libs` so there is no way GCC could come without libstdc++.

**Comment by elieux** [comment]
@abcdefghi123456789, post your source file, your compilation command and the error you're seeing.

**Comment by mati865** [comment]
@elieux, close due to lack of feedback?
