### ISSUE TITLE
codelite crashes when attempting to open any file

### ISSUE THREAD

**Issue by fspeech** [Alexpux/MINGW-packages#238]
Codelite crashes if I attempt to open any file. I was able to import a project and the source files seem to have been imported correctly. However if I attempt to open any file it just crashes. This happened with the last version as well as the latest version. I have refreshed my system (pacman -Syu) and installed the latest release: 
```
$ pacman -Qs codelite
local/mingw-w64-i686-codelite-git 6.1.1.144.g4609eb0-1
```

**Comment by Alexpux** [comment]
Does latest package work for you?

**Comment by fspeech** [comment]
It appears to work now. Thanks!
