### ISSUE TITLE
Compiler does not find pty.h

### ISSUE THREAD

**Issue by tuhlmann** [Alexpux/MINGW-packages#2383]
I'm trying to compile a graphical terminal for msys2/mingw64. I thought pangoterm might be a good place to start (http://www.leonerd.org.uk/code/pangoterm/)

I installed `msys2-devel` and the other mentioned packages from https://github.com/msys2/msys2/wiki/Contributing-to-MSYS2

I cloned the MINGW-packages repo and installed libvterm-bzr

Now when compiling pangoterm it complains it can't find `pty.h` but the file is there in `/usr/include`, and for some reason it's not part of the gcc include path, which is:

```
$ echo | gcc -E -Wp,-v -
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "<stdin>"
ignoring duplicate directory "C:/msys/mingw64/lib/gcc/../../lib/gcc/x86_64-w64-mingw32/6.3.0/include"
ignoring nonexistent directory "C:/building/msys64/mingw64/include"
ignoring nonexistent directory "/mingw64/include"
ignoring duplicate directory "C:/msys/mingw64/lib/gcc/../../lib/gcc/x86_64-w64-mingw32/6.3.0/include-fixed"
ignoring duplicate directory "C:/msys/mingw64/lib/gcc/../../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/include"
ignoring nonexistent directory "C:/building/msys64/mingw64/x86_64-w64-mingw32/include"
#include "..." search starts here:
#include <...> search starts here:
 C:/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/include
 C:/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../include
 C:/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/include-fixed
 C:/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/include
End of search list.
```
When I add the `/usr/include` path to the CCFLAGS I get a lot of duplicate includes, so I guess that isn't the answer.

I'm running the commands from a MSYS2 64-bit mintty shell.

I guess I'm running into a very noobish error, could you help me figure out what the problem might be?

**Comment by elieux** [comment]
> I'm trying to compile a graphical terminal for msys2/mingw64.

There's the first mistake. :) You need to choose one or the other. The crucial point here is that PTYs are a POSIX concept, so they work only if you target msys2. If you target mingw64, there's Windows Console API. More on that on our [Terminals wikipage](https://github.com/msys2/msys2/wiki/Terminals). Mixing msys2 with mingw64 doesn't work.

If you target msys2, you could get it to work on a similar level as mintty, but you'd probably need to build GTK and X (I don't know if Pangoterm supports other graphical back-ends). If you target mingw64, it won't work due to aforementioned differences unless Pangoterm somehow directly supports Windows.

@mingwandroid tried building Konsole some time ago, but I don't know how that worked out. Anyway, is there anything wrong with mintty, or why is your goal a graphical terminal?

**Comment by mati865** [comment]
@elieux I've got Konsole GUI starting but with mingw-w64 libs so back-end (kpty) was unavailable.
Theoretically we could build static mingw-w64 Konsole and hope it will work with msys2 based KDE Frameworks but it would require duplicating dozens of packages from mingw to msys2.

**Comment by tuhlmann** [comment]
@elieux @mati865 Thanks for the explanation! Yeah I do mix msys2 and mingw concepts.
The main thing I'm missing in mintty is tabs. I got so much used to them in xfce or Gnome console I do not wish to miss them. For now I'm using the Swan desktop (cygwin with X and xfce console) which works pretty nice. Over the weekend I got darktable compiled using mingw64 (https://github.com/darktable-org/darktable/blob/master/packaging/windows/BUILD.txt) and I also saw you have gedit in the repos, so I figured a terminal app couldn't be that far out :)

Thanks again for responding,
Torsten.

**Comment by elieux** [comment]
> I got darktable compiled using mingw64

Would you be interested in making a PKGBUILD for Darktable?

> The main thing I'm missing in mintty is tabs.

I found some possible alternative solutions (below). If you end up trying any of them, please get back to us how you liked it.

- https://superuser.com/questions/264901/is-there-a-multi-tab-terminal-replacement-for-cygwins-terminal/264912
- https://github.com/juho-p/fatty
- https://conemu.github.io/
- http://www.unixmantra.com/2013/04/putty-connection-manager-tabbed-putty.html

**Comment by tuhlmann** [comment]
I can look into creating a PKGBUILD. I know them from Arch Linux, but mostly was a consumer of these.
There are quiet a few manual steps involved in compiling darktable. Aside from having a running Java jvm, I needed to download saxon and xslt processor. Maybe that's only needed for processing the user manual and could be skipped...

When I start with that I'll probably have many questions- what's the best way to ask them?

Regarding the terminal:
For now I'm using ConEmu and finally got it configured in a way it works reasonably similar to a unix console.

Thanks,
Torsten.

**Comment by peterbud** [comment]
I'm maintaining the Windows version/port of `darktable`. It has not been officially released yet, but we are close. `darktable `itself has an standalone installer (which installs all run time dependencies), so that's one option to install it on Windows. We can create a PKGBUILD for that but I guess it would have a limited use - maybe I'm wrong, let me know.
JAVA is not needed to run `darktable`, they are only needed for compiling the usermanuals - BTW it would be great to have OpenJDK as a package for MSYS2...

**Comment by elieux** [comment]
> Aside from having a running Java jvm, I needed to download saxon and xslt processor. Maybe that's only needed for processing the user manual and could be skipped...

If there's a way to avoid Java etc. in the first iteration, I'd say "go for it". Otherwise, it's a matter of creating additional PKGBUILDs for those (downloading binaries is against the goal).

> When I start with that I'll probably have many questions- what's the best way to ask them?

Depends on your options. I personally (and a bunch of other people) hang out mostly on IRC, but there's a mailing list and the GitHub tickets can be used as a discussion as well. Maybe we could open a Gitter chat if that's your favorite. Full list of communication channels on [our homepage](http://www.msys2.org/).

[Our wiki](https://github.com/msys2/msys2/wiki) is a good source of information.

**Comment by elieux** [comment]
@peterbud, so Torsten creating a PKGBUILD for Darktable would be a duplication of efforts?

> We can create a PKGBUILD for that but I guess it would have a limited use - maybe I'm wrong, let me know.

We would welcome having a PKGBUILD for Darktable. It's good to have a choice, especially if one of those is to build from source with one command (meaning `makepkg-mingw`).

**Comment by tuhlmann** [comment]
@peterbud  I just want to say Thank you very much for the hard work you did enabling a darktable build for Windows. I've read the blog posts around this subject and they were less then friendly...

And then of course a Huge Thank You to all you who have put together time and energy to create msys2!

I guess I start by looking at the PKGBUILD for Arch (https://aur.archlinux.org/packages/darktable-git/) and try to convert it and it's dependencies to something along the lines of the BUILD.txt description.

**Comment by peterbud** [comment]
@tuhlmann : it should be fairly easy, just set the right dependencies, and check out the CI script [here](https://github.com/peterbud/darktable/blob/windows-build/ci-script-windows.sh#L59).
You need to set the right install prefix and only you don't need to build the package (installer), but a simple `cmake . --target install` would do the trick IMHO

**Comment by tuhlmann** [comment]
@elieux So I have started a PKGBUILD for mingw-w64-darktable.git and run into a dependency problem.

The dependencies look as follows:

```
depends=("${MINGW_PACKAGE_PREFIX}-exiv2" "${MINGW_PACKAGE_PREFIX}-lcms2"
         "${MINGW_PACKAGE_PREFIX}-lensfun" "${MINGW_PACKAGE_PREFIX}-dbus-glib"
         "${MINGW_PACKAGE_PREFIX}-openexr" "${MINGW_PACKAGE_PREFIX}-sqlite3"
         "${MINGW_PACKAGE_PREFIX}-libxslt" "${MINGW_PACKAGE_PREFIX}-libsoup"
         "${MINGW_PACKAGE_PREFIX}-libwebp" "${MINGW_PACKAGE_PREFIX}-libsecret"
         "${MINGW_PACKAGE_PREFIX}-lua" "${MINGW_PACKAGE_PREFIX}-graphicsmagick"
         "${MINGW_PACKAGE_PREFIX}-openjpeg2" "${MINGW_PACKAGE_PREFIX}-gtk3"
         "${MINGW_PACKAGE_PREFIX}-pugixml" "${MINGW_PACKAGE_PREFIX}-libexif"
         "${MINGW_PACKAGE_PREFIX}-osm-gps-map" "${MINGW_PACKAGE_PREFIX}-libgphoto2"
         "${MINGW_PACKAGE_PREFIX}-drmingw" "${MINGW_PACKAGE_PREFIX}-librsvg"
         "${MINGW_PACKAGE_PREFIX}-flickcurl" "${MINGW_PACKAGE_PREFIX}-gettext")
makedepends=('git' 'base-devel' "${MINGW_PACKAGE_PREFIX}-toolchain" 
             "${MINGW_PACKAGE_PREFIX}-cmake")
```
But running `MINGW_INSTALLS=mingw64 makepkg-mingw -sLf` leads to this error (translated from german):

```
==> Missing Dependencies:
  -> base-devel
  -> mingw-w64-x86_64-toolchain
==> ERROR: Could not resolve all dependencies.

==> ERROR: An unknown error has occurred. Exiting...
```

What am I doing wrong?

**Comment by mati865** [comment]
@tuhlmann You cannot require package groups. And those packages are supposed to be installed anyway so leave only `git` and `${MINGW_PACKAGE_PREFIX}-cmake` in makedepends.

**Comment by tuhlmann** [comment]
Update: I got this one- I removed `base-devel` (it's assumed to already be present says the arch wiki) and replaced toolchain with the 17 contained packages. Let's see if it builds now...

**Comment by tuhlmann** [comment]
@peterbud I'm running into the following problem when compiling the latest darktable from git (master branch, correct?) with a PKGBUILD script:

```
D:/entw/aktuell/forks/MINGW-packages/mingw-w64-darktable-git/src/darktable/build/data/darktable.desktop: error: file contains at least one line ending with a carriage return, while lines should only be separated by a line feed character. First such line is: "[Desktop Entry]"
make[2]: *** [data/CMakeFiles/validate_darktable_desktop.dir/build.make:58: data/CMakeFiles/validate_darktable_desktop] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:7813: data/CMakeFiles/validate_darktable_desktop.dir/all] Fehler 2
```

I checked the generated files on the other installation that I did a few days ago. It also creates CRLF files but doesn't seem to bother, the build went through fine.

Which repo/branch is the best to work against, or is this some problem with my PKGBUILD / msys2 installation?

**Comment by elieux** [comment]
> replaced toolchain with the 17 contained packages

Don't do that. In MINGW-packages, every PKGBUILD needs to assume the respective toolchain is installed on the build machine.

> CRLF

Check if your Git isn't configured to mangle line endings by looking at `darktable.desktop.in`. If not, then maybe the build tool that processes `*.in` is doing it.

**Comment by peterbud** [comment]
Also I'd definitely suggest NOT to use the git version in the PKGBUILD, but wait for and use one of the released versions of the source. Also keep in mind that still there are few changes which were not yet merged to the darktable/master branch.

**Comment by tuhlmann** [comment]
@peterbud So for now, until we have a release, is it safer to compile against the windows-build branch in your repo?

@elieux I will remove the toolchain entries. I did set core.autocrlf = input in my .gitconfig, and `data.darktable.desktop.in` is LF while `build/data.darktable.desktop.in is CRLF`.

**Comment by peterbud** [comment]
Yes, you can test it with my windows-build branch

**Comment by tuhlmann** [comment]
I get the same error on your branch, whether I use makepkg-mingw or compile on the command line.

@elieux 
The problem seems to be with `configure_file(${CMAKE_CURRENT_SOURCE_DIR}/darktable.desktop.in ${CMAKE_CURRENT_BINARY_DIR}/darktable.desktop.in)` and similar in the CMake files. the source file as LF, the dest file gets CRLF.
Should there be a special environment variable set to tell cmake to use Unix line endings?

My cmake is `/mingw64/bin/cmake`

**Comment by peterbud** [comment]
I'm pretty sure the code compiles just fine. You can see the whole normal CI build process [here](https://ci.appveyor.com/project/peterbud/darktable/build/1.0.120)m which uses this [CI script](https://github.com/peterbud/darktable/blob/windows-build/ci-script-windows.sh)

**Comment by tuhlmann** [comment]
@elieux @peterbud I found the problem!
In my msys2_shell.cmd I uncommented `set MSYS2_PATH_TYPE=inherit` in order to access the Windows path in msys. That must have caused cmake to generate CRLF endings. Is that a known issue? Is there a workaround?

I unset this setting and voila, darktable compiles with the makepkg-mingw command.

Peter, is there a way to create a pacman archive instead of an nsis installer executable?

Thanks for your quick replies,
Torsten.

**Comment by peterbud** [comment]
As I have mentioned briefly earlier:
1. Set the `DCMAKE_INSTALL_PREFIX` first. Similar like [here](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-pugixml/PKGBUILD#L33) . 
2. When you build use the `--target install`. That won't create NSIS installer, but just will copy the artifacte to the INSTALL_PREFIX. During `makepkg-mingw` this will result to have all artifacts under the pkg dir, which will be packaged together into a tar.gz

One more: only the 64-bit version will work, the 32-bit won't, so don't build that.

**Comment by tuhlmann** [comment]
Thanks, I read that before but thought it would only install into the target directory, not creating the pacman archive.

I'm running now into an error:

```
 file INSTALL cannot find "C:/msys/mingw64/bin/libwebp-6.dll"
```
On my system (installed just recently) I only have libwebp-7.dll installed. I think I had these issues with the other machine and some more dependencies as well. There I copied libwebp-7.dll to libwebp6-dll (symlinks are replaced with copy in msys, right?) and that worked.

Is that the best way to proceed in PKGBUILD, check if the correct file is there and if not copy it from the newer one?

**Comment by mati865** [comment]
> Is that the best way to proceed in PKGBUILD, check if the correct file is there and if not copy it from the newer one?

`libwebp-6.dll` was replaced by `libwebp-7.dll` in mingw-w64-libwebp update so this package **cannot** with it.
Most likely there is package that needs to be rebuild after mingw-w64-libwebp update, you should be able to find it from logs.

**Comment by tuhlmann** [comment]
I think I need some help installing a prior version of this package.
I went into `MINGW-packages/mingw-w64-libwebp`, restored the previous version 0.5.2 and issued a makepkg-mingw. First problem was
that the PGP key could not be verified:

I went around that with `makepkg-mingw --skippgpcheck` for a testing, then build starts and runs into the following error:

```
dwebp-dwebp.o:dwebp.c:(.text.startup+0x1c1): undefined reference to `ExUtilLoadWebP'
dwebp-dwebp.o:dwebp.c:(.text.startup+0x5e0): undefined reference to `ExUtilDecodeWebPIncremental'
dwebp-dwebp.o:dwebp.c:(.text.startup+0x6a9): undefined reference to `ExUtilSetBinaryMode'
dwebp-dwebp.o:dwebp.c:(.text.startup+0x9e5): undefined reference to `ExUtilDecodeWebP'
dwebp-dwebp.o:dwebp.c:(.text.startup+0xdd2): undefined reference to `ExUtilPrintWebPError'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:511: dwebp.exe] Fehler 1
make[1]: Verzeichnis „/entw/aktuell/forks/MINGW-packages/mingw-w64-libwebp/src/x86_64-w64-mingw32/examples“ wird verlassen
make: *** [Makefile:407: all-recursive] Fehler 1
```

It looks like a dependency of libwebp is too new?

**Comment by mati865** [comment]
Reverting isn't solution here, you should check or send logs and rebuild correct package.

**Comment by peterbud** [comment]
@tuhlmann  you are not using the appropriate darktable/windows-build source from [repo](https://github.com/peterbud/darktable/tree/windows-build). The dependency checking **was** done by hardcoded libraries, but it is **now** done by cmake's `BundleUtilities`, meaning it automatically detects library dependencies.
Look at this [commit](https://github.com/darktable-org/darktable/pull/1327/commits/c6eecf700920c010f5d2a8133ff7beae474c1b9d).

I'd suggest again to wait to have all remaining changes merged into the main darktable/master repo, and build your PKGBUILD against a _released source_

**Comment by tuhlmann** [comment]
@peterbud That sounds reasonable. And thanks for your patience!

**Comment by tuhlmann** [comment]
I'm running into another build error, I'm not sure if that is something wrong in my end. When running `
make --build . --target install` (whether from makepkg-mingw or command line I get:

```
--   dirs='C:/msys/mingw64/bin'
--   ignoreItems=''
-- fixup_bundle: preparing...
--
warning: cannot resolve item 'd3dx9_43.dll'

  possible problems:
    need more directories?
    need to use InstallRequiredSystemLibraries?
    run in install tree instead of build tree?

-- warning: gp_resolved_file_type non-absolute file 'd3dx9_43.dll' returning type 'other' -- possibly incorrect
--
warning: cannot resolve item 'd3dx9_43.dll'

  possible problems:
    need more directories?
    need to use InstallRequiredSystemLibraries?
    run in install tree instead of build tree?

warning: target 'd3dx9_43.dll' is not absolute...
warning: target 'd3dx9_43.dll' does not exist...
CMake Error at C:/msys/mingw64/share/cmake-3.7/Modules/GetPrerequisites.cmake:818 (message):
  C:/msys/mingw64/bin/objdump.exe failed: 1

  C:/msys/mingw64/bin/objdump.exe: 'd3dx9_43.dll': No such file

  FINDSTR: /a wurde ignoriert

Call Stack (most recent call first):
  C:/msys/mingw64/share/cmake-3.7/Modules/GetPrerequisites.cmake:943 (get_prerequisites)
  C:/msys/mingw64/share/cmake-3.7/Modules/BundleUtilities.cmake:618 (get_prerequisites)
  C:/msys/mingw64/share/cmake-3.7/Modules/BundleUtilities.cmake:848 (get_bundle_keys)
  packaging/cmake_install.cmake:37 (fixup_bundle)
  cmake_install.cmake:36 (include)
```

The error seems to indicate that there's something wrong with my Direct3D installation. I didn't mess with it (yet), this is a fairly recent Windows 10 64-bit installation.

Anyway as @peterbud suggested I will wait with further investigations until a proper windows version has been released...

**Comment by peterbud** [comment]
@tuhlmann : I believe you can give a try: darktable 2.2.5 has been released. That is now containing all codes to build the Windows version. You can give a try, and if you stuck feel free to ping me offlline for more help.

**Comment by elieux** [comment]
Offtopic: @peterbud, you're famous: https://www.root.cz/zpravicky/digitalni-komora-darktable-na-windows-cesta-je-volna/ :P

**Comment by peterbud** [comment]
@tuhlmann : apologies, I was too quick: 2.2.5 is only a maintenance release, and does not contain all commits which are needed for Windows build. With 2.3 hopefully we will reach that stage. I'll let you know.

**Comment by peterbud** [comment]
@elieux : thanks for letting me know! Funny to read the article with Google translate :) 

I have to say, that dt devs are really helpful and easy-going people after they see that you are serious and would like to contribute - they have helped me a lot, and I have learnt from them so much in the past few months. I guess they have just had some bad experience previously and therefore they were not trustful at the beginning, thats all.

**Comment by tuhlmann** [comment]
@peterbud No problem, just ping me when I should try again...

**Comment by peterbud** [comment]
@tuhlmann : ping
https://github.com/darktable-org/darktable/releases/tag/release-2.4.0rc0

**Comment by peterbud** [comment]
Anybody on this thread have 30 mins to try a build with this darktable PKGBUILD [here](https://github.com/Alexpux/MINGW-packages/pull/3233)? We would need some help.

**Comment by mati865** [comment]
It does build in minimal environment (AppVeyor) so it must be pulling more
libs which cause conflict when build in complete environment.

30.12.2017 08:39 "Peter Budai" <notifications@github.com> napisał(a):
