### ISSUE TITLE
libpcreposix-0 missing .a

### ISSUE THREAD

**Issue by johnkerl** [Alexpux/MINGW-packages#2394]
I'm using msys2 with mingw64 on Windows, trying to build a statically linked exe which will run outside of msys2. (I.e. build within msys2 but run outside.)

One of my dependencies is libpcreposix. Dependency setup is as follows:

    pacman -Syu
    pacman -Su
    pacman -S base-devel
    pacman -S msys2-devel
    pacman -S mingw-w64-x86_64-toolchain
    pacman -S mingw-w64-x86_64-pcre
    pacman -S msys2-runtime ?

Using `gcc` with `-lpcreposix` or `-lpcreposix.dll` I continue to get an exe requiring the two pcreposix DLLs.

A workaround is

    set PATH=%PATH%;\msys64\mingw64\bin
    nameof.exe

i.e. augment the outside-of-msys2 path to include the path to the DLLs. But what I really want is to make an exe file which people can simply run as is.

I notice that within the msys2 shell, I see

    $ find / -name \*pcreposix\*
    /mingw64/bin/libpcreposix-0.dll
    /mingw64/lib/licpcreposix.a
    /minw64/lib/libpcreposix.dll.a
    ....

i.e. there is a `.a` for `libpcreposix` but not for `libpcreposix-0`. When compile with `gcc ... -static` it finds the `libpcreposix` static library, but there is no `libpcreposix-0` static library, and when I invoke the exe outside of msys2 it says `The program can't start because libpcreposix-0.dll is missing from your computer. Try reinstalling the program to fix this problem.`

Is this a known problem? If I'm doing something wrong I don't see what it is. Why is there a static version of only one of the two libraries?

**Comment by johnkerl** [comment]
P.S.
```
% pacman -Q | grep pcre
libpcre 8.40-2
libpcre16 8.40-2
libpcre32 8.40-2
libpcrecpp 8.40-2
libpcreposix 8.40-2
mingw-w64-x86_64-pcre 8.40-1
pcre 8.40-2
```
even after `pacman -S mingw-w64-x64_64-pcre` which seems odd.

**Comment by peterbud** [comment]
As `libpcreposix` is an MSYS2 package, you might have better answers submitting an issue to the MSYS2 repo [here](https://github.com/Alexpux/MSYS2-packages/issues).

As I see the install script simply copies only the `dll`, but no the static `dll.a` libray [here](https://github.com/Alexpux/MSYS2-packages/blob/master/pcre/PKGBUILD#L97). Aka it might be rather easy to fix that.

**Comment by Alexpux** [comment]
@johnkerl, libpcreposix.a is what you need. By default GCC link with shared library, so you need tell it to link static executable with proper flags

**Comment by johnkerl** [comment]
@alexpux when I use `gcc ... -lpcreposix` I get runtime DLL dependency on `libpcreposix` and `libpcreposix-0`.

When I use `gcc ... -Bstatic -lpcreposix` I get runtime DLL dependency on `libpcreposix-0`.

**Comment by johnkerl** [comment]
@alexpux as I posted above there is a static `libpcreposix` for the linker to use, for it to satisfy my static-link request. There is no static `libpcreposix-0` for the linker to use, for it to satisfy my static-link request.

I'll try @peterbud's suggestion about seeing if the `libpcreposix-0` static library is somewhere else but didn't get copied to the right place.

**Comment by johnkerl** [comment]
@peterbud great suggestion; unfortunately it did not pan out. Moving to https://github.com/Alexpux/MSYS2-packages/issues/872. Thank you for your help!
