### ISSUE TITLE
mingw-w64-gdb fails validity check (small issue)

### ISSUE THREAD

**Issue by emmenlau** [Alexpux/MINGW-packages#2396]
This is probably a tiny issue but I currently can't fix it. mingw-w64-gdb fails to build:
http://data.biodataanalysis.de/tmp/buildlogs/1492309243-mingw-w64-gdb-buildlog.txt

**Comment by mati865** [comment]
It was broken by https://github.com/Alexpux/MINGW-packages/pull/2354
Checksums were made manually for both packages and both are wrong, they have to be recreated.
