### ISSUE TITLE
missing dependency for mingw-w64-x86_64-poppler

### ISSUE THREAD

**Issue by jdtournier** [Alexpux/MINGW-packages#2403]
Just installed `mingw-w64-x86_64-poppler` to use the `pdfunite` utility, but trying to run it resulted in:
```ShellSession
$ pdfunite.exe
C:/msys64/mingw64/bin/pdfunite.exe: error while loading shared libraries: libstdc++-6.dll: cannot open shared object file: No such file or directory
```
After a bit of detective work, it turns out that the missing dependency was actually the `libopenjp2-7.dll` library, which is included in the `mingw-w64-x86_64-openjpeg2` package. I'm guessing the `poppler` package dependencies need to be updated to fix this?

**Comment by mati865** [comment]
You can add it to [dependencies](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-poppler/PKGBUILD#L17) and update it to 0.53 by the way.
