### ISSUE TITLE
[REPOSITORY REQUEST] XML Security Library

### ISSUE THREAD

**Issue by silvioprog** [Alexpux/MINGW-packages#2404]
Hello masters,

It would be nice to publish the XML Security Library in the MinGW-w64 packages.

**Description from [its official site](https://www.aleksey.com/xmlsec):**

> XML Security Library is a C library based on [LibXML2](http://xmlsoft.org/). The library supports major XML security standards:
> 
> [XML Signature](http://www.w3.org/TR/xmldsig-core)
> [XML Encryption](http://www.w3.org/TR/xmlenc-core/)
> [Canonical XML](http://www.w3.org/TR/xml-c14n) (part of the [LibXML2](http://xmlsoft.org/))
> [Exclusive Canonical XML](http://www.w3.org/TR/xml-exc-c14n) (part of the [LibXML2](http://xmlsoft.org/))
> XML Security Library is released under the MIT Licence see the Copyright file in the distribution for details.

**Latest release and news:**

> April 20 2017
>
> The [XML Security Library 1.2.24](https://www.aleksey.com/xmlsec/download.html) release includes the following changes:
> - Added ECDSA-SHA1, ECDSA-SHA256, ECDSA-SHA512 support for xmlsec-nss (vmiklos).
> - Fixed XMLSEC_KEYINFO_FLAGS_X509DATA_DONT_VERIFY_CERTS handling (vmiklos).
> - Disabled external entities loading by xmlsec utility app by default to prevent XXE attacks (d-hat).
> - Improved OpenSSL version and features detection.
> - Cleaned up, simplified, and standardized internal error reporting.
> - Fixed a few Coverity-discovered bugs ([report](https://scan.coverity.com/projects/xmlsec)).
> - Marked as deprecated all the functions in xmlsec/soap.h file and a couple other functions no longer required by xmlsec. These functions will be removed in the future releases.
> - Several other small fixes ([more details](https://github.com/lsh123/xmlsec/commits/master)).
> - Please note that OpenSSL 0.9.8 support will be removed in the next release of XMLSec library.

Thank you!

**Comment by peterbud** [comment]
Well, it compiles with a minimal change, however some of the test cases fail, so it might require proper look from someone who actually understands what is going on.
