### ISSUE TITLE
GTK2 apps consume 100% CPU with arrow key held down.

### ISSUE THREAD

**Issue by mrev11** [Alexpux/MINGW-packages#2407]
GTK2 apps on Windows 10 (virtualized by Qemu) consume 100% CPU with arrow key held down.

    #include <gtk/gtk.h>                                                                      
                                                                                          
    int main( int  argc, char *argv[] )                                                     
    {                                                                                         
        GtkWidget *window;                                                                    
        gtk_init (&argc, &argv);                                                              
        window = gtk_window_new (GTK_WINDOW_TOPLEVEL);                                        
        gtk_widget_show  (window);                                                            
        gtk_main ();                                                                          
        return 0;                                                                             
    }                                                                                         
                                                                                          
This program whith left arrow key held down produces 100% CPU usage, as it can be seen [here](http://comfirm.hu/pub/gtk2-arrow-key-cpu-usage-on-win10.png).

With Windows-7 or 8 instead of Windows-10 the CPU usage is 0%.                    
With backspace instead of left arrow key the CPU usage is 0%.

**Comment by Ede123** [comment]
Reproduced on Windows 10 x64 with gtk-demo.exe as well as development build of Inkscape 0.92.x branch (mingw-w64-x86_64-gtk2 version 2.24.31-4).

Not reproduced on Windows 10 x64 with gtk3-demo.exe (mingw-w64-x86_64-gtk3 version 3.22.10-1).


However it does not seem to be an issue exclusive to MSYS2 as the same happens in gtk-demo.exe and Inkscape 0.92.1 (official/stable release) which were compiled without MSYS2 (using [mingw-w64 5.3.0](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/5.3.0/threads-win32/seh/) and a custom built of gtk 2.24.29).

**Comment by jtanx** [comment]
This is a known bug in gtk https://bugzilla.gnome.org/show_bug.cgi?id=771568

**Comment by Ede123** [comment]
@jtanx Modifier keys to seem fine. The issue occurs when pressing arrow keys here.

**Comment by jtanx** [comment]
Well I suggest applying the patch in that bug report and trying again, because they sound very similar.

**Comment by lazka** [comment]
The patch has been backported upstream, but there hasn't been a release yet. This can be closed when gtk 3.24.33 is out.

**Comment by mrev11** [comment]
Closed, but still wrong.

**Comment by lazka** [comment]
I'll look into backporting things
