### ISSUE TITLE
Glib2  - patched g_fopen() is not handling all modes

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#2414]
@Alexpux , I have found that the [patched ](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-glib2/0001-Use-CreateFile-on-Win32-to-make-sure-g_unlink-always.patch) `g_fopen()` is not handling all filemodes. 
For example, if someone opens the file with `w+`
`FILE *f = g_fopen(filename, "w+");`

the function returns `NULL`; while errno is 0.

I have also seen that the complete UTF8/UT16 handling is being cut out / removed: I'm not a GTK expert, but what is the reason of this large scale change?

Do we still need this patch (as I see this patch is from 2013)?

**Comment by lazka** [comment]
Looks like this is the source of the patch: https://bugzilla.gnome.org/show_bug.cgi?id=674214

**Comment by peterbud** [comment]
Thanks @lazka  -  tend to agree with @Ede123, this patch is not complete, and is removing functionality which is there in normal Glib. Let's continue the discussion at Bugzilla, and depending on the result we might propose the best action for us here.

**Comment by peterbud** [comment]
While I was working on a solution, I have compiled glib2, and run `make check`. To my surprise,  I have found that some of the test were failing:
```
Testsuite summary for glib 2.53.2
============================================================================
# TOTAL: 3703
# PASS:  3672
# SKIP:  13
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 17

```
Is this known? Anybody looked at the failed test cases?

**Comment by lazka** [comment]
@vyache-slav noticed a bug in the patch: https://github.com/Alexpux/MINGW-packages/pull/4343#commitcomment-30361956 Posting here so we don't forget

**Comment by vyache-slav** [comment]
[at this moment the bug has already been fixed (2 month ago) ](https://gitlab.gnome.org/GNOME/glib/issues/539#note_237156)
but not g_fopen
