### ISSUE TITLE
cmake: cmake-gui not working (fails to load libjsoncpp.dll)

### ISSUE THREAD

**Issue by Ede123** [Alexpux/MINGW-packages#2449]
I just tried to run `cmake-gui` from the `mingw-w64-x86_64-cmake` package (version 3.7.2-2). However it fails with the following error:
```
$ cmake-gui.exe
C:/msys64/mingw64/bin/cmake-gui.exe: error while loading shared libraries: libjsoncpp.dll: cannot open shared object file: No such file or directory
```

I have checked, though: `mingw-w64-x86_64-jsoncpp` (version 1.8.0-1) is installed and a `libjsoncpp.dll` is located in `/mingw64/bin/libjsoncpp.dll`.

**Comment by mati865** [comment]
Try running it from cmd.
Probably Cmake needs to be rebuilt.

**Comment by Ede123** [comment]
> Try running it from cmd.

Results in `The application was unable to start correctly (0xc00007b)`

**Comment by mati865** [comment]
You can wait for @Alexpux to upload CMake 3.8.1 binaries or build it yourself.

**Comment by Ede123** [comment]
Ah, great, missed that update.
I'll wait for the repo update and report back (not a high priority for me as I'm not using the `cmake-gui` anyway and `cmake` itself  is working fine)

**Comment by peterbud** [comment]
`cmake 3.8.1` is out. @Ede123 have you tried `cmake-gui`? For me it says:
`C:/msys64/mingw64/bin/cmake-gui.exe: error while loading shared libraries: zlib1.dll: cannot open shared object file: No such file or directory`

Which is funny as zlib is installed at `/mingw64/bin/zlib1.dll`

**Comment by Ede123** [comment]
Might be due to https://github.com/Alexpux/MINGW-packages/issues/2616#issuecomment-310746451
I'm unsure if we really want to add qt5 as a dependency (most people probably never touch cmake-gui) as it would blow up download size when installing the cmake package unreasonably I'm afraid.

Regarding the error messsage: I noticed something similar with Inkscape lately: It compiles a shared "libinkscape-base.dll" containing al the common code. When I'm missing a dependency it does not complain about that dependency but about libinkscape-base.dll with the exact error you're mentioning. Maybe there's something wrong here...

**Comment by mati865** [comment]
Those are common issues on Windows.

Also my cmake-gui error:
![cmake_gui](https://user-images.githubusercontent.com/1174646/27508418-9d96d7a0-58e4-11e7-800c-8df1dddabf36.png)

**Comment by Ede123** [comment]
@mati865 The window displayed by Windows when launching the executable directly is mostly showing the correct error though (in this case it mentions qt at least) while the error printed to console is a lot more cryptic and usually does not mention the actually missing library.

**Comment by mati865** [comment]
@Ede123 I have Qt installed. Most likely there is some library missing or it's ABI changed and few things need a rebuild.

**Comment by peterbud** [comment]
@Ede123 : I agree, it would be an overkill to have qt5 as a dependency for cmake

**Comment by Fazer2** [comment]
Wouldn't it make more sense to extract cmake-gui to a separate package that is suggested as an option for cmake one?
