### ISSUE TITLE
Latest update of CMake breaks Ninja builds

### ISSUE THREAD

**Issue by Ede123** [Alexpux/MINGW-packages#2462]
The latest package updates seem to have broken my cmake builds with Ninja.

Even with [the simplest dummy project](http://derekmolloy.ie/hello-world-introductions-to-cmake/) `cmake .. -G Ninja` results in 
```
$ cmake .. -G Ninja
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe -- broken
CMake Error at C:/msys64/mingw64/share/cmake-3.8/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "C:/msys64/mingw64/bin/cc.exe" is not able to compile a
  simple test program.

  It fails with the following output:

   Change Dir: E:/test/build/CMakeFiles/CMakeTmp


  Run Build Command:"C:/msys64/mingw64/bin/ninja.exe" "cmTC_c2082"

  ninja: error: loading 'build.ninja': Das System kann die angegebene Datei
  nicht finden.


  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "E:/test/build/CMakeFiles/CMakeOutput.log".
See also "E:/test/build/CMakeFiles/CMakeError.log".
```

**Comment by Ede123** [comment]
As `cmake .. -G "MinGW Makefiles"` works fine I suspect the issue is with CMake or Ninja.

**Comment by Ede123** [comment]
Confirmed:
Downgrading mingw-w64-x86_64-cmake (3.8.1-1 => 3.7.2-2) solves the issue.

**Comment by Ede123** [comment]
Pinging @mingwandroid as you broke it in 536d94d59728808ee4e004c9d8b9c6abb09c47f9 😉

**Comment by mingwandroid** [comment]
Did you run this from an msys2 shell or a mingw shell?

**Comment by mingwandroid** [comment]
If an msys2 shell then this is not a bug necessarily.

If a mingw shell then I need to see the contents of:
```
See also "E:/test/build/CMakeFiles/CMakeOutput.log".
See also "E:/test/build/CMakeFiles/CMakeError.log".
```

**Comment by Ede123** [comment]
`msys2_shell.cmd -mingw64`

**Comment by Ede123** [comment]
@mingwandroid Here you are



[debug-output.txt](https://github.com/Alexpux/MINGW-packages/files/999430/debug-output.txt)
[CMakeOutput.log.txt](https://github.com/Alexpux/MINGW-packages/files/999432/CMakeOutput.log.txt)
[CMakeError.log.txt](https://github.com/Alexpux/MINGW-packages/files/999433/CMakeError.log.txt)

**Comment by Optiligence** [comment]
I think next would be to cross-test with official builds of cmake and ninja.

**Comment by Optiligence** [comment]
official CMake 3.8.1 works

**Comment by Ede123** [comment]
Patch in ce2c60f6b2d2bde177fc00da800aba815fffd969 confirmed working, thanks @Optiligence .

Let's see if they come up with a real fix for https://gitlab.kitware.com/cmake/cmake/issues/16893 eventually...
