### ISSUE TITLE
LLVM 4.0 binary package availability

### ISSUE THREAD

**Issue by RyanGlScott** [Alexpux/MINGW-packages#2473]
I see that https://github.com/Alexpux/MINGW-packages/pull/2294 was merged about two months ago which, AFAICT, means that you can build LLVM 4.0 in this repository. Is there any change of a binary package of LLVM 4.0 being made available soon?

**Comment by RyanGlScott** [comment]
Never mind, I see there's now http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-llvm-4.0.0-1-any.pkg.tar.xz. Sorry for the noise!

**Comment by mati865** [comment]
Signature file is missing for clang package however. You will have to install it with `pacman -U <file>`.
