### ISSUE TITLE
PKBUILD mingw-packages/mingw-w64-qt5-static

### ISSUE THREAD

**Issue by ApproxDev** [Alexpux/MINGW-packages#2478]
Hello,

Ref : https://wiki.qt.io/MSYS2.

With mingw-packages/mingw-w64-qt5, I build Qt5 :
`cd /c/msys2/repos/mingw-packages/mingw-w64-qt5`
`updpkgsums`
`makepkg-mingw -fsiL`
It works fine.

Then with mingw-packages/mingw-w64-qtcreator :
`cd /c/msys2/repos/mingw-packages/mingw-w64-qtcerator`
`updpkgsums`
`makepkg-mingw -fsiL`
It's OK.

**But with mingw-packages/mingw-w64-qt5-static** :
`cd /c/msys2/repos/mingw-packages/mingw-w64-qt5-static`
`updpkgsums`
`makepkg-mingw -code   //To clean before each test`
`makepkg-mingw -fsiL`
Many errors are reported.
- The first : 
>  In file included from qwindowsintegration.cpp:51:0:
> ../../../../include/QtFontDatabaseSupport/5.8.0/QtFontDatabaseSupport/private/qwindowsfontdatabase_ft_p.h:1:96: fatal error: ../../../../../src/platformsupport/                     fontdatabases/windows/qwindowsfontdatabase_ft_p.h: No such file or directory
>  #include "../../../../../src/platformsupport/fontdatabases/windows/qwindowsfont database_ft_p.h"
>                                                                                                                      ^
> compilation terminated.
> make[6]: *** [Makefile.Debug:2324: .obj/debug/qwindowsintegration.o] Error 1
> make[6] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/platforms/windows »
> make[5]: *** [Makefile:38: debug-all] Error  2

- The last :
>  #include "../../../../../src/platformsupport/eventdispatchers/qwindowsguieventd                     ispatcher_p.h"
>                                                                                                                    ^
> compilation terminated.
> make[6]: *** [Makefile.Release:2757: .obj/release/qwindowscontext.o] Error 1
> make[6] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-                     static/src/x86_64/qtbase/src/plugins/platforms/windows »
> make[5]: *** [Makefile:52: release-all] Error 2
> make[5]: *** Attente des tâches non terminées....
> make[6] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-                     static/src/x86_64/qtbase/src/plugins/platforms/windows »
> make[5]: *** [Makefile:38: debug-all] Error 2
> make[5] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-                     static/src/x86_64/qtbase/src/plugins/platforms/windows »
> make[4]: *** [Makefile:92: sub-windows-make_first] Error 2
> make[4] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-                     static/src/x86_64/qtbase/src/plugins/platforms »
> make[3]: *** [Makefile:96: sub-platforms-make_first] Error 2
> make[3] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-                     static/src/x86_64/qtbase/src/plugins »
> make[2]: *** [Makefile:770: sub-plugins-make_first] Error 2
> make[2] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-                     static/src/x86_64/qtbase/src »
> make[1]: *** [Makefile:43: sub-src-make_first] Error 2
> make[1] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-                     static/src/x86_64/qtbase »
> make: *** [Makefile:77: module-qtbase-make_first] Error 2
> ==> ERREUR : Une erreur s’est produite dans build().
>     Abandon...

How to solve this problem ?  Is the directive -fsiL for makepkg-mingw correct ?
Thank you for your help.
Regards. AD.

PS : Windows 7 - Pack 1 - 64 bits.

**Comment by ApproxDev** [comment]
Report in Qt5-Static report.txt
[Qt5-Static report.txt](https://github.com/Alexpux/MINGW-packages/files/1016322/Qt5-Static.report.txt)
First error at line 1216

**Comment by ApproxDev** [comment]
A little help, please. Thanks.
Regards. AD.

**Comment by elieux** [comment]
Maybe @Alexpux knows what's going on. (if he has some spare time)

**Comment by mati865** [comment]
Could be too long path.

**Comment by ApproxDev** [comment]
Hello,

Tested with Windows 10 64 [long path actived]

> make[6] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/generic/tuiotouch »
> make[5] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/generic/tuiotouch »
> make[4] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/generic »
> make[3] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins »
> make[2]: *** [Makefile:770: sub-plugins-make_first] Error 2
> make[2] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src »
> make[1]: *** [Makefile:43: sub-src-make_first] Error 2
> make[1] : on quitte le répertoire « /c/msys2/repos/mingw-packages/mingw-w64-qt5-static/src/x86_64/qtbase »
> make: *** [Makefile:77: module-qtbase-make_first] Error 2
> ==> ERREUR : Une erreur s’est produite dans build().
>     Abandon...

Total blurring ! Instruction error on my part ?  Windows version incompatible ? Bug in scripts ?
I wanted to use msys2 to get faster : In fact, this is nothing or almost nothing. Never mind. I will proceed otherwise. Cordially. AD.

**Comment by mati865** [comment]
Long path setting doesn't matter if program don't have special code to support it.

**Comment by ApproxDev** [comment]
Hello,
So if I understand correctly, some programs use long paths and others called by them are not compatible with long paths ? If that is the case, it's.... delusional !  And so how did it work once ?
Regards. AD.

**Comment by mati865** [comment]
It's well-known Windows issue because of DOS compatibility, normal apps cannot use paths longer than 256 characters. To use longer path one have to add manifest and it only works on Win 10 which isn't most popular OS.
As workaround move contents of `/c/msys2/repos/mingw-packages/mingw-w64-qt5-static` to short location like `/c/qt_build`.

**Comment by mingwandroid** [comment]
It never did and never will work. The amount of software that contains (and I've surely been responsible for some of this):

`char filename[PATHMAX];`

precludes almost *ever* being able to get fully away from the 260 character limit in any non-trivial software build. I'd welcome people to try, but life (like `PATHMAX`) is too short for me to spend time on this.

.. and why wouldn't people have written (and continue to write) such code? `PATHMAX` was after all documented as the longest possible path on Windows, and in-fact such things also often appear in Linux and macOS codebases, just with `PATHMAX` being a larger number than 260 in those system's headers.
