### ISSUE TITLE
glib2 - make check fails

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#2516]
After you build glib2 with PKGBUILD you can run also `make check,` which reveals that a number of test are failing in the current glib2 build:
```
Testsuite summary for glib 2.52.2
============================================================================
# TOTAL: 3703
# PASS:  3672
# SKIP:  13
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 17
```
I have checked fileutils test suite, and found that for example `g_stat()` is not working properly, modified date field is not populated.
Actually, you can se a number of warnings which give you a hint what is the issue, like [here](https://ci.appveyor.com/project/Alexpux/mingw-packages/build/1.0.2878#L1051)
```
./../glib-2.52.2/glib/gstdio.c: In function 'g_stat':
../../glib-2.52.2/glib/gstdio.c:641:31: warning: passing argument 2 of '_wstat64i32' from incompatible pointer type [-Wincompatible-pointer-types]
   retval = _wstat (wfilename, buf);
                               ^~~
In file included from ../../glib-2.52.2/glib/gstdio.c:25:0:
C:/msys64/mingw64/x86_64-w64-mingw32/include/sys/stat.h:128:15: note: expected 'struct _stat64i32 *' but argument is of type 'GStatBuf * {aka struct _stat64 *}'
   int __cdecl _wstat64i32(const wchar_t *_Name,struct _stat64i32 *_Stat);
               ^~~~~~~~~~~

```
I have started to look into fileutil checks, but as you see above there are quite a few of those, and most likely these should be fixed upstream.

**Comment by peterbud** [comment]
This is the [relevant thread](https://bugzilla.gnome.org/show_bug.cgi?id=764566) on Bugzilla.

**Comment by lazka** [comment]
If anyone wants to improve them please open a MR upstream.

btw, glib now has a Windows CI system: https://gitlab.gnome.org/GNOME/glib/-/jobs/77666
