### ISSUE TITLE
Boost 1.63 -> 1.64

### ISSUE THREAD

**Issue by Fazer2** [Alexpux/MINGW-packages#2549]
[Boost 1.64](http://www.boost.org/users/history/version_1_64_0.html) came out on 19th April 2017, is there any plan to update the Boost packages from 1.63 to the newest version? Thanks in advance.

**Comment by Alexpux** [comment]
Will do it when new ICU Package will be fixed to build

**Comment by Fazer2** [comment]
I can see the package has been updated to 1.64, I'm closing the issue, thanks!
