### ISSUE TITLE
fontconfig: Fails to update cache file

### ISSUE THREAD

**Issue by Ede123** [Alexpux/MINGW-packages#2550]
When fontconfig attempts to update the fontconfig cache file it creates a temporary file like

`ef9c9ad8cc5857eb63cb3660bc8bd202-x86_64.cache-7.NEW`

Creation of this file succeeds, but fontconfig seems to fail to replace the original file (without the `.NEW`) afterwards, resulting in fontconfig updating the outdated file on every startup and thereby causing massive delays.

**Comment by lazka** [comment]
Maybe this https://bugs.freedesktop.org/show_bug.cgi?id=99360 ? The fix is in master only atm https://cgit.freedesktop.org/fontconfig/log/

I've tried to update fontconfig some days ago, but the newest versions fails to build, for which I've filed https://bugs.freedesktop.org/show_bug.cgi?id=101280

**Comment by lazka** [comment]
btw. In case you have fontconfig problems with a gtk+ based app, you can set "PANGOCAIRO_BACKEND=win32" to not use it.

**Comment by Ede123** [comment]
Sounds like this is the issue I'm seeing.
Let's hope we can build the latest version again soon, then I'll test the change.

**Comment by lazka** [comment]
After a quick test, the patch seems to work here. Executing fc-cache.exe returns immediately now. See #2551
