### ISSUE TITLE
qt5-webkit that comes with qt5.9 still links to icu57 - which is replaced by icu58 in the distro

### ISSUE THREAD

**Issue by bagong** [Alexpux/MINGW-packages#2575]
Hi,

the subject line pretty much says it, apps that depend on qtwebkit currently can't be built with qt5.9. Also as a side info: that qt5-webkit of which msys2 uses tp5 (annulen) has been updated. It's now called qtwebkit-5.212 and has a alpha release.

https://github.com/annulen/webkit/releases

Best

**Comment by Alexpux** [comment]
New packages uploaded
