### ISSUE TITLE
mingw-w64-icu update broke at least mingw-w64-nodejs

### ISSUE THREAD

**Issue by dscho** [Alexpux/MINGW-packages#2585]
Unlike on Linux, where the version number in the shared library's name does not prevent it from being found by dependencees, On Windows an update that deletes `libicuuc57.dll` and adds `libicuuc58.dll` breaks *every single* executable that links against the former.

**Comment by peterbud** [comment]
Thats a long story, see #2145

**Comment by mati865** [comment]
I'm working on to update node to latest LTS version so it should be rebuild soon.

**Comment by nbergont** [comment]
mingw-w64-icu update also broke mingw-w64-xerces-c : need a rebuild

**Comment by lazka** [comment]
nodejs and xerces-c have been rebuilt in the meantime.
