### ISSUE TITLE
Make fails on unlink when aborting

### ISSUE THREAD

**Issue by orgads** [Alexpux/MINGW-packages#2592]
When I abort a build, make fails to unlink the intermediate files.

This happens even for a single job (without -j).

Output:
```
main.cpp
mingw32-make[1]: *** Deleting file 'obj/main.o'
mingw32-make[1]: unlink: obj/main.o: Permission denied
^CTerminate batch job (Y/N)? y
mingw32-make[1]: *** [Makefile:7178: obj/main.o] Error 255
Terminate batch job (Y/N)? y
mingw32-make: *** [Makefile:5574: app.exe] Error 255
```

After investigating a lot, I found out that this is caused by the `make-linebuf-mingw` patch. If I revert it, unlink works as expected, but the output is interleaved. Notice that ^C is in the middle of the file name, and Terminate batch job appears without a new line:

```
make: *** Deleting file 'obj/m^ainC.oTerminate batch job (Y/N)? '
```

For completeness, this is the contents of the patch:
```patch
diff -Naur make-4.2.1/main.c make-4.2.1.new/main.c
--- make-4.2.1/main.c   2016-05-31 09:17:26.000000000 +0200
+++ make-4.2.1.new/main.c       2017-02-20 22:55:09.051617838 +0100
@@ -1126,8 +1126,11 @@

 #endif

+/* setlocale interferes with line buffering if using parallel make on MinGW */
+#ifndef __MINGW32__
   /* Set up gettext/internationalization support.  */
   setlocale (LC_ALL, "");
+#endif
   /* The cast to void shuts up compiler warnings on systems that
      disable NLS.  */
   (void)bindtextdomain (PACKAGE, LOCALEDIR);
```

Can you suggest a solution that will solve both issues?

**Comment by orgads** [comment]
After a few more attempts, I've noticed that it doesn't really matter. It only helps when invoking from command line, but not from IDE.

Do you have any idea what can be wrong? It's really easy to reproduce.

**Comment by orgads** [comment]
Ok, I found what caused this. It is due to `gcc -pipe` usage. See an example [here](http://lists.gnu.org/archive/html/bug-make/2017-06/msg00076.html).

**Comment by slspencer** [comment]
What is the fix? This problem also happens without pressing Ctrl-C

>compiling ../../../../vpo2/src/libs/vpropertyexplorer/plugins/vshortcutproperty.cpp 
mingw32-make[4]: *** Deleting file 'obj/vshortcutproperty.o'
mingw32-make[4]: unlink: obj/vshortcutproperty.o: Permission denied
Terminate batch job (Y/N)? 11:49:17: The process "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" exited with code -1.
11:49:17: Canceled build/deployment.
11:49:17: Elapsed time: 00:39.

**Comment by Alexpux** [comment]
Under msys2 console you need use regular make, not mingw32-make

**Comment by slspencer** [comment]
So, copying mingw32-make.exe to make.exe works?

**Comment by Alexpux** [comment]
No, use make from msys package
