### ISSUE TITLE
Yet another utility to build distributions

### ISSUE THREAD

**Issue by filnet** [Alexpux/MINGW-packages#2634]
It is a ntldd based python utility that will scan a list of libraries or executables and copy all their dependencies to a destination dir. 
Inspiration came from https://github.com/msys2/msys2/wiki/Distributing.

```
$ ./copy_dependencies.py -h
usage: copy_dependencies.py [-h] [-n] [-v] [-d DEST] -f FILE
                            [FILE ...] [-e FILE [FILE ...]]

Find and copy dependencies to a destination directory.

optional arguments:
  -h, --help            show this help message and exit
  -n, --no-copy         don't copy dependencies to destination dir
  -v, --verbose         enable verbose mode
  -d DEST, --dest DEST  destination directory (defaults to current directory)
  -f FILE [FILE ...], --files FILE [FILE ...]
                        a file
  -e FILE [FILE ...], --excludes FILE [FILE ...]
                        a file
```

Example usage:
```
./copy_dependencies.py -f *.dll *.exe
```
will copy all dependencies of libraries and execs found in the current directory to the current directory.

Source is [here](https://bitbucket.org/librepilot/librepilot/src/1a4bb0cc5bef153e1acd8a31984ad5efc20ce7f1/make/copy_dependencies.py?at=next&fileviewer=file-view-default]).

**Comment by jtanx** [comment]
Sounds a bit like my hobo script

```bash
#!/usr/bin/bash
#set -e
MSYSROOT=`cygpath -w /`
BINROOT=`cygpath -w $(dirname "${1}")`

libs=`ntldd -D "$(dirname \"${1}\")" -R "$1" \
| grep dll \
| sed -e '/^[^\t]/ d'  \
| sed -e 's/\t//'  \
| sed -e 's/.*=..//'  \
| sed -e 's/ (0.*)//' \
| grep -F -e "$MSYSROOT" -e "$BINROOT" \
`

echo Collecting libraries...
for f in $libs; do
    cp -v "$f" .
    #echo $f
done

echo Done.
```

**Comment by filnet** [comment]
It does :)

I'll simplify my python script to use the -R option (totally overlooked that one...)

**Comment by filnet** [comment]
Took the feedback and produced a simplified version of the python script.
The link in the 1st post will point to the new version when it gets merged.

Thanks @jtanx for the feedback.

**Comment by filnet** [comment]
Closing as it was more an ad than an issue.

**Comment by elieux** [comment]
Added: https://github.com/msys2/msys2/wiki/Distributing

**Comment by filnet** [comment]
Cool! Thanks.

**Comment by filnet** [comment]
The link to script provided in https://github.com/msys2/msys2/wiki/Distributing points to an old/obsolete version.

**Comment by elieux** [comment]
I don't have any other link.  If you send me one, I'll update the wikipage.

**Comment by filnet** [comment]
Here is the a link to the most recent version : https://bitbucket.org/librepilot/librepilot/src/4c9c3c202caad2250a35ce6aed796f5f46b5224c/make/copy_dependencies.py

Also updated to original post as I said I would...

**Comment by elieux** [comment]
Done.
