### ISSUE TITLE
vulkan only builds with 64 bit mingw

### ISSUE THREAD

**Issue by revelator** [Alexpux/MINGW-packages#2639]
Not sure if mentioned before, so here's a report.

64 bit build works but 32 bit bails with 

CMakeFiles/vulkan-1.dir/objects.a(trampoline.c.obj):trampoline.c:(.text+0x8e8): undefined reference to `InitOnceExecuteOnce'
CMakeFiles/vulkan-1.dir/objects.a(trampoline.c.obj):trampoline.c:(.text+0xc45): undefined reference to `InitOnceExecuteOnce'
CMakeFiles/vulkan-1.dir/objects.a(trampoline.c.obj):trampoline.c:(.text+0xd56): undefined reference to `InitOnceExecuteOnce'

also a lot of warnings about linking and a suggestion to use --enable-stdcall-fixup.

**Comment by wirx6** [comment]
#2590

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/16bd4e2d7ced19125727007b3674ae50f5f168b6
