### ISSUE TITLE
cmake patches are not applied

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MINGW-packages#2640]
@JPeterMugaas The [`apply_patch_with_msg`](https://github.com/Alexpux/MINGW-packages/blob/3016128af8a89358ecaa711804db501b9a566462/mingw-w64-cmake/PKGBUILD#L65) function only applies the first patch and not all of them.

**Comment by JPeterMugaas** [comment]
Thanks for pointing my mistake.  It looks like someone beat me to the punch.
