### ISSUE TITLE
python2/3, isatty and stdout buffering

### ISSUE THREAD

**Issue by lazka** [Alexpux/MINGW-packages#2645]
Python2/3 stdout not being line buffered under minttty is annoying so I'm wondering what would be the best fix here:

* On startup Python decides if stdout is linebuffered based on isatty, we could detect mintty there.
* Intercept all C level isatty calls (there are 11 calls in Python 3) so that os.isatty also returns the right result.
* Anything else?

**Comment by jtanx** [comment]
Use winpty

**Comment by lazka** [comment]
winpty is indeed nice, thanks. But it's not that obvious and tedious to type before each command. Then my question is why isn't "winpty bash" not the default mingw shell?

**Comment by jtanx** [comment]
Well, just guessing here, but there's a non-zero cost associated with using winpty, and most of the time, mintty works fine anyway. Your problem stems from trying to use mingw python which is a native windows build, and hence expects it to be used from a windows console. mintty uses pipes for input/output, so it doesn't look like a proper terminal to most programs.

On the other hand, if you use msys2 (or cygwin) python (.e.g /usr/local/bin/python2), everything just works. 

Anyway, I'm pretty sure you can also just edit the default console to not be mintty, although I don't know the full details of this. Try looking/modifying the batch file that starts msys2. 

Or you can just call bash.exe directly from cmd.exe.... that works too.

**Comment by lazka** [comment]
Hm, found a downside with winpty, it doesn't allow inputing umlauts (öäü..) in Python. A bit of a deal breaker I guess. It also seems a tiny bit slower, but I wouldn't mind if that in exchange for proper program behavior.

**Comment by lazka** [comment]
If anyone thinks that adjusting isatty() in Python is a good idea I can provide patches. If not feel free to close this.

**Comment by mingwandroid** [comment]
I'm fine with that personally. ag was recently patched in this way, maybe you can reuse the code? There was talk of trying to upstream to mingw-w64 a msys2/cygwin sympathetic isatty, does anyone know what happened with that effort?

**Comment by peterbud** [comment]
Sorry for the potentially off-topic question: could it be the reason why msys2 is not working in docker and no stdout is written to the console?
https://github.com/docker/for-win/issues/262
https://github.com/msys2/msys2/issues/46

**Comment by lazka** [comment]
@peterbud no idea, sorry

I've opened a PR #2675 for Python 3 for starters. That fixes line buffering, interactive detection with mintty and unicode input with winpty. The interactive mode using readline is still weird, maybe due to readline not detecting the terminal as well...

**Comment by lazka** [comment]
Most things should be fixed now.

* "python" now properly starts in interactive mode
* python3 does automatic line buffering in a terminal
* meson/pytest have color output now
* the readline module is disabled in case no cygwin terminal is found
