### ISSUE TITLE
[mingw-w64-curl] winidn not found in mingw32

### ISSUE THREAD

**Issue by jeroen** [Alexpux/MINGW-packages#2677]
I am building a version of `mingw-w64-curl` with `--with-winidn` ([PKGBUILD](https://raw.githubusercontent.com/rwinlib/libcurl/master/lib-winssl/PKGBUILD)). It works great on mingw64 however when building in mingw32 I see:

```
checking whether versioned symbols are wanted... no
checking whether to enable Windows native IDN (Windows native builds only)... yes
checking if IdnToUnicode can be linked... no
configure: WARNING: Cannot find libraries for IDN support: IDN disabled
``` 

And the resulting binary then does:

```
* Rebuilt URL to: http://www.malmö.se/
* IDN support not present, can't parse Unicode domains
* timeout on name lookup is not supported
* getaddrinfo(3) failed for www.malmö.se:80
* Couldn't resolve host 'www.malmö.se'
```
I also tried configuring as suggested [here](https://sourceforge.net/p/mingw-w64/bugs/384/) with

```sh
export CPPFLAGS=" -D_WIN32_WINNT=0x0600 -DWINVER=0x0600"
```

But no luck. Is this a bug in the autoconf script of libcurl? Or is `Normaliz.lib` not supported in `mingw32`?

**Comment by jtanx** [comment]
Look in `config.log` at the point where it does `checking if IdnToUnicode can be linked...` and see what the compiler/linker error is

**Comment by jeroen** [comment]
It just says:

```
configure:26798: checking whether to enable Windows native IDN (Windows native builds only)
configure:26816: result: yes
configure:26843: checking if IdnToUnicode can be linked
configure:26872: i686-w64-mingw32-gcc -o conftest.exe -D_WIN32_WINNT=0x0600 -DWINVER=0x0600 -Werror-implicit-function-declaration -O2 -Wno-system-headers -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -IC:/msys32/mingw32/include  -pipe -LC:/msys32/mingw32/lib  conftest.c -lnormaliz -lcrypt32 -lwldap32 -lz -lws2_32  >&5
C:\msys32\tmp\cccptlBZ.o:conftest.c:(.text.startup+0xc): undefined reference to `IdnToUnicode'
```

**Comment by jtanx** [comment]
Your define doesn't quite match that in the sourceforge thread - note the dash instead of underscore between `_WIN32-WINNT` (vs your `_WIN32_WINNT`)

e.g. it try `-D_WIN32-WINNT=0x0600 -DWINVER=0x0600`

**Comment by jeroen** [comment]
The curl autoconf test that is failing looks like this. It is somehow conflicting with the `WINVER` macro.

```c
if test "$want_winidn" = "yes"; then
    clean_CPPFLAGS="$CPPFLAGS"
  clean_LDFLAGS="$LDFLAGS"
  clean_LIBS="$LIBS"
  WINIDN_LIBS="-lnormaliz"
  #
  if test "$want_winidn_path" != "default"; then
            WINIDN_LDFLAGS="-L$want_winidn_path/lib$libsuff"
    WINIDN_CPPFLAGS="-I$want_winidn_path/include"
    WINIDN_DIR="$want_winidn_path/lib$libsuff"
  fi
  #
  CPPFLAGS="$CPPFLAGS $WINIDN_CPPFLAGS"
  LDFLAGS="$LDFLAGS $WINIDN_LDFLAGS"
  LIBS="$WINIDN_LIBS $LIBS"
  #
  { $as_echo "$as_me:${as_lineno-$LINENO}: checking if IdnToUnicode can be linked" >&5
$as_echo_n "checking if IdnToUnicode can be linked... " >&6; }
  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
/* end confdefs.h.  */


#define IdnToUnicode innocuous_IdnToUnicode
#ifdef __STDC__
# include <limits.h>
#else
# include <assert.h>
#endif
#undef IdnToUnicode
#ifdef __cplusplus
extern "C"
#endif
char IdnToUnicode ();
#if defined __stub_IdnToUnicode || defined __stub___IdnToUnicode
choke me
#endif

int main (void)
{
return IdnToUnicode ();
 ;
 return 0;
}
```

**Comment by jtanx** [comment]
Ah, I know why.

From `winnls.h`:

```c
  WINNORMALIZEAPI int WINAPI IdnToUnicode (DWORD dwFlags, LPCWSTR lpASCIICharStr, int cchASCIIChar, LPWSTR lpUnicodeCharStr, int cchUnicodeChar);
```

[IdnToUnicode](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318151(v=vs.85).aspx) is a `WINAPI` function, meaning it's a function declared with the `__stdcall` calling convention. On 64-bit systems, this does nothing, and is ignored, hence why it works there. But on 32-bit, it does mean something, and one of the effects is name mangling - the linker should actually be looking for `IdnToUnicode@20`.

To put it short, the [test](https://github.com/curl/curl/blob/909a5bee81a32ceecbf23a15fd8a48879a84b6dc/configure.ac#L2799) that Curl uses is broken, and needs to account for IdnToUnicode having the stdcall calling convention.

**Comment by jeroen** [comment]
@jtanx can you maybe suggest a fix at https://github.com/curl/curl/issues/1669 ?

**Comment by jeroen** [comment]
Moving the issue to upstream: https://github.com/curl/curl/issues/1669
