### ISSUE TITLE
mingw-w64-libmariadbclient is missing mysql_config script

### ISSUE THREAD

**Issue by jeroen** [Alexpux/MINGW-packages#2681]
I would like to build `gdal` package `--with-mysql`. However this requires a `mysql_config` or `mariadb_config` executable. Trying to point it to the `libmariadbclient` directory, the gdal configure script errors with:

```
configure: error: --with-mysql argument is a directory.  It should be the path to the mysql_config 
  script, often somewhere like /mingw64/bin/mysql_config.
```

Is there some way to make `mingw-w64-libmariadbclient` produce the `mysql_config` script? It seems this should because it is also included in e.g. the [ubuntu libmariadbclient](https://packages.ubuntu.com/zesty/amd64/libmariadbclient-dev/filelist) package.

**Comment by stahta01** [comment]
Can you apply a patch to the libmariadbclient package and build and test it?
If yes, I am willing to try to create a patch.

Tim S.

**Comment by stahta01** [comment]
[patch](https://github.com/stahta01/stahta01.github.io/blob/master/msys2/patches/libmariadbclient-Add-install-of-mariadb_config.exe.patch)

Tim S.

**Comment by jeroen** [comment]
Thanks! Perhaps make this a pull request?

**Comment by stahta01** [comment]
Did it test OK? 
Because, I have no idea how to test the patch to confirm it works.
All I know is it builds, installs, and the exe gives output. No idea if the output is valid.

Tim S.

**Comment by stahta01** [comment]
#2687 Pull request.

Tim S.
