### ISSUE TITLE
cmake does not see libraries

### ISSUE THREAD

**Issue by mrechte** [Alexpux/MINGW-packages#2685]
Hi,

Trying to build tigervnc, cmake fails on all find_package calls. For instance:

$ cmake -G "MSYS Makefiles" ..
find_package(JPEG REQUIRED)
Could NOT find JPEG (missing: JPEG_LIBRARY)
find_package(ZLIB REQUIRED)
Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")

However these libraries are installed:
$ pkg-config --list-all
...
libturbojpeg libturbojpeg - A SIMD-accelerated JPEG codec that provides the TurboJPEG API
...
zlib zlib - zlib compression library
...
libjpeg libjpeg - A SIMD-accelerated JPEG codec that provides the libjpeg API

$ pkg-config --modversion zlib
1.2.11
$ pacman -Qs zlib
local/mingw-w64-x86_64-zlib 1.2.11-1
Compression library implementing the deflate compression method found in gzip and PKZIP (mingw-w64)
local/zlib 1.2.11-1 (libraries)
Compression library implementing the deflate compression method found in gzip and PKZIP

$ pacman -Qs cmake
local/cmake 3.6.2-1
A cross-platform open-source make system
local/mingw-w64-x86_64-cmake 3.8.2-2
A cross-platform open-source make system (mingw-w64)

Thanks

**Comment by Optiligence** [comment]
It builds for me using a mingw64 shell.

**Comment by mrechte** [comment]
Re-installed from scratch. Issue is gone.
Thanks a lot
