### ISSUE TITLE
Ruby specific packages?

### ISSUE THREAD

**Issue by MSP-Greg** [Alexpux/MINGW-packages#2688]
For several months I've been building Ruby with MinGW, and recently, doing mswin builds of it.

For MinGW, I decided three packages would be needed, gdbm, libyaml, and openssl.  At present, all of my packages are prefixed with ruby.

1. ruby-gdbm - I tried, but I could not get gdbm later than 1.10 to work with Ruby.  So, I rebuilt 1.10.

2. ruby-libyaml - using 0.1.7, static

3. ruby-openssl - prefered to build 1.1.0, current package is 1.1.0f.  The version and the options may cause issues for inclusion in other software.  FWIW, I also build OpenSSL with mswin.  Built with the following config:

```
./Configure \
--prefix=${MINGW_PREFIX} \
--openssldir=${MINGW_PREFIX} \
--api=1.0.0 \
${_mingw} \
shared \
zlib-dynamic \
enable-capieng \
-D__MINGW_USE_VC2005_COMPAT
```

The packages (64 bit only) are presently signed and uploaded at [BinTray](https://dl.bintray.com/msp-greg/ruby_windows/).  All packages pass respective tests.  ruby-openssl also works with a few ruby extension gems that compile with OpenSSL.

So, would you accept these packages into the repo?  Naming okay?

FWIW, my Ruby build system is based on MSYS2/MinGW, but it works from a local repo, uses Ruby code to select and apply patches, generates seperate files for each of the test suites (4 or 5), etc.  IOW, I'd need to change quite a bit to get it running as package code...

**Comment by peterbud** [comment]
I suggest to read first how to create packages and submit to the repo:
at the [MSYS2 Wiki](https://github.com/msys2/msys2/wiki)
and more specifically at [how to create packages](https://github.com/msys2/msys2/wiki/Creating-Packages)

**Comment by MSP-Greg** [comment]
@peterbud 

Since I wrote the message, a Ruby specific repository for packages has started, so I may place them there.

Sorry I wasn't clearer.  I've been using the packages for several months with Ruby builds.  As I asked:

Would you accept these packages into the repo? Naming okay?

**Comment by larskanis** [comment]
I think this is now obsolete. We handle ruby specific packages in https://github.com/oneclick/rubyinstaller2-packages .
@MSP-Greg  I added your OpenSSL and gdbm there, so IMHO this issue can be closed now.
