### ISSUE TITLE
Qt5 post-install touches more files than it should

### ISSUE THREAD

**Issue by elieux** [Alexpux/MINGW-packages#270]
@mingwandroid says QtBinPatcher should only patch the files it installed, but apparently it patches more than that.

`pacman -S mingw-w64-x86_64-qt5` (`mingw-w64-x86_64-qt5 5.3.2-1`) results in this:
https://gist.github.com/elieux/39fcdde88112b8406e2c

**Comment by Alexpux** [comment]
Fixed.
