### ISSUE TITLE
Windows XP: The procedure entry point _strtod_l could not be located in the dynamic link library msvcrt.dll

### ISSUE THREAD

**Issue by Ede123** [Alexpux/MINGW-packages#2708]
Hi all,

when trying to execute recent builds of Inkscape on Windows XP I get the error noted in the title.
Does anybody have an idea what update might have caused it and how to fix it?

I know it worked not long ago (last build known to work on XP is from April 19th, i.e. three months old).

Unfortunately it's very bad timing as I wanted to use MSYS2 to prepare the next stable Inkscape release (0.92.2) which would be impossible if the cause can not be found in time 😞

**Comment by Ede123** [comment]
OK, source of the issue found - it's the icu upgrade from #2424 in 4e89abf077001e58d16447915b4b8d545719abed

**Comment by mati865** [comment]
XP msvcrt is very limited compared to new supported Windows versions so it's only matter of time when more stuff breaks.

**Comment by Ede123** [comment]
I know, but as long as we do not explicitly drop support for XP we can at least try to support it a little longer.

For me personally this is important as the Inkscape project plans to maintain the current 0.92.x stable branch as some kind of LTS release because with the changes coming in 0.93 it will be unavoidable to drop support for some legacy systems.

**Comment by lazka** [comment]
> For me personally this is important as the Inkscape project plans to maintain the current 0.92.x stable branch as some kind of LTS release because with the changes coming in 0.93 it will be unavoidable to drop support for some legacy systems.

You could also list the last working version for XP on the Download page and be done with it.

**Comment by Ede123** [comment]
That's certainly what I will do if icu should update to version 59.

Until then #2709 seems like a better approach as the fix is simple and everybody who still wants to support XP can profit.

Also I prefer not to require people (and CI) to install a lot of older packages when compatibility can still be provided with current versions. (As an example for why this is problematic: Inkscape still depends on ImageMagick 6 and we already had a report by a developer who accidentally updated to ImageMagick 7 and was wondering why his build broke).
