### ISSUE TITLE
update to clang/llvm 4.0.1?

### ISSUE THREAD

**Issue by paniq** [Alexpux/MINGW-packages#2713]
I'm having issues with clang/llvm 4.0.0, specifically the clang C++ API, which produces segfaults when querying the AST, which was no problem in 3.9.1. I have had related weird behavior on Linux with 4.0.0, which has me suspect that maybe these issues are fixed in 4.0.1, though there is no way of knowing, because I can't seem to find a 4.0.1 changelog.

Are you planning a 4.0.1 update soon? I will put my project on hold for that duration.

**Comment by mati865** [comment]
You can build and test https://github.com/Alexpux/MINGW-packages/pull/2647

**Comment by paniq** [comment]
the segfaults i got are apparently related to getting very weird duplicate symbol errors when linking both clang's static libraries and LLVM (doesn't matter if static or shared) into my app, a problem that did not occur with the 3.9 packages. I used `-Wl,--allow-multiple-definition` to suppress the error but that produces absurd segfaults when touching anything clang related.

That means as the distro is right now I can't use clang at all. So I'm very interested in getting this to work.

How would I go about building and testing this? I've never done this with mingw before.

**Comment by holgern** [comment]
You can build and test #2847

**Comment by mati865** [comment]
I'm already working on it.

**Comment by mati865** [comment]
Status report:
64-bit build works fine, tomorrow I'll build and test 32-bit build.

If both builds are fine I'll open PR tomorrow.

**Comment by mati865** [comment]
Resolved.
