### ISSUE TITLE
ceres-solver won't build, all tests segfault

### ISSUE THREAD

**Issue by ste-ve** [Alexpux/MINGW-packages#2717]
I am trying to build ceres-solver since the binary from pacman is built against an older version of Eigen which causes problems:
> Found Eigen dependency, but the version of Eigen found (3.3.3) does not exactly match the version of Eigen Ceres was compiled with (3.3.0).  This can cause subtle bugs by triggering violations of the One Definition Rule.

However, when trying to build it using the instructed command:
>    cd ceres-solver
>    MINGW_INSTALLS=mingw64 makepkg-mingw -sLf

All of the tests fail with SEGFAULT.

**Comment by peterbud** [comment]
The original author of the package is no longer on GitHub apparently.

I have tried to compile the package and found the following problems:
- Build in my case finds Eigen properly
```
-- Found Eigen version 3.3.3: C:/msys64/mingw64/include/eigen3

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================
```
- Build finds `glog` in a wrong place. `Found Glog: C:/msys64/mingw64/include`. But glog headers are located in `/mingw64/include/glog`. That can be fixed using `GLOG_INCLUDE_DIR_HINTS`, and at least the package compiles
- And I can confirm indeed all tests are failing

**Comment by stahta01** [comment]
Did NOT see segfaults during test. 18% tests passed, 56 tests failed out of 68.

Did see glog issue that peterbud saw.

Tim S.

Tested 32 bit build under Windows 10 (32 bit)
Used MSys2 shell (did NOT use Mingw32 shell)

I have these packages pinned by editing "IgnorePkg" in /etc/pacman.conf
mingw-w64-i686-gcc: 6.3.0-3
mingw-w64-i686-gcc-fortran: 6.3.0-3
mingw-w64-i686-gcc-libgfortran: 6.3.0-3
mingw-w64-i686-gcc-libs: 6.3.0-3

I have an package that has build issues using GCC 7.1; till I fix it I pinned GCC to 6.3


I had to self build mingw-w64-i686-glog package to avoid a msys2/cmake folder bug in it.


==> Starting check()...
Running tests...
Test project C:/PKGBUILD/mingw-w64-ceres-solver/src/build-i686-w64-mingw32
      Start  1: array_utils_test
 1/68 Test  #1: array_utils_test ............................***Exception: Other  2.84 sec
      Start  2: autodiff_test
 2/68 Test  #2: autodiff_test ...............................   Passed    0.52 sec
      Start  3: autodiff_cost_function_test
 3/68 Test  #3: autodiff_cost_function_test .................   Passed    0.50 sec
      Start  4: autodiff_local_parameterization_test
 4/68 Test  #4: autodiff_local_parameterization_test ........***Exception: Other  0.52 sec
      Start  5: block_jacobi_preconditioner_test
 5/68 Test  #5: block_jacobi_preconditioner_test ............***Exception: Other  0.67 sec
      Start  6: block_random_access_dense_matrix_test
 6/68 Test  #6: block_random_access_dense_matrix_test .......***Exception: Other  0.55 sec
      Start  7: block_random_access_diagonal_matrix_test
 7/68 Test  #7: block_random_access_diagonal_matrix_test ....***Exception: Other  0.53 sec
      Start  8: block_random_access_sparse_matrix_test
 8/68 Test  #8: block_random_access_sparse_matrix_test ......***Exception: Other  0.59 sec
      Start  9: block_sparse_matrix_test
 9/68 Test  #9: block_sparse_matrix_test ....................***Exception: Other  0.69 sec
      Start 10: bundle_adjustment_test
10/68 Test #10: bundle_adjustment_test ......................***Exception: Other  0.48 sec
      Start 11: c_api_test
11/68 Test #11: c_api_test ..................................***Exception: Other  0.22 sec
      Start 12: canonical_views_clustering_test
12/68 Test #12: canonical_views_clustering_test .............***Exception: Other  0.31 sec
      Start 13: compressed_row_sparse_matrix_test
13/68 Test #13: compressed_row_sparse_matrix_test ...........***Exception: Other  0.33 sec
      Start 14: conditioned_cost_function_test
14/68 Test #14: conditioned_cost_function_test ..............***Exception: Other  0.27 sec
      Start 15: corrector_test
15/68 Test #15: corrector_test ..............................***Exception: Other  0.28 sec
      Start 16: cost_function_to_functor_test
16/68 Test #16: cost_function_to_functor_test ...............   Passed    0.39 sec
      Start 17: covariance_test
17/68 Test #17: covariance_test .............................***Exception: Other  0.23 sec
      Start 18: cubic_interpolation_test
18/68 Test #18: cubic_interpolation_test ....................   Passed    0.31 sec
      Start 19: detect_structure_test
19/68 Test #19: detect_structure_test .......................***Exception: Other  0.20 sec
      Start 20: dense_sparse_matrix_test
20/68 Test #20: dense_sparse_matrix_test ....................***Exception: Other  0.25 sec
      Start 21: dynamic_autodiff_cost_function_test
21/68 Test #21: dynamic_autodiff_cost_function_test .........   Passed    0.16 sec
      Start 22: dynamic_compressed_row_sparse_matrix_test
22/68 Test #22: dynamic_compressed_row_sparse_matrix_test ...***Exception: Other  0.17 sec
      Start 23: dynamic_numeric_diff_cost_function_test
23/68 Test #23: dynamic_numeric_diff_cost_function_test .....   Passed    0.14 sec
      Start 24: evaluator_test
24/68 Test #24: evaluator_test ..............................***Exception: Other  0.22 sec
      Start 25: gradient_checker_test
25/68 Test #25: gradient_checker_test .......................***Exception: Other  0.20 sec
      Start 26: gradient_checking_cost_function_test
26/68 Test #26: gradient_checking_cost_function_test ........***Exception: Other  0.20 sec
      Start 27: gradient_problem_test
27/68 Test #27: gradient_problem_test .......................***Exception: Other  0.19 sec
      Start 28: gradient_problem_solver_test
28/68 Test #28: gradient_problem_solver_test ................***Exception: Other  0.20 sec
      Start 29: graph_test
29/68 Test #29: graph_test ..................................   Passed    0.64 sec
      Start 30: graph_algorithms_test
30/68 Test #30: graph_algorithms_test .......................   Passed    0.09 sec
      Start 31: householder_vector_test
31/68 Test #31: householder_vector_test .....................   Passed    0.23 sec
      Start 32: is_close_test
32/68 Test #32: is_close_test ...............................***Exception: Other  1.16 sec
      Start 33: implicit_schur_complement_test
33/68 Test #33: implicit_schur_complement_test ..............***Exception: Other  0.36 sec
      Start 34: iterative_schur_complement_solver_test
34/68 Test #34: iterative_schur_complement_solver_test ......***Exception: Other  0.55 sec
      Start 35: jet_test
35/68 Test #35: jet_test ....................................***Exception: Other  0.56 sec
      Start 36: levenberg_marquardt_strategy_test
36/68 Test #36: levenberg_marquardt_strategy_test ...........***Exception: Other  0.61 sec
      Start 37: dogleg_strategy_test
37/68 Test #37: dogleg_strategy_test ........................***Exception: Other  0.53 sec
      Start 38: line_search_preprocessor_test
38/68 Test #38: line_search_preprocessor_test ...............***Exception: Other  0.61 sec
      Start 39: local_parameterization_test
39/68 Test #39: local_parameterization_test .................***Exception: Other  0.38 sec
      Start 40: loss_function_test
40/68 Test #40: loss_function_test ..........................***Exception: Other  0.25 sec
      Start 41: minimizer_test
41/68 Test #41: minimizer_test ..............................***Exception: Other  0.22 sec
      Start 42: normal_prior_test
42/68 Test #42: normal_prior_test ...........................***Exception: Other  0.17 sec
      Start 43: numeric_diff_cost_function_test
43/68 Test #43: numeric_diff_cost_function_test .............***Exception: Other  0.19 sec
      Start 44: ordered_groups_test
44/68 Test #44: ordered_groups_test .........................   Passed    0.33 sec
      Start 45: parameter_block_test
45/68 Test #45: parameter_block_test ........................***Exception: Other  0.20 sec
      Start 46: parameter_block_ordering_test
46/68 Test #46: parameter_block_ordering_test ...............***Exception: Other  0.16 sec
      Start 47: partitioned_matrix_view_test
47/68 Test #47: partitioned_matrix_view_test ................***Exception: Other  0.19 sec
      Start 48: polynomial_test
48/68 Test #48: polynomial_test .............................***Exception: Other  0.25 sec
      Start 49: problem_test
49/68 Test #49: problem_test ................................***Exception: Other  0.33 sec
      Start 50: program_test
50/68 Test #50: program_test ................................***Exception: Other  0.33 sec
      Start 51: reorder_program_test
51/68 Test #51: reorder_program_test ........................***Exception: Other  0.41 sec
      Start 52: residual_block_test
52/68 Test #52: residual_block_test .........................***Exception: Other  0.19 sec
      Start 53: residual_block_utils_test
53/68 Test #53: residual_block_utils_test ...................***Exception: Other  0.38 sec
      Start 54: rotation_test
54/68 Test #54: rotation_test ...............................***Exception: Other  0.16 sec
      Start 55: schur_complement_solver_test
55/68 Test #55: schur_complement_solver_test ................***Exception: Other  0.28 sec
      Start 56: schur_eliminator_test
56/68 Test #56: schur_eliminator_test .......................***Exception: Other  0.39 sec
      Start 57: single_linkage_clustering_test
57/68 Test #57: single_linkage_clustering_test ..............***Exception: Other  1.16 sec
      Start 58: small_blas_test
58/68 Test #58: small_blas_test .............................   Passed    0.13 sec
      Start 59: solver_test
59/68 Test #59: solver_test .................................***Exception: Other  0.55 sec
      Start 60: compressed_col_sparse_matrix_utils_test
60/68 Test #60: compressed_col_sparse_matrix_utils_test .....***Exception: Other  0.61 sec
      Start 61: symmetric_linear_solver_test
61/68 Test #61: symmetric_linear_solver_test ................***Exception: Other  0.50 sec
      Start 62: triplet_sparse_matrix_test
62/68 Test #62: triplet_sparse_matrix_test ..................***Exception: Other  0.69 sec
      Start 63: trust_region_minimizer_test
63/68 Test #63: trust_region_minimizer_test .................***Exception: Other  0.64 sec
      Start 64: trust_region_preprocessor_test
64/68 Test #64: trust_region_preprocessor_test ..............***Exception: Other  0.50 sec
      Start 65: unsymmetric_linear_solver_test
65/68 Test #65: unsymmetric_linear_solver_test ..............***Exception: Other  0.73 sec
      Start 66: visibility_test
66/68 Test #66: visibility_test .............................***Exception: Other  0.53 sec
      Start 67: visibility_based_preconditioner_test
67/68 Test #67: visibility_based_preconditioner_test ........   Passed    0.69 sec
      Start 68: system_test
68/68 Test #68: system_test .................................***Exception: Other  0.78 sec

18% tests passed, 56 tests failed out of 68

Total Test time (real) =  31.63 sec

The following tests FAILED:
          1 - array_utils_test (OTHER_FAULT)
          4 - autodiff_local_parameterization_test (OTHER_FAULT)
          5 - block_jacobi_preconditioner_test (OTHER_FAULT)
          6 - block_random_access_dense_matrix_test (OTHER_FAULT)
          7 - block_random_access_diagonal_matrix_test (OTHER_FAULT)
          8 - block_random_access_sparse_matrix_test (OTHER_FAULT)
          9 - block_sparse_matrix_test (OTHER_FAULT)
         10 - bundle_adjustment_test (OTHER_FAULT)
         11 - c_api_test (OTHER_FAULT)
         12 - canonical_views_clustering_test (OTHER_FAULT)
         13 - compressed_row_sparse_matrix_test (OTHER_FAULT)
         14 - conditioned_cost_function_test (OTHER_FAULT)
         15 - corrector_test (OTHER_FAULT)
         17 - covariance_test (OTHER_FAULT)
         19 - detect_structure_test (OTHER_FAULT)
         20 - dense_sparse_matrix_test (OTHER_FAULT)
         22 - dynamic_compressed_row_sparse_matrix_test (OTHER_FAULT)
         24 - evaluator_test (OTHER_FAULT)
         25 - gradient_checker_test (OTHER_FAULT)
         26 - gradient_checking_cost_function_test (OTHER_FAULT)
         27 - gradient_problem_test (OTHER_FAULT)
         28 - gradient_problem_solver_test (OTHER_FAULT)
         32 - is_close_test (OTHER_FAULT)
         33 - implicit_schur_complement_test (OTHER_FAULT)
         34 - iterative_schur_complement_solver_test (OTHER_FAULT)
         35 - jet_test (OTHER_FAULT)
         36 - levenberg_marquardt_strategy_test (OTHER_FAULT)
         37 - dogleg_strategy_test (OTHER_FAULT)
         38 - line_search_preprocessor_test (OTHER_FAULT)
         39 - local_parameterization_test (OTHER_FAULT)
         40 - loss_function_test (OTHER_FAULT)
         41 - minimizer_test (OTHER_FAULT)
         42 - normal_prior_test (OTHER_FAULT)
         43 - numeric_diff_cost_function_test (OTHER_FAULT)
         45 - parameter_block_test (OTHER_FAULT)
         46 - parameter_block_ordering_test (OTHER_FAULT)
         47 - partitioned_matrix_view_test (OTHER_FAULT)
         48 - polynomial_test (OTHER_FAULT)
         49 - problem_test (OTHER_FAULT)
         50 - program_test (OTHER_FAULT)
         51 - reorder_program_test (OTHER_FAULT)
         52 - residual_block_test (OTHER_FAULT)
         53 - residual_block_utils_test (OTHER_FAULT)
         54 - rotation_test (OTHER_FAULT)
         55 - schur_complement_solver_test (OTHER_FAULT)
         56 - schur_eliminator_test (OTHER_FAULT)
         57 - single_linkage_clustering_test (OTHER_FAULT)
         59 - solver_test (OTHER_FAULT)
         60 - compressed_col_sparse_matrix_utils_test (OTHER_FAULT)
         61 - symmetric_linear_solver_test (OTHER_FAULT)
         62 - triplet_sparse_matrix_test (OTHER_FAULT)
         63 - trust_region_minimizer_test (OTHER_FAULT)
         64 - trust_region_preprocessor_test (OTHER_FAULT)
         65 - unsymmetric_linear_solver_test (OTHER_FAULT)
         66 - visibility_test (OTHER_FAULT)
         68 - system_test (OTHER_FAULT)

**Comment by peterbud** [comment]
@stahta01 : I have been trying to build the minw64 version, and I have 7.1 gcc already.
The segfault is definitely in glog related. Running `array_utils_test.exe`:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000006630fe00 in ?? () from C:\msys64\mingw64\bin\libglog.dll
```
Might it be related to these warnings?
```
[ 43%] Building CXX object internal/ceres/CMakeFiles/test_util.dir/evaluator_test_utils.cc.obj
In file included from C:/msys64/home/peterbud/MINGW-packages/mingw-w64-ceres-solver/src/ceres-solver-1.12.0/internal/ceres/evaluator_test_utils.cc:34:0:
C:/msys64/home/peterbud/MINGW-packages/mingw-w64-ceres-solver/src/ceres-solver-1.12.0/internal/ceres/gtest/gtest.h:10575:55: warning: optimization attribute on 'void testing::internal::PrintTo(wchar_t, std::ostream*)' follows definition but the attribute doesn't match [-Wattributes]
 GTEST_API_ void PrintTo(wchar_t wc, ::std::ostream* os);
                                                       ^
C:/msys64/home/peterbud/MINGW-packages/mingw-w64-ceres-solver/src/ceres-solver-1.12.0/internal/ceres/gtest/gtest.h:10564:13: note: previous definition of 'void testing::internal::PrintTo(bool, std::ostream*)' was here
 inline void PrintTo(bool x, ::std::ostream* os) {
             ^~~~~~~

```

**Comment by ste-ve** [comment]
Also trying to build mingw64 version with 7.1 gcc using the msys2 shell for Windows 7 64-bit. Did not see any problems with build not finding `glog` that would have prevented compiling. The binaries retrieved with `pacman` also segfault from `libglog.dll` as @peterbud saw. Don't have any ideas on how to solve.

**Comment by peterbud** [comment]
@ste-ve : I have [updated](https://github.com/Alexpux/MINGW-packages/pull/2719) `glog` to 0.3.5, and at the same time I have fixed the issue with the glog's generated cmake file, so now cmake will find `glog` without any hint.
With this new glog, I have re-built `ceres-solver`, and all tests successfully [completed](https://pastebin.com/AvvNMxV4).

**Comment by ste-ve** [comment]
@peterbud Thank you! I applied your commit, but all the unit tests from glog [segfault](https://pastebin.com/hTqKQ5h4). 
> (gdb) run
> Starting program: /g/p2/MINGW-packages/mingw-w64-glog/src/build-x86_64-w64-mingw32/demangle_unittest.exe
> [New Thread 18016.0x5030]
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x000000006630fe50 in unw_getcontext () from /g/p2/MINGW-packages/mingw-w64-glog/src/build-x86_64-w64-mingw32/libglog.dll

What might be the difference since it seems to build fine for you?

**Comment by peterbud** [comment]
As I read you are building under MSYS2 shell? While building works that way, maybe that is influencing your tests? Have you tried to build under MINGW64 shell?

**Comment by ste-ve** [comment]
@peterbud 
I have tried the MSYS2 MSYS shell and the MSYS2 MINGW64 shell, both give the same result.

**Comment by peterbud** [comment]
@ste-ve : I really don't know. Here is my [build log](https://pastebin.com/vHWakzbL), maybe you can compare. At first sight they are pretty identical.

I have the following dependencies:
```
mingw-w64-x86_64-gcc 7.1.0-2
mingw-w64-x86_64-cmake 3.8.2-2
mingw-w64-x86_64-gflags 2.2.0-1
```
Maybe somebody else can give a try with `glog` build?

**Comment by stahta01** [comment]
I will give it a try later today. I am almost ready to stop using GCC 6.3; after I upgrade to GCC 7.1 I will try building glog using peterbud repo glog branch. Tim S.
Plan on only doing 64 bit build on Windows 7 64 bit Home Prem. Ed.
Tim S.

**Comment by stahta01** [comment]
It works for me.
Tim S.
`# Steps start below
# Fresh MSys2 installation to be sure that I do NOT have some package that makes it work.
pacman -Syuu                      # Repeat until nothing needs updated

pacman -S base-devel              # Choose all
pacman -S mingw-w64-x86_64-gcc


# Build glog steps start below
cd "C:\PKGBUILD\mingw-w64-glog"
MINGW_INSTALLS=mingw64 makepkg-mingw -sLf   # Install all the packages it needs/wants

Running tests...
Test project C:/PKGBUILD/mingw-w64-glog/src/build-x86_64-w64-mingw32
    Start 1: demangle
1/3 Test #1: demangle .........................   Passed    0.06 sec
    Start 2: logging
2/3 Test #2: logging ..........................   Passed    1.62 sec
    Start 3: stl_logging
3/3 Test #3: stl_logging ......................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 3


pacman -Qs mingw-w64-x86_64-gcc && pacman -Qs mingw-w64-x86_64-cmake && pacman -Qs mingw-w64-x86_64-gflags

local/mingw-w64-x86_64-gcc 7.1.0-2 (mingw-w64-x86_64-toolchain)
    GNU Compiler Collection (C,C++,OpenMP) for MinGW-w64
local/mingw-w64-x86_64-gcc-libs 7.1.0-2 (mingw-w64-x86_64-toolchain)
    GNU Compiler Collection (libraries) for MinGW-w64
local/mingw-w64-x86_64-cmake 3.8.2-2
    A cross-platform open-source make system (mingw-w64)
local/mingw-w64-x86_64-gflags 2.2.0-1
    Google's Commandline flags module for C++ (mingw-w64)
`

**Comment by ste-ve** [comment]
I did a fresh install of MSys2 and followed Tim's steps above for Peter's glog 0.3.5 update. I do not know why the fresh install was needed since my previous installation was just one week old and I hadn't changed anything that should have broken things, but now both glog and ceres build flawlessly. Thanks a lot to both of you for the help, really appreciate it.
