### ISSUE TITLE
c-ares doesn't support static linking

### ISSUE THREAD

**Issue by Jimmy-Z** [Alexpux/MINGW-packages#2740]
there is no libcares.a, only libcares.dll.a
````
~$ pacman -Ql mingw-w64-x86_64-c-ares|grep /lib/
mingw-w64-x86_64-c-ares /mingw64/lib/
mingw-w64-x86_64-c-ares /mingw64/lib/libcares.dll.a
mingw-w64-x86_64-c-ares /mingw64/lib/pkgconfig/
mingw-w64-x86_64-c-ares /mingw64/lib/pkgconfig/libcares.pc
````
for comparison:
````
~$ pacman -Ql mingw-w64-x86_64-expat|grep /lib/
mingw-w64-x86_64-expat /mingw64/lib/
mingw-w64-x86_64-expat /mingw64/lib/libexpat.a
mingw-w64-x86_64-expat /mingw64/lib/libexpat.dll.a
mingw-w64-x86_64-expat /mingw64/lib/pkgconfig/
mingw-w64-x86_64-expat /mingw64/lib/pkgconfig/expat.pc
````

looks like it needs `--disable-shared` to get static but I'm not sure.
https://github.com/c-ares/c-ares/blob/master/INSTALL.md#more-options
current [PKGBUILD](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-c-ares/PKGBUILD#L36-L37) uses `--enable-shared` together with `--enable-static`

**Comment by irakhlin** [comment]
When i build c-ares with --enable-static --disable-shared I get a seemingly correct static library, the generated libcares.pc has -DCARES_STATICLIB defined which seem correct for using the library in linking. I have also successfully been able to use the libcares.a to build a fully static curl.exe using the library. It seems the best idea may be to do a two step build like we do for some current packages like mingw-w64-gmp, first performing a build for static only, then another build for shared only and combining them into one package if this is something you think will be useful to you I could submit a pull request.

**Comment by irakhlin** [comment]
The only issue I can see in correctly managing between the linking of a static library and a shared library is the Cflags issue. When linking statically the libcares.pc file should have:
Cflags: -I${includedir} -DCARES_STATICLIB
Unfortunately pkg-config does not have support for a Cflags.private value that would be perfect in situations like this and would only be emitted when linking statically ie pkg-config --static. I'm not sure if the correct solution would be to have the package additionally generate libcares-static.pc or if the -DCARES_STATICLIB could be added to the Libs.private: value, granted its not a "library" so I am not sure if this is correct or if it could have unexpected consequences.

**Comment by irakhlin** [comment]
I have made this pull request with some of the changes I mentioned here; https://github.com/Alexpux/MINGW-packages/pull/2827

We will see what people  have to say about how I handled the need for -DCARES_STATICLIB but it seems to work fine for me.
