### ISSUE TITLE
Add mingw-w64-jasper as a dependency for mingw-w64-qt5-static

### ISSUE THREAD

**Issue by tgharib** [Alexpux/MINGW-packages#2753]
I was having trouble linking the static version of Qt (although the dynamic version worked) and I was getting jasper linker errors. Luckily, I found the fix to the issue: https://github.com/Alexpux/MINGW-packages/issues/1703 and I was able to solve it by doing `pacman -S mingw-w64-x86_64-jasper`

Normally I would submit a pull request but the PKGBUILD looks complex.

**Comment by martinrotter** [comment]
This is probably not fixed: https://ci.appveyor.com/project/martinrotter/textilosaurus/build/666.490#L1839
