### ISSUE TITLE
qtcreator could not find platform windows

### ISSUE THREAD

**Issue by markand** [Alexpux/MINGW-packages#2766]
Hello,

Any attempt to run a program build with mingw-w64-x86_64-qt5 fails with:

````
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".
````

It's the same for mingw-w64-x86_64-qt-creator.

**Comment by mati865** [comment]
You have to copy all required Qt DLLs (or use tool that does it for you http://doc.qt.io/qt-5/windows-deployment.html).
In this specific case you need also `/mingw64/share/qt5/plugins/platforms/qwindows.dll` to be copied into `platforms\qwindows.dll`.

**Comment by elieux** [comment]
Tentatively closing. OP can reopen if necessary.

**Comment by elieux** [comment]
Thanks, @mati865.

**Comment by markand** [comment]
Then maybe you can add a notice in the package information because it's not mentioned so you install a package and it doesn't work and not explained why.Le 11 août 2017 4:24 PM, Mateusz Mikuła <notifications@github.com> a écrit :You have to copy all required Qt DLLs (or use tool that does it for you http://doc.qt.io/qt-5/windows-deployment.html).
In this specific case you need also /mingw64/share/qt5/plugins/platforms/qwindows.dll to be copied into platforms\qwindows.dll.

**Comment by mati865** [comment]
@markand are you running package from Qt Creator or via console/file manager?

**Comment by markand** [comment]
1. I open MSYS2 MinGW 64 bit
2. I've installed mingw-w64-x86_64-qt-creator
3. I've ran qt-creator

**Comment by mati865** [comment]
I mean are you starting program you build with Qt Creator run (ctrl+r shortcut) or 'manually' (from console or fileanager)?

**Comment by markand** [comment]
Sorry the issue's title is misneaming.

I'm saying that mingw-w64-x86_64-qt-creator's `qtcreator` binary is unable to start. And it's the same case for all programs built with Qt5.

**Comment by markand** [comment]
Okay I've ran `pacman -Syu` and qtcreator run correctly from MSYS2 shells, no idea what changed but it works.

**Comment by elieux** [comment]
Cool. Thanks for letting us know.

**Comment by wrightsg** [comment]
This happens again (?) with the current version of the `qt-creator` package (mingw64) in MSYS2.

Starting `qtcreator` from a mingw64 shell results in the following error message.

This application failed to start because it could not find or load the Qt platform plugin "windows" in "".
Reinstalling the application might fix the problem.

Reinstalling `qtcreator` did not fix the problem. Neither did running `pacman -Syu` as suggested above.

**Comment by Alexpux** [comment]
Run /mingw64/bin/qtbinpatcher —force —no-backup

**Comment by wrightsg** [comment]
The issue still persists after running `qtbinpatcher --force --nobackup --qt-dir=/mingw64/bin` (the `--qt-dir` option was necessary for `qtbinpatcher` to find `qmake`).
