### ISSUE TITLE
Error building mingw-w64-glib2

### ISSUE THREAD

**Issue by ladserg** [Alexpux/MINGW-packages#279]
Error log:

      CC       libgio_2_0_la-gsocketclient.lo
      CC       libgio_2_0_la-gsocketconnectable.lo
    ../../glib-2.42.0/gio/gsocket.c:1934:1: error: conflicting types for 'if_nametoindex'
     if_nametoindex (const gchar *iface)
     ^
    In file included from J:/1/msys64/mingw64/x86_64-w64-mingw32/include/iphlpapi.h:16:0,
                     from ./gnetworking.h:35,
                     from ../../glib-2.42.0/gio/gnetworkingprivate.h:22,
                     from ../../glib-2.42.0/gio/gsocket.c:60:
    J:/1/msys64/mingw64/x86_64-w64-mingw32/include/netioapi.h:318:20: note: previous declaration of 'if_nametoindex' was here
     NET_IFINDEX WINAPI if_nametoindex(
                        ^
    Makefile:2803: recipe for target 'libgio_2_0_la-gsocket.lo' failed
    make[4]: *** [libgio_2_0_la-gsocket.lo] Error 1
    make[4]: *** Waiting for unfinished jobs....
    make[4]: Leaving directory '/home/ladserg/mingw-w64-glib2/src/build-x86_64-shared/gio'

**Comment by jtanx** [comment]
Not sure if it's specifically related to this issue, but Windows XP support for glib is broken by [this patch](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-glib2/0026-define-HAVE_IF_NAMETOINDEX.patch#L8).

See also, fontforge/fontforge#2027

**Comment by Kevin551** [comment]
This bug is also being talked about here - 
http://sourceforge.net/p/msys2/tickets/132/

**Comment by elieux** [comment]
Is the issue solved now, @Kevin551, @ladserg?

**Comment by Alexpux** [comment]
Fixed.
