### ISSUE TITLE
ffmpeg doesn't run, missing libopenjpeg-5.dll after the update to 2.2.0? (MINGW64)

### ISSUE THREAD

**Issue by avih** [Alexpux/MINGW-packages#2799]
`mingw64/mingw-w64-x86_64-ffmpeg 3.3.3-1 [installed]`

After the update (from today I think) of `ffmpeg` and `libopenjpeg`, when running `ffmpeg` from the MINGW64 env, it prints the following message to the console:
`... /bin/ffmpeg.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory`

From the same env, if running `strace ffmpeg`,  (though strace seems msys rather than mingw64) then it opens a windows error dialog with:
```
ffmpeg.exe - System Error
---------------------------
The program can't start because libopenjpeg-5.dll is missing from your computer. Try reinstalling the program to fix this problem. 
```

```
$ ls /mingw64/bin/libopenj*
/mingw64/bin/libopenjp2-7.dll  /mingw64/bin/libopenjp3d-7.dll
/mingw64/bin/libopenjpip-7.dll  /mingw64/bin/libopenjpwl-7.dll

$ ls /mingw64/lib/libopenj*
/mingw64/lib/libopenjp2.a      /mingw64/lib/libopenjp3d.a
/mingw64/lib/libopenjpip.dll.a   /mingw64/lib/libopenjpwl.dll.a
/mingw64/lib/libopenjp2.dll.a  /mingw64/lib/libopenjp3d.dll.a
/mingw64/lib/libopenjpwl.a
```

**Comment by avih** [comment]
Hmm... apparently I had `mingw64/mingw-w64-x86_64-openjpeg2` installed, but ffmpeg wants `mingw64/mingw-w64-x86_64-openjpeg` (not 2).

After `pacman -S mingw-w64-x86_64-openjpeg` which installed and completed successfully, ffmpeg now runs.

Incorrect dependency for ffmpeg?

**Comment by lazka** [comment]
Similar to b30ed50d20968bfa6dd06eab38181d3dab98e731 I think. ffmpeg only looked for openjpeg 2.1 and used 1.5 instead.

**Comment by lazka** [comment]
one possible patch based on an upstream one: https://bugs.gentoo.org/show_bug.cgi?id=627562#c7

**Comment by lazka** [comment]
See #2804

**Comment by lazka** [comment]
Should be fixed (once ffmpeg is rebuilt)

**Comment by avih** [comment]
Confirmed fixed - I removed ffmpeg and all its dependencies, including openjpeg (1) and 2, then installed ffmpeg again and it works.

Thanks.
