### ISSUE TITLE
Cmake.exe: error while loading shared libraries

### ISSUE THREAD

**Issue by MaartenBent** [Alexpux/MINGW-packages#2803]
Cmake (`mingw-w64-x86_64-cmake (3.9.1-1)` ) does not run, giving the following error.
```
cmake.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

Installing `mingw-w64-x86_64-libidn2 (2.0.3-1)` fixes the problem.
I guess this dependency should be installed automatically?

**Comment by stahta01** [comment]
I see three possible solutions.
1. Add run-time dependency to  mingw-w64-x86_64-libidn2
2. Link to static libuv (I am guessing this might fix the issue)
3. Build cmake to use internal libuv. (This is also a guess)

Tim S.

**Comment by Optiligence** [comment]
it seams to be a dependency of mingw-w64 curl

**Comment by MaartenBent** [comment]
I see. Then #2801 should fix it.

**Comment by multiplemonomials** [comment]
I just had this same issue.  Fixed by updating mingw64-openssl to the latest version.
