### ISSUE TITLE
Assimp package upgrade

### ISSUE THREAD

**Issue by sdegrande** [Alexpux/MINGW-packages#2810]
(Sorry if it's not the right way for such a request)

Could you please update the assimp package to the latest release (4.0.0) ?

Thanks for your invaluable work !

**Comment by stahta01** [comment]
Found the source code for version 4.0 on this website; it is NOT listed on the sf.net website. 
http://www.assimp.org/main_downloads.html

@sdegrande can you build an MSys2 Mingw package from a git repo?
If yes, I might try updating the package; but, I have no knowledge of the package; 
so, I can NOT test the package.

Tim S.

**Comment by peterbud** [comment]
I was able to update to 4.0.1, but unit tests are failing:
```
$ ./unit.exe
[==========] Running 130 tests from 64 test cases.
[----------] Global test environment set-up.
[----------] 1 test from utProfiler
[ RUN      ] utProfiler.addRegion_success
[       OK ] utProfiler.addRegion_success (1 ms)
[----------] 1 test from utProfiler (1 ms total)

[----------] 1 test from utD3MFImporterExporter
[ RUN      ] utD3MFImporterExporter.import3MFFromFileTest
```

**Comment by sdegrande** [comment]
It seems that a commit fixing that bug was reverted (inadvertently ?).
I get in touch with the assimp devs.

**Comment by Alexpux** [comment]
Currently 4.0.1 not building for mingw during missing ````timeapi.h```` header

**Comment by peterbud** [comment]
I have replaced that with `#include <mmsystem.h>` and then it has compiled. As far as I remember only one function was the reason of including `timeapi.h`

**Comment by Alexpux** [comment]
Assimp updated

**Comment by peterbud** [comment]
@Alexpux: have you managed to run also the unitests successfully?

**Comment by Alexpux** [comment]
I'm not run unittests

**Comment by sdegrande** [comment]
A big thanks for the update.

For your information, the failing unit test is due to a problem in the 3MF importer (the 3MF format is a 3D printing format). So the impact is very limited. The issue has been fixed in the git repository.
