### ISSUE TITLE
Hivex 

### ISSUE THREAD

**Issue by steve4444** [Alexpux/MINGW-packages#2828]
I am trying to build hivex with   MSYS2  mingw64 subsystem.
It is a tool for editing offline registry hives in a cross-platform fashion, see [hivex](https://github.com/libguestfs/hivex), [libguestfs ](http://libguestfs.org). 

The build is based on autotools.  `automake` and `./configure`  work, but  `make` gives, when compiling `mmap.lo`:

    In file included from hivex-internal.h:26:0,
                     from mmap.c:17:
    byte_conversions.h:21:10: fatal error: byteswap.h: No such file or directory
     #include <byteswap.h>
              ^~~~~~~~~~~~
    compilation terminated.
    make[3]: *** [Makefile:1517: mmap.lo] Error 1

Any help?

**Comment by mati865** [comment]
`byteswap.h` is glibc header, most likely you will have to write missing functions yourself.

**Comment by lazka** [comment]
This removed the include guards: https://github.com/libguestfs/hivex/commit/ae748799b816aadc200ccbada1bed3b3ce13bd5c#diff-a19f5c0fd785f97fde350ab3a805e4f9

My guess would be that you need to call the bootstrap script before autotools.

Please ask upstream how to build for mingw (there is mingw stuff in the code, so it seems at least somewhat supported)
