### ISSUE TITLE
Version of the update package is smaller than the local package

### ISSUE THREAD

**Issue by ChinouneMehdi** [Alexpux/MINGW-packages#2846]
With the last upgrade some warnings show :
warning: mingw-w64-x86_64-curl: local (7.55.1-2) is newer than mingw64 (7.55.1-1)
warning: mingw-w64-x86_64-libuv: local (1.14.0-1) is newer than mingw64 (1.12.0-1)
warning: mingw-w64-x86_64-python2: local (2.7.13-2) is newer than mingw64 (2.7.13-1)

**Comment by mati865** [comment]
@Alexpux `mingw64.db` points to `mingw-w64-x86_64-curl-7.55.1-1`. Looks like something went wrong.

**Comment by Alexpux** [comment]
@mati865  I know, will fix some later today

**Comment by Alexpux** [comment]
Fixed
