### ISSUE TITLE
please update faac and faad2

### ISSUE THREAD

**Issue by fabiangreffrath** [Alexpux/MINGW-packages#2850]
faac has been updated upstream to version 1.29.7.4 and faad2 to version 2.8.1.

https://sourceforge.net/projects/faac/files/

Please update the packages accordingly, thanks!

**Comment by Alexpux** [comment]
Done

**Comment by fabiangreffrath** [comment]
Thanks! Please note that your remaining patches have been upstreamed just now. ;)
