### ISSUE TITLE
Boost 1.65

### ISSUE THREAD

**Issue by Alexpux** [Alexpux/MINGW-packages#2853]
Updating boost to 1.65 is not possible because of next issues:
https://svn.boost.org/trac/boost/ticket/12205 (patch from previous versions not solve problem)
and
````
//
// Thread local storage:
// Note fails on Mingw, see https://sourceforge.net/p/mingw-w64/bugs/527/
//
````

**Comment by ArekPiekarz** [comment]
Does Boost 1.65.1 release candidate fix this?
https://lists.boost.org/Archives/boost/2017/09/238441.php
(Note that subject of that mail is wrong, it's not 1.65.2.)

**Comment by Alexpux** [comment]
You can try to build and see

**Comment by ArekPiekarz** [comment]
I haven't tried building yet, but the final version 1.65.1 came out and it contains a fix for thread local storage (among other things):
http://www.boost.org/users/history/version_1_65_1.html
https://github.com/boostorg/stacktrace/commit/cd420b37ae7e84196cdb8202e489d5d276c55f0b

**Comment by Alexpux** [comment]
1.65.1 doesnt build because of 
https://svn.boost.org/trac10/ticket/12205

**Comment by pedash** [comment]
I've just successfully build current 1.66 master branch from https://github.com/boostorg/boost

**Comment by ArekPiekarz** [comment]
I think the next steps would be to do git bisect, find which commit fixed the build and backport it.
It's also possible that it was fixed "by accident" with changes to functionality, in which case it would require more effort to extract the proper fix.
Who's up for the challenge?

**Comment by ArekPiekarz** [comment]
Boost 1.66 is out, it should have fixes for the issues from above.

**Comment by ArekPiekarz** [comment]
Thanks for upgrading to 1.66, this can be closed.

For anyone trying it with CMake, you will encounter errors, because CMake doesn't support Boost 1.66 yet. See:
https://gitlab.kitware.com/cmake/cmake/issues/17575
https://gitlab.kitware.com/cmake/cmake/merge_requests/1621
https://gitlab.kitware.com/cmake/cmake/merge_requests/1625
For now you have to hack FindBoost.cmake yourself.

**Comment by TBBle** [comment]
The updated [FindBoost.cmake](https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindBoost.cmake) should work for Msys2, as it does not use the 'versioned' layout that depends on other CMake 3.11 changes. I did this as part of my validation testing for the FindBoost.cmake changes.

Alternatively, you can explicitly tell CMake to accept Boost 1.66 in CMake 3.10, and it'll work for the variables, but not the imported targets.
