### ISSUE TITLE
Debug and Release sets of Packages

### ISSUE THREAD

**Issue by subdivider** [Alexpux/MINGW-packages#2856]
Hello, it would be nice to have two separate sets of MinGW-Packages targeting Debug and Release configuration. Also MinGW shell should add ability to internally switch between Debug and Release configuration. I am MSYS2 newbie, so maybe I am missing something, but I can't see this functionality.

**Comment by Alexpux** [comment]
Sorry, but this is impossible because of lack of time. If you need debug version - you need build it yourself.

**Comment by subdivider** [comment]
Ok, thank You for Your immediate response!
