### ISSUE TITLE
git breakage

### ISSUE THREAD

**Issue by lazka** [Alexpux/MINGW-packages#2879]
```
$ git pull
fatal: unable to access 'https://github.com/Alexpux/MINGW-packages.git/': error setting certificate verify locations:
  CAfile: /usr/ssl/certs/ca-bundle.crt
  CApath: none
```

Looks like some of the recent updates. Any ideas?

**Comment by jtanx** [comment]
Possibly https://github.com/Alexpux/MSYS2-packages/pull/992; tried manually installing libunistring?

**Comment by lazka** [comment]
Thanks. That did did not help here, libunistring is already installed.

**Comment by Alexpux** [comment]
This is breakage in p11-kit package, that was recently updated.

**Comment by lazka** [comment]
ok, this works in the mean time: `GIT_SSL_NO_VERIFY=1 git pull`

**Comment by Alexpux** [comment]
````trust```` command are broken for 64-bit msys2. 32-bit is ok

**Comment by avih** [comment]
> trust command are broken for 64-bit msys2. 32-bit is ok

Is this new? the two `/usr/ssl/certs/ca-bundle.*` files are now empty (zero size), and and I think that's the cause for the failure of OP - I have the same issue.

As a workaround, for now I locally copied these two files from git-for-windows - which makes git work again, but I think the CA-certificates package is currently broken.

It was working fine yesterday.

**Comment by Alexpux** [comment]
@avih broken ````p11-kit```` package as certificates are generating by it

**Comment by holgern** [comment]
I found the cause, it is the updated msys2-runtime-2.9.0  and msys2-runtime-devel-2.9.0 !!!

I rebuild p11-kit  with msys2-runtime-2.8.2 and  msys2-runtime-devel-2.8.2 and everything works now.

**Comment by holgern** [comment]
After installing msys2-runtime-2.8.2 and then msys2-runtime-2.9.0 it kept working...

**Comment by holgern** [comment]
Commit https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=commit;h=f22054c94d3f77ba834d55123ffa9fe4aef6f93c
leads to broken p11-kit

**Comment by holgern** [comment]
I found a fix
https://github.com/Alexpux/MSYS2-packages/pull/996

**Comment by holgern** [comment]
cygwin 2.9.0 introduced a new api for strnstr.
p11-kit searches for strnstr and found that one from msys2-runtime which leads to the not working trust.exe.

So now we kann revert the strnstr function from cygwin, (which i did) or we patch p11-kit in a way that it uses in own implementation of strnstr. 
An other possibility is to investigate the error and to write a bug report for cygwin or for p11-kit

**Comment by lazka** [comment]
Things work again here. Thanks @holgern @Alexpux
