### ISSUE TITLE
gdb broken

### ISSUE THREAD

**Issue by Ede123** [Alexpux/MINGW-packages#2882]
I updated MSYS2 today and it seems gdb version 8.0.1-1 is broken (downgrading to version 8.0-2 seems to fix the issue).

When running `gdb` there's no output at all on the console and the command simply returns. Exit code is 127.

(it was last updated in 8e599b5f671d2d323ca8b73e5a1ae74eefba61fe by @Alexpux, so that's probably when the regression was introduced)

**Comment by lazka** [comment]
Only seems to affect the mingw64 version

**Comment by ninepillars** [comment]
I found this bug too. Yes, only affect the mingw64 version
