### ISSUE TITLE
mingw-w64-x86_64-headers-git update

### ISSUE THREAD

**Issue by ChinouneMehdi** [Alexpux/MINGW-packages#2889]
warning: mingw-w64-x86_64-headers-git: local (5.0.0.4965.6fcf4f9b-1) is newer than mingw64 (5.0.0.4965.a1047045-1)

**Comment by mati865** [comment]
Git hashes are unpredictable but it doesn't happen often.
Just run `pacman -Syuu`.

**Comment by ArekPiekarz** [comment]
pacman -Syuu is just a workaround. The real solution would be to:
1. Add something before the commit hash, for instance a number, that would be higher than the previous version of the package, or
2. Change pacman to ignore the commit hash in the version, or
3. Not include the hash in the version.

The first solution should be easy to implement while also retaining valuable information of the commit in the version. What do you think about it?
