### ISSUE TITLE
Comment on package folder renames

### ISSUE THREAD

**Issue by stahta01** [Alexpux/MINGW-packages#2909]
@lazka

In #2878 PR the folders where renamed to match package base name.

I suggest that in the future if the foldername and packagebasename only differs in case that the packagebasename be changed. TortiseGit did NOT like the foldername only being changed only in case.

Note: To fix the TortiseGit issue just rename the folder to a new name (not using git rename);
and, then rename to the correct name with the correct case.

Tim S.

**Comment by lazka** [comment]
Sorry for the troubles :(

I also had to do a double rename for git rename to actually work, but updating between the commits seemed to work fine. I'll keep that in mind.

I guess reverting it again wont help much now?

**Comment by stahta01** [comment]
Correct reverting will hurt instead of helping. Tim S.
