### ISSUE TITLE
gedit - Failed to load libgedit DLL

### ISSUE THREAD

**Issue by Shreeshrii** [Alexpux/MINGW-packages#291]
$ pacman -S mingw32/mingw-w64-i686-gedit
warning: mingw-w64-i686-gedit-3.14.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-i686-gedit-3.14.0-1

Total Download Size:    1.96 MiB
Total Installed Size:  13.27 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages ...
 mingw-w64-i686-gedit-3.14.0-1-any             2004.9 KiB  56.5K/s 00:35 [########################################] 100%
(1/1) checking keys in keyring                                           [########################################] 100%
(1/1) checking package integrity                                         [########################################] 100%
(1/1) loading package files                                              [########################################] 100%
(1/1) checking for file conflicts                                        [########################################] 100%
(1/1) checking available disk space                                      [########################################] 100%
(1/1) reinstalling mingw-w64-i686-gedit                                  [########################################] 100%
warning: Schema 'org.gnome.system.locale' has path '/system/locale/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy' has path '/system/proxy/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.http' has path '/system/proxy/http/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.https' has path '/system/proxy/https/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.ftp' has path '/system/proxy/ftp/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.socks' has path '/system/proxy/socks/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.

User@HP ~
$ gedit
Failed to load libgedit DLL

User@HP ~
$

**Comment by nacho** [comment]
Changed it to give some more info: https://git.gnome.org/browse/gedit/commit/?id=89a68722290274db6e6bd9119c1c1cdc7eecc22b

**Comment by Alexpux** [comment]
Fixed.
