### ISSUE TITLE
gdb 8.0.1 freezes on quit

### ISSUE THREAD

**Issue by pedash** [Alexpux/MINGW-packages#2914]
Just updated to gdb 8.0.1-1 and Qt Creator 4.4.0-1 from mingw64 and found out that gdb freezes on quit(). Also it returns to shell with some delay on gdb --version. That (probably) makes QtCreator unable to determine gdb properties properly. GDB from msys is 7.11 version and it works fine.

**Comment by lazka** [comment]
See #2882

**Comment by Alexpux** [comment]
GDB rebuilded with system readline to fix crash
