### ISSUE TITLE
meld3 -  mingw32/bin/gtk-update-icon-cache-3.0: Permission denied

### ISSUE THREAD

**Issue by Shreeshrii** [Alexpux/MINGW-packages#292]
$ pacman -S mingw32/mingw-w64-i686-meld3
resolving dependencies...
looking for conflicting packages...

Packages (3) mingw-w64-i686-python2-cairo-1.10.0-1  mingw-w64-i686-python2-gobject-3.14.0-1
             mingw-w64-i686-meld3-3.12.0-1

Total Download Size:   0.48 MiB
Total Installed Size:  2.11 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages ...
 mingw-w64-i686-python2-cairo-1.10.0-1-any       28.0 KiB   172K/s 00:00 [########################################] 100%
 mingw-w64-i686-python2-gobject-3.14.0-1-any    166.7 KiB  71.4K/s 00:02 [########################################] 100%
 mingw-w64-i686-meld3-3.12.0-1-any              294.9 KiB  64.0K/s 00:05 [########################################] 100%
(3/3) checking keys in keyring                                           [########################################] 100%
(3/3) checking package integrity                                         [########################################] 100%
(3/3) loading package files                                              [########################################] 100%
(3/3) checking for file conflicts                                        [########################################] 100%
(3/3) checking available disk space                                      [########################################] 100%
(1/3) installing mingw-w64-i686-python2-cairo                            [########################################] 100%
(2/3) installing mingw-w64-i686-python2-gobject                          [########################################] 100%
(3/3) installing mingw-w64-i686-meld3                                    [########################################] 100%
/tmp/alpm_hvxrMs/.INSTALL: line 2: mingw32/bin/gtk-update-icon-cache-3.0: Permission denied
warning: Schema 'org.gnome.system.locale' has path '/system/locale/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy' has path '/system/proxy/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.http' has path '/system/proxy/http/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.https' has path '/system/proxy/https/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.ftp' has path '/system/proxy/ftp/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.socks' has path '/system/proxy/socks/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.

**Comment by elieux** [comment]
I'd say this is the same as #141.
