### ISSUE TITLE
Split boost into headers + libs?

### ISSUE THREAD

**Issue by lazka** [Alexpux/MINGW-packages#2943]
gtk-doc has an optional dependency on source-highlight which in turn depends on boost. I left that out for now as boost is 252MB installed. Looking at arch I see that it splits boost into headers + libs which brings the runtime dependency down to 11MB.

Would splitting boost into "boost" and "boost-libs" be a good idea in msys2 as well?

**Comment by Alexpux** [comment]
I prefer to not split mingw packages at all.

**Comment by lazka** [comment]
OK
