### ISSUE TITLE
Could you add proxychains？

### ISSUE THREAD

**Issue by eromoe** [Alexpux/MINGW-packages#2946]
Hi, it is a very useful tool 
https://github.com/rofl0r/proxychains-ng

But I can't make it on msys2
```
$ make && make install
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/nameinfo.o src/nameinfo.c
src/nameinfo.c:1:10: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:81: src/nameinfo.o] Error 1

```

**Comment by jtanx** [comment]
> ProxyChains is a **UNIX** program, that hooks network-related libc functions
  in DYNAMICALLY LINKED programs via a preloaded DLL

> Supported Platforms: Linux, BSD, Mac.

**Comment by mati865** [comment]
There is no way it will work under Cygwin/MSYS2 or MinGW.

**Comment by eromoe** [comment]
That's a sad news...  
So, is there any altinative of proxychains for msys2 ?

**Comment by mati865** [comment]
> How do I distinguish a program can work in msys2 or not?

It depends which UNIX APIs they use and this project seems to be using low level APIs.
Keep in mind Cygwin (and it's fork MSYS2) is not replacement for UNIX, it makes porting easier.

However it seems to work in WSL in Windows 10 version 1703:
```
[proxychains] config file found: src/proxychains.conf
[proxychains] preloading ./libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12-git-2-g46647be
Trying 224.0.0.1...
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  google.com:80  ...  OK
Connected to google.com.
```
