### ISSUE TITLE
all gst packages are uptodate except gst-libav

### ISSUE THREAD

**Issue by filnet** [Alexpux/MINGW-packages#2976]
All gstreamer related packages have been updated to 1.12.3 recently and made available.
All except gst-libav which has not been published (yet).

mingw32/mingw-w64-i686-gst-editing-services 1.12.3-1 [installed]
mingw32/mingw-w64-i686-gst-libav **1.12.2-1** [installed]
mingw32/mingw-w64-i686-gst-plugins-bad 1.12.3-1 [installed]
mingw32/mingw-w64-i686-gst-plugins-base 1.12.3-1 [installed]
mingw32/mingw-w64-i686-gst-plugins-good 1.12.3-1 [installed]
mingw32/mingw-w64-i686-gst-plugins-ugly 1.12.3-1 [installed]
mingw32/mingw-w64-i686-gst-python 1.12.3-1 [installed]
mingw32/mingw-w64-i686-gst-rtsp-server 1.12.3-1 [installed]
mingw32/mingw-w64-i686-gstreamer 1.12.3-1 [installed]

**Comment by lazka** [comment]
It's there now: http://quodlibet.duckdns.org/msys2/updates

**Comment by filnet** [comment]
Great. Thanks !
