### ISSUE TITLE
gpg uses wrong 'home'

### ISSUE THREAD

**Issue by Karlson2k** [Alexpux/MINGW-packages#2989]
gpg use 'home' subdir inside 'mingw64' dir instead of 'HOME' env variable. 
````
$ LANG=c gpg --version
gpg (GnuPG) 2.2.0-unknown
libgcrypt 1.8.1
NOTE: THIS IS A DEVELOPMENT VERSION!
It is only intended for test purposes and should NOT be
used in a production environment or with production keys!
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: C:/msys64/mingw64/home
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

$ echo $HOME
/home/User-Name
````

**Comment by peterbud** [comment]
#2743 was supposed to fix this, but was not merged

**Comment by Karlson2k** [comment]
@peterbud Looks like @Alexpux asked to updated patches against latest version.
To my experience, patches for current version merged pretty quickly in this repo.
Could you update your patches?

**Comment by peterbud** [comment]
See #2999

**Comment by Alexpux** [comment]
Won't fix

**Comment by Karlson2k** [comment]
@Alexpux do you mean that you do not want to fix or do you mean that you are waiting for right patches?
Or you treat it as 'by design'?

**Comment by Alexpux** [comment]
Mingw gnupg can bee installed outside msys2 tree. In this case home folder will be broken. 
All mingw packages are not related to msys2 filesystem so I can't do shared gnupg folder for both mingw and msys gnupg
