### ISSUE TITLE
mingw-w64-git not found?

### ISSUE THREAD

**Issue by prasannavl** [Alexpux/MINGW-packages#3003]
Hi, I'm trying to install mingw version of the git, with the potential goal of experimenting with replacing the git official package with mingw built ones by adding a set of symlinks to the system PATH of the necessary commands.

However, I was surprised to see that I couldn't actually install it with pacman, although I do see a package of the same name in this repo: `pacman -S mingw-w64-git`/`pacboy -S git:m` fails with target not found. 

Perhaps, I misunderstood something? Would appreciate any help. Thanks.

**Comment by ArekPiekarz** [comment]
From pacboy help:

> For 64-bit MSYS2, name:i means i686-only
> For 64-bit MSYS2, name:x means x86_64-only
> For MSYS shell, name:m means mingw-w64
> For all shells, name: disables any translation for name
> For all shells, repository::name means repository/name

I don't know which shell you used, but I'm using 64-bit one and this worked for me:
`pacboy sync git:`

**Comment by prasannavl** [comment]
@ArekPiekarz, unless I've mistaken, what you just installed was the `msys` package from the `msys-packages` repo. It's not the `mingw` package that's in this repo. They're not the same. The first line of my post also hints at why the differentiation is vital.

**Comment by elieux** [comment]
@prasannavl, correct.

Our mingw-w64-git build is not too great due to our path conversion heuristic and the hybrid nature of Git.  AFAIK that's why it's not part of the distribution.  See [Git for Windows](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper) for a way to install mingw-w64-git.

I'm closing this ticket as a duplicate, but if you want to discuss further, let's.

**Comment by prasannavl** [comment]
@elieux - Thanks for the clarification! Incidentally, I also ended up stumbling upon few other discussions that are related. Just gathering them here, should someone else run into this:

- [Git for Windows](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper) (provided above by @elieux )
- https://stackoverflow.com/questions/40262434/what-are-the-differences-between-msys-git-and-git-for-windows-mingw-w64-x86-64-g
- https://github.com/git-for-windows/git/issues/1277#issuecomment-324867068
- https://github.com/git-for-windows/git/issues/284
