### ISSUE TITLE
Could not find GNU Guile in repo.

### ISSUE THREAD

**Issue by metab0t** [Alexpux/MINGW-packages#3017]
I cannot find GNU Guile in mingw x86-64 repo although I see that it is in github repo.
BTW, would you mind updating Guile to version 2.2?

**Comment by Alexpux** [comment]
Guile not buildable for 64 bit. I will not produce half building packages in repo

**Comment by metab0t** [comment]
Thanks for your reply!
Hope Guile becomes buildable in future releases.
