### ISSUE TITLE
Port request : Chicken scheme

### ISSUE THREAD

**Issue by metab0t** [Alexpux/MINGW-packages#3025]
Would you love to port chicken scheme to mingw? 
It seems easy to build in mingw environment and has no dependency.
[Chicken](https://www.archlinux.org/packages/community/x86_64/chicken/)

**Comment by lazka** [comment]
@metab0t See https://github.com/msys2/msys2/wiki/Creating-packages for how to create a package and send a PR.

**Comment by metab0t** [comment]
PR sent
#3026
