### ISSUE TITLE
mingw-w64-gtk3 depends on MSYS2 gtk-doc (which depends on python2 / python2-six)

### ISSUE THREAD

**Issue by Ede123** [Alexpux/MINGW-packages#3028]
I just tried to compile [mingw-w64-gtk3](https://github.com/Alexpux/MINGW-packages/blob/78eb955cfedf34adb704f46e3a834465561d222c/mingw-w64-gtk3/PKGBUILD) and noticed it seems to depend on MSYS2 gtk-doc.

Specifically the build broke during package as I did not have python2-six:
```
 /usr/bin/install -c -m 644 ./html/zoom_out_cursor.png
Traceback (most recent call last):
  File "/usr/bin/gtkdoc-rebase", line 28, in <module>
    from gtkdoc import common, config, rebase
  File "/usr/share/gtk-doc/python/gtkdoc/rebase.py", line 28, in <module>
    from six import iteritems, iterkeys
ImportError: No module named six
make[4]: *** [Makefile:1033: install-data-local] Fehler 1
make[4]: Verzeichnis „/e/Temp/MSYS2/MINGW-packages/mingw-w64-gtk3/src/build-x86_64-w64-mingw32/docs/reference/gdk“ wird verlassen
```

It builds properly when adjusting makedepends (which could be a quick fix), but I'm not sure it's even supposed to use gtk-doc (specifically the MSYS2 version) here?
@lazka: You recently switched some packages to mingw-w64-gtk-doc. Should this be done here, too, or is it enough to depend on the MSYS2 version?

**Comment by Ede123** [comment]
[mingw-w64-gtk3-3.22.21-1-x86_64-log.zip](https://github.com/Alexpux/MINGW-packages/files/1367223/mingw-w64-gtk3-3.22.21-1-x86_64-log.zip)

**Comment by Ede123** [comment]
P.S. I'm not sure what package installed gtk-doc in the first place  (and why it didn't install python2-six, too).
P.P.S. Strike the part in brackets, the missing dependency was fixed in https://github.com/Alexpux/MSYS2-packages/commit/13230a6ea535c2515c5b7f539fdefa33730c2386 but it seems the fix did not make it into the repo yet.

**Comment by Ede123** [comment]
So in conclusion maybe nothing needs to be done at all here except updating gtk-doc in the repo (at least everything builds properly then)...

**Comment by lazka** [comment]
* https://github.com/Alexpux/MSYS2-packages/pull/1003 not being included/build in the repo.
* gtk3 missing a gtk-doc makedepends (either msys or mingw, whichever works..)

**Comment by lazka** [comment]
See #3030

**Comment by lazka** [comment]
I think this can be closed

**Comment by Ede123** [comment]
OK, thanks.
(please be aware that fixes are not yet in the repo, though)
