### ISSUE TITLE
missing dependency for mingw-w64-x86_64-poppler

### ISSUE THREAD

**Issue by jspraul** [Alexpux/MINGW-packages#3031]
error while loading shared libraries: libpoppler-59.dll: cannot open shared object file: No such file or directory

$ ls /c/msys64/mingw64/lib/*poppler*
/c/msys64/mingw64/lib/libpoppler.a
/c/msys64/mingw64/lib/libpoppler.dll.a
/c/msys64/mingw64/lib/libpoppler-cpp.a
/c/msys64/mingw64/lib/libpoppler-cpp.dll.a
/c/msys64/mingw64/lib/libpoppler-glib.a
/c/msys64/mingw64/lib/libpoppler-glib.dll.a
/c/msys64/mingw64/lib/libpoppler-qt5.a
/c/msys64/mingw64/lib/libpoppler-qt5.dll.a

**Comment by lazka** [comment]
What program showed the error?

the shared library is in /bin btw

**Comment by jspraul** [comment]
Thanks for the pointer to the shared library. Here is the command in different paths:

MINGW64 /
$ pdftotext
C:/msys64/mingw64/bin/pdftotext.exe: error while loading shared libraries: libpoppler-59.dll: cannot open shared object file: No such file or directory

MINGW64 /c/msys64/mingw64/bin
$ pdftotext
C:/msys64/mingw64/bin/pdftotext.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

**Comment by lazka** [comment]
Huh, weird. pdftotext links against libpoppler-70.dll and both are in the same package. No idea.

**Comment by jspraul** [comment]
I will pacman -Syu a few times, 1 sec. It's been a while.

**Comment by jspraul** [comment]
Now it looks like this:

 MSYS /c/msys64/mingw64
$ bin/pdftotext.exe
C:/msys64/mingw64/bin/pdftotext.exe: error while loading shared libraries: libpoppler-70.dll: cannot open shared object file: No such file or directory

Possibly related: https://github.com/Alexpux/MINGW-packages/issues/2852

**Comment by GuilGA45** [comment]
I have had the same problem with pdfimages. It was a missing dependency for openjpeg2. It seems that poppler now depend on openjpeg2 instead of openjpeg.

**Comment by lazka** [comment]
@GuilGA45 looks like that's it, thanks!
