### ISSUE TITLE
Is `PPCFLAGS` a typo?

### ISSUE THREAD

**Issue by lhmouse** [Alexpux/MINGW-packages#3033]
cbrt on IRC mentioned this today:

https://github.com/Alexpux/MINGW-packages/blob/77794e876df75103b8a62fa116caaf0f008fc761/mingw-w64-python-scandir/PKGBUILD#L33

**Comment by mati865** [comment]
Sure it is, you can see 5 lines above :wink:

**Comment by cbrt64** [comment]
That was me, see [PR 3088](https://github.com/Alexpux/MINGW-packages/pull/3088).

**Comment by cbrt64** [comment]
Resolved, patches merged, thanks @Alexpux!

**Comment by lhmouse** [comment]
:)
