### ISSUE TITLE
mingw-w64-x86_64-qt5-5.9.2-1 broken

### ISSUE THREAD

**Issue by gbschenkel** [Alexpux/MINGW-packages#3036]
After upgrading to the last version, all .exe of the packages don't work, they ask for .dll, like Qt5Core.dll
Doing the downgrade resolves the problem.
I have attached both ldd output of Qt5Core.dll

[qt5-5.9.2-1.txt](https://github.com/Alexpux/MINGW-packages/files/1377580/qt5-5.9.2-1.txt)
[qt5-5.9.1-1.txt](https://github.com/Alexpux/MINGW-packages/files/1377587/qt5-5.9.1-1.txt)

**Comment by kelteseth** [comment]
Can confirm QtCreator no longer works.
![qttt](https://user-images.githubusercontent.com/1071536/31487699-aff0aac2-af3b-11e7-98fa-296cd694e48a.PNG)
