### ISSUE TITLE
new qt-5.9.2-1 package with Utils4.dll problems

### ISSUE THREAD

**Issue by DirkMausF** [Alexpux/MINGW-packages#3040]
After updating qt-5.9.1 to qt-5.9.2, qtcreator.exe doesn't start anymore on my system. 
Error: "/qtcreator.exe: error while loading shared libraries: Utils4.dll: cannot open shared object file: No such file or directory".

Downgrading to qt-5.9.1 fixes this. If i update to qt-5.9.2 and downgrade qtcreator to 4.4.0, it fails with the same error.

In the /bin directory there is a Util4.dll, ever after the update, but qt - not qtcreator - seems to have problems loading it.

Greetings, Dirk

**Comment by mati865** [comment]
Install pcre2 MinGW package.

**Comment by DirkMausF** [comment]
All right, that fixed it. Thanks!

**Comment by isavaskan** [comment]
I have the same problem. Some installed packages: 
qt-creator 4.7.1, qt5 5.11.2, pcre2 10.32
Also, it is strange that ldd cannot find Utils4 dependency for qtcreator.
