### ISSUE TITLE
mingw-w64-fluidsynth: new upstream available (1.1.7)

### ISSUE THREAD

**Issue by fabiangreffrath** [Alexpux/MINGW-packages#3041]
Hi there,

a new version of fluidsynth, 1.1.7, has been released recently. It brings the ability to use sound fonts in SF3 format, e.g. the one bundled with musescore. Please consider packaging it for MSYS2, thanks!

 - Fabian

**Comment by lazka** [comment]
-> https://github.com/msys2/msys2/wiki/Creating-packages

**Comment by fabiangreffrath** [comment]
Understood. I have no experience yet with using CMake in MSYS2 (fluidsynth switched to CMake with the 1.1.7 release). Is there any package that could serve as "best practice" example?

**Comment by lazka** [comment]
There are some example packages under https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-PKGBUILD-templates

**Comment by fabiangreffrath** [comment]
Thanks! I'll see what I get done over the weekend.
