### ISSUE TITLE
silent uic error in qt5-5.9.2

### ISSUE THREAD

**Issue by elhuhdron** [Alexpux/MINGW-packages#3042]
uic fails without any error message in appveyor build, this did not occur in qt5-5.9.1
building a fork of knossos with appveyor against qt5 (not qt5-static):
https://github.com/elhuhdron/knossos/blob/ea444ac2ad45d62c03425370af574134de077224/.appveyor_build.sh
I'm able to install qt5-5.9.1 as a workaround for now.

FAILED: CMakeFiles/knossos_autogen 
cmd.exe /C "cd /D C:\msys64\home\appveyor\knossos-build && C:\msys64\mingw64\bin\cmake.exe -E cmake_autogen C:/msys64/home/appveyor/knossos-build/CMakeFiles/knossos_autogen.dir RELEASE"
Exit code 0xc0000135

AutoUic: Error: uic process failed for
"include/ui_aboutdialog.h" needed by
"C:/projects/knossos/widgets/aboutdialog.cpp"
AutoUic: Command:
C:/msys64/mingw64/bin/uic.exe -o C:/msys64/home/appveyor/knossos-build/knossos_autogen/include/ui_aboutdialog.h C:/projects/knossos/widgets/aboutdialog.ui
AutoUic: Command output:

Generating UIC header include/ui_aboutdialog.h
ninja: build stopped: subcommand failed.

**Comment by mati865** [comment]
Try installing pcre2

**Comment by elhuhdron** [comment]
Yes. Didn't realize this could be the same issue as previously reported. Thanks!
