### ISSUE TITLE
libpq-fe.h is missing from mingw-w64-postgresql

### ISSUE THREAD

**Issue by miniwark** [Alexpux/MINGW-packages#3067]
`libpq-fe.h` is a header file commonly requested to build postgresql related tools (in my case pgModeler). 

On linux distribd it is generaly disbributed in pakages like `postgresql-devel` or `postgresql-libs`.

Could you please add this file to `the mingw-w64-postgresql` packages (or maybe create a package for this sort of stuff ?)

**Comment by lazka** [comment]
I see "/mingw32/include/libpq-fe.h" in the file list for mingw-w64-i686-postgresql. Are you sure it's missing?

**Comment by miniwark** [comment]
@lazka thanks you are right. The file was indeed directly in `C:/msys64/mingw64/include`.
I was looking only in `C:/msys64/mingw64/include/postgresql` and `C:/msys64/mingw64/include/libpq`.
