### ISSUE TITLE
diff.exe considers two different files to be the same

### ISSUE THREAD

**Issue by karen-arutyunov** [Alexpux/MINGW-packages#3076]
Hello,

While moving from msys2 diffutils to mingw diffutils for our build2 toolchain project, we have discovered that mingw diff utility sometimes considers different files to be the same. The specifics of the use case is that the files being compared are auto-generated at the very close time points.

The problem is that prior to comparing files content, for optimization, diff utility compares the file inodes and attributes with the following code (resides in src/diff.c file of the upstream package):

```
  ...
  else if ((same_files
           = (cmp.file[0].desc != NONEXISTENT
              && cmp.file[1].desc != NONEXISTENT
              && 0 < same_file (&cmp.file[0].stat, &cmp.file[1].stat)
              && same_file_attributes (&cmp.file[0].stat,
                                       &cmp.file[1].stat)))
              && no_diff_means_no_output)
    {
      /* The two named files are actually the same physical file.
         We know they are identical without actually reading them.  */
    }
  ...
```

Given that st_ino member of the stat structure is set to zero by stat() function call (as inodes are Unix-specific), and the st_ctime/st_mtime members has a second resolution, we can expect diff utility to misbehave quite often for the same-sized, “simultaneously” created, located on the same drive files. The issue is easily reproducible with the following command executed in mingw console, having the corresponding mingw-w64-*-diffutils package installed:

$ echo "X">X && echo "Y">Y && diff X Y

We have fixed the issue making the same_file() macro (is defined in src/system.h file of the upstream package) to expand to (-1) on Windows, which disables the broken optimization.

I have attached the patches for MINGW-packages/mingw-w64-diffutils package in case you find them useful for the issue fix.

Thanks,
Karen
[mingw-w64-diffutils.tar.gz](https://github.com/Alexpux/MINGW-packages/files/1413898/mingw-w64-diffutils.tar.gz)

**Comment by karen-arutyunov** [comment]
Also noticed that diffutils package in the repository is quite outdated. Do you plan to update it?

**Comment by karen-arutyunov** [comment]
I turns out that this issue is already fixed in the upstream package (3.6). Gnulib's stat() function replacement now fills st_ino using information provided by GetFileInformationByHandle*() functions.

So upgrade from the current 3.3 to the latest 3.6 would be highly appreciated.

**Comment by karen-arutyunov** [comment]
The mingw-w64-diffutils 3.6 package is now available. However the issue is still there.

This happens because, while being implemented, the distinguishable inodes support is disabled by default in the upstream package (see WINDOWS_STAT_INODES macro usage).

To enable the support you need to run make with an additional agrument in the PKGBUILD file:

make WINDOWS_STAT_INODES=1

I have attached the patch for MINGW-packages/mingw-w64-diffutils package in case you find it useful for the issue fix:

[mingw-w64-diffutils.tar.gz](https://github.com/Alexpux/MINGW-packages/files/2119096/mingw-w64-diffutils.tar.gz)

**Comment by peterbud** [comment]
Hi @karen-arutyunov , thanks for the suggestion, indeed, it's much better. I have just submitted a PR with these changes. Once those will be merged, we can close this issue.
Please note however that still a few test cases are failing even with this setting, so further work would be needed (the msys version of `difftools` does not have these failures)
```
============================================================================
Testsuite summary for GNU diffutils 3.6
============================================================================
# TOTAL: 20
# PASS:  12
# SKIP:  1
# XFAIL: 0
# FAIL:  7
# XPASS: 0
# ERROR: 0

```

**Comment by karen-arutyunov** [comment]
Cool, thanks.
