### ISSUE TITLE
libcurl 7.56.0-3 cause segmenation faults

### ISSUE THREAD

**Issue by Karlson2k** [Alexpux/MINGW-packages#3091]
Libcurl is used by libmicrohttpd for testing (by `make check`).
With libcurl version 7.56.0-3 almost all tests with libcurl are failed.
Reverting to 7.55.1-2 solved problem.

**Comment by lazka** [comment]
What about 7.56.1 currently open as PR (#3077) ?

https://ci.appveyor.com/api/buildjobs/7ves1jvscjddm4tp/artifacts/artifacts%2Fmingw-w64-i686-curl-7.56.1-1-any.pkg.tar.xz

https://ci.appveyor.com/api/buildjobs/ubcvtfp111kj7rah/artifacts/artifacts%2Fmingw-w64-x86_64-curl-7.56.1-1-any.pkg.tar.xz

Download and install with "pacman -U"

**Comment by Karlson2k** [comment]
@lazka 
No, same crashes as with 7.56.0-3.

Version 7.55.1-2 still works fine.

**Comment by lazka** [comment]
ok, thanks. No idea.

**Comment by Karlson2k** [comment]
Upstream PR: https://github.com/curl/curl/pull/2083

**Comment by lazka** [comment]
Looking at https://curl.haxx.se/changes.html this was fixed with 7.57.0 and both msys/mingw curl is now at 7.57.0 -> closing.
