### ISSUE TITLE
Build Poppler

### ISSUE THREAD

**Issue by MatthD** [Alexpux/MINGW-packages#3100]
Hi everyone,

I am trying to use Mingw-package to build poppler dll & exe on windows & make its exe file works (>0.59).
I do not understand how to do it :s 

I am on osx but I can use linux too.

Is there already pre-build version I can download somewhere ?

Thanks

**Comment by MatthD** [comment]
In fact my aim is to get poppler-utils (some .exe to use) & poppler dll in the newer version (0.6)
Ok so what `pacman -S mingw-w64-i686-poppler` does ?

**Comment by lazka** [comment]
The poppler utils are included in that package: https://quodlibet.duckdns.org/msys2/package/mingw-w64-i686-poppler?repo=mingw32

> Ok so what pacman -S mingw-w64-i686-poppler does ?

It installs the library.

If you need 0.60 you'll need to work on updating it.

**Comment by MatthD** [comment]
Hum.. I installed MSYS2 on windows 10
Then I did a `pacman -S mingw-w64-i686-poppler` & it installed 
`Paquets (1) mingw-w64-i686-poppler-0.48.0-1`

That's an old version of poppler it should have install the 0.59.2 version like https://quodlibet.duckdns.org/msys2/package/mingw-w64-i686-poppler?repo=mingw32

What could be the problem ?

**Comment by mati865** [comment]
@MatthD You probably haven't done `pacman -Syu` earlier.
Do it now and you will have all packages upgraded.

**Comment by lazka** [comment]
poppler is now at 0.62.0 in the repo

for getting the newer version do what @mati865 said.
