### ISSUE TITLE
glib-mkenums artifacts in generated header files

### ISSUE THREAD

**Issue by KrullBorg** [Alexpux/MINGW-packages#3131]
^
make[3]: *** [Makefile:592: goocanvasatk.lo] Error 1
make[3]: *** Attesa per i processi non terminati....
make[3]: *** [Makefile:592: goocanvasenumtypes.lo] Error 1
make[3]: *** [Makefile:592: goocanvasgrid.lo] Error 1
In file included from goocanvas.h:11:0,
                 from goocanvasgroup.c:42:
./goocanvasenumtypes.h:10:2: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
 C:/msys64/* Enumerations from "goocanvasitem.h" */
  ^
./goocanvasenumtypes.h:13:2: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
 C:/msys64/* Enumerations from "goocanvasutils.h" */
  ^
goocanvasgroup.c: In function 'goo_canvas_group_get_common_property':
goocanvasgroup.c:262:64: warning: character constant too long for its type
       G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);

**Comment by lazka** [comment]
Likely the same problem as fixed in https://github.com/Alexpux/MINGW-packages/pull/2710/commits/cce600dd3ef924035ef264cc9c2f9844358ca8ef
