### ISSUE TITLE
[mingw-w64-perl] "runperl" is broken

### ISSUE THREAD

**Issue by niklasholm** [Alexpux/MINGW-packages#3167]
The `003-replace-batch-scripts-with-bare-perl.patch` for this package installs `runperl.pl` as `runperl` directly, without converting it to a batch file (`.bat`). However, runperl is not meant to be called directly like this, if it is, it results in an infinite exec loop. This is actually mentioned in the manpage for perlwin32.

**Comment by lazka** [comment]
I know nothing about perl, but I remember someone writing that the msys2/mingw perl is broken in various ways. Feel free to improve I guess :)

**Comment by niklasholm** [comment]
I would but I'm struggling to understand how to work with these patch-files. What workflow would I use to update them correctly? It's very frustrating since the change itself is quite simple, but this setup with patch-files makes it all that more complicated. I've tried importing them into git and quilt but then when exporting the patches again the output format is different.
