### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ZachBacon** [Alexpux/MINGW-packages#3170]
So when utilizing license=() can we please make the efford to use the SPDX format, so say for every use of GPL2 it should be GPL-2.0 etc
the format for the licenses are shown on this site. 
https://spdx.org/licenses/

**Comment by lazka** [comment]
https://wiki.archlinux.org/index.php/PKGBUILD#license

**Comment by ZachBacon** [comment]
That's all good and well, but again though, formating is wrong, no one should be using GPL or GPL2, it's incorrect formating.

**Comment by lazka** [comment]
As stated in the wiki it's referencing the "GPL2" directory in the Arch "licenses" package, which contains the complete license text. It's just an ID/alias and not the proper name. There might be cases where the license ID is wrong, but "GPL" and "GPL2" are both present in the licenses package.

**Comment by ZachBacon** [comment]
That's what I dislike about arch. But we aren't archlinux. This is msys2. But I guess on this matter we can agree to disagree on formating in PKGBUILDS.

**Comment by Chocobo1** [comment]
I like this idea but I doubt it will be accepted here.

>That's what I dislike about arch. 

There is no gain to dislike OSS without putting an effort to change it. 

Why not try raising awareness at https://lists.archlinux.org/listinfo/pacman-dev or https://lists.archlinux.org/listinfo/arch-dev-public ?

**Comment by lazka** [comment]
All in all SPDX seems like a good thing to me (lots of licenses, covering all the common exceptions/variants)

Maybe we can propose a "custom:spdx:<spdx license expression>" format to Arch?

**Comment by lazka** [comment]
There is a recent thread discussing SPDX on arch-dev-public: https://lists.archlinux.org/pipermail/arch-dev-public/2019-October/029695.html
