### ISSUE TITLE
potrace missing shared library

### ISSUE THREAD

**Issue by Ede123** [Alexpux/MINGW-packages#3183]
After the last potrace update in 53c82de61106c4904bae4c81e1b2fea486f38200 (see #3172) the package is missing the shared library `libpotrace-0.dll`.

@stambaughw - do you know why?

**Comment by stambaughw** [comment]
All I did was change the upstream revision and the sha256sum for the new
source archive.  I did not change any of the build configuration
settings so it must be something internal to the potrace build config
that is causing the issue.  I missed the fact that the shared library
did not get built.

**Comment by stambaughw** [comment]
I did a bit of testing and there is something odd going on here.  If I
run makepkg-mingw from an msys2 shell, only the static library is built.

If I open a mingw32 shell and run the following from the potrace 1.15
source path:

autoreconf -if
mkdir build-mingw32
cd build-ming32
../configure --prefix=/mingw32 --mandir=/ming32/share/man \
  --with-libpotrace
make

both the static and dynamic libraries are built as expected and `make
install` would install everything as expected.  I'm not sure what is
going on with makepkg-mingw but it's not working as I would expect it to.

I don't have any more time to look into this so if the shared library is
important, feel free to revert my pull request.

Wayne

**Comment by Ede123** [comment]
Fixed in d20b2a5a71410955e10f348c9ad07cee39408b2a
