### ISSUE TITLE
Qt 5.10 QVector index out of range error 

### ISSUE THREAD

**Issue by kelteseth** [Alexpux/MINGW-packages#3202]
Steps to reproduce:

1.  Create new Project -> Application -> Qt Quick Applicaton - Stack
2.  Use the App for like 5 - 30 seconds

ASSERT failure in QVector<T>::at: "index out of range", file ../../../../include/QtCore/../../src/corelib/tools/qvector.h, line 423

**Comment by Alexpux** [comment]
Report it to Qt not here. I\m only build it but not maintain sources

**Comment by kelteseth** [comment]
@Alexpux ok thanks for the great work!
