### ISSUE TITLE
mpv does not support this configuration and will not run - rebuild mpv instead.

### ISSUE THREAD

**Issue by wurui1994** [Alexpux/MINGW-packages#3204]
ffmpeg library versions:
   libavutil       55.58.100 (runtime 55.78.100)
   libavcodec      57.89.100 (runtime 57.107.100)
   libavformat     57.71.100 (runtime 57.83.100)
   libswscale      4.6.100 (runtime 4.8.100)
   libavfilter     6.82.100 (runtime 6.107.100)
   libswresample   2.7.100 (runtime 2.9.100)
ffmpeg version: 3.4

mpv was compiled against a different version of FFmpeg/Libav than the shared
library it is linked against. This is most likely a broken build and could
result in misbehavior and crashes.

mpv does not support this configuration and will not run - rebuild mpv instead.

Exiting... (Fatal error)

**Comment by fabiangreffrath** [comment]
https://anonscm.debian.org/cgit/pkg-multimedia/mpv.git/tree/debian/patches/06_ffmpeg-abi.patch

**Comment by Alexpux** [comment]
Fixed
