### ISSUE TITLE
 matplotlib's dependency on qt should be optional

### ISSUE THREAD

**Issue by Readon** [Alexpux/MINGW-packages#3218]
Every time the installation of matplotlib requires qt lib, which will increase the download file size and disk usage up to several gigabytes.
However matplotlib is a multi-backend tools, it can work with tk, gtk, qt and others where qt is optional.
Why not add the qt requirements to optional dependency section?

**Comment by stahta01** [comment]
It is likely because MSys2 mingw qt5 package is one monolithic package; instead of smaller packages.
I am guessing it really needs qt5-base to run even when not using the qt5 GUI packages. This is based on 5 minutes at looking at the ArchLinux packages.

Tim S.

**Comment by lazka** [comment]
qt5 is an optional dependency: https://matplotlib.org/users/installing.html#dependencies

**Comment by lazka** [comment]
I haven't tried anything code wise, but I've found some upstream discussion on this issue:

https://bugs.archlinux.org/task/41744?project=5&string=python-matplotlib

https://github.com/matplotlib/matplotlib/issues/3679

**Comment by lazka** [comment]
From what I see we can remove the dependency once https://github.com/matplotlib/matplotlib/pull/9795 is done and released.

**Comment by Wybxc** [comment]
I found this: https://bugs.archlinux.org/task/41820. It mentions that there is a pull request about this in matplotlib: https://github.com/matplotlib/matplotlib/pull/9795.

**Comment by Readon** [comment]
It seems that we should wait until the release of matplotlib 3.0, cause [matplotlib#9551](https://github.com/matplotlib/matplotlib/pull/9551) has just been merged in June,2018.

**Comment by lazka** [comment]
matplotlib 3 is out and it's Python 3 only. Any objections to upgrading to it?

https://mail.python.org/pipermail/matplotlib-announce/2018-September/000027.html

**Comment by lazka** [comment]
I've created #3218
