### ISSUE TITLE
Problem with hypot and _hypot  when building python lib.

### ISSUE THREAD

**Issue by eromoe** [Alexpux/MINGW-packages#3224]
From https://stackoverflow.com/questions/10660524/error-building-boost-1-49-0-with-gcc-4-7-0/12124708#12124708

Found the answer in [this forum post](http://boost.2283326.n4.nabble.com/Boost-Python-Compile-Error-s-GCC-via-MinGW-w64-tp3165793p3166757.html). It seems that *pyconfig.h* has the following lines:

    #if defined(__GNUC__) && defined(_WIN32)
    // ...
    #define hypot _hypot
    // ...
    #endif /* GNUC */

but *cmath* included with MinGW expects the function to be named `hypot` and not `_hypot`, which causes the compilation errors:

```
    D:/msys64/mingw32/include/c++/7.2.0/cmath:1136:11: error: '::hypot' has not been declared
       using ::hypot;
               ^~~~~
    error: command 'D:\\msys64\\mingw32\\bin\\gcc.exe' failed with exit status 1
```

**Comment by lazka** [comment]
I don't see the hypot define in python2/3 pyconfig.h. Maybe it got removed?

Is this still a problem?

**Comment by lazka** [comment]
> Is this still a problem?

If yes please comment here. I'm closing this for now.
