### ISSUE TITLE
mingw-w64-x86_64-mpv doesn't work

### ISSUE THREAD

**Issue by AlvinJian** [Alexpux/MINGW-packages#3226]
Version: mingw-w64-x86_64-mpv-0.27.0-1
Symptom: mpv doesn't work at all. console log are:
* $>mpv [video file]: nothing happen. $? shows 53.
* $>mpv.com [video file]
   C:/msys64/mingw64/bin/mpv.com: error while loading shared libraries: ?: cannot open shared object file: No such file or directory. $? shows 127

**Comment by mati865** [comment]
Try running `C:/msys64/mingw64/bin/mpv.exe` from Windows console (`cmd.exe`), it should show name of missing library.

**Comment by AlvinJian** [comment]
It said "The code execution cannot be processed because libcdio-1.6.dll was not  found". I printed the file list of libcdio and found "mingw-w64-x86_64-libcdio /mingw64/bin/libcdio-17.dll" instead of libcdio-1.6.dll. Will rebuilding mpv work?

**Comment by mati865** [comment]
It was already updated to 0.27.0 6 days ago.

Are your packages up to date?
You can find installed mpv version with `pacman -Q mpv`.

2017-12-20 18:55 GMT+01:00 AlvinJian <notifications@github.com>:

**Comment by AlvinJian** [comment]
$ pacman -Q mingw-w64-x86_64-mpv
mingw-w64-x86_64-mpv 0.27.0-1

$ pacman -Si mingw-w64-x86_64-mpv
Repository      : mingw64
Name            : mingw-w64-x86_64-mpv
Version         : 0.27.0-1
Description     : Video player based on MPlayer/mplayer2 (mingw-w64)
Architecture    : any
URL             : https://mpv.io/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      :  [...]
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 1129.26 KiB
Installed Size  : 4160.00 KiB
Packager        : Alexey Pavlov <alexpux@gmail.com>
Build Date      : Wed, Dec 13, 2017 11:47:01 PM
Validated By    : MD5 Sum  SHA-256 Sum  Signature

**Comment by Alexpux** [comment]
will upload new package soon
