### ISSUE TITLE
pygi key event handler crash on 64-bit with 'de' keyboard layout

### ISSUE THREAD

**Issue by totaam** [Alexpux/MINGW-packages#3228]
To reproduce the crash in a ming64 environment with Windows-7:
* set your keyboard layout to german 'de' (I'm sure other keyboard layouts are affected - just not sure which keys are) - picture of a german keyboard: [KB_Germany.svg](https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:KB_Germany.svg)
* run the python test code (5 lines of code) and focus its window
* hit the key to the right of the left-shift key (not present on 'us' layouts..)

You then get this crash:
`ERROR:../../pygobject-3.26.1/gi/pygi-argument.c:1004:_pygi_argument_to_object: code should not be reached`
That's when we try to access the "string" attribute of the [GdkEventKey](https://developer.gnome.org/gdk3/stable/gdk3-Event-Structures.html#GdkEventKey). All the other attributes are fine.

Here's the test case: [gtk3_key_crash.py](http://xpra.org/trac/browser/xpra/trunk/src/tests/xpra/test_apps/gtk3_key_crash.py)

**Comment by lazka** [comment]
Thank, forwarded upstream: https://bugzilla.gnome.org/show_bug.cgi?id=791867

**Comment by lazka** [comment]
Should be handled upstream.

**Comment by lazka** [comment]
Does this only happen on 64bit?

I can't reproduce the issue, but there is a chance #3496 might fix it if that's the case.

**Comment by totaam** [comment]
> Does this only happen on 64bit?

Just checked, and yes, it seems so.
I've just rebuilt pygobject 3.28.1 and ran my example again, unfortunately it still crashes with the same error.

**Comment by lazka** [comment]
ok, thanks for testing
