### ISSUE TITLE
Newest runtime causes issues with the Rust programming language

### ISSUE THREAD

**Issue by tspiteri** [Alexpux/MINGW-packages#3237]
I've already posted the details to the Rust issue page: https://github.com/rust-lang/rust/issues/47048, but I'm cross-posting here as I don't know if it's a rustc issue or a MinGW issue.

Basically, after commit https://github.com/Alexpux/MINGW-packages/commit/aba4a3a57e3e964706644a4aad039716ce5e7e41 updated the runtime to version 6.0.0.5066.61efe559, rustc is unable to link to freshly compiled C libraries that use stdout owing to an undefined reference to `__imp___acrt_iob_func`.

**Comment by csstaub** [comment]
I'm seeing a similar problem with linking in CGO: https://github.com/square/ghostunnel/pull/145

Build breaks with:
```
set CGO_ENABLED=1
go build -o ghostunnel-%GIT_VERSION%-windows-%GOARCH%-with-pkcs11.exe -ldflags "-w -extldflags \"-static\" -extld=%EXTLD%" -i .
# github.com/square/ghostunnel
C:\go\pkg\tool\windows_amd64\link.exe: running x86_64-w64-mingw32-gcc failed: exit status 1
C:/msys64/MINGW64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../lib\libltdl.a(libltdl_libltdl_la-lt__alloc.o):(.text+0x3b): undefined reference to `__imp___acrt_iob_func'
collect2.exe: error: ld returned 1 exit status
```

**Comment by mati865** [comment]
It should be reported to mingw-w64-public mailing list, preferably with minimal example.
