### ISSUE TITLE
Question: OpenMP in clang

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#3278]
What is the level of OpenMP support in the current `clang `in mingw64?

**Comment by mati865** [comment]
Upstream doesn't support it on mingw-w64.

**Comment by peterbud** [comment]
Thanks @mati865 . Is my assumption also correct that `-fsanitize=address` is not supported either?

**Comment by mati865** [comment]
Sanitizer works only on 64 bit Linux and Mac.

**Comment by mati865** [comment]
Sanitizer works only on 64 bit Linux and Mac.

**Comment by peterbud** [comment]
Sigh. Thank you!

**Comment by LebedevRI** [comment]
@mati865
> Sanitizer works only on 64 bit Linux and Mac.

That's not quite true.
http://lab.llvm.org:8011/builders/sanitizer-windows/
https://github.com/google/sanitizers/wiki/AddressSanitizerWindowsPort
I believe the official release exe's do have ASAN, i did not try though.
And they are clearly not working in the mingw's clang.
