### ISSUE TITLE
mingw32-make is misbehaving

### ISSUE THREAD

**Issue by uzyfeo** [Alexpux/MINGW-packages#3283]
As we concluded in issue https://github.com/iortcw/iortcw/issues/42 there is some weird unexpected behavior hapening with mingw32-make.

Normal make from MSYS2 works without any issues but this one has as it seems more than one.

**Comment by Alexpux** [comment]
Under MSYS2 she’ll you need to use MSYS make, not MINGW one.
Mingw32-make designed to work under CMD

**Comment by uzyfeo** [comment]
Hm, interesting. So from cmd it should work properly?

I thought that with mingw I should use mingw one and not msys one... It should be written somewhere what usecase is for each one.

**Comment by mingwandroid** [comment]
In almost every case use make.

**Comment by uzyfeo** [comment]
Thanks for clarification :)
