### ISSUE TITLE
gedit-plugins: Text Size plugin mouse wheel decrease the text size on both direction.

### ISSUE THREAD

**Issue by akiyamaakira** [Alexpux/MINGW-packages#3284]
I'm using the MSYS2 MinGW 64-bit terminal,
installed the gedit and gedit-plugins,
enabled the Text Size plugin,
but the Ctrl+Mouse Wheel only decrease text size in both direction.

Please help.

![snipaste_20180112_093118](https://user-images.githubusercontent.com/4981858/34855752-4ebb43d2-f77c-11e7-9120-a1d0091d76a5.png)

**Comment by Alexpux** [comment]
You need report it to program developers, not here. We only build it

**Comment by akiyamaakira** [comment]
Thanks for reply. I got it.
