### ISSUE TITLE
[RESOLVED] Python3-pip TypeError when installing wrapt.

### ISSUE THREAD

**Issue by FierySwordswoman** [Alexpux/MINGW-packages#3286]
When installing the wrapt module necessary for pylint via pip, this error occurs:
https://pastebin.com/qRf6DNNw

Exact steps to reproduce:
 - Install latest MSYS2 64-bit
 - Run mingw64.exe
 - `pacman -S mingw-w64-x86_64-python3-pip`
 - `python3 -m pip install wrapt`

Notes:
 - Exists only in Python 3. Installation succeded in Python 2.
 - Installation succeded using Windows binary for Python 3 available from python.org

**Comment by lazka** [comment]
Hm, it seems to select the wrong compiler.

Wild guess, does `pacman -S mingw-w64-x86_64-toolchain` help?

**Comment by FierySwordswoman** [comment]
Installing the toolchain group *did* help. Surprised nothing I installed before grabbed it as a dependency.
I can't say why python2 or anything else I've done has worked without it.

Thanks for the help, as Unix is still black magic to me.

**Comment by FierySwordswoman** [comment]
Ah. was looking for that.
