### ISSUE TITLE
Jsonschema possible packaging issue

### ISSUE THREAD

**Issue by phrrk** [Alexpux/MINGW-packages#3294]
Hi,

I have recently installed the mingw-w64-x86_64-python3-jsonschema package using pacman.  It didn't work until I noticed that line 1 of the jsonschema-script.py file that is installed is:

#!C:/building/msys64/mingw64/bin/python3.exe

when I think that it should be simply

#!C:/msys64/mingw64/bin/python3.exe

There is no C:/building/ directory on my system nor is there any reference to such a directory in my environment.  On checking the files in the installation package I see that the

#!C:/building/msys64/mingw64/bin/python3.exe

is hard coded into the python script.

Is this as intended?

regards,

Jim

**Comment by Alexpux** [comment]
@phrrk need to be fixed in PKGBUILD

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/0dcccd0ee15513a194797c892c9b386a6e6ff62d
