### ISSUE TITLE
Where is opengl lib?

### ISSUE THREAD

**Issue by AntonioCS** [Alexpux/MINGW-packages#3318]
Hey guys,

I am trying to work a bit with opengl. 
I have installed freeglut and the sdl2 libs but I am unable to locate the opengl lib.

Which packages do I have to install to get this?
Note that I am using pkg-config to get the libs.
If I do this:  

> pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image glew freeglut

I get the following:

> -Dmain=SDL_main -IC:/msys64/mingw64/include/SDL2 -IC:/msys64/mingw64/include -LC:/msys64/mingw64/lib -lSDL2_ttf -lSDL2_image -lmingw32 -lSDL2main -lSDL2 -mwindows -lglew32 -lfreeglut

I believe there should be somewhere a -lopengl or -lopengl32
Do note that I have also searched the msys2 folder for anything with the name opengl and found nothing.

Thanks!

**Comment by lazka** [comment]
Never used opengl myself, but I think the library is provided by the system. Headers are in mingw-w64-i686-headers-git.

**Comment by AntonioCS** [comment]
Of course, I should have googled a bit more. Forgive my noobness :D
