### ISSUE TITLE
Why some of the packages seemingly invisible to Pacman?

### ISSUE THREAD

**Issue by jrmoore** [Alexpux/MINGW-packages#3320]
I'm unable to install some of the packages, like the one for Boost for example, no matter what I try; and others like GCC seem to be older then the ones I can see here in sources (GCC seems to be 6.4.0 for example).

I checked my Pacman configuration and it seems correct for me, the main server also points to the official one for the repos, like "http://repo.msys2.org/mingw/x86_64" for MinGW-w64.

What seems to be the problem? Does anybody have any idea?

**Comment by jrmoore** [comment]
For example, this is the output I get when trying to install GDB:

```
James@Rock MINGW64 ~
$ pacman -S gdb
resolving dependencies...
looking for conflicting packages...

Packages (4) gdbm-1.11-3  libgdbm-1.11-3  python2-2.7.13-1  gdb-7.11.1-1

Total Download Size:   13.91 MiB
Total Installed Size:  72.81 MiB

:: Proceed with installation? [Y/n]
```
Yet I see 8.0.1 being the latest version in the repo.

**Comment by mati865** [comment]
You are looking for wrong package:
```
mingw32/mingw-w64-i686-gdb 8.0.1-2 (mingw-w64-i686-toolchain)
mingw64/mingw-w64-x86_64-gdb 8.0.1-2 (mingw-w64-x86_64-toolchain)
msys/gdb 7.11.1-1 (base-devel)
```

**Comment by jrmoore** [comment]
Thank you very much, what a rookie mistake; I'll be closing this issue now.
