### ISSUE TITLE
gdb: Move to Python 3

### ISSUE THREAD

**Issue by lazka** [Alexpux/MINGW-packages#3329]
Filing this here, as rebuilding the current gdb PKGBUILD (as is, without changes) results in a broken build. Run gdb, type "bt", it crashes..

Here is a patch to get the Python 3 build working, if the above gets fixed:

```diff
--- gdb-8.0.1/gdb/python/python.c.orig	2018-01-29 17:17:16.030537500 +0100
+++ gdb-8.0.1/gdb/python/python.c	2018-01-29 17:17:25.135058300 +0100
@@ -351,6 +351,9 @@
 
   /* Because we have a string for a filename, and are using Python to
      open the file, we need to expand any tilde in the path first.  */
+
+#ifndef IS_PY3K
+
   gdb::unique_xmalloc_ptr<char> full_path (tilde_expand (filename));
   gdbpy_ref<> python_file (PyFile_FromString (full_path.get (), (char *) "r"));
   if (python_file == NULL)
@@ -361,6 +364,14 @@
 
   PyRun_SimpleFile (PyFile_AsFile (python_file.get ()), filename);
 
+#else
+
+  /* Python 3 no loner exposes FILE structs, so we are out of luck */
+  gdb::unique_xmalloc_ptr<char> full_path (tilde_expand (filename));
+  PyRun_SimpleFile (fopen (full_path.get(), "r"), filename);
+
+#endif
+
 #endif /* _WIN32 */
 }
```

**Comment by Ede123** [comment]
Related to #3330 ?

**Comment by lazka** [comment]
Could be. Newly build gtk+3 also crashes

**Comment by lazka** [comment]
Yeah, both gdb and gtk3 work again if I build with an older binutils, thanks @Ede123

**Comment by Alexpux** [comment]
I have troubles with gdb+python3.
If you install gdb on drive other than "C" it not work:
````
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000d18 (most recent call first):

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

````

**Comment by lazka** [comment]
ok, will have a look

**Comment by genusistimelord** [comment]
I am also getting the same Error message as Alexpux, but I do have my msys2 located on the C drive.

`genusis@DESKTOP-LPJ5EVG MINGW64 ~
$ gdb -v
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002e64 (most recent call first):

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
`

**Comment by lazka** [comment]
Do you have anything in your `~/.gdbinit` ?

**Comment by filnet** [comment]
Same issue here.
Msys2 located in `C:\msys64` and no `~/.gdbinit` to be found.

**Comment by lazka** [comment]
I can reproduce with a fresh msys2 env, It some how works in my main one..

**Comment by lazka** [comment]
OK, problem is that configure.ac is not enabling relocatable support with python3.

**Comment by lazka** [comment]
See #3345

**Comment by lazka** [comment]
New package is in the repos, can anyone confirm that it's working again?

**Comment by filnet** [comment]
gdb starts fine:

```
$ gdb
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
```

**Comment by lazka** [comment]
@filnet thanks

sorry for the breakage!
