### ISSUE TITLE
C++ hello world is causing a segmentation fault after gcc upgrade to 7.3.0

### ISSUE THREAD

**Issue by OliverSCE** [Alexpux/MINGW-packages#3331]
Hello, 

after the recent gcc upgrade to 7.3.0 a simple c++ hello word crashes with segfault, both for 32 and 64 bit versions. (under Win 7 professional). The issue looks more or less identical to
https://github.com/Alexpux/MINGW-packages/issues/1104

Any ideas how to fix this? 

Oliver

**Comment by mati865** [comment]
Duplicate https://github.com/Alexpux/MINGW-packages/issues/3330
