### ISSUE TITLE
GDI+ gdk-pixbuf-loader performance issues

### ISSUE THREAD

**Issue by hitchfred** [Alexpux/MINGW-packages#3335]
Hi. I've been having issues with the gdk-pixbuf package. My Gtk 3 program stalls loading larger jpegs, and the GdkPixbufLoader does not produce area-updated signals for JPEGs as it does for PNGs. I've tracked it down to the package's use of GDI+ pixbuf loaders. After rebuilding gdk-pixbuf to use libjpeg, etc, my program becomes as responsive as it is on Linux, and area-updated signals are correctly produced.

Would it be possible to change the gdk-pixbuf package to disable the GDI+ loaders in favor of libjpeg, libtiff, etc loaders?

I think this problem has come up before:
https://mail.gnome.org/archives/gtk-list/2010-February/msg00128.html

**Comment by lazka** [comment]
@Ede123 looks like you enabled them, thoughts?

**Comment by lazka** [comment]
Thanks for the explanation. Would there by any downside in just using the gdi loads for formats for which no other loader exists (tiff/jpeg/..)?

**Comment by lazka** [comment]
I did a small test using random jpeg images between 90x90 and 600x600, and the decoding with the gdi loader is between 10x and 20x times slower.

Regarding dependencies, I don't mind (also the current package depends on libjpeg/libtiff while not even linking against it..)

**Comment by lazka** [comment]
I've opened #3339 feedback welcome

**Comment by lazka** [comment]
@Ede123 the image in the Ubuntu bug loads fine with the libjpeg loader. In 0.088sec vs 2.075sec with gdi+

**Comment by Ede123** [comment]
Sounds promising! I'll do some tests (probably this evening) to see if I can find any regressions, otherwise I'm fine with merging.

**Comment by lazka** [comment]
The new package is in the repos.

**Comment by hitchfred** [comment]
Closing. With the new package, everything is fine. Thanks
