### ISSUE TITLE
The latest version of gdb crashed!

### ISSUE THREAD

**Issue by ninepillars** [Alexpux/MINGW-packages#3348]
gdb version: mingw-w64-x86_64-gdb-8.0.1-3   and  mingw-w64-i686-gdb-8.0.1-3

Yestoday, I upgrade the whole msys2 system to the latest versions. But when I start gdb, I've got this:

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001d10 (most recent call first):

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by lazka** [comment]
There is a fixed version in the repo since today (8.0.1-4)

**Comment by lazka** [comment]
See https://github.com/Alexpux/MINGW-packages/issues/3329#issuecomment-362703227
