### ISSUE TITLE
rocksdb: WARNING: Package contains reference to $(cygpath -m /)

### ISSUE THREAD

**Issue by filnet** [Alexpux/MINGW-packages#3355]
I just contributed a new rocksdb package. See https://github.com/Alexpux/MINGW-packages/pull/3352.

At the end of makepkg-mingw I see this warning:

`WARNING: Package contains reference to $(cygpath -m /)`

```
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> WARNING: Package contains reference to $(cygpath -m /)
==> Creating package "mingw-w64-i686-rocksdb"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
error: invalid option '--noprogressbar'
  -> Generating .MTREE file...
  -> Compressing package...
==> Finished making: mingw-w64-rocksdb 5.10.2-1 (Tue, Feb  6, 2018  6:27:18 PM)
```

What kind of check does makepkg-mingw do ?
A grep of the value of `$(cygpath -m /)` ?

There are a few cmake related files in the resulting package that do reference `$(cygpath -m /)`.
```
-- Installing: C:/M/mingw-w64-rocksdb/pkg/mingw-w64-i686-rocksdb/mingw32/lib/cmake/rocksdb/RocksDBTargets.cmake
-- Installing: C:/M/mingw-w64-rocksdb/pkg/mingw-w64-i686-rocksdb/mingw32/lib/cmake/rocksdb/RocksDBTargets-release.cmake
-- Installing: C:/M/mingw-w64-rocksdb/pkg/mingw-w64-i686-rocksdb/mingw32/lib/cmake/rocksdb/RocksDBConfig.cmake
-- Installing: C:/M/mingw-w64-rocksdb/pkg/mingw-w64-i686-rocksdb/mingw32/lib/cmake/rocksdb/RocksDBConfigVersion.cmake
```

How does one go about fixing that ?

**Comment by Alexpux** [comment]
It tell that files in package contain hardcoded build paths. You need fix build to not contain  such paths because in most cases it lead to half-working package on other computer

**Comment by filnet** [comment]
@Alexpux I know that those warnings are bad and lead to packages that fully work only on the computer where the package was built.

I was asking how those issues are found. Is makepkg doing a brute force grep across the whole package content ?

And also how to fix them.

**Comment by Alexpux** [comment]
This introduced here:
https://github.com/Alexpux/MSYS2-pacman/commit/b4be2fda64680b99284fe56ad3176cac2107ea20#diff-b98ecfc72a7079965f783e3c55394691

How to fix see packages in repo. Lot of them have different ways to solve it

**Comment by filnet** [comment]
@Alexpux Thanks for the detailed answer.

**Comment by filnet** [comment]
Found a fix for a similar issue in the alembic package.
