### ISSUE TITLE
OpenAL package missing EFX-Util.h

### ISSUE THREAD

**Issue by AntonioCS** [Alexpux/MINGW-packages#3368]
Hey guys,

I am trying to compile this game (https://github.com/ryanfleury/global_game_jam_2018) and one of the issues I am getting is this:

> ./source/globals.cpp:11:10: fatal error: AL/EFX-Util.h: No such file or directory
>  #include <AL/EFX-Util.h>

I have installed OpenAl using: pacman -S mingw64/mingw-w64-x86_64-openal
If I do: pkg-config --libs --cflags openal
I get: -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/AL -LC:/msys64/mingw64/lib -lopenal

The problem is that the file is missing from the actual include/AL directory.
Does anyone know if this is an old file of the lib or is this package actually missing the file by mistake?

Thanks!

**Comment by MenaceInc** [comment]
EFX-Util.h isn't available in the OpenAL Soft package. I'm not sure but it appears to have been a header that was available with old versions of OpenAL. Commenting it out of the game project doesn't appear to have had any negative consequences.
