### ISSUE TITLE
gst-plugins-ugly build fails due to changes in libx264

### ISSUE THREAD

**Issue by lazka** [Alexpux/MINGW-packages#3379]
Cause: https://git.videolan.org/gitweb.cgi/x264.git/?a=commit;h=71ed44c7312438fac7c5c5301e45522e57127db4

Upstream GStreamer bug: https://bugzilla.gnome.org/show_bug.cgi?id=792111

In ffmpeg this was fixed here: https://github.com/FFmpeg/FFmpeg/commit/650cb712efc47cf4c1f4f419ea220fcedc65f122

**Comment by revelator** [comment]
seing the same here, hopefully a fix soon.

**Comment by lazka** [comment]
I've opened #3452
