### ISSUE TITLE
[mingw-w64-perl] ERROR: A failure occurred in package()

### ISSUE THREAD

**Issue by niklasholm** [Alexpux/MINGW-packages#3397]
Trying to build mingw-w64-perl results in an error.

```sh
$ makepkg-mingw -sCLf
[... lots of output ...]
  -> Creating relocate patterns for:
     C:\msys64
     C:\\msys64
     C:\msys64\home\Niklas\MINGW-packages\mingw-w64-perl\pkg\mingw-w64-x86_64-perl
     C:\\msys64\\home\\Niklas\\MINGW-packages\\mingw-w64-perl\\pkg\\mingw-w64-x86_64-perl
sed: can't read lib/perl5/core_perl/.packlist: No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...

$ find pkg -name '.packlist'
pkg/mingw-w64-perl/mingw64/lib/perl5/core_perl/.packlist
```

It seems the `package()` script cd into `pkg/mingw-w64-x86_64-perl`, but `.packlist` is located under `pkg/mingw-w64-perl`, thus the error. This is very strange and should have been caught a long time ago, which leads me to belive I'm doing something wrong. Why does makepkg-mingw produce multiple build roots?

**Comment by Alexpux** [comment]
MINGW perl package is not maintained for a long time. So I cant say what is wrong there right now.
Seems wrong location of ````.packlist```` passed to sed. 
It not generate multiple build roots. It just try to fix PATHs in scripts to be able run perl on other computer. not where it builded

**Comment by Alexpux** [comment]
Yeah seems it create somewhere 2 install roots. Feel free to fix it

**Comment by niklasholm** [comment]
Obviously, the package has been built successfully with this recipe before, so the question is: What's changed?

**Comment by niklasholm** [comment]
It seems the line `pkgbase=mingw-w64-${_realname}` is the cause. Removing it fixes the error. No idea why though.
