### ISSUE TITLE
[mingw-w64-graphviz] 2.40.1-1 is missing libtool in its dependencies

### ISSUE THREAD

**Issue by ptensschi** [Alexpux/MINGW-packages#3415]
On a pretty blank msys system, installation fails in the "dot -c" step:
```:: Processing package changes...
(1/1) reinstalling mingw-w64-x86_64-graphviz                                                                       [###################################################################] 100%
:: Processing package changes...
C:/swept/msys64/mingw64/bin/dot.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_PlW1Gb/.INSTALL; post_upgrade 2.40.1-1 2.40.1-1 ) failed to execute correctly
```
After installing mingw-w64-x86_64-libtool manually, it works.

**Comment by achadwick** [comment]
Verified here. My dud install at the end of #737 was fixed by installing the (exceedingly developer-focused) libtool package. That seems strange for the surely very binary and end-user-facing graphviz install :neutral_face: 

```
testuser@win7test MSYS ~
$ pacman -S mingw-w64-x86_64-libtool mingw-w64-i686-libtool
resolving dependencies...
looking for conflicting packages...

Packages (2) mingw-w64-i686-libtool-2.4.6-11  mingw-w64-x86_64-libtool-2.4.6-11

Total Download Size:   0.86 MiB
Total Installed Size:  4.59 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 mingw-w64-i686-libt...   439.0 KiB  1216K/s 00:00 [#####################] 100%
 mingw-w64-x86_64-li...   437.0 KiB  42.7M/s 00:00 [#####################] 100%
(2/2) checking keys in keyring                     [#####################] 100%
(2/2) checking package integrity                   [#####################] 100%
(2/2) loading package files                        [#####################] 100%
(2/2) checking for file conflicts                  [#####################] 100%
(2/2) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/2) installing mingw-w64-x86_64-libtool          [#####################] 100%
(2/2) installing mingw-w64-i686-libtool            [#####################] 100%

testuser@win7test MSYS ~
$ pacman -S mingw-w64-x86_64-graphviz mingw-w64-i686-graphviz
warning: mingw-w64-x86_64-graphviz-2.40.1-1 is up to date -- reinstalling
warning: mingw-w64-i686-graphviz-2.40.1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (2) mingw-w64-i686-graphviz-2.40.1-1
             mingw-w64-x86_64-graphviz-2.40.1-1

Total Installed Size:  29.32 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
(2/2) checking keys in keyring                     [#####################] 100%
(2/2) checking package integrity                   [#####################] 100%
(2/2) loading package files                        [#####################] 100%
(2/2) checking for file conflicts                  [#####################] 100%
(2/2) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/2) reinstalling mingw-w64-x86_64-graphviz       [#####################] 100%
(2/2) reinstalling mingw-w64-i686-graphviz         [#####################] 100%
```

And now:

```
testuser@win7test MINGW64 ~
$ dot -V
dot - graphviz version 2.40.1 (20161225.0304)
```

**Comment by lazka** [comment]
> That seems strange for the surely very binary and end-user-facing graphviz install :neutral_face:

The contained library looks useful in itself: https://www.gnu.org/software/libtool/manual/html_node/Using-libltdl.html -  there are also quite a few users: https://quodlibet.duckdns.org/msys2/package/mingw-w64-i686-libtool?repo=mingw32

**Comment by lazka** [comment]
I've opened #3418

**Comment by achadwick** [comment]
@lazka 
On a review of the package contents: fair enough, although it's worth noting that other systems (e.g. Debian) make consistently split the packages up.

- graphviz → libcgraph6, libcgraph6-dev, graphviz
- libtool → libltdl7, libltdl-dev, libtool

I really wish MSYS2 would adopt something similar: it'd make users of bundlers (like Styrene :electric_plug::electric_plug:) happier, for starters.

Oh, and a pony. :carousel_horse:

**Comment by Alexpux** [comment]
@achadwick we prefer to not split packages for MINGW. It really take lot of work.

**Comment by achadwick** [comment]
@Alexpux 
As a result, developers, build maintainers and bundle creators who want to use MSYS2 need to do much more work to make their creations minimal and their downloads small. They need to disentangle the often surprising hairball of package dependencies that comes from having maxed-out packages whose obscure corners depend on things you'll never need your program.

Doing the work up front to allow the dependency tree to slice neatly along pre-cut paths really would help, and it is possible no matter how much this sounds like a mystical quest :unicorn:
It would need some guidelines for the PKGBUILD maintainers. Luckily there's a lot of prior art, and it could be introduced gradually.

But enough of my regular whining. Thanks for 32404fe4bc0f716c251b59727c255681370d31a9 and all the work you do in keeping MSYS2 running! :1st_place_medal:

**Comment by Alexpux** [comment]
@achadwick splitting packages for MINGW totally increase number of package files and dependencies between them. We have already lot of issues without splitting. If anyone want to do all the work about splitting packages - I'm glad to see him. 
In near time i will stop working on MSYS2 for some months because of my real work.
