### ISSUE TITLE
openblas .pc file needs cleanup

### ISSUE THREAD

**Issue by okhlybov** [Alexpux/MINGW-packages#3428]
As of version 0.2.20 the OpenBLAS' .pc file contains linking flags (`-defaultlib`) apparently belonging to the MSVC and not supported by the GCC:
```
libdir=/mingw32/lib
includedir=/mingw32/include/OpenBLAS
version=0.2.20
extralib=-defaultlib:advapi32 -lgfortran -defaultlib:advapi32 -lgfortran
Name: openblas
Description: OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
Version: ${version}
URL: https://github.com/xianyi/OpenBLAS
Libs: -L${libdir} -lopenblas
Libs.private: ${extralib}
Cflags: -I${includedir}
```
This prevents from using this .pc file for static linking.

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/eeebe48eba513dde23f9e2a5436d2f33a8017e46
