### ISSUE TITLE
Wrong MINGW-GCC output for -MM/-MT switches

### ISSUE THREAD

**Issue by mmaxs** [Alexpux/MINGW-packages#3430]
C++ preprocessor yields output for -MM / -MT options with Windows paths.
Here is the example:
```
$ x86_64-w64-mingw32-c++ -E -I "/d/wroot.vba&vbs/XLL/Excel2010XLLSDK/INCLUDE"  \ 
    -MM  -MT "/d/wroot.vba&vbs/XLL/build/sdk_sample/generic/generic.o" generic.c
```
The output is:
```
D:/wroot.vba&vbs/XLL/build/sdk_sample/generic/generic.o: generic.c \
 D:/wroot.vba&vbs/XLL/Excel2010XLLSDK/INCLUDE/xlcall.h
```
Notice that even for -MT option the path of the target is being modified. But according to GCC manual it should not:
>An -MT option sets the target to be exactly the string you specify.

Yet another test:
```
$ x86_64-w64-mingw32-c++ -E -I "/d/wroot.vba&vbs/XLL/Excel2010XLLSDK/INCLUDE"  \
    -MM  -MT "/bla-bla-bla/d/wroot.vba&vbs/XLL/build/sdk_sample/generic/generic.o" generic.c
```
The output appears containing `C:/msys64` prefix:
```
C:/msys64/bla-bla-bla/d/wroot.vba&vbs/XLL/build/sdk_sample/generic/generic.o: \
 generic.c D:/wroot.vba&vbs/XLL/Excel2010XLLSDK/INCLUDE/xlcall.h
```
**All this breaks Makefile usage scenarios that should normally execute OK.**

---

Here are comparisions with Cygwin:
Test 1:
```
$ x86_64-w64-mingw32-c++ -E -I "/cygdrive/d/wroot.vba&vbs/XLL/Excel2010XLLSDK/INCLUDE"  \
    -MM  -MT "/cygdrive/d/wroot.vba&vbs/XLL/build/sdk_sample/generic/generic.o" generic.c
```
Output 1:
```
/cygdrive/d/wroot.vba&vbs/XLL/build/sdk_sample/generic/generic.o: \
 generic.c /cygdrive/d/wroot.vba&vbs/XLL/Excel2010XLLSDK/INCLUDE/xlcall.h
```
Test 2:
```
$ x86_64-w64-mingw32-c++ -E -I "/cygdrive/d/wroot.vba&vbs/XLL/Excel2010XLLSDK/INCLUDE"  \
    -MM  -MT "/bla-bla-bla/cygdrive/d/wroot.vba&vbs/XLL/build/sdk_sample/generic/generic.o" generic.c
```
Output 2:
```
/bla-bla-bla/cygdrive/d/wroot.vba&vbs/XLL/build/sdk_sample/generic/generic.o: \
 generic.c /cygdrive/d/wroot.vba&vbs/XLL/Excel2010XLLSDK/INCLUDE/xlcall.h
```

**Comment by Alexpux** [comment]
MSYS2 always try to convert posix paths to windows for native Windows programs. There are no issue there

**Comment by mmaxs** [comment]
I figured it out now. I should use mingw64/make (mingw32-make.exe) instead of msys/make in my particular case.

Mingw64/make CURDIR predefined variable and file name functions return Windows paths, and then Mingw-GCC preprocessor output matches targets and prerequisites evaluated from Makefile directives.

My Cygwin experience has misled me: Mingw-GCC toolchain  by itself is a Cygwin-flavor programs there (while building output binaries not linked to Cygwin) and is working fine in conjunction with Cygwin's own make utility.
