### ISSUE TITLE
How to integrate and install intel c compiler into mingw64?

### ISSUE THREAD

**Issue by BudiKusasi** [Alexpux/MINGW-packages#3448]
How to integrate and install intel c compiler into mingw64 with instructive detail how-to explanation

**Comment by Alexpux** [comment]
I don't think that anyone tell it for you because MINGW-W64 have its own compiler GCC.

**Comment by BudiKusasi** [comment]
I just really want richer available options to compile, intel c compiler, borland turbo C are of them to benefit them integrated conveniently in mingw64, either on MSYS2 or CYGWIN

**Comment by ArekPiekarz** [comment]
I think for the Intel compiler you will have more success with a different, more versatile and cross platform package manager, like Conan - https://conan.io

**Comment by BudiKusasi** [comment]
Great info !.. Thanks so much
who has right to close this, may close it

**Comment by BudiKusasi** [comment]
What a great info from a great favor ! I'm grateful.. thanks
