### ISSUE TITLE
mingw64-w64-python{2,3} 'os' module has no support for POSIX style paths

### ISSUE THREAD

**Issue by linedot** [Alexpux/MINGW-packages#3459]
The MinGW versions of python do not work with POSIX style paths ( i.e /c/some/path )

Example:
```
$ winpty python3
Python 3.6.4 (default, Jan 23 2018, 13:17:37)  [GCC 7.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.exists('/c/')
False
>>> os.path.exists('C:/')
True
>>>
```

This can lead to issues with some software, [here is one example](https://github.com/Valloric/YouCompleteMe/issues/2932)

The msys version of python does not show this behaviour:

```
$ winpty /bin/python2.exe
Python 2.7.13 (default, Feb 14 2017, 14:46:01)
[GCC 6.3.0] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.exists('/c/')
True
>>> os.path.exists('C:/')
True
>>>
```

**Comment by Alexpux** [comment]
Mingle python is native Windows application and as all Windows applications it not understand posix paths.
