### ISSUE TITLE
mingw64 sqlite3 CLI  don't work

### ISSUE THREAD

**Issue by CCTV-1** [Alexpux/MINGW-packages#3463]
if don't "enter shell"(`sqlite3 --help` and other methods) the program(\mingw64\bin\sqlite3.exe) is working.
if `sqlite3 $(filename)` or `sqlite3` enter shell,no output,can only kill the process(you can see the process is running).

environment:
Windows10 1709 16299.248.
msys2: `uname -a` : `MINGW64_NT-10.0 CCTV 2.10.0(0.325/5/3) 2018-02-09 15:25 x86_64 Msys`.
shell:ming64_shell zsh mintty. (msys2_shell working)
sqlite3 version: `mingw-w64-x86_64-sqlite3-3.21.0-1`

**Comment by lazka** [comment]
likely due to mintty, try `sqlite --interactive`

**Comment by CCTV-1** [comment]
@lazka `sqlite3 --interactive` work,thank you.
