### ISSUE TITLE
Build Stockfish chess engine error in g++ compile after gcc 7.3 update

### ISSUE THREAD

**Issue by BudiKusasi** [Alexpux/MINGW-packages#3469]
I tried to build Stockfish chess engine with pacman-updated gcc witht downgrade favor as in 7.2 it succeeded perfectly, but on this, at step 1 here it returned :
```
g++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o syzygy/tbprobe.o -lgcov -static
D:/MSYS/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0\libgcov.a(_gcov.o):(.text+0x206): undefined reference to `__imp___acrt_iob_func'
D:/MSYS/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0\libgcov.a(_gcov.o):(.text+0x1110): undefined reference to `__imp___acrt_iob_func'
D:/MSYS/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0\libgcov.a(_gcov.o):(.text+0x1161): undefined reference to `__imp___acrt_iob_func'
D:/MSYS/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0\libgcov.a(_gcov.o):(.text+0x1fa8): undefined reference to `__imp___acrt_iob_func'
D:/MSYS/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0\libstdc++.a(vterminate.o):(.text$_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x5b): undefined reference to `__imp___acrt_iob_func'
D:/MSYS/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0\libstdc++.a(vterminate.o):(.text$_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0xd7): more undefined references to `__imp___acrt_iob_func' follow
collect2.exe: error: ld returned 1 exit status

make[2]: *** [Makefile:492: stockfish] Error 1
make[2]: Leaving directory '/d/CYGwin/usr/src/Stockfish-master/src'
make[1]: *** [Makefile:508: gcc-profile-make] Error 2
make[1]: Leaving directory '/d/CYGwin/usr/src/Stockfish-master/src'
make: *** [Makefile:414: profile-build] Error 2
```
any idea what's actually happened, I searched for string "_iob_func" all over .h, .c, .cpp files in entire dirs. with no outcome at all.
Thanks in advance, for the attention

**Comment by mati865** [comment]
Does it happen with latest crt/headers (version `6.0.0.5114.b9400293`)?
If so it should be reported to mingw-w64.

[This](https://gitlab.com/mati865/mingw-w64-mirror/commit/af149abc81550de19a80fba0f9d0e89fe4d01f2f) commit seems relevant.

**Comment by BudiKusasi** [comment]
> rebuilding GCC with latest crt/headers.

How to do such.. could you explain it  instructively in more detail ?

> Does it happen with latest crt/headers (version 6.0.0.5114.b9400293)?

How to check and retrieve the crt/headers version ?

**Comment by mstorsjo** [comment]
This sounds like a case where libgcov.a was built with newer headers (after the commit that was pointed out), but libmsvcrt.a wasn't rebuilt after updating the headers.

**Comment by mati865** [comment]
I just build Sockfish with updated MSYS2 and `make build ARCH=x86-64-bmi2`. It doesn't crash and basic examples are working.

> How to check and retrieve the crt/headers version ?
```
$ pacman -Qs crt
local/mingw-w64-x86_64-crt-git 6.0.0.5114.b9400293-1 (mingw-w64-x86_64-toolchain)
    MinGW-w64 CRT for Windows
```

**Comment by BudiKusasi** [comment]
Thanks so much everyone who's helped me !!
IT"S FIXED now.. after  I updated crt ;
`$ pacman -Sy local/mingw-w64-x86_64-crt-git`

the rest just "pacman miracle" grace..
