### ISSUE TITLE
Has anyone managed to successfully build a Midori browser?

### ISSUE THREAD

**Issue by niXman** [Alexpux/MINGW-packages#3490]
In the repository I can see the `mingw-w64-midori` directory and it contains the PKGBUILD file, but among the binary packages there is no Midori package, but there is a webkitgtk binary package.

My question is whether the webkitgtk is an working one and whether someone used it?

Thanks.

**Comment by mati865** [comment]
@niXman it was WIP but apparently haven't got finished: https://github.com/Alexpux/MINGW-packages/commits/master/mingw-w64-midori

**Comment by niXman** [comment]
Thanks for reply.

But my another question is: the webkitgtk is an working one and whether someone used it?

**Comment by revelator** [comment]
Managed to build it but working unfortunatly no, crashes when trying to open a site.
webkit version is also very old but the newer version uses cmake and needs a lot of patching before working on windows.

**Comment by lazka** [comment]
The webkitgtk version we have is full of security issues and shouldn't be used to load anything you don't control or trust.
