### ISSUE TITLE
update gstreamer to 1.14.0

### ISSUE THREAD

**Issue by filnet** [Alexpux/MINGW-packages#3504]
I am on it...

See https://gstreamer.freedesktop.org/releases/1.14/

Note that some plugins with external dependencies have been moved from bad to good.
PKGBUILD dependencies need to be adapted...

PS : how do you make sure PKGBUILD dependencies are correct (not too many and none missing) when your msys environment is full of all sorts of installed packages ?

**Comment by lazka** [comment]
Oh, I'll stop then :)

I only did gstreamer: drop intltool, gtk-doc -> mingw gtk-doc, update the conflicts against bad to > 1.14.0 (some headers have moved as well)

**Comment by filnet** [comment]
Why did you drop intltool ?
And I did  not understand what you did with gtk-doc...

Yes, most patches in in bad are not needed anymore (only the 1st one is still needed apparently).

**Comment by lazka** [comment]
> Why did you drop intltool ?

The Arch package doesn't depend on it and I tried building without it.

>  And I did not understand what you did with gtk-doc...

Replace `"gtk-doc"` with `"${MINGW_PACKAGE_PREFIX}-gtk-doc"`

**Comment by filnet** [comment]
Ok. Got it. 

I noticed that all gst packages are built with the option `--disable-gtk-doc`.
I'll still change to use `"${MINGW_PACKAGE_PREFIX}-gtk-doc"` in case that option gets removed.

**Comment by filnet** [comment]
I am removing gcc and pkg-config from makedepends as they come with the toolchain.
