### ISSUE TITLE
How to distributing gstreamer software to non-MSYS2-users

### ISSUE THREAD

**Issue by CCTV-1** [Alexpux/MINGW-packages#3509]
I plan to use `mingw-w64-x86_64-gstreamer` build programs,but,i don't know how get the programs runtime load gstreamer plus path,don't know how to organize the file structure(other library dll depende use a python script bay ldd output auto copy,this work).

I try use `strace` get GStreamer runtime load dll list,copy to programs path,programs can run,but function `gst_element_factory_make` always return `NULL`(gstreamer-core document:`gst_element_factory_make return value : new GstElement or NULL if unable to create element`),load gstreamer modules faliure.

So how do i get him to work(or where to go for relevant information)?

PS.sorry,my english is not very good.

**Comment by filnet** [comment]
You'll need to package and distribute all the exécutables and libraries needed by your project.

A few helpful resources are listed here: https://github.com/msys2/msys2/wiki/Distributing

**Comment by filnet** [comment]
For GStreamer, you'll need to go to the GStremaer project documentation / forum.

There are many ways to tell GStreamer where to find its plugins : https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gst-running.html

**Comment by CCTV-1** [comment]
@filnet Thank you, we are now late at night. i will read these documents tomorrow morning and try distributing my programs.

**Comment by CCTV-1** [comment]
@filnet By document [https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gst-running.html](url)  set `GST_PLUGIN_PATH`、`GST_DEBUG` load plugin successfully,but gstreamer `gst_element_factory_make` still return `NULL` .but in mingw64_shell this work.what does mingw64_shell do?

**Comment by filnet** [comment]
@CCTV-1 please ask your gstreamer related questions on the gstreamer forum.

**Comment by CCTV-1** [comment]
so mingw_shell did not hook related api?okay, then I close this issues.
