### ISSUE TITLE
build OpenCV error

### ISSUE THREAD

**Issue by dbyoung720** [Alexpux/MINGW-packages#3514]
/MSYS2/mingw64/include/c++/7.3.0/cmath:1138:11: error: '::hypot' has not been declared   using ::hypot;

**Comment by filnet** [comment]
please provide more context (command line, full error, etc...)

**Comment by revelator** [comment]
looks like the same bug thats happening with another package using python ?
try exporting CFLAGS=" -D_hypot=hypot" and then build, if its the same bug it should work.

**Comment by dbyoung720** [comment]
thank, I try.

**Comment by thewtex** [comment]
If this patch is applied to CPython, it should fix the issue:

  https://github.com/python/cpython/pull/880
