### ISSUE TITLE
Update to poppler to  0.63.0

### ISSUE THREAD

**Issue by bratao** [Alexpux/MINGW-packages#3517]
Hello, 
Thank you for this awesome project.

Lib poppler updated to  0.63.0 with some great fixes. The repo here still contains the version 0.62

https://poppler.freedesktop.org/

**Comment by lazka** [comment]
https://github.com/msys2/msys2/wiki/Creating-Packages

**Comment by GitMensch** [comment]
@bratao : What @lazka likely meant to say: Please try to update the existing package (normally relative easy if the dependencies did not change: just replace the source link and its SHA + package in the [PKGBUILD](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-poppler/PKGBUILD) and run an update.
@bratao Do you give it a try?
