### ISSUE TITLE
libzip doesn't come with static library

### ISSUE THREAD

**Issue by uwehermann** [Alexpux/MINGW-packages#3561]
Hi, please consider also providing a static libzip library. It currently comes with a .dll and .dll.a (but no .a file). libzip is one of two missing dependencies that would allow us to build sigrok (see www.sigrok.org) natively on Windows using MSYS2. Thanks!

**Comment by mingwandroid** [comment]
@uwehermann please stop with the mischaracterisations that missing static libraries inhibits building software. It's just not true. Shared libraries are generally speaking better than static ones for various reasons.

But we should look to provide static libs for people who disagree with that assertion.
