### ISSUE TITLE
gcc commandline defines passed case-insensitive, causing clashes with variable names

### ISSUE THREAD

**Issue by martin-frbg** [Alexpux/MINGW-packages#3575]
Over at the OpenBLAS project, our build instructions for Windows were recently changed to recommend msys2.org and the mingw compiler it pulls in from pacman, rather than the mingw-w64 project hosted on sourceforge. This has now led to https://github.com/xianyi/OpenBLAS/issues/1503, where a gcc command line containing "-DCR" (with matching "if defined(CR)" in the sources) results in the error message 
```
<command-line>:0:4: error: expected identifier or '(' before numeric constant
```
researching this message led me to mingw bug 2183 from around the time of gcc-4.8.1, where similar
behaviour was demonstrated with -DUI and a lowercase "ui" used somewhere as a shorthand for "unsigned int" in a system header. Indeed the OpenBLAS build failure can be worked around by
changing "CR" to "CRX" so it looks like it is still the same problem. Needless to say, the current mingw-w64 from sourceforge (or any other compiler for that matter) do not show this misbehaviour.

**Comment by lazka** [comment]
https://sourceforge.net/p/mingw/bugs/2183/

**Comment by martin-frbg** [comment]
A user comment in the OpenBLAS issue thread suggests that the problem can be worked around by downgrading your currently available mingw-w64 crt, headers and tools packages to your archived
mingw-w64-x86_64-crt-git-6.0.0.5100.739199f8-1-any.pkg.tar.xz
mingw-w64-x86_64-headers-git-6.0.0.5102.2f16a8c7-1-any.pkg.tar.xz
mingw-w64-x86_64-tools-git-6.0.0.5079.3b7a42fd-1-any.pkg.tar.xz
which probably points towards the tools package as the source of the problem.

**Comment by Alexpux** [comment]
@martin-frbg well need then bisect mingw-w64 commit that leads to this issue.
6.0.0.5100 is builded on 26.01.18
6.0.0.5125 is builded on 21.03.18

So need check commits between this dates.

Maybe need also check 6.0.0.5114 package builded on 28.02.18. It may decrese commits to check

**Comment by Alexpux** [comment]
Checked that 6.0.0.5114 seems to work,
so need bisect commit between 5114 and 5125

**Comment by martin-frbg** [comment]
New comment by "pingplug" in the OpenBLAS issue traces this to https://sourceforge.net/p/mingw-w64/mingw-w64/ci/0f9569488ba7e48472183765a7ae6555ed990f4a in mingw-w64-headers where a new struct containing a `DWORD CR` was added to winnt.h

**Comment by martin-frbg** [comment]
I have created ticket 736 on the mingw-w64 issue tracker at sourceforge now

**Comment by martin-frbg** [comment]
So it seems the issue actually comes from the addition of the conflicting definitions to the winnt.h of Windows10, and my initial assumption that an old bug with very similar symptoms had returned was unfounded. Sorry for the noise.

**Comment by Alexpux** [comment]
Fixed in https://github.com/Alexpux/MINGW-packages/commit/3ab133bc4875734cd63293838c86e6babbe83684
