### ISSUE TITLE
gtk3: filechooser broken

### ISSUE THREAD

**Issue by juml** [Alexpux/MINGW-packages#3584]
Since last updates gtk filechooser appears broken.

Steps:
1. run gedit
2. Open -> Other documents ...
3. Dialog shows, try to change drive to "Label (D:)"
4. No content to bowse

Entries like Home / Documents / etc works.

**Comment by lazka** [comment]
Confirmed and filed upstream: https://gitlab.gnome.org/GNOME/gtk/issues/170

**Comment by juml** [comment]
This got to master/branch pretty quickly, nice.

**Comment by houz** [comment]
There is 2.57.1 now. Could you package that, or pick the fix into the 2.56.1 package? Having a working file selector would be awesome. :-)

**Comment by ZachBacon** [comment]
could always try and backport the fix as a patch.

**Comment by lazka** [comment]
#3845
