### ISSUE TITLE
Qt5Webkit is broken: missing ICU 58 dependency

### ISSUE THREAD

**Issue by omichel** [Alexpux/MINGW-packages#3585]
After the recent update of Qt5, Qt5Webkit.dll is broken because it depends on `libicuin58.dll` which was replaced with `libicuin61.dll` by the Qt5 upgrade. We should probably rebuild mingw-w64-qtwebkit with ICU 61.1 to fix that problem.

**Comment by Alexpux** [comment]
There are a lot of packages that still need to be rebuilded with new ICU.
Be patient it can take some days or week.

**Comment by Alexpux** [comment]
Fixed

**Comment by omichel** [comment]
🤘 I confirm it is now fixed. Thank you very much for the very quick reaction!
