### ISSUE TITLE
glib-networking is broken

### ISSUE THREAD

**Issue by tschoonj** [Alexpux/MINGW-packages#3595]
@KrullBorg 

The switch to meson appears to have broken glib-networking as I am now getting errors like:

```
GLib-Net-WARNING **: 11:17:55.838: couldn't load TLS file database: Failed to open file   C:/building/msys64/mingw64/ssl/certs/ca-bundle.crt: No such file or directory

WARNING **: 11:17:56.740: libsoup error message: Unacceptable TLS certificate
```

I think this relates to the `-Dca_certificates_path=${MINGW_PREFIX}/ssl/certs/ca-bundle.crt`, which now takes an absolute path instead of a relative one. This is important because the `0002-relative-system-ca-file.mingw.patch` patch depends on a relative path being fed to meson.

FWIW: the ca_certificates_path option is [no longer in master](https://github.com/GNOME/glib-networking/commit/f1c8feee014007cc913b71357acb609f8d1200df)

**Comment by KrullBorg** [comment]
thanks, tomorrow i'll try to fix it

**Comment by KrullBorg** [comment]
could you try? i built packages under c:\msys64

https://github.com/KrullBorg/MINGW-packages/commit/35217ecfe2bcdad297fd0b0e4a5a8a2621be0502

https://saetta.ns0.it/images/mingw-w64-i686-glib-networking-2.56.0-2-any.pkg.tar.xz
https://saetta.ns0.it/images/mingw-w64-x86_64-glib-networking-2.56.0-2-any.pkg.tar.xz

**Comment by lazka** [comment]
@KrullBorg seems to work again. Tested with https://gist.github.com/lazka/c8f38190c49d7c4090372addb6c2f88e

**Comment by tschoonj** [comment]
Works fine. Many thanks!

**Comment by lazka** [comment]
new build is in the repo
