### ISSUE TITLE
Curl downloads are very slow 

### ISSUE THREAD

**Issue by YousefSaber** [Alexpux/MINGW-packages#3603]
My internet down speed is 6.6Mbps according to speed test result 

and Curl takes only 0.5 Mbps of my bandwidth connection

![image](https://user-images.githubusercontent.com/33742499/38771044-4c8e0052-401c-11e8-9e2f-84f0ca8e8e00.png)

what's the cause for this slow down 

![image](https://user-images.githubusercontent.com/33742499/38771049-5abb3834-401c-11e8-92fd-456dc6fb10c8.png)

**Comment by lazka** [comment]
Is this still a problem?

I can't reproduce (with these: https://speed.hetzner.de/)
