### ISSUE TITLE
mingw-w64-i686-webkitgtk3 broken by Ilibicu upgrade.

### ISSUE THREAD

**Issue by jralls** [Alexpux/MINGW-packages#3609]
webkitgtk3 depends on icu, and icu encodes its version into its symbols (e.g. u_charDirection_58).  You upgraded icu from ICU-58 to ICU-61 April 8 but didn't rebuild webkitgtk3, so now it won't load.

**Comment by Alexpux** [comment]
There are errors building webkitgkt with icu 61, so will rebuild when solve it

**Comment by Alexpux** [comment]
Well there are many dependencies on ICU. I can’t control all packages for rebuilding myself. If you want to see it rebuilded you can help or wait while it happened. I’m only one person who build and upload to repo and I don’t want to build 24 hours in a day, I have my own life.

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/4402b9a72e2a1741ca27bb174f52608870546f87
