### ISSUE TITLE
pugixml package is not able to find includes

### ISSUE THREAD

**Issue by RobertBColton** [Alexpux/MINGW-packages#3620]
```
fatal error: pugixml.hpp: No such file or directory
 #include <pugixml.hpp>
          ^~~~~~~~~~~~~
```

And I have installed pugixml:
```
$ pacman -Ss pugixml
mingw32/mingw-w64-i686-pugixml 1.9-1
    Light-weight, simple and fast XML parser for C++ with XPath support
    (mingw-w64)
mingw64/mingw-w64-x86_64-pugixml 1.9-1 [installed]
    Light-weight, simple and fast XML parser for C++ with XPath support
    (mingw-w64)
```

This occurs with both #3563 and #1983

The only way it works is if I manually add it to my include and lib dirs in my makefile:
```make
CXXFLAGS  += -I/mingw64/include/pugixml-1.8/
LDFLAGS += -L/mingw64/lib/pugixml-1.8/
```

This is undesirable, as it would be with many other packages, because I do not want to put the version number into my makefile, as I am only relying on the latest pugixml.

**Comment by Alexpux** [comment]
You must get flags from pkgconfig, this is right way. There are nothing to fix there

**Comment by RobertBColton** [comment]
Thank you, can you please provide me an example? I'm using regular make and not CMake.

**Comment by RobertBColton** [comment]
I think I got it with:
```make
$(shell pkg-config --libs pugixml)
```

Thanks!
