### ISSUE TITLE
mingw-w64-opencollada-git contains cmake files pointing to ${pkgdir}

### ISSUE THREAD

**Issue by ekpyron** [Alexpux/MINGW-packages#363]
/mingw*/lib/opencollada/cmake/OpenCOLLADATargets-release.cmake contains absolute paths containing the value of ${pkgdir} used at package creation time - they need to be replaced with e.g. ${_opencollada_rootdir} while adding

~~~~
get_filename_component(_opencollada_rootdir ${CMAKE_CURRENT_LIST_DIR}/../../../ ABSOLUTE)
~~~~

to the top of the file.

**Comment by elieux** [comment]
Would elieux/mingw-packages@c502552aa568e3ddb74d00b5367b2c35d5cb0b9f fix it? I don't know how to properly test cmake scripts.

**Comment by ekpyron** [comment]
Almost - you have to have curled brackets in ${PACKAGE_PREFIX_DIR}, so the second sed command would have to read:

     sed -i "s;$(cygpath -ma "${pkgdir}${MINGW_PREFIX}");\$\{PACKAGE_PREFIX_DIR\};" "${pkgdir}${MINGW_PREFIX}/lib/${_realname}/cmake"/*Targets*.cmake


To test it it would have sufficed to create a directory with a simple CMakeLists.txt file like the following:

    cmake_minimum_required(VERSION 3.0)
    find_package (OpenCOLLADA REQUIRED)
    message ("OpenCOLLADA include dirs: " ${OPENCOLLADA_INCLUDE_DIRS})
    message ("OpenCOLLADA libraries: " ${OPENCOLLADA_LIBRARIES})

And in that directory execute:

    /mingw64/bin/cmake.exe -G "MSYS Makefiles" .

And check whether there are errors and whether the paths are correct.

**Comment by elieux** [comment]
Thank you for the testcase. New commit: elieux/mingw-packages@500baa2857897c9c200485771a4b8bae1b527326

**Comment by ekpyron** [comment]
Yes, that one does it.
