### ISSUE TITLE
lldb: missing llvm dependency

### ISSUE THREAD

**Issue by mewmew** [Alexpux/MINGW-packages#3630]
Installing lldb with:

```bash
$ pacman -Sy mingw-w64-i686-lldb
```

and subsequently running lldb with:

```bash
$ lldb
```

gives the following error:

```
C:/msys64/mingw32/bin/lldb.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

Running strace on the binary gives us the answer on what library is missing (llvm.dll).

![LLVM.dll missing](https://image.ibb.co/jsx13c/lldb_missing_llvm_dll.png)

So, installing llvm through:

```bash
$ pacman -Sy mingw-w64-i686-llvm
```

results in a working lldb.

**EDIT:** note, this is true also for `mingw-w64-x86_64-lldb` requiring `mingw-w64-x86_64-llvm`.

**Comment by Alexpux** [comment]
Fixed in 6.0.0
