### ISSUE TITLE
mpv 0.28.2 missing vulkan-1.dll 

### ISSUE THREAD

**Issue by wurui1994** [Alexpux/MINGW-packages#3631]
![default](https://user-images.githubusercontent.com/12657158/39192981-13a70fe2-480d-11e8-96dc-3cdcf1365efb.png)
$ pacman -Qi mingw-w64-i686-mpv
名字           : mingw-w64-i686-mpv
版本           : 0.28.2-1
描述           : Video player based on MPlayer/mplayer2 (mingw-w64)
架构           : any
URL            : https://mpv.io/
软件许可       : GPL
组             : 无
提供           : 无
依赖于         : mingw-w64-i686-angleproject-git  mingw-w64-i686-ffmpeg
                 mingw-w64-i686-lcms2  mingw-w64-i686-libarchive
                 mingw-w64-i686-libass  mingw-w64-i686-libbluray
                 mingw-w64-i686-libcaca  mingw-w64-i686-libcdio
                 mingw-w64-i686-libcdio-paranoia  mingw-w64-i686-libdvdnav
                 mingw-w64-i686-libdvdread  mingw-w64-i686-libjpeg-turbo
                 mingw-w64-i686-lua51  mingw-w64-i686-rubberband
                 mingw-w64-i686-uchardet  winpty
可选依赖       : 无
要求被         : 无
被可选依赖     : 无
冲突与         : 无
取代           : 无
安装后大小     : 4.36 MiB
打包者         : Alexey Pavlov <alexpux@gmail.com>
编译日期       : 2018年04月23日 3:14:47
安装日期       : 2018年04月24日 22:09:43
安装原因       : 单独指定安装
安装脚本       : 否
验证者         : 数字签名

**Comment by ZachBacon** [comment]
You need the runtime https://vulkan.lunarg.com/

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/7bdae7560c6c65acefac1d5569c796a38d820121
