### ISSUE TITLE
Error building app with GTK3 and glade

### ISSUE THREAD

**Issue by arkkimede** [Alexpux/MINGW-packages#3637]
Hi,
I've build a simple application on Ubuntu using GTK3 + glade and it works
perfectly.

Than I've installed MSYS2 and all the file suggested to build application
with GTK3 and Glade.

First of all the compilation option -export-dynamic is not recognized ad I
obtain the following error:
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/.
./../../../x86_64-w64-mingw32/bin/ld.exe: warning: --export-dynamic is not
supported for PE+ targets, did you mean --export-all-symbols?

If I substitute with  --export-all-symbols  I obtain
gcc.exe: error: unrecognized command line option '--export-all-symbols'

Than I erase this option.

The compilation end without errors but if I run the executable:
(LAVORO.exe:5684): Gtk-WARNING **: 08:41:50.459: Could not find signal
handler 'on_button1_clicked'.  Did you compile with -rdynamic?

(LAVORO.exe:5684): Gtk-WARNING **: 08:41:50.459: Could not find signal
handler 'on_window_main_destroy'.  Did you compile with -rdynamic?

(LAVORO.exe:5684): Gtk-WARNING **: 08:41:50.459: Could not find signal
handler 'on_doPlot_clicked'.  Did you compile with -rdynamic?

(LAVORO.exe:5684): Gtk-WARNING **: 08:41:50.475: Could not find signal
handler 'on_cbox_changed'.  Did you compile with -rdynamic?

(LAVORO.exe:5684): Gtk-WARNING **: 08:41:50.475: Could not find signal
handler 'on_btn_exe_clicked'.  Did you compile with -rdynamic?

(LAVORO.exe:5684): Gtk-WARNING **: 08:41:50.475: Could not find signal
handler 'on_btn_quit_clicked'.  Did you compile with -rdynamic?

(LAVORO.exe:5684): Gtk-WARNING **: 08:41:50.491: Could not find signal
handler 'on_plotWindow_delete_event'.  Did you compile with -rdynamic?

(LAVORO.exe:5684): Gtk-WARNING **: 08:41:50.491: Could not find signal
handler 'on_close_plotWindow_clicked'.  Did you compile with -rdynamic?

(LAVORO.exe:5684): Gtk-WARNING **: 08:41:50.506: Could not find signal
handler 'on_plot_draw'.  Did you compile with -rdynamic?

Could you help me?

**Comment by nadelacruz** [comment]
Did you find the fix to this bug?
