### ISSUE TITLE
Latest mingw-w64 / gcc update breaks Inkscape build

### ISSUE THREAD

**Issue by Ede123** [Alexpux/MINGW-packages#3638]
I just noticed [today's Inkscape build](https://ci.appveyor.com/project/inkscape/inkscape/build/master-1252) is failing, it still worked fine for the [previous build](https://ci.appveyor.com/project/inkscape/inkscape/build/master-1249) less than 24 hours ago.

The error is happening while linking libinkscape_base.dll:  
"Error: export ordinal too large: 106954"

Details:
```
[1010/1012] Linking CXX shared library bin\libinkscape_base.dll
FAILED: bin/libinkscape_base.dll lib/libinkscape_base.dll.a 
cmd.exe /C "cd . && C:\msys64\mingw64\bin\g++.exe  -fopenmp -m64 -mms-bitfields -mthreads -mwindows -pthread -std=c++11   -shared -o bin\libinkscape_base.dll -Wl,--out-implib,lib\libinkscape_base.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles/inkscape_base.rsp  && cd ."
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Error: export ordinal too large: 106954
collect2.exe: error: ld returned 1 exit status
```

I assume this is related to 66be52cd17fe6f8a7ea2a5417800279c41c2e762 and/or 014550223ecce08407fa63fef093f78858cedb66 - any idea what changed?  

Is this a mingw-w64 regression or did we really hit some hard limit? According to info I found online ordinals are 16-bit values, though, so I wonder how that number could've suddenly increased by that much...

**Comment by Alexpux** [comment]
Well GCC itself not changed, just rebuilded so I assume this is mingw-w64 regression possibly

**Comment by Ede123** [comment]
OK, turns out this was completely unrelated to mingw-w64.

It was a [change in behavior](https://gitlab.kitware.com/cmake/cmake/issues/17944) in CMake 3.11 which caused the build type to be undefined (which caused the build to use debug symbols which is known to cause the aforementioned error on Windows)
