### ISSUE TITLE
Wrong symbol decorations in ANGLE-provided libGLESv2.dll and libEGL.dll

### ISSUE THREAD

**Issue by LRN** [Alexpux/MINGW-packages#3667]
The convention (followed by all GPU vendors and by MS) is for GL-related DLLs to export their symbols with undecorated names in the symbol table (since GL functions tend to be loaded at runtime, and only a compiler, reading header files, is able to correctly form the `@number` decoration to link a function, whereas user and loader code usually lacks this capability).

But ANGLE builds in MSYS2 repo export everything with stdcall decorations. Therefore, these DLLs cannot be used with any GL loader. The only way to use them is to link them, at link time, as if they were normal libraries (with obvious consequences).

**Comment by Alexpux** [comment]
@LRN  fixed in https://github.com/Alexpux/MINGW-packages/commit/4a04381673f735a473a7e346682c61e46d601880
