### ISSUE TITLE
ffmepg 4.0 broke gst-libav

### ISSUE THREAD

**Issue by filnet** [Alexpux/MINGW-packages#3668]
Current gst-libav does not work because it expects an older version of ffmpeg.

And gst-libav has build errors when using ffmepg 4.0 as some deprecated includes have been removed from ffmpeg.

PS : may be it was a bit premature to upgrade to ffmpeg 4.0 ?

**Comment by lazka** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=792900

arch has switched back to use the internal ffmpeg: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/gst-libav&id=e3b49f937a40df4a5861fb96c38a86bfebdb3b97

**Comment by lazka** [comment]
I've opened #3672

**Comment by lazka** [comment]
new package is up
