### ISSUE TITLE
ConEmu failed in Windows XP

### ISSUE THREAD

**Issue by FrankHB** [Alexpux/MINGW-packages#370]
When run in Windows XP SP3 with almost all patches installed, it complained "CreateProcessAsUserW could not be located in the dynamic link library KERNEL32.DLL". But the official package installed (as MSI) and run successfully. And [MSDN](http://msdn.microsoft.com/en-us/library/windows/desktop/ms682429(v=vs.85).aspx) shows this function should be in "Advapi32.dll". So I suspect it is a mingw-package-specific bug.

**Comment by Maximus5** [comment]
This may be closed, I think.
