### ISSUE TITLE
Is it possible to update cfitsio ?

### ISSUE THREAD

**Issue by lock042** [Alexpux/MINGW-packages#3728]
The version of cfitsio available in repo is kind of old. Moreover some security vulnerabilities have been fixed in 3.43. Could it be possible to update the package to the 3.45 ?

Cheers,

**Comment by filnet** [comment]
If you really need it and can't wait for another contributor to eventually do it, then you can always contribute the update yourself.

**Comment by filnet** [comment]
> - Did you plan to update cfitsio ?

It all depends who hides behind the "you" :)

There are no paid employees here, only free willing contributors.
Contributors usually do what they need, not what others need.

And I can't speak for the project owner (aka @Alexpux) but he usually answers the same as I did: "Feel free to do it yourself".

**Comment by Alexpux** [comment]
@lock042 currently as I remember cfitsio have issues with building because of conflict types with mingw headers

**Comment by lock042** [comment]
@filnet : I know and understand. I also contribute to an open-source project.
@Alexpux : OK, so it will be complicated. Thank you.

**Comment by Alexpux** [comment]
@lock042:
````
[  1%] Building C object CMakeFiles/cfitsio.dir/cfileio.c.obj
In file included from C:/repo/mingw-w64-cfitsio/src/cfitsio/fitsio2.h:4:0,
                 from C:/repo/mingw-w64-cfitsio/src/cfitsio/cfileio.c:13:
C:/repo/mingw-w64-cfitsio/src/cfitsio/fitsio.h:220:22: error: expected identifier or '(' before numeric constant
 #define TBYTE        11
                      ^
````

TBYTE is typedefed in mingw-w64 headers:
````
C:/building/msys64/mingw64/x86_64-w64-mingw32/include/tchar.h
121:  typedef wchar_t TBYTE,*PTBYTE;
779:  typedef unsigned char TBYTE,*PTBYTE;
978:  typedef unsigned char TBYTE,*PTBYTE;

C:/building/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h
350:  typedef WCHAR TBYTE, *PTBYTE;
374:  typedef unsigned char TBYTE, *PTBYTE;
````

**Comment by lock042** [comment]
That's a big issue indeed, but this issue should also occurred with previous versions ? no ?

**Comment by Alexpux** [comment]
@lock042 yeah I try some versions and it also have this bug.

**Comment by lock042** [comment]
OK, so How did you built the 3.410 ?
Thanks for taking a look. That's very nice.

**Comment by Alexpux** [comment]
@lock042 previous version seems was builded without curl libraries:

````
[  1%] Building C object CMakeFiles/cfitsio.dir/cfileio.c.obj
/C/building/msys64/mingw64/bin/gcc.exe -DCFITSIO_HAVE_CURL -I/C/building/msys64/mingw64/include  -march=x86-64 -mtune=generic -O2 -pipe  --save-temps -o CMakeFiles/cfitsio.dir/cfileio.c.obj   -c /C/repo/mingw-w64-cfitsio/src/cfitsio/cfileio.c
gcc.exe: warning: -pipe ignored because -save-temps specified
In file included from C:/building/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163:0,
                 from C:/building/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from C:/building/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/building/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
                 from C:/building/msys64/mingw64/include/curl/system.h:391,
                 from C:/building/msys64/mingw64/include/curl/curl.h:38,
                 from C:/repo/mingw-w64-cfitsio/src/cfitsio/cfileio.c:16:
C:/building/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:374:24: error: expected identifier or '(' before numeric constant
   typedef unsigned char TBYTE, *PTBYTE;
                        ^~
````

**Comment by lock042** [comment]
Nice catch

**Comment by Alexpux** [comment]
Build without CURL:
https://github.com/Alexpux/MINGW-packages/commit/bc52c0d9a6891bfd6db6859eba8b807f575db191

**Comment by lock042** [comment]
@Alexpux: Many thanks for your work !!

**Comment by acz13** [comment]
Is there fix or workaround for `TBYTE` conflict with cfitsio and mingw when compiling other libs? Not any use for windows TBYTE anyway...
