### ISSUE TITLE
gstreamer: update to  1.14.1

### ISSUE THREAD

**Issue by filnet** [Alexpux/MINGW-packages#3760]

**Comment by lazka** [comment]
somewhat unrelated: have you tried building any of the gstreamer libs with meson yet?

**Comment by filnet** [comment]
Nope, I am old school...

Not sure the meson build is 100% equivalent to the current build.
Do you want to give it a try ? I won't have much time in the weeks that come.

**Comment by lazka** [comment]
> Nope, I am old school...
> 
> Not sure the meson build is 100% equivalent to the current build.

It might need some patches, but upstream is using it to build with msvc afaik, so it shouldn't be too far off.

> Do you want to give it a try ? I won't have much time in the weeks to come.

I will give it a try. Do you want to handle the 1.14.1 update, or should I have a look?

> PS : has your gst-inspect patch been merged ?

No update there, but I've changed the default registry path in my app so the cache will be recreated when users update, working around the issue.

**Comment by filnet** [comment]
> I will give it a try. Do you want to handle the 1.14.1 update, or should I have a look?

Be my guest (if you have the time...).

**Comment by lazka** [comment]
> I will give it a try. Do you want to handle the 1.14.1 update, or should I have a look?
> 
> Be my guest (if you have the time...).

#3779

**Comment by lazka** [comment]
I've started with gstreamer+gst-plugins-base and filed some patches upstream: https://bugzilla.gnome.org/show_bug.cgi?id=796273 https://bugzilla.gnome.org/show_bug.cgi?id=796274

**Comment by filnet** [comment]
@lazka what you are doing is good to get ready for the meson switch but maybe it is still a bit early.

Quoting Tim-Philipp Müller : "meson is still not our primary build system".

We will see what the gst-plugins-* projects  yield... but I am sure some plugins will be lost when switching to meson.

**Comment by lazka** [comment]
I'm always diffing the meson build with the autotools one to make sure we get the same result.

**Comment by lazka** [comment]
But you're right, there still seems to be quite a bit of meson activity upstream. I kinda had assumed it was further along as it was one of the first projects to adopt meson, but it's of course also one of the more complex projects.

I'll convert gstreamer+gst-plugins-base when 1.14.2 is out and have another look at the rest with 1.16.

**Comment by lazka** [comment]
#3779 has been merged

Somewhat related to the update, I tried the newly rewritten wasapisink, but hit some problems on win7 and I've filed https://bugzilla.gnome.org/show_bug.cgi?id=796280
