### ISSUE TITLE
GTK+3 application won't run on Windows

### ISSUE THREAD

**Issue by liudonghua123** [Alexpux/MINGW-packages#3794]
When I try the `example-0.c` on https://developer.gnome.org/gtk3/stable/gtk-getting-started.html, I can build successfully in my `cmd` (I have configured the PATH environment variable), but run with the errors as the snapshot below.

![image](https://user-images.githubusercontent.com/2276718/40342791-3cb8a342-5dbf-11e8-91d7-1c51265d6866.png)
![image](https://user-images.githubusercontent.com/2276718/40342821-5c071a12-5dbf-11e8-978a-51a4822f238f.png)

Also note if I didn't close the first error msgbox quickly, the second error msgbox won't shown. This is really strange.

However, I can run it (`./example-0.exe`) without this problem in my `C:\msys32\mingw32.exe`

![image](https://user-images.githubusercontent.com/2276718/40342968-2386f4f4-5dc0-11e8-878c-b26cd7efccb1.png)

**Comment by liudonghua123** [comment]
My PATH environment variable is as below.

![image](https://user-images.githubusercontent.com/2276718/40343132-fb0c7d5e-5dc0-11e8-8783-a8d23343a4a1.png)

**Comment by TheDcoder** [comment]
I am essentially having the same issue but it won't work even from the MINGW shell. I am also getting 2 errors but they are a bit different:
```
The procedure entry point deflateSetHeader could not be located in the dynamic link library C:\msys64\mingw64\bin\libgio-2.0-0.dll. 
```
and
```
The procedure entry point inflateReset2 could not be located in the dynamic link library C:\msys64\mingw64\bin\libpng16-16.dll. 
```

**Comment by liudonghua123** [comment]
@TheDcoder Did you installed the packages list on https://gtk.org/download/windows.php ?

**Comment by TheDcoder** [comment]
I did install the packages for GTK, otherwise the compiler would not have found the headers and libs during compile time :)

On 24 May 2018 8:29:44 AM IST, liudonghua <notifications@github.com> wrote:
>@TheDcoder Did you installed the packages list on
>https://gtk.org/download/windows.php ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Alexpux/MINGW-packages/issues/3794#issuecomment-391572255

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tschoonj** [comment]
@TheDcoder I bet you have two zlib1.dll's on your system. What is the output on your MSYS2 shell for:

```
which zlib1.dll
```

**Comment by TheDcoder** [comment]
@tschoonj You were right! Albeit `which zlib1.dll` did not find any files because my shell doesn't have them in path (I lauch the executable externally), however `where zlib1.dll` showed two files:
```
C:\Users\TheDcoder>where zlib1.dll
C:\Program Files\Intel\WiFi\bin\zlib1.dll
C:\msys64\mingw64\bin\zlib1.dll
```

The rouge `zlib1.dll` from Intel was the problem, after I renamed it my executable worked perfectly!

It was tricky, but thanks!

**Comment by liudonghua123** [comment]
@tschoonj Thanks, you get the point, it's the zlib1.dll priority problem.
![image](https://user-images.githubusercontent.com/2276718/40570654-94fa5494-60bf-11e8-83ad-fa9b6a695263.png)

**Comment by LRN** [comment]
It is very unhealthy to put random things into PATH.

I would suggest either adjusting the installation instructions to mention this problem, or adding this to the List Of Most Common Issues, or writing a tool that would run in post-install step of any package and check for exe and dll files in PATH shadowing the exe and dll files in mingw bin subdirectory.

**Comment by TheDcoder** [comment]
@LRN While it is true that it is not a good practice to add random things to PATH, most additions cannot be helped as they are performed by installers of other programs on the computer. And if you are you developer who deals with C you should know what to put in your PATH anyway 😄

During deployment, I prefer to place all the required DLLs in the same folder as my executable so that they take priority over items in PATH.
