### ISSUE TITLE
pip: command not found

### ISSUE THREAD

**Issue by billskeen68** [Alexpux/MINGW-packages#3797]
(3/3) installing mingw-w64-x86_64-python2-pip      [#####################] 100%
/
mingw.sh: line 39: pip: command not found

Trying to install Amazon Alexa AVS on Windows 10 Pro machine. Install works great until this error. 

Any ideas?

**Comment by lazka** [comment]
My guess would be that `C:\msys64\mingw64` isn't in your PATH

**Comment by billskeen68** [comment]
Good guess. Did I miss a step setting the path or is that something the installation should have done?

**Comment by lazka** [comment]
I don't know what your setup is, but C:/msys64/mingw64.exe starts a shell with the right PATH for the mingw 64bit env.

Another way is to start a login shell with MSYSTEM set: `MSYSTEM=MINGW64 /usr/bin/bash -lc 'echo $PATH'`
