### ISSUE TITLE
mingw-w64-unicorn: No pre-build package available

### ISSUE THREAD

**Issue by JayFoxRox** [Alexpux/MINGW-packages#3808]
This PKGBUILD has been provided since September 2017 with #2903 , however, these past 8 months, we never seem to have gotten an easy-to-install package on the official MSYS repos.

As a crude workaround, we have to keep this in our projects build instructions (including non-unicorn packages needed for our project):

```
mkdir unicorn
cd unicorn
wget https://raw.githubusercontent.com/Alexpux/MINGW-packages/master/mingw-w64-unicorn/PKGBUILD
MINGW_INSTALLS=mingw64 makepkg-mingw -sLf -i
cd ..
pacman -S mingw-w64-x86_64-SDL2 mingw-w64-x86_64-glew mingw-w64-x86_64-openal mingw-w64-x86_64-enet
```

Ideally we'd just have to do (which does not work yet):

```
pacman -S mingw-w64-x86_64-unicorn mingw-w64-x86_64-SDL2 mingw-w64-x86_64-glew mingw-w64-x86_64-openal mingw-w64-x86_64-enet
```

I've had issues with outdated packages in the past and the response was: "we build packges every once in a while"; I get that, but 8 months is a long time, and I'm starting to think that this package was just forgotten.

The PKGBUILD is maintained by @zrax , although I believe that building / distribution is not their responsibility?

**Comment by Alexpux** [comment]
Uploaded
