### ISSUE TITLE
[gcc] is the patch for xmmintrin.h still needed ?

### ISSUE THREAD

**Issue by lhmouse** [Alexpux/MINGW-packages#3850]
https://github.com/Alexpux/MINGW-packages/blob/52bf9247d9c308ac416b861e6eef425fb2747cd3/mingw-w64-gcc/0009-gcc-make-xmmintrin-header-cplusplus-compatible-depre.patch#L8

As mentioned above this could be safely removed now.

**Comment by lhmouse** [comment]
Related issue: #3850

**Comment by Alexpux** [comment]
@lhmouse I will do it when upgrade to 8.1

**Comment by lhmouse** [comment]
ack.
