### ISSUE TITLE
gdb 8.1 crash

### ISSUE THREAD

**Issue by lokimx88** [Alexpux/MINGW-packages#3851]
window 7 64bit

mingw64/mingw-w64-x86_64-gdb 8.1-1 (mingw-w64-x86_64-toolchain) [已安装]
    GNU Debugger (mingw-w64)

 问题事件名称:	APPCRASH
  应用程序名:	gdb.exe
  应用程序版本:	0.0.0.0
  应用程序时间戳:	00000000
  故障模块名称:	msvcrt.dll
  故障模块版本:	7.0.7600.16385
  故障模块时间戳:	4a5bdfbe
  异常代码:	c0000005
  异常偏移:	00000000000011e1
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	7881
  其他信息 2:	78815c2f53ecfe22909346eef6797be0
  其他信息 3:	a809
  其他信息 4:	a809dec9fc45b62da67e4e569e15cd44

I have downgrade gdb to 8.0.1.  It works fine

**Comment by lazka** [comment]
It seems to work fine here. Do you have an example which crashes for you?

**Comment by lhmouse** [comment]
Please do not post messages in Chinese cause most people don't read it. It is both irresponsible and impolite.

**Comment by lokimx88** [comment]
the message is the original message  from the runtime-error window.
 If It was modified,how can anyone know  that is right?

It works now today with  someother updates.
BTW,please take of your anger sometimes

**Comment by lhmouse** [comment]
我认为，在特定场合使用 _适当的_ 语言体现的是基本的涵养。我们可以容忍你的语法错误，但是我们不会容忍那些不懂得礼貌的笨蛋。我建议你看看 [这个](http://catb.org/~esr/faqs/smart-questions.html#writewell)。
I think that using _the appropriate_ language on a specific occasion is of the fundamental etiquette. We will be tolerant for grammatical mistakes, but we will not forgive rude morons. I suggest you take a look at [this](http://catb.org/~esr/faqs/smart-questions.html#writewell).
