### ISSUE TITLE
mingw-w64-crt-git: CryptImportPublicKeyInfoEx2 is missing from the 32-bit version

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#3909]
It looks like the 64-bit version is OK, but the 32-bit version is missing this export.

```
$ nm /mingw64/x86_64-w64-mingw32/lib/libcrypt32.a | grep CryptImportPublicKeyInfoEx2
0000000000000000 I __imp_CryptImportPublicKeyInfoEx2
0000000000000000 T CryptImportPublicKeyInfoEx2
```

However 32-bit version returns empty:
`nm /mingw32/i686-w64-mingw32/lib/libcrypt32.a | grep CryptImportPublicKeyInfoEx2`

I discovered this when I was trying to compile `xmlsec`, and the 32-bit version compilation failed, while the 64-bit version succeeded.

**Comment by Alexpux** [comment]
@peterbud report it upstream to mingw-w64

**Comment by peterbud** [comment]
ok, thx
