### ISSUE TITLE
file: static library not included

### ISSUE THREAD

**Issue by piguribiba** [Alexpux/MINGW-packages#3917]
Static libraries for file aren't included in the package. I believe this might be a mistake given the staticlibs option specified in the package. By default, file won't build static libraries and the "--enable-static" flag should be passed to the configure script to build it.

**Comment by ZachBacon** [comment]
not entirely true, there's a good deal of packages that include static libs https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-wxWidgets/PKGBUILD for example, however there are issues though where some static libs seem to link to shared dependencies. But that's another issue, but yes there are static libs and they are packaged from what I've seen. Some like sfml though doesn't seem to have that enabled. 
So there are some inconsistencies.

**Comment by Adsun701** [comment]
This issue should be fixed by the already-merged #3929.
