### ISSUE TITLE
Anybody can build mingw-w64-python-path?

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#3936]
I have tried to build [python-path](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-python-path/PKGBUILD), and I got the following error message at the end of the packaging:
```
running install_egg_info
running egg_info
writing path.py.egg-info/PKG-INFO
writing dependency_links to path.py.egg-info/dependency_links.txt
writing top-level names to path.py.egg-info/top_level.txt
error: [WinError 267] The directory name is invalid
```
Is it me only?

**Comment by lazka** [comment]
Same here

**Comment by peterbud** [comment]
Thanks @lazka the confirmation. 
@oroppas as you are the maintainer: any advice?

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/f70c16812fbf778e2c2268d61ca7591b47f4f3c8

**Comment by peterbud** [comment]
Thanks!
