### ISSUE TITLE
Clang: rebuild needed?

### ISSUE THREAD

**Issue by eidheim** [Alexpux/MINGW-packages#3944]
I get this error window using `strace` on a program linked with libclang:
"The procedure entry point ___emutls_get_address could not be located in the dynamic link library C:\msys64\mingw64\bin\clang.dll."

To reproduce:
```sh
git clone https://gitlab.com/cppit/libclangmm
cd libclangmm
mkdir build && cd build
cmake -G"MSYS Makefiles" -DBUILD_TESTING=1 ..
make
strace tests/cursor_test
```

**Comment by Alexpux** [comment]
@eidheim we working on upgrading clang to 6.0.0
