### ISSUE TITLE
GDB 8.1(64bit) crash with info reg command

### ISSUE THREAD

**Issue by erw7** [Alexpux/MINGW-packages#3946]
GDB 8.1(`mingw-w64-x86_64-gdb-8.1-1`) will crash with `info reg` command.

I believe this problem is caused by the upstream. I do not know whether that is correct or not. But, the problem did not occur with the following patch.

```
diff --git a/gdb/arch/amd64.c b/gdb/arch/amd64.c
index d31d8f1f75..ebc9aa563b 100644
--- a/gdb/arch/amd64.c
+++ b/gdb/arch/amd64.c
@@ -55,9 +55,10 @@ amd64_create_target_description (uint64_t xcr0, bool is_x32, bool is_linux)
     regnum = create_feature_i386_64bit_core (tdesc, regnum);

   regnum = create_feature_i386_64bit_sse (tdesc, regnum);
-  if (is_linux)
+  if (is_linux) {
     regnum = create_feature_i386_64bit_linux (tdesc, regnum);
-  regnum = create_feature_i386_64bit_segments (tdesc, regnum);
+    regnum = create_feature_i386_64bit_segments (tdesc, regnum);
+  }

   if (xcr0 & X86_XSTATE_AVX)
     regnum = create_feature_i386_64bit_avx (tdesc, regnum);
```

Ref. https://sourceware.org/bugzilla/show_bug.cgi?id=22854

**Comment by ssbssa** [comment]
That patch was already merged with #3686.

**Comment by erw7** [comment]
@ssbssa  Thanks. I understand that this patch has already been merged into `mingw-w64-gdb-git`. But why are not merged with `mingw-w64-gdb`? I will close this for now.

**Comment by erw7** [comment]
I do not know if this is fine, but I created a new PR(#3952).
