### ISSUE TITLE
clang dynamic library name fixes ignored

### ISSUE THREAD

**Issue by revelator** [Alexpux/MINGW-packages#3953]
the hack used to enable windows specific naming of dll's on clang and llvm no longer seems to work,.
A fresh build left me with LLVM.dll and clang.dll and a few others with a lib prefix before the name, so now they are named libLLVM.dll and libClang.dll. While on itself this should not cause any problems it breaks previous packages like codelite doxygen and QT5 which expect LLVM.dll and clang.dll.

**Comment by Alexpux** [comment]
Most DLLs builded with mingw have lib prefix that prevent in many cases conflicts with system installed dlls. And yes need to rebuild some packages after that. Deoxygenated already rebuilded without clang. 
Qt5/qt-creator in any case need to be updated as codelite too. So I don’t see any big issue in it

**Comment by revelator** [comment]
Well qt creator does not build atm because of some bug with QString ->

/qt-creator-opensource-src-4.6.1/src/plugins/qbsprojectmanager/qbsprofilessettingspage.cpp:112:69: error: 'class QString' has no member named 'toString'; did you mean 'QString'?
     m_ui.versionValueLabel->setText(qbs::LanguageInfo::qbsVersion().toString());

I suspect toString() might need to be renamed to toStdString() but im not certain on that part.
Also codelite seems to not like the latest crt and errors out about a multitude of conflicting function names in the crt :/

**Comment by Alexpux** [comment]
I will update qtcreator to 4.6.2 when finish qt-5.11

**Comment by revelator** [comment]
toString is actually a member of QString but the QString header is not included in that particular source file so i patched it in, doing a full build now. Lets hope it fixes this.

**Comment by revelator** [comment]
Well that was a colossal bust :/ no cigar including QString.
4.6.2 version exhibits the same error.

**Comment by Alexpux** [comment]
I cant reproduce your errors with QString. New packages uploaded

**Comment by revelator** [comment]
Ok that's odd, but if it builds on your end then the problem must be here.

Ill reinstall the packages from server then.


Den 17-06-2018 kl. 20:39 skrev Алексей:
