### ISSUE TITLE
static freetype enables -mms-bitfields

### ISSUE THREAD

**Issue by LordAro** [Alexpux/MINGW-packages#3966]
Not quite sure if the issue is here or upstream, but `pkg-config --static --cflags freetype2` results in:

    -mms-bitfields -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include

Coupled with https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52991, this is really very inconvenient for whatever program is being compiled with freetype. Is the `-mms-bitfields` actually necessary?

**Comment by mingwandroid** [comment]
mms-bitfields has been the default for absolutely ages.

So the flag is irrelevant. You've shown nothing anyone could use here to help you with your actual problem which you've not described.

**Comment by LordAro** [comment]
Interesting. How long is "absolutely ages" ?

Previously I've only used `pragma pack` on windows, using `__attribute__((packed))` everywhere else. (Therefore setting `-mno-msbitfields` where relevant). I'm guessing this is now an incorrect assumption?
