### ISSUE TITLE
diff can't load libsigsegv-2.dll

### ISSUE THREAD

**Issue by karen-arutyunov** [Alexpux/MINGW-packages#3989]
After MSYS2 upgrade trying to run diff fails like this:

C:/msys64/mingw64/bin/diff.exe: error while loading shared libraries: libsigsegv-2.dll: cannot open shared object file: No such file or directory

It seems that mingw-w64-x86_64-diffutils 3.6-1 package lacks dependency on mingw-w64-x86_64-libsigsegv.

The same is about i686 architecture.

**Comment by peterbud** [comment]
I cannot repro this - can you elaborate?
```
$ /mingw64/bin/diff --version
diff (GNU diffutils) 3.6
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Paul Eggert, Mike Haertel, David Hayes,
Richard Stallman, and Len Tower.
```

Also it works in cmd prompt:
```
C:\msys64\mingw64\bin>diff.exe --version
diff (GNU diffutils) 3.6
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Paul Eggert, Mike Haertel, David Hayes,
Richard Stallman, and Len Tower.
```

**Comment by lazka** [comment]
> I cannot repro this - can you elaborate?

Try after `pacman -R mingw-w64-i686-libsigsegv`

**Comment by peterbud** [comment]
I don't have `libsigsegv `installed:
```
$ pacman -Ss libsigs
mingw32/mingw-w64-i686-libsigsegv 2.12-1
    Page fault detection library (mingw-w64)
mingw64/mingw-w64-x86_64-libsigsegv 2.12-1
    Page fault detection library (mingw-w64)

```

**Comment by Alexpux** [comment]
@peterbud do you install difficult from repo or if your own builded?

**Comment by peterbud** [comment]
I see, that was the problem: 
* Using the repo version (3.6-1), indeed I got the same error message
* I have had no problem with the version I have just built (3.6-2), using the new lag as @karen-arutyunov suggested.

**Comment by lazka** [comment]
f265c223794a
