### ISSUE TITLE
bison uses hardcoded path to call m4

### ISSUE THREAD

**Issue by elieux** [Alexpux/MINGW-packages#402]
I see a call to `C:\msys64\mingw64\bin\m4.exe` even though my MSYS2 installation is elsewhere.

To test: install mingw-bison, download [parser.y]
(https://github.com/openscad/openscad/blob/master/src/parser.y) and call `bison parser.y`.

**Comment by Alexpux** [comment]
Fixed in mingw-bison

**Comment by elieux** [comment]
Cool, it seems to work now. Should there be an issue for mingw-w64-flex?

**Comment by Alexpux** [comment]
mingw-flex need a lot of work
