### ISSUE TITLE
python3-pyzmq package missing dependency on zeromq package?

### ISSUE THREAD

**Issue by aha79** [Alexpux/MINGW-packages#4020]
I installed the 'mingw-w64-x86_64-python3-pyzmq' and got, when trying to import zmq in python, a "DLL not found" error.
This could be resolved by also installing the 'mingw-w64-x86_64-zeromq' package. Then the python application started correctly.
So perhaps there is a missing package dependency?

This may apply to the 'mingw-w64-x86_64-python2-pyzmq' and other variants as well.

**Comment by lazka** [comment]
Looks like it. Can you create a PR with a fix?

**Comment by Alexpux** [comment]
Fixed
