### ISSUE TITLE
can't build openal

### ISSUE THREAD

**Issue by RemoveRusky** [Alexpux/MINGW-packages#4031]
I wanted to fix a bug in current openal package but I can't even seem to build the unmodified version in msys2 

Enigma@DESKTOP-6PLODR1 MSYS ~/MINGW-packages/mingw-w64-openal
$ MINGW_INSTALLS=mingw64 makepkg-mingw -sLf
==> Making package: mingw-w64-openal 1.18.2-1 (Fri, Jun 29, 2018 10:03:52 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found openal-soft-1.18.2.tar.bz2
  -> Found 0001-versioned-w32-dll.mingw.patch
  -> Found 0002-w32ize-portaudio-loading.mingw.patch
  -> Found 0003-openal-not-32.mingw.patch
  -> Found 0004-disable-OSS-windows.patch
==> Validating source files with sha256sums...
    openal-soft-1.18.2.tar.bz2 ... Passed
    0001-versioned-w32-dll.mingw.patch ... Passed
    0002-w32ize-portaudio-loading.mingw.patch ... Passed
    0003-openal-not-32.mingw.patch ... Passed
    0004-disable-OSS-windows.patch ... Passed
==> Extracting sources...
  -> Extracting openal-soft-1.18.2.tar.bz2 with bsdtar
==> Starting prepare()...
patching file CMakeLists.txt
Hunk #1 succeeded at 1254 (offset 21 lines).
patching file Alc/backends/portaudio.c
patching file CMakeLists.txt
Hunk #1 succeeded at 1176 (offset 24 lines).
patching file CMakeLists.txt
Hunk #1 succeeded at 896 (offset 138 lines).
Hunk #2 succeeded at 912 (offset 138 lines).
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR)
-- Could NOT find AudioIO (missing: AUDIOIO_INCLUDE_DIR)
-- Could NOT find SoundIO (missing: SOUNDIO_LIBRARY SOUNDIO_INCLUDE_DIR)
-- Could NOT find QSA (missing: QSA_LIBRARY QSA_INCLUDE_DIR)
CMake Error at C:/msys64/mingw64/share/cmake-3.11/Modules/CheckIncludeFiles.cmake:61 (message):
  Unknown arguments:

    -D_WIN32_WINNT=0x0502

Call Stack (most recent call first):
  CMakeLists.txt:970 (CHECK_INCLUDE_FILES)

-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/Enigma/MINGW-packages/mingw-w64-openal/src/build-shared-x86_64-w64-mingw32/CMakeFiles/CMakeOutput.log".
See also "C:/msys64/home/Enigma/MINGW-packages/mingw-w64-openal/src/build-shared-x86_64-w64-mingw32/CMakeFiles/CMakeError.log".
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by RemoveRusky** [comment]
bump

**Comment by mingwandroid** [comment]
If you wanted to fix a bug then go ahead and fix this one too.

**Comment by Alexpux** [comment]
@RemoveRusky it fixed upstream https://github.com/kcat/openal-soft/commit/cae4b1a062b53dd25eba7caa41622be730106749

**Comment by Alexpux** [comment]
Fixed in repo

**Comment by RobertBColton** [comment]
I'm still not able to use it statically.
