### ISSUE TITLE
Clang doesn't find standard headers with option -stdlib=libc++

### ISSUE THREAD

**Issue by epigramx** [Alexpux/MINGW-packages#4032]
e.g. clang++ can't find iostream on a standard cpp hello world. The -v option of clang shows the search paths.  By using -I and pointing it to the 7.3.0 files it may eventually find them all but then it might complain of not finding libc++ and I didn't grep it anywhere.

**Comment by mathias-freire** [comment]
When using -stdlib=libc++, you must point to libc++ headers by -I flag

**Comment by XNQrE** [comment]
Since this is still open, apparently it doesn't even compile with libc++ on the current version since it returns undefined references.
