### ISSUE TITLE
mingw-w64-x86_64-devhelp doesn't work

### ISSUE THREAD

**Issue by CCTV-1** [Alexpux/MINGW-packages#4039]
run `devhelp`
ouput:`D:/MSYS2/mingw64/bin/devhelp.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory`.
reinstall do not solve the problem.
now pkg mingw-w64-x86_64-devhelp version 3.8.2-2.
3.8.2-1 it seems to work well,but i didn't find the pkg test.

**Comment by lazka** [comment]
libenchant had a so version bump

**Comment by lazka** [comment]
I've started looking into this, I'll open a PR later.

**Comment by Dremor** [comment]
Problem seem to be back.

**Comment by lazka** [comment]
Afair someone said that gtkwebkit no longer builds and since it's old and unmaintained it's unlikely to change.
