### ISSUE TITLE
python 3.7: loading of classes from sibling files fails with ModuleNotFoundError

### ISSUE THREAD

**Issue by chhe** [Alexpux/MINGW-packages#4062]
Since Python was updated from 3.6 to 3.7 loading of classes from sibling files does not work anymore.

Steps to reproduce:

`file_with_class.py`:
```
class TestClass: pass
```

`import_class_from_file.py`:
```
from file_with_class import TestClass

testClass = TestClass()
```

Save both files in the same directory (`$DIRECTORY`). Run `import_class_from_file.py` (`python3.7 $DIRECTORY/import_class_from_file.py`). This yields the following error:

```
$ python3 /c/45/import_class_from_file.py
Traceback (most recent call last):
  File "C:/45/import_class_from_file.py", line 1, in <module>
    from file_with_class import TestClass
ModuleNotFoundError: No module named 'file_with_class'
```

**Comment by Alexpux** [comment]
@chhe seems it only fail from MSYS shell, CMD works ok for me

**Comment by Alexpux** [comment]
Also blender stop working after migrate to python 3.7

**Comment by chhe** [comment]
I can confirm it works when called from Windows CMD. Maybe some path conversion problem when being called from an MSYS shell?

**Comment by Alexpux** [comment]
@chhe maybe

**Comment by Alexpux** [comment]
I get this issue myself too when build some packages. Need investigate it

**Comment by lazka** [comment]
I remember a similar issue even with 3.6 if CWD isn't the directory of the executed script.

**Comment by chhe** [comment]
I just checked on a PC where I didn't update MINGW's Python to 3.7. The minimal test case I posted works with 3.6. It also works with MSYS2's Python 3.6.

**Comment by chhe** [comment]
@lazka You added `is_cygpty` to a couple of `isatty` conditions. My guess would be you either missed a (few) `isatty` condition(s) or you added `is_cygpty` where it should not be added. I could be completely off though.

**Comment by lazka** [comment]
@chhe I'll have a look

**Comment by AndreasPK** [comment]
This seems related: https://bugs.python.org/issue34103

**Comment by Alexpux** [comment]
@AndreasPK our python is very different from version for Windows distributed from python.org, as there are no official support for Mingw platform. There are was discussion in the past with Python developers and they don't want to support Mingw platform for building python. So don't report issues upstream and don't tell that it related. You create PR upstream about our own distribution but there are nothing related to issue on upstream

**Comment by AndreasPK** [comment]
> There are was discussion in the past with Python developers and they don't want to support Mingw platform for building python. So don't report issues upstream

I did not know where to report it. I will know in the future.

**Comment by Alexpux** [comment]
Nothing to report. Issue is already posted here. Don't know when it will be resolved

**Comment by elieux** [comment]
Thanks to @AndreasPK, there's maybe even simpler test for this. Put `import sys; print(sys.path[0])` in a file somewhere, let's say `W:\temp\test.py`. Then open a *MINGW64* shell (or `set MSYSTEM=MINGW64`). Then run the script from a different directory, like from your home folder: `python3 W:\temp\test.py`

mingw-w64-x86_64-python3-3.6.5-1: `W:\temp`
mingw-w64-x86_64-python3-3.7.0-7: *(empty)*

**Comment by Alexpux** [comment]
I hope fixed in 3.7.0-9

**Comment by mheinzler** [comment]
This fixed it for me. Thanks @Alexpux.

**Comment by LigH-de** [comment]
Confirming for MABS: vulkan built.
