### ISSUE TITLE
How to install mingw-w64-arm-none-eabi-gcc

### ISSUE THREAD

**Issue by HaidStefan** [Alexpux/MINGW-packages#4068]
Hello,

I have seen that a mingw-w64-arm-none-eabi-gcc package exists. I have installed the latest MSYS2. Also I have updated everything with `pacman -Syu` .
After that I tried to install the package with `pacman -S mingw-w64-arm-none-eabi-gcc` but that did not work. I thought that this package repo is the repo which MSYS2 is using. Or is there any other mechanism to install msys2. My goal is to build micropython for STM32 on windows 10.  I hope I can do that in any way... 
But for that I need a gnu arm tool-chain. 

many thanks
cheers 
stefan

**Comment by Alexpux** [comment]
PKGBUILD exists but there are no binary package for it. I don’t have time to support it so feel free to build it yourself

**Comment by HaidStefan** [comment]
Okay so I have to clone the repo and build it that way - right?
