### ISSUE TITLE
qt5-static QFlatpakThemePlugin pulls in 2 DllMain

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MINGW-packages#4080]
```
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib\libcrypto.a(cryptlib.o):(.text+0xad0): multiple definition of `DllMain'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib\libdbus-1.a(libdbus_1_la-dbus-sysdeps-thread-win.o):(.text+0x140): first defined here
```

**Comment by Alexpux** [comment]
As you see dll main comes from third party libraries, not qt5-static

**Comment by Optiligence** [comment]
So is the build for those incorrect? 

Both `mingw-w64-x86_64-dbus` and `mingw-w64-x86_64-openssl` provide `*.a` as well as `*.dll.a` versions, so there should be no `DllMain` in the `*.a`. 

But i’m not sure if this plugin is supposed to be available on Windows anyway. 
It just means that using `CMAKE_AUTOSTATICPLUGINS` without manual intervention is currently broken.

**Comment by Alexpux** [comment]
@Optiligence DllMain seems doesnt need to be in *.a but it is upstream issue seems. Feel free to try solve it

**Comment by Alexpux** [comment]
@Optiligence QFlatpack is really extra files in qt5-static need to find why it installed for Windows

**Comment by Alexpux** [comment]
@Optiligence flatpack theme are going to be installed because of dbus in config. Need guard it to not use under win32
https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platformthemes/platformthemes.pro

**Comment by Alexpux** [comment]
Does we really need DBUs module for Qt5 under Windows? Maybe completaly disable it

**Comment by Optiligence** [comment]
yeah, i think it’s fine to disable it

thx for the workaround (fb37a71d0c696b0490595f248be530077cc927f5)

PS: i didn’t want to create an account to file a dbus bug
