### ISSUE TITLE
sophos recognizes part of the mingw-w64 toolchain as malware

### ISSUE THREAD

**Issue by zimmermm** [Alexpux/MINGW-packages#4085]
As of today, sophos (but accroding to https://www.virustotal.com/de/ no other virus scanner) recognizes the following files as malware:
\msys64\mingw32\bin\brotli.exe
\msys64\mingw32\bin\dllwrap.exe
\msys64\mingw32\bin\elfedit.exe

**Comment by Alexpux** [comment]
I don’t really care about it. If you think yourself that this is malware then build this packages yourself

**Comment by zimmermm** [comment]
Totally OK! I see your point

**Comment by jeroen** [comment]
I built this myself and also seeing this warning, so it's likely a false positive.
