### ISSUE TITLE
qtcreator 4.7.0-1 throws 'Sqlite::StatementHasError' when launching

### ISSUE THREAD

**Issue by askondro** [Alexpux/MINGW-packages#4092]
$ qtcreator
terminate called after throwing an instance of 'Sqlite::StatementHasError'

**Comment by Alexpux** [comment]
You need remove  ````qtcreator/symbol-experimental-v1.db```` in your user home directory

**Comment by jagannatharjun** [comment]
can't able to find the file:
```
E:\Cpp\msys64>cd mingw64

E:\Cpp\msys64\mingw64>dir /s symbol-experimental-v1.db
 Volume in drive E has no label.
 Volume Serial Number is F2B8-2ACA
File Not Found

E:\Cpp\msys64\mingw64>cd ..

E:\Cpp\msys64>dir /s symbol-experimental-v1.db
 Volume in drive E has no label.
 Volume Serial Number is F2B8-2ACA
File Not Found
```

**Comment by jagannatharjun** [comment]
it was under %AppData%/qtproject/qtcreator
thanks working now

**Comment by askondro** [comment]
Deleting %AppData%/qtproject/qtcreator/symbol-experimental-v1.db helped.

Thanks!
