### ISSUE TITLE
zlib/minizip, no tm_zip member in zip_fileinfo struct

### ISSUE THREAD

**Issue by ukhf-jm** [Alexpux/MINGW-packages#4099]
Updated zlib yesterday and now some code that I have which depends on minizip/zip.h is broken as the `zip_fileinfo` struct is changed.  

I've double checked by downloading the latest 1.2.11 release from the zlib site and the struct is fine there and contains the `tm_zip` member as expected.  

Struct as is in the 1.2.11 release
```
typedef struct
{
    tm_zip      tmz_date;       /* date in understandable format           */
    uLong       dosDate;       /* if dos_date == 0, tmu_date is used      */
/*    uLong       flag;        */   /* general purpose bit flag        2 bytes */

    uLong       internal_fa;    /* internal file attributes        2 bytes */
    uLong       external_fa;    /* external file attributes        4 bytes */
} zip_fileinfo;
```

Struct as it is in mingw32/mingw64
```
typedef struct
{
    uint32_t    dos_date;
    uint16_t    internal_fa;        /* internal file attributes        2 bytes */
    uint32_t    external_fa;        /* external file attributes        4 bytes */
} zip_fileinfo;
```

I've had a look through the patches in the zlib folder and saw that it was pulling the minizip source from https://github.com/nmoinvaz/minizip/commit/7914ff3c.  
It seems that [this commit](https://github.com/nmoinvaz/minizip/commit/28ad5bf4fb7ceb1014e1d80c9b64ce52bb329329) refactored the struct and hence broke my code.   

Should the minizip sources be pulled from that repo or should it be sticking with the one provided by the zlib authors? Should minizip perhaps be pulled out into it's own package?

**Comment by lazka** [comment]
Can you report this to upstream minizip fork?

**Comment by Alexpux** [comment]
Do you have installed skin 1.2.11-3?

**Comment by ukhf-jm** [comment]
Apologies, I was on annual leave and didn't check my work email

> Can you report this to upstream minizip fork?

The change by the upstream fork was deliberate and included a number of changes to refactor. For some reason, the package doesn't write out the correct headers which begin with mz_*. It may be due to the minizip fork using cmake for building. I may look into this in more detail when I have a chance, sorry.

> Do you have installed zlib 1.2.11-3?
Yes, pacman is showing that I have 1.2.11-3 installed. This started I believe with the [commit](https://github.com/Alexpux/MINGW-packages/commit/d0076cc5d0acac8ff28ac8cd32dcd60d1ce32caf#diff-a41e814c7fecbe9982b106e5448bd1ac) updating PKGBUILD on 2018-07-19

Considering the large changes to minizip, that's why I was wondering if perhaps it would be best to strip out the minizip stuff and just build zlib on it's own and perhaps have minizip as a separate package or perhaps just stick with the one that comes with zlib. I don't have any strong feelings towards any particular solution and it's up to you guys really with regards to what would be best. Figure out the build for the minizip fork, stick with the original packaged minizip or split it off into a separate package.

**Comment by vszakats** [comment]
Maybe this past commit helps?: https://github.com/nmoinvaz/minizip/commit/ce26dba5bafae49e92d31bd1a0ef10e09bb763bb

The revision hosted by MSYS2 is a bit outdated. Just since April 2018, there has been at least two dozen fixes targeting the compatibility interface, so it may be worth to try the latest 2.5.0 release.

**Comment by ukhf-jm** [comment]
With the splitting of the packages, I feel like this particular issue is resolved. I have to rewrite my code but ultimately, it was third party code in the contrib folder and I shouldn't have relied on it. Thanks @Alexpux for sorting this out.
