### ISSUE TITLE
GDAL tries to load wrong json-c dll

### ISSUE THREAD

**Issue by alex85k** [Alexpux/MINGW-packages#4106]
Every executable built with gdal libraries fails to start (even with updated msys2 installation).
For example, this error is generated by gdalinfo.exe .
The messagebox says that libjson-c-3.dll is needed
![image](https://user-images.githubusercontent.com/4124648/43078567-50e82eb2-8ea4-11e8-9418-611375993e78.png)
while json-c is automatically installed as  libjson-c-4.dll . Renaming dll helps as a temporary workaround.

Seem that gdal package needs rebuilding with newer json-c?

**Comment by alex85k** [comment]
Original issue in project: https://github.com/osmcode/libosmium/issues/262

**Comment by Alexpux** [comment]
Fixed

**Comment by mlt** [comment]
Something is off with version comparison. Is it a naming /pacman issue?
```
:: Starting full system upgrade...
warning: mingw-w64-i686-json-c: local (0.13_20171207-2) is newer than mingw32 (0.13.1_20180305-1)
warning: mingw-w64-x86_64-json-c: local (0.13_20171207-2) is newer than mingw64 (0.13.1_20180305-1)
 there is nothing to do
```
