### ISSUE TITLE
Python3 jupiter notebook not building.

### ISSUE THREAD

**Issue by Alexpux** [Alexpux/MINGW-packages#4107]
When try to build package I see message:
````
==> Starting build()...
running build
running build_py
running jsversion
running js
running jsdeps
installing build dependencies with npm
> npm install
npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm notice created a lockfile as package-lock.json. You should commit this file.
added 69 packages in 27.097s
````

Then build just stop without any error

**Comment by peterbud** [comment]
I'll look into that

**Comment by peterbud** [comment]
Hi @Alexpux : jupyter-notebook cannot be built if logging is enabled - this is an issue with `npm`. You need to build _without_ logging.

I was able to build using
`makepkg -sCf`

Also in appveyor it is building properly, see this log:
https://ci.appveyor.com/project/peterbud/mingw-packages/build/1.0.262

Shortly I'm going to upgrade to 5.6.0, PR is on its way.

**Comment by Alexpux** [comment]
I think we need add to PKGBUILD header that package need to build without logging and then can close issue
