### ISSUE TITLE
curl broken?

### ISSUE THREAD

**Issue by tschoonj** [Alexpux/MINGW-packages#4111]
The very recently updated curl appears to be broken:

```
C:/msys64/mingw64/bin/curl.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

**Comment by Alexpux** [comment]
Run curl from CMD and see what library is missing

**Comment by tschoonj** [comment]
DependencyWalker says `libpsl-5.dll` is missing, a dependency of `libcurl-4.dll`

Just typing `curl` on the MSYS2 shell gives:

```
C:/msys64/mingw64/bin/curl.exe: error while loading shared libraries: libmetalink-3.dll: cannot open shared object file: No such file or directory
```

**Comment by ksherlock** [comment]
`mingw-w64-x86_64-cmake-3.12.0-1` and `mingw-w64-i686-cmake-3.12.0-1` are also broken without libpsl.

```
$ cmake --version
C:/unix/mingw64/bin/cmake.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

$ pacman -S mingw64/mingw-w64-x86_64-libpsl
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-libpsl-0.20.2-1

…

$ cmake --version
cmake version 3.12.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).

```

**Comment by Alexpux** [comment]
@tschoonj libmetalink is in dependencies.
@ksherlock yeah, will add libpsl to dependenices

**Comment by Optiligence** [comment]
cmake just depends on curl, so there’s that

**Comment by Optiligence** [comment]
rephrasing: 

`mingw-w64-x86_64-curl` seems to miss `mingw-w64-x86_64-libpsl` as dependency

`mingw-w64-x86_64-cmake` is just transitively broken
