### ISSUE TITLE
cmake broken due to missing dependency on libpsl

### ISSUE THREAD

**Issue by Rondom** [Alexpux/MINGW-packages#4114]
Cmake (both 32 and 64bit) fails due to missing dependency on libpsl. Installing `mingw-w64-{x86_64,i686}-libpsl` manually fixes this.

I will submit a pull request as well.

**Comment by Rondom** [comment]
Closing this issue as a duplicate of #4111

**Comment by mati865** [comment]
I think there is no PR for `curl`, you can fix it instead if you want.

**Comment by Rondom** [comment]
Last I have checked it is still @Alexpux who is the only one who can do uploads and he mentioned that he will do it, Thus, I am not sure if me submitting a PR will help in any way.

Maybe this has changed, though. I will go ahead and submit a PR.
