### ISSUE TITLE
cx_Freeze for python3.7 needs a patch - bytecode is unusable

### ISSUE THREAD

**Issue by totaam** [Alexpux/MINGW-packages#4150]
As it is, the installation directories it generates are unusable.
That's because the bytecode format has changed in Python 3.7

There is a patch to correct this problem (tested, working), you can find it in this pull request:
https://github.com/anthony-tuininga/cx_Freeze/pull/395

**Comment by Alexpux** [comment]
Fixed in https://github.com/Alexpux/MINGW-packages/commit/4c18633ba2331d980f00aff075f17135399c43c5
