### ISSUE TITLE
issue with new OpenCV failing to find itself + solution

### ISSUE THREAD

**Issue by Dmi3Dev** [Alexpux/MINGW-packages#4160]
Hi, I'm not creating PR for this, because it's my firs time finding an issue with MSYS2 and solution, so I'm not sure how you handle PR's and I'm short on time right now. 

Problem:
After setting up fresh Windows install I setup fresh MSYS2 with mingw64 and As I tested my project, I got CMake error with OpneCV unable to find itself. 

Solution:
fixed by adding: 
`  list(APPEND candidates "lib")`
to line 76 (before `  foreach(c ${candidates})`)
in file `C:\msys64\mingw64\share\OpenCV\OpenCVConfig.cmake`

otherwise it was trying to look for config in 
`C:/msys64/mingw64/share/OpenCV/x64/mingw/lib`
when it actuality it's located in
`C:/msys64/mingw64/share/OpenCV/lib`

Tested, project compiles and works fine after fix. I hope it helps. If you have rules for PR's, I'll look it up next time and do it proper way.

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/b13a692e80e1f9022dd963dc2820c460d9710699
