### ISSUE TITLE
clear, tabs, tput etc. fail to recognise $TERM in mingw shell

### ISSUE THREAD

**Issue by CounterPillow** [Alexpux/MINGW-packages#42]
`clear`, `tput` and `tabs` fail with `'xterm-256color': unknown terminal type.` when executed in the mingw64 shell, but work in the msys shell. This is probably because the mingw64 ncurses is built differently.

**Comment by elieux** [comment]
Since the utilities don't work at all in the Windows console AFAIK, they were renamed and no longer conflict with MSYS ncurses. Can we close this?
