### ISSUE TITLE
SDL2: WASAPI sound backend broken?

### ISSUE THREAD

**Issue by fabiangreffrath** [Alexpux/MINGW-packages#4223]
Hi there,

I am developing a Doom port called "Crispy Doom" and bundle each release with the necessary SDL*.dll files from MSYS2. Since the switch to SDL 2.0.6, when the WASAPI audio backend was made the default, user kept complaining regularly about distorted sounds, i.e. mostly too high-pitched. As it turns out, forcefully switching the SDL_AUDIODRIVER to "directsound" fixes these issues for some, i.e. those user from which you could expect to set an environment variable in Windows. Some others, though, report no issues with the WASAPI backend on Windows 10.

The "directsound" and "winmm" audio backends are still available in current SDL release as fallback solutions, but I'd rather have "directsound" be the default again, as it was up unti SDL 2.0.5, at least until the WASAPI backend works as reliably.

I see two possible solutions (for which I could provide a PR if needed): Either the WASAPI backend is disabled from our SDL2 build or the priority order of the backends is changed so that "directsounds" has preference over "WASAPI".

Is anyone actively and intentionally using the WASAPI backend, so he would suffer from either of these changes?

**Comment by lazka** [comment]
Can't you set the env var in code before SDL init?

**Comment by mati865** [comment]
It looks like something that should be reported upstream, as workaround this should work:
```
#if EE_CURRENT_PLATFORM == EE_PLATFORM_WINDOWS
   SDL_setenv("SDL_AUDIODRIVER", "directsound", true);
#endif
```
From [this](https://www.doomworld.com/forum/topic/97402-important-for-devs-sdl2-206s-audio-breakage-in-windows/?do=findComment&comment=1810769) post.

**Comment by fabiangreffrath** [comment]
> Can't you set the env var in code before SDL init?

Yes, of course, and I am on the way towards this. But this will only fix my specific case, the WASAPI backend will still remain broken for others.

> Other than that you should really file this upstream if you want the sounds issue to be fixed.

Sure. The point is, I don't have a reproducible use case. The sound issues seem to spread over different Windows versions, both 32 and 64 bit - the WASAPI backend is merely the common denominator. I suspect Windows driver issues on the individual computers, but I am no Windows expert and have no means to debug this.

Apart from this, I am sure upstream already knows that the WASAPI backend is still a bit cheesy. The entire 2.0.7 release was nothing more than a bug-fix for its first implementation. I wonder why they chose to make it the default backend that rashly after all.

**Comment by fabiangreffrath** [comment]
So, I understand that anything else than fixing the buggy WASAPI backend upstream at SDL must be considered a workaround. And since I don't feel like fixing the issue upstream, it should make no big difference if the workaround is applied on a package level (by disabling or degrading the faulty backend) or on an application level (by forcefully choosing a different backend). So, not much left to do for MSYS2 here.
