### ISSUE TITLE
static FFmpeg

### ISSUE THREAD

**Issue by msink** [Alexpux/MINGW-packages#4234]
I need FFmpeg as static libraries, but it disabled in PKGBUILD. Why?
https://github.com/Alexpux/MINGW-packages/blob/ecb37ea8bb97255ace2ed29721cc15bb7ecb5753/mingw-w64-ffmpeg/PKGBUILD#L66

**Comment by mingwandroid** [comment]
Because no one else needs it? Submit a PR if you care.
