### ISSUE TITLE
msmtp broken

### ISSUE THREAD

**Issue by MarcelRaad** [Alexpux/MINGW-packages#4259]
This used to work, but broke some weeks ago:
```
$ echo "Hello World" | mutt -s "Hello" address@domain.com
C:/msys64/mingw64/bin/msmtp.exe: error while loading shared libraries: libidn-11.dll: cannot open shared object file: No such file or directory
Error sending message, child exited 127 (Exec error.).
Could not send the message.
```
In C:\msys64\mingw64\bin, there is no libidn-11.dll, but libidn-12.dll. Reinstalling doesn't help. Does msmtp have to be rebuilt?

**Comment by Alexpux** [comment]
@MarcelRaad fixed by https://github.com/Alexpux/MINGW-packages/commit/dad74311f8dc662c2b74dc5128fc6743fc18e5d6

**Comment by MarcelRaad** [comment]
I just updated and can confirm it works. Thank you very much!

**Comment by MarcelRaad** [comment]
Oh no, actually I can't, now msmtp completely disappeared...
