### ISSUE TITLE
libjson-c: possible to package?

### ISSUE THREAD

**Issue by achadwick** [Alexpux/MINGW-packages#429]
Would it be possible to package lib[json-c](https://github.com/json-c/json-c) for MSYS2's MinGW? It's a GLib-free JSON engine written in C, and one of the dependencies for [MyPaint](https://github.com/mypaint/mypaint/) (in fact the only one which can't be satisfied from the msys2 repos right now!)

Configure/make/install is fairly simple: https://github.com/mypaint/mypaint/blob/master/README_WINDOWS.md#install-libjson-c

Arch Linux page for their packaging of it: https://www.archlinux.org/packages/extra/i686/json-c/

**Comment by mingwandroid** [comment]
Sure. Would it be possible for you to add the PKGBUILD though? We'd also like one for MyPaint, it looks great!

Pull requests are very welcome.

**Comment by achadwick** [comment]
I may give it a go. PKGBUILD is easy, right? (I'm used to Debian systems)

**Comment by achadwick** [comment]
BTW, if you could assign me, that'd be great.

(json-c looks easy; there are significant hurdles for MyPaint involving scons and python specificana. Check the README)

**Comment by mingwandroid** [comment]
PKGBUILD is easy yeah, a few (bash) shell script functions that you need to fill out. You can usually start from ArchLinux's. You should check some of the changes needed for MinGW-w64 PKGBUILDs by browsing a few in this repo, maybe do a git log to see some of the most recent ones.

I'm not sure about what you say regarding SCons in the README. I haven't touched SCons for a number of years, but I do remember it having the concept of 'tools' and setting them to 'mingw' was possible. MSYS2 itself only really exists to provide tools to 'cross' compile native Windows software, so in that regard, SCons is just like Autotools (or gnumake) and we have no problem building both native and MSYS2 software using Autotools (and gnumake).

Looking at MyPaint I'm guessing that it being written in Python may cause SCons to target the Python that it itself is running under. Is this the case? Can you 'cross-build' MyPaint with SCons in any way at present?

Seems I can only assign this issue to people with commit rights.

**Comment by mingwandroid** [comment]
Also, regarding the README, I'm not aware of numpy having significant problems in MSYS2's 64-bit MinGW-w64, only some IEEE rounding mode differences between threads that shouldn't cause *many* real world problems (not that this shouldn't be fixed though).

**Comment by achadwick** [comment]
@mingwandroid
There is a warning about NumPy's W64 support at runtime, which may just reflect Python's abjuring of non-MS compilers for MS platforms. It may amount to nothing for our rather simple purposes though. I'll give it a go if I get a moment.

The real killer for us is GDK hardware support. I've not managed to get pressure passing through to it from a VM with proper Wacom drivers and correct USB pass-through. Could that improve with 64-bit everything maybe?

(Anyway, enough about MyPaint for now. Better concentrate on fixing up json-c.)
