### ISSUE TITLE
Qt tools fail to run due to icu package

### ISSUE THREAD

**Issue by droidmonkey** [Alexpux/MINGW-packages#4290]
Updating the icu package to version ```mingw-w64-x86_64-icu-62.1-1``` causes all Qt tools to fail to run. For example, try running ```uic``` and it will fail to load Qt5Core.dll. After running ```strace uic``` it identified the libicuuc61.dll as the culprit.

Downgrading back to ```mingw-w64-x86_64-icu-61.1-1``` resolves the issue.

**Comment by Optiligence** [comment]
i suggest to put major version dependencies in i,e. Qt and Boost packages

**Comment by droidmonkey** [comment]
Also, after downgrading the icu package, my program compiles but crashes immediately on startup. GDB reports static variable initialization error. This did not happen before MSYS2 update and does not happen in Ubuntu.

**Comment by Alexpux** [comment]
This is because not only Qt depends on ICU but other packages like harfbuzz too. So you need downgrade all packages that depends on ICU. In near time I will not upload new Qt package as there are problems with building it

**Comment by droidmonkey** [comment]
The current state of MSYS2 is terribly broken as a result of this.

**Comment by Optiligence** [comment]
@Alexpux downgrade the repo then, please. it not only breaks work environments which can be manually fixed, but also continous integration

**Comment by Alexpux** [comment]
Instead ignoring the problems need to solve them. I’m only one who build and upload and can’t solve all problems in short time. Build packages take much time so wait while it will be fixed or downgrade packages manually

**Comment by Optiligence** [comment]
well icu shouldn’t be updated in the repo if dependents are not ready. 
CIs are difficult to manually downgrade
Ignoring it now would prevent a lot more people from getting broken environments without requiring much effort.

**Comment by Alexpux** [comment]
As workaround you can try to copy ICU 62 dlls and rename them to 61

**Comment by Optiligence** [comment]
My fingernails curl when i think about this. 

I’m just proposing to revert the change that broke the repo until it’s in a complete state. 
it’s even possible to easily sync that for users with `pacman -Syuu`

**Comment by Diapolo** [comment]
Are you using GCC hardening features like stack protector?

**Comment by droidmonkey** [comment]
@Diapolo were you asking me? If so, yes we are using hardening features, building KeePassXC Password Manager Tool.

**Comment by mati865** [comment]
@Diapolo it's different issue, Qt expects older soname of the library.

**Comment by droidmonkey** [comment]
OK, so in case anyone else is plagued by this, here is what I did to backout my MSYS2 to a certain date:

1. Navigate to your ```/var/cache/pacman/pkg``` directory and sort by last modified
2. Pick a date to revert back to and select all the packages from NOW to that date. Press and hold SHIFT and right click then select "copy path".
3. Paste into your favorite text editor and do some find/replace to chop the list down to a long, space-separated string of package names (see below for this particular issue resolution).
4. DELETE the packages you selected from the cache folder (important for step 6).
5. Download "downgrade.sh" from my gist and place in bin directory: https://gist.github.com/droidmonkey/144cee8aa1e1b797d442c5e398fa4485
6. Run ```downgrade.sh <package_list> -o 1``` to revert back to the last known package of the names extracted before. The -o 1 uses the first available package which would be the last good one since you deleted the old bad packages already in step 4.

<details><summary>Package List from Aug 22 to July 8</summary>
mingw-w64-i686-openssl mingw-w64-x86_64-openssl mingw-w64-i686-glib2 mingw-w64-x86_64-glib2 mingw-w64-i686-harfbuzz mingw-w64-x86_64-harfbuzz mingw-w64-i686-dbus mingw-w64-x86_64-dbus mingw-w64-i686-expat mingw-w64-x86_64-expat mingw-w64-i686-icu-debug-libs mingw-w64-i686-icu mingw-w64-x86_64-icu-debug-libs mingw-w64-x86_64-icu mingw-w64-x86_64-python3-pip mingw-w64-x86_64-python2-pip mingw-w64-i686-libtiff mingw-w64-x86_64-libtiff mingw-w64-i686-p11-kit mingw-w64-x86_64-p11-kit mingw-w64-i686-libgsf mingw-w64-x86_64-libgsf mingw-w64-x86_64-python3-setuptools mingw-w64-x86_64-python2-setuptools mingw-w64-i686-graphite2 mingw-w64-x86_64-graphite2 ttyrec mintty mingw-w64-i686-libjpeg-turbo mingw-w64-x86_64-libjpeg-turbo mingw-w64-i686-gdb mingw-w64-x86_64-gdb pacman libcurl curl mingw-w64-x86_64-gcc-objc mingw-w64-x86_64-gcc-ada mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-gcc-libgfortran mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-gcc mingw-w64-i686-curl mingw-w64-x86_64-curl liblzo2 autoconf libffi libcrypt time rebase gcc-libs less libgnutls libopenssl openssl perl-URI perl-libwww file perl-Net-HTTP perl-IO-Socket-SSL perl-HTTP-Message perl-Error mingw-w64-i686-libpng mingw-w64-x86_64-libpng mingw-w64-i686-zlib mingw-w64-x86_64-zlib mingw-w64-i686-cmake mingw-w64-x86_64-cmake mingw-w64-i686-binutils mingw-w64-x86_64-binutils mingw-w64-x86_64-libmangle-git mingw-w64-i686-libgpg-error mingw-w64-x86_64-libgpg-error mingw-w64-x86_64-winstorecompat-git mingw-w64-x86_64-tools-git mingw-w64-i686-libwinpthread-git mingw-w64-i686-winpthreads-git mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-libmicrohttpd mingw-w64-i686-libuv mingw-w64-x86_64-libuv mingw-w64-i686-llvm mingw-w64-i686-clang mingw-w64-x86_64-llvm mingw-w64-x86_64-clang gnupg libgpg-error libltdl libtool mingw-w64-i686-openal mingw-w64-x86_64-openal mingw-w64-i686-python3 mingw-w64-x86_64-python3 mingw-w64-i686-crt-git mingw-w64-x86_64-crt-git mingw-w64-i686-headers-git mingw-w64-x86_64-headers-git mingw-w64-i686-jsoncpp mingw-w64-x86_64-jsoncpp libnpth filesystem sed info 
</details>

**Comment by Optiligence** [comment]
@Alexpux if you don’t want to downgrade the repo, can you upload a downgraded database file here?

**Comment by Alexpux** [comment]
@Optiligence I dont have old database files

**Comment by dfileccia** [comment]
Thank you @awhatson for you script. I was able to downgrade and now I can build!

Thank you @Alexpux for all your work on MSYS2! It takes a lot of effort to do this and it is much appreciated. I would much rather have the small headache I just had than have to build Qt and MSYS2 just to keep away from M$ on Windows.

**Comment by Optiligence** [comment]
[zipped db file](https://github.com/Alexpux/MINGW-packages/files/2319159/mingw64.zip) with boost and icu downgraded
extract into `/var/lib/pacman/sync/` and remove /var/lib/pacman/sync/mingw64.db.sig`

**Comment by Alexpux** [comment]
64-bit Qt5 packages uploaded. 32-bit will be later when build done

**Comment by omichel** [comment]
Qt5WebKit.dll is still linked with ICU61, so it is still broken...

**Comment by Alexpux** [comment]
@omichel qtwebkit not buildable now. gcc 8.2.0 crash on it

**Comment by droidmonkey** [comment]
The new version of gcc is causing me a ton of heartache as well... it absolutely hates static variables.

**Comment by Alexpux** [comment]
Im upload 64bit QtWebkit linked to ICU 62, 32bit some later

**Comment by omichel** [comment]
I just tested the 64 bit version and can confirm it now works great with ICU 62. Thank you!
