### ISSUE TITLE
pango - custom font paths registered with fontconfig are ignored - defaults to ugly

### ISSUE THREAD

**Issue by iongion** [Alexpux/MINGW-packages#4293]
I am using fontconfig to register a font from a custom path (not system path)

```C
  const char *fontPath = "Saira.ttf";
  FcBool fontAddStatus = FcConfigAppFontAddFile(FcConfigGetCurrent(), fontPath);
  if (fontAddStatus) {
    fprintf(stdout, "  - allocated font-config font from `%s`\n", fontPath);
  } else {
    fprintf(stderr, "  - [ERROR] could not load font from file `%s`\n", fontPath);
    error = 1;
  }

  const char *fontDescription = "Saira 17";
  fprintf(stdout, "  - text with pango descriptor `%s`\n", fontDescription);
  PangoFontDescription *desc = pango_font_description_from_string(fontDescription);
  PangoLayout *layout = pango_cairo_create_layout(cr);
  pango_layout_set_text(layout, text, -1);
  pango_font_description_set_size(desc, fontSize * PANGO_SCALE * TWEAKABLE_SCALE);
  pango_layout_set_font_description(layout, desc);
  pango_font_description_free(desc);
  cairo_move_to(cr, x, y);
  pango_cairo_update_layout(cr, layout);
  cairo_set_source_rgba(
    cr,
    r,
    g,
    b,
    alpha);
  pango_cairo_show_layout(cr, layout);
  g_object_unref(layout);

```

On Ubuntu 16.04 I am compiling and running it and all is rendering properly, but on windows, the same code ouputs these pango warnings:

```
 Pango-WARNING **: 17:29:45.159: couldn't load font "Saira Not-Rotated 16.7998046875", falling back to "Sans Not-Rotated 16.7998046875", expect ugly output.
```

It is as if the msys pango cannot be aware of fontconfig declared fonts, why is that ?
Can it be fixed or overcome ?

**Comment by Alexpux** [comment]
Maybe this is because Windows dont have installed this font?

**Comment by iongion** [comment]
@Alexpux Yes, you are right windows does not have it installed, but on Linux it works differently, even if it is not installed in system fonts, this line is respected:

```
  const char *fontPath = "Saira.ttf";
  FcBool fontAddStatus = FcConfigAppFontAddFile(FcConfigGetCurrent(), fontPath);
  if (fontAddStatus) {
    fprintf(stdout, "  - allocated font-config font from `%s`\n", fontPath);
  } else {
    fprintf(stderr, "  - [ERROR] could not load font from file `%s`\n", fontPath);
    error = 1;
  }
```

So pangocairo is respecting the fontconfig font added above that was changed programmatically, while on msys, it does not respect the programatically changed fontconfig.

**Comment by iongion** [comment]
I have added the example code with the font, **it should work even if font is not installed in OS system fonts**.

[example.zip](https://github.com/Alexpux/MINGW-packages/files/2317630/example.zip)

You can compile it with

    gcc pango-test.c $(pkg-config --cflags --libs pangocairo fontconfig) -o pango-test

**Comment by Alexpux** [comment]
@iongion I think need ask gnome devs. I\m not familar with pango

**Comment by piense** [comment]
Any progress on this? I'm running into the same thing. pango_font_map_list_families() shows my loaded font but pango_font_description_from_string() fails to find it.

**Comment by piense** [comment]
Figured it out in my case and I'll explain for anyone else googling around and I can see why @iongion is having trouble. Basically creating a layout uses the Win32 backend - which isn't normally an option on other OSes so it's not obvious. To fix that and use the fontconfig back end, grab the context from the layout with pango_layout_get_context, then set it to a new font map created with something like pango_ft2_font_map_new to use the fontconfig backend, then issue pango_layout_context_changed on the layout. In theory there's a way to use pango_cairo_font_map_set_default but I haven't figured that out.

**Comment by iongion** [comment]
@piense Excelent work, I got stuck and quit supporting Windows due to this, but now I can bring it back!
Thank you!

**Comment by laurenthenrie** [comment]
Hi Hi 

I got stuck in the same issue you were running in december 2018 about not been able to load a custom font   in windows 

You seem to have solve this using the tip from @piense .

Would you mind to share the full content of the solution based on your pango-test.c exemple ?

I would really appreciate .
