### ISSUE TITLE
Could someone please rebuild qt5 with new icu

### ISSUE THREAD

**Issue by JPeterMugaas** [Alexpux/MINGW-packages#4299]
I can not build qt5 because I don't have mingw-w64-i686-firebird2-git and it conflicts with mingw-w64-i686-unixodbc.  The problem is that icu broke some things including qt5.  

This is making it nearly impossible to build cmake 3.12.1.  TIA.

**Comment by Alexpux** [comment]
@JPeterMugaas only I'm uploading and build packages that is on official repo. So be patient. If it not rebuilded yet then there are reasons for it.
