### ISSUE TITLE
ag does nothing

### ISSUE THREAD

**Issue by oscarfv** [Alexpux/MINGW-packages#431]
`ag foo` just hangs, doing nothing.

**Comment by Alexpux** [comment]
Try, for example:
ag foo c:/msys64

**Comment by oscarfv** [comment]
Your example works, but as per the man page (and my experience with `ag` on Linux confirms that) the path is optional, so `ag foo` is equivalent to `ag foo .`

**Comment by Alexpux** [comment]
Ok, I will leave this issue for anyone who want to fix it)
I have no time for it

**Comment by elieux** [comment]
The problem is that ag thinks you want it to search the input stream. The goal is to behave correctly in commands like `ls * | ag foo` (search input stream) and `ag foo` (search current directory). Unfortunately, when running inside MinTTY, programs can't easily distinguish between these two cases.

I've isolated the detection code, but I'm not sure what to do to fix it. See https://github.com/ggreer/the_silver_searcher/blob/master/src/options.c#L303-308

**Comment by elieux** [comment]
There's probably not a good solution for you at the moment. Running ag in [winpty](https://github.com/rprichard/winpty) solves the hang, but breaks colors (unless you use [http://adoxa.altervista.org/ansicon/](ansicon) or similar). Fortunately, [ag will gain native coloring support in its next release](https://github.com/ggreer/the_silver_searcher/compare/0.29.1...master), so we'll be able to wrap it in winpty by default.

(For future reference, current master is ggreer/the_silver_searcher@85f7bf69f42dc6c19ea81f0de024548bc2ab1bd2.)

**Comment by Alexpux** [comment]
Fixed.

**Comment by orlp** [comment]
It seems that this issue has once again surfaced. `ag foo` hangs, `ag foo .` runs fine.

**Comment by mingwandroid** [comment]
Well, it was never fixed as such. If someone wants to take a go at fixing it, Git for Windows have a patch in git itself that implements a better `isatty()` function. AFAIR it checks the name of the pipes connected to the standard io handles and if they are cygwin-y/msys2-y then it considers `isatty()` to be true.

We need a very similar function for `ag` and also for `npm`, and probably anywhere where `winpty` is used to work around these problems.

**Comment by orlp** [comment]
@mingwandroid Do you mean this commit?

https://github.com/git-for-windows/git/commit/de0d35dbabf220e47d50e5af7e7c5e9cbe977a13

Because that seems to rely on `MSYS_TTY_HANDLES`, which appears to be gone.

**Comment by mingwandroid** [comment]
I don't think that it is gone so much as was never pushed upstream by the g4w team though I am not sure on that point!

**Comment by orlp** [comment]
@mingwandroid I was under the impression that `MSYS_TTY_HANDLES` was a MSYS2 feature that has disappeared, rather than a git 4 windows feature.

**Comment by orlp** [comment]
@mingwandroid I was under the impression that `MSYS_TTY_HANDLES` was an MSYS2 feature, not a g4w feature.

**Comment by mati865** [comment]
@orlp https://github.com/git-for-windows/msys2-runtime/pull/4
