### ISSUE TITLE
imagemagick tries to use _s_open from msvcrt.dll

### ISSUE THREAD

**Issue by oscarfv** [Alexpux/MINGW-packages#432]
`_sopen_s` does not exists on `msvcrt.dll` version `7.0.2600.5512`, which the one installed on Windows XP SP 3.

The dependency is on `msys32\mingw32\bin\LIBMAGICKCORE-6.Q16HDRI-2.DLL`.

This happens on `mingw-w64-i686-imagemagick-6.9.0.4-1-any.pkg.tar.xz`. Previously I was using `mingw-w64-i686-imagemagick-6.9.0.0-1-any.pkg.tar.xz`, which works fine.

The problem was discovered because `emacs-git` refused to start. `emacs-git` depends on `imagemagick`.

**Comment by Alexpux** [comment]
This is cause by recent mingw-w64 commit by adding "mkstemp" implementation.
https://github.com/Alexpux/mingw-w64/commit/f713f639f6f017371c5176f4deab07d1a92473b4#diff-cc1bd3d845f9a0ff2d38778e12b84a17R52

So please report it to mingw-w64 ML

**Comment by oscarfv** [comment]
I see you already mentioned it on their mailing list. I'll create a bug report on their tracker if there is no response on the next few days.

Thanks.

**Comment by oscarfv** [comment]
A fix was pushed to mingw-w64:

https://sourceforge.net/p/mingw-w64/mingw-w64/ci/efc07ae1f91561e0be21ed108ac33a3511dfd548/

**Comment by Alexpux** [comment]
ok wii build in a day

**Comment by Alexpux** [comment]
Fixed in latest packages.
