### ISSUE TITLE
Here is an update for GTK+/gtkmm developers

### ISSUE THREAD

**Issue by Brute2** [Alexpux/MINGW-packages#433]
Hello, I'm developing with gtkmm libraries on windows machine, and there is an problem with gtkmm builds for windows... (installed with pacman in MSYS2)

when you download gtkmm package with pacman, the package(and it's dependencies) will not install icons and this will cause horribly slow application start up, also std out will show a lot of assertion failures due to missing icons and the application will be slow in general....

I was browsing around internet and saw that all windows developers that use gtkmm (or GTK+) have this problem and it looks nobody has a good solution.

So here are the steps (for 64 bit builds) that "should" to be included into this repository for those who want their GTK+/gtkmm packages/applications to fully work:

> pacman -S mingw-w64-x86_64-icon-naming-utils
> pacman -S mingw-w64-x86_64-gnome-icon-theme-symbolic
> pacman -S mingw-w64-x86_64-hicolor-icon-theme
> cd /mingw64/share/icons/gnome
> gtk-update-icon-cache ./
> cd ../hico*
> gtk-update-icon-cache ./

after I performed these steps all the problem have gone!

Thank you Alexey and others for all of the work you have done!

**Comment by Alexpux** [comment]
Maybe add  icon* packages as dependencies for  gtk?

**Comment by Brute2** [comment]
Yes, I this think this an absolute must because it affects all Windows (and probably non-gnome desktop) developers..
or at least letting people know to solve the problem.

**Comment by Brute2** [comment]
I forgot to mention that **gtk-update-icon-cache** can fail, (according to other people that complained about this issue), because version of grep package installed by pacman is out of date.

The solution that worked for me was to manually install an updated grep installment package for Windows from GNU download site: http://gnuwin32.sourceforge.net/packages/grep.htm

After installation I put the new version of grep into PATH before everything to make sure that new version is used instead.

**Comment by Alexpux** [comment]
We use MSYS2 version of grep. If anyone port grep to Mingw it will be good.

**Comment by Brute2** [comment]
Of course, I'm not criticizing MSYS2, just telling what solution worked for me..

indeed without MSYS2 project having most recent gtkmm builds would be impossible.
so again Thank you zillion times!

**Comment by mingwandroid** [comment]
gtk-update-icon-cache uses grep? Not a wonder it takes ages, can't it be written to not do that?

**Comment by BrisingrAerowing** [comment]
@Alexpux Grep builds fine on MinGW without any kind of code changes. I have done it before. I know very little about bash scripting, so I can't be of much help with a PKGBUILD. It needs PCRE and Gettext (and possibly others I am forgetting about).

**Comment by elieux** [comment]
@Brute2, is this solved? Note there's a dependency gtk -> adwaita-icon-theme.

**Comment by lazka** [comment]
* gtk3 depends on adwaita-icon-theme
* the symbolic icon theme no longer exists and is part of adwaita-icon-theme
* gtk-update-icon-cache is written in C and does not use grep

I think this can be closed.
