### ISSUE TITLE
.pc file for glib2.0 and gio contain wrong info

### ISSUE THREAD

**Issue by wuhanck** [Alexpux/MINGW-packages#4364]
glib-2.0.pc contains -lgnulib, which doesn't exist in mingw64 env.
gio-2.0.pc contains -lgiowin32, which donesn't exist in mingw64 env.

Maybe we need check pkg-config files?

**Comment by lazka** [comment]
Thanks, I'll have a look.

**Comment by lazka** [comment]
OK, it's in Libs.private, so only affecting static builds I guess.

**Comment by LigH-de** [comment]
Yes, it does, e.g. building static FFmpeg including liblensfun.

**Comment by lazka** [comment]
Opened a PR: #4373 and filed upstream: https://gitlab.gnome.org/GNOME/glib/issues/1516
