### ISSUE TITLE
Qt4 and Qt5

### ISSUE THREAD

**Issue by u8sand** [Alexpux/MINGW-packages#439]
Might it be possible to make a way for both Qt4 and Qt5 to be available simultaneously? Currently they conflict with one another. Many linux distros manage to get them both as many apps depend on one or the other.

I'm working on two different projects one being Qt4 and the other being Qt5; switching each time is ridiculous.

**Comment by mingwandroid** [comment]
Sure, implement it on the qt4 PKGBUILD as arch Linux does.

Or install two distinct msys2 installations.

**Comment by lazka** [comment]
Any news here? I assume with qt4 being eol for a long time now we can close this.

**Comment by u8sand** [comment]
Yeah, if no one else needs this, I no longer do.
