### ISSUE TITLE
GCC internal compiler error

### ISSUE THREAD

**Issue by hunbernd** [Alexpux/MINGW-packages#4409]
I get the following build error when using 64 bit GCC 8.2.0.
`internal compiler error: in based_loc_descr, at dwarf2out.c:14272`
`libbacktrace could not find executable to open`

 Using 32 bit GCC 7.3.0 the same codes compiles well.

It seems like that there is already a patch:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86593

Please provide an updated version of GCC for mingw64.

**Comment by Alexpux** [comment]
New 64 bit GCC 8 uploaded

**Comment by cfis** [comment]
I am still seeing this error when building ruby 2.5.3 from source. I believe I am using the latest version of gcc available, see below.

-------------------

 gcc -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-8.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=ada,c,lto,c++,objc,obj-c++,fortran --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev3, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 8.2.0 (Rev3, Built by MSYS2 project)

**Comment by mati865** [comment]
It's said to be fixed in GCC 9 and backporting https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=264096 should fix it for GCC 8.

**Comment by cfis** [comment]
Its not a minimal test case, but:

* Download ruby 2.5.3 - https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.3.tar.bz2

* Configure (your paths my vary):
$ ./configure --prefix=/ CPPFLAGS=-I/mingw64/include LDFLAGS=-L/ming64/lib --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32

$ make

And you'll see the error in about 5 seconds.

**Comment by mingwandroid** [comment]
You're right that's not minimal. Please use creduce as I recommended.

**Comment by crlf0710** [comment]
Still seeing this problem. Proceeding by removing "-fno-emit-frame-pointer" as a work around.

**Comment by hunbernd** [comment]
I managed to backport the patch: https://github.com/msys2/MINGW-packages/pull/5261

Minimal test case:
`g++ test.c -o test.o -O -g -fno-omit-frame-pointer`

test.c:
```
struct Foo
{
    int bar(int a, int b, int c, int i1, int i2, int i3, int d);
};

int Foo::bar(int a, int b, int c, int i1, int i2, int i3, int d)
{
  return 0;
}
```
