### ISSUE TITLE
[Qt5<module>Config.cmake] INTERFACE_LINK_LIBRARIES is wrongly populated for Qt5::Core

### ISSUE THREAD

**Issue by cyrilBoucher** [Alexpux/MINGW-packages#4455]
It seems this patch:
https://github.com/Alexpux/MINGW-packages/blob/0c81c77a16ee379e29837dc23a5dcdf62b300f7d/mingw-w64-qt5/0042-qt-5.4.0-static-cmake-also-link-plugins-and-plugin-deps.patch#L11

Broke the transitive dependency of Qt5 modules along with populating ```Qt5::Core``` with a lot of unecessary things.

First of all, it seems ```Qt5::Core``` is wrongly populated every single time, ```Qt5::$${CMAKE_MODULE_NAME}``` is used throughout the config files but the newly added line  ```set_property(TARGET Qt5::Core APPEND PROPERTY...``` uses a hard coded ```Qt5::Core``` which happens to break the dependency transitivity between Qt5 module libraries, that is, for example, ```Qt5::Gui``` does not have ```Qt5::Core``` in its ```INTERFACE_LINK_LIBRARIES property```. The line should be ```set_property(TARGET Qt5::$${CMAKE_MODULE_NAME} APPEND PROPERTY```

Lastly,
```
if (_Qt5$${CMAKE_MODULE_NAME}_LIB_DEPENDENCIES)
    set(_list_sep \";\")
endif()
```

These lines should be checking if ```_Qt5$${CMAKE_MODULE_NAME}_LIB_DEPENDENCIES)``` contains more than one library otherwise we append **;** with nothing behind it resulting in **>** being interpreted as an actual item in the list of libraries

Here is an example of what we can find in the INTERFACE_LINK_LIBRARIES from ```Qt5::Core``` as a result of this patch:
```$<$<CONFIG:RELEASE>:>;$<$<CONFIG:DEBUG>:>;$<$<AND:$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>,$<BOOL:$<TARGET_PROPERTY:WIN32_EXECUTABLE>>,$<NOT:$<BOOL:$<TARGET_PROPERTY:Qt5_NO_LINK_QTMAIN>>>,$<TARGET_POLICY:CMP0020>>:Qt5::WinMain>;$<$<CONFIG:RELEASE>:Qt5::Core;>;$<$<CONFIG:DEBUG>:Qt5::Core;>;$<$<CONFIG:RELEASE>:Qt5::Core;>;$<$<CONFIG:DEBUG>:Qt5::Core;>;$<$<CONFIG:RELEASE>:Qt5::Gui;Qt5::Core;>;$<$<CONFIG:DEBUG>:Qt5::Gui;Qt5::Core;>;$<$<CONFIG:RELEASE>:Qt5::Core;>;$<$<CONFIG:DEBUG>:Qt5::Core;>;$<$<CONFIG:RELEASE>:Qt5::Core;>;$<$<CONFIG:DEBUG>:Qt5::Core;>;$<$<CONFIG:RELEASE>:Qt5::Core;>;$<$<CONFIG:DEBUG>:Qt5::Core;>```

**Comment by mingwandroid** [comment]
Please make a PR.

**Comment by cyrilBoucher** [comment]
I unfortunately do not have the bandwidth to investigate what has been done and propose a clean way to fix this (The patch changes much more than what I talked about in my issue). In the end we went back to using files shipped with Qt with no patches.

Feel free to close this issue or leave it open if someone wants to take the lead.

**Comment by Optiligence** [comment]
@cyrilBoucher Was the `;` a problem for you anywhere? Using i.e. `foreach` on the property doesn’t work even if there are several elements in the list because it can’t handle the generator expressions. Using it to link works just fine.
