### ISSUE TITLE
python pip broken because ssl module in Python is not available.

### ISSUE THREAD

**Issue by xiaowen64** [Alexpux/MINGW-packages#4470]
python3.exe -m pip install --upgrade pip
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
...
Requirement already up-to-date: pip in c:/msys64/mingw64/lib/python3.7/site-packages (18.0)
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.

**Comment by lazka** [comment]
new package is out, so updating your install should fix it.
