### ISSUE TITLE
Please update gcc to 8.2.1 since 8.2.0 contains a confirmed bug

### ISSUE THREAD

**Issue by metorm** [Alexpux/MINGW-packages#4477]
The bug is reported at [this page](https://www.mail-archive.com/gcc-bugs@gcc.gnu.org/msg581872.html).

It prevents anyone from compiling the following code:

```
#include <variant>

int main(int, char**) {
    std::variant<std::monostate> v1, v2;
    std::swap(v1, v2);
}
```
 gcc 8.2.1 works well with the above code.

**Comment by Alexpux** [comment]
@metorm gcc 8.2.1 not released so i cant update

**Comment by metorm** [comment]
Sorry, so I have to wait ...

**Comment by Alexpux** [comment]
@metorm you can backport patch for 8.2.0 and create PR

**Comment by metorm** [comment]
I can try it. Is there any guideline about making PRs?

**Comment by Alexpux** [comment]
@metorm clone our repo, prepare patch for GCC and integrate it into GCC PKGBUILD. Build gcc yourself and see if all is ok, then send pull request

**Comment by metorm** [comment]
Yeah, I know about the basic flow.

I now confirm replacing a header file with the one copied from the 8.2.1 release solved the problem.
So, I am gonna to add a `*.patch` file called `0019-gcc-8.2.0-Backport-patches-for-std-variant-_M_destructive_move.patch` to replace the file with the newer version, then change the `pkgrel=2` to `pkgrel=3` in PKGBUILD, and then commit and create a PR. IS that OK? Is there any additional test procedure?

**Comment by mingwandroid** [comment]
> Is there any additional test procedure?

You need to build the recipe yourself and ensure it works before making the PR.
