### ISSUE TITLE
unable to build gcc 8.2.0 myself on a 32-bit machine

### ISSUE THREAD

**Issue by shhccie** [Alexpux/MINGW-packages#4486]
Because there is no update of 32-bit gcc 8.2.0 on the web, I try to build it myself following the instruction on the home page. After a failure of gpg verifying the singnature of the gcc source, the build process then ended.

What's wrong with it? How can I fix it? Thanks!

**Comment by shhccie** [comment]
That works. Thank you very much for quick reply!

**Comment by shhccie** [comment]
Sorry, building GCC 8.2.0 for 32 bit with '--enable-languages=c,lto,c++,fortran' still crash by an 'Fatal Error: Reading module 'openacc_kinds' at line 4 column 1: Unexpected EOF':

[from the build log]
...
f951.exe: Fatal Error: Reading module 'openacc_kinds' at line 4 column 1: Unexpected EOF
compilation terminated.
make[5]: *** [Makefile:686：openacc.lo] 错误 1
make[5]: *** 正在等待未完成的任务....
mv -f .deps/priority_queue.Tpo .deps/priority_queue.Plo
checking for stdlib.h... make[5]: 离开目录“/temp/mingw/mingw-w64-gcc/src/build-i686-w64-mingw32/i686-w64-mingw32/libgomp”
make[4]: *** [Makefile:904：all-recursive] 错误 1
make[4]: 离开目录“/temp/mingw/mingw-w64-gcc/src/build-i686-w64-mingw32/i686-w64-mingw32/libgomp”
make[3]: *** [Makefile:493：all] 错误 2
make[3]: 离开目录“/temp/mingw/mingw-w64-gcc/src/build-i686-w64-mingw32/i686-w64-mingw32/libgomp”
make[2]: *** [Makefile:20723：all-stage2-target-libgomp] 错误 2
make[2]: *** 正在等待未完成的任务....

...

make[3]: Leaving directory '/temp/mingw/mingw-w64-gcc/src/build-i686-w64-mingw32/i686-w64-mingw32/libstdc++-v3/include'
make[2]: 离开目录“/temp/mingw/mingw-w64-gcc/src/build-i686-w64-mingw32”
make[1]: *** [Makefile:22205：stage2-bubble] 错误 2
make[1]: 离开目录“/temp/mingw/mingw-w64-gcc/src/build-i686-w64-mingw32”
make: *** [Makefile:949：all] 错误 2
...

**Comment by shhccie** [comment]
I downloaded the most recent scripts and edited the PKGBUILD dropping building support for the languages Ada, Objc, and Obj-c++, then I used this command to build:

MINGW_INSTALLS=mingw32 makepkg-mingw --skippgpcheck -sLf

Thanks!

**Comment by Alexpux** [comment]
@shhccie as I told you already we dont provide GCC 8 for 32 bit as it not buildable. Report problem to GCC devs

**Comment by shhccie** [comment]
@oscarfv Thank you for reply! Could you please post the PKBUILD here. I'm an ordinary user of Github and can't use gist for now. I can't open the link. Thank you very much.

**Comment by oscarfv** [comment]
Weird, the link works fine from here. Github does not allow to upload an arbitrary file as a comment and fails when I try to upload as .txt.

[Try this link to the raw contents](https://gist.githubusercontent.com/oscarfv/eacd4f2ae9da653ffd5437013ca5976b/raw/fd9ebaff1a6e36d5cdc26d2c19d858358e0490a9/PKGBUILD.patch)

**Comment by oscarfv** [comment]
By the way, throwing exceptions crashes the application. If you plan to use this for serious C++ work, more work is required.

**Comment by shhccie** [comment]
Yes, I see the patch now. Thank you very much.

It's not weird. That may be a restriction Github puts on free users.
