### ISSUE TITLE
Automoc fails on MSYS2/Qt5

### ISSUE THREAD

**Issue by dmikushin** [Alexpux/MINGW-packages#4508]
Dear all,

I came across an error from Automoc below, which gives no clue about the cause of failure (Output is empty). The mechanics of Automoc in CMake is not clear. Looks like "cmake_autogen" only launches a command described in variables. But where the command return value is checked? What places should I look at to debug cmake_autogen/automoc in CMake?

Thanks & Kind regards,
- Dmitry Mikushin.

```
$ make
[  0%] Automatic MOC for target glazomer
Start

AutoMoc subprocess error
------------------------
The content generation command for "moc_predefs.h" failed.

Command
-------
/mingw64/bin/x86_64-w64-mingw32-g++.exe -dM -E -c /usr/share/cmake-3.12.2/Modules/CMakeCXXCompilerABI.cpp -I/c/Users/dmikushin/glazomer/glazomer/build/glazomer_autogen/include -I/mingw64/include/QtDBus -I/mingw64/include/QtNetwork -I/mingw64/include/QtTest -I/mingw64/include/qwt -I/mingw64/include/libusb-1.0 -I/c/Users/dmikushin/glazomer/glazomer/ThirdParty/eigen -I/c/Users/dmikushin/glazomer/glazomer/src -I/mingw64/include -I/mingw64/include/QtCore -I/mingw64/share/qt5/mkspecs/win32-g++ -I/mingw64/include/QtGui -I/mingw64/include/QtWidgets -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB

Output
------

make[2]: *** [CMakeFiles/glazomer_autogen.dir/build.make:58: CMakeFiles/glazomer_autogen] Error 1
make[1]: *** [CMakeFiles/Makefile2:180: CMakeFiles/glazomer_autogen.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

**Comment by mingwandroid** [comment]
`-c /usr/share/cmake-3.12.2`

it seems you are using the MSYS2/cmake program here, which should only be used for compiling msys2 dll linked software. Instead of installing `cmake` you should install `mingw-w64-x86_64-cmake` or `mingw-w64-i686-cmake`  instead.

**Comment by dmikushin** [comment]
This **is** an awesome catch! Now it works, many thanks, Ray.

**Comment by mingwandroid** [comment]
No problem, glad I could help.

**Comment by 3togo** [comment]
can you elaborate a little bit?
what should I do after installing mingw-w64-x86_64-cmake?
/mingw64/bin/cmake will then become default cmake and then there are numerous thing needs to be reconfigured. Are I right?

**Comment by 3togo** [comment]
I did make some progress on this problem 
1. Using execute_process will work perfectly.
execute_process(COMMAND "moc ../mainwindow.h > moc_mainwindow.cpp" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
2.  qt5_wrap_cpp cannot read posix path 

```
qt5_wrap_cpp(SOURCES ".mainwindow.h")
moc: /home/eli/git/superpixels-segmentation-gui-opencv/mainwindow.h: No such file

qt5_wrap_cpp(SOURCES "C:\\msys64\\home\\eli\\git\\superpixels-segmentation-gui-opencv\\mainwindow.h")
moc: Cannot open options file specified with @

```

**Comment by dmikushin** [comment]
Ah yes, I think I remembered this one. This is due to Perl usage somewhere inside the Qt. I'm not entirely sure if it applies here. But if it does, you need Windows-based Perl distribution instead of MSYS', same issue as with the CMake above.

**Comment by 3togo** [comment]
Thank you for your reply.
I sloved it along a very similar way as what you have suggested. 

`# Take care of Qt dependencies
find_package(Qt5 COMPONENTS Core Gui Widgets REQUIRED)
file( GLOB header_list src/*.h  )
file( GLOB source_list src/*.cpp )
file( GLOB ui_list src/*.ui )
file( GLOB qrc_list src/*.qrc )
if("${CMAKE_SYSTEM_NAME}" MATCHES "^MINGW64.*$")
    qt5_wrap_ui( generated_ui_list ${ui_list} )

     #not working with AUTOMOC ON
     #qt5_wrap_cpp(SOURCES "./mainwindow.h")
     #message("SOURCES = ${SOURCES}")

    list(APPEND MOC_HEADERS "mainwindow.h" "mat-image-tools.h")
    foreach (MOC_HEADER IN LISTS header_list)
        message("MOC_HEADER = ${MOC_HEADER}")
        cmake_path(GET MOC_HEADER STEM LAST_ONLY MOC_HEADER_WITHOUT_EXT)
        #cmake_path(GET MOC_HEADER STEM MOC_HEADER_WITHOUT_EXT)
        set(MOC_CPP "${CMAKE_BINARY_DIR}/moc_${MOC_HEADER_WITHOUT_EXT}.cpp")
        message("MOC_CPP = ${MOC_CPP}")
        execute_process(COMMAND moc ${MOC_HEADER} -o ${MOC_CPP} WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR} RESULT_VARIABLE CMD_ERROR)
        message("CMD_ERROR = ${CMD_ERROR}")
        list(APPEND MOC_CPPS ${MOC_CPP})
    endforeach()

    qt5_add_resources( generated_qrc_list ${qrc_list} )

endif()`

**Comment by 3togo** [comment]
But I honestly don't think it is a proper way to do it
