### ISSUE TITLE
Kate missing Qt5Xml.dll

### ISSUE THREAD

**Issue by gbschenkel** [Alexpux/MINGW-packages#4534]
I just installed 'kate' package and got the error when trying to run it.

`C:/dev/msys64/mingw64/bin/kate.exe: error while loading shared libraries: Qt5Xml.dll: cannot open shared object file: No such file or directory`

**Comment by zrax** [comment]
That will be fixed by #4533 -- short answer: install `mingw-w64-x86_64-editorconfig-core-c`
