### ISSUE TITLE
`mingw-w64-i686-gdb 8.2-1` crashing on breakpoint

### ISSUE THREAD

**Issue by matanui159** [Alexpux/MINGW-packages#4545]
- It doesn't happen in the main file (the file where the `int main()` function is defined).
- it causes the error `Thread 1 hit Breakpoint 1, game_lerp_get (terminate called after throwing an instance of 'gdb_exception_RETURN_MASK_ERROR'`
- it is happening in the repo https://github.com/matanui159/game_platform
- for the time being I will be using equation's build of gdb which is a few versions old (http://www.equation.com/servlet/equation.cmd?fa=gdb)

**Comment by Alexpux** [comment]
Related to https://github.com/Alexpux/MINGW-packages/issues/4543

**Comment by Alexpux** [comment]
Temporarily it can be solved by downgrading GCC to 7.3.0-2

**Comment by matanui159** [comment]
I believe that issue is different. That issue is with *GCC* crashing on an *exception*. My issue is with *GDB* crashing on a *breakpoint*. I have no need to downgrade *GCC*, but downgrading *GDB* has temporarily fixed the issue.
