### ISSUE TITLE
Error During NPM Update

### ISSUE THREAD

**Issue by vladipus** [Alexpux/MINGW-packages#457]
I'm getting the following error, when running`npm update -g` After this error the `npm` becomes unavailable - `bash: /mingw64/bin/npm: No such file or directory` Can the `npm` itself be updated like that or I have to exclude it from the process? The error during update is:

	npm@1.4.28 P:\msys64\mingw64\lib\node_modules\cca\node_modules\cordova\node_modules\cordova-lib\node_modules\npm
	npm@1.4.28 P:\msys64\mingw64\lib\node_modules\cordova\node_modules\cordova-lib\node_modules\npm
	npm ERR! Refusing to delete: P:\msys64\mingw64\share\man\man1\npm-README.1 not in P:\msys64\mingw64\lib\node_modules\npm
	File exists: P:\msys64\mingw64\share\man\man1\npm-README.1
	Move it away, and try again.

	npm ERR! System Windows_NT 6.1.7601
	npm ERR! command "P:\\msys64\\mingw64\\bin\\node.exe" "P:\\msys64\\mingw64\\lib\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g"
	npm ERR! cwd P:\projects.local\vdt\software\apps\third-party\tellmebest\app.cordova
	npm ERR! node -v v0.10.32
	npm ERR! npm -v 1.4.28
	npm ERR! path P:\msys64\mingw64\share\man\man1\npm-README.1
	npm ERR! code EEXIST
	npm ERR! error rolling back Error: EPERM, unlink 'P:\msys64\mingw64\bin\npm'
	npm ERR! error rolling back  { [Error: EPERM, unlink 'P:\msys64\mingw64\bin\npm']
	npm ERR! error rolling back   errno: 50,
	npm ERR! error rolling back   code: 'EPERM',
	npm ERR! error rolling back   path: 'P:\\msys64\\mingw64\\bin\\npm' }
	npm ERR! not ok code 0

**Comment by elieux** [comment]
There are two problems here. First, Windows doesn't like deleting currently opened files (which can be worked around by invoking `npm-cli.js` directly), and second, npm is a bit dumb (use '-f`). The final command is `node /mingw64/lib/node_modules/npm/bin/npm-cli.js update -g -f npm` (run in mingw64_shell). There is a [more involved way of upgrading npm](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows), but it may not be applicable to our package.
