### ISSUE TITLE
Wrong include path for header files in mingw-w64-x86_64-libkml-1.3.0-4

### ISSUE THREAD

**Issue by sphoto** [Alexpux/MINGW-packages#4571]
Wrong include path set in pkgconfig/libkml.pc

Should be <code>includedir=${prefix}/include/kml</code>

**Comment by Alexpux** [comment]
@sphoto I dont think that it is wrong. Projects may include headers like <kml\someheader.h>

**Comment by Alexpux** [comment]
@sphoto  if you think it is wrong then report it upstream
