### ISSUE TITLE
libgit2 ask for unexisting libraries on appveyor

### ISSUE THREAD

**Issue by albfan** [Alexpux/MINGW-packages#4578]
Seeing this failure;

https://github.com/Alexpux/MINGW-packages/pull/4560#issuecomment-431749658

Where are we grabbing build packages? I guess is from azure CI, since azure seems to have `libcrypto-1.1.dll` and `libssl-1.1.dll` avaliable meanwhile appveyor do not have them.

Is possible to specify openssl dep for libgit2 so it relays on `libcrypto.dll.a` and `libssl.dll.a` which are based on openssl 1.0.2 instead of those 1.1 dlls?

**Comment by lazka** [comment]
libgit2 already depends on openssl: https://msys2.duckdns.org/package/mingw-w64-i686-libgit2?repo=mingw32

**Comment by albfan** [comment]
I mean what CI upload packages there in msys2.duckdns.org?. If one CI builds correctly and the other fails, and, in my experience, it is due to one CI has libraries the other haven't, that could be the cause:

Using ntldd -R I could check that my libgit2.dll depends on libssh2.dll which need libcrypto-1.1.dll.

I recompile libssh2 and now it do not depend on libcrypto-1.1.dll

Seems too, msys2 do not detect transitive dependencies, as libssh2 is build the last one from:

mingw-w64-libgit2-glib
mingw-w64-gitg
mingw-w64-libssh2

although gitg depends on libgit2-glib which depends on libgit2 which depends on libssh2

I can touch libgit2 so libssh2 is build in correct order.

**Comment by albfan** [comment]
@Alexpux After packages are uploaded this is still happening

to recompile:

libgit2-glib complains about libgit2 not compiled in threadsafe ??? so I recompile libgit2
libgit2-glib complains about missing dlls. I found with ntldd that libgit2.dll needs libcrypto-1.1.dll, so I recompile libssh2.dll
Then libgit2-glib compiles

**Comment by albfan** [comment]
So looking for openssl:

https://msys2.duckdns.org/base/mingw-w64-openssl

it is supposed to be 1.1.1-4

looking for libcrypto-1_1.dll pkgfile confirm it:

    $ pkgfile -v libcrypto-1_1-x64.dll
    mingw64/mingw-w64-x86_64-openssl 1.1.1-4        /mingw64/bin/libcrypto-1_1-x64.dll

    $ pkgfile -v libcrypto-1_1.dll
    mingw32/mingw-w64-i686-openssl 1.1.1-4  /mingw32/bin/libcrypto-1_1.dll

But when I check for it:

    $ pacman -Q mingw-w64-i686-openssl
    mingw-w64-i686-openssl 1.0.2.n-5

    $ pacman -Q mingw-w64-x86_64-openssl
    mingw-w64-x86_64-openssl 1.0.2.n-5

And cannot update it:

```
$ pacman -S mingw-w64-x86_64-openssl
advertencia: mingw-w64-x86_64-openssl-1.0.2.n-5 está actualizado -- reinstalándolo
resolviendo dependencias...
buscando conflictos entre paquetes...

Paquetes (1) mingw-w64-x86_64-openssl-1.0.2.n-5

Tamaño total de la instalación:  34,80 MiB
Tamaño neto tras actualizar:     0,00 MiB

:: ¿Continuar con la instalación? [S/n] S
(1/1) comprobando las claves del depósito                                                               [############################################################] 100%
(1/1) verificando la integridad de los paquetes                                                         [############################################################] 100%
(1/1) cargando los archivos de los paquetes                                                             [############################################################] 100%
(1/1) comprobando conflictos entre archivos                                                             [############################################################] 100%
(1/1) comprobando el espacio disponible en el disco                                                     [############################################################] 100%
:: Procesando los cambios de los paquetes...
(1/1) reinstalando mingw-w64-x86_64-openssl                                                             [############################################################] 100%
```

so it seems to be my problem

**Comment by mati865** [comment]
@albfan try `pacman -Syy` if  it doesn't help your mirror must be outdated.

**Comment by albfan** [comment]
@mati865 seems I have something called git-for-windows in /etc/pacman.conf which is:

https://dl.bintray.com/git-for-windows/pacman/x86_64/

which max version is mingw-w64-i686-openssl-1.0.2.n-5-any.pkg.tar.xz

After removing that mirror from /etc/pacman.conf

seems it install the max openssl 1.0.2 from 

http://repo.msys2.org/mingw/x86_64/

which is mingw-w64-x86_64-openssl-1.0.2.p-1-any.pkg.tar.xz

but there is too mingw-w64-x86_64-openssl-1.1.1-4-any.pkg.tar.xz

Whatever I try to get it installed just didn't work.

    pacman -Scc
    pacman -Syu
    pacman -Syy

**Comment by albfan** [comment]
@Alexpux @mati865  I think appveyor is in the same state as my msys install. I removed /c/msys64 and install again from last installer on https://msys2.duckdns.org/ and it only install openssl 1.0.2.p-2 after pacman -Syu although this page says https://msys2.duckdns.org/base/mingw-w64-openssl is 1.1.1-4 and only openssl 1.1.1-4 containst libcrypto-1.1.dll

**Comment by albfan** [comment]
opps:

openssl is a msys package while mingw-w64-x86_64-openssl is another one:

    $ pacman -Q mingw-w64-x86_64-openssl
    mingw-w64-x86_64-openssl 1.1.1-4

So need to investigate what's missing now

**Comment by albfan** [comment]
After manually move libgitg .dll to bin all seems to work now. See https://github.com/Alexpux/MINGW-packages/pull/4589

I think I can close this now
