### ISSUE TITLE
Some notes on NCurses and Shared Libraries (And a bug(?) in g++ 4.9.2)

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#458]
I just was able to build NCurses 5.9-20150131 as shared libraries that do export symbols.

The command line I used is:

```
./configure --prefix=/mingw32-ncurses --build=i686-w64-mingw32 --with-cxx --without-ada --disable-home-terminfo --enable-database --enable-sp-funcs --enable-term-driver --enable-interop --disable-termcap --with-progs --with-libtool --enable-pc-files --mandir=/mingw32-ncurses/share/man --disable-rpath --enable-colorfgbg --disable-symlinks --enable-widec --without-pthread
```
I did have an issue with libtool not finding some Windows libraries (e.g. psapi.dll), so I set the ```deplibs_check_method``` to ```pass_all``` as a (rather horrible) workaround until I can figure out how to make it work.

(I was thinking of extending the script to look for the library without the lib prefix if on Windows, but I am not sure how to do that)

And the G++ bug is that it is looking for some .o files provided in the MinGW-w64 CRT in a hardcoded "C:\msys64\mingw32\..." instead of the prefix I have it installed at (currently "C:\MinGW\Msys2\mingw32\...")

**Comment by Alexpux** [comment]
Why do you think that paths are hardcoded for gcc?

**Comment by mingwandroid** [comment]
> I did have an issue with libtool not finding some Windows libraries (e.g. psapi.dll), so I set the deplibs_check_method to pass_all as a (rather horrible) workaround until I can figure out how to make it work.

mingw-w64 has import libraries with the lib prefix:

$ find /mingw64/x86_64-w64-mingw32/lib -name "*psapi*"
/mingw64/x86_64-w64-mingw32/lib/libpsapi.a

.. those are what libtool should find.

**Comment by BrisingrAerowing** [comment]
@mingwandroid Libtool is searching for the shared version of the library (the dll), and it says it last checked the import library, which failed the check. The usual check uses ```file``` and checks for ```X86 DLL``` in the output. 
@Alexpux The same happens for G++ from Mingw-builds and the G++ included here. I am not sure where else G++ could get those paths. It is specifically looking for crtbegin.o, crtend.o, and dllcrt2.o in the wrong path. Does the prefix for those come from somewhere else?

**Comment by Alexpux** [comment]
@BrisingrAerowing, show output from:
gcc --print-search-dirs

**Comment by mingwandroid** [comment]
@BrisingrAerowing That is incorrect, the libWINDOWSDLL.a files that I pointed out to you are "import libraries" for DLLs which is what libtool cares about. They are not static libraries by the normal definition. Usually, we prefer import libraries to have a ".dll.a" extension but this is not the case for mingw-w64 ones unfortunately.

If you've somehow bullied libtool into looking at DLLs in C:\Windows\System32 then you are using it wrong.

Given your other problem about .o files, I can only assume you're doing all sorts of weird things to the toolchains to "bend" them to your will.

**Comment by BrisingrAerowing** [comment]
All I do is ./configure; make; make install. Nothing else, other than following commands in the PKGBUILDs here. I do nothing other than those.

The exact error starts on line 9889 and goes to 9898 (in the mingw-w64-i686-libtool package libtool script).

What I get is as follows:

```
    *** Warning: linker path does not have real file for library -lpsapi.
    *** I have the capability to make that library automatically link in when
    *** you link to this library.  But I can only do this if you have a
    *** shared version of the library, which you do not appear to have
    *** because I did check the linker path looking for a file starting
    *** with libpsapi and none of the candidates passed a file format test
    *** using a file magic. Last file checked: /mingw32/i686-w64-mingw32/lib/libpsapi.a
```

(Copied from libtool with variables replaced from memory)

If that doesn't help resolve this, then I will stop using these systems and recommend that others don't as well.

**Comment by mingwandroid** [comment]
Please post full output from configure and config.log to paste.kde.org or as a gist on github.

**Comment by BrisingrAerowing** [comment]
@mingwandroid  This happens during the make stage, not configure. Configure works perfectly fine.

I will post make output as well.

**Comment by mingwandroid** [comment]
I have a feeling that the problem starts at configure. They usually do.

**Comment by BrisingrAerowing** [comment]
I am working on the gist now. Not sure how long make will take.

**Comment by BrisingrAerowing** [comment]
[Here's the Gist](https://gist.github.com/BrisingrAerowing/e6e503a8bfc9cafe2ca7)

**Comment by mingwandroid** [comment]
You should not be setting LDFLAGS or CPPFLAGS in your environment. The compiler has those values baked in, and in the correct location (i.e. in system includes and system link path, not user includes and user link path where setting them manually as you do puts them). Regardless, this is not the cause of your failure so more investigation is needed.

Please run:
https://gist.githubusercontent.com/mingwandroid/754e85ea7a5a68e47a31/raw/6d9301df039ea42078278a220654299e5e5d8832/ncurses-test.sh

and then post another gist, containing the same files as my gist (feel free to exclude ncurses-test.sh unless you modify it, and scrub env.txt of anything you don't want to broadcast):
https://gist.github.com/mingwandroid/754e85ea7a5a68e47a31

**Comment by BrisingrAerowing** [comment]
[Here you go](https://gist.github.com/BrisingrAerowing/e78130211b7d7a5a66e4)

The same error pops up at the end of the make.log file.

**Comment by mingwandroid** [comment]
next, can you do:
cd /home/Zachary/Sources/ncurses-5.9-20150131/lib
libtool --tag=CC --debug --mode=link gcc  gcc -O2 --param max-inline-insns-single=1200 -o libncursesw.la ../obj_lo/hardscroll.lo ../obj_lo/hashmap.lo ../obj_lo/lib_addch.lo ../obj_lo/lib_addstr.lo ../obj_lo/lib_beep.lo ../obj_lo/lib_bkgd.lo ../obj_lo/lib_box.lo ../obj_lo/lib_chgat.lo ../obj_lo/lib_clear.lo ../obj_lo/lib_clearok.lo ../obj_lo/lib_clrbot.lo ../obj_lo/lib_clreol.lo ../obj_lo/lib_color.lo ../obj_lo/lib_colorset.lo ../obj_lo/lib_delch.lo ../obj_lo/lib_delwin.lo ../obj_lo/lib_echo.lo ../obj_lo/lib_endwin.lo ../obj_lo/lib_erase.lo ../obj_lo/lib_flash.lo ../obj_lo/lib_gen.lo ../obj_lo/lib_getch.lo ../obj_lo/lib_getstr.lo ../obj_lo/lib_hline.lo ../obj_lo/lib_immedok.lo ../obj_lo/lib_inchstr.lo ../obj_lo/lib_initscr.lo ../obj_lo/lib_insch.lo ../obj_lo/lib_insdel.lo ../obj_lo/lib_insnstr.lo ../obj_lo/lib_instr.lo ../obj_lo/lib_isendwin.lo ../obj_lo/lib_leaveok.lo ../obj_lo/lib_mouse.lo ../obj_lo/lib_move.lo ../obj_lo/lib_mvcur.lo ../obj_lo/lib_mvwin.lo ../obj_lo/lib_newterm.lo ../obj_lo/lib_newwin.lo ../obj_lo/lib_nl.lo ../obj_lo/lib_overlay.lo ../obj_lo/lib_pad.lo ../obj_lo/lib_printw.lo ../obj_lo/lib_redrawln.lo ../obj_lo/lib_refresh.lo ../obj_lo/lib_restart.lo ../obj_lo/lib_scanw.lo ../obj_lo/lib_screen.lo ../obj_lo/lib_scroll.lo ../obj_lo/lib_scrollok.lo ../obj_lo/lib_scrreg.lo ../obj_lo/lib_set_term.lo ../obj_lo/lib_slk.lo ../obj_lo/lib_slkatr_set.lo ../obj_lo/lib_slkatrof.lo ../obj_lo/lib_slkatron.lo ../obj_lo/lib_slkatrset.lo ../obj_lo/lib_slkattr.lo ../obj_lo/lib_slkclear.lo ../obj_lo/lib_slkcolor.lo ../obj_lo/lib_slkinit.lo ../obj_lo/lib_slklab.lo ../obj_lo/lib_slkrefr.lo ../obj_lo/lib_slkset.lo ../obj_lo/lib_slktouch.lo ../obj_lo/lib_touch.lo ../obj_lo/lib_tstp.lo ../obj_lo/lib_ungetch.lo ../obj_lo/lib_vidattr.lo ../obj_lo/lib_vline.lo ../obj_lo/lib_wattroff.lo ../obj_lo/lib_wattron.lo ../obj_lo/lib_winch.lo ../obj_lo/lib_window.lo ../obj_lo/nc_panel.lo ../obj_lo/safe_sprintf.lo ../obj_lo/tty_update.lo ../obj_lo/varargs.lo ../obj_lo/vsscanf.lo ../obj_lo/lib_freeall.lo ../obj_lo/charable.lo ../obj_lo/lib_add_wch.lo ../obj_lo/lib_box_set.lo ../obj_lo/lib_cchar.lo ../obj_lo/lib_erasewchar.lo ../obj_lo/lib_get_wch.lo ../obj_lo/lib_get_wstr.lo ../obj_lo/lib_hline_set.lo ../obj_lo/lib_in_wch.lo ../obj_lo/lib_in_wchnstr.lo ../obj_lo/lib_ins_wch.lo ../obj_lo/lib_inwstr.lo ../obj_lo/lib_key_name.lo ../obj_lo/lib_pecho_wchar.lo ../obj_lo/lib_slk_wset.lo ../obj_lo/lib_unget_wch.lo ../obj_lo/lib_vid_attr.lo ../obj_lo/lib_vline_set.lo ../obj_lo/lib_wacs.lo ../obj_lo/lib_wunctrl.lo ../obj_lo/expanded.lo ../obj_lo/legacy_coding.lo ../obj_lo/lib_dft_fgbg.lo ../obj_lo/lib_print.lo ../obj_lo/resizeterm.lo ../obj_lo/use_screen.lo ../obj_lo/use_window.lo ../obj_lo/wresize.lo ../obj_lo/access.lo ../obj_lo/add_tries.lo ../obj_lo/alloc_ttype.lo ../obj_lo/codes.lo ../obj_lo/comp_captab.lo ../obj_lo/comp_error.lo ../obj_lo/comp_hash.lo ../obj_lo/db_iterator.lo ../obj_lo/doalloc.lo ../obj_lo/entries.lo ../obj_lo/fallback.lo ../obj_lo/free_ttype.lo ../obj_lo/getenv_num.lo ../obj_lo/home_terminfo.lo ../obj_lo/init_keytry.lo ../obj_lo/lib_acs.lo ../obj_lo/lib_baudrate.lo ../obj_lo/lib_cur_term.lo ../obj_lo/lib_data.lo ../obj_lo/lib_has_cap.lo ../obj_lo/lib_kernel.lo ../obj_lo/lib_keyname.lo ../obj_lo/lib_longname.lo ../obj_lo/lib_napms.lo ../obj_lo/lib_options.lo ../obj_lo/lib_raw.lo ../obj_lo/lib_setup.lo ../obj_lo/lib_termcap.lo ../obj_lo/lib_termname.lo ../obj_lo/lib_tgoto.lo ../obj_lo/lib_ti.lo ../obj_lo/lib_tparm.lo ../obj_lo/lib_tputs.lo ../obj_lo/lib_trace.lo ../obj_lo/lib_ttyflags.lo ../obj_lo/lib_twait.lo ../obj_lo/name_match.lo ../obj_lo/names.lo ../obj_lo/obsolete.lo ../obj_lo/read_entry.lo ../obj_lo/read_termcap.lo ../obj_lo/strings.lo ../obj_lo/tries.lo ../obj_lo/trim_sgr0.lo ../obj_lo/unctrl.lo ../obj_lo/visbuf.lo ../obj_lo/alloc_entry.lo ../obj_lo/captoinfo.lo ../obj_lo/comp_expand.lo ../obj_lo/comp_parse.lo ../obj_lo/comp_scan.lo ../obj_lo/parse_entry.lo ../obj_lo/write_entry.lo ../obj_lo/define_key.lo ../obj_lo/hashed_db.lo ../obj_lo/key_defined.lo ../obj_lo/keybound.lo ../obj_lo/keyok.lo ../obj_lo/version.lo ../obj_lo/lib_driver.lo ../obj_lo/gettimeofday.lo ../obj_lo/wcwidth.lo ../obj_lo/widechars.lo ../obj_lo/win_driver.lo ../obj_lo/tinfo_driver.lo -rpath /mingw32-ncurses/lib -version-number 5:9 -no-undefined -L../lib -lpsapi > libtool.txt 2>&1

.. then upload libtool.txt please?

**Comment by mingwandroid** [comment]
I've put it in a gist so that it's easier to copy:

https://gist.github.com/mingwandroid/34328444148dc362a351

**Comment by BrisingrAerowing** [comment]
@mingwandroid [Here's the file](https://gist.github.com/BrisingrAerowing/08c5d6074de1b9509f2a). You're going to have to view it raw as it is to large to display.

**Comment by mingwandroid** [comment]
Ok, this seems to be a legitimate bug with libtool, thanks for the report. I'm working on a fix now.

**Comment by BrisingrAerowing** [comment]
I was guessing as much. It seemed kind of odd that libtool would need the actual Windows dll file.

**Comment by mingwandroid** [comment]
I've committed the fixed PKGBUILD now (https://github.com/Alexpux/MINGW-packages/commit/a7a715586e8b9e425adc8fbd8904a50688361932). Please test if you are in a position to do so.

**Comment by mingwandroid** [comment]
FYI the new packages have been released now.

**Comment by BrisingrAerowing** [comment]
I'll do a test now.

**Comment by BrisingrAerowing** [comment]
Unfortunately my internet speed at home is currently very slow and I keep getting timeout errors downloading from Sourceforge using pacman. This is a common(ish) issue with cable internet. I will have to test during my break at school tomorrow (From 10:45 AM - 1:30 PM EST), as the internet there is  *usually* fast, but that can vary.

**Comment by mingwandroid** [comment]
OK, no problem

**Comment by mingwandroid** [comment]
Oh, the test requires making sure that MSYS2 isn't installed to C:\msys64. Any other path would cause the problem to happen.

**Comment by BrisingrAerowing** [comment]
Good to know. I am running configure now. Hopefully I can report back soon.

**Comment by BrisingrAerowing** [comment]
It worked perfectly fine this time. This issue is closed.
