### ISSUE TITLE
python3-cryptography broken

### ISSUE THREAD

**Issue by lovetox** [Alexpux/MINGW-packages#4610]
On a vanilla msys2 installation, after installing all dependencys

executing in python3

`from cryptography.hazmat.bindings.openssl.binding import Binding`

leads to

```
Traceback (most recent call last):
  File "C:\msys64\home\xxx\Tests\test.py", line 1, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\msys64\mingw64\lib\python3.7\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: Module not found.
```

This can also observed with python3-pyopenssl

`Import OpenSSL`

does lead to the same error

no idea how to fix that

**Comment by Alexpux** [comment]
Probably the same as https://github.com/Alexpux/MINGW-packages/issues/4582

**Comment by lovetox** [comment]
Hm no, 4582 was only experienced on appveyor, this i see locally, also pip works fine.

**Comment by yachoor** [comment]
It seems it's built against older openssl - it stopped working after openssl update that changed library names. If I copy old openssl libraries from 1.0.2 (libeay32.dll and ssleay32.dll) to C:\msys64\mingw64\bin it works fine.

**Comment by lovetox** [comment]
@Alexpux i just rebuild the package with openssl 1.1.0 present and it works now, how can we trigger a rebuild with openssl 1.1.0 present? Do we just have to add openssl to the dependencys in PKGBUILD?

Or is it enough to just up the rel-version and trigger a rebuild?

**Comment by lazka** [comment]
Is this still a problem? I tried locally and it links against openssl1.1 here.

**Comment by lovetox** [comment]
No problem anymore, because cryptography was updated to 2.4 and thus rebuild. thanks
