### ISSUE TITLE
cyclic dependency among mingw-w64-x86_64-{harfbuzz,freetype,fontconfig}

### ISSUE THREAD

**Issue by oroppas** [Alexpux/MINGW-packages#464]
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
warning: dependency cycle detected:
warning: mingw-w64-x86_64-harfbuzz will be installed before its mingw-w64-x86_64-freetype dependency
warning: dependency cycle detected:
warning: mingw-w64-x86_64-harfbuzz will be installed before its mingw-w64-x86_64-freetype dependency
warning: dependency cycle detected:
warning: mingw-w64-x86_64-harfbuzz will be installed before its mingw-w64-x86_64-fontconfig dependency
warning: dependency cycle detected:
warning: mingw-w64-x86_64-harfbuzz will be installed before its mingw-w64-x86_64-freetype dependency
warning: dependency cycle detected:
warning: mingw-w64-x86_64-harfbuzz will be installed before its mingw-w64-x86_64-freetype dependency

Packages (3) mingw-w64-x86_64-fontconfig-2.11.1-3  mingw-w64-x86_64-freetype-2.5.5-3  mingw-w64-x86_64-harfbuzz-0.9.38-3

Total Download Size:   0.90 MiB
Total Installed Size:  5.50 MiB
Net Upgrade Size:      0.05 MiB

**Comment by Alexpux** [comment]
Yeah I know it but don't know how to solve it properly. Now freetype and harfbuzz depends on each other. You can see it if open freetype and harfbuzz dll's in "Dependency Walker"

**Comment by oroppas** [comment]
OK. We can't do much about this issue. Closing for now.
