### ISSUE TITLE
PostgreSQL fails to run due to missing shared library "libssl-1_1-x64.dll"

### ISSUE THREAD

**Issue by magneticflux-** [Alexpux/MINGW-packages#4642]
I'm trying to manually start a Postgres server and it fails to start with these messages:
```
>~> postgres
C:/msys64/mingw64/bin/postgres.exe: error while loading shared libraries: libssl-1_1-x64.dll: cannot open shared object file: No such file or directory
>~> pg_ctl
C:/msys64/mingw64/bin/pg_ctl.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

I have the Git-for-Windows repositories applied before the original ones, so my OpenSSL version is `1.0.2p` per [this commit](https://github.com/git-for-windows/MINGW-packages/commit/1a3e032ef1d57c720e30f402041b434c17513c35).

**Comment by Alexpux** [comment]
@magneticflix, our postgresql package is builded with openssl 1.1.x so you need upgrade OpenSSL from our original repo

**Comment by magneticflux-** [comment]
Running `pacman -S mingw64/mingw-w64-x86_64-openssl` fixed my PostgreSQL issue! I'm still making sure it works with Git for Windows though.

**Comment by magneticflux-** [comment]
Git breaks when forcing OpenSSL 1.1 or higher. Hopefully some progress can be made in https://github.com/git-for-windows/git/issues/1691 to update OpenSSL downstream.

Closing as it's not this repository's issue that it's been updated further than others.
