### ISSUE TITLE
MSYS2 mingw-w64-opencv2 build fail

### ISSUE THREAD

**Issue by eCronik** [Alexpux/MINGW-packages#4680]
Hey,

I am trying to install "mingw-w64-opencv2" on Windows 10, and when building via "MINGW_INSTALLS=mingw64 makepkg-mingw -sLf" it ends with an error: 

https://pastebin.com/jZhVwSkV

Does somebody have an idea what is wrong here and how I might be able to fix it?

Thanks,
eC

**Comment by mati865** [comment]
I don't know where did you found `mingw-w64-opencv2`, in this repository there is only `mingw-w64-opencv` package in version 3.4.3.

**Comment by eCronik** [comment]
Hi, mati and thanks for your quick reply - I am trying to install butterflow and there it seems to be needed: 

https://github.com/dthpham/butterflow/blob/master/docs/Install-On-Windows-Guide.md

**Comment by mati865** [comment]
It's the https://github.com/dthpham/butterflow/issues/90
MSYS2 now ships FFmpeg 4.1 which is incompatible with your opencv version.
You should ask in https://github.com/dthpham/butterflow project.
