### ISSUE TITLE
Tcl build fails

### ISSUE THREAD

**Issue by oscarfv** [Alexpux/MINGW-packages#4697]
While trying to update Tcl to the new 8.6.9 release I experienced a failure when creating the package (make install phase). At first I thought that it was due to the changes on the new version, but building Tcl 8.6.8 also fails:

```
$ makepkg-mingw

....
Tcl_RegisterChannel: duplicate channel names
/bin/sh: line 1:  3868 Illegal instruction     ./tclsh86.exe "/d/dev/other/MINGW-packages/mingw-w64-tcl/src/tcl8.6.8/win/../tools/installData.tcl" "/d/dev/other/MINGW-packages/mingw-w64-tcl/src/tcl8.6.8/win/../library/msgs" "/d/dev/other/MINGW-packages/mingw-w64-tcl/pkg/mingw-w64-x86_64-tcl/mingw64/lib/tcl8.6/msgs"
make: *** [Makefile:680: install-msgs] Error 132
```

It looks like a bug on MSYS2 introduced since mingw-w64-*-tcl-8.6.8 was published.

**Comment by mati865** [comment]
I bet you have CPU without AVX or AVX2 instruction set, could you tell what you've got?
Those instructions are coming from openssl package and propagated to other binaries in `/usr/bin`:
```
/usr/bin/cleanupdelta.exe
AVX (vzeroupper)
AVX2 (vinserti128)

/usr/bin/msys-crypto-1.0.0.dll
AVX (vzeroupper)
AVX2 (vinserti128)

/usr/bin/msys-gfortran-4.dll
AVX (vxorps)
AVX2 (vpermpd)

/usr/bin/pacman.exe
AVX (vzeroupper)
AVX2 (vinserti128)

/usr/bin/pacman-conf.exe
AVX (vzeroupper)
AVX2 (vinserti128)

/usr/bin/testpkg.exe
AVX (vzeroupper)
AVX2 (vinserti128)
```
They should be using runtime detection to only use supported functions by the CPU, at least this is what they are doing on Linux. So there should be no problem.

**Comment by oscarfv** [comment]
After updating MSYS2 with the new msys runtime released this weekend, the problem persists.

**Comment by oscarfv** [comment]
Installing MSYS2 20180531 and building without updating the package database, works fine.

This PR and #4543 seems related to a new bug on the MSYS2 part, not on MinGW-w64.

**Comment by mati865** [comment]
@oscarfv can you try with `grep` 3.0?

**Comment by oscarfv** [comment]
@mati865 : same error after downgrading to grep-3.0-1.

**Comment by oscarfv** [comment]
@Alexpux : the problem is `009-fix-using-gnu-print.patch`. The special conversion chars that it introduces are unnecessary and wrong now. Possibly a change in the w64 mingw runtime.

Compile this with `gcc -Wall foo.c`:

```
#include <stdio.h>

#ifndef __USE_MINGW_ANSI_STDIO
#error "__USE_MINGW_ANSI_STDIO not defined!"
#endif

int main() {
  __int64 i = 1234567890123;
  printf("n: %Ix %I64\n", i, i);
  /* This doesn't work: */
  printf("n: %zx %ll\n", i, i);
}
```

**Comment by oscarfv** [comment]
For compatibility with i686 it seems that `009-fix-using-gnu-print.patch` must be:

```
--- tcl8.6.5-orig/win/tclWinInt.h	2016-02-25 23:12:38.000000000 +0300
+++ tcl8.6.5/win/tclWinInt.h	2016-03-03 08:47:51.129171100 +0300
@@ -45,7 +45,11 @@
 #endif
 
 #ifdef _WIN64
+# ifdef __USE_MINGW_ANSI_STDIO
+#         define TCL_I_MODIFIER        "I64"
+# else
 #         define TCL_I_MODIFIER        "I"
+# endif
 #else
 #         define TCL_I_MODIFIER        ""
 #endif
```

**Comment by Alexpux** [comment]
@oscarfv thanks, I will try
