### ISSUE TITLE
mingw-w64-xz : support for Windows XP 64 bit

### ISSUE THREAD

**Issue by whizmo** [Alexpux/MINGW-packages#4706]
The mingw-w64-xz package for 64 bits uses functions not available in Windows XP and Windows 2003.
I solved this issue compiling and installing myself the library using a modified version of the PKGBUILD file.
I only added the  --enable-threads=win95 flag to the configure step in the PKGBUILD file.

**Comment by Alexpux** [comment]
We switch minimum supported version for our packages to Win7, so there will no XP support anymore

**Comment by aquilarubra** [comment]
I am on Windows 10, latest update.

**Comment by whizmo** [comment]
OK. I understand.
I just wanted to show my workaround. Maybe it is helpful for someone.
Also, it is strange that the 32 bit package is Windows XP compatible, but the 64 bit package is not.

**Comment by vikramacme** [comment]
Hello whizmo,
 I also have similar requirement on supporting WinXP and Windows 2003 64 bit. Faced same issue. I saw your solution but did not understand it fully. Can you please help us with more details?

**Comment by vikramacme** [comment]
Hello whizmo,

 I tried to creating mingw-w64-xz package on WinXP 64 bit. but it gives error runtime: failed to create new os theard (22). By any chance you came across this issue?

-- Vikram

**Comment by whizmo** [comment]
This is the PKGBUILD file that I used back in the day. Hope it helps. 
(I had to add the .txt extension to upload it)

[PKGBUILD.txt](https://github.com/msys2/MINGW-packages/files/6598091/PKGBUILD.txt)
