### ISSUE TITLE
cmake has problems with openscenegraph

### ISSUE THREAD

**Issue by revelator** [Alexpux/MINGW-packages#4717]
OpenSceneGraph itself builds with no problems, but several modules like osgqtquick fail to build with the latest cmake.

'''CMake Error at I:/Msys64/mingw64/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find osgQt (missing: OSGQT_LIBRARY) (Required is at least version
  "3.0")'''

and yes OsgQt is installed. 
Also osgBullet seems to be in need of a patch against current bullet.

**Comment by Alexpux** [comment]
@revelator fixed by https://github.com/Alexpux/MINGW-packages/commit/f0201c7bf249b82e5fec9a8f174c49b059b6e1ac
