### ISSUE TITLE
Linking dbghelp breaks applications

### ISSUE THREAD

**Issue by rokups** [Alexpux/MINGW-packages#4739]
Linking `dbghelp` library for some reason imports all of the exported functions even if they are not used. This also includes `MapDebugInformation` which no `dbghelp.dll` dll on test system (Windows 10 LTSB) export. As a result compiled application fails to start due to missing import.

**Comment by Alexpux** [comment]
where it linked? try to remove package that provide this library

**Comment by Alexpux** [comment]
Well you need create bug report on mingw-w64 then

**Comment by rokups** [comment]
Alright, thanks.
