### ISSUE TITLE
Qt 5.4 reporting wrong version number in Qt Creator

### ISSUE THREAD

**Issue by athairus** [Alexpux/MINGW-packages#477]
Packages: 
```
mingw64/mingw-w64-x86_64-qt5-static 5.4.0-3
mingw64/mingw-w64-x86_64-qt5 5.4.0-1
```
and their 32-bit variants are reported by Qt Creator as 5.3, not 5.4.
I've only installed the 64-bit variants but for some reason the 32-bit variants show up in Qt Creator with red (!) indicating the files associated with them don't exist.

**Comment by Alexpux** [comment]
Fixed.
