### ISSUE TITLE
Boost 1.69-1 -x32/-x64 library file name suffix

### ISSUE THREAD

**Issue by stambaughw** [Alexpux/MINGW-packages#4773]
I just installed version 1.69.0-1 of boost which broke building KiCad.  After a bit of digging I found that all of the boost libraries have either -x32 or -x64 appended to the filename which breaks CMake's FindBoost macro.  I'm guessing this would also break any autotools find boost macro as well.  What is the purpose of the -x32/-x64 suffix?  Version 1.68.0-2 of boost did not have this suffix.

**Comment by oscarfv** [comment]
This breaks build scripts in general, but nothing changed in the PKGBUILD to cause this problem, so it comes from upstream.

Also, the new version adds more than 30 MB to the unpacked size. This comes from upstream too.

**Comment by josch** [comment]
I have the same problem. If I read https://github.com/Kitware/CMake/commits/master/Modules/FindBoost.cmake right, then support for boost 1.69.0 was only added in cmake 3.13.

**Comment by Alexpux** [comment]
@josch  @oscarfv I think we need revert changes in boost to generate old style names for libraries as it will break many packages. igging into boost commits....

**Comment by oscarfv** [comment]
I looked at the boost build system and -x32/-x64 are present in library names since 1.66, at least for VC++ builds (search "-x32" in https://www.boost.org/doc/libs/1_66_0/boost/config/auto_link.hpp) Somehow it didn't apply to mingw until now.

**Comment by Alexpux** [comment]
@oscarfv I think I found where irt changed. Rebuilding now boost to see if I fix it. We build tagged layout, not versioned this is why we dont have architecture in names before 1.69. Now it changed for tagged layout too

**Comment by Alexpux** [comment]
Library names will be fixed in 1.69.0-2

**Comment by stambaughw** [comment]
Thanks for the quick fix!
