### ISSUE TITLE
Geany Plugins.

### ISSUE THREAD

**Issue by genusistimelord** [Alexpux/MINGW-packages#478]
https://github.com/geany/geany-plugins

if you could make a 64 and 32bit version of these plugins for the geany package. thank you.

**Comment by elieux** [comment]
I prepared a preliminary PKGBUILD. Would you be willing to test it?

**Comment by EPashkin** [comment]
If change `-ctpl` to `-ctpl-git` in PKGBUILD starting build 64bit version but failed with
```
  CCLD     geanylua.la
libtool:   error: can't build x86_64-w64-mingw32 shared library unless -no-undefined is specified
Makefile:697: error for target «libgeanylua.la»
```
Treebrowser which I needed and cannot build yourself worked fine (after `make` in its folder).
Tried some others after geanylua and it also `make` without error.
Don't know how to build 32bit version. Using latest msys2 on Windows7 Pro 64.

**Comment by elieux** [comment]
Finally, I've done it. Added the plugins along with an update to Geany v1.29. It'll be available through pacman soon (if there's no issues).
