### ISSUE TITLE
GTK+ How to add import libraries in Visual Studio?

### ISSUE THREAD

**Issue by VladimV** [Alexpux/MINGW-packages#4781]
I installed GTK+ on Windows and I created the application using gcc. Now I want to create an application using Visual Studio. The application is compiled, but the linker needs to connect libraries. In this topic http://www.tarnyko.net/en/?q=node/22 it is proposed to add .lib files. But .lib files are not in C:\msys64\mingw64\lib. What should I do ?
Thanks

**Comment by VladimV** [comment]
Thanks ! Do you have a link to how to do it ?

**Comment by Alexpux** [comment]
@VladimV no, I'm not work with Visual Studio at all
