### ISSUE TITLE
npm not found via pacman

### ISSUE THREAD

**Issue by gdo** [Alexpux/MINGW-packages#4788]
Hello,

pacman -S mingw-w64-x86_64-npm doesn't work.

I try to use the PKGBUILD file but I have a lot of problems with deps.

I try with nvm but I can't compile nodejs 8.14.1

How can I have node and npm with msys2 ?

Thanks,

**Comment by StarWolf3000** [comment]
There's no npm package for MSYS2/MINGW available atm. You have to install `mingw-w64-x86_64-nodejs` instead (8.11.1 release 5). It comes with npm.

**Comment by AlexLeung** [comment]
Solution: add the following line to `~/.bash_profile`
`export PATH=/mingw64/bin:$PATH`

**Comment by peterbud** [comment]
@AlexLeung : pls read the first few wiki pages about the MSYS/mingw32/mingw64 subsystems:
https://github.com/msys2/msys2/wiki/MSYS2-introduction

If you wan to use a mingw64 package like `mingw-w64-x86_64-nodejs`, you need to start it from the mingw64 subsystem, NOT from the MSYS2 subsystem

**Comment by AlexLeung** [comment]
Thanks

**Comment by silviubogan** [comment]
I have an old installation of MSYS2 (of a few years). When I try to install node I get this error:

```
$ pacman -S mingw-w64-x86_64-nodejs
eroare: nu s-a găsit ținta: mingw-w64-x86_64-nodejs
```

The last line, translated, would be `error: target not found: mingw-w64-x86_64-nodejs`.

I also tried with `mingw-w64-x86_64-node` and the same result.

What can I do to make MSYS2 work with node? Should I reinstall MSYS2?

Thank you.

**Comment by silviubogan** [comment]
Sorry for the spam. I figured it out [here](https://github.com/msys2/MINGW-packages/issues/5848#issuecomment-539405968). I think I will install Ubuntu, or the Windows version of node and npm.

Thank you.

**Comment by AlexLeung** [comment]
Yeah as much as I like what MSYS2 is going for, I ended up switching to Ubuntu and now everything just works.
