### ISSUE TITLE
Geany 32bit Editor image cache issues.

### ISSUE THREAD

**Issue by genusistimelord** [Alexpux/MINGW-packages#479]
When running geany in none admin mode or admin mode the cache does not seems to get updated for 2 images.

Geany: failed to load icon 'classviewer-var': Icon 'classviewer-var' not present in theme
Geany: failed to load icon 'classviewer-method': Icon 'classviewer-method' not present in theme
Gtk: Error loading theme icon 'geany-save-all' for stock: Icon 'geany-save-all' not present in theme
Gtk: Error loading theme icon 'geany-build' for stock: Icon 'geany-build' not present in theme

this issue is fixed in the nightly geany they put up. maybe use the nightly 1.25 instead?

**Comment by elieux** [comment]
Can you run `/mingw32/bin/gtk-update-icon-cache-3.0 -f -t /mingw32/share/icons/hicolor` in MSYS2 shell opened as Administrator? Does it help?

**Comment by elieux** [comment]
Closing due to missing follow-up.
