### ISSUE TITLE
QBittorrent execution issue

### ISSUE THREAD

**Issue by suratovvlad** [Alexpux/MINGW-packages#4828]
Hello!

I'm trying to start qbittorrent 4.1.5 from this repo, however it crashes on start
![image](https://user-images.githubusercontent.com/3812290/50668784-698e6800-0fd2-11e9-893b-7d0b8a0970f9.png)

**Comment by ZachBacon** [comment]
looks like libtorrent-rasterbar needs to be rebuilt against boost again.

**Comment by Alexpux** [comment]
fixed
