### ISSUE TITLE
GLFW update 3.1 currently using 3.0

### ISSUE THREAD

**Issue by genusistimelord** [Alexpux/MINGW-packages#483]
If you get time please update glfw to 3.1 which has many segmentation fault fixes and speed ups as well as new features.

http://www.glfw.org/download.html

thank you.

I would do it myself for you if i knew how.

**Comment by mingwandroid** [comment]
Maybe you could take this as a chance to learn how?

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/95cbf719108c1ed0fc87e142effc0aa06ec0f3e4

**Comment by martell** [comment]
I would have left it forcing others to learn :)
