### ISSUE TITLE
pango: unstable version 1.43.0 does not link correctly to the gobject library

### ISSUE THREAD

**Issue by airwin1** [Alexpux/MINGW-packages#4830]
A user building PLplot on MinGW-w64/MSYS2 has reported a problem (missing link to gobject library) with linking to the pango library version 1.43.0.    The explanation of this issue is there is a bug in the pkg-config packages configured by version 1.43.0.  See comments and fix (which I think has been merged upstream) noted by  Tom Schoonjans at <https://gitlab.gnome.org/GNOME/pango/merge_requests/22#note_390137>. 
 
Upstream is going through their transition to meson using their unstable 1.43.x series of unstable releases because during that transition you can expect bugs like this one which make it impossible to use pkg-config to configure linking to the pango library.  So Tom's further comment (on the plplot-general mailing list) was the following:

"The issue here is that pango should never have been updated to 1.43.0 in MSYS2 since it’s an unstable development release, as are all GNOME releases with an odd minor version number. Linux distributions and macOS package managers would never have packaged this release."

I have verified this statement for Debian where there is no sign at all of any packaging activity for pango 1.43 for even their most cutting edge distribution (Sid = Unstable).  So you may wish to solve this pango bug and potentially others for that library by simply reverting your packaging for libpango from 1.43.0 to 1.42.4.  That change to an even minor version number (signifying a stable release series) would be consistent with recent packaging you have done for closely related GNOME libraries such as harfbuzz and cairo where the current version numbers are  harfbuzz 2.2.0 and cairo 1.16.0, i.e., the minor version numbers in those cases are even.

**Comment by lazka** [comment]
@Alexpux Why did you update to 1.43?
