### ISSUE TITLE
Should gtk3 package require hicolor-icon-theme

### ISSUE THREAD

**Issue by mojofunk** [Alexpux/MINGW-packages#484]
Hi,

I noticed that if I install the gtk3 package without first installing hicolor-icon-theme I get this output:

gtk-update-icon-cache-3.0.exe: Failed to open file mingw32/share/icons/hicolor\.icon-theme.cache : No such file or directory

but if install hicolor-icon-theme first I don't get this output, so should the gtk3 require hicolor-icon-theme or is this not a problem?

Thanks.

**Comment by Alexpux** [comment]
Hope that next commits fix it:
https://github.com/Alexpux/MINGW-packages/commit/dc6573d6de4c4ed0a520f2f23205ee392c76862e
https://github.com/Alexpux/MINGW-packages/commit/bf1c5cc2f5b93fafaf6642e5eaa7b175230564cc
https://github.com/Alexpux/MINGW-packages/commit/54365ef768e1569c3319abc1efd5efc0cdd53a4a
https://github.com/Alexpux/MINGW-packages/commit/ee6861c7316d99bf9df596dbee8e0bd5d322b542

**Comment by mojofunk** [comment]
Yes it certainly did. Thank you.
