### ISSUE TITLE
mingw-w64-glib2 (2.58.x) please apply patch for EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by rolftheunissen** [Alexpux/MINGW-packages#4840]
I had a EXCEPTION_ACCESS_VIOLATION when calling g_app_info_get_all, see https://gitlab.gnome.org/GNOME/glib/issues/1637

Please apply this patch to the 2.58.x release already
https://gitlab.gnome.org/GNOME/glib/commit/eeb657bb0f9daff272f0bf854dafe1389b05b866

**Comment by lazka** [comment]
backported in https://gitlab.gnome.org/GNOME/glib/merge_requests/586 and should be in 2.58.3

**Comment by lazka** [comment]
I've created #4899

**Comment by lazka** [comment]
Should be fixed
