### ISSUE TITLE
vlc package complains about missing libvlc.dll

### ISSUE THREAD

**Issue by mikealeonetti** [Alexpux/MINGW-packages#4877]
When I try to run vlc.exe (from the mingw64/mingw-w64-x86_64-vlc package) I get the following error:
```
$ vlc.exe
C:/msys64/mingw64/bin/vlc.exe: error while loading shared libraries: libvlc.dll: cannot open shared object file: No such file or directory
```

But it's definitely there
```
$ ls /mingw64/bin/libvlc.dll
/mingw64/bin/libvlc.dll
```
Path seems legit
```
$ echo $PATH
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/
```
Steps to reproduce:
1) Downloaded msys2 64 bit
2) Updated using pacman -Syu closed window
3) Updated packages using pacman -Su
4) Installed "mingw64/mingw-w64-x86_64-vlc"
5) Ran vlc.exe
6) Here we are

**Comment by sjemens** [comment]
libvlc.dll calls libvlccore.dll which calls libidn.dll which is the one missing.
For now you can install the mingw-w64-x86_64-libidn to satisfy the missing dependency.
I have a PR #4876 that resolves this

**Comment by mikealeonetti** [comment]
You are correct. This 100% fixes my issue. Even the project I was linking with this. Can you tell me how I can trace it next time so I can be more useful?
