### ISSUE TITLE
gdk-pixbuf2 with GDI+ is too slow

### ISSUE THREAD

**Issue by WillyAguilera** [Alexpux/MINGW-packages#489]
Please build gdk-pixbuf2 without GDI+ support, because is too slow to load image files (megapixels photos) with GDI+ loaders activated, but with the opensource loaders is better.
You only have to include --without-gdiplus in configure.
Your patch "0001-Give-priority-to-the-modules-using-the-open-source-l.patch" doesn't solution the problem of slowness.
Many Thanks for your great work, saves me many hours.

**Comment by lazka** [comment]
This is now the case since #1843, so this can be closed.
