### ISSUE TITLE
mingw-w64-x86_64-gtk-engines: the current version of engine modules can't be loaded with the current version of mingw-w64-x86_64-gdk-pixbuf2

### ISSUE THREAD

**Issue by dolbnya** [Alexpux/MINGW-packages#4905]
The current version of engine modules from mingw-w64-x86_64-gtk-engines can't be loaded with the current version of mingw-w64-x86_64-gdk-pixbuf2 because engine dlls import DllMain from libgdk_pixbuf-2.0-0.dll, but libgdk_pixbuf-2.0-0.dll doesn't export DllMain

**Comment by lazka** [comment]
#4906
