### ISSUE TITLE
mingw-w64-x86_64-gtk-engine-murrine: the current version of engine module can't be loaded with the current version of mingw-w64-x86_64-gdk-pixbuf2

### ISSUE THREAD

**Issue by dolbnya** [Alexpux/MINGW-packages#4906]
The current version of engine module from mingw-w64-x86_64-gtk-engine-murrine can't be loaded with the current version of mingw-w64-x86_64-gdk-pixbuf2 because engine dll imports DllMain from libgdk_pixbuf-2.0-0.dll, but libgdk_pixbuf-2.0-0.dll doesn't export DllMain.
The issue could be solved with rebuilding by the current gcc version.

**Comment by lazka** [comment]
mingw-w64-gtk-engines has been rebuilt, can you test if it works now?
