### ISSUE TITLE
nasm 2.14.01 may run into an infinite loop of garbage in MinGW32

### ISSUE THREAD

**Issue by LigH-de** [Alexpux/MINGW-packages#4916]
Trying to build LAME MP3 v3.100 in media-autobuild_suite, after a major clean-up in my installation, I noticed that nasm 2.14.01 quickly started to produce a huge log of garbage instead of a working binary when compiling for MinGW32. cbrt64 in IRC confirmed that, and it passed in MinGW64 instead.

9 days after [reporting this issue in the nasm tracker](https://bugzilla.nasm.us/show_bug.cgi?id=3392552), they did not yet respond.

So I would suggest considering to downdate nasm. Version 2.13.01 still seems to be the stable one, according to their IRC channel on Freenode. cbrt64 also said:

> repo lame3.100-1 was last built 15 Oct 2017 corresponding to nasm 2.13.01-1

**Comment by Alexpux** [comment]
Try to build 2.14.02 and use it

**Comment by cbrt64** [comment]
Using nasm 2.14.01-1 to build LAME 3.100-1, hit the same infinite loop for me. This only happened on i686.

Falling back to nasm 2.14-1 from the msys2 repo, as well as upgrading to a locally built 2.14.02, allowed `makepkg-mingw` to successfully build LAME on both architectures.

**Comment by LigH-de** [comment]
Confirmed. Substituted nasm 2.14.01 from MinGW packages with manually built nasm 2.14.02. LAME v3.100 builds **libmp3lame/i386/fft3dn.nas** without issues. So I hope you will agree to upgrade to the current official stable version.

**Comment by cbrt64** [comment]
Looks like 2.14.02 has been in the repos for a week now.

**Comment by LigH-de** [comment]
True. So this issue can be closed.
