### ISSUE TITLE
Issues with running gphoto2 - libreadline7 missing?

### ISSUE THREAD

**Issue by chanibal** [Alexpux/MINGW-packages#4951]
Hi, I tried to run gphoto2 and failed, any ideas why?

Here is what I've done: 
1. I obtained a clean msys2 (using chocolatey), ran `mingw64.exe`
2. I  installed gphoto with `pacman -S mingw-w64-x86_64-gphoto2`
3.  `C:/tools/msys64/mingw64/bin/gphoto2.exe: error while loading shared libraries: libreadline7.dll: cannot open shared object file: No such file or directory` - ok, I can't find the dll myself (although there is `/bin/msys-readline7.dll`)
4. Installed by hand with `pacman -Ql mingw-w64-x86_64-readline` (maybe someone forgot a dependency?)
5.  `C:/tools/msys64/mingw64/bin/gphoto2.exe: error while loading shared libraries: libreadline7.dll: cannot open shared object file: No such file or directory` - again, but this time `which libreadline7.dll` points to `/mingw64/bin/libreadline7.dll`

Tried with ldd, but it looks that it's ok:
```
$ ldd /mingw64/bin/gphoto2
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ff93efe0000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ff93c470000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ff93b8c0000)
        ADVAPI32.dll => /c/WINDOWS/System32/ADVAPI32.dll (0x7ff93e840000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7ff93ef10000)
        sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7ff93c690000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7ff93c210000)
        libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x64940000)
        libexif-12.dll => /mingw64/bin/libexif-12.dll (0x6b440000)
        libgphoto2-6.dll => /mingw64/bin/libgphoto2-6.dll (0x62280000)
        SHELL32.dll => /c/WINDOWS/System32/SHELL32.dll (0x7ff93c9c0000)
        cfgmgr32.dll => /c/WINDOWS/System32/cfgmgr32.dll (0x7ff93c090000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7ff93bd40000)
        shcore.dll => /c/WINDOWS/System32/shcore.dll (0x7ff93e790000)
        combase.dll => /c/WINDOWS/System32/combase.dll (0x7ff93e900000)
        bcryptPrimitives.dll => /c/WINDOWS/System32/bcryptPrimitives.dll (0x7ff93c190000)
        windows.storage.dll => /c/WINDOWS/System32/windows.storage.dll (0x7ff93b0d0000)
        libreadline7.dll => /mingw64/bin/libreadline7.dll (0x6e780000)
        msvcp_win.dll => /c/WINDOWS/System32/msvcp_win.dll (0x7ff93b820000)
        libgphoto2_port-12.dll => /mingw64/bin/libgphoto2_port-12.dll (0x66600000)
        profapi.dll => /c/WINDOWS/System32/profapi.dll (0x7ff93b080000)
        USER32.dll => /c/WINDOWS/System32/USER32.dll (0x7ff93e5f0000)
        powrprof.dll => /c/WINDOWS/System32/powrprof.dll (0x7ff93afe0000)
        win32u.dll => /c/WINDOWS/System32/win32u.dll (0x7ff93b0b0000)
        shlwapi.dll => /c/WINDOWS/System32/shlwapi.dll (0x7ff93c350000)
        GDI32.dll => /c/WINDOWS/System32/GDI32.dll (0x7ff93c910000)
        libintl-8.dll => /mingw64/bin/libintl-8.dll (0x61cc0000)
        ??? => ??? (0x80000)
        gdi32full.dll => /c/WINDOWS/System32/gdi32full.dll (0x7ff93be40000)
        libpopt-0.dll => /mingw64/bin/libpopt-0.dll (0x633c0000)
        kernel.appcore.dll => /c/WINDOWS/System32/kernel.appcore.dll (0x7ff93b060000)
        cryptsp.dll => /c/WINDOWS/System32/cryptsp.dll (0x7ff93c0e0000)
        libsystre-0.dll => /mingw64/bin/libsystre-0.dll (0x6bcc0000)
        libtermcap-0.dll => /mingw64/bin/libtermcap-0.dll (0x6ac40000)
        libiconv-2.dll => /mingw64/bin/libiconv-2.dll (0x66000000)
```

```
$ ldd /mingw64/bin/libreadline7.dll
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ff93efe0000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ff93c470000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ff93b8c0000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7ff93ef10000)
        USER32.dll => /c/WINDOWS/System32/USER32.dll (0x7ff93e5f0000)
        win32u.dll => /c/WINDOWS/System32/win32u.dll (0x7ff93b0b0000)
        GDI32.dll => /c/WINDOWS/System32/GDI32.dll (0x7ff93c910000)
        gdi32full.dll => /c/WINDOWS/System32/gdi32full.dll (0x7ff93be40000)
        msvcp_win.dll => /c/WINDOWS/System32/msvcp_win.dll (0x7ff93b820000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7ff93bd40000)
        libtermcap-0.dll => /mingw64/bin/libtermcap-0.dll (0x6ac40000)
        IMM32.DLL => /c/WINDOWS/System32/IMM32.DLL (0x7ff93c730000)
```

What did I do wrong? Is gphoto2 even usable? Other windows ports seem to be useless even with the special drivers.

**Comment by chanibal** [comment]
Probably related: https://github.com/Alexpux/MINGW-packages/issues/3457

**Comment by chanibal** [comment]
Yes, adding libtool fixed the issue with libreadline (although it doesn't detect any camera :/ )

So this issue is a duplicate of #3457.

**Comment by peterbud** [comment]
Have you seen #4611 ?
Try to check the dependencies using ntldd, like:
` ntldd /mingw64/bin/gphoto2`

**Comment by chanibal** [comment]
Not exactly on topic, @peterbud  but can you give me a few pointers on gphoto2/libusb usage? I used it before in linux, but on windows, I can't get it to run.

I installed libusb 1.2.6.0 and using inf-wizard.exe installed it to my camera for both startup modes (PictBridge (PTP) and PC). The camera is now recognized as:
![image](https://user-images.githubusercontent.com/697605/52410110-aa006a80-2ad7-11e9-94bf-b89f76784a98.png)


In PictBridge (PTP) mode of my camera, it all works - but this mode does not support any camera control:
<pre>
# gphoto2 --auto-detect --summary
Model                          Port
----------------------------------------------------------
Panasonic DMC-FS62             usb:001,010
Camera summary:
Manufacturer: Panasonic
Model: DMC-GF6
  Version: 1.2
  Serial Number: 000000000000000000FX1L05290980
Vendor Extension ID: 0x6 (1.0)

Capture Formats:
Display Formats: Association/Directory, DPOF, Apple Quicktime, Defined Type, JPEG
Supported MTP Object Properties:
        Association/Directory/3001: dc01/StorageID dc02/ObjectFormat dc03/ProtectionStatus dc04/ObjectSize dc05/AssociationType dc07/ObjectFileName dc0b/ParentObject dc41/PersistantUniqueObjectIdentifier dc44/Name
        DPOF/3006: dc01/StorageID dc02/ObjectFormat dc03/ProtectionStatus dc04/ObjectSize dc07/ObjectFileName dc0b/ParentObject dc41/PersistantUniqueObjectIdentifier dc44/Name
        Apple Quicktime/300d: dc01/StorageID dc02/ObjectFormat dc03/ProtectionStatus dc04/ObjectSize dc07/ObjectFileName dc0b/ParentObject dc41/PersistantUniqueObjectIdentifier dc44/Name dc87/Width dc88/Height dc89/Duration de93/SampleRate de94/NumberOfChannels de97/ScanDepth de9a/AudioBitRate de9b/VideoFourCCCodec de9c/VideoBitRate
        Defined Type/3800: dc01/StorageID dc02/ObjectFormat dc03/ProtectionStatus dc04/ObjectSize dc07/ObjectFileName dc0b/ParentObject dc41/PersistantUniqueObjectIdentifier dc44/Name dc87/Width dc88/Height dcd3/ImageBitDepth
        JPEG/3801: dc01/StorageID dc02/ObjectFormat dc03/ProtectionStatus dc04/ObjectSize dc07/ObjectFileName dc0b/ParentObject dc41/PersistantUniqueObjectIdentifier dc44/Name dc87/Width dc88/Height dcd3/ImageBitDepth

Device Capabilities:
        File Download, File Deletion, No File Upload
        No Image Capture, No Open Capture, No vendor specific capture

Storage Devices Summary:
store_00010001:
        StorageDescription: None
        VolumeLabel: None
        Storage Type: Removable RAM (memory card)
        Filesystemtype: Digital Camera Layout (DCIM)
        Access Capability: Read-Write
        Maximum Capability: 3948937216 (3766 MB)
        Free Space (Bytes): 1485930496 (1417 MB)
        Free Space (Images): 0

Device Property Summary:
Session Initiator Info(0xd406):(readwrite) (type=0xffff) 'Windows/6.2.9200 MTPClassDriver/6.2.9200.16384'
Perceived Device Type(0xd407):(read only) (type=0x6) 1
Battery Level(0x5001):(read only) (type=0x2) Range [0 - 100, step 10] value: 100% (100)

...

# gphoto2 --trigger-capture
ERROR: Could not trigger capture.
*** Error (-6: 'Unsupported operation') ***
</pre>

In PC mode (the one I've been using on Linux), control should be supported, but I can't seem to connect to the device:
<pre>
# gphoto2 --auto-detect
Model                          Port
----------------------------------------------------------
</pre>

At some point before, auto detect seemed to be working under PC mode, but any query of the camera (even `--summary`) said that `*** Error (-53: 'Could not claim the USB device') ***`.

I think this was before I installed libusb drivers to PictBridge (PTP) mode.

**Comment by peterbud** [comment]
Here is how you can make `libgphoto2 `work on Windows:
libgphoto2 doesn’t work with the default Windows drivers used for connecting them via USB. For tethering to work (in general for libgphoto2 and libusb to work):
* Use [this](http://zadig.akeo.ie/) program to install USB driver on Windows for your camera
* Follow the description [here](https://github.com/pbatard/libwdi/wiki/Zadig). When you run it, replace the current Windows camera driver with WinUSB driver.

I was able to use my D5000 to use in tethered mode in darktable do live preview and capture photos.

**Comment by chanibal** [comment]
Thanks for the help, @peterbud. The thing is somehow I've broken my camera. Not sure if this was an firmware update, me trying to use all of the different zadig drivers or anything else - but it stopped giving me the option to configure itself via PTP. In PC mode it now only gives me USB mass storage option and nothing more - although before it had lots of vendor extensions.

This is not an issue with MSYS2 and probably not with gphoto2 either. Verified with another MacOS machine with gphoto2 that supported the camera before that.
Tried resetting the settings of the camera (they didn't provide a proper factory reset), tried a firmware update to newest official firmware - but nothing did help. Fortunatelly I've got different cameras to check out... hopefully they'll work.

Back to the issue - it was a missing libtool issue - so maybe add it to the package dependencies? I know it shouldn't be required, but it is. It's small and everything works well when it's there, so maybe this fix is a good idea?

**Comment by peterbud** [comment]
Yes, you are right:
```
$ ntldd /mingw64/bin/libgphoto2-6.dll
        libgphoto2_port-12.dll => C:\Development\msys64\mingw64\bin\libgphoto2_port-12.dll (0x0000000000bf0000)
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x0000000000d30000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x0000000000d30000)
        SHELL32.dll => C:\WINDOWS\SYSTEM32\SHELL32.dll (0x0000000000fe0000)
        libexif-12.dll => C:\Development\msys64\mingw64\bin\libexif-12.dll (0x0000000000bf0000)
        libintl-8.dll => C:\Development\msys64\mingw64\bin\libintl-8.dll (0x0000000000c10000)
        libltdl-7.dll => C:\Development\msys64\mingw64\bin\libltdl-7.dll (0x0000000000c10000)
```

I'll open a PR shortly.
