### ISSUE TITLE
Failed to link ws2_32 

### ISSUE THREAD

**Issue by yuwenyong** [Alexpux/MINGW-packages#4952]
When I compile my program, it is always failed with following messages.

[ 98%] Linking CXX executable exception_test.exe
C:/msys64/mingw64/lib/libcrypto.a(b_addr.o):(.text+0xaa): undefined reference to `__imp_getnameinfo'
C:/msys64/mingw64/lib/libcrypto.a(b_addr.o):(.text+0x21d): undefined reference to `gai_strerrorW'
C:/msys64/mingw64/lib/libcrypto.a(b_addr.o):(.text+0xb05): undefined reference to `gai_strerrorW'
C:/msys64/mingw64/lib/libcrypto.a(b_addr.o):(.text+0xc67): undefined reference to `gai_strerrorW'

I have found that libws2_32.a only exists in the path C:/msys64/mingw64/x86_64-w64-mingw32/lib.
So I add the link flags "-LC:/msys64/mingw64/x86_64-w64-mingw32/lib -lwsock32 -lws2_32".

I don't know why I still failed to link against libws2_32.a? Or where else can I find ws2_32 library?

**Comment by rthickling** [comment]
Did you determine the reason for this?  I have the same problem.
I found documentation on `gai_strerrorW` [here](https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-gai_strerrorw).  I read that the libraries (and others I needed) could be found in the [Windows 10 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/) so I downloaded and installed it.

This put many libraries in `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64` including `ws2_32.lib` which I thought would contain `gai_strerrorW`.  But linking using it failed to resolve `gai_strerrorW`.  Also, running 
```
nm ws2_32.lib | grep gai_strerrorW
``` 
found nothing.  So I guess `gai_strerrorW` is not actually in `ws2_32.lib` !

@yuwenyong you closed this - so perhaps you'd found the answer?

**Comment by Biswa96** [comment]
You are not supposed to use library Visual Studio with mingw compiler. Try to add `-lws2_32` option while compiling the program. `gai_strerrorW` API exists in mingw-w64 crt. For example,

```sh
$ nm /mingw64/x86_64-w64-mingw32/lib/libws2_32.a | grep gai_strerror
lib64_libws2_32_a-gai_strerrorA.o:
0000000000000000 T gai_strerrorA
                 U gai_strerrorW
lib64_libws2_32_a-gai_strerrorW.o:
0000000000000000 T gai_strerrorW
```

**Comment by rthickling** [comment]
Hey thanks @Biswa96 - that figures.  I didn't realize there was a MSYS version of `ws2_32` - but I suppose that's obvious.
Thanks for your help!
