### ISSUE TITLE
evince seg faults

### ISSUE THREAD

**Issue by fspeech** [Alexpux/MINGW-packages#496]
I installed evince to view ps files. It seg faulted after I tried to open a ps file and then continued to seg fault at start up. Is this a known issue with evince? If not I wonder if I did something wrong during install and should attempt to reinstall it and its dependencies. I killed fontconfig during installation because I thought it was running too long but I think it was just populating the cache. Later I reinstalled fontconfig but evince still seg faults.

**Comment by fspeech** [comment]
I have pacman -Syu my system to make sure it is up to date and the seg fault persisted. It gave out the following message before it died:
```
(evince.exe:8912): GLib-GIO-CRITICAL **: This application can not open files.

[1]+  Segmentation fault      evince ~/w/some.ps
```
Invoking evince without a file also seg faults but without the warning.

**Comment by fspeech** [comment]
I decided to try ```ps2pdf``` instead and use a pdf viewer. However when I first ran ps2pdf it could not find ```gs``` even though ghostscript is installed. I found a few exes that start with gs in the ghostscript package by using ```pacman -Ql```. Ghostscript official website says ```gswin32c.exe``` is the preferred Windows command line interface, but ```gsc.exe``` looks identical to ```gswin32c.exe``` by size. I copied ```gsc.exe``` to ```gs.exe``` and ```ps2pdf``` now works. So it looks like the installation script did not name the executable correctly: ```gsc.exe``` should have been named ```gs.exe```. Please fix the ghostscript installation script. 

Feel free to close this issue as I no longer need evince (evince still seg faults). I will be using ps2pdf manually and then use system pdf viewer instead.

**Comment by Alexpux** [comment]
Does evince not work for you at all? I'm be able to open pdf documents with it without issues.
Ghostscript package  seems need install gs.exe too. Will see it.

**Comment by fspeech** [comment]
The very first time evince started up okay. After the first crash however evince crashed at start up. That seemed suspicious so I tried to figure out how evince starts. I found the file ```AppData/Local/recently-used.xbel``` that seemed to contain xml data of evince invocation so I removed it. And now evince works both on pdf and postscript files! 
So this confirms that missing ```gs.exe``` was the cause of the first evince crash. There is a bug somewhere with evince not able to recover from that crash but it is not specific to your distro. So please close the issue after you fix the ghostscript package (either rename or copy ```gsc.exe``` to ```gs.exe```) since I think a correctly installed gs should  not crash evince. But people whose evince already crashed need to manually delete the file ```AppData/Local/recently-used.xbel``` to recover from the missing ```gs.exe``` problem (a simple reinstall won't work).
