### ISSUE TITLE
linking to qt5 is broken (contains references to build system)

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MINGW-packages#4967]
a basic Qt5Core example fails with undefined references to pcre2

and the prl files contain a lot of references to static libraries in `'C:/building/msys32/mingw64/x86_64-w64-mingw32/lib`

**Comment by Optiligence** [comment]
qt5 (non static) is also affected: 
`Qt5GuiConfigExtras.cmake`, `*.prl` and `*.pc` files

**Comment by Alexpux** [comment]
@Optiligence what ````*.pc```` files you mean? I dont see issues with Qt5 pc files.

**Comment by adipose** [comment]
I have been having the same problem with qt 5 static.  Prior build was ok, but the binaries were twice the size of normal.  After upgrading, can't link at all :-/

**Comment by Optiligence** [comment]
Ok, my non-static issues were due to an empty `CMAKE_BUILD_TYPE`. Although `Qt5GuiConfigExtras.cmake` still contains the following, that doesn’t seem to be a breaking problem. 
```
_qt5gui_find_extra_libs(OPENGL "C:/building/msys32/mingw64/x86_64-w64-mingw32/lib/libglu32.a;C:/building/msys32/mingw64/x86_64-w64-mingw32/lib/libopengl32.a;C:/building/msys32/mingw64/x86_64-w64-mingw32/lib/libgdi32.a;C:/building/msys32/mingw64/x86_64-w64-mingw32/lib/libuser32.a" "" "")
```

And for static, Core actually works, but using Gui or Widgets requires static libraries in locations were they don’t exist.

**Comment by Alexpux** [comment]
This I hope will solve paths problem:
https://github.com/Alexpux/MINGW-packages/commit/0fa1452ca9fb2a2cfb93df37e6e0bec53f6fa5d8
and
https://github.com/Alexpux/MINGW-packages/commit/f514bb8d7bccbb231e8b66c922aeb2dd03f3f6e1

**Comment by adipose** [comment]
Alex, are these patches live, or do we need to wait for another qt5 static build? I still have the problems I had earlier.

**Comment by Alexpux** [comment]
You can build Qt5 static yourself to test or wait while I have time to do it

**Comment by adipose** [comment]
After manually applying the following script (cribbed from your patch), I still get an error.

```
#/usr/bin/bash
export pkgdir=/mingw32
export MINGW_PREFIX_WIN=C:/building/msys32/mingw32
export _qt5_prefix=/qt5-static
export QT_PREFIX_WIN=$(cygpath -m ${_qt5_prefix})
export PKGDIR_QT_PREFIX_WIN=$(cygpath -m ${pkgdir}${_qt5_prefix})

echo pkgdir=${pkgdir}
echo _qt5_prefix=${_qt5_prefix}
echo MINGW_PREFIX_WIN=${MINGW_PREFIX_WIN}
echo PKGDIR_QT_PREFIX_WIN=${PKGDIR_QT_PREFIX_WIN}


find "${pkgdir}${_qt5_prefix}/share/qt5" -type f \( -name '*.pri' -o -name '*.prl' \) -exec sed -i -e "s|${MINGW_PREFIX_WIN}|${PKGDI
find "${pkgdir}${_qt5_prefix}/lib" -type f \( -name '*.pri' -o -name '*.prl' \) -exec sed -i -e "s|${MINGW_PREFIX_WIN}|${PKGDIR_QT_P
~

```

`g++.exe: error: C:/msys64/mingw32/qt5-static/lib/libQt5Core.dll.a: No such file or directory`

There indeed does not seem to be any `libQt5Core.dll.a` in the static build, unlike in previous versions of the static build.

```
$:qt5-static$find . -name libQt5Core*
./lib/libQt5Core.a
./lib/libQt5Cored.a

```

**Comment by Alexpux** [comment]
You need remove installed shared and static Qt5 before build

**Comment by adipose** [comment]
Sorry, I should have explained better.  I didn't rebuild Qt, I just applied that script to the already installed qt5-static, which fixed all my build issues, except that dll one.  I'm not quite sure why the static build is referencing the dll library.

**Comment by adipose** [comment]
The qmodule.pri has these offending lines, which weren't present in older qt5-static builds (mine's a bit older, but I think it makes the point ok).


![qmodule.pri](https://i.imgur.com/0b77Cin.png)

**Comment by adipose** [comment]
I think this one can be closed since 5.12.1-4 was published and solves it.  But my new issue is probably the same as:

https://github.com/Alexpux/MINGW-packages/issues/4970

**Comment by Kwizatz** [comment]
This seems to be back on 5.12.3-1:

$ pacman -Qe | grep qt
mingw-w64-x86_64-qt5 5.12.3-1

$ cmake -G"MSYS Makefiles" ..
-- Generator MSYS Makefiles
CMake Error at C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:15 (message):
  The imported target "Qt5::Gui" references the file

     "C:/building/msys32/mingw64/x86_64-w64-mingw32/lib/libglu32.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:45 (_qt5_Gui_check_file_exists)
  C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:70 (_qt5gui_find_extra_libs)
  C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:212 (include)
  C:/msys64/mingw64/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  CMakeLists.txt:212 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Code/AeonEngine3/mingw64/CMakeFiles/CMakeOutput.log".

**Comment by Optiligence** [comment]
ya, i made https://github.com/msys2/MINGW-packages/issues/5253 because i thought it was different
but looking again (at https://github.com/msys2/MINGW-packages/issues/4967#issuecomment-462732784) it, indeed, seems to be identical
