### ISSUE TITLE
A lot of (*.pri)file not apply patch after mingw-w64-i686-qt5-static-5.12.1-2 installed

### ISSUE THREAD

**Issue by shithappens2016** [Alexpux/MINGW-packages#4968]
mingw-w64-i686-qt5-static-5.12.1-2

`EXTRA_DEFINES += DBUS_STATIC_BUILD JAS_DLL=0
EXTRA_INCLUDEPATH += C:/building/msys32/mingw32/include/dbus-1.0 C:/building/msys32/mingw32/lib/dbus-1.0/include C:/building/msys32/mingw32/include/mariadb
QT_CPU_FEATURES.i386 = 
QT.global_private.enabled_features = sse2 alloca_malloc_h alloca avx2 dbus dbus-linked gc_binaries gui network release_tools sql testlib widgets xml
QT.global_private.disabled_features = alloca_h android-style-assets private_tests libudev posix_fallocate reduce_exports reduce_relocations stack-protector-strong system-zlib
PKG_CONFIG_EXECUTABLE = C:\\building\\msys32\\mingw32\\bin/pkg-config.exe
QMAKE_LIBS_DBUS = C:/building/msys32/mingw32/lib/libdbus-1.dll.a C:/building/msys32/mingw32/i686-w64-mingw32/lib/libws2_32.a C:/building/msys32/mingw32/i686-w64-mingw32/lib/libiphlpapi.a C:/building/msys32/mingw32/i686-w64-mingw32/lib/libdbghelp.a
QMAKE_INCDIR_DBUS = C:/building/msys32/mingw32/include/dbus-1.0 C:/building/msys32/mingw32/lib/dbus-1.0/include
QT_COORD_TYPE = double
CONFIG += sse2 aesni sse3 ssse3 sse4_1 sse4_2 avx avx2 avx512f avx512bw avx512cd avx512dq avx512er avx512ifma avx512pf avx512vbmi avx512vl compile_examples f16c largefile optimize_debug precompile_header rdrnd shani x86SimdAlways
QT_BUILD_PARTS += libs tools
QT_HOST_CFLAGS_DBUS += -IC:/building/msys32/mingw32/include/dbus-1.0 -IC:/building/msys32/mingw32/lib/dbus-1.0/include
`

**Comment by Alexpux** [comment]
@shithappens2016 well there are an issue with patching such situation right now. Need to think how to solve this. This is because qtbinpatcher cant find old prefix in pri files as /mingw64 and /mingw64/qt5-static are different prefixes

**Comment by Alexpux** [comment]
@shithappens2016 probably this https://github.com/Alexpux/MINGW-packages/commit/0fa1452ca9fb2a2cfb93df37e6e0bec53f6fa5d8 will solve wrong paths problem

**Comment by shithappens2016** [comment]
@Alexpux don't have building environment can't test it.
Not just qconfig.pri and qmodule.pri but all the pri and prl files are contain the wrong path 'C:/building/msys32/'

**Comment by Alexpux** [comment]
Also more path fixes by https://github.com/Alexpux/MINGW-packages/commit/f514bb8d7bccbb231e8b66c922aeb2dd03f3f6e1
