### ISSUE TITLE
QScintilla Install Failure

### ISSUE THREAD

**Issue by RobertBColton** [Alexpux/MINGW-packages#4982]
```
$ pacman -Sy mingw-w64-x86_64-qscintilla
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-qscintilla-2.10.8-1

Total Download Size:    8.48 MiB
Total Installed Size:  67.28 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 mingw-w64-x86_64-qs...     8.5 MiB  8.76M/s 00:01 [#####################] 100%
(1/1) checking keys in keyring                     [#####################] 100%
(1/1) checking package integrity                   [#####################] 100%
:: File /var/cache/pacman/pkg/mingw-w64-x86_64-qscintilla-2.10.8-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] Y
error: failed to commit transaction (invalid or corrupted package (checksum))
Errors occurred, no packages were upgraded.
```

**Comment by nophead** [comment]
I have exactly the same issue.

**Comment by StarWolf3000** [comment]
Have you tried downloading it via browser and installing via `$ pacman -U mingw-w64-x86_64-qscintilla-2.10.8-1-any.pkg.tar.xz`?

**Comment by nophead** [comment]
The only place I could find that file was on Sourceforge. I download that and it does work, thanks.

**Comment by StarWolf3000** [comment]
Which mirror do you use? Check /etc/pacman.d/mirrorlist.mingw64, the mirrors without `#` at the beginning of the line are active and they're used from top to bottom.

The file I checked is on https://repo.msys2.org/mingw/x86_64/ : http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-qscintilla-2.10.8-1-any.pkg.tar.xz

**Comment by nophead** [comment]
Hmm, seem to be using a Russian mirrow. I am in the UK.
```
##
## 64-bit Mingw-w64 repository mirrorlist
##

## Primary
## msys2.org
Server = http://repo.msys2.org/mingw/x86_64/
Server = https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/
Server = http://www2.futureware.at/~nickoe/msys2-mirror/mingw/x86_64/
Server = https://mirror.yandex.ru/mirrors/msys2/mingw/x86_64/
```

**Comment by StarWolf3000** [comment]
Again, try downloading it via browser from repo.msys2.org, and install it manually.

**Comment by nophead** [comment]
Yes that also works.

**Comment by StarWolf3000** [comment]
Then from whatever mirror it was downloaded, it was corrupt, either during download or already corrupt in the repo of the mirror.

**Comment by RobertBColton** [comment]
Well maybe it would be a good idea for that mirror to be de-listed. Especially if it's from Russia I mean.... maybe it's malicious and that's why the checksum is failing?

**Comment by nophead** [comment]
I manually downloaded the Russian one and did a file compare with the repo.msys2.org and it matches, so I have no idea what the problem is / was.

**Comment by RobertBColton** [comment]
Sure, while that may work for me and you, I am leaving the issue open because that's.... generally defeats the purpose of the package system having to do all of it manually. For other people, they will at least see this work around, but the actual issue should still be rooted out and addressed.

**Comment by nophead** [comment]
Even with my mirror list set to this:
```
##
## 64-bit Mingw-w64 repository mirrorlist
##

## Primary
## msys2.org
Server = http://repo.msys2.org/mingw/x86_64/
#Server = https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/
#Server = http://www2.futureware.at/~nickoe/msys2-mirror/mingw/x86_64/
#Server = https://mirror.yandex.ru/mirrors/msys2/mingw/x86_64/
```
I get the problem, so I don't think it is a corrupt mirror.

**Comment by StarWolf3000** [comment]
Err, I'm not going to test it out with pacman, since not only would it require me to download 1.4 GiB in total, but installation itself takes 7.5 GiB (thanks Qt!).

Also try to disable anti-virus, it may interfere with the download and make sure, there's enough space on the drive for the package cache.

**Comment by nophead** [comment]
Yes QT is massive but I have plenty of space. 

I don't ever need to disable my virus checker (NOD32) for anything else, so I doubt that is a factor. I am loading dozens of packages, including the huge QT one with pacman -S and they all work except this one, unless I download it manually.

**Comment by nophead** [comment]
I got the same problem yesterday morning with pacman -Syuu.  Ran it again today and it updated a lot of packages again and didn't fall over at QScintilla. Very odd because it updated qt yesterday and updated it again today. Did it change overnight or is there something odd going on?

**Comment by RobertBColton** [comment]
I did the same thing and it worked here too. Closing as resolved I guess.
