### ISSUE TITLE
GCC -mcrtdll specs faulty

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#507]
The default specs file for GCC has the following in the libgcc section:

```
%{!mcrtdll:-lmsvcrt}%{mcrtdll=*:-l%*}
```

which promptly causes failures as it outputs -lmsvcrt-lwhatever if the -mcrtdll=whatever options is used.

Adding a space between the two parts fixes the issue:

```
%{!mcrtdll:-lmsvcrt} %{mcrtdll=*:-l%*}
```

This caused me quite a few headaches before I figured out what actually was going on.

**Comment by Alexpux** [comment]
Will bbe fixed in GCC-4.9.2-5
