### ISSUE TITLE
qt5-static qcollectiongenerator missing minimal plugin

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MINGW-packages#509]
fails with 
```
This application failed to start because it could not find or load the Qt platform plugin "minimal".
Available platform plugins are: windows.
```

**Comment by Alexpux** [comment]
For static Qt you need link with Qt plugins statically too.

**Comment by mingwandroid** [comment]
@Alexpux this is a bug in our qt5-static package. I will take a look at how qcollectiongenerator.exe is built as soon as I can. It may not be for a few days yet though.

**Comment by mingwandroid** [comment]
@Optiligence : if you rebuild qt5-static this should be ok now.

**Comment by Optiligence** [comment]
@mingwandroid thanks
