### ISSUE TITLE
Shebangs of python2 packages contain "C:/msys64"

### ISSUE THREAD

**Issue by zklhp** [Alexpux/MINGW-packages#515]
Shebangs of some files in mingw-w64-x86_64-python2 and related packages are started with windows-style absolute path "C:/msys64". This may cause problems when the install path is not "C:/msys64". These files are:

mingw-w64-x86_64-python2 2.7.9-2:
/mingw64/bin/2to3
/mingw64/bin/idle
/mingw64/bin/pydoc
/mingw64/lib/python2.7/smtpd.py

mingw-w64-x86_64-python2-setuptools 12.0.5-1:
/mingw64/bin/easy_install-2.7-script.py

mingw-w64-x86_64-python2-ipython 2.3.1-1:
/mingw64/bin/ipcluster2-script.py
/mingw64/bin/ipcontroller2-script.py
/mingw64/bin/ipengine2-script.py
/mingw64/bin/iptest2-script.py
/mingw64/bin/ipython2-script.py

**Comment by Alexpux** [comment]
Fixed.
