### ISSUE TITLE
Bug in Cmake patch

### ISSUE THREAD

**Issue by oltolm** [Alexpux/MINGW-packages#525]
The Cmake patch wxWidgets-module.patch contains a bug.
```
        # Flags are a string, not a list, fix it here
        string(REPLACE ";" " "
          wxWidgets_CXX_FLAGS "${wxWidgets_CXX_FLAGS}"
```
This code turns a list into a string that leads to the following error:
```
g++.exe: error: unrecognized command line option '-mthreads -fpermissive'
```
This happens because the generated makefile contains the following code:
```
 -std=c++11 "-mthreads -fpermissive" -o 
```
My `CMakeLists.txt` contains the following code:
```
target_compile_options(${PROJECT_NAME} PRIVATE ${wxWidgets_CXX_FLAGS})
```
The other variables like `wxWidgets_INCLUDE_DIRS`, `wxWidgets_DEFINITIONS` and `wxWidgets_LIBRARIES` are lists and work correctly with `target_include_directories`, `target_link_libraries` and `target_compile_definitions`.

If I manually remove this patch then the generated Makefile is correct.
```
-std=c++11 -mthreads -fpermissive -o 
```
Please remove the incorrect patch.

**Comment by Alexpux** [comment]
This patch solve problem splitting flags that are get from wxWidgets config. So I can't remove this patch.

**Comment by oltolm** [comment]
I understand, but those problems should be solved in a proper way. This patch breaks CMake projects that use `wxWidgets_CXX_FLAGS`. It took me hours to find this problem. All the `wxWidgets_*` variables are correct except this one. Please take a look at this [bug report](http://www.cmake.org/Bug/view.php?id=15087). There a CMake developer rejects the patch and explains why it is wrong:
>The FindwxWidgets module only sets the value of wxWidgets_CXX_FLAGS. It is up to the project to use it correctly. If one uses the COMPILE_OPTIONS target property to apply the flags then a ;-list is the correct thing. I think this is a documentation issue because the docs do not say how the value is provided w.r.t. multiple flags. Existing projects may already expect a ;-list since that is what is now provided. Rather than changing this behavior, it should simply be documented.

This is exactly what happened to me. My project expects the `wxWidgets_CXX_FLAGS` to be a list, just like all the other `wxWidgets_*`variables. And this patch broke it.

**Comment by Alexpux** [comment]
Ok, push proper patch then instead.

**Comment by oltolm** [comment]
What are the problems that this patch tries to solve? If I knew I could try solving those problems or I could inform the package maintainers about them.

**Comment by Alexpux** [comment]
Read original bug report carefully:
````
FindwxWidgets.cmake parses the output of wx-config and converts it to a list. The definitions and includes seem to be processed appropriately but whatever is left is considered a CXX flag.

If more than one flag remains it is left as a cmake list, i.e.:
"-mthreads;-fpermissive" which gcc chokes on.
````

**Comment by Alexpux** [comment]
See output:
````
$ /mingw32/bin/wx-config --cxxflags
-I/mingw32/lib/wx/include/msw-unicode-3.0 -I/mingw32/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMSW__ -mthreads -fpermissive
````

**Comment by oltolm** [comment]
That is not enough information for me to fix it. The code in `FindwxWidgets.cmake` is correct. The CMake developer confirms it.

>It is up to the project to use it correctly. If one uses the COMPILE_OPTIONS target property to apply the flags then a ;-list is the correct thing.

Therefore I would need to know in which MINGW package the problem happens. Perhaps I should simply ask Richard Shaw why he created the patch. It seems that he already has a fix that is not yet in CMake.

**Comment by Alexpux** [comment]
Try build for example 32-bit "codelite-git"

**Comment by oltolm** [comment]
It turns out that he already fixed the bug in CMake. See the [maling list](http://public.kitware.com/pipermail/cmake-developers/2014-August/011040.html) and this [git commit](http://www.cmake.org/gitweb?p=cmake.git;a=commit;h=e6fa6e60f6330ddf60294a0d9a6ed4cb3f27d4c4).

For some reason he didn't close his own bug report. He didn't inform you to tell that his patch is wrong and breaks other software. There's nothing for me to do.

**Comment by Alexpux** [comment]
Ok, will rebuild cmake without my patch then
