### ISSUE TITLE
MinGW-w64-tools(-git) not in the binary repository

### ISSUE THREAD

**Issue by rubenvb** [Alexpux/MINGW-packages#528]
This package is not available through pacman. And the non-git version deserves a spot in the repo too.

**Comment by Alexpux** [comment]
Packages named as:
````
mingw-w64-i686-tools-git
mingw-w64-x86_64-tools-git
````

We build only trunk version because all packages builded with it, so we don't want to build released travels.

**Comment by rubenvb** [comment]
RIght, could have known. Should have known. Sorry for the noise.
