### ISSUE TITLE
gettext doesn't works for MINGW, show invalid encoding result

### ISSUE THREAD

**Issue by lygstate** [Alexpux/MINGW-packages#535]
Start mingw shell mingw64_shell.bat
run
```
$ echo $LANG
zh_CN.UTF-8
$ msgfmt #The the console will show the invalid characters.
```

**Comment by Alexpux** [comment]
This issue is duplicate for https://github.com/Alexpux/MSYS2-packages/issues/208

**Comment by lygstate** [comment]
@Alexpux sorry for the duplicate, I just think this issue belongs to mingw but msys.
cause msys works fine.

**Comment by elieux** [comment]
This seems to work now, so I'm closing the ticket.
```
$ LANG=zh_CN.UTF-8 msgfmt
msgfmt: 没有给出输入文件
试试“msgfmt --help”查看帮助信息。
```
If the issue persists, re-open the ticket.
