### ISSUE TITLE
mingw-w64-lua: Conflicting files error prevents upgrade

### ISSUE THREAD

**Issue by athairus** [Alexpux/MINGW-packages#537]
```
$ pacman -Su
:: Starting full system upgrade...
***snip***
error: failed to commit transaction (conflicting files)
mingw-w64-x86_64-lua: /mingw64/bin/lua exists in filesystem
mingw-w64-x86_64-lua51: /mingw64/bin/lua5.1 exists in filesystem
Errors occurred, no packages were upgraded.
```

I first tried to fix the issue by removing the lua51 package. The line with lua51 didn't show up next time I ran pacman -Su, but the other one did.

The errors were resolved by first checking if any packages owned these files:
```
$ pacman -Qo /mingw64/bin/lua
```

This said that no packages owned it, so I deleted the file and the upgrade worked. Something's wrong with the lua packages...

**Comment by Alexpux** [comment]
This is known issue. You need first upgrade lua package with '--force'' flag and then upgrade other packages.

**Comment by athairus** [comment]
Is this documented anywhere? There's no way I could have known that...

**Comment by Alexpux** [comment]
I'm answer to you yesterday on IRC but you left it before. 
Will add to issues here
https://sourceforge.net/p/msys2/wiki/MSYS2%20installation/

**Comment by elieux** [comment]
Added: https://sourceforge.net/p/msys2/wiki/MSYS2%20installation/
