### ISSUE TITLE
mingw-w64-lz4

### ISSUE THREAD

**Issue by psteinb** [Alexpux/MINGW-packages#538]
Just tried to build lz4 and got this on W7 64bit Enterprise:

```
svn: E205000: syntax error in revision argument '1.5.0.r127'
==> ERROR: Failure while downloading lz4 svn repo
```

Can I simply change the value of pkgver on
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-lz4/PKGBUILD#L5 ?

Also, lz4 has moved to github
https://github.com/Cyan4973/lz4
but I am unclear how to change PKGBUILD accordingly!

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/541d0da31a4d2e648689655e49ddfffbe7ff5dfe

**Comment by psteinb** [comment]
thanks
