### ISSUE TITLE
cmake fails to load libstdc++-6.dll

### ISSUE THREAD

**Issue by ekpyron** [Alexpux/MINGW-packages#544]
Since today trying to run cmake (both from mingw-w64-x86_64-cmake and from mingw-w64-x86_64-cmake-git) gives me the following:

    $ cmake
    /mingw64/bin/cmake.exe: error while loading shared libraries: libstdc++-6.dll: cannot open shared object file: No such file or directory

This happens although libstdc++-6.dll seems to be present and intact:

    $ which libstdc++-6.dll
    /mingw64/bin/libstdc++-6.dll

    $ file /mingw64/bin/libstdc++-6.dll
    /mingw64/bin/libstdc++-6.dll: PE32+ executable (DLL) (console) x86-64 (stripped to external PDB), for MS Windows

The problem exists since I updated MSYS2 today and does also appears in a clean reinstall of MSYS2. I didn't yet check whether anything else depending on libstdc++-6.dll is affected.

UPDATE:
A simple test application depending on libstdc++-6.dll works just fine, so I suppose the problem is somewhere in cmake - rebuilding mingw-w64-x86_64-cmake[,-git] from the PKGBUILD doesn't help, though.

**Comment by Alexpux** [comment]
Itself ````libstdc++-6.dll```` depends on ````libgcc_s_seh-1.dll```` and ````libwinpthread-1.dll````. So maybe you miss one of them or it breaked somehow. Try open ````cmake.exe```` in dependency walker and see if all required dll's present

**Comment by ekpyron** [comment]
$ ldd /mingw64/bin/libstdc++-6.dll
          ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ff83a800000)
          KERNEL32.DLL => /c/Windows/system32/KERNEL32.DLL (0x7ff839d60000)
          KERNELBASE.dll => /c/Windows/system32/KERNELBASE.dll (0x7ff837ad0000)
          libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x61440000)
          msvcrt.dll => /c/Windows/system32/msvcrt.dll (0x7ff83a190000)
          libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x64940000)
          USER32.dll => /c/Windows/system32/USER32.dll (0x7ff83a010000)
          GDI32.dll => /c/Windows/system32/GDI32.dll (0x7ff839a00000)
          IMM32.DLL => /c/Windows/system32/IMM32.DLL (0x7ff839cc0000)
          MSCTF.dll => /c/Windows/system32/MSCTF.dll (0x7ff839b60000)

Actually that looks fine - and as I said a simple test application depending on libstdc++-6.dll does work just fine... "ldd /mingw64/bin/cmake.exe" does seem to hang forever, though...

Anyways if the problem is not reproducable elsewhere I'll try to figure out what might be wrong on my system...

**Comment by Alexpux** [comment]
As I told, you need to check dependencies of cmake executable itself not libstdc++

**Comment by ekpyron** [comment]
As I said - "ldd /mingw64/bin/cmake.exe" just hangs forever, so there's definitely something wrong there, though not just a missing dependency, because that shouldn't cause "ldd" to crash either :-).

**Comment by Alexpux** [comment]
Can you run ````cmake.exe```` from CMD and see what error it show you?

**Comment by ekpyron** [comment]
Yes, that produced something more meaningful - it seems cmake.exe is linked against libhogweed-2-5.dll, but currently there is only libhogweed-4-0.dll present (part of mingw-w64-x86_64-nettle)...

Surprisingly rebuilding cmake locally on my system didn't help, so I'll try to rebuild nettle first and then cmake again and see whether that helps...

**Comment by Alexpux** [comment]
I see issue. Need rebuild ````gnutls```` and ````rtmpdump```` packages.

**Comment by ekpyron** [comment]
OK, I'll try that...

**Comment by ekpyron** [comment]
checking for NETTLE... no
    configure: error:
      ***
      *** Libnettle 2.7.1 was not found. Note that this version of gnutls doesn't support nettle 3.0.

Rebuilding gnutls doesn't seem well possible either right now, but the problem indeed seems to lie here - I'll see whether I can update the gnutls PKGBUILD to version 3.4.0...

**Comment by Alexpux** [comment]
You need build new gnutls-3.4.0

**Comment by Alexpux** [comment]
I try to build it now but have some problems

**Comment by ekpyron** [comment]
If you're also experiencing the error in their "sanitized" version of time.h - I just wrote a patch that removes it entirely, so that gnutls falls back to the system time.h (http://pastebin.com/mpY7Bp8U), but I'm still getting "undefined reference" errors to __imp_gnutls_free, etc. in the end - I'll let you know if I succeed in building gnutls-3.4.0...

**Comment by ekpyron** [comment]
I put together a working PKGBUILD for gnutls-3.4.0 in my fork of MINGW-packages. With that and after rebuilding rtmpdump and curl finally cmake works again.
I created a pull request with the changes I made to get gnutls to build.

**Comment by Alexpux** [comment]
I'm comment on pull request. But your patch is wrong sorry

**Comment by Alexpux** [comment]
Remove please part of upgrading gnutls and just add new package.

**Comment by ledvinap** [comment]
(for people ending here searching for similar problem):
Using `strace` on failing program (`strace cmake`) will show dialog box with actual dll that is missing.
