### ISSUE TITLE
nettle update broke curl

### ISSUE THREAD

**Issue by dscho** [Alexpux/MINGW-packages#549]
The recent major version jump (mingw-w64-$ARCH-nettle-2.7.1-3 to mingw-w64-$ARCH-nettle-3.1-1) completely messed up curl. It now says: `error while loading shared libraries: ?: cannot open shared object file: No such file or directory`.

This is probably the same problem as #544 although with a completely different problem (and more worrisome because it affects users, not only developers who want to build anything).

**Comment by Alexpux** [comment]
Be patient, I know this issue.

**Comment by dscho** [comment]
> Be patient, I know this issue.

Oh good. Thanks for being on it!

**Comment by Alexpux** [comment]
Fixed.

**Comment by BangLy** [comment]
[githubflow-online.pdf](https://github.com/Alexpux/MINGW-packages/files/1053459/githubflow-online.pdf)
