### ISSUE TITLE
rebuild needed for gedit/gedit plugins

### ISSUE THREAD

**Issue by DoctorWho11** [Alexpux/MINGW-packages#550]
I don't think it affects gedit itself as more of gedit plugins, but with the recent gnutls update gedit complains about gnutls, so I am guessing it will need a rebuild
EDIT: actually gio so technically it's a libglib rebuild.

**Comment by Alexpux** [comment]
I'm rebuild glib-networking. Is it fix your issue?

**Comment by DoctorWho11** [comment]
It does indeed. Issue is now closed.
