### ISSUE TITLE
qt5-static doesn't work

### ISSUE THREAD

**Issue by xylosper** [Alexpux/MINGW-packages#558]
After I updated qt5-static from 5.4.1-1 to 5.4.1-3, I can't build with qt5-static anymore.
It seems some wrong absolute path is hardcoded through entire package.
For instance, QtCreator tries to find mkspec in wrong path and prints next error:

>Cannot read C:/repo/mingw-w64-qt5-static/pkg/mingw-w64-x86_64-qt5-static/mingw64/qt5-static/share/qt5/mkspecs/win32-g++/qmake.conf: No such file or directory

Right path in my system is  `C:/msys64/mingw64/qt5-static/share/qt5/mkspecs/win32-g++/qmake.conf`.

**Comment by Alexpux** [comment]
Reinstall it, seems patcher not patch files properly. Or you can fix it by hand:
````
cd /mingw64/bin
qtbinpatcher --force --nobackup
````

**Comment by xylosper** [comment]
It seems working. Thank you!
