### ISSUE TITLE
stat() does not recognize unix form of paths

### ISSUE THREAD

**Issue by eternalNight** [Alexpux/MINGW-packages#568]
The following code snippet:

    int main() {
    	struct stat buf;
    	char *path_unix = "/usr/bin/ls.exe";
    	char *path_win = "D:/msys64/usr/bin/ls.exe";
    	int ret_unix, ret_win;
    
    	ret_unix = stat(path_unix, &buf);
    	ret_win = stat(path_win, &buf);
    
    	printf("returns %d %d\n", ret_unix, ret_win);
    	return 0;
    }

prints "returns -1 0" instead of "returns 0 0". Is stat() expected to accept paths in windows form only? Thanks.

**Comment by Alexpux** [comment]
You can't use UNIX paths with mingw applications.

**Comment by eternalNight** [comment]
Some applications compile the installation path (e.g. /mingw64/lib or so) into the binary and look for its library files via stat(). What is the best known method to fix this issue on mingw?

**Comment by Alexpux** [comment]
You need patch such applications to relocate paths.
@mingwandroid  wrote universal procedures to do it. Look into https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-pathtools.
Examples of using them you can see in patches for **p11-kit, hunspell** and others.

**Comment by eternalNight** [comment]
Got it. Thanks!
