### ISSUE TITLE
 GnuTLS and emacs

### ISSUE THREAD

**Issue by podiki** [Alexpux/MINGW-packages#573]
The latest GnuTLS is not recognized by the latest emacs package, although both install fine. This is upstream [bug #20294](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=20294) and fixed with this [commit](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=dc79845aac339db1cdcbbfc48d8f1569ed9a5aa2). Unfortunately right now that means GnuTLS won't work with emacs (breaking things like package downloading, or tools like cask), and even the current mingw (64bit) git version of emacs does not have the fix. I'm not sure what the procedure here is, but since this is a Windows specific bug that has been fixed, I hope the package here can be updated soon.

**Comment by elieux** [comment]
I just tried building `emacs-git` and it seems to work. @Alexpux, can you build and upload `emacs-git`?

@podiki, if you're impatient, you can try my build: https://dl.dropboxusercontent.com/u/59899181/mingw-w64-x86_64-emacs-git-r121100.b591977-1-any.pkg.tar.xz

**Comment by podiki** [comment]
I'll give `emacs-git` another shot when I get back to my Windows box tonight and report back. I don't mind waiting if there will be a normal bugfix release for 24.5 soon (or some update), but I suspect I won't be alone in having problems since this seems to break the package system (trying `package-list-packages` completely hangs emacs for me). Ideally there would be an update to emacs without having to package some intermediate version.

As a temporary workaround, I think copying `libgnutls-30.dll` to `libgnutls-28.dll` in the `bin` directory (the older version was no longer there) worked fine for me (which means emacs was built against this newest gnutls?). Of course it's best not to do these sort of things, as presumably that could break something that relies on the older version, which shouldn't be binary compatible.

**Comment by Alexpux** [comment]
emace and emacs-git are rebuilded and uploaded to repo two days ago. I wonder why you not update them

**Comment by podiki** [comment]
@elieux
Your package does seem to work with GnuTLS 3.4, although I run into other errors with installing packages. Probably this is some emacs 25 thing, or because of all the mucking about I've been doing (I just looked quickly, didn't dig into it as it's not relevant). I'll be staying on 24.5 for now.

@Alexpux 
I have been using the latest packages, which are from 4 days ago according to this repo, and `emacs-git` has the same issue. There is no problem with installing or running, but if you try, e.g. `M-: (gnutls-available-p)` in emacs, you get `nil` rather than `t`. Trying `cask install` in `~/.emacs.d` to install packages in a new version fails with `gnutls.c: [1] (Emacs) GnuTLS library not found` (unless for some reason gnutls-28.dll still exists, but I only have gnutls-30.dll after latest updates).

Anyway, I know how to work around it, and I guess whenever the next update for the emacs packages comes it will have the bugfix. I just wanted people to be aware, since this (for me, at least) breaks the emacs package system, and probably anything else relying on specifically having the gnutls-28.dll library.

**Comment by elieux** [comment]
@Alexpux, the `emacs-git` available in our repo is revision emacs-mirror/emacs@a2940cd. The commit that fixes GnuTLS is emacs-mirror/emacs@dc79845 and as you can see in the [commit history](https://github.com/emacs-mirror/emacs/commits/dc79845), our build doesn't contain the fix (it was commited one day later).
