### ISSUE TITLE
qt5: CMAKE_AUTOSTATICPLUGINS in effect with dynamic qt

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MINGW-packages#577]
I enabled `CMAKE_AUTOSTATICPLUGINS` globally and unconditionally in my `CMakeLists.txt` to get its advantages on a static build. But due to the recent sync of patches from `qt5-static` it tries to link to the static plugins for the dynamic Qt too. 
I think this is undesirable.

**Comment by Alexpux** [comment]
Does it work properly with latest package?

**Comment by Optiligence** [comment]
No. I even unintalled qt5-static to make sure.

**Comment by mingwandroid** [comment]
This really should be fixed! I will try to find time to check it tomorrow. Perhaps putting it in the  core CMake file for qt5-static would be a workaround?

Out of interest what file food you put it in?

**Comment by Optiligence** [comment]
As long as there’s no use case in linking just a fraction of all available plugins, putting it in the qt cmake config sounds like a good solution in general. 

>Out of interest what file food you put it in?

hm?

**Comment by mingwandroid** [comment]
What file did you put it in... Predictive miscorrection.

**Comment by Optiligence** [comment]
> globally and unconditionally in my CMakeLists.txt
I have only one.

**Comment by Optiligence** [comment]
bump

**Comment by mingwandroid** [comment]
To enable `CMAKE_AUTOSTATICPLUGINS` globally, which file did you put it into?

**Comment by Optiligence** [comment]
Into the one and only `CMakeLists.txt` of the respective projects. 
Globally meaning not as a property of a specific target.

**Comment by mingwandroid** [comment]
When mingw-w64-{i686,x86_64}-qt5{,-static}-5.5.1-3 are release this should be fixed. I'll close it at that stage (or someone should!)

**Comment by Optiligence** [comment]
thx
