### ISSUE TITLE
Missing package dependency: blender requires SDL2.dll

### ISSUE THREAD

**Issue by DavidEGrayson** [Alexpux/MINGW-packages#580]
After I installed the mingw64-x86_64-blender package (version 2.71-1) in MSYS2 and tried to run it in the Win64 shell by typing `blender`, it didn't appear to do anything and just exited immediately with a return code of 0.  Then I tried running `strace blender` and it displayed a message box about how SDL2.dll could not be found.   I solved this problem by installing mingw64-x86_64-SDL2.

The message box said:

> blender-app.exe - System Error
> The program can't start because SDL2.dll is missing from your computer.  Try reinstalling the program to fix this problem.

I haven't looked into the details, but I assume that SDL2 should be added to the depends list of the [blender package](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-blender/PKGBUILD).  (Alternatively, maybe the intention was to build blender so that it doesn't require SDL2, and the latest build was done incorrectly.)

P.S. What's the protocol for reporting bugs around here?  Should I open a ticket on sourceforge for this?  Should I submit a pull request?

**Comment by Alexpux** [comment]
Fixed in 2.74-2
