### ISSUE TITLE
Upgrade to GCC 5.1

### ISSUE THREAD

**Issue by CoolOppo** [Alexpux/MINGW-packages#585]
GCC 5.1 was released! When it's possible, please upgrade the package to the latest version. Thanks.

**Comment by oysteinkrog** [comment]
This is quite rude.

**Comment by CoolOppo** [comment]
I wasn't trying to be rude. In fact, I tried to take extra care not to sound like a dick, but I failed at that apparently. It's really just a suggestion for something nice to have.

**Comment by oysteinkrog** [comment]
Ok, in that case I'm sorry, for I was.
Please consider that the maintainers spend a lot of time working in and around gcc and mingw, and as such I'm pretty sure that they all know _very_ well that gcc 5.1 has been released :)

**Comment by CoolOppo** [comment]
yes of course they do! Yet, the issue wasn't created yet, so I made it,
because somebody probably would've done it anyways.

**Comment by Alexpux** [comment]
Currently we have troubles building 32-bit gcc-5.1.0.

**Comment by CoolOppo** [comment]
If anybody is interested, the [nuwen.net MinGW Distro](http://nuwen.net/mingw.html) is updated with GCC 5.1.0

**Comment by nyfair** [comment]
Hmm, you can just ship 64-bit version first just like what those Archlinux package maintainers always do, right?

**Comment by Alexpux** [comment]
No, I don't want to provide different versions of packages for 32 and 64 bit.
If you need it - you can build 64-bit package yourself and install it.

**Comment by Alexpux** [comment]
Temporary I'm create MINGW_test repo where I'm rebuild everything with gcc-5.1.0
https://sourceforge.net/projects/msys2/files/REPOS/MINGW_Test/
