### ISSUE TITLE
Building python2 stops with segmentation fault.

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#588]
I am building Python 2.7.9 on x86_64 manually (following the steps in the pkgbuild), and the build abruptly stops with the message:

```
/bin/sh: line 6:  7152 Segmentation fault      CC='x86_64-w64-mingw32-gcc' LDSHARED='x86_64-w64-mingw32-gcc -shared -Wl,--enable-auto-image-base ' OPT='-DNDEBUG ' _TCLTK_INCLUDES='' _TCLTK_LIBS='' ./python.exe -E ./setup.py $quiet build
Makefile:496: recipe for target 'sharedmods' failed
make: *** [sharedmods] Error 139
```

The only real differences my builds have are shared ncurses and readline linked to that.

[Full make output up to the crash](https://gist.github.com/BrisingrAerowing/7aa8caf6e3ca73bfa319)

**Comment by BrisingrAerowing** [comment]
I am going to try rebuilding readline with termcap and see if that fixes the issue.

**Comment by BrisingrAerowing** [comment]
[Output from python with -v -v -v](https://gist.github.com/BrisingrAerowing/f586449ccecc2dd8398c)

It crashes trying to find win32api.

**Comment by Alexpux** [comment]
We don't build ncurses as shared as Python crash building curses module.

**Comment by BrisingrAerowing** [comment]
Weird. I wonder why.

I ended up deleting the builds I had and using some packages. Now I have an error with GObject-Introspection. I will put that in a separate ticket.
