### ISSUE TITLE
GObject-Introspection Syntax Error when building GLib-2.0.gir

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#589]
I get a long list of errors when  building GObject-Introspection similar to the ones below:

```
C:\msys64\mingw64\include\glib-2.0\glib\glib-autocleanups.h:35: syntax error, unexpected typedef-name, expecting identifier or '(' in 'typedef GAsyncQueue *GAsy' at 'GAsyncQueue_autoptr'
C:\msys64\mingw64\include\glib-2.0\glib\glib-autocleanups.h:36: syntax error, unexpected typedef-name, expecting identifier or '(' in 'typedef GBookmarkFile *GB' at 'GBookmarkFile_autoptr'
C:\msys64\mingw64\include\glib-2.0\glib\glib-autocleanups.h:37: syntax error, unexpected typedef-name, expecting identifier or '(' in 'typedef GBytes *GBytes_au' at 'GBytes_autoptr'
C:\msys64\mingw64\include\glib-2.0\glib\glib-autocleanups.h:38: syntax error, unexpected typedef-name, expecting identifier or '(' in 'typedef GChecksum *GCheck' at 'GChecksum_autoptr'
```
These go on and on down the screen.

Is there something I missed, or is there some weird issue here?

I am sure I applied all the patches, but I will try doing them one-by-one and see if I missed something.

**Comment by mingwandroid** [comment]
Does makepkg-mingw not work for you?

**Comment by BrisingrAerowing** [comment]
I have been doing the builds manually as I am using some slightly different configure options (mostly just related to paths, e.g. I am not putting things from sbin into bin).  I am rebuilding a number of things now, and I haven't gotten to this package yet.

I was using a newer GLib version than the one in the GLib PKGBUILD, and I am currently using the version you guys are (the latest has a number of build issues with GCC 5.1.0)

I had to remove -Werror=format=2 from the GLib configure script as the build will fail with GCC 5.1.0 (but it works with 4.9.2! :confounded: )

**Comment by mingwandroid** [comment]
Well, I meant that perhaps you could compare vs the PKGBUILD we provide. Clearly you're forging your own path here, which is cool, but you aren't really reporting a bug against MSYS2's gobject-introspection here that we can investigate.

So I guess upstream might be a better place for such a bug report?

**Comment by BrisingrAerowing** [comment]
Ah, I see what you mean now. I will do so if I get the error this time.

**Comment by mingwandroid** [comment]
Ok, closing this then.

**Comment by BrisingrAerowing** [comment]
I figured out something some time ago, but never posted it. I was using the latest (at the time) version of GLib (which was 2.45.x), while you guys were using 2.44.x. Switching to that worked. Not sure why, though.
