### ISSUE TITLE
Please package expect (tcl-based tool)

### ISSUE THREAD

**Issue by andreygursky** [Alexpux/MINGW-packages#591]
Source: http://sourceforge.net/projects/expect. If it's not trivial, please post here details.

Thanks,
Andrey

**Comment by Alexpux** [comment]
feel free to contribute PKGBUILD for it

**Comment by elieux** [comment]
Relevant resources on our wiki:
- http://sourceforge.net/p/msys2/wiki/Porting/
- http://sourceforge.net/p/msys2/wiki/Contributing%20to%20MSYS2

**Comment by Alexpux** [comment]
Packaged as msys-package.
