### ISSUE TITLE
Python 3.4 Build Error

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#598]
I get a runtime error stating "Dictionary size changed during iteration"

I tracked it down to code added by [this patch](https://github.com/Alexpux/MINGW-packages/blob/c40c165d61c0392da729a82edc8939e4a54cfe15/mingw-w64-python3/0610-msys-cygwin-semi-native-build-sysconfig.patch)

The code is as follows:

```python
  for k, v in done.items():
      if isinstance(k, str):
          if k.endswith("_b2h"):
```

which fails.

I changed it to 

```python
for k, v in dict(done).items():
        if isinstance(k, str):
            if k.endswith("_b2h"):
```

which works.

I am not sure why it works for you guys, but this should help anyone having this issue.

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/c96c4262443a8c96dcfa7ed2a40cb78ac16a63ec
 Uploaded new packages.
