### ISSUE TITLE
Does libwinpthread  have a static version?

### ISSUE THREAD

**Issue by rexdf** [Alexpux/MINGW-packages#604]
I build filezilla in msys2. After a few patches, everything goes well.

But it depends on (and only on) `/mingw32/bin/libwinpthread-1.dll`. I know MingW-w64 gcc has threads-win32  version and threads-posix version. Filezilla offically suggests threads-win32 of MingW-w64. 

I build it using MingW-W64 threads-win32,too. It has no dependencies.

**Comment by Alexpux** [comment]
Our mingw-w64 toolchains are builded with ````threads=posix```` so it pull dependency from libwinpthread-1.dll. You can link with static libwinpthread library only if you link filezilla statically
