### ISSUE TITLE
GLib version bug.

### ISSUE THREAD

**Issue by jeandudey** [Alexpux/MINGW-packages#621]
I'm using glib installed from the official MSYS2 repository and it shows that i
have the version 2.44.0-1 and the same with `pkg-config glib-2.0 --modversion`.

But the error happens when i use glib with gcc and compile a program like this:
```
#include <glib.h>
#include <gio/gio.h>

int main(int argc, char **argv)
{
        GFile *file = NULL;

        file = g_file_new_for_path("afile.txt");

        g_object_unref(file);

        return 0;
}
```

It compiles successfully but when i run it i get these errors:
```
(main.exe:4196): GLib-GObject-CRITICAL **: gtype.c:2720: You forgot to call g_type_init()

(main.exe:4196): GLib-CRITICAL **: g_once_init_leave: assertion `result != 0' failed

(main.exe:4196): GLib-GObject-CRITICAL **: gtype.c:2720: You forgot to call g_type_init()

(main.exe:4196): GLib-CRITICAL **: g_once_init_leave: assertion `result != 0' failed
```
The errors shows me that i have to call g_type_init() in the program but it's
deprecated since the version 2.36 of glib but i have the version 2.44.0-1.

So what's happening?

**Comment by Alexpux** [comment]
I think you need ask Glib developers. This is not our issue.
I think that ````call g_type_init```` is deprecated but not yet removed from codebase.

**Comment by jeandudey** [comment]
I will ask to the GLib develepers.
