### ISSUE TITLE
ImageMagick configuration broken ?

### ISSUE THREAD

**Issue by fpopineau** [Alexpux/MINGW-packages#622]
It doesn't list the known formats:
```
$ identify -list format
   Format  Module    Mode  Description
-------------------------------------------------------------------------------

* native blob support
r read support
w write support
+ support for multiple images
$
It is able to list configure and delegates however and convert is able to do some conversions.
$ pacman -Qen | grep magick
mingw-w64-x86_64-imagemagick 6.9.0.7-1
```
Any idea of what's going on ?
Thanks.

**Comment by Alexpux** [comment]
We try to relocate PATH's for Imagemagick to get it working from any location:
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-imagemagick/001-relocate.patch

Maybe need more work, but I have no time for it now.

**Comment by fpopineau** [comment]
There is a bug in magick/nt-base.c that led to this situation: opendir() on the module directory fails without this patch:
$ diff -u magick/nt-base.c~ magick/nt-base.c
--- magick/nt-base.c~   2015-02-22 22:02:34.000000000 +0100
+++ magick/nt-base.c    2015-05-12 13:31:02.627609000 +0200
@@ -1625,12 +1625,16 @@
   wchar_t
     file_specification[MaxTextExtent];

+  wchar_t WCDirectorySeparator[strlen(DirectorySeparator)+1];
+  MultiByteToWideChar(CP_UTF8,0,DirectorySeparator,-1,WCDirectorySeparator,
+                     strlen(DirectorySeparator)+1);
+
   assert(path != (const char *) NULL);
   length=MultiByteToWideChar(CP_UTF8,0,path,-1,file_specification,
     MaxTextExtent);
   if (length == 0)
     return((DIR *) NULL);
-  if(wcsncat(file_specification,(const wchar_t*) DirectorySeparator,
+  if(wcsncat(file_specification, WCDirectorySeparator,
        MaxTextExtent-wcslen(file_specification)-1) == (wchar_t*) NULL)
     return((DIR *) NULL);
   entry=(DIR *) AcquireMagickMemory(sizeof(DIR));


It is a bit crude, but at least it fixes it.
I don't even know how it could work with the native distribution of ImageMagick.

**Comment by maoueh** [comment]
@fpopineau You will need to use a code block (indent by 4 spaces or surround with triple backticks ```), because right now, your diff is interpreted as markdown code and render weirdly :)

**Comment by mingwandroid** [comment]
Please clone this repository and then submit this as a pull request. Don't forget to bump the pkgrel

**Comment by Alexpux** [comment]
I'm building new version of Imagemagick now (4.9.1.x). Don't do pull request

**Comment by fpopineau** [comment]
Thanks. And now Gnu Emacs is able to actually use ImageMagick :-)

**Comment by mingwandroid** [comment]
I must check this emacs thing out one day.

**Comment by fpopineau** [comment]
Gnu Emacs builds out of the box these days on mingw64. Either 24.5 or the Git version.

**Comment by Alexpux** [comment]
New packages uploaded.
