### ISSUE TITLE
Does pkg-config really need the dependency on GLib?

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#623]
The pkg-config PKGBUILD uses the `--with-internal-glib` configure switch, which causes pkg-config to use its bundled copy of GLib and ignore any external versions, which indicates that the dependency on external GLib is superfluous and can be removed.

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/41b67e22ff3ef5d2731c17a9cae8635f7d431d58
