### ISSUE TITLE
mingw-w64-i686-glib2 failed install due to virus warning

### ISSUE THREAD

**Issue by limerix** [Alexpux/MINGW-packages#625]
I'm new to msys2 and was playing around with pacman, when this failed:

```
$ pacman -S mingw-w64-i686-glib2
[...]
error: mingw-w64-i686-glib2: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is invalid
:: File /var/cache/pacman/pkg/mingw-w64-i686-glib2-2.44.1-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
```

it seems the download was no xz file but a html page saying

```
Bitdefender Antivirus Free Edition has blocked a page!
Malware detected!
Access to this page has been blocked.
I understand the risks, take me there anyway
```

So my antivirus BitDefender blocked it. I downloaded the file (nervously) and uploaded to virustotal.com. It reports malware (Gen:Variant.Adware.SMSHoax) by 6 of 56 AV programs.

https://www.virustotal.com/sv/file/85ba022926f106df5b32ab912778e427fc70d5d0862cb267392a6a486394715f/analysis/1431862020/

Could be false positives of course. I'm just reporting it here if others get same error.

**Comment by elieux** [comment]
It wouldn't be the first false positive we got. Can you submit the file as a false positive using your BitDefender? (I've heard anti-virus vendors take care to respond to their customers, but not so much to "random" developers.)

**Comment by limerix** [comment]
Good idea. I've did that now, and I'll report the outcome.

**Comment by limerix** [comment]
Forgot to report back: BitDefender eventually fixed this. It was a false positive.
