### ISSUE TITLE
libmicrohttpd

### ISSUE THREAD

**Issue by sl1200mk2** [Alexpux/MINGW-packages#629]
Hi,
any chance to got a package for libmicrohttpd?
thank you,
best regards,
nicolas

**Comment by mingwandroid** [comment]
Yes, if you make the PKGBUILD and submit a pull request there is a good chance!

**Comment by sl1200mk2** [comment]
Hi,
in fact I'm facing problem compiling this lib...
so it was more or less to know if you would succeed compiling it.

best regards,
nicolas

**Comment by mingwandroid** [comment]
Please share your work-in-progress PKGBUILD and patches and I will take a look later.

**Comment by sl1200mk2** [comment]
well PKGBUILD is nowhere for now... but here's the error (for both 32 & 64) in case it talks to you.
libtool: link: (cd .libs/libmicrohttpd.lax/libplatform_interface.a && ar x "/c/Users/nico/dev/dlight/win32/libmicrohttpd-0.9.42/src/microhttpd/../../src/platform/.libs/libplatform_interface.a")
libtool: link: object name conflicts in archive: .libs/libmicrohttpd.lax/libplatform_interface.a//c/Users/nico/dev/dlight/win32/libmicrohttpd-0.9.42/src/microhttpd/../../src/platform/.libs/libplatform_interface.a
Makefile:774: recipe for target 'libmicrohttpd.la' failed
make[3]: *** [libmicrohttpd.la] Error 1

thanx

**Comment by mingwandroid** [comment]
Having a PKGBUILD would lower the effort-barrier enough for me to investigate this.

**Comment by sl1200mk2** [comment]
Hi,
following is start of PKGBUILD for libmicrohttpd
there's gnutls and libgcrypt as depencies, but crypto stuff for libmicrohttpd doesn't interrest me.
so when I try to compile, I pass --disable-https to not depend on libgcrypt nor gnutls.
thanks for your help,
best regards

_realname=libmicrohttpd
pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
pkgver=0.9.42
pkgrel=1
pkgdesc="GNU libmicrohttpd is a small C library that is supposed to make it easy to run an HTTP server as part of another application"
arch=('any')
url=http://www.gnu.org/software/libmicrohttpd/"
license=("LGPL")
makedepends=("${MINGW_PACKAGE_PREFIX}-gcc" "${MINGW_PACKAGE_PREFIX}-pkg-config")
depends=('gnutls' 'libgcrypt')
source=("http://ftp.gnu.org/gnu/libmicrohttpd/${_realname}-${pkgver}.tar.gz")
md5sums=('3b9cf0b67fc8ebc9e69f53c6bc84a88d')

build() {
  mkdir -p ${srcdir}/build-${MINGW_CHOST} && cd ${srcdir}/build-${MINGW_CHOST}
  ../${_realname}-${pkgver}/configure \
    --prefix=${MINGW_PREFIX} \
    --build=${MINGW_CHOST} \
    --host=${MINGW_CHOST} \
    --enable-shared \
    --enable-static

  make
}

package() {
  cd "${srcdir}/build-${MINGW_CHOST}"
  make DESTDIR="$pkgdir" install
}

**Comment by Alexpux** [comment]
I'm build libmicrohttpd without any problems. Will upload this packages today.

**Comment by Alexpux** [comment]
Here is PKGBUILD:
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-libmicrohttpd/PKGBUILD

**Comment by sl1200mk2** [comment]
thanx guys,
will try as soon as I can

best regards,
nicolas

**Comment by sl1200mk2** [comment]
thanx for you work about this.
++
Nicolas
