### ISSUE TITLE
Package request: libportmidi

### ISSUE THREAD

**Issue by j3ffhubb** [Alexpux/MINGW-packages#638]
Hello,

I'd like to request that [Portmidi](http://sourceforge.net/projects/portmedia/?source=navbar) (cross-platform C library for interfacing with MIDI hardware) be added to the repositories.  There is an optional bundled GUI application that has a Java dependency, IMHO that component could be omitted and just package the libportmidi dll and headers.

Thanks

**Comment by elieux** [comment]
Did you try building portmidi in MSYS2 with mingw-w64? If yes, was it successful?

**Comment by j3ffhubb** [comment]
Hello,

Portmidi advertises mingw support.  I have not been successful in trying to compile it without the Java dependency (although that may be because I'm not very familiar with CMake).  I can install Java and try to compile it the normal way, but that wouldn't be much help for creating a PKGBUILD since Java isn't available in the repos.

I found [these notes](http://chrisarndt.de/projects/portmidizero/INSTALL-windll.txt) on how to autotool-ize Portmidi and compile without CMake, but I haven't tried it yet.

**Comment by elieux** [comment]
I prepared a PKGBUILD in #643. Let's move the discussion there.
