### ISSUE TITLE
Package request: Rubberband

### ISSUE THREAD

**Issue by j3ffhubb** [Alexpux/MINGW-packages#639]
Hello,

I'd like to request that [Rubberband](http://breakfastquay.com/rubberband/) (a C++ library and CLI for performing independent time-stretching and pitch-shifting of audio) be added to the repos.

Thanks

**Comment by Alexpux** [comment]
The faster method is to provide PKGBUILD for it. In other case need someone who will do it for you.

**Comment by j3ffhubb** [comment]
I'll try to create a PKGBUILD some time this weekend.

**Comment by j3ffhubb** [comment]
I was able to successfully compile Rubberband using MSYS2.  It depends on 2 packages already in the repos, and one package that is not (Vamp-SDK).  I'll put together PKGBUILDs for Rubberband and Vamp-SDK and submit a pull request.

**Comment by j3ffhubb** [comment]
Closing this issue, pull request [#646](https://github.com/Alexpux/MINGW-packages/pull/646) created
