### ISSUE TITLE
Missing package dependency: gimp depends on json-glib

### ISSUE THREAD

**Issue by DavidEGrayson** [Alexpux/MINGW-packages#656]
This is similar to my [previous issue](https://github.com/Alexpux/MINGW-packages/issues/580) but with different packages.

If I install mingw-w64-x86_64-gimp and run "gimp" in the shell, it prints this (non-fatal) error:

> GEGL-C:/git/MINGW-packages/mingw-w64-gegl-git/src/gegl/gegl/module/geglmodule.c-Message: Module 'C:\msys64\mingw64\lib\gegl-0.3\json.dll' load error: 'C:\msys64\mingw64\lib\gegl-0.3\json.dll': The specified module could not be found.

A similar error is displayed in a message box if you run gimp by double-clicking on the executable.

I found that installing mingw-w64-x86_64-json-glib fixed these error messages.

**Comment by mingwandroid** [comment]
Any chance you can make a pull request that fixes this?

**Comment by DavidEGrayson** [comment]
Sure, I'll look into it.  I'm not immediately sure if json-glib needs to be a dependency of gimp itself or some other package that gimp depends on.

**Comment by mingwandroid** [comment]
Thanks. I think gegl-git package might be the one carrying that dependency. I'm really busy with my job or else I would investigate more, but for what it's worth, I launched gimp 64 bit just fine last night without the json package installed, which is strange. Process hacker 2 is invaluable for seeing what DLLs are loaded by a given process too.

**Comment by mingwandroid** [comment]
pactree and ldd should also prove useful.

**Comment by DavidEGrayson** [comment]
A DLL from the gegl-git package (json.dll) does depend on libjson-glib:

~~~~
$ ldd /mingw64/lib/gegl-0.3/json.dll | grep json
        libjson-glib-1.0-0.dll => /mingw64/bin/libjson-glib-1.0-0.dll (0x65480000)
~~~~

**Comment by DavidEGrayson** [comment]
It's trivial for me to add json-glib as a dependency to gegl-git.  But I want to make sure that gegl-git can actually compile, so I'll be posting about random issues I have with it and my progress on solving them.  

The first issue is that the `IT_PROG_INTLTOOL(0.40.1)` macro in some autoconf script is not being expanded, so that line appears in a `configure` script and Bash doesn't know how to run it.

**Comment by DavidEGrayson** [comment]
The solution was to install the msys2 package `intltool`.  I will be adding that to the makedepends list.

**Comment by DavidEGrayson** [comment]
I'm seeing some incorrect array-bounds and maybe-uninitialized warnings when I build this package (the mingw64 version).  If someone wants to work on improving the compiler they could look into those warnings.
