### ISSUE TITLE
ConEmu package

### ISSUE THREAD

**Issue by Maximus5** [Alexpux/MINGW-packages#664]
Hi. I'm checking now the ConEmu package and have few questions ATM.
1. Place for ConEmu's binaries is `/opt/bin` folder?
2. I'm going to implement xml search location in `/share/conemu` folder, right?
3. And I suppose, "...ignore-recommended-files-warning.patch" must be removed.

**Comment by Alexpux** [comment]
I think that need to be implemented standard unix-like files structure. If we will configure ````ConEmu```` to be installed into ````/opt```` folder then:
1. Executables/dll's will be in ````/opt/bin````
2. Configuration files need to be in ````/opt/etc/conemu```` or ````/opt/share/conemu````

This is simplest way I think.

About "...ignore-recommended-files-warning.patch" - I will try to build ConEmu directly from your repo without patches.

**Comment by Maximus5** [comment]
Newbie question. How to build 32-bit applications with 64-bit MINGW?

I have MinGW installed in `T:\GitSDK\mingw64`, installed by [git-for-windows](https://github.com/git-for-windows/build-extra). But the folder `T:\GitSDK\mingw32` is almost empty. And when I try to link my 32-bit target, there are a lot of error about missing libs (libkernel32.a and so on).

So, how to install and what packages? What `pacman` command must be issues?

**Comment by Alexpux** [comment]
I don't know what git-for-windows provide. But MSYS2 don't have multilib toolchains so you need instal 32-bit toolchain to build 32-bit applications. It will be installed in to /mingw32 prefix with ````pacman -S ming-w64-i686-toolchain````

**Comment by martell** [comment]
If this is being put in the opt/bin folder it should be built with
mingw-cross and not the mingw-toolchains.
An example of this is the winpty package.

Kindest Regards
Martell

I don't know what git-for-windows provide. But MSYS2 don't have multilib
toolchains so you need instal 32-bit toolchain to build 32-bit
applications. It will be installed in to /mingw32 prefix with pacman -S
ming-w64-i686-toolchain

—
Reply to this email directly or view it on GitHub
<https://github.com/Alexpux/MINGW-packages/issues/664#issuecomment-126952158>
.

**Comment by Alexpux** [comment]
@martell, yeah. We do it currently for consume package: https://github.com/Alexpux/MSYS2-packages/blob/master/mingw-w64-cross-conemu-git/PKGBUILD#L15

**Comment by Alexpux** [comment]
I'm not just update cross-mingw toolchains to gcc5 as it need to be the same as MSYS2 gcc

**Comment by Maximus5** [comment]
After installing `ming-w64-i686-toolchain` build succeeds, thanks.

**Comment by martell** [comment]
I should have known that was there because I wrote it haha.

I thought Maximus5 was building a package for pacman :)

We should probably rename that package to just conemu like how we have
winpty.

How is conemu now btw.
Is it in a state to be used as an optional alternative to mintty in msys2?

Kind Regards
Martell

**Comment by Maximus5** [comment]
I'm trying to switch to minhooks. Temporary branch [br-minhook](https://github.com/Maximus5/ConEmu/tree/br-minhook) is available. But 32bit compilation fails. Can you help me? 64bit compilation succeeds.

    $ mingw32-make.exe -f makefile_gcc DIRBIT=32
    compiling ../modules/minhook/src/hook.c
    In file included from T:/GitSDK/mingw32/lib/gcc/i686-w64-mingw32/4.9.2/include/x86intrin.h:31:0,
                     from T:/GitSDK/mingw32/i686-w64-mingw32/include/intrin.h:73,
                     from ../modules/minhook/src/hook.c:31:
    ../modules/minhook/src/hook.c: In function 'EnterSpinLock':
    T:/GitSDK/mingw32/lib/gcc/i686-w64-mingw32/4.9.2/include/xmmintrin.h:1238:1: error: inlining failed in call to always_inline '_mm_pause': target specific option mismatch
     _mm_pause (void)
     ^
    ../modules/minhook/src/hook.c:444:13: error: called from here
                 _mm_pause();
                 ^
    ../makefile_gcc_target:70: recipe for target '../../gcc/ConEmuHk32mod/hook.o' failed
    mingw32-make.exe: *** [../../gcc/ConEmuHk32mod/hook.o] Error 1
