### ISSUE TITLE
can't compile qt3d

### ISSUE THREAD

**Issue by silentmissile** [Alexpux/MINGW-packages#67]
I just downloaded qt3d from
https://qt.gitorious.org/qt-labs

and followed the README to compile, when I run make, the error message is like this

In file included from ..\..\..\qt3d\src\threed\global\qglnamespace.h:45:0,
                 from ..\..\..\qt3d\src\threed\global\qglnamespace.cpp:42:
..\..\..\qt3d\src\threed\global\qt3dglobal.h:48:19: error: expected constructor, destructor, or type conversion before '(' token
QT_LICENSED_MODULE(Qt3d)
                   ^
In file included from ..\..\..\qt3d\src\threed\global\qglnamespace.cpp:42:0:
..\..\..\qt3d\src\threed\global\qglnamespace.h:156:19: error: 'QSize' does not name a type
     Q_QT3D_EXPORT QSize nextPowerOfTwo(const QSize& value);
                   ^
..\..\..\qt3d\src\threed\global\qglnamespace.cpp:284:45: error: 'QSize QGL::nextPowerOfTwo(const QSize&)' should have been declared inside 'QGL'
QSize QGL::nextPowerOfTwo(const QSize& value)
                                             ^

**Comment by Alexpux** [comment]
Qt3D now in Qt-5.5
