### ISSUE TITLE
mingw-w64-tk installs X11 headers 

### ISSUE THREAD

**Issue by jtanx** [Alexpux/MINGW-packages#677]
The tk package installs X11 headers (e.g. `/mingw64/include/X11/X.h`) which causes conflicts with installing the actual x11proto headers (custom install)

**Comment by Alexpux** [comment]
Don't know how to fix it properly. Maybe you need build your own custom tk package.

**Comment by oscarfv** [comment]
I think that those headers are not needed on Windows. If that is true, we can remove them before creating the package. I hope to have time to look into this later today.

**Comment by oscarfv** [comment]
The header files are used on Windows.

**Comment by jtanx** [comment]
Is it possible to move it to a TK-specific folder? e.g `/mingw64/include/tk8.6/X11`

**Comment by oscarfv** [comment]
Yes, patching the top-level tk headers that include them and adapting the install or the packaging.
