### ISSUE TITLE
mingw-w64-cgal produces incorrect CGALConfig.cmake resulting in broken builds

### ISSUE THREAD

**Issue by donbright** [Alexpux/MINGW-packages#681]
Hello

Thanks for msys2 it is a wonderful project. 

I am having some troubles with package CGAL. I believe it may be related to the way that cgal alters it's own CGALConfig.cmake file during 'cmake/make/make install'. Since the CMAKE_INSTALL_PREFIX set at that time is set to C:/git/MINGW-packages/mingw-w64-cgal/pkg/mingw-w64-x86_64-cgal/ it substitutes that string into the lines of CGALConfig.cmake 

When a 3rd party program attempts to use cmake to Find Package on CGAL, it results in UseCGAL.cmake including this incorrect CGALConfig.cmake

Here is what the start of MSYS2 /mingw64/lib/CGAL/CGALConfig.cmake looks like:

```
set(CGAL_CONFIG_LOADED TRUE)

# CGAL_DIR is the directory where this CGALConfig.cmake is installed
set(CGAL_INSTALL_PREFIX "C:/git/MINGW-packages/mingw-w64-cgal/pkg/mingw-w64-x86_64-cgal/")

set(CGAL_MAJOR_VERSION    "4" )
set(CGAL_MINOR_VERSION    "5" )
set(CGAL_BUILD_VERSION    "1000" )
set(CGAL_SCM_BRANCH_NAME  "")
set(CGAL_GIT_SHA1         "")

set(CGAL_BUILD_SHARED_LIBS        "ON" )
set(CGAL_Boost_USE_STATIC_LIBS    "OFF" )

set(CGAL_CXX_FLAGS_INIT                   "-march=x86-64 -mtune=generic -O2 -pipe  -frounding-math" )
set(CGAL_CXX_FLAGS_RELEASE_INIT           "-O3 -DNDEBUG" )
set(CGAL_CXX_FLAGS_DEBUG_INIT             "-g" )
set(CGAL_MODULE_LINKER_FLAGS_INIT         " -pipe" )
set(CGAL_MODULE_LINKER_FLAGS_RELEASE_INIT "" )
set(CGAL_MODULE_LINKER_FLAGS_DEBUG_INIT   "" )
set(CGAL_SHARED_LINKER_FLAGS_INIT         " -pipe" )
set(CGAL_SHARED_LINKER_FLAGS_RELEASE_INIT "" )
set(CGAL_SHARED_LINKER_FLAGS_DEBUG_INIT   "" )
set(CGAL_BUILD_TYPE_INIT                  "Release" )

set(CGAL_INCLUDE_DIRS  "C:/git/MINGW-packages/mingw-w64-cgal/pkg/mingw-w64-x86_64-cgal/mingw64/include" )
set(CGAL_MODULES_DIR   "C:/git/MINGW-packages/mingw-w64-cgal/pkg/mingw-w64-x86_64-cgal/mingw64/lib/CGAL" )
set(CGAL_LIBRARIES_DIR "C:/git/MINGW-packages/mingw-w64-cgal/pkg/mingw-w64-x86_64-cgal/mingw64/lib" )

```

and here is  what an ordinary CGALConfig.cmake from a linux machine looks like:

```

set(CGAL_CONFIG_LOADED TRUE)

# CGAL_DIR is the directory where this CGALConfig.cmake is installed
set(CGAL_INSTALL_PREFIX "/usr")

set(CGAL_MAJOR_VERSION    "4" )
set(CGAL_MINOR_VERSION    "2" )
set(CGAL_BUILD_VERSION    "1000" )
set(CGAL_SCM_BRANCH_NAME  "")
set(CGAL_GIT_SHA1         "")

set(CGAL_BUILD_SHARED_LIBS        "TRUE" )
set(CGAL_Boost_USE_STATIC_LIBS    "OFF" )

set(CGAL_CXX_FLAGS_INIT                   "-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -frounding-math" )
set(CGAL_CXX_FLAGS_RELEASE_INIT           "-O3 -DNDEBUG" )
set(CGAL_CXX_FLAGS_DEBUG_INIT             "-g" )
set(CGAL_MODULE_LINKER_FLAGS_INIT         " -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed" )
set(CGAL_MODULE_LINKER_FLAGS_RELEASE_INIT "" )
set(CGAL_MODULE_LINKER_FLAGS_DEBUG_INIT   "" )
set(CGAL_SHARED_LINKER_FLAGS_INIT         " -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed" )
set(CGAL_SHARED_LINKER_FLAGS_RELEASE_INIT "" )
set(CGAL_SHARED_LINKER_FLAGS_DEBUG_INIT   "" )
set(CGAL_BUILD_TYPE_INIT                  "Release" )

set(CGAL_INCLUDE_DIRS  "/usr/include" )
set(CGAL_MODULES_DIR   "/usr/lib/CGAL" )
set(CGAL_LIBRARIES_DIR "/usr/lib" )

```

As you can see, the include dir and library dirs are not correct on MSYS2 - in fact those paths dont exist on MSYS2. By hand-alterting the CGALConfig.cmake file in /mingw64/usr/lib/CGAL on msys2 to use a prefix of something like /mingw64/ I was succesfully able to build a project that used find_package(CGAL) from within cmake. 

I would be happy to submit a patch but I am not sure of the best way of going about fixing this. Should it simply alter the CGALConfig.cmake file after the last stage to be correct for MSYS2? I was not able to find much documentation about this situation for CGAL itself.  I believe CGAL is typically installed with CMAKE_INSTALL_PREFIX set to the system prefix like /usr and not to a packaging directory. 

Thanks.

**Comment by mingwandroid** [comment]
The problem here is that cmake is a Windows program so it doesn't grok "/mingw64/" prefixed paths.

Is there a concept of THIS_FILE in CMake? If so, we need to replace the absolute references with relative references.

The other way is to write a post install script that patches things, but post installs should be avoided unless absolutely necessary.

**Comment by Alexpux** [comment]
Currently we use postinstall scripts for such issues.

**Comment by mingwandroid** [comment]
CMAKE_CURRENT_SOURCE_DIR might be useful for this.

**Comment by Alexpux** [comment]
From: http://www.cmake.org/Wiki/CMake_Useful_Variables
````
CMAKE_CURRENT_SOURCE_DIR 
this is the directory where the currently processed CMakeLists.txt is located in
````

How it is useful?

**Comment by mingwandroid** [comment]
Because that should give the absolute path of CGALConfig.cmake, I think. Then relative paths from that can be used, e.g.

````
set(CGAL_INCLUDE_DIRS  "${CMAKE_CURRENT_SOURCE_DIR}/../../include" )
````

**Comment by Alexpux** [comment]
Issue here is that when you try to build any program that use CGAL.cmake from our package it contain wrong paths.
````CMAKE_CURRENT_SOURCE_DIR```` is good for using when building only

**Comment by mingwandroid** [comment]
I hoped ${CMAKE_CURRENT_SOURCE_DIR} would give the directory of CGALConfig.cmake when put in that file. Unfortunately I was wrong.

There's another way which involves setting `MSYS2_ARG_CONV_EXCL` at time of calling cmake to configure CGAL, but that precludes using anything except the 'MSYS Makefiles' generator so I was hoping for a better solution. I will ask on the CMake IRC channel for advise.

**Comment by mingwandroid** [comment]
I found it actually: `${CMAKE_CURRENT_LIST_DIR}`, preparing a gist.

**Comment by mingwandroid** [comment]
https://gist.github.com/mingwandroid/cd856ba3ddfa9ce40ee6

**Comment by mingwandroid** [comment]
.. going this route is safest. We can do the replacements at package() time in the PKGBUILD, there's no post installs and it should work correctly on all build systems. If you want, we could tidy up the ../.. stuff by:

http://stackoverflow.com/questions/9809494/cmake-get-the-complete-representation-of-a-path-minus-relative-elements

@donbright would you like to have a go at this or do you want me to do it?

**Comment by Alexpux** [comment]
I think you mean ````bin```` directories for ````dll````

**Comment by Alexpux** [comment]
So we will patch all cmake packages in this way then?

**Comment by mingwandroid** [comment]
yeah, whatever ;-)

**Comment by mingwandroid** [comment]
I think so, but let me play with it later today to make sure it all works correctly. So far, for the ones I did, I've been using `MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" cmake ...` so that the paths emitted to the config files are MSYS2 paths that then work ok provided the `MSYS Generator` is used, but this is a nicer solution IMHO.

**Comment by mingwandroid** [comment]
Fixed with: https://github.com/Alexpux/MINGW-packages/commit/34ea54e4f174cc055aaee137a1c7f86495b4ebb0

**Comment by mingwandroid** [comment]
Re-opened until @Alexpux repackages and @donbright tests!

**Comment by donbright** [comment]
sorry i am very ill, will be a few days before i can test.

**Comment by mingwandroid** [comment]
Sorry to hear that. There's no rush!

**Comment by donbright** [comment]
Just wanted to say thanks. I updated my MSYS2 and whatever you did it works now without a patch. It is using the RELOCATED_INSTALL_PREFIX mechanism. 

Thanks again. MSYS2 is really impressive.

**Comment by mingwandroid** [comment]
Thanks! The change was https://github.com/Alexpux/MINGW-packages/commit/34ea54e4f174cc055aaee137a1c7f86495b4ebb0 .. I need to apply this to all our CMake library packages at some point.
