### ISSUE TITLE
glib-2.0's .pc files need -D__USE_MINGW_ANSI_STDIO=1 adding to them.

### ISSUE THREAD

**Issue by mingwandroid** [Alexpux/MINGW-packages#691]
See: https://github.com/Alexpux/MSYS2-packages/issues/279 for the reasoning.

From https://github.com/conklech

Just to summarize my reasoning from #279: glib exposes a macro, G_GSIZE_FORMAT, advertised as providing the platform-local format string to print variables of type size_t. Without __USE_MINGW_ANSI_STDIO=1, this is incorrect.

**Comment by lazka** [comment]
I've tried to clarify the limitations of the format macros upstream: https://gitlab.gnome.org/GNOME/glib/commit/a9164f55f7db1e620d336511ea5461207b7a06b6

Is that enough?
