### ISSUE TITLE
Missing miniupnpc python bindings

### ISSUE THREAD

**Issue by xrogaan** [Alexpux/MINGW-packages#695]
miniupnpc can be found there: https://github.com/miniupnp/miniupnp/tree/master/miniupnpc

The bindings are quite difficult for a layman to build, thus I would appreciate any help on this matter. But as far as I understand, the available tools in that repository are not as useful as they could have been. What is missing is some link to some library, probably trivial for somebody who know what he is doing.

Here is an error log: https://paste.kde.org/pg7pxytwq

**Comment by Alexpux** [comment]
Probably missing ````-lws2_32```` while linking

**Comment by Alexpux** [comment]
I'm fix miniupnpc to install python modules. Will  be available in test repo today (if sourceforge will up)
