### ISSUE TITLE
Readline 6.3 patch to port to MinGW

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#698]
I created a patch to port Readline 6.3 to MinGW.

[Here is the Gist](https://gist.github.com/BrisingrAerowing/7c17d678363056eaa421)

I am not really good with shell scripts and stuff (I know enough to fix some issues, though), so I think it would be better if someone else updates the PKGBUILD so that I don't completely bork things.

**Comment by Alexpux** [comment]
I will try it

**Comment by Alexpux** [comment]
Done by https://github.com/Alexpux/MINGW-packages/commit/c2bc4c56d98996f7cd980cb483c28fde824eb77d
