### ISSUE TITLE
compilation CGAL applications fail

### ISSUE THREAD

**Issue by kien-kieu** [Alexpux/MINGW-packages#701]
I have installed mingw-w64-i686-gcc (4.9.2-5) and mingw-w64-i686-cgal (4.6-1). When I try to compile an example of CGAL doc (CMake file generated by cgal_create_cmake_script), I get the error

[100%] Building CXX object CMakeFiles/array_convex_hull_2.dir/array_convex_hull_2.cpp.obj
/mingw32/bin/c++.exe   -DCGAL_USE_GMP -DCGAL_USE_MPFR -march=i686 -mtune=generic -O2 -pipe  -frounding-math -O3 -DNDEBUG -isystem /mingw32/include -I/d/kien/cgal_example/build    -o CMakeFiles/array_convex_hull_2.dir/array_convex_hull_2.cpp.obj -c /d/kien/cgal_example/array_convex_hull_2.cpp
make[2]: ***  Aucune règle pour fabriquer la cible « /mingw32/lib/libCGAL_Core.dll », nécessaire pour « array_convex_hull_2 ». Arrêt.

The problem can be fixed by editing the file CGALConfig.cmake: add the ".a" suffix to the three libraries CGAL, CGALCore and CGAL_ImageIO at lines 48-50.

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/7a6aba6f7eb6f5897f4a643f6fe4f33c2e00c1c6
