### ISSUE TITLE
New mirrors for packages.

### ISSUE THREAD

**Issue by Alexpux** [Alexpux/MINGW-packages#702]
As sourceforge.net is down for a long time we have created new primary repositories for all packages.
To activate them you need modify ````/etc/pacman.d/mirrorlist*```` files by adding ````Server```` entries at first place.
- File ````/etc/pacman.d/mirrorlist.msys```` : 

````Server = http://45.59.69.178/msys/$arch````

- File ````/etc/pacman.d/mirrorlist.mingw32```` : 

````Server = http://45.59.69.178/mingw/i686````

- File ````/etc/pacman.d/mirrorlist.mingw64```` : 

````Server = http://45.59.69.178/mingw/x86_64````

We will not do it without server that provide to us ```` ***Diablo-D3*** ````

**Comment by jasin** [comment]
Nice I will update my pacman mirrorlist

**Comment by DavidEGrayson** [comment]
I found it was quicker to set up my new mirrors by doing something like this:

~~~~
wget http://repo.msys2.org/msys/x86_64/pacman-mirrors-20150722-1-any.pkg.tar.xz
pacman -U pacman-mirrors-20150722-1-any.pkg.tar.xz
~~~~

**Comment by Alexpux** [comment]
I'm already upload new pacman-mirrors package to sf.net and repo.msys2.org so you can easily get it via pacman.

**Comment by achadwick** [comment]
@DavidEGrayson 
wget is not installed by default. If anyone's bootstrapping:

```sh
curl -O http://repo.msys2.org/msys/x86_64/pacman-mirrors-20150722-1-any.pkg.tar.xz
pacman -U pacman-mirrors-20150722-1-any.pkg.tar.xz
pacman --needed -Sy bash pacman pacman-mirrors msys2-runtime 
```

@Alexpux I didn't get anything beyond 

    warning: pacman-mirrors-20141223-1 is up to date -- skipping

with a recent (< 1h ago) attempt, but maybe it takes a while for sf's infra to catch up.

**Comment by PiotrVV** [comment]
on repo.msys.org in msys "x86_64"
mingw-w64-i686-gdb-7.9-1-any.pkg.tar.xz
mingw-w64-x86_64-gtksourceview2-2.10.5-1-any.pkg.tar.xz  

These packages probably should't see you there?

**Comment by Alexpux** [comment]
yeah seems bad upload

**Comment by mkae** [comment]
This could be closed, no?!

**Comment by jasin** [comment]
if you are asking me, the one who posted the original bug #296. Yeah I am fine with it being closed.

**Comment by elieux** [comment]
Closing. If needed, the ticket can be re-opened.
