### ISSUE TITLE
Fontconfig doesn't load the local config.

### ISSUE THREAD

**Issue by zklhp** [Alexpux/MINGW-packages#705]
Hi,
With mingw-w64-x86_64-fontconfig 2.11.94-2, settings in `~/.config/fontconfig/fonts.conf` won't work. But with 2.11.1-3 it does. I compare these two versions and find that in 2.11.94-2 there are no .conf files under `/mingw64/etc/fonts/conf.d/`. By copying the missing .conf files from 2.11.1-3 it works again. Is this by design? Or am I miss something?

Thanks.

**Comment by Alexpux** [comment]
Will look on it today

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/b395e62abbcf2ab83851948b1557c5a098ffce2e in ````fontconfig-2.11.94-3````
