### ISSUE TITLE
mingw-w64-qt5 (5.5.0) fails to compile

### ISSUE THREAD

**Issue by towlie** [Alexpux/MINGW-packages#707]
https://gist.github.com/towlie/9c0e25ed90f64512d4d4

**Comment by martell** [comment]
Hi @towlie :)

From your log it seems like qt5 is already defining those IID's
if you could locate where this is, most likely qaxscript.cpp
and #ifndef it out for the mingw-w64 target then it should build

We also accept PR's to fix bugs that pop up like this :)

Many Thanks
Martell

**Comment by Alexpux** [comment]
@martell, no. This is butg in mingw-w64 headers, but it already fixed by me upstream.
@towlie, seems you use toolchain not provided by MSYS2.

**Comment by towlie** [comment]
https://gist.github.com/anonymous/b33a50a0248910f4f02d

**Comment by martell** [comment]
@Alexpux He is using the correct toolchain it seems
@towlie  the latest version is mingw-w64-x86_64-headers-git 5.0.0.4522.e2d9393-1

are your mirrors still pointing to sourceforge or did you update them ?

**Comment by towlie** [comment]
@martell I think it all from sourceforge. I did update on 15. Jul 2015.

**Comment by martell** [comment]
https://github.com/Alexpux/MINGW-packages/issues/702
Please update the mirrors and to the latest headers and retry

**Comment by towlie** [comment]
Updating helped. Thanks.
