### ISSUE TITLE
icu-config fails to work

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#708]
Due to the removal of unversioned ICU symlinks, icu-config fails as it looks for the unversioned libraries.

Adding a variable named ICULIBSUFFIX_VERSION set to the base ICU version (currently 55) fixes the issue. Lines 78-80 in icu-config have information on this variable.

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/6f760432b4bbc3b8f528ee1b5f74cc9d3985725b

Please test it.
