### ISSUE TITLE
winpthreads-git: mypaint segfault when launched after upgrading winpthreads ("ImportError: DLL load failed: Invalid access to memory location.")

### ISSUE THREAD

**Issue by achadwick** [Alexpux/MINGW-packages#709]
MyPaint fails to run when my MSYS2 system is upgraded to mingw binaries from the repository which contain gcc 5.2.0. It used to work fine with the old Sourceforge repos, whose gcc was at 4.9.

```bash
$ ./mypaint
INFO: lib.i18n: Windows: LANG='en_US.UTF-8'
INFO: lib.i18n: Windows: LANGUAGE='en_GB:en_US'
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
INFO: mypaint: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (ctypes)
ERROR: mypaint: Failed to load MyPaint's C extension. This probably means that MyPaint was not correctly installed, or was built incorrectly.
Traceback (most recent call last):
  File "./mypaint", line 438, in <module>
    from lib import mypaintlib
  File "./lib/mypaintlib.py", line 28, in <module>
    _mypaintlib = swig_import_helper()
  File "./lib/mypaintlib.py", line 20, in swig_import_helper
    import _mypaintlib
ImportError: DLL load failed: Invalid access to memory location.
INFO: mypaint: script: './mypaint'
INFO: mypaint: sys.path: ['.', 'C:/msys64/mingw32/lib/python27.zip', 'C:/msys64/mingw32/lib/python2.7', 'C:/msys64/mingw32/lib/python2.7/plat-win32', 'C:/msys64/mingw32/lib/python2.7/lib-tk', 'C:/msys64/mingw32/lib/python2.7/lib-old', 'C:/msys64/mingw32/lib/python2.7/lib-dynload', 'C:/building/msys32/mingw32', 'C:/msys64/mingw32/lib/python2.7/site-packages']
Segmentation fault
```
-- full build log at <https://gist.github.com/achadwick/68957fe2f0d7315b3eaf>

From IRC earlier:

    <alexey> need try to see what dll is failed to load
    <alexey> try run from CMD - you will get messagebox with failed dll

I didn't get much out of this other than a few memdump blobs and a `WER9C64.tmp.WERInternalMetadata.xml`.

```xml
<?xml version="1.0" encoding="UTF-16"?><!-- converted here -->
<WERReportMetadata>
	<OSVersionInformation>
		<WindowsNTVersion>6.1</WindowsNTVersion>
		<Build>7601 Service Pack 1</Build>
		<Product>(0x4): Windows 7 Enterprise</Product>
		<Edition>Enterprise</Edition>
		<BuildString>7601.18869.amd64fre.win7sp1_gdr.150525-0603</BuildString>
		<Revision>1130</Revision>
		<Flavor>Multiprocessor Free</Flavor>
		<Architecture>X64</Architecture>
		<LCID>1033</LCID>
	</OSVersionInformation>
	<ProblemSignatures>
		<EventType>APPCRASH</EventType>
		<Parameter0>python.exe</Parameter0>
		<Parameter1>0.0.0.0</Parameter1>
		<Parameter2>73657922</Parameter2>
		<Parameter3>libgcc_s_dw2-1.dll</Parameter3>
		<Parameter4>0.0.0.0</Parameter4>
		<Parameter5>0001f302</Parameter5>
		<Parameter6>c0000005</Parameter6>
		<Parameter7>00014a74</Parameter7>
	</ProblemSignatures>
	<DynamicSignatures>
		<Parameter1>6.1.7601.2.1.0.256.4</Parameter1>
		<Parameter2>2057</Parameter2>
		<Parameter22>0a9e</Parameter22>
		<Parameter23>0a9e372d3b4ad19135b953a78882e789</Parameter23>
		<Parameter24>0a9e</Parameter24>
		<Parameter25>0a9e372d3b4ad19135b953a78882e789</Parameter25>
	</DynamicSignatures>
	<SystemInformation>
		<MID>C3DACC09-4836-412B-809C-86D35F10A6CF</MID>
		<SystemManufacturer>innotek GmbH</SystemManufacturer>
		<SystemProductName>VirtualBox</SystemProductName>
		<BIOSVersion>VirtualBox</BIOSVersion>
	</SystemInformation>
</WERReportMetadata>
```

This affects the PKGBUILD [maintained here](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-mypaint) and local testing builds of mypaint.

I have tried upgrading my system and then downgrading the `mingw-w64-i686-gcc*` packages to the GCC 4.9 packages preserved at <https://www.mirrorservice.org/sites/downloads.sourceforge.net/m/ms/msys2/>,

```bash
$ pacman -U /tmp/*.pkg*xz
loading packages...
warning: downgrading package mingw-w64-i686-gcc (5.2.0-3 => 4.9.2-5)
warning: downgrading package mingw-w64-i686-gcc-ada (5.2.0-3 => 4.9.2-5)
warning: downgrading package mingw-w64-i686-gcc-fortran (5.2.0-3 => 4.9.2-5)
warning: downgrading package mingw-w64-i686-gcc-libgfortran (5.2.0-3 => 4.9.2-5)
warning: downgrading package mingw-w64-i686-gcc-libs (5.2.0-3 => 4.9.2-5)
warning: downgrading package mingw-w64-i686-gcc-objc (5.2.0-3 => 4.9.2-5)
resolving dependencies...
looking for conflicting packages...

Packages (6) mingw-w64-i686-gcc-4.9.2-5  mingw-w64-i686-gcc-ada-4.9.2-5
             mingw-w64-i686-gcc-fortran-4.9.2-5
             mingw-w64-i686-gcc-libgfortran-4.9.2-5
             mingw-w64-i686-gcc-libs-4.9.2-5  mingw-w64-i686-gcc-objc-4.9.2-5
[...]
```

and then rebuilding mypaint packages. The resultant packages work correctly, but upgrading gcc (and gcc-libs) to the latest 5.2.0 causes MyPaint to break once again.

**Comment by achadwick** [comment]
Well, this is weird...

On a snapshotted system with `mingw-w64-i686-gcc` 4.9.2 (and `mingw-w64-i686-python2-numpy` 1.9.2-1, merely upgrading the gcc stuff isn't sufficient to provoke this problem when a mypaint is installed from a .pkg.tar.xz built with GCC 4.9.2.

```bash
$ pacman -S mingw-w64-i686-gcc-libs mingw-w64-i686-gcc mingw-w64-i686-gcc-libgfortran mingw-w64-i686-gcc-ada mingw-w64-i686-gcc-fortran mingw-w64-i686-gcc-objc

$ (cd /tmp && mypaint)
[runs normally, interface presents normally (for MINGW32 at least)]
```

Upgrading numpy too, 1.9.2-1 → 1.9.2-3

```bash
$ pacman -S mingw-w64-i686-python2-numpy
```

does not break the existing mypaint installation. Continuing in the above vein, the following upgrades do **NOT** cause the error:

* OK AFTER mingw-w64-i686-python2 2.7.10-2 → 2.7.10-4
* OK AFTER mingw-w64-i686-openblas 0.2.14-1 → 0.2.14-2
* ATTEMPTED1 mingw-w64-i686-python2-gobject 3.16.0-1 → 3.16.2-1
 - pulls in mingw-w64-i686-gobject-introspection-runtime-1.44.0-5 mingw-w64-i686-pygobject-devel-3.16.2-1 mingw-w64-i686-python2-gobject-3.16.2-1
  - fails due to presence of .typelib files in the filesystem
* OK AFTER mingw-w64-i686-gobject-introspection 1.44.0-3 → 1.44.0-5 (pulls in mingw-w64-i686-gobject-introspection-runtime-1.44.0-5 mingw-w64-i686-python2-beaker-1.7.0-2 mingw-w64-i686-python2-mako-1.0.1-3 mingw-w64-i686-python2-markupsafe-0.23-3 mingw-w64-i686-gobject-introspection-1.44.0-5)
* OK AFTER mingw-w64-i686-python2-gobject 3.16.0-1 → 3.16.2-1
  - pulls in mingw-w64-i686-pygobject-devel-3.16.2-1

So far nothing... because @Alexpux just mentioned libwinpthread on IRC:

* **NOT OK AFTER upgrading mingw-w64-i686-winpthreads-git** 5.0.0.4497.4254261-1 → 5.0.0.4531.49c7046-1
  - pulls in mingw-w64-i686-libwinpthread-git-5.0.0.4531.49c7046-1
  - BINGO. winpthreads appears to be the cause of the error.

**Comment by achadwick** [comment]
gdb trace - I'm not sure how useful it is though.
<https://gist.github.com/achadwick/01c6a1b519a36dcdbe0a>

**Comment by achadwick** [comment]
Setting `enable_openmp=False` in the mypaint build fixes this.

**Comment by achadwick** [comment]
@Alexpux winpthread 5.0.0.4538.78dca70-1 fixes this in the presence of `-fopenmp -pthread`. No need for `enable_openmp=False`. Thanks for chasing this!

**Comment by RoyiAvital** [comment]
Does MSYS currently support using of OpenMP out of the box?
