### ISSUE TITLE
rebuild openscenegraph (OSG) using gcc 5.2.0

### ISSUE THREAD

**Issue by adrpo** [Alexpux/MINGW-packages#710]
Hi,

As I was saying here:
http://sourceforge.net/p/msys2/mailman/message/34323638/
there are issues with linking existing OSG libraries
with code generated by latest, newer gcc 5.2.0.

Can you rebuild OSG using gcc 5.2.0?

Thanks!

Cheers,
Adrian Pop/

**Comment by Alexpux** [comment]
I read ML. Yes OSG not yet rebuilded because I'm wait 3.4.0 release on this or next week

**Comment by adrpo** [comment]
Ok, thanks. I'll keep an eye out for it.

**Comment by Alexpux** [comment]
I'm upload OpenSceneGraph-3.4.0rc7 package. Feel free to test it.
