### ISSUE TITLE
wxWidgets link error.

### ISSUE THREAD

**Issue by stambaughw** [Alexpux/MINGW-packages#712]
As of the gcc 5 builds of wxWidgets, any 64 bit (I haven't tested 32 bits yet) application built against it will fail for a DLL link error (see image for failure message).  According to the package list, wxWidgets has already been rebuilt against gcc 5 and I did not see it in the fail to build list.  This means that your packaged version of KiCad will fail due to this problem.  It looks like wxWidgets is not playing nice with gcc 5 or something went wrong when the wxWidgets package was rebuilt..

![image](https://cloud.githubusercontent.com/assets/5891750/8961810/6ae826f2-35e5-11e5-8e17-708724fe7271.png)

**Comment by Alexpux** [comment]
Yeah I see the same error during start of ***kicad***, but ***codelite*** works ok.

**Comment by nickoe** [comment]
FWIW, I also see this on linux, I have done this for quite some time, and I think it has started to appear when some kicad added some checking on the verions of wxwidgets and wxpyhon, IIRC.

```
$ pcbnew/pcbnew 
19:04:55: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1008,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 999999,wx containers,compatible with 2.8).
```
The above paste is kicad build with the intel compiler. I actually don't see it currently with my gcc build. (on linux).

@stambaughw  Can you confirm you also se that error with my builds on http://www2.futureware.at/~nickoe/ ?

**Comment by nickoe** [comment]
ABI version bump: https://github.com/gcc-mirror/gcc/commit/399fbd

**Comment by renatosilva** [comment]
This is a bug with wxWidgets [already fixed upstream](https://github.com/wxWidgets/wxWidgets/pull/40).

**Comment by nickoe** [comment]
I don't see how that fixes this issue. The upstream fix is only within the range 1002-1008, and here we are at 1009 on one side.

**Comment by HighCommander4** [comment]
Are the ABI changes from version 8 ("1008") to version 9 ("1009") documented anywhere? [This page](https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html) only documents up to version 8.

**Comment by stambaughw** [comment]
On 7/29/2015 1:06 PM, nickoe wrote:
> FWIW, I also see this on linux, I have done this for quite some time,
> and I think it has started to appear when some kicad added some checking
> on the verions of wxwidgets and wxpyhon, IIRC.

I just rebuilt kicad with scripting disabled and I still get the same
error so it's not wxPython causing the problem.

> 
> |$ pcbnew/pcbnew 19:04:55: Warning: Mismatch between the program and
> library build versions detected. The library used 3.0 (wchar_t,compiler
> with C++ ABI 1008,wx containers,compatible with 2.8), and your program
> used 3.0 (wchar_t,compiler with C++ ABI 999999,wx containers,compatible
> with 2.8). |
> 
> The above paste is kicad build with the intel compiler. I actually don't
> see it currently with my gcc build. (on linux).
> 
> @stambaughw <https://github.com/stambaughw> Can you confirm you also se
> that error with my builds on http://www2.futureware.at/~nickoe/
> <http://www2.futureware.at/%7Enickoe/> ?

A bug report was already filed against your packaged builds here:
https://bugs.launchpad.net/kicad/+bug/1479204

**Comment by stambaughw** [comment]
It looks like wxWidgets needs to be rebuilt with gcc 5.2 so the ABI
versions will match when linking against it.

**Comment by Alexpux** [comment]
Rebuilded wxWidgets uploaded.

**Comment by nickoe** [comment]
I have updated to the new wxwidgets, but this time I see it conflicting with the ABI of wxpython instead of "your program".

I guess a rebuild of wxpython will fix this issue. I have not tried it though.

![image](https://cloud.githubusercontent.com/assets/352202/8971736/85100022-3653-11e5-9f1a-65503c0c2881.png)

**Comment by nickoe** [comment]
I have now tried to rebuild wxpython locally, and that fixes the above error.

**Comment by pingplug** [comment]
can not link against static lib
link against shared lib is OK
