### ISSUE TITLE
gdbinit problem

### ISSUE THREAD

**Issue by zklhp** [Alexpux/MINGW-packages#719]
Hi,

With mingw-w64-x86_64-gdb-7.9.1-3, Starting gdb will produce output like this:

> Traceback (most recent call last):
>   File "<string>", line 4, in <module>
>   File "i:\msys64\mingw64\share\gdb/python/../../gcc-5.2.0/python/libstdcxx/v6/printers.py", line 1267, in register_libstdcxx_printers
>     gdb.printing.register_pretty_printer(obj, libstdcxx_printer)
>   File "i:\msys64\mingw64\share\gdb/python/gdb/printing.py", line 152, in register_pretty_printer
>     printer.name)
> RuntimeError: pretty-printer already registered: libstdc++-v6
> i:\msys64\mingw64\bin\../etc/gdbinit:6: Error in sourced command file:
> Error while executing Python code.

A quick search (http://stackoverflow.com/questions/18289377/gdb-runtimeerror-pretty-printer-already-registered-libstdc-v6) suggests that the line

> register_libstdcxx_printers (None)

in `gdbinit` isn't needed, and removing this line the error message is gone. Should this be removed?

Thanks.

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/22eaa7634a04b6a83cdeca1704cc22e20f1a999b
