### ISSUE TITLE
gpgme does not find gpg.exe

### ISSUE THREAD

**Issue by jeroenooms** [Alexpux/MINGW-packages#724]
Already discussed this in email but posting it here so that it doesn't get lost.

The `mingw-w64-gpgme` library is unable to find the required `gpg.exe` or `gpgconf.exe`. For some reason the msys2 version of libgpgme works fine, but not the mingw build. For an example see: [this gist](https://gist.github.com/jeroenooms/038d3faba0976f85fb36).

**Comment by jeroenooms** [comment]
I don't think this fixed it. I rebuilt and installed `mingw-w64-gpgme` but I keep getting the same error when running the example from the gist:

```
/mingw64/bin/gcc test.c -o gpgme-test-mingw64.exe -DDEBUG -I/mingw64/include -L/mingw64/lib /mingw64/lib/libgpgme.a /mingw64/lib/libgpg-error.a /mingw64/lib/libassuan.a -lws2_32
./gpgme-test-mingw64.exe

GPGME 2015-08-05 00:41:13 <0x1058>  gpgme_debug: level=9
GPGME 2015-08-05 00:41:13 <0x1058>  gpgme_check_version: call: 0=0000000000000000, req_version=(null), VERSION=1.5.5
GPGME 2015-08-05 00:41:13 <0x1058>  gpgme_check_version_internal: call: 0=0000000000000000, req_version=(null), offset_sig_validity=52
GPGME 2015-08-05 00:41:13 <0x1058>  gpgme_set_locale: enter: ctx=0000000000000000, category=2, value=C
GPGME 2015-08-05 00:41:13 <0x1058>  gpgme_set_locale: leave
GPGME 2015-08-05 00:41:13 <0x1058>  _gpgme_get_gpgconf_path: '(null)' not found
GPGME 2015-08-05 00:41:13 <0x1058>  gpgme-dinfo: gpgconf='[null]'
GPGME 2015-08-05 00:41:13 <0x1058>  _gpgme_get_gpg_path: '(null)' not found
GPGME 2015-08-05 00:41:13 <0x1058>  engine.c:155: returning error: Invalid crypto engine
GPG engine init error: Invalid crypto engine
```

**Comment by mingwandroid** [comment]
I think you're misunderstanding something crucial here. You *need* to run your built exe from the /mingw64/bin folder. My commit fixes a subsequent bug you'd would encounter after doing that. Please read the commit message.

Try:

```
mv gpgme-test-mingw64.exe /mingw64/bin
/mingw64/bin/gpgme-test-mingw64.exe
```

.. and your test should work ok.

**Comment by jeroenooms** [comment]
Ah okay sorry I misunderstood. But can we perhaps leave this issue open if this is not really the one that you fixed? 

In addition: if it is difficult to find `gpg.exe` from the PATH, is there a way we can at least make it work with an explicitly specified path:

```
#define GPG4WIN "C:/Program Files (x86)/GNU/GnuPG/gpg2.exe"
gpgme_set_engine_info(GPGME_PROTOCOL_OpenPGP, GPG4WIN, NULL);
```

Or with the environment variable:

```
 gpgme_set_global_flag("gpgconf-name", "C:/Program Files (x86)/GNU/GnuPG/gpgconf");
gpgme_set_global_flag("gpg-name", "C:/Program Files (x86)/GNU/GnuPG/gpg2");
```

**Comment by mingwandroid** [comment]
> Ah okay sorry I misunderstood. But can we perhaps leave this issue open if this is not really the one that you fixed?

You can keep it open if you can verify that the workarounds you've suggested don't work.

```#define GPG4WIN "C:/Program Files (x86)/GNU/GnuPG/gpg2.exe"```

Personally I won't spend any time ensuring that MSYS2's gpgme packages interoperate with a non-MSYS2 gnupg since we already provide our own builds of gnupg:

```pacman -S mingw-w64-x86_64-gnupg
pacman -Ql mingw-w64-x86_64-gnupg /mingw64/bin/gpg2.exe | /mingw64/bin/ag gpg2.exe```

.. but do test and let me know. My comments apply equally to `gpgme_set_global_flag`.

**Comment by mingwandroid** [comment]
> In addition: if it is difficult to find gpg.exe from the $PATH
Well, I'd not say it's difficult necessarily, and a patch for this would be welcome. FWIW, since I develop MSYS2 packages, I'm happy that every executable I build that links to gpgme will reside in the same folder as gnupg, so IMHO at this stage, this is an itch for you to scratch.

**Comment by jeroenooms** [comment]
> You can keep it open if you can verify that the workarounds you've suggested don't work.

Since you closed the issue, only you can reopen it ;)

> Personally I won't spend any time ensuring that MSYS2's gpgme packages interoperate with a non-MSYS2 gnupg since we already provide our own builds of gnupg

The same problem appears for e.g:

```c
gpgme_set_engine_info(GPGME_PROTOCOL_OpenPGP, "/mingw64/bin/gpg.exe", NULL);
```

I just need a way to build an app with gpgme support that is outside of the gpg.exe directory, one way or another.

**Comment by mingwandroid** [comment]
"/mingw64/bin/gpg.exe" is an msys2 path and that makes no sense to a native Windows program.

**Comment by mingwandroid** [comment]
If you want to do it that way, you'd need to call out to cygpath, but you'd then have the problem of not knowing where that lives.

**Comment by jeroenooms** [comment]
> IMHO, the best solution is to write a patch to search in your PATH. 

That should be the default behavior already (and it works for the linux or msys2 builds of gpgme).

**Comment by mingwandroid** [comment]
Clearly is not the default behaviour, that's why I recommend you write a patch. I did some mmore investigation:

    $ cd repo/mingw-w64-gpgme/src/gpgme-1.5.5
    $ /mingw64/bin/ag -w PATH
    ....
    src/posix-util.c
    74:/* Find an executable program PGM along the envvar PATH.  */
    84:  orig_path = getenv ("PATH");

`src/posix-util.c` is not used on Windows, `src/w32-util.c` is used instead. Perhaps you can port that feature from one file to the other?

**Comment by jeroenooms** [comment]
Okay that makes sense. I am surprised they implement their own `walk_path` function. Can we just use something like [PathFindOnPath](https://msdn.microsoft.com/en-us/library/windows/desktop/bb773594(v=vs.85).aspx) on windows?

**Comment by mingwandroid** [comment]
You'd be introducing a dependency on Shlwapi.lib and Shlwapi.dll that way. Doing the work by hand via str* and _stat would be my approach.

**Comment by jeroenooms** [comment]
Here is a first patch. Would you mind reviewing this? http://pastebin.com/raw.php?i=EhxMFEfX

It fixes a bug in the existing system to lookup `gpg.exe` where it looks in `C:\Program Files` but not in `C:\Program Files (x86)` which is where GPG is installed by default. I realize this is not directly relevant to msys2 but it helps with building portable apps.

**Comment by mingwandroid** [comment]
Please use a github gist instead of pastebin. My firewall blocks pastebin.

**Comment by jeroenooms** [comment]
OK here it is: https://gist.github.com/jeroenooms/5b380fbed8d93187d8b5

**Comment by jeroenooms** [comment]
Sorry there was a typo in there, updated: https://gist.github.com/jeroenooms/5b380fbed8d93187d8b5
