### ISSUE TITLE
Recompile/bump pkgrel of libidn

### ISSUE THREAD

**Issue by wiiaboo** [Alexpux/MINGW-packages#729]
Would it be possible to recompile/bump pkgrel of libidn in order to force update?

Reason being libidn.pc containing a "-R" flag in Libs which causes issues with compilation/linking.

Just bumping pkgrel should be enough since I just `makepkg-mingw` the PKGBUILD and the pkg-config file didn't contain that flag.

**Comment by mabreedlove** [comment]
I committed a change with --disable-rpath that disables it.  Not sure what precisely warrants a bump in pkgrel, but the fix is applied at least.

**Comment by wiiaboo** [comment]
I assume pkgrel means it's not a new version of the app/lib but new recompilation/repackaging/patches.

**Comment by mabreedlove** [comment]
Pretty much.  It triggers pacman to pull down the new build.  I don't do the repo builds, however.

**Comment by mingwandroid** [comment]
On Wed, Aug 12, 2015 at 9:56 PM, Matt Breedlove <notifications@github.com>
wrote:

> Pretty much. It triggers pacman to pull down the new build. I don't do the
> repo builds, however.
>

Ah, I didn't check that, you should bump pkgrel whenever you make a change,
but if you update to a new pkgver, then reset it to 1.

**Comment by mabreedlove** [comment]
That's what I thought, but I figured I would wait to make sure.  I'll go through and make sure the rest of my changes got bumped up shortly when I do a build for the new vorbis release that needs updating as well.

**Comment by mingwandroid** [comment]
No problem. I bumped those of the two packages I merged your commits for already.

Technically if you did something that wouldn't alter the final package (like tidying up the PKGBUILD file) then you don't need to bump it, but it's easier to be mechanical about it I think.
