### ISSUE TITLE
mingw64/mingw-w64-x86_64-breakpad-svn's problem with libstdc++-6.dll

### ISSUE THREAD

**Issue by antekone** [Alexpux/MINGW-packages#731]
After installing the `breakpad` package, no executable from this package runs:

    $ /mingw64/bin/sym_upload.exe
    /mingw64/bin/sym_upload.exe: error while loading shared libraries: libstdc++-6.dll: cannot open shared object file: No such file or directory

    $ /mingw64/bin/dump_syms
    /mingw64/bin/dump_syms.exe: error while loading shared libraries: libstdc++-6.dll: cannot open shared object file: No such file or directory

Should I install anything else to make it work? If yes, shouldn't this dependency installed automatically by pacman?

**Comment by antekone** [comment]
Installing `mingw-w64-x86_64-gcc-libs` helped. Shouldn't this be added as a dependency?

**Comment by Alexpux** [comment]
You can create pull request to fix it or wait when we do it ourself

**Comment by Alexpux** [comment]
Fixed in PKGBUILD. Will be rebuilded some later.
