### ISSUE TITLE
glib2's pkg-config Libs.private misses iconv

### ISSUE THREAD

**Issue by rubidium42** [Alexpux/MINGW-packages#744]
After solving https://github.com/Alexpux/MINGW-packages/issues/743 statically linking to freetype using "pkg-config freetype2 --libs --static" fails due to a missing library:
C:/msys32/mingw32/lib\libintl.a(dcigettext.o):(.text+0x70b): undefined reference to `libiconv'
C:/msys32/mingw32/lib\libintl.a(dcigettext.o):(.text+0x870): undefined reference to`libiconv_open'
C:/msys32/mingw32/lib\libintl.a(dcigettext.o):(.text+0x9d9): undefined reference to `libiconv_open'
C:/msys32/mingw32/lib\libintl.a(relocatable.o):(.text+0x4b): undefined reference to`libiconv_set_relocation_prefix'
collect2.exe: error: ld returned 1 exit status

Since glib-2.0 adds -lintl to it's Libs.private, it should also contain -liconv. Alternatively libiconv gets pkg-config support and you add a Requires.private, but that is significantly more work.

The problem can be solved by adding iconv to the Libs.private pkg-config file:
--- glib-2.0.pc 2015-08-13 19:58:45.341377600 +0200
+++ glib-2.0.pc    2015-08-13 19:58:56.799043000 +0200
@@ -12,5 +12,5 @@ Description: C Utility Library
 Version: 2.44.1
 Requires.private:
 Libs: -L${libdir} -lglib-2.0 -lintl
-Libs.private: -pthread -lws2_32 -lole32 -lwinmm -lshlwapi  -lintl
+Libs.private: -pthread -lws2_32 -lole32 -lwinmm -lshlwapi  -lintl -liconv
 Cflags: -I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include -mms-bitfields

**Comment by Alexpux** [comment]
This need to be fixed upstream in glib2 I think.

**Comment by Martchus** [comment]
I fixed this issue for the mingw-w64 toolchain under Arch Linux:
https://github.com/Martchus/PKGBUILDs/commit/b12ed5b2276a0dde1e24f38ebe538a27aebc3b8e
https://github.com/Martchus/PKGBUILDs/commit/9acd7dd3429212db919be10a19ba40d4a8dbf268

BTW: There is also a patch included to make the latest gettext work.
