### ISSUE TITLE
Cannot catch std::ios_base::failure exceptions thrown by C++ standard library

### ISSUE THREAD

**Issue by DavidEGrayson** [Alexpux/MINGW-packages#747]
Sorry, I don't really know if this is an MSYS2 bug or a bug in one of the upstream packages.

I just discovered a bug with mingw g++ in MSYS2: the standard C++ library throws exceptions of type `std::ios_base::failure` that you cannot actually catch using that class name.

It throws exceptions with type name: `NSt8ios_base7failureE`.  But if you refer to std::ios_base:failure in your code, you are actually using: `NSt8ios_base7failureB5cxx11E`.  So I don't know what to write in order to actually catch these exceptions that get thrown.

Here is some code demonstrating the issue:

``` .cpp
#include <iostream>
#include <sstream>
#include <typeinfo>

int main()
{
    std::istringstream s("hi");
    s.exceptions(s.badbit);
    try
    {
        // throw std::ios_base::failure("hi");
        s.setstate(s.badbit);
    }
    catch(const std::ios_base::failure & e)
    {
        std::cout << "Caught std::ios_base::failure: "
                  << typeid(e).name() << std::endl;
    }
    catch(const std::exception & e)
    {
        std::cout << "Caught std::exception: "
                  << typeid(e).name() << std::endl;
    }
    return 0;
}
```

Here is a MINGW64 shell session showing my version of GCC, how I compiled it, and the result I got:

```
$ g++ -v
Using built-in specs.
COLLECT_GCC=D:\msys64\mingw64\bin\g++.exe
COLLECT_LTO_WRAPPER=D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-5.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --with-gxx-include-dir=/mingw64/include/c++/5.2.0 --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-version-specific-runtime-libs --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev3, Built by MSYS2 project' --with-bugurl=http://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 5.2.0 (Rev3, Built by MSYS2 project)
$ g++ prog.cpp && ./a.exe
Caught std::exception: NSt8ios_base7failureE
```

You can see that the first catch clause is not used, and instead the second one is used.  If I run this with GCC 4 on Ubuntu, I am able to catch that exception class properly and the first clause is used.

The parent class of `std::ios_base::failure` changed in C++11 [according to cppreference.com](http://en.cppreference.com/w/cpp/io/ios_base/failure).  I suspect that the C++ standard library was compiled with different options than are being used by the compiler at compile time.  In particular, it seems like it was compiled with the `_GLIBCXX_USE_CXX11_ABI` turned off.  Here is the definition of `std::ios_base::failure` in `/mingw64/include/c++/5.2.0/bits/ios_base.h`:

``` .cpp
#if _GLIBCXX_USE_CXX11_ABI
    class _GLIBCXX_ABI_TAG_CXX11 failure : public system_error
    {
      ...
    };
#else
    class failure : public exception
    {
      ...
    };
#endif
```

Maybe the standard library actually needs to be compiled in two different ways, one for C++11 programs and one for other programs?  I should note that this behavior doesn't seem to change if I add the `--std=gnu++11` option, so both the pre-C++11 programs and the C++11 programs are  affected by this bug.

I tried this with x86_64 and i686 versions of g++ and did not notice any difference.

I don't know how serious this bug is.  It's easy to work around if you know about it, but there might be a lot of code out there trying to catch these exceptions and they would suffer from subtle bugs when ported to MSYS2.

**Comment by mingwandroid** [comment]
Hi David,

Interesting. Can you post this to the mingw-w64 users mailing list? Hopefully Kai or JonY will have some insight.

**Comment by niXman** [comment]
Hi,

I tested it using `x86_64-4.9.3-release-posix-seh` build form MinGW-W64: http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.3/threads-posix/seh/x86_64-4.9.3-release-posix-seh-rt_v4-rev0.7z/download

all works as expected:
```
nixman@nixman-pc MSYS ~
$ g++ -v
Using built-in specs.
COLLECT_GCC=C:\msys64\home\nixman\mingw-builds\toolchains\mingw64\bin\g++.exe
COLLECT_LTO_WRAPPER=C:/msys64/home/nixman/mingw-builds/toolchains/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/4.9.3/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-4.9.3/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysroot=/c/mingw493/x86_64-493-posix-seh-rt_v4-rev0/mingw64 --with-gxx-include-dir=/mingw64/x86_64-w64-mingw32/include/c++ --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,objc,obj-c++,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-isl-version-check --disable-cloog-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/c/mingw493/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/c/mingw493/prerequisites/x86_64-w64-mingw32-static --with-mpc=/c/mingw493/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/mingw493/prerequisites/x86_64-w64-mingw32-static --with-cloog=/c/mingw493/prerequisites/x86_64-w64-mingw32-static --enable-cloog-backend=isl --with-pkgversion='x86_64-posix-seh-rev0, Built by MinGW-W64 project' --with-bugurl=http://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -I/c/mingw493/x86_64-493-posix-seh-rt_v4-rev0/mingw64/opt/include -I/c/mingw493/prerequisites/x86_64-zlib-static/include -I/c/mingw493/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -I/c/mingw493/x86_64-493-posix-seh-rt_v4-rev0/mingw64/opt/include -I/c/mingw493/prerequisites/x86_64-zlib-static/include -I/c/mingw493/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/c/mingw493/x86_64-493-posix-seh-rt_v4-rev0/mingw64/opt/lib -L/c/mingw493/prerequisites/x86_64-zlib-static/lib -L/c/mingw493/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 4.9.3 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

nixman@nixman-pc MSYS ~
$ g++ extest.cpp -oextest && ./extest
Caught std::ios_base::failure: NSt8ios_base7failureE
```

I have not tested the rest of the MinGW-W64 builds.

**Comment by niXman** [comment]
In the `x86_64-5.2.0-release-posix-seh` this error also present.

**Comment by AlB80** [comment]
It's because the stream throws "std::ios_base::failure", but this c++11 code tries to catch "std::ios_base::failure[abi:cxx11]". 
Ub14.4's gcc 5.1 tries to catch a c++98 class in both cases.
Seems like it is not MinGW bug
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66145
