### ISSUE TITLE
Can "cccl" be added?

### ISSUE THREAD

**Issue by ebraminio** [Alexpux/MINGW-packages#749]
Is it possible [cccl](https://github.com/swig/cccl), MSVC compiler wrapper for cc, be added as an MINGW package? I may can work on it if is OK to be added.

**Comment by mingwandroid** [comment]
IMHO, MSYS2 should not promote proprietary, closed source software (ok, just Windows itself; that's kind of necessary). It would also cause people to try to mix libraries compiled with MinGW-w64 and ones compiled with MSVC which won't work very well and we'd have to deal with the bug reports.

I'd not oppose merging such a PKGBUILD, but I don't think we should release a binary package for it.

**Comment by ebraminio** [comment]
I understand. Thank you. The main motivation was to use it for a project [CI purpose](https://github.com/behdad/harfbuzz/pull/112) so lack of binary wouldn't make it useful for the purpose. I like to hear other and the final decision, feel free to just close this in case this would go furthur.

**Comment by mingwandroid** [comment]
AFAIK, you could add a prebuilt pkg.xz file to the AppVeyor setup still, or even build it as part of the CI run (I guess something as simple as cccl would build in a matter of seconds?)

**Comment by ebraminio** [comment]
Yep. I just thought it would be nice to do this in a more clean and reusable way.

**Comment by mingwandroid** [comment]
Or you could setup a repo for your own.

Actually, I won't oppose the binary release if you do the work. I'd just caution people not to use it :-)

**Comment by ebraminio** [comment]
Well I tested it and this was easier than I thought, there is no compile involved here, just copying cccl to /usr/bin. Maybe this is valid usecase for MSYS2-packages or even being a package anyway?

**Comment by elieux** [comment]
@mingwandroid, do we at least want the PKGBUILD?

**Comment by mingwandroid** [comment]
@elieux : At least, yeah, I don't object to a package either.

**Comment by galeksandrp** [comment]
#2315
