### ISSUE TITLE
mingw-w64-shiboken-qt4 broken

### ISSUE THREAD

**Issue by MrKepzie** [Alexpux/MINGW-packages#753]
Build is failing for shiboken, cf below:

    $ gcc --version
    gcc.exe (Rev3, Built by MSYS2 project) 5.2.0

    C:/msys64/home/lex/MINGW-packages/mingw-w64-shiboken-qt4/src/build-x86_64-w64-mingw32-python2/sources/shiboken/libshiboken/sbkenum.cpp: In function 'PyTypeObject* Shiboken::Enum::newTypeWithName(const char*, const char*)':
    C:/msys64/home/lex/MINGW-packages/mingw-w64-shiboken-qt4/src/build-x86_64-w64-mingw32-python2/sources/shiboken/libshiboken/sbkenum.cpp:541:19: error: invalid conversion from 'Py_ssize_t (*)(PyObject*) {aka long long int (*)(_object*)}' to 'hashfunc {aka long int (*)(_object*)}' [-fpermissive]
         type->tp_hash = &enum_hash;

**Comment by Alexpux** [comment]
Yeah. This is need to be fixed in shiboken after removing patch https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-shiboken-qt4/shiboken.patch#L47-L57

**Comment by MrKepzie** [comment]
I did remove this patch part but then I get other cast errors at other places, I cannot paste the errors right now I'm on another computer

**Comment by Alexpux** [comment]
This is shiboken issue that I try to solve in the past. Right now I have no time to fix it as I'm on vacation

**Comment by Alexpux** [comment]
Fixed & uploaded.
