### ISSUE TITLE
Installing the toolchain renders the environment unusable

### ISSUE THREAD

**Issue by rafalcieslak** [Alexpux/MINGW-packages#755]
Steps to reproduce:
1. Create a new MSYS installation using the MSYS2 installer (https://msys2.github.io/).
2. Check that the `uname` program works correctly.
3. Update the package list: `pacman -Sy`.
4. Download and install the toolchain: `pacman -S mingw-w64-x86_64-toolchain`.
5. Run the `uname` program again, it will output `bash: /usr/bin/uname: Permission denied
`.

This happened to me for the first time when I recently performed update with pacman (this was my first update in the last 2-3 weeks, so I assume this bug was recently introduced with one of these updates). I have been trying to pin down which package upgrade caused the problem, but I was not able to find a particular one - maybe the issue is caused by a particular combination of packages. Updating the runtime with `update-core` does not fix this error, and it does not prevent it when issued before installing toolchain.

I have successfully reproduced this issue on various machines (all running windows7 64bit).

Other potentially useful symptoms of this problem include:

```
$ env
bash: /usr/bin/env: Permission denied
$ strace uname
strace.exe: error creating process uname, (error 5)
$ file /usr/bin/uname
/usr/bin/uname: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

`/usr/bin/uname` has read/write/execute access, and I can `touch` it successfuly.

I am not certain whether I reported this bug against the right project, if not, please point me where else should I go.

I will be happy to assist with troubleshooting this bug, in case you require more information.

**Comment by elieux** [comment]
Weird. Can you `getfacl /usr/bin/uname`?

**Comment by elieux** [comment]
Closing for lack of follow-up. Sorry for the late reply.
