### ISSUE TITLE
qt5-static issues

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MINGW-packages#762]
- Some functionality of Qt seems to be missing:  
`qconfig.h` defines `QT_NO_SHAREDMEMORY` and `QT_NO_SYSTEMSEMAPHORE`
- In the link line, there is `-L$[QT_INSTALL_LIBS]`
- there also ends up `Qt5::UiPlugin-NOTFOUND` in the resulting makefiles without any CMake error

**Comment by mingwandroid** [comment]
Please share a test project.

**Comment by Optiligence** [comment]
```
project(qt5-static_issues)
cmake_minimum_required(VERSION 3.0)

set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}" "D:/msys64/mingw64/qt5-static")

find_package(Qt5 5.4 REQUIRED COMPONENTS Core Gui UiTools)

file(GLOB SRC_LIST *.cpp *.h)

add_executable(${PROJECT_NAME} ${SRC_LIST})
target_link_libraries(${PROJECT_NAME}
	Qt5::Core
	Qt5::Gui
	Qt5::UiTools
)
```
```
#include <QSharedMemory>

int main() {
	QSharedMemory mem;
}
```

**Comment by mingwandroid** [comment]
Seems that the update to 5.5.0 broke it. I will investigate this after work.

**Comment by mingwandroid** [comment]
AFAICT, the commit that's causing at least some of these problems is:

http://code.qt.io/cgit/qt/qtbase.git/commit/?id=a6f223f8c892a8d83df90ba623d462fd1569ea80

5.5.0 needs more work, can you use the previous version until I get it fixed (5.4.2)?

**Comment by Optiligence** [comment]
Thanks a lot for your work. 
Unfortunately https://github.com/Alexpux/MINGW-packages/commit/b10a4c66ddf001d7467d43403fa6ecbefb002825#diff-ffc9a5a6e396fdadbc6ef220d54f48d9R7 doesn’t work. 
I think it should be something like this (not tested yet): 
`string(REPLACE \"$$[QT_INSTALL_LIBS]\" ${$${CMAKE_MODULE_NAME}_install_prefix}/lib static_depends \"${static_depends}\")`

Why did you change the installation prefix to include the version?

**Comment by mingwandroid** [comment]
No problem, sorry I didn't notice it was broken before your report, I've been on other adventures.

The prefix was changed by mistake, but there's still an issue that I need to fix before it's usable, so hold tight. Shouldn't take me too long but I won't be able to take a look for a few hours yet.

**Comment by mingwandroid** [comment]
It should be ok now, you'll need to build it yourself for now. Re-open if there's any problems.

Cheers!
