### ISSUE TITLE
limits.h is missing

### ISSUE THREAD

**Issue by chaffra** [Alexpux/MINGW-packages#765]
Hi,

I relocated my msys64/mingw64 directory to a different location. Now I cannot compile my program. I am getting the error below. It looks like limits.h is missing from my mingw64/include folder but everthing works fine when compiling with the gcc in msys64/mingw64/bin. Any ideas ?

Thanks,
Chaffra

```
C:...\release\bin/x86_64-w64-mingw32-gcc.exe -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -DNDEBUG -DNDEBUG -IC:.../release/include/python2.7 -c ffc_form_7bd6577c10bbcb804be59fc66abf7e2cc66554aa_wrap.cxx -o build/temp.mingw-2.7/ffc_form_7bd6577c10bbcb804be59fc66abf7e2cc66554aa_wrap.o -O2 -std=c++11

In file included from C.../release/lib/gcc/x86_64-w64-mingw32/5.2.0/include-fixed/syslimits.h:7:0,

                 from C:.../release/lib/gcc/x86_64-w64-mingw32/5.2.0/include-fixed/limits.h:34,

                 from C:.../release/include/python2.7/Python.h:19,

                 from ffc_form_7bd6577c10bbcb804be59fc66abf7e2cc66554aa_wrap.cxx:168:

C:.../release/lib/gcc/x86_64-w64-mingw32/5.2.0/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
```

**Comment by mingwandroid** [comment]
We don't support moving directories like this. MSYS2 is a complete system and many things depend on a fixed layout (relative to the root folder).

**Comment by chaffra** [comment]
Ok. do you mind explaining what's happening with the include_next directives in stddef.h for example. My build breaks here; where is the next stddef.h?

**Comment by mingwandroid** [comment]
Not really, you're not using MSYS2 correctly then asking why it breaks.

If you want to persist with this, then use gcc -v to see the folders that GCC is looking in and compare the correct version vs the one you broke.

**Comment by mingwandroid** [comment]
or gcc --save-temps can be useful then looking at the .i or .ii files.

**Comment by chaffra** [comment]
limits.h is in /msys64/mingw64/x86_64-w64-mingw32. I has forgotten to copy that directory to the new location. Everything works now.

**Comment by mingwandroid** [comment]
Please don't use MSYS2 like this, or if you do, be explicit (as you were here, thanks!) every time you report a bug that you've decided to move folders around arbitrarily.

You understand that you can't use pacman -Syu to update your GCC package now?

**Comment by chaffra** [comment]
Yes I do. This is because I am trying to use mingw-gcc as a just in time compiler. The user won't need to update with pacman but the compiler needs to be self-contained as it is here.
