### ISSUE TITLE
g++ deprecated warning spam

### ISSUE THREAD

**Issue by marekr** [Alexpux/MINGW-packages#766]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65974

gcc5.1 and 5.2 "broke" their detection of deprecation attributes. It will spam your log with warnings even if the function is not being used, just declared. It was fixed upstream a bit over week ago. Might be nice to backport.

This hampers building with wxwidgets which makes very liberal usage of the deprecated attribute in headers and you have -Wall turned on. KiCad is affected by this.

**Comment by mingwandroid** [comment]
Submit a pull request with the new patch please.
