### ISSUE TITLE
Rebuild ctags

### ISSUE THREAD

**Issue by oscarfv** [Alexpux/MINGW-packages#769]
`ctags` `PKGBUILD` was updated time ago for fixing a bug that affects a whole set of features (related to regex support). However, the binary package was not rebuilt.

Please rebuild and publish the binary package.

In addition, it would be a good thing to provide a binary package for `universal-ctags-git`. It provides an up-to-date ctags implementation with lots of fixes and quite a few new features. I'm not certain about how much backwards compatibility this package maintains wrt `ctags`, though. Definitely `universal-ctags-git` will be preferred by those using modern programming languages (such as C++11).

**Comment by Alexpux** [comment]
Fixed.
