### ISSUE TITLE
meld binary has incorrect path to python2.exe

### ISSUE THREAD

**Issue by DavidEGrayson** [Alexpux/MINGW-packages#775]
The first line of the file `/mingw32/bin/meld` in the meld3 package contains the absolute path to python2.exe, and the path is wrong.

Here is a Win32 shell session showing the problem:

~~~~
$ pacman -Qo /mingw32/bin/meld
/mingw32/bin/meld is owned by mingw-w64-i686-meld3 3.13.2-1
$ head -n1 /mingw32/bin/meld
#!C:/building/msys32/mingw32/bin/python2.exe
$ meld
bash: /mingw32/bin/meld: C:/building/msys32/mingw32/bin/python2.exe: bad interpreter: Permission denied
~~~~

**Comment by DavidEGrayson** [comment]
If I fix the first line of `/mingw32/bin/meld` then I can run meld and it kind of works.  Unfortunately, though, it acts as if ARGV[0] (which is `/mingw32/bin/meld`) is the first user-provided argument, so it always shows its own source code on the left side of the window.  Of course this is not what you want; you want to use meld to compare the files you care about instead of being forced to compare your files to `/mingw32/bin/meld`.

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/ee0ebc29fac363b3c88b4011d8b6d1a9f2f8662c
