### ISSUE TITLE
Latest mingw headers update broke FFmpeg with d3d11va

### ISSUE THREAD

**Issue by wiiaboo** [Alexpux/MINGW-packages#778]
The [d3d11 video decoder](https://github.com/Alexpux/MINGW-packages/blob/e629b3add67e2765026380e28a1535eb5af5266f/mingw-w64-headers-git/0006-Add-d3d11-video-decoder.patch) seems to still be needed.

See https://github.com/jb-alvarado/media-autobuild_suite/issues/160#issue-106024990 for the exact issue.

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/262196808193c6e9abe406ad4a72a800a44ef638
