### ISSUE TITLE
vlc-git dependency conflicts

### ISSUE THREAD

**Issue by kyonifer** [Alexpux/MINGW-packages#783]
Looks like after d16a69652667ff344d928315939544ab5475e429 VLC wont install (its sub dependencies pull in both dcadec-git and libdca-svn).

**Comment by Alexpux** [comment]
Yeah, need decide how to properly fix it

**Comment by Alexpux** [comment]
Fixed.

**Comment by kyonifer** [comment]
Awesome thanks!
