### ISSUE TITLE
looks like python2-pyqt4 is missing from repo

### ISSUE THREAD

**Issue by chaffra** [Alexpux/MINGW-packages#784]
Is there a particular reason pyqt4 is missing from repo? It seems to be present in PKGBUILD.

$ pacman -Ss qt4
mingw32/mingw-w64-i686-qt4 4.8.7-3 (mingw-w64-i686-qt4)
mingw64/mingw-w64-x86_64-qt4 4.8.7-3 (mingw-w64-x86_64-qt4)

**Comment by Alexpux** [comment]
Uploaded.

**Comment by chaffra** [comment]
Thanks, but now I am getting

$ pacman -Su mingw-w64-x86_64-python2-pyqt4
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-python2-pyqt4-4.11.4-1

Total Installed Size:  18.92 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                               [###############################] 100%
(1/1) checking package integrity                             [###############################] 100%
(1/1) loading package files                                  [###############################] 100%
(1/1) checking for file conflicts                            [###############################] 100%
error: failed to commit transaction (conflicting files)
mingw-w64-x86_64-python2-pyqt4: /mingw64/share/qt4/qsci/api/python/PyQt4.api exists in filesystem
Errors occurred, no packages were upgraded.

**Comment by Alexpux** [comment]
Remove previously installed pyqt4 packages.
