### ISSUE TITLE
Python 3.5.0

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#791]
I'd like to know if you guys are working on porting Python 3.5 to MinGW. It adds a whole bunch of features that I'd like to use (namely the async/await syntax)

**Comment by Alexpux** [comment]
Currently no. We have lot of other work, so Python-3.5.x will be later when we have time

**Comment by BrisingrAerowing** [comment]
OK.

**Comment by Alexpux** [comment]
I'm push WIP work on Python 3.5. Right now one extension fail to build. Will see it later. You can try fix it yourself or wait

**Comment by Alexpux** [comment]
Uploaded Python 3.5.0
