### ISSUE TITLE
nuitka: issues with bundled scons

### ISSUE THREAD

**Issue by achadwick** [Alexpux/MINGW-packages#792]
I'm trying to get nuitka running under msys2, and I'm having trouble with its bundled SCons:

``` python
#!/usr/bin/env python2

if __name__ == '__main__':
    print("Hello, world!")
```

``` sh
$ nuitka hello1.py
Error, need to find Python2 executable under C:\Python26 or C:\Python27 to execute scons which is not Python3 compatible.
$ nuitka2 hello1.py
AttributeError: 'FS' object has no attribute '_cwd':
  File "C:/msys64/mingw64/lib/python2.7/site-packages/nuitka/build/inline_copy/bin/../lib/scons-2.3.2/SCons/Script/Main.py", line 1367:
    _exec_main(parser, values)
  File "C:/msys64/mingw64/lib/python2.7/site-packages/nuitka/build/inline_copy/bin/../lib/scons-2.3.2/SCons/Script/Main.py", line 1330:
    _main(parser)
  File "C:/msys64/mingw64/lib/python2.7/site-packages/nuitka/build/inline_copy/bin/../lib/scons-2.3.2/SCons/Script/Main.py", line 897:
    fs = SCons.Node.FS.get_default_fs()
  File "C:/msys64/mingw64/lib/python2.7/site-packages/nuitka/build/inline_copy/bin/../lib/scons-2.3.2/SCons/Node/FS.py", line 3242:
    default_fs = FS()
  File "C:/msys64/mingw64/lib/python2.7/site-packages/nuitka/build/inline_copy/bin/../lib/scons-2.3.2/SCons/Node/FS.py", line 1130:
    self.Top = self.Dir(self.pathTop)
  File "C:/msys64/mingw64/lib/python2.7/site-packages/nuitka/build/inline_copy/bin/../lib/scons-2.3.2/SCons/Node/FS.py", line 1352:
    return self._lookup(name, directory, Dir, create)
  File "C:/msys64/mingw64/lib/python2.7/site-packages/nuitka/build/inline_copy/bin/../lib/scons-2.3.2/SCons/Node/FS.py", line 1285:
    directory = self._cwd
```

The final error is something I've seen a lot when attempting to use `scons-local` for compiling MyPaint. The MSYS2 SCons does not suffer from this now.

It looks as if Nuitka's `setup.py` has instructions to use the installed SCons if `/usr/bin/scons` exists at the time it is run, but for some reason this isn't being executed, meaning that the `inline_copy` files are being installed and confusing Nuitka.

**Comment by DavidEGrayson** [comment]
I thought the MSYS2 way was to avoid having copies of programs bundled in other programs.  If Nuitka wants to run scons, it should just use the first one available on the path.

MinGW programs do not really understand paths like /usr/bin/scons.  The / corresponds to C:/ instead of the root directory of MSYS2.

**Comment by achadwick** [comment]
Putting together a patch for that too :D
On MSYS2 - and in fact all Win32 systems - it should be calling the Python2 interpreter .exe with /usr/bin/scons as an argument - or rather, '<results-of-pathsearch>/scons'. It's trying, but failing for a number of reasons, not the least of which is it's expecting a pre-MSYS2 c:\PythonNN install.

**Comment by DavidEGrayson** [comment]
There isn't a mingw-w64 scons package.  I think you are trying to make a mingw-w64 nuitka package that calls the msys-2.0.dll-based Python 2 to run scons.  Is it normal for mingw-w64 packages to depend on msys2 packages?   It means that the nuitka package isn't really a native Windows app.

**Comment by achadwick** [comment]
As I said: /usr/bin/scons.

Well, I got somewhere - but SCons is a tricky beast. It really wants to be invoked with a Python in its $PREFIX so that it can find all of its libs:

```
Test User@win7test MINGW64 /g/MyPaintProject/mypaint
$ /usr/bin/python2.exe /usr/bin/scons --version
SCons by Steven Knight et al.:
        script: v2.3.4, 2014/09/27 12:51:43, by garyo on lubuntu
        engine: v2.3.4, 2014/09/27 12:51:43, by garyo on lubuntu
        engine path: ['/usr/lib/python2.7/site-packages/SCons']
Copyright (c) 2001 - 2014 The SCons Foundation

Test User@win7test MINGW64 /g/MyPaintProject/mypaint
$ /mingw64/bin/python2.exe /usr/bin/scons --version
Import failed. Unable to find SCons files in:
  C:/msys64/usr/bin/../engine
  C:/msys64/usr/bin/scons-local-2.3.4
  C:/msys64/usr/bin/scons-local
  C:/msys64/mingw64/scons-2.3.4
  C:/msys64/mingw64/Lib/site-packages/scons-2.3.4
  C:/msys64/mingw64/scons
  C:/msys64/mingw64/Lib/site-packages/scons
Traceback (most recent call last):
  File "C:/msys64/usr/bin/scons", line 190, in <module>
    import SCons.Script
ImportError: No module named SCons.Script

```

so my path-searching thing isn't going to work neatly. Shame! It seemed so elegant.

Nuitka is a development tool for use in native build pipelines, and those can be native and depend on MSYS2 binaries via shellouts. I _think_ that's allowable in the "MSYS2 way", but I may well be wrong.

I think we've found a corner case here though: Alexpux/MSYS2-packages#352. Either Nuitka belongs with SCons in nativeland, or scons belongs with Nuitka in cygwinland :D  I kinda prefer the former, since native SCons is quite likely to break in my experience - it needs a *lot* of hand-holding.

**Comment by Alexpux** [comment]
No one mingw package will depend on msys2 package. S o you need fix nuitka to work with mingw scons (providing scons package for mingw) or move nuitka to msys packages and build it with msys-python.
