### ISSUE TITLE
gtksourceviewmm3 needed

### ISSUE THREAD

**Issue by eidheim** [Alexpux/MINGW-packages#799]
like gtk3 has gtkmm3, gtksourceview3 has gtksourceviewmm3. Though the versions of gtksourceviewmm are not updated as often as gtksourceview (https://developer.gnome.org/gtksourceviewmm/), 3.12 for instance works together with gtksourceview up to, but not including, 3.18. In other words, when gtksourceview3.18 is accepted, gtksourceviemm3.18 should be used. 

To create a package for gtksourceviewmm3.12, gtksourceview3.12 is needed I think, but just to build it. See https://github.com/cppit/jucipp/tree/master/MINGW-packages for working package sources for both.

**Comment by Alexpux** [comment]
You can create pull request for gtksourceviewmm3 but don't hardcode version. I will build gtksourceview-3.18 instead 3.12

**Comment by Alexpux** [comment]
I'm add "gtksourceviewmm3" package myself.

**Comment by eidheim** [comment]
Thank you!
