### ISSUE TITLE
Update mingw-w64-gcc to the 5.1

### ISSUE THREAD

**Issue by XVilka** [Alexpux/MINGW-packages#801]
Since gcc-5.1 is the latest stable release (5.0 wasn't released due to the critical regressions), please update the package too.

**Comment by DavidEGrayson** [comment]
If you update your packages, you should get gcc version 5.2.0.  You can also look at the version number in the [mingw-w64-gcc PKGBUILD script](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gcc/PKGBUILD).

**Comment by XVilka** [comment]
Sorry, somehow my update script failed. Closing.
