### ISSUE TITLE
gtk3: fails in build() during GISCAN "recipe for target 'Gdk-3.0.gir' failed"

### ISSUE THREAD

**Issue by achadwick** [Alexpux/MINGW-packages#808]
From a fresh, upgraded installation of msys2-x86_64-20150916, plus:

```
$ pacman -S mingw-w64-x86_64-toolchain mingw-w64-i686-toolchain base-devel
```

`mingw-w64-gtk3` fails to build with `makepkg-mingw -sfL`:

```
[...]
make[4]: Leaving directory '/g/MINGW-packages/mingw-w64-gtk3/src/x86_64-w64-mingw32/gdk/broadway'
Making all in .
make[4]: Entering directory '/g/MINGW-packages/mingw-w64-gtk3/src/x86_64-w64-mingw32/gdk'
  CC       libgdk_3_la-gdkcolor.lo
  CC       libgdk_3_la-gdk.lo
  CC       libgdk_3_la-gdk-private.lo
[...]
  CC       libgdk_3_la-gdkwindowimpl.lo
  CC       libgdk_3_la-gdkenumtypes.lo
  CC       libgdk_3_la-gdkmarshalers.lo
  GEN      gdkconfig.h
  CCLD     libgdk-3.la
  GISCAN   Gdk-3.0.gir
Command '['G:\\MINGW-packages\\mingw-w64-gtk3\\src\\x86_64-w64-mingw32\\gdk/tmp-introspectalaywx/Gdk-3.0.exe', '--introspect-dump=G:\\MINGW-packages\\mingw-w64-gtk3\\src\\x86_64-w64-mingw32\\gdk/tmp-introspectalaywx/functions.txt,G:\\MINGW-packages\\mingw-w64-gtk3\\src\\x86_64-w64-mingw32\\gdk/tmp-introspectalaywx/dump.xml']' returned non-zero exit status -1073741765
/mingw64/share/gobject-introspection-1.0/Makefile.introspection:176: recipe for target 'Gdk-3.0.gir' failed
make[4]: *** [Gdk-3.0.gir] Error 1
make[4]: Leaving directory '/g/MINGW-packages/mingw-w64-gtk3/src/x86_64-w64-mingw32/gdk'
Makefile:1448: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/g/MINGW-packages/mingw-w64-gtk3/src/x86_64-w64-mingw32/gdk'
Makefile:955: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/g/MINGW-packages/mingw-w64-gtk3/src/x86_64-w64-mingw32/gdk'
Makefile:717: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/g/MINGW-packages/mingw-w64-gtk3/src/x86_64-w64-mingw32'
Makefile:611: recipe for target 'all' failed
make: *** [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

No fancy build options, just trying to build from fresh.

**Comment by Alexpux** [comment]
Try build again. This error is happen time to time

**Comment by achadwick** [comment]
I've tried rebuilding this many times, without success (though #811 came out of it usefully). Is there anything I'm missing?

Try making a clean, fresh install as above to reproduce, and please just ask if you need any further information about the systems I'm trying this on.

**Comment by Alexpux** [comment]
Do you have installed Python from official binaries?

**Comment by achadwick** [comment]
@Alexpux No; just MSYS2 (MINGWxx and MSYS) pythons from the repo binary packages. I also don't use any separate compilers or build tools other than the MSYS2 ones detailed above.

**Comment by Alexpux** [comment]
Will it be builded if you run build on drive "C"?

**Comment by achadwick** [comment]
That "G:" is a VirtualBox shared folder on the host machine that presents as a mapped share (`\\vboxsvr\whatever`) on Windows boxes. I don't know if it's actually speaking CIFS/SMB or bound in any way by its filesystem semantics, so I'll give it a try. Thanks.

**Comment by achadwick** [comment]
Okay, results. From msys2_shell.bat, with *fresh* git clones into specific path prefixes:

* `/c/MINGW-packages` (VM's C: drive, cloned using msys2 git): built successfully!
* `/tmp/MINGW-packages` (VM's C: drive, cloned using msys2 git): build progressed beyond the point above, at which point I Ctrl-C'ed it.
* `/g/_tmp/MINGW-packages` (VM's G: drive, cloned using VM host's git): fails to build in the exact manner described above.

So either it's the host git at fault, or the gtk3 PKGBUILD is constrained by the limitations of the filesystem semantics on the drive you run the build from. However I trust that host git enough to be reasonably certain it's not causing any issues :stuck_out_tongue_winking_eye: 

Moral: build big complicated stuff like gtk3 on a normal locally-attached disk such as the C: drive. Doesn't seem to matter if that disk is virtual hardware or real, but shared folders appear to break this particular build.
