### ISSUE TITLE
evince has trouble loading pango library

### ISSUE THREAD

**Issue by oroppas** [Alexpux/MINGW-packages#815]
C:/msys64/mingw64/bin/evince.exe: error while loading shared libraries: libpango-1.0-0.dll: cannot open shared object file: No such file or director

I double-checked pango is already installed:

$ ls /mingw64/bin/libpango-1.0-0.dll
/mingw64/bin/libpango-1.0-0.dll*

**Comment by DavidEGrayson** [comment]
Well, I installed mingw-w64-x86_64-evince on my machine and I can't reproduce this.  Maybe try eliminating everything from your PATH in case a bad DLL from some other part of your system is being loaded?

**Comment by oroppas** [comment]
The error disappeared after installing mingw-w64-x86_64-gst-plugins-base. Not sure if evince explicitly depends on gst-plugins-base, though.

**Comment by Red54** [comment]
@DavidEGrayson 

I met the same problem, and it fixed after installing mingw-w64-x86_64-gst-plugins-base.

Maybe you should add mingw-w64-x86_64-gst-plugins-base as a dependence of mingw-w64-x86_64-evince.
