### ISSUE TITLE
Cython 0.23.3

### ISSUE THREAD

**Issue by htzh** [Alexpux/MINGW-packages#819]
Is there a reason why the current packaged Cython is behind the official release by a few steps? I had trouble with the pacman installed Cython but the pip installed Cython works. See https://github.com/honnibal/spaCy/issues/132

If you update the packaged Cython I will be happy to test it and report back if the difference persists. Then we would know if it was a problem with a particular version of Cython or a problem with the MinGW build.

**Comment by Alexpux** [comment]
Uploaded 0.23.4

**Comment by htzh** [comment]
Thanks. Now pacman installed Cython works the same as pip installed one. Good to know that it is not a build issue.
