### ISSUE TITLE
Update to Qt 5.5.1 please ?

### ISSUE THREAD

**Issue by mcallegari** [Alexpux/MINGW-packages#827]
Just released.
It fixes interesting issues, especially one on the UDP sockets that I would like to deploy in my project.

Thanks

**Comment by mcallegari** [comment]
Hey, I've seen this 3a1f9d4a3f3331777b195f947cb52f2a54815f7d but it's a WIP ?
Are there particular issues with 5.5.1 compared to 5.5.0 ?
Any ETA ?

Thanks !

**Comment by Alexpux** [comment]
Currently we can't build Qt-5.5.1 as we have issue with linking with error "file too big"

**Comment by mcallegari** [comment]
Curious. Is that a debug or a release build ?

Qt debug builds can be evil, especially packing QtWebkit/QtWebEngine

**Comment by mcallegari** [comment]
Is it building now after 4a90a5f2999fa8fba0e074695e5ee7f03e8f94aa ?

**Comment by Alexpux** [comment]
Already uploaded

**Comment by mcallegari** [comment]
Nice, thanks !
Please have a look at #851 when you can.
I think it can be of interest for many users.
