### ISSUE TITLE
Segmentation fault in GIMP's animation-optimize.exe

### ISSUE THREAD

**Issue by DavidEGrayson** [Alexpux/MINGW-packages#828]
I just updated my packages and noticed that 64-bit GIMP got updated.  Now, when I launch GIMP through a taskbar shortcut or by double-clicking on it in Windows Explorer, I am greeted with this error message:

> animation-optimize.exe - Application Error
> 
> The application was unable to start correctly (0xc0000005).  Click OK to close the application.

![image](https://cloud.githubusercontent.com/assets/466764/10533432/0649954c-737e-11e5-96e7-3c5b0e40ac35.png)

This error message is not shown when you launch GIMP from bash, so I can understand how it would have been missed.

I think a related fact is that when I try to run `/mingw64/lib/gimp/2.0/plug-ins/animation-optimize.exe` from the Win64 shell, it just prints `Segmentation fault` and exits.

**Comment by Alexpux** [comment]
Fixed in 2.8.14-9

**Comment by DavidEGrayson** [comment]
Great!
