### ISSUE TITLE
qt5 prevents use of qt5-static

### ISSUE THREAD

**Issue by athairus** [Alexpux/MINGW-packages#829]
I'm still working this out, but it seems that the static version of Qt 5, at the very least, fails to define `Q_OS_WIN64` like the non-static version does. Defining this manually via the .pro file of my project causes more errors involving conflicting Qt headers:

I use other libraries in my project that are available in `/mingw64`. This prefix is apparently not used at all when using the static kit. Instead, the static Qt prefix is used: `/mingw64/qt5-static`. However, I *need* those other libraries. It seems like my choice is to either abandon using the static version of Qt, manually copy what I need into the static prefix or uninstall the non-static Qt for the duration of the compile. Are they meant to be mutually incompatible? Why not just put the non-static Qt in its own prefix?

**Comment by athairus** [comment]
I've built a fresh copy using the mingw64 compilers using this script: 
https://wiki.qt.io/Building_a_static_Qt_for_Windows_using_MinGW
https://sourceforge.net/p/qtlmovie/code/ci/master/tree/build/windows-build-qt-static.ps1?format=raw

Same problem, `Q_OS_WIN` isn't defined, let alone `Q_OS_WIN64`. Weird.

**Comment by mingwandroid** [comment]
Why did you use that build script? Our build script (and numerous necessary patches) for qt5-static is here: https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-qt5-static

If you need to use qt5-static with libraries located in /mingw64 you should add them to the .pro file as LIBS += -L/mingw64/lib -lsomelib
