### ISSUE TITLE
CMAKE :  Argument list too long

### ISSUE THREAD

**Issue by tenko** [Alexpux/MINGW-packages#835]
make fails with message:
"
/bin/sh: /C/msys64/mingw64/bin/ar.exe: Argument list too long
"
During configure CMake reports:
"
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_NEED_RESPOSE
"

The build type is set to "MSYS Makefiles" with the setting:
"
   -G"MSYS Makefiles"
"

Eariler the builds worked fine with the fix activated with parameter "CMAKE_NEED_RESPOSE"
on the CMake command line. However it seems now to not be activated anymore.

**Comment by Alexpux** [comment]
Because typo is fixed. You need pass CMAKE_NEED_RESPO**N**SE
