### ISSUE TITLE
KiCad issues with Boost 1.59.

### ISSUE THREAD

**Issue by stambaughw** [Alexpux/MINGW-packages#836]
There is a known bug in Boost 1.59 that causes the KiCad build to fail.  It is due to a bug in Boost 1.59:

https://github.com/boostorg/uuid/pull/6

There is a patch that fixes the build problem here:

https://github.com/tabe/uuid/commit/a19682a4cf46b7d95ea03ce74f22408bf92350df

I've tested the patch and it does resolve the build issue.  Unfortunately, kicad crashes when launching pcbnew due to the new context switch library.  If you want to be able to build and use KiCad, your going to have to stick with Boost 1.57 for the time being.  I know Boost provided their own gnu assembler files for the context library which were previously provided by a patch.  I don't know how much different the new Boost context library code is compared to the 1.57 patch but there is definitely an issue.

Here is the gdb back trace of the segfault:
#0  0x0000000067b814f0 in ?? ()

   from c:\msys64\mingw64\bin\libboost_context-mt.dll
#1  0x000000000b0b8ca4 in COROUTINE<int, TOOL_EVENT const&>::Call (

```
this=0x5b096b70, aArgs=...)
at C:/msys64/home/wstambaugh/src/kicad/product/include/tool/coroutine.h:161
```
#2  0x000000000ae82331 in TOOL_MANAGER::dispatchInternal (this=0x5b0609f0,

```
aEvent=...)
at C:/msys64/home/wstambaugh/src/kicad/product/common/tool/tool_manager.cpp:541
```
#3  0x000000000ae82d3a in TOOL_MANAGER::ProcessEvent (this=0x5b0609f0,

```
aEvent=...)
at C:/msys64/home/wstambaugh/src/kicad/product/common/tool/tool_manager.cpp:665
```
#4  0x000000000ae81154 in TOOL_MANAGER::invokeTool (this=0x5b0609f0,

```
aTool=0x5b083100)
at C:/msys64/home/wstambaugh/src/kicad/product/common/tool/tool_manager.cpp:352
```
#5  0x000000000ae80ca2 in TOOL_MANAGER::InvokeTool (this=0x5b0609f0,

```
aToolName="pcbnew.InteractiveSelection")
at C:/msys64/home/wstambaugh/src/kicad/product/common/tool/tool_manager.cpp:276
```
#6  0x000000000a809f41 in PCB_EDIT_FRAME::setupTools (this=0x58e1d140)

```
at C:/msys64/home/wstambaugh/src/kicad/product/pcbnew/pcbframe.cpp:546
```
#7  0x000000000a8094d6 in PCB_EDIT_FRAME::PCB_EDIT_FRAME (this=0x58e1d140,

```
aKiway=0x4ea0e0 <Kiway>, aParent=0x36e1d0)
at C:/msys64/home/wstambaugh/src/kicad/product/pcbnew/pcbframe.cpp:454
```
#8  0x000000000afc16a7 in PCB::IFACE::CreateWindow (

```
this=0xb7a8260 <PCB::kiface>, aParent=0x36e1d0, aClassId=4,
aKiway=0x4ea0e0 <Kiway>, aCtlBits=2)
at C:/msys64/home/wstambaugh/src/kicad/product/pcbnew/pcbnew.cpp:120
```
#9  0x000000000042ee68 in KIWAY::Player (this=0x4ea0e0 <Kiway>,

```
aFrameType=FRAME_PCB, doCreate=true)
at C:/msys64/home/wstambaugh/src/kicad/product/common/kiway.cpp:304
```
#10 0x000000000040c885 in KICAD_MANAGER_FRAME::RunPcbNew (this=0x36e1d0,

```
aProjectBoardFileName=...)
at C:/msys64/home/wstambaugh/src/kicad/product/kicad/mainframe.cpp:346
```
#11 0x000000000040cac1 in KICAD_MANAGER_FRAME::OnRunPcbNew (this=0x36e1d0,

```
event=...)
at C:/msys64/home/wstambaugh/src/kicad/product/kicad/mainframe.cpp:373
```
#12 0x0000000066ac32a6 in ?? ()

   from c:\msys64\mingw64\bin\wxbase30u_gcc_custom.dll
#13 0x0000000066c23b5e in ?? ()

   from c:\msys64\mingw64\bin\wxbase30u_gcc_custom.dll
#14 0x0000000066c23c63 in ?? ()

   from c:\msys64\mingw64\bin\wxbase30u_gcc_custom.dll
#15 0x0000000066c24038 in ?? ()

   from c:\msys64\mingw64\bin\wxbase30u_gcc_custom.dll
#16 0x00000000004202fb in EDA_BASE_FRAME::ProcessEvent (this=0x36e1d0,

```
aEvent=...)
at C:/msys64/home/wstambaugh/src/kicad/product/common/basicframe.cpp:167
```
#17 0x0000000066c23e33 in ?? ()

   from c:\msys64\mingw64\bin\wxbase30u_gcc_custom.dll
#18 0x0000000066c240f8 in ?? ()

   from c:\msys64\mingw64\bin\wxbase30u_gcc_custom.dll
#19 0x000000000634d8c5 in ?? ()

   from c:\msys64\mingw64\bin\wxmsw30u_core_gcc_custom.dll
(More stack frames follow...)

**Comment by Alexpux** [comment]
Create pull request to fix it then

**Comment by stambaughw** [comment]
I created a pull request that fixes the build error.  I did some more testing and the context library crash only happens on 64-bit builds.  The 32-bit builds work fine so I'll file a separate bug report for the 64 bit boost context library issue and see if I can figure out what got broken between Boost 1.57 and 1.59.

**Comment by nickoe** [comment]
@stambaughw Maybe this can be marked as closed now?
