### ISSUE TITLE
python3: multiprocessing is not fully supported.

### ISSUE THREAD

**Issue by yfwz100** [Alexpux/MINGW-packages#837]
I happen to use the multiprocessing lib in python 3 with this code:

```
from multiprocessing import Pool

def inc(a):
    return a + 1

with Pool(10) as p:
    print(p.map(inc, range(100)))
```

But it fail with this message:

```
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

How to solve it? The same program runs well on MSYS python 3.

**Comment by Alexpux** [comment]
MSYS python3 is like Linux python, while MINGW python is Windows python. Try to see issue 3770 on python bug tracker as recommended.

**Comment by BrisingrAerowing** [comment]
The MSVC build of Python uses a custom Semaphore implementation, but testing it failed with a rather bizarre error stating that the runtime tried to start a new process before the current one finished bootstrapping. I used the code provided in the OP to test with.

I'll have to figure out what went wrong. It seems to be related to the freeze support system, as that is mentioned at the bottom of the error.

**Comment by BrisingrAerowing** [comment]
The file the custom semaphore implementation is in is:
https://hg.python.org/cpython/file/v3.5.0/Modules/_multiprocessing/semaphore.c (Python 3.5)
https://hg.python.org/cpython/file/v2.7.10/Modules/_multiprocessing/semaphore.c (Python 2.7)
You may want to compile that in as well to get the Multiprocessing module working.

**Comment by mingwandroid** [comment]
Thanks for investigating. Unfortunately I am too busy with work to fix this for a few weeks.

**Comment by BrisingrAerowing** [comment]
I found that is is compiled, but the sem_unlink method is not provided on Windows. I simply forced Python to provide a no-op version of the method on Windows and got the test to work with a few changes:

``` python
from multiprocessing import Pool

def inc(a):
    return a + 1

	
def doit():
	with Pool(10) as p:
		print(p.map(inc, range(100)))
		
if __name__ == "__main__":
	doit()
```

I will create and provide a patch.

**Comment by BrisingrAerowing** [comment]
[Here's the patch](https://gist.github.com/BrisingrAerowing/10944f8d2e14dd49def8)

It should help. I am not good at shell scripting, so I will leave that up to you guys.

**Comment by yfwz100** [comment]
Know little about this. Otherwise, I will be glad to help...

**Comment by BrisingrAerowing** [comment]
@Alexpux @mingwandroid Any progress on this?

**Comment by mingwandroid** [comment]
I'm looking at this now, and since MSVC Python 3.5 doesn't work with this simple testcase, I'm keen to move away from winnt threads for multiprocessing and will try using winpthreads instead. Mainly, being agile enough to be able to switch between both APIs seems like a worthwhile goal. @yfwz100 , would it be possible for you to submit this testcase to bugs.python.org please?

@BrisingrAerowing, leaking semaphores here won't scale well. I would guess CloseHandle can be used in sem_unlink instead? If you can rework your patch to use that I will also be happy to try it, or if I have spare time after I test with winpthreads I may give it a go myself.

Thanks for your efforts.

**Comment by BrisingrAerowing** [comment]
@mingwandroid Are you using my modified testcase or the one in the original message? The original one is not structured correctly, so it won't work.

I'll look into updating the patch to use CloseHandle.

**Comment by BrisingrAerowing** [comment]
Odd. Firefox posted that when I minimized the window to check something. I will get to the patch when I get to building Python again. Should be within the next few hours.

**Comment by mingwandroid** [comment]
Ok thanks. I'll try to get time to merge it tomorrow.

**Comment by BrisingrAerowing** [comment]
Might take a while as I unintentionally 'rm -rf'-ed my /mingw64 directory, so I needed to restart and rebuild everything (I do packages in related sets, e.g. GCC and dependencies is the first set, then I do Python (2 & 3), Ruby (which seems to have a bug when building), and Perl (and their deps) and so on. I am working on the dependencies for Python right now. I just finished OpenSSL (after an hour fighting Windows 10, which randomly starting ignoring the executionLevel element in manifests for some reason and wanting EVERYTHING to run as Administrator, and after several reboots I ended up forcing a cold boot and got it working again)

**Comment by BrisingrAerowing** [comment]
I didn't reply right away as life has been hectic for me, what with work (from which I got laid off), various things at home, my mother (who I live with) going to Fort Wayne tomorrow to help one of my Uncles with a surgery, and a whole host of other curveballs that life threw at me.

I just want some peace and quiet, is that really to much to ask of life?

**Comment by BrisingrAerowing** [comment]
The semaphore.c file defines SEM_UNLINK to 0 on Windows, and to the sem_unlink function on other platforms. I am going to look at the Python modules and see how they work and whether the CloseHandle is actually needed.

**Comment by BrisingrAerowing** [comment]
It looks like it is. I am going to have to figure out how to get a Semaphore handle from the name. This might take a while. I am going to have to look at how the MSVC build does it.

**Comment by mingwandroid** [comment]
When you get this sorted, add yourself as a contributor to the PKGBUILD if you want; you'll have deserved it ;-)

**Comment by BrisingrAerowing** [comment]
I am opening the MSVC solution in VS to see what is defined (and where the defines are) and to see HOW this works.

This is going to be fun... maybe.

**Comment by BrisingrAerowing** [comment]
The MSVC solution does NOT define POSIX_SEMAPHORES_NOT_ENABLED, where defining it causes sem_unlink to NOT be included in the build. I will just add a patch to undefine it on Windows.

Should not take too long. I'll leave the sem_unlink implementation as-is and not make it no-op.

**Comment by mingwandroid** [comment]
Sounds .. weird, but then we know that multiprocessing on CPython 3.5 is at least pretty broken with the testcase from @yfwz100 .. I think I might need to spend some time investigating the latest CPython mercurial repository to see if they've fixed anything here recently. Seems like a bit of a mess overall.

**Comment by BrisingrAerowing** [comment]
Multiprocessing REQUIRES having the following code:

``` python
if __name__ == "__main__":
    do_it()
```

in the file. The original code does not have it so multiprocessing fails with an error message. That code allows multiprocessing to run the code as an actual process and keep track of the various processes it creates.

**Comment by BrisingrAerowing** [comment]
[Here is the patch](https://gist.github.com/BrisingrAerowing/496a62f422af1432cb46)

Not much to it. I recently caused bash to blow up spectacularly with a shell script (that I wrote), so I don't think I will be of much help with a PKGBUILD (also considering when I tried with expat I had about 97 commits and STILL didn't have it working... I gave up after that.) Shell Scripting and me do not mix well.
