### ISSUE TITLE
mingw-w64-zeromq static libraries

### ISSUE THREAD

**Issue by jeroen** [Alexpux/MINGW-packages#840]
Upstream issue: https://github.com/zeromq/libzmq/issues/1614.

I need static libraries for `libzmq`. Currently these are disabled in the autoconf script, but this [old post](http://grokbase.com/t/zeromq/zeromq-dev/136sg6zk4s/build-zmq-as-static-library-under-mingw) suggests they can be enabled with cflags `-DZMQ_STATIC -DFD_SETSIZE24`. Any suggestions for a patch (either upstream or in msys2) that would be really awesome.

**Comment by galeksandrp** [comment]
Did this problem persist? zeromq/libzmq#1615 fixes `--enable-static` behavior, which is currently enabled by https://github.com/Alexpux/MINGW-packages/commit/63f040d6e9a4687cd12b0ed711f9e984a6000f7b.
