### ISSUE TITLE
mingw-w64-mbedtls updated package (2.1.2) is missing in the repo

### ISSUE THREAD

**Issue by nazar554** [Alexpux/MINGW-packages#848]
I have pushed this [commit](https://github.com/Alexpux/MINGW-packages/commit/9976f360ab4ca757f6ab344ac4434ffd3d71d29a) almost 20 days ago, but still no update in repos. Is something wrong with the `PKGBUILD`?

**Comment by Alexpux** [comment]
Don't yet have time to build it. Will do on Monday
