### ISSUE TITLE
binutils-git: patch fail to apply

### ISSUE THREAD

**Issue by fracting** [Alexpux/MINGW-packages#850]
Dear folks,

I recently reported a MINGW ld crashes to binutils community, then binutils developer ask me to test the development version of ld [1], so I try to build binutils-git but the patches are out of date and fail to apply:

patching file configure
Hunk #1 succeeded at 2954 with fuzz 1 (offset 89 lines).
Hunk #2 succeeded at 2966 with fuzz 1 (offset 89 lines).
patching file binutils/bucomm.c
patching file binutils/elfedit.c
patching file binutils/readelf.c
Hunk #1 succeeded at 15561 (offset 948 lines).
Hunk #2 succeeded at 15580 (offset 948 lines).
patching file libiberty/Makefile.in
Hunk #1 succeeded at 130 with fuzz 1 (offset 1 line).
Hunk #2 succeeded at 155 (offset 1 line).
Hunk #3 succeeded at 172 (offset 1 line).
Hunk #4 succeeded at 221 (offset 1 line).
patching file libiberty/configure.ac
Hunk #1 succeeded at 372 (offset 37 lines).
Hunk #2 succeeded at 472 (offset 36 lines).
Hunk #3 succeeded at 482 (offset 36 lines).
Hunk #4 succeeded at 629 (offset 15 lines).
patching file libiberty/configure
Hunk #4 succeeded at 6321 (offset 13 lines).
patching file bfd/bfd-in.h
patching file bfd/bfd-in2.h
patching file binutils/dwarf.c
Hunk #1 FAILED at 140.
1 out of 1 hunk FAILED -- saving rejects to file binutils/dwarf.c.rej
patching file binutils/nm.c
Hunk #1 succeeded at 162 (offset -2 lines).
Hunk #2 succeeded at 292 (offset 2 lines).
patching file binutils/prdbg.c
patching file binutils/readelf.c
Hunk #1 succeeded at 1123 (offset 117 lines).
Hunk #2 succeeded at 11552 (offset 716 lines).
patching file binutils/strings.c
Hunk #1 FAILED at 557.
Hunk #2 FAILED at 576.
Hunk #3 FAILED at 595.
3 out of 3 hunks FAILED -- saving rejects to file binutils/strings.c.rej
patching file gas/read.c
Hunk #1 succeeded at 4322 (offset 29 lines).
patching file gas/as.h
patching file gold/configure
Hunk #1 succeeded at 7553 (offset 23 lines).
patching file gold/configure.ac
Hunk #1 succeeded at 615 (offset 14 lines).
patching file include/ansidecl.h

Could you update the patch set?

Thanks a lot!

[1] https://sourceware.org/ml/binutils/2015-10/msg00239.html

**Comment by mingwandroid** [comment]
I'll try to do this tomorrow @fracting.

**Comment by fracting** [comment]
Hi @mingwandroid , thanks for your help, and updates? ;-)

**Comment by mingwandroid** [comment]
Aah, I've gotten so busy with work that I forgot! I will try to do it this weekend. Apologies!

**Comment by fracting** [comment]
np, it's understandable, you are doing great, thanks!

**Comment by mingwandroid** [comment]
Hi @fracting, I've corrected the patches now.

Best regards.

**Comment by fracting** [comment]
Thanks @mingwandroid , I'm building now!

**Comment by mingwandroid** [comment]
Great. To debug, change options to include 'debug' and '!strip'

**Comment by fracting** [comment]
Thanks @mingwandroid , could I also CC you in https://sourceware.org/bugzilla/show_bug.cgi?id=19196 ?
