### ISSUE TITLE
[Package request] qt5-noicu

### ISSUE THREAD

**Issue by mcallegari** [Alexpux/MINGW-packages#851]
Hello everyone,
first of all let me say I love MSYS2. It makes building projects on Windows a piece of cake. Well done !

I have a project which makes extensive use of the Qt5 libraries and I would like to raise an issue concerning the deployment footprint. I've raised this already in the Sourceforge forum, but didn't get much interest. So here I am again, with a concrete example of the impact of how Qt5 is currently built in MINGW.

I have written a very simple HelloWorld application, based on QtWidget. It looks like this, very simple:

![2015-10-18_132015](https://cloud.githubusercontent.com/assets/2951337/10754869/d7794714-7c9a-11e5-8fe9-5c1d5f6ca664.png)

Then I prepared it for deployment, and this is the result:

![2015-10-19_202835](https://cloud.githubusercontent.com/assets/2951337/10754884/e6d70eb2-7c9a-11e5-9d68-e188b0f13dec.png)

As you can see, a stupidly simple application requires 50MB of space !
Half of it is cause of the ICU libraries which, as far as I know, are needed when deploying an application using QtWebKit or QtWebEngine.
At the moment I build ICU myself to obtain a minimal version of the libicudt55.dll with size 717Kb (instead of 24MB), but it's a workaround, not a solution.

My request is to create a new Qt5 package in MINGW built with the following flags:
-no-icu -skip qtwebkit -skip qtwebengine

This would have 2 benefits:
1) lighter deployment of applications
2) lighter MINGW package since QtWebKit and QtWebEngine would not be included (so faster to download)

I believe I wouldn't be the only one using this package as I've had quite a positive response from my stripped ICU libraries on StackOverflow: http://stackoverflow.com/questions/18914274/reducing-size-of-icudt51-dll/21814106#21814106

Thanks

**Comment by mingwandroid** [comment]
@mcallegari : It's too much work for us to do this, I believe Qt were talking about optionally implementing the native platform solutions for unicode handling. This is the path that we would pursue in this regard. Also, have you tried the qt5-static package? It can get self contained executables at around 20MB (but yes often much bigger too).

**Comment by mcallegari** [comment]
@mingwandroid I thought Qt was leaving the QtCore ICU dependency with 5.5.0, but that didn't happen.
I saw the qt5 static package but I can't use it, cause my bundle includes 2 applications sharing the same libraries.

I asked for this package cause I thought it was a subset of the qt5 package. Just built with different flags. 
Since I don't know every bit of it, may I ask in which terms this is too much work for you ?
Maintenance ? Porting ? Else ?

If you want, I am willing to contribute to this project and I can setup a building environment to eventually come up with a pull request.

**Comment by mingwandroid** [comment]
Time is one of the most precious commodities that I know of. Your application could maybe suffer the doubling up of the qt libraries when using qt5-static? I get that this isn't ideal and doesn't scale.

Building Qt5 and qt5-static take significant amounts of time. Fixing issues when the builds fail take significant amounts of time * amount of issues.

You are of course welcome to invest your time in maintaining a PKGBUILD that doesn't use ICU, provide QtWebKit or QtWebEngine and we'd probably consider merging the PKGBUILD here, but we wouldn't make builds of it. It'd need to be prefixed elsewhere too, like /mingw{32,64}/qt5-minimal or something. For us, maintaining builds for such an 'esoteric' variant for one users' use case* is definitely not something we can entertain, especially when we hope that upstream provides a solution to the size problem.

*I'm sure some other developers and users would also like this, but I doubt *most* people care too much in these days of large hard drives and fast broadband.

**Comment by DavidEGrayson** [comment]
A few years ago, before I knew about MSYS2, I made a Qt4 app using the official Qt tools and the DLL overhead was only 11.8 MB, so it is disappointing if that is going to jump to 50 MB when I make a Qt5 app with MSYS2.  However, that should get compressed to something less than 50 MB when I put it in my installer, so it should probably take less than 20 seconds to download on my class of internet connection.

Still, I'd be interested in some solution to make that smaller if it doesn't take up any of the MSYS2 developers' time.  Maybe we can replace some of the bigger DLLs with stubs that just return error codes at run time.

**Comment by DavidEGrayson** [comment]
I can confirm that a simple Qt Widgets or Qt Quick application requires 46.5 MB of DLLs.  The set of DLLs it requires is basically the same as @mcallegari's screenshot, except I find that libgcc_s_seh-1.dll is needed, not libgcc_s_dw2.dll.

I tried the qt5-static package and it seems to work, producing a single 15 MB executable that does not require any DLLs.

So if you have two Qt executables or less, and there are no legal issues with static linking, then you can save space by using the qt5-static package.

Question: Does anyone know if there are issues with using DLLs from a Qt5 static application?  I'm a bit worried that some DLL I might want to use would depend on libgcc_s_seh-1.dll and then I would end up distributing multiple copies of some of the functions in there: one copy would be in the DLL and one copy would be in the executable.  This might cause some sort of problem.

**Comment by mingwandroid** [comment]
On Mon, Nov 30, 2015 at 1:48 AM, David Grayson <notifications@github.com>
wrote:

> I can confirm that a simple Qt Widgets or Qt Quick application requires
> 46.5 MB of DLLs. The set of DLLs it requires is basically the same as
> @mcallegari <https://github.com/mcallegari>'s screenshot, except I find
> that libgcc_s_seh-1.dll is needed, not libgcc_s_dw2.dll.
>
> I tried the qt5-static package and it seems to work, producing a single 15
> MB executable that does not require any DLLs.
>
> So if you have two Qt executables or less, and there are no legal issues
> with static linking, then you can save space by using the qt5-static
> package.
>
Each person needs to verify this for themselves I think. We are not lawyers.

> Question: Does anyone know if there are issues with using DLLs from a Qt5
> static application? I'm a bit worried that some DLL I might want to use
> would depend on libgcc_s_seh-1.dll and then I would end up distributing
> multiple copies of some of the functions in there: one copy would be in the
> DLL and one copy would be in the executable. This might cause some sort of
> problem.
>
Every DLL should depend on libgcc_s_seh-1.dll since
https://github.com/Alexpux/MINGW-packages/commit/abf850d0fe3a07eef11cbef78f727c8f58da8998
. In my experience, there's no middle ground on MinGW-w64 between static
and non-static as far as libgcc* goes. In particular this was true for i686
as I spent a while investigating a bug that turned out to be caused by
double calling of the exception handling table unregistering code for DLLs
linked with -static-libgcc. Some of the details are discussed at
https://www.mail-archive.com/gcc@gcc.gnu.org/msg68284.html (you'll need to
read the whole thread and be wary of some assumptions; Kai and ILT are
reliable). MSYS2 had a discussion on the same subject later at
http://sourceforge.net/p/msys2/mailman/message/32956415/

The Summary is: I strongly discourage linking any DLLs (which should not
have been built with -static-libgcc) with anything that should have been
built with -static-libgcc (e.g. executables created by qt5-static). I
stumbled into this problem due to tcl/tk plugins/shared-libraries being
built with -static-libgcc. Now any time I run into weird things with
programs crashing on exit on i686, this is one of the first things I look
for.

--
Best regards,

Ray

**Comment by DavidEGrayson** [comment]
Ok, thanks for the information, @mingwandroid.

**Comment by DavidEGrayson** [comment]
I found more information here:  http://wiki.qt.io/Qt-5-QLocale

It describes a plan to change Qt5 so it doesn't use ICU on Windows, and only uses it on other platforms.  Does anyone know if this plan was adopted, and whether we can expect to see it in Qt5.6?

I am trying to compile Qt5 with `-no-icu` right now using the scripts here: https://github.com/DavidEGrayson/mingw-packages-deg/tree/master/mingw-w64-qt5-noicu

So I'll know in about 13 hours or so whether it worked.  :smiley_cat:

**Comment by DavidEGrayson** [comment]
The build scripts I mentioned earlier did successfully compile a qt5 package, but for some reason it didn't install to a special directory (e.g. qt-noicu) so its files conflicted with the regular qt5 package.  I didn't test it to see if there was anything else wrong.

On another note: When I compress the 50 MB of DLLs into an installer (MSI) using WiX, the resulting installer is only 22 MB.  That's not _so_ bad.

**Comment by DavidEGrayson** [comment]
From commit 3697c0bb883b9776b1e8dc54c1001bd5d114c348 it looks like @AlexPux is working on the Qt5 package, and he added a `_use_icu` option at the top.  While that option is set to "yes" by default for the shared verison of Qt5, you could set it to "no" to enable some patches that @AlexPux added.  He is also working on opengl=dynamic at the same time, probably to address issue #924.  The commit message says "WIP" so it's not clear if Qt5 can build at the moment.

**Comment by Alexpux** [comment]
Qt5 can't be builded right now with opengl=dynamic as it not support recent version of ANGLE

**Comment by DavidEGrayson** [comment]
Thanks for the information, @AlexPux.  If I changed two lines in the PKGBUILD to set `_opengl=desktop` and `_use_icu=no`, and tried to build the shared variant, do you know if that would work?  I might try that tonight.

**Comment by Alexpux** [comment]
You can try. I still not yet try build without ICU. I add no-icu patches from fedora guys repo

**Comment by DavidEGrayson** [comment]
Thanks for finding those patches and adding them, @AlexPux.  I will try to build it now.  I just noticed that 0123-webkit-commit-151422.patch is already applied by upstream, so we don't need to apply it.

**Comment by DavidEGrayson** [comment]
See #996.

**Comment by DavidEGrayson** [comment]
I successfully built `mingw-w64-i686-qt5` last night and I tested my app with it.  My DLL overhead is down to just 21.4 MB!  So here is how I did it:

1. Check out commit `f7cb02ebfb164ee42d0044c2e9074ad80129e50d` of this repository.
2. Change `_use_icu=yes` to `_use_icu=no` and change `_opengl=dynamic` to `_opengl=desktop`, as shown in the patch below.

~~~~{.patch}
diff --git a/mingw-w64-qt5/PKGBUILD b/mingw-w64-qt5/PKGBUILD
index 1e102cf..ecc35be 100644
--- a/mingw-w64-qt5/PKGBUILD
+++ b/mingw-w64-qt5/PKGBUILD
@@ -37,7 +37,7 @@ else
   _freetype2="-system-freetype"
   _fastbuild="no"
   _ltcg="no"
-  _use_icu=yes
+  _use_icu=no
 fi

 # Thiago's patch doesn't contain the configure script changes
@@ -82,8 +82,8 @@ else
 fi

 #_opengl=angle
-#_opengl=desktop
-_opengl=dynamic
+_opengl=desktop
+#_opengl=dynamic
 _opengl_for_configure="${_opengl}"
~~~~

3. Run `MINGW_INSTALLS=mingw32 makepkg-mingw -s`  This step could take a long time (like 13 hours).
4. Install it in place of the official MSYS2 Qt package using `pacman -U mingw-w64-i686-qt5-5.5.1-4-any.pkg.tar.xz`.  This will replace the Qt5 on your system with the one you just built; obviously this might break some apps, if they somehow depending on Qt5's ICU support.

Does anyone know what ICU actually does in Qt5 and if there are apps that depend on it?

**Comment by mcallegari** [comment]
I think we can close this for 2 reasons:
- some work has been done in the qt5 PKGBUILD file to disable the ICU dependency. Thanks !
- the project maintainers will not provide a ready-made no-ICU version. One has to build Qt himself
