### ISSUE TITLE
Feature Request: SDL_mixer and SDL_net (1.x)

### ISSUE THREAD

**Issue by fabiangreffrath** [Alexpux/MINGW-packages#860]
Hi there,

it seems that the SDL_net library is missing, i.e. the SDL 1.x variant, the SDL 2 variant is there.

Thank you very much!

 - Fabian

**Comment by fabiangreffrath** [comment]
Oh, and SDL_mixer 1.x is also missing. Both libraries are needed to build Chocolate Doom (and ROTT and Wolf4SDL) and probably many other games that have not yet been ported to the SDL2 API.

**Comment by Alexpux** [comment]
Done

**Comment by fabiangreffrath** [comment]
Impressive, thank you!
