### ISSUE TITLE
SDL[2]_mixer: please avoid hard dependencies on backend libraries

### ISSUE THREAD

**Issue by fabiangreffrath** [Alexpux/MINGW-packages#865]
Hi there,

currently, the SDL_mixer libraries are built with support for many sound backends, which is generally a good thing. However, it is dynamically linked against all these libraries which means that they all become hard dependencies of SDL_mixer. This in turn makes it harder to add the SDL_mixer libraries to portable game bundles. Among the dependencies are heavy-weights such as libfluidsynth-1.dll which in turn pulls in libglib-2.0-0.dll and so on.

```
$ objdump.exe -x /mingw32/bin/SDL_mixer.dll | grep DLL
        DLL
 vma:            Hint    Time      Forward  DLL       First
        DLL Name: KERNEL32.dll
        DLL Name: msvcrt.dll
        DLL Name: WINMM.DLL
        DLL Name: libgcc_s_dw2-1.dll
        DLL Name: libFLAC-8.dll
        DLL Name: libfluidsynth-1.dll
        DLL Name: libmikmod-3.dll
        DLL Name: SDL.dll
        DLL Name: smpeg.dll
        DLL Name: libvorbisfile-3.dll

$ objdump.exe -x /mingw32/bin/libfluidsynth-1.dll | grep DLL
        DLL
 vma:            Hint    Time      Forward  DLL       First
        DLL Name: dsound.dll
        DLL Name: KERNEL32.dll
        DLL Name: msvcrt.dll
        DLL Name: USER32.dll
        DLL Name: WINMM.DLL
        DLL Name: WS2_32.dll
        DLL Name: libgcc_s_dw2-1.dll
        DLL Name: libglib-2.0-0.dll
        DLL Name: libportaudio-2.dll
        DLL Name: libsndfile-1.dll
```

To help this situation, there are configure switches like `--disable-music-fluidsynth-shared` which will cause SDL_mixer to `dlopen()` the fluidsynth library like a plugin without carrying around a hard dependency on it. Please consider passing these flags to the `./configure` call. Though, I believe these flags are already the default...?

If this still doesn't work, please consider adding `-Wl,--no-undefined -Wl,--as-needed` to `LDFLAGS` in order to prevent overlinking.

Also, please note that many libraries carry around a dependency on `libgcc_s_dw2-1.dll`, which is another ugly extra-dependency that could be avoided by defaulting to calling `gcc` with `-static-libgcc`

Thank you!

 - Fabian

**Comment by Alexpux** [comment]
Our priority to build shared libraries and we will not build anything with "-static-libgcc"

**Comment by fabiangreffrath** [comment]
I understand the rationale behind avoiding `-static-libgcc`, but the other means I pointed out in my request should really be considered.

**Comment by fabiangreffrath** [comment]
Short update before I have to leave office:
It seems that SDL_mixer's `./configure` script actually tries to find the dynamic libs in order to use them for `dlopen()`, but the function called `find_lib()` inside the `configure` script is too broken on non-Posix systems to find anything useful.

**Comment by fabiangreffrath** [comment]
The following patch against `configure` brings back the ability to `dlopen()` the backend libraries in MinGW:
```
--- SDL_mixer-1.2.12/configure
+++ SDL_mixer-1.2.12.fab/configure
@@ -11850,12 +11850,13 @@
     gcc_bin_path=`$CC -print-search-dirs 2>/dev/null | fgrep programs: | sed 's/[^=]*=\(.*\)/\1/' | sed 's/:/ /g'`
     gcc_lib_path=`$CC -print-search-dirs 2>/dev/null | fgrep libraries: | sed 's/[^=]*=\(.*\)/\1/' | sed 's/:/ /g'`
     env_lib_path=`echo $LIBS $LDFLAGS $* | sed 's/-L[ ]*//g'`
+    env_path=`echo $PATH | sed 's/:/ /g'`
     if test "$cross_compiling" = yes; then
         host_lib_path=""
     else
         host_lib_path="/usr/$base_libdir /usr/local/$base_libdir"
     fi
-    for path in $gcc_bin_path $gcc_lib_path $env_lib_path $host_lib_path; do
+    for path in $gcc_bin_path $gcc_lib_path $env_lib_path $env_path $host_lib_path; do
         lib=`ls -- $path/$1 2>/dev/null | sort | sed 's/.*\/\(.*\)/\1/; q'`
         if test x$lib != x; then
             echo $lib
@@ -13161,6 +13162,9 @@
                     ;;
                 *-*-cygwin* | *-*-mingw32*)
                     fluidsynth_lib=`find_lib "fluidsynth*.dll"`
+                    if test x$fluidsynth_lib = x; then
+                        fluidsynth_lib=`find_lib "libfluidsynth*.dll"`
+                    fi
                     ;;
                 *)
                     fluidsynth_lib=`find_lib "libfluidsynth.so.[0-9]"`
```

**Comment by Alexpux** [comment]
Please create pull request with patch and PKGBUILD modification for SDL*_mixer instead writing this in issue
