### ISSUE TITLE
Odd issue with WIDL and enum pointers

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#869]
I am doing a manual build of the headers-git package and hit an issue (bug?) in widl. It seems that widl does not like the [v1_enum] attribute applied to enums that also define a pointer type (the one I am having issues with is PBDA_EVENT_ID in bdatypes.h).

Has anyone else seen this issue? Is there a fix for it?

The exact error message is "include/bdatypes.h:43: error: 'PBDA_EVENT_ID': [v1_enum] attribute applied to non-enum type"

**Comment by Alexpux** [comment]
You need write bug report to mingw-w64 ML.

**Comment by BrisingrAerowing** [comment]
Oddly it randomly doesn't work. I simply built a new version from the repository which worked straight through. I was using the MinGW-Builds GCC 5.2.0 x86_64 SEH rev0 compilers and bundled tools.

I guess this was reported and fixed after that compiler build was released.
