### ISSUE TITLE
llvm's FileCheck is missing (error while building rustc 1.4.0)

### ISSUE THREAD

**Issue by kryptan** [Alexpux/MINGW-packages#871]
I tried to update rust to 1.4.0, I modified PKGBUILD: changed `pkgver` to `1.4.0` and updated `sha256sums` to `1c0dfdce5c85d8098fcebb9adf1493847ab40c1dfaa8cc997af09b2ef0aa8211`.

When I try to build it it complains during `configure` that FileCheck is missing :

    error: program '/mingw64/bin/FileCheck' is missing, please install it

As I understand FileCheck is part of llvm but it is not installed with `mingw-w64-x86_64-llvm` package.

**Comment by alilee** [comment]
Also missing on ubuntu (aarch64) in llvm-3.6.

**Comment by mingwandroid** [comment]
@alilee I think you want to report that to ubuntu :-)

**Comment by alilee** [comment]
Ha @mingwandroid . Although homebrew does this so doing a bit more examination:
   LLVM executables are installed in /usr/local/opt/llvm/bin. 
   Extra tools are installed in /usr/local/opt/llvm/share/llvm.

**Comment by nodakai** [comment]
As of LLVM 3.8, `cmake ... -D LLVM_INSTALL_UTILS=ON` is required to install `FileCheck` (as `$prefix/bin/FileCheck`)

**Comment by mingwandroid** [comment]
Please make a pull request for this rather than a bug report. They take about the same amount of time but one gives you so much more kudos :-)
