### ISSUE TITLE
Git for Windows

### ISSUE THREAD

**Issue by Sh4rK** [Alexpux/MINGW-packages#873]
Hi!

I see that git for windows is now based on this repo, but having to download it separately is suboptimal in my opinion. What is preventing the upstreaming of the work done in https://github.com/git-for-windows/MINGW-packages?

**Comment by mingwandroid** [comment]
Time.

**Comment by Sh4rK** [comment]
Time ruins everything :(

**Comment by maoueh** [comment]
In the mean time, see https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper

**Comment by maoueh** [comment]
And this issue https://github.com/git-for-windows/git/issues/284 from time to time for progress in this matter.
