### ISSUE TITLE
makepkg -s in pacman: check fails

### ISSUE THREAD

**Issue by cptG** [Alexpux/MINGW-packages#879]
I tried to rebuild the pacman package but makepkg fails in the check step (~44 tests are failing)
I'm rebuilding with the check step disabled (testing with a second install of msys2 so I don't blow my main install with a maybe-broken pacman)... but I'm wondering: do you build pacman from the PKGBUILD yourself? If so: are there other steps I need to take to make the check succeed or is it ok to just skip it?

**Comment by Alexpux** [comment]
It is ok to skip check step.
