### ISSUE TITLE
make qt4 & qt5 coexist

### ISSUE THREAD

**Issue by cptG** [Alexpux/MINGW-packages#880]
Currently qt5 and at4 can't be installed at the same time. The problem:
if I want to develop for qt4 and use qtcreator, pacman -Syu would pull in qt5 as a dependency for qtcreator and this conflicts with qt4.
It would be great if the qt4 package was configured like in Arch Linux such that qt4 and qt5 could coexist next to each other.

**Comment by mingwandroid** [comment]
If you want this feature then do the work.
