### ISSUE TITLE
icu-le-hb

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#881]
As the ICU layout engine (icu-le) is depreciated, a replacement that uses HarfBuzz, [icu-le-hb](https://github.com/behdad/icu-le-hb) was created.

The ICU layoutex library (which is not depreciated) can be built with it, using [these instructions](http://userguide.icu-project.org/layoutengine/paragraph). The process is a bit convoluted, though.

Would it be possible to add a package for this?

**Comment by Alexpux** [comment]
Maybe you do it?

**Comment by Alexpux** [comment]
Also why we need these library?
