### ISSUE TITLE
pycairo configure failure

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#885]
When I run the pycairo configuration process, it fails with the error message "python executable '/mingw64/bin/python3' different from sys.executable '/usr/bin/python3'". Running it with MinGW Python fails at finding the wscript file.

Can someone confirm this? Is there a fix?

**Comment by Alexpux** [comment]
Are you build with PKGBUILD?

**Comment by BrisingrAerowing** [comment]
I wasn't, but I found that it failed well after it spat out that message while trying to run a command with the shell, which was failing due to quoting issues. I ended up download the packages you guys built and installing those.

I hate Waf, as it doesn't spit out much info, and what it does spit out is generally nowhere near where it failed. It took me a good five hours of fiddling to identify where the issue actually was.
