### ISSUE TITLE
mpfr link error

### ISSUE THREAD

**Issue by silentmissile** [Alexpux/MINGW-packages#919]
when I use CGAL to develop some code, the following link error happened, I think the issue exist at MPFR not CGAL

Also I linked both libgmp.a and libgmp.dll.a, but it still happened.

D:\msys64\mingw64\lib\libmpfr.a(clear.o)|| undefined reference to `__gmp_get_memory_functions'|
D:\msys64\mingw64\lib\libmpfr.a(round_prec.o)|| undefined reference to`__gmp_get_memory_functions'|
D:\msys64\mingw64\lib\libmpfr.a(init2.o)|| undefined reference to `__gmp_get_memory_functions'|
D:\msys64\mingw64\lib\libmpfr.a(div.o)|| undefined reference to`__gmpn_divrem'|
D:\msys64\mingw64\lib\libmpfr.a(mulders.o)|| undefined reference to `__gmpn_divrem'|
D:\msys64\mingw64\lib\libmpfr.a(mulders.o)|| undefined reference to`__gmpn_divrem'|
||error: ld returned 1 exit status|

**Comment by elieux** [comment]
Sorry, I'm not familiar with CGAL. Please post steps to reproducing this issue.
