### ISSUE TITLE
pyqt4 install breaks for i686 version

### ISSUE THREAD

**Issue by chaffra** [Alexpux/MINGW-packages#928]
pacman -Su mingw-w64-i686-python2-pyqt4 breaks on msys64 with

error: failed to commit transaction (conflicting files)
/mingw32/share/qt4/qsci/api/python/PyQt4.api exists in both 'mingw-w64-i686-pyqt4-common' and 'mingw
-w64-i686-python2-pyqt4'

**Comment by mingwandroid** [comment]
It's very unlikely that anyone will look into this since it's qt4 and qt5 has been out for a very long time now. If you want it fixed then you will need to supply a patch that fixes it yourself.
