### ISSUE TITLE
python3: Linking with -lpython35 fails

### ISSUE THREAD

**Issue by patrikhuber** [Alexpux/MINGW-packages#931]
I was trying to use Theano from the pip3 repository and everything went well so far except that when executing code, it produces a shell-command like this, which will fail: (I shortened the command a bit)

```
g++.exe -shared -g -O3 [...a lot of flags...] -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -IC:/msys64/mingw64/lib/python3.5/site-packages\numpy\core/include -IC:/msys64/mingw64/include/python3.5m -o out.pyd mod.cpp -LC:/msys64/mingw64/include/libs -LC:/msys64/mingw64/lib -lpython35

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpython35
collect2.exe: error: ld returned 1 exit status
```

It fails because it can't find `-lpython35`:

```
/mingw64/lib $ ls -la | grep libpyth
-r--r--r-- 1 Patrik None   691466 Jul  8 13:11 libpython2.7.dll.a
-rw-r--r-- 1 Patrik None   901416 Oct  8 10:32 libpython3.5.dll.a
-rw-r--r-- 1 Patrik None   901416 Oct  8 10:32 libpython3.5m.dll.a
```

And the following fixes it: `/mingw64/lib $ ln -s libpython3.5.dll.a libpython35.dll.a`

Theano produces this command automatically, so I have no means of changing the `-lpython35` to something else. I think it gathers the appropriate paths and names from the system environment somehow. 

I couldn't find any specific Google hits but other people seem to use the syntax `-lpython35` as well (and not something like `-lpython3.5`) so it looks like it is supposed to work. But I'm not sure if my symlink is the proper fix.

Steps to reproduce:
- In msys2 shell:
  `pacman -S mingw64/mingw-w64-x86_64-python3 mingw64/mingw-w64-x86_64-python3-numpy mingw64/mingw-w64-x86_64-python3-scipy`
- Then in mingw64 shell: `pip3 install Pillow Theano`
- And then run a small hello-world Theano .py script.

**Comment by mingwandroid** [comment]
I made a decision to change MSYS2's MinGW-w64 Python libraries from being called Python35.dll to being called libpython3.5.dll to help avoid any dll conflicts (both at the linking / technical and the naming level).

Pillow or Theano must be making hard-coded assumptions about the name of the Python dll import library. I will try to look at it when I am not so busy.

**Comment by patrikhuber** [comment]
I see! Your decision seems sensible. Both ways will have their disadvantages I guess.

Yep, that's most likely what's going on. Thank you for having a look at it! My symlink-workaround seems to work so far, but it would be great to find a fix for the future and for everybody else that's going to try using theano with msys2-mingw64. msys2 is a really really awesome project by the way. Thank you! :-)

**Comment by lazka** [comment]
Looks like the hardcoding is done here: https://github.com/Theano/Theano/blob/77daa7eb3796802b597ad7d03f219d7a44f42ce6/theano/gof/cmodule.py#L1636

Best to report this upstream if you still care.
