### ISSUE TITLE
makepkg-mingw on gcc package

### ISSUE THREAD

**Issue by DoctorWho11** [Alexpux/MINGW-packages#933]
running makepkg-mingw on the gcc pkgbuild fails 
```
==> ERROR: arch should be an array
```

**Comment by DavidEGrayson** [comment]
This is a bug in Pac-Man.  I think they already fixed it upstream after I reported it but the fix hasn't made it to MSYS.  For now, you should find the line that says `with--arch=` and replace it with `with-ar""ch=` to defeat grep.

**Comment by DoctorWho11** [comment]
@DavidEGrayson You may of lost me, what line in what file?

**Comment by DavidEGrayson** [comment]
The file is the gcc PKGBUILD you mentioned in your question.

**Comment by DoctorWho11** [comment]
that produces an unexpected token in which makepkg-mingw fails on.

**Comment by DavidEGrayson** [comment]
Why not paste the full output from makepkg-mingw or at least the exact error message?

**Comment by DoctorWho11** [comment]
assuming you mean in line 17 where you have arch=('any')

```
 makepkg-mingw
/home/baconator/Documents/MINGW-packages/mingw-w64-gcc-win32/PKGBUILD: line 17: syntax error near unexpected token `'any''
/home/baconator/Documents/MINGW-packages/mingw-w64-gcc-win32/PKGBUILD: line 17: `ar""ch=('any')
```

**Comment by DavidEGrayson** [comment]
No, I didn't mean that.

~~~~{.patch}
diff --git a/mingw-w64-gcc/PKGBUILD b/mingw-w64-gcc/PKGBUILD
index 8c9cb2f..cbaed24 100644
--- a/mingw-w64-gcc/PKGBUILD
+++ b/mingw-w64-gcc/PKGBUILD
@@ -184,7 +184,7 @@ build() {
     --libexecdir=${MINGW_PREFIX}/lib \
     --with-gxx-include-dir=${MINGW_PREFIX}/include/c++/${pkgver} \
     --enable-bootstrap \
-    --with-arch=${_arch} \
+    --with-ar""ch=${_arch} \
     --with-tune=generic \
     --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada \
     --enable-shared --enable-static \
~~~~

**Comment by DoctorWho11** [comment]
gotcha.

**Comment by DoctorWho11** [comment]
basically I'm just doing a win32 threaded gcc, gonna setup a repo for it, main reason is that some people like a slightly faster compiled exe, native win32 threading provides that (mind you execution iirc isn't that much faster, but there are some people that appreciate it)

**Comment by mingwandroid** [comment]
@DoctorWho11 please save yourself the time and effort or get benchmarks to prove this slowness. Intel committed fixes for the only arguably slower part of winpthreads so now it is a very slim wrapper around native win32 threads. There are real issues to fix instead :-)

**Comment by mingwandroid** [comment]
Also, if you rebuild pacman, I committed local fixes for the --with-arch problem already. I thought that Alexey rebuilt since then but I could be mistaken.

**Comment by DoctorWho11** [comment]
@mingwandroid meh, still gonna do it purely because I'm wanting to do a static build anyways of everything and no matter what I use whether it's -static or not, gcc keeps linking in shared libgcc and pthreads so if anything it's still for me.

**Comment by mingwandroid** [comment]
@DoctorWho11 well, feel free of course! I never understand what the big attraction is for static (your rebuild time goes exponential), unless you're making the MSYS2 installer with qt5-static .. but to each their own :-)

**Comment by DoctorWho11** [comment]
@mingwandroid don't tempt me :P and nah, this is for some small projects of mine. vba-m we just prefer linking statically.

**Comment by mingwandroid** [comment]
@DoctorWho11 Sure, so what I do to build static things (which I sometimes do for work) from MSYS2 packages is to just use `pacman --root` to install the necessary stuff library dependencies to a new location, then I remove the .dll.a files, and then build using makepkg-mingw and that way even the dumbest build systems are happy to pick up the static libraries instead of finding the dynamic ones.

Also, we're happy to accept patches that add static libraries to any packages that are missing them, as you know ;-)

**Comment by DoctorWho11** [comment]
@mingwandroid it's typically autotools and cmake that are too stupid to even know what a static lib from a shared one sadly, even when explicit. the only other thing I can think of is to seperate the static from the shared as seperate packages perhaps.

**Comment by mingwandroid** [comment]
Yeah, see my update above regarding making a new MSYS2 env.

I started a project a while back with the explicit goal to make templates to explore how to do all this stuff: https://github.com/mingwandroid/build-system-templates .. it's not finished, not sure when it will be!

.. anyway .. make a new MSYS2 with pacman (it'll re-use your package cache), jump into it, remove the .dll.a files, and then you are good to go, in theory. Paul Moore brought this issue up on the MSYS2 users mailing list a while ago and this suggestion (deleting the .dll.a files) worked well enough for him.

**Comment by mingwandroid** [comment]
I should be clear, the worst dumbness in autotools is in libtool, that thing is all kinds of stupid, then picking holes in autotools is a bit like shooting fish in a barrel .. then again, I pretty much hate all build systems equally and am convinced that over-exposure to any of them leads first to Stockholm Syndrome and later, hatred :-)

**Comment by Alexpux** [comment]
Fixed in latest pacman.
