### ISSUE TITLE
Cannot statically link libcurl

### ISSUE THREAD

**Issue by kryptan** [Alexpux/MINGW-packages#950]
``` c
#include <curl/curl.h>

void main() {
    curl_easy_init();
}
```

If I try to compile my program with

``` bash
gcc -o crl crl.c -static -DCURL_STATICLIB $(pkg-config --libs --cflags --static libcurl)
```

I get a lot of undefined reference errors. But even if I add missing libraries manually there are still missing symbols:

```
$ gcc -o crl crl.c -static -DCURL_STATICLIB $(pkg-config --libs --cflags --static libcurl) -lgnutls.dll -lnettle -lgmp -liconv -lintl -lwinmm
C:/msys64/mingw64/lib\librtmp.a(rtmp.o):(.text+0xeba): undefined reference to `nettle_mpz_get_str_256'
C:/msys64/mingw64/lib\librtmp.a(rtmp.o):(.text+0x111b): undefined reference to `nettle_mpz_set_str_256_u'
C:/msys64/mingw64/lib\librtmp.a(rtmp.o):(.text+0x122a): undefined reference to `nettle_mpz_get_str_256'
C:/msys64/mingw64/lib\libintl.a(relocatable.o):(.text+0x46): undefined reference to `libiconv_set_relocation_prefix'
collect2.exe: error: ld returned 1 exit status
```

**Comment by Alexpux** [comment]
I build it successfully using ````curl-config````
See:
````
gcc crl.c -o crl -DCURL_STATICLIB $(curl-config --static-libs)
````

**Comment by kryptan** [comment]
Your command links only curl as static lib but all of its dependencies are linked dynamically.
What I want is to produce a self-contained executable which doesn't depend on anything except system windows dlls. If I add `-static` and missing libraries:

    gcc crl.c -o crl -static -DCURL_STATICLIB $(curl-config --static-libs)  -lgnutls.dll -lnettle -lgmp -liconv -lintl -lwinmm

then I get the same errors as above.

**Comment by Alexpux** [comment]
Today I'm upload new gnutls package with static libraries. Feel free to test

**Comment by elieux** [comment]
No response. Closing.

**Comment by AndrewBelt** [comment]
I'm still experiencing the problem above. Using `--static` gives

	C:/msys64/mingw32/lib\libcurl.a(libcurl_la-http2.o):(.text+0x1c): undefined reference to `_imp__nghttp2_session_del'
	C:/msys64/mingw32/lib\libcurl.a(libcurl_la-http2.o):(.text+0xde): undefined reference to `_imp__nghttp2_session_want_write'
	C:/msys64/mingw32/lib\libcurl.a(libcurl_la-http2.o):(.text+0x157): undefined reference to `_imp__nghttp2_session_get_stream_user_data'
	C:/msys64/mingw32/lib\libcurl.a(libcurl_la-http2.o):(.text+0x187): undefined reference to `_imp__nghttp2_session_get_stream_user_data'
	...
