### ISSUE TITLE
libwebp and FreeImage DLL version mismatch

### ISSUE THREAD

**Issue by omichel** [Alexpux/MINGW-packages#955]
The current mingw-w64-FreeImage has a dependency in libfreeimage-3.dll to libwebp-5.dll. However, the current mingw-w64-libwebp package doesn't contain libwebp-5.dll, but only libwebp-6.dll. Hence mingw-w64-FreeImage is currently broken. :unamused:

**Comment by omichel** [comment]
Reverting to mingw-w64-x86_64-libwebp-0.4.3-2 from http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libwebp-0.4.3-2-any.pkg.tar.xz fixes the problem.

**Comment by Alexpux** [comment]
Uploaded new packages to solve this.

**Comment by omichel** [comment]
Great. The problem is fixed. Thanks for the quick reaction!
