### ISSUE TITLE
mingw-w64-openscenegraph: Updated to developer release 3.5

### ISSUE THREAD

**Issue by parched** [Alexpux/MINGW-packages#961]
This broke some stuff I am working on. Why not stick with just stable releases (like Arch does)? If someone needs the dev version then maybe that should be a separate package (mingw-w64-openscenegraph-developer)

**Comment by mingwandroid** [comment]
While neither of these suggestions are general solutions to (they won't work for packages with a lot of dependencies) but for this one you can likely get away with it:

1. You probably have the old package in `/var/cache/pacman.d/` that you can install with `pacman -U`
2. Failing that you should be able build the old version yourself, it's easy enough to do, we can help here.
.. in either case you should then put an entry in `/etc/pacman.conf` of `IgnorePkg=mingw-w64-x86_64-OpenSceneGraph` or `IgnorePkg=mingw-w64-i686-OpenSceneGraph`.

How does OpenSceneGraph's versioning scheme work? Is it even for stable and odd for unstable? @Alexpux was 3.5 a dependency for something we wanted to upgrade to?

**Comment by parched** [comment]
Ok yes that will do for myself for now, but I was going to submit osgearth to this repo, the latest version of which is built on the latest stable osg. I will try and patch it for osg 3.5 though. Yes even are "stable releases" odd are "developer releases".

**Comment by parched** [comment]
I have worked around this, so I don't think it is a much of an issue really.

**Comment by mingwandroid** [comment]
Ok, great, I think @Alexpux is on holiday at present.
