### ISSUE TITLE
respose -> response

### ISSUE THREAD

**Issue by argriffing** [Alexpux/MINGW-packages#964]
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-lapack/PKGBUILD#L37
This has to be a typo/bug similar to https://github.com/Alexpux/MINGW-packages/pull/666.

**Comment by preetpalS** [comment]
Fixed in 7f59e68587598f4370d5fa483877a7523931d5a2.

**Comment by elieux** [comment]
Thanks.
