### ISSUE TITLE
Qt Creator can't load Help.dll plugin

### ISSUE THREAD

**Issue by nazar554** [Alexpux/MINGW-packages#967]
Using dependency walker i traced the issue to missing `libwebp-5.dll`.
![pic](https://cloud.githubusercontent.com/assets/12029825/12075291/3c296284-b184-11e5-932f-eeddb6b29e6e.png)
I have `mingw-w64-x86_64-libwebp` installed so running pacman gave me:
```
$ pacman -Ql mingw-w64-x86_64-libwebp
...
mingw-w64-x86_64-libwebp /mingw64/bin/gif2webp.exe
mingw-w64-x86_64-libwebp /mingw64/bin/libwebp-6.dll
...
```
So quick `cp /mingw64/bin/libwebp-6.dll /mingw64/bin/libwebp-5.dll` fixed the problem for me.
I don't know if this dirty hack will continue to work, but it looks like the `qtcreator` package needs a rebuild.

**Comment by mingwandroid** [comment]
It's qt5 that needs to be rebuilt unfortunately. Your hack will see you right until this happens though.

**Comment by elieux** [comment]
Thanks for reporting. The package was rebuilt. Closing this ticket.
