### ISSUE TITLE
Package request: ENet

### ISSUE THREAD

**Issue by qme5400** [Alexpux/MINGW-packages#968]
Please add ENet package for building enet.dll (or libenet.dll): http://enet.bespin.org/

**Comment by qme5400** [comment]
Please review attached PKGBUILD:
[mingw-w64-enet.zip](https://github.com/Alexpux/MINGW-packages/files/76388/mingw-w64-enet.zip)
[LICENSE.ZIP](https://github.com/Alexpux/MINGW-packages/files/76389/LICENSE.ZIP)

**Comment by mingwandroid** [comment]
Can you make a pull request for this please?

**Comment by qme5400** [comment]
done
