### ISSUE TITLE
gdk-pixbuf static library

### ISSUE THREAD

**Issue by jeroenooms** [Alexpux/MINGW-packages#987]
I am looking for `libgdk_pixbuf-2.0.a` however it does not seem to be included with `mingw-w64-x86_64-gdk-pixbuf2` even though the `PKGBUILD` has `--enable-static`. What could be the reason for this? On osx (homebrew [gdk-pixbuf.rb](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gdk-pixbuf.rb)) the static library is included.

**Comment by mingwandroid** [comment]
Thanks for the report @jeroenooms. This should be fixed now if you rebuild the package. I also reported it upstream and submitted the patch at https://bugzilla.gnome.org/show_bug.cgi?id=760369

**Comment by jeroenooms** [comment]
I'm not seeing the patch just yet, did you push it already?

**Comment by mingwandroid** [comment]
Oops, doing 3 things at once! Pushed now.

**Comment by jeroenooms** [comment]
I can build the static library now, but when I link it I get:

```
../windows/rsvg-2.40.12/lib/x64/libgdk_pixbuf-2.0.a(gdk-pixbuf-io.o):(.text+0x1f69): undefined reference to `__imp_g_threads_got_initialized'
```

This seems to be some deprecated glib function?

**Comment by mingwandroid** [comment]
Can you also file bugs on gnome's bugzilla for your issues with MSYS2's gdk/gtk/glib2 packages then post the links here?

**Comment by jeroenooms** [comment]
I'm just not sure they are glib issues because they don't appear on linux/osx. But I can certainly try and ask over there as well.

**Comment by jeroenooms** [comment]
Reported here: https://bugzilla.gnome.org/show_bug.cgi?id=760397

**Comment by mingwandroid** [comment]
Thanks. Since MSYS2 is the, more or less, the official binary distribution channel for gnome on Windows, it is appropriate to report issues upstream.

**Comment by mingwandroid** [comment]
If you can also add links back to github that would also be appreciated!
