### ISSUE TITLE
glib2 unexported variables

### ISSUE THREAD

**Issue by jeroen** [Alexpux/MINGW-packages#988]
I am trying to statically link my application to `librsvg` however it fails to find symbols `__imp_g_ascii_table` and `__imp_g_utf8_skip`. 

These symbols are `GLIB_VAR` types which get defined by `glib2` in `glib-2.0/glib/gstrfuncs.h` and `glib-2.0/glib/gunicode.h` but for some reason not included in the static library.

My full error log:

```
C:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o rsvg.dll tmp.def g_utf8_skip.o rsvg.o strtok_r.o -L../windows/rsvg-2.40.12/lib/x64 -lrsvg-2 -lxml2 -lz -lpangocairo-1.0 -lpango-1.0 -lpangoft2-1.0 -lpangowin32-1.0 -lcairo-gobject -lcairo -lfontconfig -lfreetype -lpng16 -lpixman-1 -lexpat -lharfbuzz -lbz2 -lgdi32 -lz -lcroco-0.6 -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -lgdk_pixbuf-2.0 -lintl -lffi -liconv -lusp10 -ldnsapi -liphlpapi -lshlwapi -lwinmm -lole32 -lws2_32 -LC:/Rbuild/R-devel-win64/extsoft/lib/x64 -LC:/Rbuild/R-devel-win64/extsoft/lib -LC:/PROGRA~1/R/R-EXPE~1/bin/x64 -lR
../windows/rsvg-2.40.12/lib/x64/librsvg-2.a(librsvg_2_la-rsvg-css.o):(.text+0x12de): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/librsvg-2.a(librsvg_2_la-rsvg-io.o):(.text+0xc): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/librsvg-2.a(librsvg_2_la-rsvg-mask.o):(.text+0x37b): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/librsvg-2.a(librsvg_2_la-rsvg-styles.o):(.text+0x2db4): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/librsvg-2.a(librsvg_2_la-rsvg-styles.o):(.text+0x32ea): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/libpangocairo-1.0.a(pangocairo-font.o):(.text+0xe5f): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(fonts.o):(.text+0x88): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(fonts.o):(.text+0x11f9): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(fonts.o):(.text+0x166d): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-context.o):(.text+0x2e): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-context.o):(.text+0x8b7): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-context.o):(.text+0xe78): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-context.o):(.text+0x1990): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-engine.o):(.text+0x1ab): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-engine.o):(.text+0x3a1): more undefined references to `__imp_g_utf8_skip' follow
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-markup.o):(.text+0x10de): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-script.o):(.text+0x9c): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-utils.o):(.text+0x72): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-utils.o):(.text+0xa6): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-utils.o):(.text+0x493): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-utils.o):(.text+0x4da): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-utils.o):(.text+0x5cb): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-utils.o):(.text+0xaeb): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-utils.o):(.text+0xd74): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(break.o):(.text+0x144): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(break.o):(.text+0x278): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(break.o):(.text+0x5aa): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(break.o):(.text+0x1879): more undefined references to `__imp_g_utf8_skip' follow
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(pango-color.o):(.text+0x146): undefined reference to `__imp_g_ascii_table'
../windows/rsvg-2.40.12/lib/x64/libpango-1.0.a(fribidi.o):(.text+0x301): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpangoft2-1.0.a(pangofc-font.o):(.text+0x98c): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpangowin32-1.0.a(pangowin32-shape.o):(.text+0xe64): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpangowin32-1.0.a(pangowin32-shape.o):(.text+0x11b6): undefined reference to `__imp_g_utf8_skip'
../windows/rsvg-2.40.12/lib/x64/libpangowin32-1.0.a(pangowin32-shape.o):(.text+0x125a): undefined reference to `__imp_g_utf8_skip'
collect2.exe: error: ld returned 1 exit status
```

**Comment by mingwandroid** [comment]
My best guess at this is you shouldn't have imports to anything other than things in system DLLs in those static libraries .. librsvg-2.a and libpango-1.0.a are broken.

Those C files have been compiled with incorrect gcc __attribute__ decorators present on the function declarations (i.e. dllexport was present when it should not have been).

**Comment by BrisingrAerowing** [comment]
I noticed this myself and I think the easiest route would be to do two compilations, like you do for GLib itself.

**Comment by manisandro** [comment]
Came across this by chance, but I had the same problem with the Fedora mingw packages. I solved this by doing two compilations, and when doing the static builds, rsvg also needs `-DLIBXML_STATIC -DGLIB_STATIC_COMPILATION`, and pango needs `-DGLIB_STATIC_COMPILATION`. Plus fixes for other issues like multiple definitions of DllMain in glib, gdk-pixbuf, cairo, and possibly others.

**Comment by jeroenooms** [comment]
@manisandro were you successful in creating a working static library for glib? I ended up shipping dll's because of the DllMain conflicts.

**Comment by manisandro** [comment]
@jeroenooms Yep, needed to surround various DllMain declarations/definitions with `#ifdef DLL_EXPORT`, then things worked fine.

**Comment by jeroenooms** [comment]
And it actually works? I got it to build & link at some point but `librsvg` would segfault when using the static glib...  Would you consider submitting your patches to the [mingw-w64-glib2](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-glib2/PKGBUILD) repo?

**Comment by manisandro** [comment]
@jeroenooms I'll tell you in a moment, chasing a compilation error in mingw-cairo.

**Comment by manisandro** [comment]
@jeroenooms Indeed, running is an additional challenge, argh...

    GLib-GObject:ERROR:../../gobject/gtype.c:2752:g_type_register_static: assertion failed: (static_quark_type_flags)

**Comment by jeroenooms** [comment]
Actually I think static linking is broken in glib 2.46, it is not working on osx and linux either. I had to downgrade to glib-2.42.2 to get it to build a static application on osx.

**Comment by manisandro** [comment]
@jeroenooms Some progress via

    diff -rupN glib-2.47.5/glib/glib-init.c glib-2.47.5-new/glib/glib-init.c
    --- glib-2.47.5/glib/glib-init.c	2015-11-09 16:46:06.000000000 +0100
    +++ glib-2.47.5-new/glib/glib-init.c	2016-02-09 16:52:18.859690798 +0100
    @@ -243,14 +243,33 @@ glib_init (void)
      g_quark_init ();
    }
    
    -#if defined (G_OS_WIN32)
    +HMODULE glib_dll = NULL;
    +
    +#if defined (G_HAS_CONSTRUCTORS)
    +
    +#ifdef G_DEFINE_CONSTRUCTOR_NEEDS_PRAGMA
    +#pragma G_DEFINE_CONSTRUCTOR_PRAGMA_ARGS(glib_init_ctor)
    +#endif
    +G_DEFINE_CONSTRUCTOR(glib_init_ctor)
    +
    +static void
    +glib_init_ctor (void)
    +{
    +  glib_init ();
    +#ifdef G_OS_WIN32
    +  g_clock_win32_init ();
    +#ifdef THREADS_WIN32
    +  g_thread_win32_init ();
    +#endif
    +#endif
    +}
    +
    +#elif defined (G_OS_WIN32) && defined (DLL_EXPORT)
    
    BOOL WINAPI DllMain (HINSTANCE hinstDLL,
                          DWORD     fdwReason,
                          LPVOID    lpvReserved);
    
    -HMODULE glib_dll;
    -
    BOOL WINAPI
    DllMain (HINSTANCE hinstDLL,
              DWORD     fdwReason,
    @@ -281,19 +300,6 @@ DllMain (HINSTANCE hinstDLL,
      return TRUE;
    }
    
    -#elif defined (G_HAS_CONSTRUCTORS)
    -
    -#ifdef G_DEFINE_CONSTRUCTOR_NEEDS_PRAGMA
    -#pragma G_DEFINE_CONSTRUCTOR_PRAGMA_ARGS(glib_init_ctor)
    -#endif
    -G_DEFINE_CONSTRUCTOR(glib_init_ctor)
    -
    -static void
    -glib_init_ctor (void)
    -{
    -  glib_init ();
    -}
    -
    #else
    # error Your platform/compiler is missing constructor support
    #endif
    diff -rupN glib-2.47.5/gobject/gtype.c glib-2.47.5-new/gobject/gtype.c
    --- glib-2.47.5/gobject/gtype.c	2015-11-16 19:17:52.000000000 +0100
    +++ glib-2.47.5-new/gobject/gtype.c	2016-02-09 16:47:10.803608611 +0100
    @@ -4459,7 +4459,19 @@ gobject_init (void)
      _g_signal_init ();
    }
    
    -#if defined (G_OS_WIN32)
    +#if defined (G_HAS_CONSTRUCTORS)
    +#ifdef G_DEFINE_CONSTRUCTOR_NEEDS_PRAGMA
    +#pragma G_DEFINE_CONSTRUCTOR_PRAGMA_ARGS(gobject_init_ctor)
    +#endif
    +G_DEFINE_CONSTRUCTOR(gobject_init_ctor)
    +
    +static void
    +gobject_init_ctor (void)
    +{
    +  gobject_init ();
    +}
    +
    +#elif defined (G_OS_WIN32) && defined (DLL_EXPORT)
    
    BOOL WINAPI DllMain (HINSTANCE hinstDLL,
                          DWORD     fdwReason,
    @@ -4484,18 +4496,6 @@ DllMain (HINSTANCE hinstDLL,
      return TRUE;
    }
    
    -#elif defined (G_HAS_CONSTRUCTORS)
    -#ifdef G_DEFINE_CONSTRUCTOR_NEEDS_PRAGMA
    -#pragma G_DEFINE_CONSTRUCTOR_PRAGMA_ARGS(gobject_init_ctor)
    -#endif
    -G_DEFINE_CONSTRUCTOR(gobject_init_ctor)
    -
    -static void
    -gobject_init_ctor (void)
    -{
    -  gobject_init ();
    -}
    -
    #else
    # error Your platform/compiler is missing constructor support
    #endif

and http://stackoverflow.com/questions/1202494/why-doesnt-attribute-constructor-work-in-a-static-library#

**Comment by manisandro** [comment]
To wrap up, the above patch and compiling with `--with-threads=posix` results in a working statically linked executable (looks like the win32 threads implementation is broken with recent glib2, regardless of whether used with statically or dynamically linked glib). In short, the Fedora mingw-glib2-2.47.5-1 [1] with the patch posted at [2] works.

[1] http://pkgs.fedoraproject.org/cgit/rpms/mingw-glib2.git/tree/
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1306047

**Comment by jeroenooms** [comment]
Thanks. Did you post this upstream to the glib folks?

Just out of curiosity: I'm completely unfamiliar with the Feodra mingw effort. Are the static/dynamic libraries that you produce compatible with native builds? Which exception/threading model of mingw-w64 are you using? Does cross-compiling from Fedora require different patches or is it very similar to msys2?

**Comment by manisandro** [comment]
Just found an upstream glib ticket [1], looks like there is a memory leak issue when using constructors - but at least it compiles and runs.

About compatibility: First issue is compiler C++ ABI, and since Fedora is compiling with GCC6 which defaults to -std=c++11. Exception model is sjlj. Not really sure about threading model.

About the build procedure (I assume you mean this), I'm not aware of any patching necessary to the code in general.

[1] https://bugzilla.gnome.org/show_bug.cgi?id=698118

**Comment by manisandro** [comment]
Previous patch was bogous (and it was it's fault that win32 threads were broken), should be

    diff -rupN glib-2.47.5/glib/glib-init.c glib-2.47.5-new/glib/glib-init.c
    --- glib-2.47.5/glib/glib-init.c	2015-11-09 16:46:06.000000000 +0100
    +++ glib-2.47.5-new/glib/glib-init.c	2016-02-10 01:45:06.853253602 +0100
    @@ -245,12 +245,14 @@ glib_init (void)
    
    #if defined (G_OS_WIN32)
    
    +HMODULE glib_dll = NULL;
    +
    +#if defined (DLL_EXPORT)
    +
    BOOL WINAPI DllMain (HINSTANCE hinstDLL,
                          DWORD     fdwReason,
                          LPVOID    lpvReserved);
    
    -HMODULE glib_dll;
    -
    BOOL WINAPI
    DllMain (HINSTANCE hinstDLL,
              DWORD     fdwReason,
    @@ -260,11 +262,6 @@ DllMain (HINSTANCE hinstDLL,
        {
        case DLL_PROCESS_ATTACH:
          glib_dll = hinstDLL;
    -      g_clock_win32_init ();
    -#ifdef THREADS_WIN32
    -      g_thread_win32_init ();
    -#endif
    -      glib_init ();
          break;
    
        case DLL_THREAD_DETACH:
    @@ -281,7 +278,10 @@ DllMain (HINSTANCE hinstDLL,
      return TRUE;
    }
    
    -#elif defined (G_HAS_CONSTRUCTORS)
    +#endif /* defined (DLL_EXPORT) */
    +#endif /* defined (G_OS_WIN32) */
    +
    +#if defined (G_HAS_CONSTRUCTORS)
    
    #ifdef G_DEFINE_CONSTRUCTOR_NEEDS_PRAGMA
    #pragma G_DEFINE_CONSTRUCTOR_PRAGMA_ARGS(glib_init_ctor)
    @@ -291,6 +291,12 @@ G_DEFINE_CONSTRUCTOR(glib_init_ctor)
    static void
    glib_init_ctor (void)
    {
    +#if defined (G_OS_WIN32)
    +  g_clock_win32_init ();
    +#ifdef THREADS_WIN32
    +  g_thread_win32_init ();
    +#endif /* defined (THREADS_WIN32) */
    +#endif /* defined (G_OS_WIN32) */
      glib_init ();
    }
    
    diff -rupN glib-2.47.5/gobject/gtype.c glib-2.47.5-new/gobject/gtype.c
    --- glib-2.47.5/gobject/gtype.c	2015-11-16 19:17:52.000000000 +0100
    +++ glib-2.47.5-new/gobject/gtype.c	2016-02-10 01:45:02.735174154 +0100
    @@ -4459,7 +4459,19 @@ gobject_init (void)
      _g_signal_init ();
    }
    
    -#if defined (G_OS_WIN32)
    +#if defined (G_HAS_CONSTRUCTORS)
    +#ifdef G_DEFINE_CONSTRUCTOR_NEEDS_PRAGMA
    +#pragma G_DEFINE_CONSTRUCTOR_PRAGMA_ARGS(gobject_init_ctor)
    +#endif
    +G_DEFINE_CONSTRUCTOR(gobject_init_ctor)
    +
    +static void
    +gobject_init_ctor (void)
    +{
    +  gobject_init ();
    +}
    +
    +#elif defined (G_OS_WIN32) && defined (DLL_EXPORT)
    
    BOOL WINAPI DllMain (HINSTANCE hinstDLL,
                          DWORD     fdwReason,
    @@ -4484,18 +4496,6 @@ DllMain (HINSTANCE hinstDLL,
      return TRUE;
    }
    
    -#elif defined (G_HAS_CONSTRUCTORS)
    -#ifdef G_DEFINE_CONSTRUCTOR_NEEDS_PRAGMA
    -#pragma G_DEFINE_CONSTRUCTOR_PRAGMA_ARGS(gobject_init_ctor)
    -#endif
    -G_DEFINE_CONSTRUCTOR(gobject_init_ctor)
    -
    -static void
    -gobject_init_ctor (void)
    -{
    -  gobject_init ();
    -}
    -
    #else
    # error Your platform/compiler is missing constructor support
    #endif

**Comment by jeroenooms** [comment]
@manisandro are you still working on this? Do you have an updated patch for to `mingw-w64-glib2` 2.48.1 ?

**Comment by manisandro** [comment]
@jeroenooms this should work:
https://smani.fedorapeople.org/glib-prefer-constructors-over-DllMain.patch

**Comment by jeroenooms** [comment]
@manisandro I found that we need to fix the same problem in `gdk-pixbuf`. See https://github.com/Alexpux/MINGW-packages/issues/1611

**Comment by manisandro** [comment]
@jeroenooms https://smani.fedorapeople.org/gdk-pixbuf_static.patch

**Comment by jeroenooms** [comment]
@manisandro wow we should really coordinate efforts to not duplicate this research/patches in msys2 and fedora...  do you also have patches for `librsvg`?

**Comment by manisandro** [comment]
@jeroenooms It would be best to push the stuff upstream, but I haven't yet managed to do so. For rsvg: just pass

     -DLIBXML_STATIC -DGLIB_STATIC_COMPILATION

in the CPPFLAGS.

**Comment by manisandro** [comment]
@jeroenooms I've uploaded the package sources I'm using:

https://smani.fedorapeople.org/mingw/

In each folder, there are the spec + patches, and in particular one patch (i.e. 0001-Enable-static-build.patch or 0001-Fix-static-library.patch) which documents all the changes compared to the current Fedora package).

**Comment by jeroenooms** [comment]
Awesome. I wish I would have found this before. Hopefully @mingwandroid or @Alexpux will consider adopting your patches :)

**Comment by mingwandroid** [comment]
@jeroenooms, @manisandro, could you please make a PR with the patches?

**Comment by lazka** [comment]
Has this been fixed in the meantime?

**Comment by jeroen** [comment]
Yes. To static link to glib2 you need to compile with `-DGLIB_STATIC_COMPILATION` and then it works.
