### ISSUE TITLE
LLVMConfig.cmake variables are incorrect

### ISSUE THREAD

**Issue by baconator** [Alexpux/MINGW-packages#990]
For the mingw-w64-x86_64-llvm (and probably the 32 bit package, too), it looks like LLVM_INCLUDE_DIRS, LLVM_LIBRARY_DIRS, LLVM_CMAKE_DIR, and LLVM_TOOLS_BINARY_DIR are not pointing to the correct directories (e.g. D:/develop/scripts/mingw-w64-clang/src/build-x86_64/./bin instead of C:/msys64/mingw64/bin). Unfortunately, I'm unfamiliar with both pacman and LLVM's build process, so my current workaround is to just rename the paths :| thoughts?

**Comment by DavidEGrayson** [comment]
I added a feature to makepkg to warn about that, but that LLVM package was built back in July before my feature was added: https://github.com/Alexpux/MSYS2-pacman/pull/19

**Comment by lrs-123** [comment]
I have also had this issue after building llvm/clang in the Msys2 package manager. LLVMconfig.cmake contains these (non-existent) directories).

    # LLVM_BUILD_* values available only from LLVM build tree.
    set(LLVM_BUILD_BINARY_DIR "D:/develop/scripts/mingw-w64-clang/src/build-x86_64")
    set(LLVM_BUILD_LIBRARY_DIR "D:/develop/scripts/mingw-w64-clang/src/build-x86_64/./lib")
    set(LLVM_BUILD_MAIN_INCLUDE_DIR "D:/develop/scripts/mingw-w64-clang/src/llvm3.7.0.src/include")
    set(LLVM_BUILD_MAIN_SRC_DIR "D:/develop/scripts/mingw-w64-clang/src/llvm-3.7.0.src")

I am using llvm/clang version 3.7.0-9 :

    $ pacman -Qs llvm
    local/mingw-w64-x86_64-clang 3.7.0-9
        C language family frontend for LLVM
    local/mingw-w64-x86_64-llvm 3.7.0-9
        Low Level Virtual Machine (mingw-w64)
