### ISSUE TITLE
SQLite 3.10.0

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MINGW-packages#994]
Are you considering updating to the newest SQLite?

I found a bug where the configure script couldn't find readline.

The code in the script was as follows:

```shell
for ac_lib in '' edit; do
  if test -z "$ac_lib"; then
    ac_res="none required"
  else
```
and I had to change it to:
```shell
for ac_lib in readline edit; do
  if test -z "$ac_lib"; then
    ac_res="none required"
  else
```
to make it work.

The offending line is at line 12994 of the configure script. I am not sure why it was that way, but I suspect a bug in the autoconf version the SQLite project used to generate the script.

**Comment by Alexpux** [comment]
Create pull request to update sqlite

**Comment by BrisingrAerowing** [comment]
I ended up encountering another bug with the makefile generation causing it to try and reference editline instead of readline. I couldn't figure out why it did that. I fixed it by changing -DHAVE_EDITLINE in the makefile to -DHAVE_READLINE.

I'll have to go back and see if just running autoreconf fixes the issue.

**Comment by BrisingrAerowing** [comment]
I figured out the issue. In SQLite 3.10.0, editline is the default and --disable-editline and --enable-readline need to be passed to configure.

I'll do the changes and submit a pull request.

**Comment by BrisingrAerowing** [comment]
Pull request submitted.
